### ISSUE TITLE
mput: Operation not supported: 405 Method Not Allowed (PUT)

### ISSUE THREAD

**Issue by dheeraj86mathur** [rear/rear#1005]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): rear.x86_64 0:1.17.2-1.el6
* OS version (cat /etc/rear/os.conf or lsb_release  -a): rhel 6.7
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): 
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="http://abcd.1234.partners/"
OUTPUT_URL="http://abcd.1234.partners/"
NETFS_KEEP_OLD_BACKUP_COPY=y
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/mnt' '/media' '/var/crash')

* Brief description of the issue
With above setting, I have also installed lftp, so that is not the problem now. 
I am getting below error messages : 
mput: Operation not supported: 405 Method Not Allowed (PUT)

Also, how can I use sftp instead of lftp. Do i need to specify credentials for lftp or sftp somewhere ?

* Work-around, if any
not yet.

**Comment by gozora** [comment]
Just a guess, but this loos like PUT method is not allowed on you web server ;-).
So maybe not a ReaR issue at all?

**Comment by gdha** [comment]
The following combination is not allowed:
````
BACKUP=NETFS
BACKUP_URL="http://abcd.1234.partners/"
````
The `http` does only work with the `OUTPUT_URL`. Select a supported transport method for the BACKUP_URL - see the rear man page https://github.com/rear/rear/blob/master/doc/rear.8.adoc

**Comment by jsmeix** [comment]
I think with https://github.com/rear/rear/issues/1005#issuecomment-248541753
this issue can be closed.

FYI:
See also https://github.com/rear/rear/issues/1003
I did not notice the invalid BACKUP_URL="http://..." therein.
