### ISSUE TITLE
"Relax-and-Recover" or "Relax and Recover" that is the question

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1008]
In current rear code I find
58 times "Relax and Recover" and
1 time "Relax and recover".

@gdha 
Is there a reason to write Relax-and-Recover
sometimes as "Relax and Recover"?

If not, I could fix all misspelled forms to Relax-and-Recover.

**Comment by jsmeix** [comment]
I found some more:
relax-and-recover
Relax-and-recover
Relax-and-Recovery

**Comment by gdha** [comment]
@jsmeix **Relax-and-Recover** should be the only one IMHO. @schlomo  what is your opinion?

**Comment by schlomo** [comment]
+1, the dashes make it a term and not a sentence.

Am 22.09.2016 6:09 nachm. schrieb "gdha" <notifications@github.com>:

**Comment by jsmeix** [comment]
O.k.
I will correct all misspelled forms to Relax-and-Recover.

**Comment by jsmeix** [comment]
See if https://github.com/rear/rear/pull/1009 is o.k.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1009 merged
this issue is fixed.
