### ISSUE TITLE
After recover, NW Device Name is changed

### ISSUE THREAD

**Issue by kodiss** [rear/rear#1020]
* rear version (/usr/sbin/rear -V):1.18 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): OS_VENDOR =SUSE_LINUX, OS_VESION=11 (SUSE11SP4)
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
ISO_MKISOFS_BIN=/usr/bin/ebiso
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://NFS_IP/hanabackup/osbackup
NETFS_KEEP_OLD_BACKUP_COPY=yes
BACKUP_PROG_ARCHIVE="osbackup_$(hostname)"
EXCLUDE_VG=( 'vg_data1' 'vg_log1' 'vg_shared1' 'vg_usrsap' 'vg_usrsap1' )
EXCLUDE_MOUNTPOINTS=( '/usr/sap' '/hana/shared' '/hana/log' '/hana/data' '/usr/sap/HMP' '/hanabackup' )
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "fs:/usr/sap" "fs:/hana/shared" "fs:/hana/log" "fs:/hana/data" "fs:/usr/sap/HMP" "fs:/hanabackup" )
EXCLUDE_BACKUP=('/dev/shm/*' '/var/crash/*' '/hana/*' '/hanabackup/*' '/sysadmin/*')
USING_UEFI_BOOTLOADER=1
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y

* Brief description of the issue
  - When i boot using the ISO, NW Device name is changed from p12XXXX to ethX
    so during the recover, i set the IP by myself.

   After complete to recover, i reboot.
   But after reboot, NW Device name is still ethX.

   Please tell me how to fix it.
   Thank you and Best regards.

* Work-around, if any

**Comment by gdha** [comment]
@kodiss The usage of biosdevname can be enforced on every hardware with "biosdevname=1". If the BIOS has no support, no network interface names are renamed. See https://www.suse.com/releasenotes/x86_64/SUSE-SLES/11-SP3/#fate-311333
Or, see also issue #951 
You could try to define `KERNEL_CMDLINE="biosdevname=1"` in the `/etc/rear/local.conf` file and see what happens (the `biosdevname` executable is already copied to the ramdisk if available). So, be sure it is on your system of course.

**Comment by kodiss** [comment]
Thank you for you support, I also know about biosdevname.
But i don't know the option for rear.

Thank you so much!

**Comment by gdha** [comment]
@kodiss I would appreciate feedback if what I proposed actually worked or not?

**Comment by kodiss** [comment]
unfortunately, I don't have enough time for test because this system will be opend for our customer.
I'm sorry but i don't forget your help.
Thank you.
