### ISSUE TITLE
BUG making the script 20_partition_layout.sh

### ISSUE THREAD

**Issue by DavidNogueraBuxeda** [rear/rear#1021]
- rear version (/usr/sbin/rear -V):
  Relax-and-Recover 1.18 / Git
- OS version (cat /etc/rear/os.conf or lsb_release  -a):
  OS_VENDOR=RedHatEnterpriseServer
  OS_VERSION=6
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
  I execute `/usr/sbin/rear -vD mkbackup -c /etc/rear/conf_dp/` I have attached the content in the file site.conf inside the directory
  [site.conf.txt](https://github.com/rear/rear/files/505892/site.conf.txt)
- Brief description of the issue
  When the rear it's doing this script I receive a lot of bugiferror and doesn't stop never: `/usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh`
  type of errors:

```
+++ BugIfError 'Empty string passed to get_device_name'
++ BugIfError 'Function get_version could not detect parted version.'
+++ BugIfError 'Empty string passed to get_device_name'
+++ BugIfError 'Could not determine size of disk sda, please file a bug.
```

The script is doing all the time this checks.

```
+++ for device in '/dev/mapper/*'
++++ dmsetup info -c --noheadings -o major,minor asm_teb01des_sys2_001
+++ mapper_number=253:56
+++ '[' 70:768 = 253:56 ']'
+++ for device in '/dev/mapper/*'
++++ dmsetup info -c --noheadings -o major,minor asm_teb01des_sys2_001p1
+++ mapper_number=253:57
+++ '[' 70:768 = 253:57 ']'
+++ for device in '/dev/mapper/*'
++++ dmsetup info -c --noheadings -o major,minor asm_tsb01des_data_003
+++ mapper_number=253:119
+++ '[' 70:768 = 253:119 ']'
+++ for device in '/dev/mapper/*'
++++ dmsetup info -c --noheadings -o major,minor asm_tsb01des_data_003p1
+++ mapper_number=253:120
+++ '[' 70:768 = 253:120 ']'
+++ for device in '/dev/mapper/*'
++++ dmsetup info -c --noheadings -o major,minor asm_tsb01int_data_002
+++ mapper_number=253:427
+++ '[' 70:768 = 253:427 ']'
```

[rear-tsbora1d.txt](https://github.com/rear/rear/files/505910/rear-tsbora1d.txt)
- Work-around, if any
  None, it 's the first server that I had problems to do the iso image.

**Comment by gdha** [comment]
Is related to issue #721 - for an in-depth analysis of this particular case consider the options mentioned on page http://relax-and-recover.org/support/sponsors
