### ISSUE TITLE
linux redhat booting problem

### ISSUE THREAD

**Issue by satelitexp** [rear/rear#1032]
I was trying to install ldap on the server and something happened and I can not boot the server any more,  I get the following error.  Can you provide some advice how to fix this?

telinit: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
init: rcS post-stop process (47) terminated with status 1

**Comment by gozora** [comment]
Hi,

Check this: https://github.com/rear/rear/issues/590

**Comment by satelitexp** [comment]
Unfortunately I can not boot the server and so I have no way of editing anything on the server.  Any other suggestions?

**Comment by gozora** [comment]
If you are using ISO for booting.

1. Mount ISO on some other (possibly Linux) machine

2. [Edit](http://www.thegeekstuff.com/2009/07/how-to-view-modify-and-recreate-initrd-img) initrd.cgz (check if /etc/passwd /etc/nsswitch.conf are present if not add them)

3. Re-create ISO with new initrd.cgz

4. Try to boot with new ISO

**Comment by satelitexp** [comment]
I am running on a linux machine with redhat 6.6 and I do not think I am using ISO for booting

**Comment by gozora** [comment]
Hmm, maybe i've just misunderstood. Can you explain one more time in more detail what is your problem, and how does ReaR fit into it?

**Comment by gdha** [comment]
@satelitexp Sorry - I do not see in your description what it has to do with ReaR? Perhaps contact your RedHat representative instead as it seems to be an software issue.

**Comment by satelitexp** [comment]
I was installing ldap on the linux machine and when i tried to restart the machine it would not reboot

**Comment by gozora** [comment]
Well, then I have to agree with @gdha, that this issue have nothing to do with ReaR and you should contact your OS vendor.

**Comment by jsmeix** [comment]
Not a Relax-and-Recover issue => closing it.
