### ISSUE TITLE
"rear" or "Rear" or "ReaR" or "REAR" that is the question

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1033]
This issue is related to https://github.com/rear/rear/issues/1008
but now it is about the right spelling for the abbreviation:

In current master code I find:

<pre>
rear (451 times)
Rear (9 times)
ReaR (13 times)
REAR (27 times)
</pre>

What is the officially right spelling?

My personal preference would be
either plain simple "rear"
or (because "rear" is a normal English word and
not a proper name) alternatively "Rear" to make it
a proper name.

Because I am lazy I would prefer "rear" over "Rear"
so that I do not need to fix it at hundreds of places.

**Comment by schlomo** [comment]
If Relax-and-Recover is the official name then I would think ReaR to be the official abbreviation. IMHO followed by REAR. Under no circumstances should we write plain rear because that might lead to unpleasant surprises with English.

**Comment by jsmeix** [comment]
Only my personal opinion:

I think nowadays camel case as in "ReaR" is considered
to be outdated or even to be old-fogyish or ugly.

If I remember correctly some text writers and journalists
refuse camel case spelling and use their own "right" way
according to their own opinion of what "right" is.

Furthermore I myself find it hard to always type "ReaR"
or even "REAR" ( the latter looks like shouting
but is in perfect compliance with SUSE ;-)

Regardless what the reasons are I think the
end-result is various kind of wrong spellings.

Therefore I would prefer a simple spelling that is
automatically done right by usual people.

The usual English names spelling would be "Rear",
cf. 'GNU Tar'
https://www.gnu.org/software/tar/

I think many Unix tools also use normal English
lowercase words as their name, cf 'tar'
https://en.wikipedia.org/wiki/Tar_%28computing%29

The official logo does not have "ReaR" but "REAR".
The font is all uppercase glyphs.
The two middle glyphs 'E' and 'A' are only smaller
but they are no lowercase glyphs 'e' and 'a'.
I know about "small caps" fonts, cf
https://en.wikipedia.org/wiki/Small_caps
but even if the font in the official logo
is actually a small caps font, I assume
nobody would recognize this - i.e. I assume
everybody would read it as "REAR".

My personal summary:

Currently I think
I would like "rear" most (plain and simple)
then "Rear" (normal English name spelling)
and last "REAR" (currently accepted spelling for
abbreviation of longer names)
but I do not like the camel case spelling.

For the fun of it:
Initially it was "S.u.S.E"
which got changed to "SuSE"
which got changed to "SUSE"
but often it is spelled "Suse" by non-SUSE people,
let's se if at the very end "Suse" becomes official ;-)

**Comment by gozora** [comment]
I like **ReaR**, because if you are using it in text, it evokes it is something else then "back part of something..."

Didn't know it is called "camel case" :+1:

**Comment by jsmeix** [comment]
Ah!
Good point - "ReaR" looks less than "rear", "Rear", or "REAR"
like the English word for "back part of something... ".
Also for me the abbreviation of "Relax-and-Recover"
is a bit unfortunate English word ;-)

**Comment by jsmeix** [comment]
My current understanding is that
meanwhile "ReaR" has most agreement
(I changed my opinion since https://github.com/rear/rear/issues/1033#issuecomment-255071562).

In
https://en.opensuse.org/SDB:Disaster_Recovery
I changed 'rear' to 'ReaR' and I explained both spellings in
https://en.opensuse.org/SDB:Disaster_Recovery#Disaster_recovery_with_Relax-and-Recover_.28ReaR.29
as follows:
<pre>
Relax-and-Recover is abbreviated ReaR
(often misspelled 'Rear' or 'rear').
Regarding Relax-and-Recover the word 'rear' is
mainly used when the program /usr/sbin/rear is meant
(e.g. programm calls like "rear mkbackup" and
"rear recover") and in ReaR file and directory
names (e.g. /etc/rear/local.conf). Also RPM package
names are usually lowercase so that ReaR RPM
packages are named 'rear'.
</pre>

If there is no objection I like to close this issue
and open a new issue that I fix wrong spellings
when Relax-and-Recover is abbreviated to make
the texts in the ReaR 2.0 release look well.

**Comment by jsmeix** [comment]
If you like, you may read the whole
https://en.opensuse.org/SDB:Disaster_Recovery
and check if you agree with my usage of 'ReaR' versus 'rear'.

**Comment by gdha** [comment]
@jsmeix Ok let us use **ReaR** as official abbreviation for Relax-and-Recover and use **rear** to point to the RPM package or script.

**Comment by jsmeix** [comment]
The actual spelling check and fixex happens via
https://github.com/rear/rear/issues/1086
