### ISSUE TITLE
Add an automated test that script names match the new 3-digit_ scheme

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1054]
Since https://github.com/rear/rear/pull/1053
is merged all numbered scripts must now match
the new 3-digit_ scheme because the adapted
SourceStage function in framework-functions.sh
now only works for 3-digit names.

Furthermore according to
https://github.com/rear/rear/pull/1022#issuecomment-255676605
that reads (excerpt)

<pre>
numbers 01 and 99 are never used by ReaR so that
those numbers are always reserved for user scripts
</pre>

ReaR 3-digit_ scripts should not be 000_\* or 999_*
i.e. ReaR 3-digit_ scripts should never use the edges
of the 000..999 3-digit range so that the edges are kept
always free to be used by users for their own scripts.

Hereby I ask for an automated test that is run
for each pull request that checks that script names
with leading numbers match the 3-digit_ scheme
and that at least 000_\* or 999_\* are forbidden.

Perhaps we may also forbid more numbers to always
have free numbers for user scripts.

For example ReaR 3-digit_ scripts may never use
two subsequent numbers e.g. 123_this.sh and 124_that.sh
so that between each two ReaR 3-digit_ scripts there is
always at least one free number where a user can insert
his own script.

@gdha 
I assign it to you because I do not know
how to add automated test.

**Comment by gdha** [comment]
@jsmeix could be a good idea to verify if everything is still working - I noticed lots of `chmod` actions during my last commit - I cannot remember I changed anything on the security mode level, did you?

**Comment by jsmeix** [comment]
I did not actively change any owner/group/permission settings
of ReaR files and I am not aware that I changes something accidentally.

I think your two latest commits
https://github.com/rear/rear/commit/64535e0d3a76d8688bd47372fdd34c1b40c5849a
and
https://github.com/rear/rear/commit/df8c92a0bfb27669340c35e8d8b05b0cc55fe8f3
broke things, see
https://github.com/rear/rear/issues/1150

**Comment by gdha** [comment]
@jsmeix should be better now

**Comment by jsmeix** [comment]
Now it looks perfectly o.k.
