### ISSUE TITLE
mkrescue error; "ERROR: No restore job defined in Bareos for"  

### ISSUE THREAD

**Issue by brockshort** [rear/rear#1072]
rear version 1.19 with bareos 16.2.4 on debian 8 using the following local.conf 

OUTPUT_URL=/mnt/x 
BACKUP=BAREOS 
BAREOS_CLIENT=bareos-fd

runnig rear -v mkrescue results in "ERROR: No restore job defined in Bareos for server_01"

also initially complained about not finding bareos-fd.conf so I manually copied it to the /etc/bares from /etc/bareos/bareos-fd.d/client/ 

I also tried previous version of rear1.17 with same result, it seams some issues related to the new bareos release and the new directory structure for configuration files. I also tried copy bareos-dir.conf to /etc/bareos from /etc/bareos/bareos-dir.d/director, and than populating it with all my jobs including the default "Restore Files" job yet I still get the error.

# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Brief description of the issue
* Work-around, if any

**Comment by gdha** [comment]
You should follow a REAR workshop sometimes (see http://osbconf.org/workshops/). Well, your problem might be fixed when you use the config file as shown at https://github.com/rear/rear-workshop-osbconf-2016/blob/master/rear-configs/local-with-bareos.conf
Pay attention to the last 2 lines (these are in comment, but that was the exercise to understand the issue).

**Comment by brockshort** [comment]
I should like to go over the workshops, as for my issue manually defining the restore job name and client fileset as your example suggested does indeed fix my problem. That is the rescue creation process completed successfully Thank you.
