### ISSUE TITLE
boot rear rescue ISO Centos 7 kernel panic

### ISSUE THREAD

**Issue by urobasa** [rear/rear#1093]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

Relax-and-Recover 1.17.2
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
copy default config, and set NETFS
ISO
and nfs path

* Brief description of the issue
kernel panic on boot of any hardware

* Work-around, if any
if site.conf do not copied of default conf, and add to site.conf only 3 lines(NETFS,ISO,nfs path)
rear iso scucefull boot!

![cam00567](https://cloud.githubusercontent.com/assets/6368725/20754188/3e0c72b2-b723-11e6-9426-66800a495909.jpg)

**Comment by gozora** [comment]
Hi, 
Maybe code I've added in https://github.com/rear/rear/commit/b81693f27a41482ed89da36a9af664fe808f8186 will fix this. 
Can you try to upgrade to ReaR 1.19?

V.

**Comment by urobasa** [comment]
ok, upgrade to 1.19 planned

**Comment by jsmeix** [comment]
@urobasa 
because you closed it I assume with ReaR 1.19 is works for you.

@gozora 
as always many thanks for your continuous valuable help!

**Comment by gozora** [comment]
@jsmeix I had this problem "cached" so not a big deal ;-)

**Comment by urobasa** [comment]
1.19 work boot iso Thursday, 01 December 2016, 05:21PM +0300 from Vladimir Gozora  notifications@github.com :
