### ISSUE TITLE
mdadm do not restored on new hardware

### ISSUE THREAD

**Issue by urobasa** [rear/rear#1094]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 1.19
* OS version (cat /etc/rear/os.conf or lsb_release  -a): Centos 7 x64
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
BACKUP=NETFS
OUTPUT=ISO
BACKUP_URL=nfs://site/mnt/storage3/bak
* Brief description of the issue
On backup server enabled intel raid mdadm (mirror)
On new server does not have intel raid
after mapping 2 disk rear stop on error - An error occurred during layout recreation
partitions on mapped disks created with the type of Linux rather than the type of raid autodetection
![2016-12-01 13-11-08](https://cloud.githubusercontent.com/assets/6368725/20790677/d6d8c25c-b7d2-11e6-9dd2-977998aa9b16.png)

**Comment by gdha** [comment]
It has to do with the `--metadata=imsm` Intel Raid - I have heard it before ReaR cannot cope with it. Sorry, we do not have this kind of hardware so it is very difficult to help you.

**Comment by Kolesar** [comment]
I have RAID1 made by BIOS and I tried make some fix adding follow:
```
# If imsm is set, we can ignore RAID altogether
if grep -qw 'imsm' /proc/mdstat; then
   return
fi
```
on the beginning of the:
`/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh`
and
`/usr/share/rear/prep/GNU/Linux/230_include_md_tools.sh`

Because, I do not want to touch any on RAID through Linux, just make partitions and LVM if exists, but I did not finish it, because I have some another issues. Maybe, you can try this on your environment if you have similar situation.

**Comment by urobasa** [comment]
thank you

⁣Отправлено с помощью Blue ​

На 13 сент. 2017 г., 17:00, в 17:00, "Asim Husanović" <notifications@github.com> написал:п>I have RAID1 made by BIOS and I tried make some fix adding follow:

**Comment by jsmeix** [comment]
See also
https://github.com/rear/rear/issues/1540#issuecomment-343129121

**Comment by jsmeix** [comment]
@urobasa 
I assume you also have the special Intel Matrix RAID hardware, cf.
https://github.com/rear/rear/issues/1540#issuecomment-343418305

**Comment by sriemer** [comment]
Intel RST on Linux documentation:
https://www.intel.com.au/content/dam/www/public/us/en/documents/white-papers/rst-linux-paper.pdf

Check if HW supports RST:
`mdadm -–detail-platform`
or less reliable:
`lspci | grep "SATA RAID Controller"`
