### ISSUE TITLE
Get rid of using "sfdisk"

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1107]
I think we should try to get rid of using partitioning tools
that do not support GPT and large partitions because
otherwise I fear there will be and endless sequence
of more and more problems in ReaR in the future.

In particular "man sfdisk" reads:
<pre>
sfdisk doesn't understand the GUID Partition Table
(GPT) format and it is not designed for large partitions.
In these cases use the more advanced GNU parted(8).
</pre>

Cf.
https://github.com/rear/rear/issues/1106#issuecomment-265088912

Currently "sfdisk" is called in
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/finalize/Linux-ppc64/200_install_yaboot.sh
usr/share/rear/finalize/SUSE_LINUX/ppc64/200_install_yaboot.sh
and "sfdisk" is mentioned in comments in
usr/share/rear/lib/mkrescue-functions.sh
and "sfdisk" is listed as REQUIRED_PROGS or PROGS in
usr/share/rear/conf/Linux-i386.conf
usr/share/rear/conf/Linux-ia64.conf
usr/share/rear/conf/Linux-ppc64.conf
usr/share/rear/conf/Linux-ppc64le.conf

**Comment by gozora** [comment]
Btw. same applies to `fdisk` (which seems not to be currently used in ReaR code ;-) )
```
fdisk does not understand GUID partition tables 
(GPTs) and it is not designed for large partitions.  
In these cases, use the more advanced GNU parted(8).
```

**Comment by jsmeix** [comment]
Probably "sfdisk" is still needed for NTFS support
to get NTFS related data from a 'msdos' partitioned disk
and sgdisk could be used for a 'gpt' partitioned disk, cf.
https://github.com/rear/rear/issues/1078#issuecomment-266386136

**Comment by gozora** [comment]
Yes, at least until we have complete code for that NTFS/Windows stuff, I'd put this "on hold".
