### ISSUE TITLE
Can't subscribe to mailing list due to broken SPF record

### ISSUE THREAD

**Issue by dominikr** [rear/rear#1113]
Hi everyone,
I tried subscribing to the rear-devel mailing list today, but I can't receive any emails from rear-devel-bounces@lists.relax-and-recover.org due to a broken SPF record (the SPF basically tells me that 148.251.123.139 is NOT allowed to send mail for lists.relax-and-recover.org. So it gets blocked by my employers mailgateway)

% dig txt lists.relax-and-recover.org
[...]
;; ANSWER SECTION:
lists.relax-and-recover.org. 80163 IN   TXT     "v=spf1 mx -all"

..but "lists.relax-and-recover.org" does not have a MX record specified. This could be fixed by adding an 'a' to the SPF record, or an MX record for lists.relax-and-recover.org

**Comment by gdha** [comment]
@dagwieers Hey Dag - does the above ring a bell with you?

**Comment by jsmeix** [comment]
Perhaps @danboid has the same problem, cf.
https://github.com/rear/rear/issues/1078#issuecomment-262756069
<pre>
I seem to be having trouble subscribing to your mailing list
</pre>

**Comment by dagwieers** [comment]
This should now be fixed !
Let me know if you have any issues (but wait 24h to report them, just in case ;-))

**Comment by dominikr** [comment]
Yep, I can now subscribe to the list

**Comment by dagwieers** [comment]
Thanks for reporting back !
