### ISSUE TITLE
support for new Bareos 16.2 client configuration file location

### ISSUE THREAD

**Issue by amtuannguyen** [rear/rear#1117]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 
Relax-and-Recover 1.19 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
Ubuntu 14.04.3 LTS

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=BAREOS
BACKUP_URL="nfs://blahblah/"
BAREOS_FILESET=$(hostname --fqdn)
BAREOS_RESTORE_JOB=RestoreFiles

* Brief description of the issue
rear mkrescue failed due to missing bareos-fd.conf
Starting with Bareos 16.2, the client configuration file lives in /etc/bareos/bareos-fd.d/client/myself.conf 

* Work-around, if any
Adding a test for the new configuration file in
/usr/share/rear/prep/BAREOS/default/45_check_BAREOS_client_configured.sh 

```
   [ -s /etc/bareos/bareos-fd.conf ] || [ -s /etc/bareos/bareos-fd.d/client/myself.conf ]
   StopIfError "Bareos configuration file (bareos-fd.conf) missing"
```

**Comment by jsmeix** [comment]
I am not a Bareos user so that I cannot test or verify
anything regarding Bareos on myself, nevertheless:

@amtuannguyen 
can you do a GitHub pull request with your change
so that others with sufficient Bareos knowledge
could have a look?

**Comment by jsmeix** [comment]
I think this one is a sub-set (i.e.one particular item)
of the general
https://github.com/rear/rear/issues/1077

@amtuannguyen 
I like to close this one and ask you to continue via
https://github.com/rear/rear/issues/1077

**Comment by jsmeix** [comment]
Since https://github.com/rear/rear/pull/1169
is merged this issue should be fixed.
