### ISSUE TITLE
RHEL 7 issue with Consistent Network Device Naming 

### ISSUE THREAD

**Issue by MiguelSanders** [rear/rear#1128]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 1.19
* OS version (cat /etc/rear/os.conf or lsb_release  -a): RHEL 7.3
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
BACKUP=NETFS
BACKUP_URL=nfs://XXX/GPFS/var/rear
OUTPUT=ISO
ONLY_INCLUDE_VG=('rootvg')

* Brief description of the issue

RHEL 7 uses "Consistent Network Device Naming" in which interface names are no longer ethX by default. (udev is generating a predictable interface name, fe. eno1654872). 
Even though this feature is disabled when running mkbackup, the rear recovery ISO is still using the predictable name for the interface. As a result, the interface doesn't get an IP address and recovery cannot continue automatically. 

* Work-around, if any

Add IP address manually to the interface.

**Comment by jsmeix** [comment]
As a workaround use
NETWORKING_PREPARATION_COMMANDS
so that you can define in /etc/rear/local.conf whatever
commands you need for networking setup in the
ReaR recovery system.
See
/usr/share/rear/conf/default.conf
how NETWORKING_PREPARATION_COMMANDS
is meant to work and for some examples how it works see
https://github.com/rear/rear/pull/960#issuecomment-239448861

**Comment by jsmeix** [comment]
FYI you may have a look at the somewhat related issue
https://github.com/rear/rear/issues/819

**Comment by MiguelSanders** [comment]
Hi Johannes

Thanks for the feedback.
Not sure if this will help since the name of the interface on the target system is unknown at the time of the backup. We don't know what udev will make of it...

**Comment by MiguelSanders** [comment]
One solution that I currently see is to generate a udev rule and put this in the recovery media. That way the target system can use the same interface name. 

f.e. 
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="<mac_address_of_interface_on_source>", ATTR{type}=="1", KERNEL=="eth*", NAME="<interface_name_on_source>"

What's your idea?

**Comment by gdha** [comment]
See solution in https://github.com/gdha/rear-automated-testing/issues/6

**Comment by jsmeix** [comment]
I assume it works now because "no news is good news".
