### ISSUE TITLE
Add Relax-and-Recover manual page and draft documentation to website

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#113]
Currently there is no documentation on the website. While we do have a manual page and draft documentation.

Maybe we should add the draft documentation, but clearly indicate it is a draft version and we expect feedback and contributions through Github.

**Comment by dagwieers** [comment]
I just added links to an auto-rendered GitHub page.
The documentation can be edited online and edits generate a Pull Request.

**Comment by schlomo** [comment]
Hey @dagwieers, thanks a lot!

**Comment by dagwieers** [comment]
I should have done this a lot earlier ;-)
But the AsciiDoc-integration in GitHub is a welcome change !
