### ISSUE TITLE
ERROR: No restore job defined in Bareos for client

### ISSUE THREAD

**Issue by amtuannguyen** [rear/rear#1137]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 
Relax-and-Recover 1.19 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=BAREOS
BACKUP_URL="nfs://1.2.3.4/backup/"
BAREOS_FILESET=$(hostname --fqdn)

* Brief description of the issue
Error when running rear mkrescue 
ERROR: No restore job defined in Bareos for

* Work-around, if any
A vanila Bareos setup has exactly ONE restore job for ALL clients. If there is no client specific restore job found, then rear should use the default restore job

**Comment by amtuannguyen** [comment]
https://github.com/rear/rear/pull/1138

**Comment by jsmeix** [comment]
@amtuannguyen 
many thanks for your contribution to ReaR
https://github.com/rear/rear/pull/1138
where I assigned @gdha because he made
the check_bareos_restore_jobs.sh script
(as far as "git log -p --follow ..." tells).

**Comment by jsmeix** [comment]
I merged https://github.com/rear/rear/pull/1138
so that this issue should now be fixed.
