### ISSUE TITLE
non-PAE processor

### ISSUE THREAD

**Issue by nnhughes** [rear/rear#1143]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 1.19 / 2016-12-23
* OS version (cat /etc/rear/os.conf or lsb_release  -a):16.04.1 LTS
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Brief description of the issue: 
When trying to boot from the rescue USB just created I get the message:
WARNING: PAE disabled. Use parameter 'forcepae' to enable at your own risk!
This kernel requires the following features not present on the CPU: 
pae

I remember when loading Ubuntu 16.04 on to my laptop this was an issue and I needed to use the forcepae parameter. Is there any way of using REAR where by this parameter is included somehow in the rescue install?
* Work-around, if any:none found as yet

Thanks in advance for any help that can be offered.

**Comment by gozora** [comment]
Hi,

Reading [default.conf](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf):
```
# You can add arbitrary kernel command line parameters when booting the rescue/recovery system
# as you need it (e.g. things like 'console=...' see USE_SERIAL_CONSOLE below).
# Additionally Relax-and-Recover supports the following special kernel command line parameters:
# - 'debug' starts all init-scripts (in /etc/scripts/system-setup.d/ in the rescue/recovery system)
#   in debug mode (via 'set -x') and asks for confirmation before it runs each init-script
#   so that you can skip a script if needed.
# - 'noip' prevents initialization of the networking configuration which is useful when
#   you want to do the networking configuration manually in the rescue/recovery system
#   e.g. to prevent the rescue/recovery system to use the same IP address as the original system
#   but for the latter using USE_DHCLIENT="yes" (see below) is probably easier:
KERNEL_CMDLINE=""
```

So in your case, it should be enough to add `KERNEL_CMDLINE="forcepae"` to `/etc/rear/local.conf`

**Comment by nnhughes** [comment]
Thanks heaps. This enabled the rescue image to boot.
