### ISSUE TITLE
Oversized archive

### ISSUE THREAD

**Issue by nnhughes** [rear/rear#1144]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):1.19 / 2016-12-23
* OS version (cat /etc/rear/os.conf or lsb_release  -a): 16.04.1 LTS
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): 
OUTPUT=ISO
BACKUP=NETFS
BACKUP_PROG=tar
OUTPUT_URL=null
ISO_URL="file:///media/nigel/5dd07191-9647-432f-bd4c-22fb863ad950/Ubuntu backup"
BACKUP_URL=iso:///backup/
BACKUP_OPTIONS=rw
KERNEL_CMDLINE="forcepae"

* Brief description of the issue: When running sudo usr/sbin/rear -v mkbackup an archive is created to the size of the free space of the system partition (on which the /tmp directory is). The process then fails with the following messages in the log:
mkdir: cannot create directory '/tmp/rear.0DSlFdKHTlVFu9K/tmp/boot': No space left on device
2017-01-01 11:18:11 ERROR: Could not mkdir /tmp/rear.0DSlFdKHTlVFu9K/tmp/boot

The harddrive I'm trying to back up is 320GB that is partitioned as:
- 30GB Filesystem Root (of which only 7GB is used) 
- Extended partition
        - 267GB Mounted at /home (84GB used)
        - 20GB Mounted at /usr/local (nearly totally empty)
        - 3.1GB Swap

I'm really only needing to the rescue disk to backup the system partition and I suppose the 20GB partition to an external 4TB usb hdd. (The files in the home partition are backed up separately.) Any ideas how I can achieve this?

Attached is the REAR log.
[rear-ubuntu.txt](https://github.com/rear/rear/files/679889/rear-ubuntu.txt)
        
* Work-around, if any: none.

**Comment by gdha** [comment]
Please use `ISO_DIR` instead of `ISO_URL` (`ISO_URL` is deprecated. Use `OUTPUT_URL` instead). So, what you did was just redefining `OUTPUT_URL`.

And, if `/tmp` does not have enough disk space you can redefine a directory for temporary space with the variable `TMPDIR`

**Comment by jsmeix** [comment]
I assume the backup of the 84GB used home partition
makes it too big for the 23GB free space on the root partition.

By default all mounted "normal" local filesystems are included
in the backup except things in BACKUP_PROG_EXCLUDE
see /usr/share/rear/conf/default.conf

To only backup the system partition either use
BACKUP_PROG_EXCLUDE to specify what local
filesystems should not be included in the backup.

Alternatively when you use the current ReaR GitHub code
you could use BACKUP_PROG_INCLUDE plus
BACKUP_ONLY_INCLUDE to specify only what local
filesystems should be included in the backup.

See the description of those variables in the current default.conf
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf

ReaR calls 'tar' with the options '--one-file-system' and '--anchored'
as follows (from my backup.log on my test system):
<pre>
tar --warning=no-xdev --sparse --block-number
 --totals --verbose --no-wildcards-match-slash
 --one-file-system --ignore-failed-read --anchored --gzip
 -X /tmp/rear.s0ZaD9wlm6SlToD/tmp/backup-exclude.txt
 -C / -c -f - / /root/rear/var/log/rear/rear-e205.log
</pre>
On my test system '/' is the only mounted "normal" local filesystem:
<pre>
# mount | grep sda
/dev/sda2 on / type ext4 (rw,relatime,data=ordered)
</pre>

**Comment by nnhughes** [comment]
Thank you very much gdha and jsmeix for your assistance. I'm yet to find a chance to implement your suggestions and test but will let you know when I do.

**Comment by jsmeix** [comment]
I assume at least for now this issue is sufficiently answered
so that I close it hereby.
If there are further questions that belong to this same issue
it can be reopened.
If there are further different questions, new separated issues
should be opened to keep different topics separated.
