### ISSUE TITLE
Better colors for the ReaR issue labels and additional labels

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1149]
From my point of view the current colors of the
ReaR issue labels at
https://github.com/rear/rear/labels
could be a bit better so that
corresponding labels get similar colors and
for example labels which mark things as done
like "fixed" should be green i.e. the complementary
color to red for things that need to be done and so on.

Furthermore I would like to add two labels named
"external backup tool" or "third party"
for things that somehow belong to ReaR but are
no ReaR core functionality
and something like
"no ReaR issue" or "invalid"
for things that do not belong to ReaR.

@gdha 
what do you think about such changes?

**Comment by gdha** [comment]
@jsmeix no problem for me - improvements are always more then welcome

**Comment by jsmeix** [comment]
I have doen the new colors mostly.
Only "support" is currently while - it should
get a color that looks promising...

**Comment by gdha** [comment]
@jsmeix colors are fine for me
