### ISSUE TITLE
/dev/sda1 device or resouce is  busy when recreate partition during rear recover

### ISSUE THREAD

**Issue by Veklip** [rear/rear#1167]
rear version :2.0
OS version : RHEL7
/etc/rear/local.conf : 
OUTPUT_URL=file:///mnt
BACKUP_URL=file:///mnt
BACKUP=NETFS

* Brief description of the issue:
parted -s /dev/sda mkpart "primary" 3149824B 422580223B
Error:Failed to add partition 1 (Device or resouce busy)

**Comment by jsmeix** [comment]
https://en.opensuse.org/SDB:Disaster_Recovery#Debugging_issues_with_Relax-and-Recover

**Comment by gdha** [comment]
@Veklip Show us the `/var/lib/rear/layout/disklayout.conf` file

**Comment by Veklip** [comment]
@gdha


# Disk /dev/sda
# Format: disk <devname> <size(bytes)> <partition label type>
disk /dev/sda 147086327808 msdos
# Partitions on /dev/sda
# Format: part <device> <partition size(bytes)> <partition start(bytes)> <partition type|name> <flags> /dev/<partition>
part /dev/sda 1048576 1048576 primary none /dev/sda1
part /dev/sda 419430400 2097152 primary boot /dev/sda2
part /dev/sda 107374182400 421527552 primary lvm /dev/sda3
part /dev/sda 1024 107795709952 extended none /dev/sda4
part /dev/sda 21600665600 107797807104 logical lvm /dev/sda5
part /dev/sda 8451522560 129399521280 logical lvm /dev/sda6
lvmdev /dev/vg_data /dev/sda6 PGHF5W-KciE-54oa-e5cF-k2Aj-113a-WLCTJa 16506880
lvmdev /dev/cinder-volumes /dev/sda5 QNxauN-fisb-xRCr-XUBJ-7L2q-tMLh-eB6HPg 42188800
lvmdev /dev/vg_sys /dev/sda3 3Zuomj-zvgC-I7g0-UbM0-rHSn-b0oI-YTdBbZ 209715200
lvmgrp /dev/vg_data 4096 2014 8249344
lvmgrp /dev/cinder-volumes 4096 5149 21090304
lvmgrp /dev/vg_sys 4096 25599 104853504
lvmvol /dev/vg_data lv_swap 2000 16384000 
lvmvol /dev/vg_sys lv_root 25594 209666048 
# Filesystems (only ext2,ext3,ext4,vfat,xfs,reiserfs,btrfs are supported).
# Format: fs <device> <mountpoint> <fstype> [uuid=<uuid>] [label=<label>] [<attributes>]
fs /dev/mapper/vg_sys-lv_root / ext4 uuid=737d2e00-c1f0-41bc-a928-bb86ef381db9 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=180d bytes_per_inode=16380 default_mount_options=user_xattr,acl options=rw,relatime,data=ordered
fs /dev/sda2 /boot ext3 uuid=9a4aadd0-fd5e-432a-a33b-19289d939ffa label= blocksize=1024 reserved_blocks=5% max_mounts=-1 check_interval=180d bytes_per_inode=4096 default_mount_options=user_xattr,acl options=rw,relatime,data=ordered
# Swap partitions or swap files
# Format: swap <filename> uuid=<uuid> label=<label>
swap /dev/mapper/vg_data-lv_swap uuid=5d8a3a31-7d25-4500-a74d-b7ca3ef96f82 label=
~                                                                                                                                                                                            
~

**Comment by gdha** [comment]
@Veklip As `/mnt` mount point used in the `/etc/rear/local.conf` file is part of the `/` file system (and VG `/dev/mapper/vg_sys` or `/dev/sda3`) you cannot mount and reformat the same partition. Please use and external disk (e.g. USB devices or NFS mount point) otherwise you will never be able to re-format `/dev/sda3`.
If on `/mnt` file system you mounted another NFS file system, then you forgot to tell me.

**Comment by Veklip** [comment]
@gdha Thanks for reminding me.And I mounted another NFS file system onto /mnt in this case. It stranges me that parted command is ok when I recover on another machine.

**Comment by gdha** [comment]
@Veklip Any further assistance required?

**Comment by gdha** [comment]
Closing as no questions nor feedback received

**Comment by jsmeix** [comment]
According to "no news is good news"
I assume it is (somehow) "fixed/solved/done".
