### ISSUE TITLE
ReaR sshfs -- "fuse" kernel module doesn't load

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#1181]
````
RESCUE xrearm3d:~ # rear -V
Relax-and-Recover 1.17.2 / Git

[root@xrearm3d rear]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[root@xrearm3d rear]# cat local.conf
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
# John L added the lines below.
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=sshfs://root@xxx.xxx.xxx.xx/dbar/
BACKUP_URL=sshfs://root@xxx.xxx.xxx.xx/dbar/
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
````
When doing a OS recovery the process will stop because the "fuse" kernel module doesn't load.  The workaround is to issue "modprobe fuse" then start the recovery.  This is not an issue with RHEL6. 
Do I need to configure anything different for RHEL7?

Below is a cut and paste from the log.
````
2017-01-25 21:06:08.576224076 Mounting with 'sshfs root@xxx.xxx.xxx.xx:/dbar/ /tmp/rear.WsziLKbsxTRNmcx/outputfs -o rw,noatime'
fuse: **device not found, try 'modprobe fuse' first**
2017-01-25 21:06:08.577977056 ERROR: Mount command 'sshfs root@xxx.xxx.xxx.xx:/dbar/ /tmp/rear.WsziLKbsxTRNmcx/outputfs -o rw,noatime' failed.
=== Stack trace ===
Trace 0: /bin/rear:251 main
Trace 1: /usr/share/rear/lib/recover-workflow.sh:27 WORKFLOW_recover
Trace 2: /usr/share/rear/lib/framework-functions.sh:70 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:31 Source
Trace 4: /usr/share/rear/verify/NETFS/default/06_mount_NETFS_path.sh:11 source
Trace 5: /usr/share/rear/lib/global-functions.sh:153 mount_url
Trace 6: /usr/share/rear/lib/_input-output-functions.sh:132 StopIfError
Message: Mount command 'sshfs root@xxx.xxx.xxx.xx:/dbar/ /tmp/rear.WsziLKbsxTRNmcx/outputfs -o rw,noatime' failed.
````

Thanks,
John

**Comment by John-Leone** [comment]
Sorry, not sure why the font is so big.

**Comment by jsmeix** [comment]
Relax-and-Recover 1.17.2 is rather old
(from August 2015).

I think this issue should be fixed in current ReaR with
https://github.com/rear/rear/commit/c1e962855a3e477093caa63cdd7602a76a801f72

This was committed on 7 Jul 2016 so that it
should be fixed since ReaR version 1.19.0 (October 2016).

**Comment by gdha** [comment]
@John-Leone If you have a RHEL support contract create a ticket with RedHat and request a newer rear version (and refer to RHBZ#1355667 - Rebase rear to newer version ). The more people ask for it, then the RH engineers will make some time to test out rear-2.00 and validate it for RHEL 7.2

**Comment by John-Leone** [comment]
Thank you; I will do what you recommend.
Also, we are waiting for (MANUAL_INCLUDE= fix) rear-2.1 coming in May.

**Comment by jsmeix** [comment]
@John-Leone 
I don't know about a "fix" for MANUAL_INCLUDE
that is planned for the next ReaR version?

I only know about
https://github.com/rear/rear/issues/1019#issuecomment-271077493
which is about to get rid of MANUAL_INCLUDE provided
BACKUP_PROG_INCLUDE plus BACKUP_ONLY_INCLUDE and
BACKUP_PROG_EXCLUDE plus BACKUP_ONLY_EXCLUDE
can be used as a replacement for what MANUAL_INCLUDE
is intended to be used.

**Comment by John-Leone** [comment]
So I should be able to use BACKUP_PROG_INCLUDE=( ) to backup only the file systems that are specified in the statement, correct?  It essentially works like MANUAL_INCLUDE.
Let me know if I’m mistaken.

**Comment by jsmeix** [comment]
@John-Leone 
let's not misuse this issue which is about sshfs and fuse
for issues about MANUAL_INCLUDE.
I think I already answered your above question in
https://github.com/rear/rear/issues/1019#issuecomment-264132715
therein see in particular the "How it works" part at the end
or even better see directly the documentation in default.conf
in the curent GitHub master code:
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf

**Comment by John-Leone** [comment]
Thank you.

**Comment by John-Leone** [comment]
I just heard back from RedHat and the target to rebase ReaR to either 1.19 or 2.0 is RHEL 7.4.
