### ISSUE TITLE
verbose mode showing  speed as negative

### ISSUE THREAD

**Issue by razorfish-sl** [rear/rear#1187]
Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

centos 7.2
Relax-and-Recover 2.00-git201701271258 / 2017-01-27

when running in verbose mode during mkbackup figures are shown negative....

Archived -6385 MiB [avg -7413 KiB/sec]

**Comment by gdha** [comment]
@razorfish-sl I haven't seen this so far??

**Comment by razorfish-sl** [comment]
it was on a VM
Perhaps the network was so fast the "speed" was wrapping the bitsize of the variable.
after about 30 minutes it went positive.

**Comment by gdha** [comment]
We never saw this behaviour. Have no clue what it could be (for the moment) and as it is not impacting rear archiving I would prefer to leave it as it is.
In the future we could re-open this issue if needed.
