### ISSUE TITLE
Issue template change

### ISSUE THREAD

**Issue by gozora** [rear/rear#1196]
Hello guys,

Can you please correct new issue template
```
- Are you using legacy BIOS of UEFI boot?
+ Are you using legacy BIOS or UEFI boot?
```

I guess it is an typo.

Thanks

V.

**Comment by gdha** [comment]
Fixed it - thanks Vlad!

**Comment by jsmeix** [comment]
@gozora 
only for the fun of it:
It was me who added that text
but it is your pristine original typo ;-)
that I blindly copy&pasted, see
https://github.com/rear/rear/issues/1153#issuecomment-270638388
I really did not notice the typo at that time
regardless that I had read the text
which tells a lot how good I am in finding typos.

**Comment by gozora** [comment]
@jsmeix 
I've made a typo. Surprise, surprise! :-)
