### ISSUE TITLE
Implement FIRMWARE_FILES support

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1216]
I would like to implement a new variable
FIRMWARE_FILES
where the user can specify which firmware files
get included in the ReaR recovery system.

This enhancement is based on the experience in
https://github.com/rear/rear/issues/1142#issuecomment-276015345
<pre>
It seems more than the half of ReaR's initrd
on my x86_64 system is used for firmware.
</pre>
and
https://github.com/rear/rear/issues/1142#issuecomment-283324917
<pre>
After removing /usr/lib/firmware contents
except for /usb/lib/firmware/rtl_nic ...
I ended up with ...
initrd.xz with xz lzma compression (48327540 bytes)
</pre>

In particular an explicit FIRMWARE_FILES variable
that is documented in default.conf gives the user the final power
to decide what gets included in the ReaR recovery system.
Regarding "give the user the final power" cf.
"too much secretly working 'magic automatisms' in ReaR" in
https://github.com/rear/rear/pull/1204#issuecomment-282252947

Furthermore the FIRMWARE_FILES variable could be
a good template case for variables have ternary semantics, cf.
https://github.com/rear/rear/pull/1212#issuecomment-283698753

My currently planned ternary semantics for
FIRMWARE_FILES will be:

FIRMWARE_FILES=""
means "whatever reasonable automated behaviour"

FIRMWARE_FILES="yes" (or any explicit 'true' value)
means "include all firmware files in the ReaR recovery system"

FIRMWARE_FILES="no" (or any explicit 'false' value)
means "include no firmware file in the ReaR recovery system"

Finally the FIRMWARE_FILES variable might become
also a template case for variables that have multiple semantics:

For example in addition to the ternary semantics above
the FIRMWARE_FILES could also be an array
of explicitly listed firmware files that will be included in the
ReaR recovery system and/or filename globbing patterns
that are used as '-iname' arguments for 'find' calls to find
firmware files in the /lib/firmware/ directory that will get
included in the ReaR recovery system.

Regarding variables that can have multiple semantics
cf. how UEFI_BOOTLOADER can be specified since
https://github.com/rear/rear/pull/1212
is merged (see the current default.conf).

**Comment by jsmeix** [comment]
With a REAR_INITRD_FIRMWARE variable
that gives the user the final power to decide
what gets included in the ReaR recovery system
it may then even work on ppc64le in BareMetal Mode (PowerNV)
with yaboot, cf.
https://github.com/rear/rear/issues/1142#issuecomment-276050900

**Comment by ProBackup-nl** [comment]
I did clean up my firmware directory to just over 92K.

I think I'd rather see a warning message during rescue creation, in case firmware is relative large, as a reminder to clean up the firmware folder on that (new) machine too.

**Comment by ProBackup-nl** [comment]
On second thought, this feature is actually quite usable: I don't need networking to restore my system from the USB drive. So I don't need any firmware at all copied into the initrd file.

**Comment by jsmeix** [comment]
ReaR will not do things like "clean up the firmware folder".

In general ReaR must not change any existing file
of the original system.
The only thing what happens during "rear mkbackup/mkrescue"
on the original system is that ReaR creates its working directory
where ReaR builds its rescue/recovery system ISO image
(cf. TMPDIR in default.conf).

The only exception that I know about where ReaR can change
even crucial files of the original system is GRUB_RESCUE
but that functionality is disabled by default (cf. default.conf).

During "rear recover" ReaR should not change the recreated system.
During "rear recover" ReaR should recreate the system as much as
possible as it was before (except in case of bigger new harddisk
where ReaR will try to adapt the partitioning to the new harddisk
by its so called "migration mode").
During "rear recover" ReaR will restore the files of the original
system as they were saved in the backup during "rear mkbackup"
and there is the special BACKUP_RESTORE_MOVE_AWAY
functionality that does nothing by default (see default.conf).

**Comment by jsmeix** [comment]
I will use the variable name FIRMWARE_FILES
(instead of my initial idea REAR_INITRD_FIRMWARE)
to have this variable name in compliance with
the existing variable name KERNEL_FILE.

**Comment by ProBackup-nl** [comment]
Some more experience is shared. Even after cleaning up the HOST its firmware directory, 

> Finished running 'build' stage in 21 seconds 

of running `mkrescue` workflow, which finishes in 31 seconds in total. 

With 68% of time in the build stage, creates room speed improvements.

Like excluding certain copy paths in [build/GNU/Linux/400_copy_modules.sh](https://github.com/rear/rear/blob/master/usr/share/rear/build/GNU/Linux/400_copy_modules.sh), a variable where I could specify exclusions like for example:
```
/lib/modules/*-ARCH/kernel/drivers/net/
/lib/modules/*-ARCH/kernel/fs/cifs/
/lib/modules/*-ARCH/kernel/net/ 
```
When not needing networking in the rescue system, exclude SSH permissions adjustment from  [build/GNU/Linux/150_adjust_permissions.sh](https://github.com/rear/rear/blob/master/usr/share/rear/build/GNU/Linux/150_adjust_permissions.sh)

**Comment by jsmeix** [comment]
@ProBackup-nl 
regarding what kernel modules get included in the recovery system see
https://github.com/rear/rear/issues/1202
and regarding what I intend to improve there see in particular
https://github.com/rear/rear/issues/1202#issuecomment-284377443
but all this happens "as time permits" for me which currently means
it has to wait because currently I have to work on other areas
which is currently mainly printing related stuff, cf.
https://en.opensuse.org/User:Jsmeix

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1256 merged,
this issue should be fixed.
