### ISSUE TITLE
Website contributing section seems out of date: checkout new branches against upstream/dev

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1224]
To contribute I was pointed to [http://relax-and-recover.org/development/#contributing](http://relax-and-recover.org/development/#contributing)

The website suggests to checkout new branches against `upstream/dev`

However that leaves me with to old 2-digit file naming scheme, instead current master 3-digit file naming scheme:
```
00_remove_workflow_conf.sh  04_check_output_scheme.sh		  31_include_uefi_tools.sh	 50_guess_bootloader.sh
02_translate_url.sh	    05_check_keep_old_output_copy_var.sh  32_include_uefi_env.sh	 95_check_missing_programs.sh
03_translate_tape.sh	    10_init_workflow_conf.sh		  40_save_mountpoint_details.sh
```

This makes contributing complex. Something seems to need an update.

**Comment by gdha** [comment]
@ProBackup-nl This morning I did synchronization between our dev/master branch. They are now equal.

**Comment by jsmeix** [comment]
I think this issue should now be fixed
because the following pull requests were merged:
https://github.com/rear/rear/pull/1222
https://github.com/rear/rear/pull/1226
https://github.com/rear/rear/pull/1227
