### ISSUE TITLE
What about 30_stop_selinux.onhold (two digit named script)?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1228]
I found a two digit named script
backup/NETFS/GNU/Linux/30_stop_selinux.onhold
and I wonder how it came into the current ReaR master.

@gdha 
I assign this issue to you because
<pre>
git log -p --follow usr/share/rear/backup/NETFS/GNU/Linux/30_stop_selinux.onhold
</pre>
shows that the script was renamed by you
from 30_stop_selinux.sh to 30_stop_selinux.onhold
in July 2011.
Currently I cannot explain why it was not renumbered.
Perhaps because its extension is not '.sh' but '.onhold'.

**Comment by gdha** [comment]
The script `backup/NETFS/GNU/Linux/310_stop_selinux.sh` is a symlink to `backup/RSYNC/GNU/Linux/310_stop_selinux.sh` and is exactly the same script as `30_stop_selinux.onhold`
We better remove it.

**Comment by jsmeix** [comment]
@gdha 
many thanks for your explanation and for your fast fix!
