### ISSUE TITLE
swap disk excluded from recovery

### ISSUE THREAD

**Issue by gdha** [rear/rear#1231]
* rear version (/usr/sbin/rear -V): 1.17.2 and higher
* OS version (cat /etc/rear/os.conf or lsb_release -a): all
* Brief description of the issue:

````
#-> grep swap /etc/fstab
/dev/mapper/vg00-swap   swap                    swap    defaults        0 0
/dev/mapper/swap-lvswap       swap    swap    defaults        0 0
````

````
#-> cat /proc/swaps
Filename                                Type            Size    Used    Priority
/dev/dm-1                               partition       4194300 1444    -1
/dev/dm-5                               partition       33553404        0       -2
````

````
#-> grep swap /var/lib/rear/layout/disklayout.conf
#lvmdev /dev/swap /dev/sdb N3Xb5L-Ueha-Q8Q6-JJbn-enEO-kOKO-mqkLnR 67108864
#lvmgrp /dev/swap 1024 32767 33553408
#lvmvol /dev/swap lvswap 32767 67106816
lvmvol /dev/vg00 swap 1024 8388608
swap /dev/mapper/vg00-swap uuid=109e1047-d5bb-4bd1-ad17-f013910321a7 label=
#swap /dev/mapper/swap-lvswap uuid=65729f51-2de5-41ca-b03a-316de4365fcf label=
````
We pin-pointed the issue in the script `layout/save/default/320_autoexclude.sh` and more specific in the area where disks are excluded which are **not** in use. Reason is the variable `AUTOEXCLUDE_DISKS=y` setting in the `conf/default.conf` file.

The question is  : should be add _swap_ devices automatically to the `used_disks` array in above mentioned script? Or, should be add a better explanation in the `default.conf` file about potential consequences of variable `AUTOEXCLUDE_DISKS` ?

**Comment by jsmeix** [comment]
I think because this issue is marked as "fixed" it can be closed.
