### ISSUE TITLE
rear backup fails on servers with oracle asm disks

### ISSUE THREAD

**Issue by mcothenet** [rear/rear#1234]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
 Puppet Deployed module cn_rear (editable)
# Do NOT remove this comment or file will be replaced.
# BACKUP_URL and other settings automatically defined in site.conf.
# You CAN change the values here, this file will NOT be replaced.


# Relax-and-Recover will not automatically add itself to the Grub bootloader. It copies itself to your /boot folder.
# To enable this, add
# GRUB_RESCUE=1

######
# Create Rear rescue media as ISO image
OUTPUT=ISO
BACKUP=NETFS
EXCLUDE_MOUNTPOINTS=()
EXCLUDE_MD=()
MODULES_LOAD=( vmxnet )

# Exclude all VG except rootvg
EXCLUDE_VG=(`vgs |awk '!/VG|rootvg/{print $1}'`)

# Exclude folders
# Note : Data should be restore with netbackup

if [ -r "/etc/rear/exclude_folders" ]; then
        BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" `cat /etc/rear/exclude_folders` )
fi


# Exclude filesystems
# Note : Filesystem will not created during restore process, so no garantee if filesystem/data is preseved

if [ -r "/etc/rear/exclude_filesystems" ]; then
        EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" `cat /etc/rear/exclude_filesystems` )
fi

## /etc/rear/exclude_filesystems look like :
# fs:/media/backup

BACKUP_URL=nfs://mtlnza-07.cn.ca/data/col1/linux-backup
````
* Are you using legacy BIOS or UEFI boot? legacy BIOS
* Brief description of the issue:
````
Following error when executing rear -v mkbackup
====================
ERROR: BUG BUG BUG!  Could not determine size of disk sdam/sdam1, please file a bug.
Note: disks may differ if you restart the command.
````
* Work-around, if any:

**Comment by gdha** [comment]
@mcothenet Is this RHEL 7.3 or 7.2? See also issue #721 
What you also can do is `rear -v -D savelayout` and upload the log (e.g. via gist)

**Comment by mcothenet** [comment]
Hello,
Here is the rear log
Thx

[rear-mtl-o24n41s.docx](https://github.com/rear/rear/files/903747/rear-mtl-o24n41s.docx)

**Comment by gdha** [comment]
@mcothenet Did you close this issue on purpose or by accident?
What can you tell me about device /dev/sdbg? I assume that is a disk under control of Oracle asm?
````
+++ get_disk_size sdbg/sdbg1
+++ local disk_name=sdbg/sdbg1
++++ get_block_size sdbg
++++ '[' -r /sys/block/sdbg/queue/logical_block_size ']'
++++ echo 512
+++ local block_size=512
+++ '[' -r /sys/block/sdbg/sdbg1/size ']'
+++ BugIfError 'Could not determine size of disk sdbg/sdbg1, please file a bug.'
+++ ((  1 != 0  ))
+++ BugError 'Could not determine size of disk sdbg/sdbg1, please file a bug.'
+++ '[' Could not determine size of disk sdbg/sdbg1, please file a bug. -eq Could not determine size of disk sdbg/sdbg1, please file a bug. ']'
+++ EXIT_CODE=1
+++ Error 'BUG BUG BUG! ' 'Could not determine size of disk sdbg/sdbg1, please file a bug.' '
````

**Comment by mcothenet** [comment]
Hi!
The issue is still open.
You are right. /dev/sdbg is under asm control.

ls -al /dev/sdbg
brw-rw---- 1 root disk 67, 160 Apr  7 08:11 /dev/sdbg

sv_asm_datac1_st4_002 (360002ac0000000000000021e0001c5a6) dm-83 3PARdata,VV
size=2.0T features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
`-+- policy='round-robin 0' prio=50 status=active
  |- 1:0:0:59 sdbg              67:160     active ready  running
  |- 3:0:0:59 sdgy              132:224    active ready  running
  |- 1:0:1:59 sdec              128:64     active ready  running
  `- 3:0:1:59 sdju              65:384     active ready  running


After I have added in /etc/rear/local.conf the following lines, the rear backup on one server is fine but I get the initial errors on the other server in cluster

CHECK_CONFIG_FILES=( '/etc/drbd/' '/etc/drbd.conf' '/etc/lvm/lvm.conf' '/etc/multipath.conf' '/etc/rear/' '/etc/udev/udev.conf' )
EXCLUDE_MULTIPATH=y

You help will be greatly  appreciated.
Thx

**Comment by mcothenet** [comment]
Hello,
Issue solved by updating rear to latest version.
rear-2.00-1.el7.x86_64.rpm
