### ISSUE TITLE
mkrescue: don't copy .gitignore files to /rootfs/

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1249]
* rear version (/usr/sbin/rear -V): 2.00 git
* OS version (cat /etc/rear/os.conf or lsb_release -a): Arch Linux rolling
* UEFI boot

KEEP_BUILD_DIR="yes"

Shows in my case that 93 times a `.gitignore` file is being copy.

On the rescue medium `.gitignore` files have no purpose I think, so better not copy `.gitignore` files onto it.

some examples:
```
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/tmp/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/run/systemd/journal/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/run/systemd/generator/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/run/klogd/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/log/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lock/subsys/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lock/lvm/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lock/lockdev/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lib/syslog-ng/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lib/nfs/statd/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lib/empty/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lib/dhcpcd/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/var/lib/dhclient/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/usr/lib/udev/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/usr/lib/systemd/system/basic.target.wants/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/usr/include/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/tmp/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/sys/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/selinux/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/run/udev/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/run/systemd/journal/syslog/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/run/resolvconf/.gitignore
/tmp/rear.HRmBfwd61buMrjq/rootfs/run/lvm/.gitignore
```

**Comment by jsmeix** [comment]
I assume that on the rescue medium
the .gitignore files do not do any harm
so that I think the issue is only cosmetic.
Furthermore - as far as I understand it - it only
happens when you work on a GitHub checkout
because - as far as I remember - when you use
ReaR via e.g. an installed RPM package, you
don't get .gitignore files installed.

**Comment by schlomo** [comment]
Indeed, not an issue for releases. For dev builds from checkouts I would strongly suggest to combine all those .gitignore files into one global one in the top level directory. I follow all the [arguments for a single file](https://stackoverflow.com/questions/3305869/are-multiple-gitignores-frowned-on/29695734#29695734)

**Comment by gdha** [comment]
Issue #1392 takes care of this issue.
