### ISSUE TITLE
grubby bootloader (needed on s390x and aarch64) is unsupported

### ISSUE THREAD

**Issue by tcerna** [rear/rear#1261]
Hi Gratien.
Is s390x still unsuported? I tried run tests on s390x and it fails because of 'Unknown bootloader'.

```
# rear -v mkbackup
Relax-and-Recover 2.00 / Git
Using log file: /var/log/rear/rear-ibm-z-37.log
Using backup archive '/tmp/rear.A7rTQmnaKkRkQdq/tmp/isofs/backup/backup.tar.gz'
mkdir: created directory '/root/reartest'
Creating disk layout
ERROR: 
====================
BUG in /usr/share/rear/layout/save/default/450_check_bootloader_files.sh:
'Unknown bootloader () - ask for sponsoring to get this fixed'
--------------------
Please report this issue at https://github.com/rear/rear/issues
and include the relevant parts from /var/log/rear/rear-ibm-z-37.log
preferably with full debug information via 'rear -d -D mkbackup'
====================
Aborting due to an error, check /var/log/rear/rear-ibm-z-37.log for details
Terminated

# rpm -q rear
rear-2.00-1.el7.s390x
```

When I checked script 450_check_bootloader_files.sh, I saw that there is no grubby support which s390x needs.

**Comment by gdha** [comment]
@tcerna  Hi Tereca - unfortunately I do not have access to s390x hardware to get support added into ReaR. I'm looking for a sponsor who can do this for us, or someone who is willing to buy consultancy to get this implemented.

**Comment by gdha** [comment]
@schabrolles Hey Sebastien, s390x is this an architecture that you cover as well?

**Comment by schabrolles** [comment]
@gdha, not in my team ... If needed I could ask if somebody could find some time to work on that.

**Comment by jsmeix** [comment]
For reference: See the related issues on aarch64:
https://github.com/rear/rear/issues/1357
https://github.com/rear/rear/issues/1358

**Comment by jsmeix** [comment]
The `grubby` bootloader might be now supported
since https://github.com/rear/rear/pull/2142 is merged
because `grubby` is mentioned in
https://github.com/rear/rear/blob/master/usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh

@tcerna 
could you test if `grubby` now works for you, cf.
https://github.com/rear/rear/issues/2137#issuecomment-566078295
