### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by DongIn0916** [rear/rear#1263]
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release -a):
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
* Work-around, if any:

**Comment by DongIn0916** [comment]
Leave a comment

**Comment by jsmeix** [comment]
It ssems this one is the actual issue:
https://github.com/rear/rear/issues/1264
