### ISSUE TITLE
Relax-and-Recover (ReaR) Documentation Style

### ISSUE THREAD

**Issue by gdha** [rear/rear#1275]
#### Relax-and-Recover (ReaR) Documentation Style

I found the following interesting link: https://toolchain.gitbook.com/
which we could use for writing documentation like our developers guide
https://github.com/rear/rear/wiki/Developers-Guide
Perhaps, I will use it for writing a workshop.
Feedback is welcome...

**Comment by jsmeix** [comment]
Ony FYI:
Today I will watch a (SUSE internal) presentation/tutorial
that is about "Technical Writing":
<pre>
You need to write (technical) texts now and then?
But you are not sure how to structure them,
how to phrase your content, or how to best address your readers?
This session shows you how to optimize texts to make them
easier to understand. Get to know universal principles that
can be applied to a wide variety of text types - including
release notes, bug reports, error messages, or e-mails. 
</pre>
