### ISSUE TITLE
Check out waffle.io to increase transparency / Agree on external tool access to ReaR

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1280]
Please have a look at https://waffle.io/rear/rear, maybe this helps our users see what we work on?

**Comment by gozora** [comment]
lol Ironing my waffle???

**Comment by gozora** [comment]
Don't want to sound paranoid but is this safe?
```
Authorize application
Waffle by @waffleio would like permission to access your account
```

@schlomo Did you authorized this access for your account?

**Comment by schlomo** [comment]
Yes, I did. And I know what you mean. That is why I want your opinion on this topic.

**Comment by schlomo** [comment]
Waffle says: "Due to limitations in the GitHub API, we require read/write access to your repos in order to interact with Issues". I actually saw this kind of disclaimer in many tools and would say that this is a reason why GitHub is only good for public stuff.

**Comment by schlomo** [comment]
A possible alternative is to use [GitHub projects](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) which kind of does the same but less fancy looking.

**Comment by gozora** [comment]
Well, reviewing permissions, I'm fine with:
 - Email addresses (read-only)
This application will be able to read your private email addresses.
- Organizations and teams
Read-only access
This application will be able to read your organization and team membership.
- write access to Issues

I'm not so happy with following write access:
- Code
- Pull requests
- Wikis
- Settings
- Webhooks and services (despite I'm not entirely sure what this does)

But biggest NO NO for me is **Deploy keys**

But in general I'll trust you guys, as I'm pretty new in development, so if you say it is safe I'm joining you.

V.

**Comment by gozora** [comment]
If GitHub projects can do same thing, I'm prepared to exchange fanciness for better security control any time ;-)
A short [video](https://www.youtube.com/watch?v=C6MGKHkNtxU) about GitHub projects if you like watching more then reading ...

V.

**Comment by schlomo** [comment]
According to the video it seems like the projects can't use the labels to sort issues into columns.

If we already talk about security, ATM we already have some external apps enabled:
![image](https://cloud.githubusercontent.com/assets/101384/24714729/9f671db4-1a29-11e7-887f-bb31e4542ee0.png)

Maybe this is a good moment to talk about that and make sure that everybody here agrees with that. I most definitively don't want to make anybody feel worried about security here.

**Comment by schlomo** [comment]
@gozora The deploy keys access that you mention is also the thing that worries me most of all - and which is for me the reason to treat GitHub more as a repo and less as a workflow tool that can change stuff elsewhere.

To safeguard ReaR code we could also adopt GPG signing - as long as the 3rd party apps don't have your GPG key they won't be able to manipulate our code without us knowing about it.

I actually started to sign all my commits this month.

**Comment by gozora** [comment]
GPG signing of ReaR is indeed a good idea!

**Comment by jsmeix** [comment]
I didn't read all the details but in general
I never permit anybody or anything to act as if it was me.

**Comment by schlomo** [comment]
It seems to me that we don't need Waffle.io or similar external tools at the moment. If nobody speaks up in favor I'll remove it soon. Thanks a lot, Schlomo

**Comment by gdha** [comment]
As nobody seems to use this we better close the case
