### ISSUE TITLE
Handle eMMC and NVMe naming schemes (also for migrations)

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1301]
* rear version: 2.00 git
* OS version: Arch
* rear configuration files: USB NETFS
* Are you using legacy BIOS or UEFI boot? UEFI
* Brief description of the issue: Migration from `/dev/sda` to `/dev/nvme0n1` fails, due to device translation `/dev/sda1` becomes `/dev/nvme0n11` in the new disklayout.conf, which in the generated script becomes partition `11` (instead of 1).

Note:
`/dev/nvme0n1` = first NVMe drive
`/dev/nvme9n1` = 10th NVMe drive
`/dev/nvme10n1` = 11th NVMe drive

I suspect similar failures for eMMC storage, using naming scheme `/dev/mmcblk*`

And [Clonezilla lists](https://github.com/stevenshiau/clonezilla/blob/master/clonezilla.spec) that there are also nvme naming schemes like `nvme*n2`, `nvme*n3`:

> - Expand NVME support to disk device name like /dev/nvme0n2, and /dev/nvme0n3 instead of /dev/nvme0n1 only.

**Comment by jsmeix** [comment]
@ProBackup-nl 
I assume this issue is "fixed/solved/done"
with https://github.com/rear/rear/pull/1302
and https://github.com/rear/rear/pull/1305
merged. If not, reopen it.
