### ISSUE TITLE
BACKUP_PROG_INCLUDE suggested command in SLE12 btrfs example configuration

### ISSUE THREAD

**Issue by deacomm** [rear/rear#1330]
The suggested command to generate BACKUP_PROG_INCLUDE can be wrong:
 - findmnt can output non-ascii glyphs to draw the tree lines in default output, while the command relies on the dash character ('-') to be used in those lines
 - some subvolume mount points can include the dash character (e.g. '/boot/grub2/x86_64-efi' on SLES12SP1)

The commands are at:
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf#L59
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf#L61

Suggested alternative which worked for me:
`findmnt -n -r -t btrfs | cut -d ' ' -f 1 | grep -v '^/$' | egrep -v 'snapshots|crash' | sed -e "s/$/\/*'/" -e "s/^/'/" | tr '\n' ' '`

**Comment by jsmeix** [comment]
Fixed.

@deacomm 
many thanks for careful reading the examples!
