### ISSUE TITLE
Clean-up bonding TODOs in network_devices

### ISSUE THREAD

**Issue by jezzaaa** [rear/rear#134]
The 31_network_devices.sh script has a number of mentions of things that need to be fixed up for bonding.  I have a SLES10 bonding setup (both production and lab) and I'm happy to work on this, testing and/or submitting patches, if the problems can be specified.

I've yet to try this with a multi-bond server, but so far I haven't had a problem using the bond0 interface when in the recovery environment.  I don't have SIMPLIFY_BONDING defined.

**Comment by gdha** [comment]
VLAN support is in rear-1.16 already - we better close this issue and if other (bew) issues occur a new issue can be opened
