### ISSUE TITLE
Error: "No files to copy (RESULT_FILES is empty)" when using TSM + PXE

### ISSUE THREAD

**Issue by schabrolles** [rear/rear#1342]
During mkrescue phase I got the error : 
`Error: "No files to copy (RESULT_FILES is empty)"`

`output/TSM/default/950_dsmc_save_result_files.sh` try to backup `RESULT_FILES`, bit those one seems to be removed by previous script : `output/TSM/default/800_copy_tftp.sh`

=> `$RESULT_FILES` is empty, then we got the error message.

`950_dsmc_save_result_files.sh` should not run if ` $PXE_TFTP_URL` is set 

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 2.00-git
* OS version (cat /etc/rear/os.conf or lsb_release -a): SLES 11 SP4
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
* Work-around, if any:

Extract from /etc/rear/local.conf
```
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y

COPY_AS_IS_TSM=( /etc/adsm/TSM.PWD /opt/tivoli/tsm/client/ba/bin/dsmc /opt/tivoli/tsm/client/ba/bin/tsmbench_inclexcl /opt/tivoli/tsm/client/ba/bin/dsm.sys /opt/tivoli/tsm/client/ba/bin/dsm.opt /opt/tivoli/tsm/client/api/bin64/libgpfs.so /opt/tivoli/tsm/client/api/bin64/libdmapi.so /opt/tivoli/tsm/client/ba/bin/EN_US/dsmclientV3.cat /usr/local/ibm/gsk8* )

OUTPUT=PXE
OUTPUT_PREFIX_PXE=rear/$HOSTNAME

PXE_CONFIG_GRUB_STYLE=y
# On your TFTP server:
# In your tftpboot dir execute the following command to create the netboot directory based on GRUB.
# grub2-mknetdir --net-directory=/var/lib/tftpboot
# config directory will be /var/lib/tftpboot/boot/grub2/powerpc-ieee1275
# More information about setting up a PXE based on Grub on POWER : https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-installation-server-setup.html#sect-network-boot-setup-ppc-grub2
PXE_TFTP_IP=10.7.19.177
PXE_CONFIG_URL="nfs://$PXE_TFTP_IP/var/lib/tftpboot/boot/grub2/powerpc-ieee1275"
PXE_CREATE_LINKS=IP
PXE_REMOVE_OLD_LINKS=y
PXE_TFTP_URL="nfs://$PXE_TFTP_IP/var/lib/tftpboot"

USE_STATIC_NETWORKING=y

BACKUP=TSM
TSM_RESULT_SAVE=n

REAR_INITRD_COMPRESSION=lzma
```

**Comment by jsmeix** [comment]
FYI, see the related issue
https://github.com/rear/rear/issues/888

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1343 merged,
this issue should be fixed.

@schabrolles 
many thanks for the fix and for testing ReaR with TSM.

Only FYI:
In general regarding TSM support in ReaR
you may also have a look at
https://github.com/rear/rear/issues/823
