### ISSUE TITLE
Xorriso support

### ISSUE THREAD

**Issue by icebal** [rear/rear#1360]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release -a):
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
Add support for xorriso -as mkisofs
This could be as simple as putting in the config MKISOFS_BIN=xorriso or USE_XORRISO=TRUE
This would allow not only UEFI support, but bios as well without any other configuration. I would also suggest moving to use xorriso as the default as that is what is used for grub-mkrescue on ubuntu, and anything uefi related.
* Work-around, if any:

**Comment by schlomo** [comment]
👍 I am actually a big fan of the idea to work towards a version 3 that does away with most of the legacy stuff.

**Comment by jsmeix** [comment]
FYI: The current default.conf contains
<pre>
ISO_MKISOFS_BIN="$( type -p xorrisofs || type -p mkisofs || type -p genisoimage )"
</pre>

@schlomo @gdha @gozora 
perhaps FOSDEM 2018 is a good target date for a version 3.x ?

**Comment by jsmeix** [comment]
FYI:
On my SLES12 test system
with BIOS (on a KVM/QEMU virtual machine)
the "rear -d -D mkrescue" log contains (excerpts):
<pre>
2017-05-10 16:50:42.196041204 Using '/usr/bin/xorrisofs' to create ISO images
...
++ /usr/bin/xorrisofs -v -o /root/rear/var/lib/rear/output/rear-e205.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -volid RELAXRECOVER -v -iso-level 3 .
xorriso 1.3.4 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:/root/rear/var/lib/rear/output/rear-e205.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 11.1g free
Added to ISO image: directory '/'='/tmp/rear.sZRZkdc3UPQgzYH/tmp/isofs'
xorriso : UPDATE : 14 files added in 1 seconds
xorriso : UPDATE : 14 files added in 1 seconds
xorriso : UPDATE :  21.05% done
xorriso : UPDATE :  89.66% done
ISO image produced: 38920 sectors
Written to medium : 38920 sectors at LBA 0
Writing to 'stdio:/root/rear/var/lib/rear/output/rear-e205.iso' completed successfully.
</pre>
