### ISSUE TITLE
ReaR releases should not mention Git in version / Dev builds should mention the Git commit hash

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1362]
ATM the version string of a release (e.g. from EPEL) is `Relax-and-Recovery 2.00 / Git` which is confusing to customers who think that this is a development build from some git commit and not a real release.

ATM the version string of a dev build contains a date/time string and the date but not the commit hash.

I suggest to improve that so that we are more clear about the release/dev status of a package.

**Comment by jsmeix** [comment]
I also noitced that but found no time
to investigate what the root cause is.

**Comment by gdha** [comment]
@schlomo @jsmeix This will show the effective RELEASE_DATE of an official release date. I suppose this enough for v2.1?

**Comment by gdha** [comment]
Moved the milestone to v2.2 - for v2.1 we did what we needed to do and we have no time for further corrections/modifications.

**Comment by gdha** [comment]
I think we can close this issue
