### ISSUE TITLE
rear mkrescue shows "Using backup archive" message

### ISSUE THREAD

**Issue by gdha** [rear/rear#1363]
* rear version (/usr/sbin/rear -V): master git
* OS version (cat /etc/rear/os.conf or lsb_release -a): centos 7.3
* Brief description of the issue:
I find it rather strange when running `rear mkrescue` that we see the following message:
````
# rear -vd mkrescue
Relax-and-Recover 2.00-git201705081501 / 2017-05-08
Using log file: /var/log/rear/rear-client.log
Using backup archive '/tmp/rear.B9uTEKRZLGjnpxn/outputfs/client/backup.tar.gz'
Creating disk layout
````

**Comment by jsmeix** [comment]
I know it since a long time.
It is because same stuff is run for "mkbackup" and "mkrescue".
I had a look but found no time to properly clean it up.
Things are too much interwoven for a quick and clean fix.

**Comment by jsmeix** [comment]
The root cause is that both WORKFLOW_mkbackup
and WORKFLOW_mkrescue need to run the 'prep' stage
and the 'prep' stage contains
prep/NETFS/default/070_set_backup_archive.sh

Or in other words:
Creating the backup is implemented intermixed
with creating the rescue/recovery system
but actually creating the backup happens
usually after creating the rescue/recovery system
except for WORKFLOW_mkbackup on USB where
things are additionally intermixed in another way.

**Comment by gdha** [comment]
@jsmeix Thanks Johannes for your review. I will try to fix this one later this month.

**Comment by jsmeix** [comment]
Nothing that needs to be done for ReaR 2.3
so that I set the milestone to ReaR 2.4

**Comment by gdha** [comment]
````
mkbackuponly-workflow.sh:    SourceStage "prep"
mkbackup-workflow.sh:	SourceStage "prep"
mkopalpba-workflow.sh:	SourceStage "prep"
mkrescue-workflow.sh:	SourceStage "prep"
````
are the workflows using the **prep** phase

**Comment by jsmeix** [comment]
This needs a more careful analysis whether or not
usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
still works o.k. when the variable backuparchive is no longer set in
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
in case of the 'mkrescue' workflow.

See
https://github.com/rear/rear/pull/2063#issuecomment-469197065

**Comment by jsmeix** [comment]
With
https://github.com/rear/rear/commit/77cb3c23ea45598aafa628d6e5b4afec75030210
and
https://github.com/rear/rear/commit/4e037335c3345cda377a2df3cde0253ce7b349ae
I added comments to
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
and
usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
that describe the above described interdependency between
prep/NETFS/default/070_set_backup_archive.sh and
output/ISO/Linux-i386/810_prepare_multiple_iso.sh
that exists except for the mkrescue workflow.
