### ISSUE TITLE
prolient dl380 Gen7 network not coming up

### ISSUE THREAD

**Issue by razorfish-sl** [rear/rear#1364]
Rear is not discovering any networking infrastructure (missing drivers?) when a recovery disk is moved from  a different manufactures kit.  other ->DL380 gen7

Is it possible to  run "rear" on a fully configured  DL380 then use the  initrd.cgz from that image & transplant it into the other systems boot media to bring the networking on line?

both systems are running centos7 & the same versions.
disk partitioning is the same.

**Comment by jsmeix** [comment]
@razorfish-sl 
regardless that I have no experience at all with things
like "prolient dl380 Gen7" or "DL380" I wonder what
exactly you mean with "missing drivers?"

If you mean that certain kernel modules are not included
in the rescue/recovery system, have a look at the current
newest GitHub ReaR master where there is now
support for some new special MODULES values 
MODULES=( 'all_modules' ) 
MODULES=( 'loaded_modules' ) 
MODULES=( 'no_modules' ) 
This way users can better specify what kernel modules 
get included in the rescue/recovery system. 
See the explanation in default.conf and the 
issues https://github.com/rear/rear/issues/1202 
and https://github.com/rear/rear/issues/1355 

For system migration I would recommend to use
MODULES=( 'all_modules' ) 
to be on the safe side.

**Comment by jsmeix** [comment]
And regarding having all firmware files in the recovery system
(some NICs need that), see FIRMWARE_FILES in default.conf
and https://github.com/rear/rear/issues/1216

**Comment by jsmeix** [comment]
I assume "no news is good news" so that it can be closed.

@razorfish-sl 
I think you can still add comments even when an issue is closed.
If the issue still exists, you can reopen it but then provide
more specific information so that others have a better chance
to imagine what might go wrong on your particular system, see
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
and also see "Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by razorfish-sl** [comment]
OK I think i have tracked this down on proliant systems.

Normally in /sys/class/net/
There are link files for each Network interface, these are linked in to  the PCIE tree.

It seems that IF you move a rear recovery from another system to the proliant, the network  link files are NOT regenerated.
This means that the network cannot be configured and you cannot get a net connection.

maybe the 'proliants' have something weird with their PCI tree due to all the embedded chips.
