### ISSUE TITLE
rear recover does not label disk partitions

### ISSUE THREAD

**Issue by cal-s** [rear/rear#137]
Net certain if this affects only md->sd restores or sd->sd as well

disklabels are collected in layout/prepare/GNU/Linux/13_include_filesystem_code.sh but isn't subsequently being used during restore-time filesystem creation.  This affects grub.conf and fstab,  which can describe partitions as labels but not as UUIDs (CentOS5).  Rear does collect and restore UUIDs from disklayout.conf:

fs /dev/sda1 /boot ext2 uuid=996f046e-7da7-4c7e-8c70-1c1cdfc16037 label= blocksize=1024 reserved_blocks=5% max_mounts=27 check_interval=180d bytes_per_inode=4092 options=rw

> blkid /dev/sda1
/dev/sda1: LABEL="/boot" UUID="996f046e-7da7-4c7e-8c70-1c1cdfc16037" TYPE="ext2"

The disklabel was hand-applied using tune2fs

**Comment by gdha** [comment]
fills up the queue and nothings has been done - so better close it for now
