### ISSUE TITLE
Provide security recommendations for ReaR developers

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1371]
I suggest to provide security recommendations
for ReaR developers at
https://github.com/rear/rear/wiki/Developers-Guide

I noticed
http://yastgithubio.readthedocs.io/en/latest/security-tips/
and I think basically the same applies to ReaR.

Furthermore I wonder if we should perhaps additionally
provide security recommendations for ReaR users
in a doc/user-guide/security_recommendations.adoc
file.

What do you think?

**Comment by schlomo** [comment]
Can you please tell us some specific examples how you see them applied to ReaR?
