### ISSUE TITLE
Make ReaR safe against blanks or special characters in file and directory names

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1372]
In general ReaR is not safe against whitespace characters
or other special characters or non-ASCII characters
in file and directory names and other names and values
that matter for ReaR (e.g. file and directory names that
are only in the backup should not matter for ReaR).

Cf. https://github.com/rear/rear/issues/580

**Comment by jsmeix** [comment]
Meanwhile I think it is in practice not worth the effort
to make all the scripts in ReaR safe against blanks
in file names and other values that matter for ReaR.

Reasoning:

ReaR is written in bash and meant to be easily
adapted and enhanced by its users.

Adaptions and enhancements by ReaR users
should be o.k. for ReaR when they work
as usual bash scripts do.

ReaR works how bash works and
bash separates values based on $IFS and
$IFS is by default 'space' 'horizontal tab' and 'new line'.

Therefore for ReaR 'space' 'horizontal tab' and 'new line'
are separators for values and using that separators inside
a single name or value just calls for failures.

Because ReaR is meant that those who use ReaR
are the same as those who adapt and enhance ReaR,
it is in practice impossible to enfore bash scripting rules
so that all is safe against blanks or special characters
in names and values that are used in the scripts.

In particular I will never ever find the time to check
all the scripts in ReaR neither will I find the time to
verify each user contribution whether or not it is safe
against blanks or special characters in names and values.
If someone else will do it - perfectly fine for me -  I set
"needs sponsorship" for this part.

But I think it should be documented (which I could do)
that for ReaR 'space' 'horizontal tab' and 'new line' are
separators for values and using that separators inside
a single name or value just calls for failures - I set
"documentation" for this and assign it to me.

**Comment by schlomo** [comment]
I try to point out in PRs when I think that a variable lacks quoting in a dangerous way. As `test` takes only single arguments it is actually very important to quote there and AFAIK we do so in most or all cases.

IMHO the problem is mostly related to URLs. Since we call them URLs we should consider to also support URI-encoded content of these variables which would probably solve that issue as well.

And finally, I would hope that one of the users who actually has the problem would contribute a PR fixing the files that are relevant to them.

**Comment by jsmeix** [comment]
Some time ago I had "fun" with URI-encoding
and got almost toast in encoding hell.
I would appreciate GitHub pull requests
that implement such functionality properly in ReaR.
But I won't do that myself (except my employer forced me
because such functionality in ReaR was considered by my
employer to be more important than other things ;-)

For the fun of 'test' it is sometimes very important to not quote there:
<pre>
# foo="" ; test "$foo" && echo foo set || echo foo not set
foo not set

# foo=" " ; test "$foo" && echo foo set || echo foo not set
foo set

# foo=" " ; test $foo && echo foo set || echo foo not set
foo not set
</pre>
