### ISSUE TITLE
Does ReaR work with EMC Powerpath multipathing software?

### ISSUE THREAD

**Issue by tomcombs** [rear/rear#1377]
I'm trying to use ReaR 2.0 to recover a RHEL7 host that boots from a SAN disk and uses EMC powerpath for the multipathing software. I've been going around and around trying to get it to work with no luck but then again I am new to ReaR. Before adding configuration files, I'd like to know if using EMC Powerpath is something that has already been looked at and deemed not possible. 

Thanks, Tom

**Comment by gdha** [comment]
@tomcombs SAN disks using EMC powerpath should work with ReaR v2.2 and beyond.
