### ISSUE TITLE
'rear recover' errors out in FindStorageDrivers () with: "FindStorageDrivers called but STORAGE_DRIVERS is empty ..."

### ISSUE THREAD

**Issue by genghongxiang** [rear/rear#1379]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.1 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
<pre>
LSB Version:	:base-4.0-ia32:base-4.0-noarch:core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-   noarch:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 6.0 (Final)
Release:	6.0
Codename:	Final
</pre>

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
GRUB_RESCUE=1
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="file:///root/sdb"
</pre>

* Are you using legacy BIOS or UEFI boot?
No

* Brief description of the issue:
<pre>
findStorageDrivers calls but STORAGE_DRIVERS is empty and no builtin storage modules found
</pre>

* Work-around, if any:

**Comment by jsmeix** [comment]
@genghongxiang 
if I understand your brief description of the issue correctly
ReaR errors out for you in FindStorageDrivers () with
the error message
<pre>
FindStorageDrivers called but STORAGE_DRIVERS is empty and no builtin storage modules found
</pre>

STORAGE_DRIVERS is set in
usr/share/rear/rescue/GNU/Linux/230_storage_and_network_modules.sh
and in
usr/share/rear/verify/GNU/Linux/230_storage_and_network_modules.sh
(which is a symbolic link to the former) via
<pre>
STORAGE_DRIVERS=( $( find_modules_in_dirs /lib/modules/$KERNEL_VERSION/kernel/drivers/{block,firewire,ide,ata,md,message,scsi,usb/storage} ) )
</pre>

To find out why this results an empty STORAGE_DRIVERS array
in your particular case one needs to inspect the ReaR log file.

Regarding how to get the ReaR log file see
"Debugging issues with Relax-and-Recover" see
https://en.opensuse.org/SDB:Disaster_Recovery

Also inspect in the rescue/recovery system what
kernel modules are there in /lib/modules
in your particular case.

Some general information:

STORAGE_DRIVERS is related to kernel modules.

Perhaps it helps to explicitly specify which kernel modules
should be included in the rescue/recovery system
e.g. include all kernel modules to be on the safe side via
<pre>
MODULES=( 'all_modules' )
</pre>
cf. "MODULES" in usr/share/rear/conf/default.conf

**Comment by jsmeix** [comment]
@genghongxiang 
for further debugging you could also re-run on your
original system "rear -d -D mkbackup/mkrescue" with
<pre>
KEEP_BUILD_DIR="yes"
</pre>
in your etc/rear/local.conf file and then inspect if the contents
of your $TMPDIR/rear.XXXXXXXXXXXXXXX/rootfs/
look o.k. - in particular whether or not all needed
kernel modules are there.

**Comment by jsmeix** [comment]
Assuming "no news is good news"
i.e. the issue is sufficiently answered
so that it can be closed.
