### ISSUE TITLE
debian stretch: sshd wont start as /run/sshd is missing from recovery image

### ISSUE THREAD

**Issue by abbbi** [rear/rear#1381]
* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.1 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a): Debian Stretch
* Work-around, if any: create directory /run/sshd

sshd wont start as /run/sshd is missing from the image on debian stretch.
Rest of the recovery went flawlessly.

**Comment by gdha** [comment]
With commit https://github.com/rear/rear/commit/e67fbb61fc8a32e2558abec1b77b9ddf01044c97 we can close this issue

**Comment by jsmeix** [comment]
@gdha 
note that commit https://github.com/rear/rear/commit/e67fbb61fc8a32e2558abec1b77b9ddf01044c97
is not in the master branch but in the schlomo-2017-06 branch.
To get the issue fixed in ReaR 2.2 the schlomo-2017-06 branch
would need to be merged into the master branch.

**Comment by jsmeix** [comment]
Meanwhile it is in the master branch.
