### ISSUE TITLE
REAR iso maps scsi controllers in different order than native SUSE on VMWare with different cntrollers

### ISSUE THREAD

**Issue by dzegelman** [rear/rear#1384]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 1.19
* OS version (cat /etc/rear/os.conf or lsb_release -a): SUSE Linux x64 11 SP3
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): default
* Are you using legacy BIOS or UEFI boot? BIOS, VMware
* Brief description of the issue: rear recovery iso has different order of scsi hosts initialization what creates problem to recover. When booting from REAR iso lsscsi gives different ids for scsi controllers. Hosts has 4 various controllers LSI and  Paravirtual
* Work-around, if any: No workaround found

**Comment by schlomo** [comment]
Please provide both from the working source and the troubled rescue system
* `dmesg` which shows all the SCSI relevant parts, both about drivers and devices
* `lspci`
* `lsscsi -kds`
* `lsmod`

**Comment by dzegelman** [comment]
Thanks a lot for the answer.

Original Situation VMWare SUSE 11 Enterprise SP3 with shared drives running Oracle Database with ASM:
rn2inssv268:~ # lsscsi -H
[0]    mptspi
[1]    ata_piix
[2]    ata_piix
[3]    vmw_pvscsi
[4]    vmw_pvscsi
[5]    vmw_pvscsi
rn2inssv268:~ #

SCSI adapters order is correct like in a vmx file

RESCUE statsus (rear 1.17, 1.19, 1.21 was tested):
[0]    vmw_pvscsi
[1]    vmw_pvscsi
[2]    vmw_pvscsi
[3]    mptspi
[4]    ata_piix
[5]    ata_piix

Order is different. All other required information is attached.

Thanks a lot in advance,

Dan Zegelman

**Comment by schlomo** [comment]
Did you send this via email? I think that GitHub strips attachments. Please upload directly via the GitHub web UI.

**Comment by dzegelman** [comment]
Requested files uploaded

**Comment by dzegelman** [comment]
[dmesg.orig.docx](https://github.com/rear/rear/files/1072014/dmesg.orig.docx)
[lsmod.rescue.docx](https://github.com/rear/rear/files/1072019/lsmod.rescue.docx)
[lspci.orig.docx](https://github.com/rear/rear/files/1072022/lspci.orig.docx)
[lspci.rescue.docx](https://github.com/rear/rear/files/1072021/lspci.rescue.docx)
[lsscsi.orig.docx](https://github.com/rear/rear/files/1072018/lsscsi.orig.docx)
[lsscsi.rescue.docx](https://github.com/rear/rear/files/1072020/lsscsi.rescue.docx)
[dmesg.orig.docx](https://github.com/rear/rear/files/1072023/dmesg.orig.docx)
[dmesg.rescue.docx](https://github.com/rear/rear/files/1072025/dmesg.rescue.docx)
[lsmod.orig.docx](https://github.com/rear/rear/files/1072024/lsmod.orig.docx)

**Comment by schlomo** [comment]
Note: May be also related to #1327

**Comment by dzegelman** [comment]
Yes, we had behavior mentioned in #1327, it was relevant only for disks remapping and we overcome it by pressing "y"  through recovery flow :) and later hacked scripts to avoid it. Can we implement any workaround for now? Thanks, Dan

**Comment by schlomo** [comment]
After reading the change in #1372 I realized that there we only added `--force` to the `wipefs` call and not to the `mkfs.ext?` calls. I'll have a look into fixing this.

**Comment by jsmeix** [comment]
I think the whole module loading in the recovery system
currently works too much automated that leads to
unwanted results. For details see
https://github.com/rear/rear/pull/909#issuecomment-309693663
