### ISSUE TITLE
RFC: A future ReaR major version that does away with all the old stuff?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1390]
At least @schlomo and @jsmeix are
dreaming about a future ReaR major version
that does away with all the old stuff to make
the code much simpler if we could limit support
to "nowadays usually used stuff".

Related issues are
https://github.com/rear/rear/issues/1173
https://github.com/rear/rear/issues/764

**Comment by jsmeix** [comment]
I have a hopefully useful idea how we could get rid of all old stuff
in a particular part of the ReaR code (but it is a core part of ReaR):
https://github.com/rear/rear/issues/791#issuecomment-406513969

**Comment by gdha** [comment]
@rear/contributors Proposal could be that after we release **ReaR 2.5** we start working on a new branch for **ReaR 3.0**. If a sub-release for **ReaR 2.x** would still be necessary that would be still possible of course, but on a sponsored basis?

**Comment by pcahyna** [comment]
See the discussion in #699 about empty arrays, which are not well supported in bash 3, and using them properly needs requiring bash 4.
