### ISSUE TITLE
SELinux autorelabelling possibly inconsistently implemented

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1404]
While working on https://github.com/rear/rear/pull/1401
I noticed that SELinux autorelabel stuff in ReaR
is possibly inconsistently implemented.

Currently it seems SELinux autorelabelling is implemented
in some backup method specific scripts, namely:
<pre>
# (cd usr/share/rear/ ; find . | xargs grep -l '\.autorelabel' )

./backup/NETFS/GNU/Linux/600_start_selinux.sh
./backup/NETFS/GNU/Linux/620_force_autorelabel.sh
./backup/RSYNC/GNU/Linux/610_start_selinux.sh
./backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
./prep/NETFS/GNU/Linux/200_selinux_in_use.sh
./prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
./restore/FDRUPSTREAM/default/270_selinux_considerations.sh
./restore/NETFS/default/500_selinux_autorelabel.sh
./restore/default/500_selinux_autorelabel.sh
./restore/BLOCKCLONE/default/500_selinux_autorelabel.sh
</pre>

I am not at all a SELinux expert but I think
SELinux stuff is generic functionality that should
be implemented in a generic ReaR script so that
SELinux stuff (in particular SELinux autorelabelling)
works independent of the backup method.

**Comment by schlomo** [comment]
Maybe the script in `restore/default` makes all the other files obsolete?
