### ISSUE TITLE
REAR on Power (SLES): use original Kernel CMD-Line

### ISSUE THREAD

**Issue by abbbi** [rear/rear#1420]
hi,

just as a discussion for that topic: Currently on PPC64 REAR defines the CMDLine of the
linux kernel in:

```
./usr/share/rear/conf/Linux-ppc64.conf
KERNEL_CMDLINE="LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us console=hvc0"
```

on SLES Systems however, there exists:

/etc/sysconfig/bootloader

which contains the original CMDLine and the fallback CMD line like this:

```
LOADER_TYPE="ppc"
DEFAULT_NAME="SLES11_SP4"
DEFAULT_APPEND="quiet sysrq=1 insmod=sym53c8xx insmod=ipr crashkernel=512M-:256M"
DEFAULT_VGA=""
FAILSAFE_APPEND="quiet sysrq=1 insmod=sym53c8xx insmod=ipr crashkernel=512M-:256M"
FAILSAFE_VGA=""
XEN_KERNEL_APPEND="quiet sysrq=1 insmod=sym53c8xx insmod=ipr"
```

so i think it would make sense to:

1) use KERNEL_CMDLINE if it is set in the config to override default with special user settings
2) if KERNEL_CMDLINE is not set try to get it from /etc/sysconfig/bootloader
3) if /etc/sysconfig/bootloader is not found, stick with the default that is currently used

Would it make also sense to create yaboot.conf with multiple boot options even if the failsave
and the normal boot on SLES seem to be the same in default installation?

**Comment by schabrolles** [comment]
@abbbi, since #1442, I remove this specific KERNEL_CMDLINE for power (both ppc64/ppc64le).

Power are now using the same rear KERNEL_CMDLINE than other arch.

Does it answer to you question ?

**Comment by jsmeix** [comment]
I assume with https://github.com/rear/rear/pull/1442 merged
this issue is fixed.
If not, this issue can be reopened or a new issue should be
created if there is a subsequent related but different problem.
