### ISSUE TITLE
BACKUP_URL target should include/append backup date

### ISSUE THREAD

**Issue by cal-s** [rear/rear#143]
Saving via nfs:// should probably append the creation date-time associated with the hostname, otherwise a subsequent mkbackup will overwrite the previous one.  We export NFS dirs with root_squash, so it's not possible for root on the remote to create a dated subdirectory via its autofs paths in which to save to latest mkbackup.  I seem to recall that this is done for USB-based mkbackups.

eg: local.conf:

BACKUP_URL=nfs://host/xfs/backup/rear

mkbackup will create t/xfs/backup/rear/host-fqdn

containing that host's ISO and tarbball

Preferably, ReaR should create the mkbackup in /xfs/backup/rear/host-fqdn/date or /xfs/backup/rear/host-fqdn-date

**Comment by gdha** [comment]
no time to work on this - sorry
