### ISSUE TITLE
TSM Client 8.1.2 use other files for authentication

### ISSUE THREAD

**Issue by RolfWeilen** [rear/rear#1452]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / 2017-07-20
* OS version (cat /etc/rear/os.conf or lsb_release -a):
OS_VENDOR=RedHatEnterpriseServer                                                                                                                                             
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
# cat /etc/rear/site.conf
AUTOEXCLUDE_MULTIPATH=N
OUTPUT=ISO
#OUTPUT_URL=file:/var/lib/rear/output/
OUTPUT_URL=null
ISO_DEFAULT=manuel
TIMESYNC=NTP
BACKUP=TSM
TSM_RESULT_SAVE=n
TSM_RESULT_FILE_PATH=
USE_DHCLIENT=y
USE_STATIC_NETWORKING=n
# Include only rootvg
ONLY_INCLUDE_VG=(res9910vg00)
# Add an group Entry
GRUB_RESCUE=n
# Warten wir mal 360Tage
WAIT_SECS=31104000
# Login via ssh auf iso
SSH_ROOT_PASSWORD=rear
````
* Are you using legacy BIOS or UEFI boot?
BIOS
* Brief description of the issue:
New TSM Client use new file for authentication. The TSM.PWD file no longer exists. 
* Work-around, if any:
Changed file /usr/share/rear/conf/default.conf
old: - COPY_AS_IS_TSM=( /etc/adsm/TSM.PWD /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )
new: - COPY_AS_IS_TSM=( /etc/adsm/TSM.* /etc/adsm/spclicert.* /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )
or simpler: COPY_AS_IS_TSM=( /etc/adsm /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )

**Comment by RolfWeilen** [comment]
new files in /etc/adsm
-rw-rw-rw-    1 root root    80 Aug 23 09:41 spclicert.rdb
-rw-rw-rw-    1 root root    80 Aug 23 09:41 spclicert.crl
-rw-------    1 root root   193 Aug 23 09:41 spclicert.sth
-rw-rw-rw-    1 root root  5080 Aug 23 09:41 spclicert.kdb
-rw-------    1 root root   193 Aug 23 09:41 TSM.sth
-rw-rw-rw-    1 root root   645 Aug 23 09:41 TSM.IDX
-rw-rw-rw-    1 root root  3260 Aug 23 09:41 TSM.KDB

**Comment by gdha** [comment]
@RolfWeilen So the work-around `COPY_AS_IS_TSM=( /etc/adsm /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )` update in `default.conf` would fix your issue, right?
@schabrolles Sebastien, I believe you are using TSM also - can you comment on this?

**Comment by schabrolles** [comment]
I run TSM 8.1.0, It seems to be new in 8.1.2. https://www.ibm.com/support/knowledgecenter/en/SSEQVQ_8.1.2/client/c_secure_pwd.html

I agree with @RolfWeilen proposal  `COPY_AS_IS_TSM=( /etc/adsm /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )`

I can make a in test 8.1.2 next week when I will be back to the office.

**Comment by RolfWeilen** [comment]
Hi
Yes we are using TSM as backup solution. I have tested this change in COPY_AS_IS_TSM with the new tsm client 8.1.2 and it works. If those file are missing you have to run the command dsmc, which will create this files, before run rear recover command. In this case you must now the password from the tsm node.
So we have an workaround for this situation.

**Comment by RolfWeilen** [comment]
Hi

Should I install the new master for testing?

Regards
Rolf

Freundliche Grüsse

Rolf Weilenmann | Systemspezialist
Suva | Rösslimattstrasse 39 | 6002 Luzern
041 419 64 79

**Comment by gdha** [comment]
@RolfWeilen Yes the master repo contains the fixes.

**Comment by schabrolles** [comment]
@RolfWeilen did you find time to test ReaR master branch to confirm if it solves your issue regarding TSM authentication in rescue image ?

**Comment by jsmeix** [comment]
Because "no news is good news" I assume that since
https://github.com/rear/rear/pull/1461
is merged it works so that I can close this issue.
If the same issue persists this issue report can be reopened but
new and different issues need new and separated issue reports.
