### ISSUE TITLE
Debian/Ubuntu package version 2.2 are named 2.1?

### ISSUE THREAD

**Issue by gdha** [rear/rear#1465]
* rear version (/usr/sbin/rear -V): 2.2
* OS version (cat /etc/rear/os.conf or lsb_release -a): ubuntu14/16
* Brief description of the issue: stable deb packages of 2.2 are called 2.1 on OBS
See https://build.opensuse.org/package/live_build_log/Archiving:Backup:Rear/rear-2.2/xUbuntu_14.04/x86_64
````
[   40s] Attempting automatic discovery of a suitable source archive.
[   40s] Source archive chosen for transformation: rear-2.2.tar.gz
[   40s] No DEBTRANSFORM-FILES-TAR line in the .dsc file.
[   40s] Attempting automatic discovery of a debian archive.
[   40s] Hardlinking //usr/src/packages/SOURCES/rear-2.2.tar.gz to //usr/src/packages/SOURCES.DEB/rear_2.1.orig.tar.gz
[   40s] files 1071edd829a5faa035472ab3f9c69be5 4733655 rear_2.1.orig.tar.gz
[   40s] Scanning //usr/src/packages/SOURCES.DEB/rear_2.1.orig.tar.gz...
[   40s] Generating //usr/src/packages/SOURCES.DEB/rear_2.1-0git201706261424.diff
[   40s] Processing file "//usr/src/packages/SOURCES/debian.copyright"...
[   40s] Processing file "//usr/src/packages/SOURCES/debian.changelog"...
[   40s] Processing file "//usr/src/packages/SOURCES/debian.control"...
[   40s] Processing file "//usr/src/packages/SOURCES/debian.compat"...
[   40s] Processing file "//usr/src/packages/SOURCES/debian.rules"...
[   40s] Writing //usr/src/packages/SOURCES.DEB/rear_2.1-0git201706261424.dsc
...
[   85s] DEBS/rear_2.1-0git201706261424_amd64.changes
[   85s] DEBS/rear_2.1.orig.tar.gz
[   85s] DEBS/rear_2.1-0git201706261424.diff.gz
[   85s] DEBS/rear_2.1-0git201706261424_amd64.deb
[   85s] DEBS/rear_2.1-0git201706261424.dsc
````
Guess something went wrong in our numbering scheme when we build are new packages?
@schlomo Could you have have a look at?

**Comment by schlomo** [comment]
Oh no, this is indeed not good. @jsmeix any idea? My OBS days are long over unfortunately.

**Comment by schlomo** [comment]
Good thing that we have an official Debian package that is built independently.

**Comment by gdha** [comment]
In download section of stable rear I find unstable diff/dsc which we do not find for older releases. I think this brings us into problems with the 2.2 build
````
[   ] rear_2.1-0.dsc                         07-Jun-2017 11:26  279    Details
[   ] rear_2.1-0git201706261424.diff.gz      01-Sep-2017 08:59  1.0K   Details
[   ] rear_2.1-0git201706261424.dsc          01-Sep-2017 08:59  695    Details
[   ] rear_2.1.orig.tar.gz                   07-Jun-2017 11:26  435K   Details

````

**Comment by jsmeix** [comment]
I think this is not an issue of the Open Build Service
but an issue of how the package is built for Debian/Ubuntu
(i.e. an issue in the Archiving:Backup:Rear/rear-2.2 sources
therein probably in the debian related files).
Unfortunately I know nothing at all about how to build
packages for Debian/Ubuntu (I only know about RPM).
By blind inspecting the Archiving:Backup:Rear/rear-2.2
source files I found in rear.dsc:
<pre>
Version: 2.1-0git201706261424
</pre>
where the value matches.

**Comment by gdha** [comment]
I noticed that the Snapshot series for Debian and Ubuntu are also broken:
````
[   88s] dpkg-deb: building package 'rear' in '../rear_2.1-0git201706261424_amd64.deb'.
[   89s]  dpkg-genchanges  >../rear_2.1-0git201706261424_amd64.changes
[   89s] dpkg-genchanges: warning: the current version (2.1-0git201706261424) is earlier than the previous one (2.2-0git.0.81757d4.unknown.changed)
````

**Comment by gdha** [comment]
I found out that OBS requires the existence of a **description** file (`rear.dsc`) which was left out during working on issue #1362. In OBS there was one there - albeit an old one pointing to 2.1-0git201706261424 which explained that this particular version was build.

**Comment by gdha** [comment]
OK the Debian/Ubuntu build went fine on OBS now with a rear.dsc being there and containing the correct versions nr

**Comment by gdha** [comment]
Fixed on OBS manually the rear.dsc file on the stable branch of **rear-2.2**  and now the rear-2.2 versions for Debian and Ubuntu are build correctly on OBS.
I think we are good the close this issue
