### ISSUE TITLE
SUSE 12 SP1 Btrfs filesystem failed to restore

### ISSUE THREAD

**Issue by metro1234** [rear/rear#1470]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
1.17.2 and 2.2-3
* OS version (cat /etc/rear/os.conf or lsb_release -a):
<pre>
LSB Version:    n/a
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server for SAP Applications 12 SP1
Release:        12.1.0.1
Codename:       n/a
</pre>
cat /etc/rear/os.conf
<pre>
OS_VENDOR=SUSE_LINUX
OS_VERSION=12
</pre>
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
OUTPUT=ISO
OUTPUT_URL="nfs://10.10.10.10/esx1/osbackup/"
BACKUP=NETFS
BACKUP_URL="nfs://10.10.10.10/esx1/osbackup/"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp/*' '/var/crash' '/hana')
NETFS_KEEP_OLD_BACKUP_COPY=
</pre>
* Are you using legacy BIOS or UEFI boot?
legacy BIOS
* Brief description of the issue:

Taken backup:
<pre>
>  rear -v mkbackup
</pre>
tried to restore
<pre>
>  rear -v recover 
</pre>
it got failed and attached zip for logs and screensheet.

It has lot of subfile systems

Below are the df -h info:
<pre>
df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/system-root   38G  4.4G   34G  12% /
devtmpfs                 5.9G     0  5.9G   0% /dev
tmpfs                     11G  136K   11G   1% /dev/shm
tmpfs                    5.9G  9.8M  5.9G   1% /run
tmpfs                    5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/mapper/system-root   38G  4.4G   34G  12% /.snapshots
/dev/mapper/system-root   38G  4.4G   34G  12% /var/tmp
/dev/mapper/system-root   38G  4.4G   34G  12% /var/spool
/dev/mapper/system-root   38G  4.4G   34G  12% /var/log
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/pgsql
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/named
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/mysql
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/mariadb
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/mailman
/dev/mapper/system-root   38G  4.4G   34G  12% /var/lib/libvirt/images
/dev/mapper/system-root   38G  4.4G   34G  12% /var/crash
/dev/mapper/system-root   38G  4.4G   34G  12% /var/opt
/dev/mapper/system-root   38G  4.4G   34G  12% /usr/local
/dev/mapper/system-root   38G  4.4G   34G  12% /tmp
/dev/mapper/system-root   38G  4.4G   34G  12% /srv
/dev/mapper/system-root   38G  4.4G   34G  12% /home
/dev/mapper/system-root   38G  4.4G   34G  12% /opt
/dev/mapper/system-root   38G  4.4G   34G  12% /boot/grub2/i386-pc
/dev/mapper/system-root   38G  4.4G   34G  12% /boot/grub2/x86_64-efi
/dev/sr0                 3.1G  3.1G     0 100% /run/media/root/SLE-12-SP1-SAP-DVD-x86_6402691
</pre>
* Work-around, if any: No 

Please let me know for any more details

[rear-hpe990-suse.zip](https://github.com/rear/rear/files/1273810/rear-hpe990-suse.zip)

**Comment by gozora** [comment]
Please check [configuration examples ](https://github.com/rear/rear/tree/master/usr/share/rear/conf/examples) ?

V.

**Comment by metro1234** [comment]
@gozora ,

Thanks a lot. I used configuration examples.

**Comment by gozora** [comment]
@metro1234 did it work?

If so, please close this issue ...

V.

**Comment by metro1234** [comment]
Yes It worked and closing Case

**Comment by metro1234** [comment]
I have used configuration examples provided in Suse OS as suggested by Gozora. It works fine

**Comment by jsmeix** [comment]
@gozora 
thanks for your help!
