### ISSUE TITLE
Clean up vagrant and virtualbox detection

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1474]
Currently vagrant and VirtualBox support is detected in [usr/share/rear/rescue/default/550_vagrant.sh](https://github.com/rear/rear/blob/2c12a52b3322f833c81cae2a8bc5baa799c3187d/usr/share/rear/rescue/default/550_vagrant.sh).

TODO
- [x] split into two scripts, one for vagrant and one for VirtualBox
- [ ] use `getent` to access the passwd, group and shadow databases
- [ ] don't assume that the password is hashed with MD5, if there is no password in the source system then there doesn't need to be one in the rescue system
- [ ] don't assume that admin is a relevant group (I actually doubt that this works since we *don't* include sudo)
- [ ] add support for more recent VBoxService implementations that use systemd or upstart

**Comment by jsmeix** [comment]
Because @gdha is the only author of
usr/share/rear/rescue/default/550_vagrant.sh
as far as
"git log -p --follow usr/share/rear/rescue/default/550_vagrant.sh"
tells, I dare to assign this issue to him - at least initially.

**Comment by gdha** [comment]
Some background information about the origin of the script #486 and https://gist.github.com/Reiner030/4b602289320f3c2ed4e7

**Comment by gdha** [comment]
As @schlomo has started to split up the script in two pieces I prefer that Schlomo also owns the issue as well. Honours to the one who works on it ;-)

**Comment by schlomo** [comment]
Haha, I forgot this one and just thought again "why does virtualbox depend on vagrant?". Can't promise to do all of that, though.

**Comment by gdha** [comment]
@schlomo On Ubuntu16.04 we run into trouble with `/opt/VBoxGuestAdditions-5.1.26` inclusion:
See https://github.com/gdha/rear-automated-testing/issues/35 for the error report.

I wonder if we really need all of this?
`VBOX_COPY_AS_IS=( /etc/init.d/vboxadd* /opt/VBoxGuestAdditions-* /usr/sbin/VBoxService )` from script `prep/GNU/Linux/280_include_virtualbox.sh`
