### ISSUE TITLE
Rear terminates if the /boot/efi is not mounted

### ISSUE THREAD

**Issue by jmazanek** [rear/rear#1478]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): rear-2.00
* OS version (cat /etc/rear/os.conf or lsb_release -a):Red Hat Enterprise Linux Server release 7.4 (Maipo)
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=RSYNC
BACKUP_URL=rsync://192.168.122.43/home/rear_bk
OUTPUT_URL=rsync://192.168.122.43/home/rear_rcv
GRUB_RESCUE=y
* Are you using legacy BIOS or UEFI boot? no
* Brief description of the issue:
It has been reported by  the users, that rear aborts with "ERROR: Cannot find required programs: efibootmgr"  message even if the directory  /boot/{efi|EFI} exists ( as that previous problem is described here: https://github.com/rear/rear/issues/1239 and fixed here: https://github.com/rear/rear/pull/1225) , unless the directory is actually mounted.
* Work-around, if any:
The following change seems to fix the issue : https://github.com/rear/rear/pull/1477

**Comment by jsmeix** [comment]
According to
https://github.com/rear/rear/pull/1477#issuecomment-328515342
my quick attempt
https://github.com/rear/rear/commit/6e05b6f0e51fdfdf02c67edddb117b41a364c6f4
to fix
https://github.com/jsmeix/rear/commit/9bb07357ac7892ad7d82c5438e76e57a44d21113#commitcomment-24177948
broke it for the non-UEFI case and reintroduced this issue here.

**Comment by jsmeix** [comment]
Meanwhile I think my
https://github.com/rear/rear/commit/6e05b6f0e51fdfdf02c67edddb117b41a364c6f4
did not make anything worse that it was before because
https://github.com/rear/rear/pull/1477#issuecomment-328518336

**Comment by jsmeix** [comment]
This issue is fixed with
https://github.com/rear/rear/pull/1481
cf.
https://github.com/rear/rear/pull/1481#issuecomment-328791603
