### ISSUE TITLE
Rear fails to detect /dev/sdc1 format

### ISSUE THREAD

**Issue by deonlinux** [rear/rear#1482]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):Relax-and-Recover 2.1 / 2017-06-07
* OS version (cat /etc/rear/os.conf or lsb_release -a):
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 5.11 (Final)
Release:	5.11
Codename:	Final

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=USB
BACKUP=NETFS
USB_DEVICE=/dev/disk/by-label/REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
* Are you using legacy BIOS or UEFI boot?
Legacy

* Brief description of the issue:
During  mkrescue or mkbackup rear aborts with message:
BUG in /backup/rear-2.1/usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh:
'Filesystem for device '/dev/sdc1' could not be found'

* Work-around, if any:
None found yet. Production system has 2 drives mounted sda & sdb. sdc was formatted, e2label reports correct label.
Centos 5.11 system 
[rear-BS-demo.txt](https://github.com/rear/rear/files/1295384/rear-BS-demo.txt)

**Comment by gozora** [comment]
Did you format your usb device with `rear format <usb disk name>` command?

**Comment by deonlinux** [comment]
Good News, it seems rear-2.2 works on this system.
Currently busy creating a backup. It is in a remote location so will have to ask a techie to go there and reboot to test.

**Comment by jsmeix** [comment]
Because "no [further] news is good news" I just assume that since
https://github.com/rear/rear/issues/1482#issuecomment-328814771
ReaR 2.2 works so that I can close this issue.
If the same issue persists this issue report can be reopened but
new and different issues need new and separated issue reports.
