### ISSUE TITLE
back-port bugs reported in Debian

### ISSUE THREAD

**Issue by gdha** [rear/rear#1488]
* rear version (/usr/sbin/rear -V): > 2.2
* OS version (cat /etc/rear/os.conf or lsb_release -a): debian/ubuntu
* Brief description of the issue: back-port bugs reported in Debian
See https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=rear
And, also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849303
* Work-around, if any: apply the proposed changes if applicable

**Comment by jsmeix** [comment]
@gdha 
I am a bit astonished that you (or more generally that we
at ReaR upstream) need to do such things.
I would expect that the Debian ReaR package maintainer
submits their fixes to us upstream.
Or do I perhaps misunderstand something here?

**Comment by gdha** [comment]
@frediz Why did you not tell us about these modifications? See also #1163

**Comment by gdha** [comment]
All Debian related patches were incorporated, therefore, we can close this issue
