### ISSUE TITLE
Relax-and-Recover fails when /tmp is mounted noexec

### ISSUE THREAD

**Issue by schoekek** [rear/rear#150]
Hi,

i have this error since version 1.12...
I installed today the 1.13.0 from suse Buildservice on Debian 6.0.5.

many thx for ideas,

Karsten

**Comment by kollyma** [comment]
We are facing the same issue, because /tmp mouted with noexec permissions:
```
ERROR: Cannot test if the ReaR recovery system is usable because /tmp is mounted 'noexec'
Aborting due to an error, check /var/log/rear/rear-serverxy.log for details
```
set the TMDIR variable to fix the issue:
```
export TMPDIR='/var/tmp/' ; /usr/sbin/rear mkbackup 
```
