### ISSUE TITLE
ubuntu16.04: missing ldconfig.real

### ISSUE THREAD

**Issue by gdha** [rear/rear#1504]
* rear version (/usr/sbin/rear -V): 2.2 and above
* OS version (cat /etc/rear/os.conf or lsb_release -a): ubuntu 16.04
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): BACKUP=bareos
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: `/sbin/ldconfig.real` missing in rescue image.
````# file /sbin/ldconfig*
/sbin/ldconfig:      POSIX shell script, ASCII text executable
/sbin/ldconfig.real: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=334bc156192bd660fce221c25abf1471f2287d6b, stripped
````

* Work-around, if any: add /sbin/ldconfig.real

**Comment by jsmeix** [comment]
With
https://github.com/rear/rear/commit/80aaef44ee61ec2afa93530bd068ebbcc3eca9d2
others can now understand what that 'ldconfig.real' stuff
in 550_copy_ldconfig.sh is about.
