### ISSUE TITLE
ReaR Backup On Multiple USB Disks

### ISSUE THREAD

**Issue by dcz01** [rear/rear#1520]
#### ReaR Backup On Multiple USB Disks

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): ``Relax-and-Recover 2.2 / 2017-07-20``
* OS version (cat /etc/rear/os.conf or lsb_release -a):
````
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6
````
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
OUTPUT=ISO
OUTPUT_URL=file:///tmp/rear
BACKUP=NETFS
BACKUP_PROG=tar
BACKUP_PROG_CRYPT_ENABLED=1
BACKUP_PROG_CRYPT_KEY=brpbackup123
BACKUP_PROG_CRYPT_OPTIONS="/usr/bin/openssl aes256 -salt -k"
BACKUP_PROG_DECRYPT_OPTIONS="/usr/bin/openssl aes256 -d -k"
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
BACKUP_TYPE=incremental
FULLBACKUPDAY="Sat"
BACKUP_PROG_EXCLUDE=( '/tmp/*' '/dev/shm/*' $VAR_DIR/output/\* '/opt/tivoli/tsm/rear/*' '/mnt/*' '/media/*' '/var/lib/pgsql/*/data/base/*' '/var/lib/pgsql/*/data/global/*' '/var/lib/pgsql/*/data/pg*/*' '/var/lib/pgsql/*/backups/*' )
#NETFS_KEEP_OLD_BACKUP_COPY=y
USB_SUFFIX="$HOSTNAME"
SSH_ROOT_PASSWORD='$1$HGjk3XUV$lid3Nd3k01Kht1mpMscLw1'
````
* Are you using legacy BIOS or UEFI boot? BIOS.
* Brief description of the issue: Possibility to backup the system to more than only one usb drive.
* Work-around, if any: None.

When i tried to use in the site.conf ``BACKUP_URL=usb:///dev/disk/by-label/REAR-*`` i get the following error:
````
ERROR: Invalid scheme '' in BACKUP_URL 'usb:///dev/disk/by-label/REAR-*' valid schemes: nfs cifs usb tape file iso sshfs ftpfs
````

**Comment by gozora** [comment]
Check ["Using Multiple Backups for Relax-and-Recover"](https://github.com/rear/rear/blob/master/doc/user-guide/11-multiple-backups.adoc#using-multiple-backups-for-relax-and-recover)

V.

**Comment by dcz01** [comment]
@gozora Well i know that new feature but i can't use it in that case...
``In general multiple backups are **not supported** for BACKUP_TYPE=incremental or BACKUP_TYPE=differential because those require special backup archive file names.``

And the only thing i need is that i want to use more than only one usb backup drive but not parallel on the machine.
The idea was to let ReaR do backups one week on the first drive and then change the drive to the second and format it too with ReaR to use it.
But will the label of the drive be REAR-000 too like of the first one or will ReaR increment the label to REAR-001?
And then how to tell this to ReaR in the config?

At the end it should look like this:
````
REAR-000 -> 1. Week
REAR-001 -> 2. Week
REAR-002 -> 3. Week
````
So if one drive fails the backups are save on the other drives.

**Comment by jsmeix** [comment]
The label 'REAR-000' is hardcoded at various places in the code.

**Comment by jsmeix** [comment]
@dcz01 
in general regarding advanced backup functionality in ReaR see
the comments in usr/share/rear/conf/default.conf that read
<pre>
In general regarding advanced backup functionality
(like incremental and differential backup):
ReaR is primarily a disaster recovery tool to recreate
the basic system after a disaster happened.
ReaR is is neither a backup software nor a backup
management software and it is not meant to be one
(cf. "Relax-and-Recover versus backup and restore"
in https://en.opensuse.org/SDB:Disaster_Recovery).
In particular do not expect too much from ReaR's
internal backup methods like 'tar'.
For simple tasks ReaR's internal backup
methods should be o.k. but
ReaR's internal backup methods are not meant
as professional backup solutions.
In general the backup and restore of the files
is "external functionality" for ReaR.
ReaR only calls an external tool and that tool
does the backup and restore of the files.
Use a professional backup solution in particular
when you need advanced backup functionality.
</pre>

**Comment by dcz01** [comment]
Or will all usb drives have the same label REAR-000 when i format them with ReaR?
But then i should be able to use anyone of the three drives to restore the system?

**Comment by jsmeix** [comment]
I think, but I never tested it (I do not use backup on USB),
that any USB device that is formatted by "rear format"
gets the same label 'REAR-000' so that for restore you
can use any of them, but not two of them at the same time.

**Comment by dcz01** [comment]
Well when i can use all the three but not at the same time all is ok :-)
I don't need nothing more.
Then we can close this issue.

**Comment by jsmeix** [comment]
@dcz01 
please report if it actually works for you this way
(I am just curious).

**Comment by dcz01** [comment]
@jsmeix Yes it works good for me this way.
I always get the label "REAR-000" by the `rear format` command.

**Comment by jsmeix** [comment]
@dcz01 
many thanks for your confirmation that it works this way.

It helps (at least me) a lot to have an explicit feedback
when even "special things" actually work with ReaR.
