### ISSUE TITLE
ReaR Backup with CIFS SMB 2 configuration 

### ISSUE THREAD

**Issue by metro1234** [rear/rear#1531]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
RHEL 7.2
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
OUTPUT=ISO
OUTPUT_URL="cifs://1.1.1.1/public/"
BACKUP=NETFS
BACKUP_URL="cifs://1.1.1.1/public/"
NETFS_KEEP_OLD_BACKUP_COPY=
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp/*' '/var/crash'  '/proc/')
BACKUP_OPTIONS="username=testuser,domain=rear,vers=2.0"
</pre>
* Are you using legacy BIOS or UEFI boot?
UEFI
* Brief description of the issue:
Not able mount cifs mount (windows cifs share)
* Work-around, if any:
recent changes in windows it accept only smb 2.0 protocol and added vers=2.0
<pre>
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-sapprdhdb160.log
Password for testuser@//1.1.1.1/public/:  **********************
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
.
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
ERROR: Mount command 'mount -v -o rw,noatime,guest //172.17.87.15/public/ /tmp/rear.M6Wg09kHV49CmCZ/outputfs' failed.
Aborting due to an error, check /var/log/rear/rear-sapprdhdb160.log for details
Terminated
</pre>
It is using guest user

**Comment by gozora** [comment]
Hi, @metro1234 

Default options are used for mounting of your OUTPUT_URL, which is fully ok, as you did not explicitly specify them.

Try to add something like:
```
OUTPUT_OPTIONS="username=testuser,domain=rear,vers=2.0"
```
or if OUTPUT_OPTIONS should be same as BACKUP_OPTIONS add following line AFTER line with BACKUP_OPTIONS
```
OUTPUT_OPTIONS="$BACKUP_OPTIONS"
```

V.

**Comment by gdha** [comment]
@metro1234 Was the suggestion successful?

**Comment by gdha** [comment]
As no feedback came back we may assume the problem has been solved

**Comment by Randhirkarn0** [comment]
![image](https://user-images.githubusercontent.com/128147317/225895994-c7129041-4876-4548-ae85-d74342650846.png)
Hello Team,

unable to restore Rear Backup , see below error and suggest

**Comment by jsmeix** [comment]
@Randhirkarn0 
this issue is closed since a long time (since Nov. 2017).

Relax-and-Recover 1.17.2 is very old (released Aug. 2015)

Go to
https://github.com/rear/rear/issues
there click the [New issue] button and
follow the instructions that show up then, cf.
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
