### ISSUE TITLE
Use pigz instead of gzip

### ISSUE THREAD

**Issue by mtxd** [rear/rear#1537]
How about using a multithreaded pigz instead of tar --gzip ?

**Comment by jsmeix** [comment]
Do a GitHub pull request so that we can see
how you made it work for you.

**Comment by jsmeix** [comment]
Just do a GitHub pull request so that we can have a look
how you made pigz work for your particular case.

**Comment by mtxd** [comment]
To save us all some time, is there a particular reason why pigz would not work?

**Comment by gdha** [comment]
@mtxd Article https://stackoverflow.com/questions/12313242/utilizing-multi-core-for-targzip-bzip-compression-decompression describes nicely the usage. However, it seems `tar` does not yet fully integrate all functionalities that `pigz` has. You need to combine `tar` and the pipe command combined with `pigz`. However, I prefer the `--use-compress-program=pigz` with `tar`

**Comment by gdha** [comment]
@mtxd However, do not forget to add `pigz` to the binaries to be copied to the rescue image. Feedback is always welcome of course, or even better a pull request.

**Comment by gdha** [comment]
No response after a very long time, therefore, change this to "won't fix" and close it
