### ISSUE TITLE
rear with EMC networker

### ISSUE THREAD

**Issue by thuens** [rear/rear#1546]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / 2017-07-20
* OS version (cat /etc/rear/os.conf or lsb_release -a):OS_VENDOR=RedHatEnterpriseServer 7
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
OUTPUT=ISO
BACKUP=NSR
NSRSERVER=xxxxhpsrm411
NSR_SERVER=xxxxhpsrm411
NSR_DEFAULT_POOL_NAME=DD411-SRVBACK
NSR_RETENTION_TIME="4 week"
</pre>
* Are you using legacy BIOS or UEFI boot?
i think uefi
* Brief description of the issue:
I want to create an rescue-ISO of my backup-server, named xxxxhpsrmn03  and save it on the second Backup-Server named xxxxhpsrm411 to have rescue-system available if xxxxhpsrmn03  crashes. I use EMC Networker 9.1.x. 
xxxxhpsrmn03  is configured as a client on xxxxhpsrm411 and the backup runs without problems.
To configure rear, I created a local.conf with this content:
<pre>
OUTPUT=ISO
BACKUP=NSR
NSR_SERVER=xxxxhpsrm411                                        the destination backup-server
NSR_DEFAULT_POOL_NAME=DD411-SRVBACK      the destination pool on xxxxhpsrm411                                       
NSR_RETENTION_TIME="4 week"
</pre>
“rear dump” looks fine:
<pre>
…
                    local.conf : OK
Backup with NSR
                   NSR_DEFAULT_POOL_NAME = DD411-SRVBACK
                   NSR_RETENTION_TIME = 4 week
                   NSR_ROOT_DIR = /nsr
                   NSR_SERVER = xxxxhpsrm411
                   BACKUP_INTEGRITY_CHECK =
</pre>
The command, that is created at runtime looks like this:
<pre>
root     23291 28340  0 16:06 pts/0    00:00:00 save -s xxxxhpsrmn03 -c xxxxhpsrmn03 -N REAR.20171025 -b DD411-SRVBACK -y 4 week /var/lib/rear/output/rear-xxxxhpsrmn03.iso
</pre>
NSR_SERVER=xxxxhpsrm411 in local.conf is not considered. I also tried NSRSERVER, but that is missing in “rear dump”
Where does rear take the NSRSERVER/NSR_SERVER from if not from local.conf ?
* Work-around, if any:
-

**Comment by gozora** [comment]
I have no experience with NSR but right config variable looks to be [NSRSERVER](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1090)

V.

**Comment by gozora** [comment]
check of [460_save_nsr_server_name.sh](https://github.com/rear/rear/blob/master/usr/share/rear/rescue/NSR/default/460_save_nsr_server_name.sh) might help you to check how NSRSEVER is set in ReaR.

V.

**Comment by thuens** [comment]
Hello Vladimir,
thank you for the hint , where to find the place where NSRSERVER is handled.
I had to dig a little deeper to find the reason for my problem.
I will try to describe it here:
If you start rear for the first time, the script rescue/NSR/default/460_save_nsr_server_name.sh 
finds the NSRSERVER and writes it to /var/lib/rear/recovery/nsr_server. Rear delivers the output as exepected.
If you decide to use another backupserver and you add the line
"NSRSERVER=anotherbackupserver" to the local.conf file, the NSRSERVER-variable is set in the main script. During the workflow, the script layout/save/NSR/default/650_check_iso_recoverable.sh sets NSRSERVER back to the "old" value, stored in /var/lib/rear/recovery/nsr_server.

NSRSERVER=$(cat $VAR_DIR/recovery/nsr_server)
CLIENTNAME=$(hostname)

The script rescue/NSR/default/460_save_nsr_server_name.sh runs after 650... and has nothing to do,
because NSRSERVER is already set, but with the wrong value.
After i removed the line NSRSERVER=... form 650... rear worked as i expected.

Another little point is, that NSRSERVER should be displayed in "rear dump". But 
the variables are only displayed if they have an underscore. For example, NSR_SERVER would be displayed. Please see lib/dump-workflow.

Thank you and best regards
thuens

**Comment by jsmeix** [comment]
Cannot be done until ReaR 2.3 is released
so that I set the milestone to ReaR 2.4.

**Comment by gdha** [comment]
@thuens So, the request is to rename variable `NSRSERVER` into `NSR_SERVER`, right? If we do that we should make sure that if the variable `NSRSERVER` is set (legacy name of the variable) it is copied into the new variable `NSR_SERVER` (during the **prep** phase).
I have no objection against it - will you prepare a pull request?

**Comment by gdha** [comment]
As not response came back - I will close this request until further notice.
