### ISSUE TITLE
EFI Boot Manager restoration issue

### ISSUE THREAD

**Issue by MarcoS80** [rear/rear#1564]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2-git.0.b7927e5.unknown.changed /  2017-10-31
* OS version (cat /etc/rear/os.conf or lsb_release -a): Ubuntu/17.04/i386
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso:///backup
ISO_VOLID="REARISO"
OUTPUT_URL=file:///tmp
MODULES=( 'all_modules' )
</pre>

* Are you using legacy BIOS or UEFI boot? UEFI

* Brief description of the issue:
The EFI Boot Manager cannot be installed when the system has a nvme
ssd, because the device name is resolved in /dev/nvme0n1p rather than
 /dev/nvme0n1.
* Work-around, if any:
In:
/usr/share/rear/finalize/Linux-i386/630_run_efibootmgr.sh
the following if statement:
<pre>
if [[ (! -b $Disk) && ( ${Disk/nvme//} != $Disk  ) && ( ${Disk%p} ) ]] ; then
    Disk=${Disk%p}
fi
</pre>
just after line 11 statement:
<pre>
Disk=$( echo ${Dev%$ParNr} ) # /dev/sda or  /dev/mapper/vol34_part or /dev/mapper/mpath99p
</pre>
can be used to check if a nvme device is in use and resolve the device name correctly

**Comment by gozora** [comment]
@MarcoS80 (again ;-)) could you please open pull request for these changes?

Thanks

V.

**Comment by MarcoS80** [comment]
I'm sorry,
I don't think I can. Not at the moment, at least.
I didn't get the script through git. I installed a .deb package and modified the script on the spot.

**Comment by gozora** [comment]
No rush, take your time. 
If you've found something that can enhance ReaR, it is your right to open PR and become an contributor.
I can try to implement your thoughts into ReaR code, but I can't fully test its functionality as I'm not the proud owner of any nvme device :-(.

V.

**Comment by kladiv** [comment]
+1

As workaround i added the code below in the file `/usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh`, after eMMC trailing 'p' block:
```
# For NVMe devices the trailing 'p' in the Disk value
# (as in /dev/nvme0n1p that is derived from /dev/nvme0n1p1)
# needs to be stripped (to get /dev/nvme0n1), otherwise the
# efibootmgr call fails because of a wrong disk device name.
# See also https://github.com/rear/rear/issues/2103
if [[ $Disk = *'/nvme'+([0-9])n+([0-9])p ]] ; then
    Disk=${Disk%p}
fi
```
I successfully restored EFI bootloader on a Baremetal server + SSD Samsung EVO NVMe disk.

**Comment by jsmeix** [comment]
I did not read about the details here but I just assume that
with https://github.com/rear/rear/pull/2160 merged
this issue is sufficiently fixed so that I close it hereby.
If not it can of course be reopened.
