### ISSUE TITLE
Detect and escalate NFS 'root_squash' (or other permission related problems) to the user

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#158]
When the user has no rights to write to the destination folder (as root), we should detect and report this to the user. Causes could be NFS root_squash, read_only mounts and/or selinux.

If possible, we should analyse the permission problems and provide guidance for each specific case. Or if impossible, at least report the various causes for this issue.

This closes #146.

**Comment by gdha** [comment]
NFSv4 support post-pone  to rear-1.18 release

**Comment by gdha** [comment]
Fully NFSv4 integration into rear is postponed to 1.19. No time left for 1.18 release.

**Comment by gdha** [comment]
We may close this issue as we have a special issue #754 for this topic.
