### ISSUE TITLE
Missing /tmp after recovery (ubuntu with one big /)

### ISSUE THREAD

**Issue by gdha** [rear/rear#1581]
* rear version (/usr/sbin/rear -V): 2.2
* OS version (cat /etc/rear/os.conf or lsb_release -a): ubuntu 16.04
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): BACKUP=BAREOS
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: after recovery mkinitrd failed due to missing /tmp directory
* Work-around, if any:
Edit script `/usr/share/rear/prep/default/400_save_mountpoint_details.sh` and as last line add:
````
echo "tmp 1777 root root" >> "$VAR_DIR/recovery/mountpoint_permissions"
````
See also https://github.com/rear/rear/pull/1527/commits/2ebe65eddcd9ccb8386ce2fc036bd0d3bfad3a14

Perhaps it would be enough to change the default entry in `conf/default.conf` from (for ReaR 2.3):
````
DIRECTORY_ENTRIES_TO_RECOVER=( )
to
DIRECTORY_ENTRIES_TO_RECOVER=( '/tmp 1777 root root' )
````
Thoughts?

**Comment by jsmeix** [comment]
Any missing standard FHS directory is unexpeced because in
prep/default/400_save_directories.sh
I intentionally implemented (at least I tried to)
that all standard FHS directories are always recreated.

@gdha 
could you inpect your "rear mkrescue" and "rear recover" logs
why the standard FHS directory 'tmp' is not automatically
recreated in this case.

**Comment by gdha** [comment]
@jsmeix Fair enough - for ReaR 2.3 it is fixed then (via `prep/default/400_save_directories.sh`), but the script was different in rear-2.2.
But, the work-around I gave is good enough for now. Thanks for the feedback and I will close it again

**Comment by jsmeix** [comment]
@gdha 
if you find the time I would appreciate it
if you could verify that it is rally fixed
with current ReaR master code.
