### ISSUE TITLE
430_prepare_timesync.sh needs to be improved

### ISSUE THREAD

**Issue by gdha** [rear/rear#1598]
* rear version (/usr/sbin/rear -V): 2.2 and higher
* OS version (cat /etc/rear/os.conf or lsb_release -a): n/a
* Brief description of the issue: 
  - script `rescue/default/430_prepare_timesync.sh` needs an update with **ntpd** and `/etc/inittab` - today it should become a systemd script
  - secondly, it might be useful to add **NTPDATE** as a third possibility to set-up time

**Comment by N3WWN** [comment]
Just a quick comment that adding chrony as another option to sync time may be a good idea since RHEL/CentOS 7.x use chrony by default.

I could help with this or take this on within the next few weeks, if you'd like.

**Comment by gdha** [comment]
@N3WWN Hi Richard - indeed chronyd is used by RHEL and ubuntu and for my rear-automated-testing I just added an ansible playbook for this fact (https://github.com/gdha/rear-automated-testing/commit/ccfd1cf1a3a7690292738542d1cad22536c3f8a9)
However, that being said does not mean that our rescue image is chronyd ready, therefore, your help would be very much appreciated.

**Comment by gdha** [comment]
The **NTPDATE** feature should be implemented for rear-2.3 as then my rear automated testing system can compare hours more easily. **Chrony** is for 2.4 or later.
Therefore, I change the milestone to 2.3 for the ntpdate update.

**Comment by N3WWN** [comment]
@gdha I can start work on the ntpdate feature today and get it to you ASAP.   If I can't get it today, would next week be okay?

**Comment by gdha** [comment]
@N3WWN Try to do it today, if not then I will check it tomorrow (only have a few hours before I leave for a trip). We will see - thanks for your kind offer!

**Comment by N3WWN** [comment]
Will do and you're welcome! 😀 

I will be away Thu-Mon which is why I say it may be next week, but will do what I can today.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1608 merged
the NTPDATE feature is implemented for ReaR 2.3
so that I close this issue as "fixed/solved/done".

For the further enhancement with Chrony for 2.4 or later
a separated new issue should be opened.

**Comment by N3WWN** [comment]
Roger that @jsmeix !  I will open a new issue when I get back early next week.
