### ISSUE TITLE
SSHFS ReaR Hangs

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#1600]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

[root@xhcsm5a rear]# rear -V
Relax-and-Recover 2.00 / Git

Red Hat Enterprise Linux Server release 7.3 (Maipo)

#
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=sshfs://root@xxx.xxx.xx.xxx/dbar/
BACKUP_URL=sshfs://root@xxx.xxx.xx.xxx/dbar/
KEEP_OLD_OUTPUT_COPY=1
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/u01' '/var/cache/yum')

using legacy BIOS  boot?

We use ReaR with sshfs option to backup Linux physical/virtual servers.  This works very well but each week we have approximately 30  backups fail because sshfs hangs.

The current work around is to create the ReaR files local on the server then copy them to the backup server.

Here is the ls output from /tmp:

[root@xhcsm5a rear.tdHIIt4LVxXrsKA]# pwd
/tmp/rear.tdHIIt4LVxXrsKA
[root@xhcsm5a rear.tdHIIt4LVxXrsKA]# ls -lhart
ls: cannot access outputfs: Transport endpoint is not connected
total 0
??????????? ? ?    ?     ?            ? outputfs
drwxr-xr-x  2 root root  6 Nov 27 14:16 tmp
drwxr-xr-x  3 root root 16 Nov 27 14:16 rootfs
drwx------  5 root root 44 Nov 27 14:16 .
drwxrwxrwt. 4 root root 50 Nov 27 14:25 ..

In most cases a server reboot will fix the problem but I'm wondering if there was anyway to avoid rebooting the server to clear this issue?

Thanks,
John
[rear-xhcsm5a.log](https://github.com/rear/rear/files/1507370/rear-xhcsm5a.log)

**Comment by gozora** [comment]
Hello @John-Leone,

This don't look like ReaR issue to me. 
You can confirm directly with RedHat, but AFAIK sshfs is not supported on RHEL...

V.

**Comment by John-Leone** [comment]
Hi @gozora 
That's correct sshfs is not supported by RedHat, I opened a case with them and they don't support sshfs.
I'm looking for a workaround other than rebooting the server.

**Comment by gozora** [comment]
Lot of things can be wrong here and I guess RedHat does not support sshfs for a reason ...
I personally did not run into any kind of hang situations with FUSE filesystems, but try just umount stale share:
```
fusermount -u /tmp/rear.tdHIIt4LVxXrsKA/outputfs
```

V.

**Comment by John-Leone** [comment]
sshfs works fine most of the time.
I tried fusermount -u then tried running a new backup with the same result.

**Comment by gozora** [comment]
Most of the time ... :-).
Did you try `rmmod fuse && modprobe fuse` ?

V.

**Comment by John-Leone** [comment]
That's a good idea, but same result.

**Comment by gdha** [comment]
@John-Leone Please add `ServerAliveInterval 15` to your `.ssh/config` file to avoid such issues in the future

**Comment by jsmeix** [comment]
I close it because it is not an issue in ReaR.
