### ISSUE TITLE
Create a bootable ISO for RedHat on PPC

### ISSUE THREAD

**Issue by spacfonseca** [rear/rear#1606]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
cat /etc/rear/os.conf
     OS_VENDOR=RedHatEnterpriseServer
     OS_VERSION=7
uname -a
     Linux ch1lx770.corp.panorg.com 3.10.0-514.26.2.el7.ppc64le #1 SMP Fri Jun 30 01:27:36 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue: Not able to create a valid bootable ISO to boot and rescue server

I need help on how to create a working bootable ISO image for a PPC server. All the ISOs I have created allow boot but hungs

**Comment by jsmeix** [comment]
In general Relax-and-Recover version 1.17.2
is "simply too old" to have proper PPC support.

@schabrolles 
made tons of fixes and enhancements
for POWER architecture in current ReaR.

@spacfonseca 
please try the current ReaR GitHub master code.

To test the current ReaR GitHub master code
basically "git clone" it into a directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# cd rear

# vi etc/rear/local.conf

# usr/sbin/rear -d -D mkbackup
</pre>
(note the relative paths "etc/rear/" and "usr/sbin/").

**Comment by jsmeix** [comment]
@spacfonseca 
because "no news is good news" I assume
it works with current ReaR GitHub master code
so that I can close this issue.

**Comment by spacfonseca** [comment]
Hello!
Thanks for your support.
I did update the rear to version 2.2 but still was not able to perform restore tests. Please close this subject. I will get back to it once I do all testing needed.

Regards
Sérgio

On 1 Dec 2017, 13:31 +0000, Johannes Meixner <notifications@github.com>, wrote:

Closed #1606<https://github.com/rear/rear/issues/1606>.

**Comment by mmeier9** [comment]
Hello,
We encountered the same issue on Power8 ppc64 le RHEL 7.4 and we downloaded the git rear as directed above to get it to "Relax-and-Recover 2.3 / Git".   The backup works fine for both the iso and the tar file.  The restore of the iso, however, boots and runs for a little bit but then stops at "Relax-and-Recover rescue system is ready", followed by "[OK] Found device /dev/hvc0]" and finally followed by "[OK] Started Initialize Rescue System."  where it hangs forever.  Please let us know if there is another fix for this or some other website to download the working release from.  Thank you.

**Comment by jsmeix** [comment]
https://github.com/rear/rear/issues/1606#issuecomment-360499352
was submitted as new issue
https://github.com/rear/rear/issues/1710
