### ISSUE TITLE
Support restoring network configurations on ancient OS releases (e.g. RHEL6)

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1607]
* rear version (/usr/sbin/rear -V): rear-2.2
* OS version (cat /etc/rear/os.conf or lsb_release -a): rhel6
* Brief description of the issue:

On RHEL6 systems, the network configuration of the system cannot be generated properly, typically when bridges are used. This is due to "ip link" not supporting "bridge" type. In such case "brctl" may be used instead.
Also "readlink" only accepts 1 file name on RHEL6, and network devices do not have "lower_*" nodes in /sys/class/net/_<netdev>_/

PR #1605 fixes all this.
Sorry for not having noticed that before.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1605 merged
I consider this issue to be fixed.
