### ISSUE TITLE
Daemons spawned by sysinit.service die upon sysinit.service's end 

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1609]
* rear version (/usr/sbin/rear -V): 2.00
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL7
* Brief description of the issue:

When OS uses systemd, the sysinit.service oneshot service executes /etc/scripts/system-setup which in turns executes /etc/scripts/system-setup.d/* scripts.
Upon these, there is **dhclient** and **netbackup** daemons.
With existing code, these daemons die upon sysinit's end.

**Comment by gdha** [comment]
With PR #1610 merged this issue is probably fixed

**Comment by jsmeix** [comment]
I close it because it is fixed.
