### ISSUE TITLE
Rear can't create image / xfs_info checks FS, not Mountpoint (230_filesystem_layout)

### ISSUE THREAD

**Issue by Kosta-G** [rear/rear#1618]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / Git
[root@acer kosta]# pacman -Q relax-and-recover-git
relax-and-recover-git 2.2.r423.gb9cf52ff-1
* OS version (cat /etc/rear/os.conf or lsb_release -a):
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://qnap/Sams_2TB/backup/rear/backup/"
NETFS_KEEP_OLD_BACKUP_COPY=yes
ISO_DIR="/tmp"
ISO_IMAGES=
ISO_ISOLINUX_BIN="/usr/lib/syslinux/bios/isolinux.bin"
ISO_MKISOFS_BIN="/usr/bin/mkisofs"
ISO_PREFIX=ReaR
ISO_VOLID=RELAXRECOVER
USE_CFG2HTML=y
</pre>
* Are you using legacy BIOS or UEFI boot?
legacyBIOS
* Brief description of the issue:
Trying to create image, rear aborts very early.
Log shows problem showing xfs options...
Rear Scripts tries to execute   xfs_info with  FS name /dev/sda3   instead of  Mountpoint  /
<pre>
230_filesystem_layout.sh:
 (xfs)
                uuid=$(xfs_admin -u $device | cut -d'=' -f 2 | tr -d " ")
                label=$(xfs_admin -l $device | cut -d'"' -f 2)
                echo -n " uuid=$uuid label=$label "
                xfs_info $device > $LAYOUT_XFS_OPT_DIR/$(basename ${device}.xfs)
                StopIfError "Failed to save XFS options of $device"
                ;;
</pre>
xfs_info    Should use $mountpoint and not $device. As its not running (under Arch) with device.

<pre>
> [root@acer kosta]# xfs_info /dev/sda3
> xfs_info: /dev/sda3 ist kein eingehängtes XFS-Dateisystem
> [root@acer kosta]# xfs_info /
> meta-data=/dev/sda3              isize=512    agcount=4, agsize=29456322 blks
>          =                       sectsz=4096  attr=2, projid32bit=1
>          =                       crc=1        finobt=1 spinodes=0 rmapbt=0
>          =                       reflink=0
> data     =                       bsize=4096   blocks=117825286, imaxpct=25
>          =                       sunit=0      swidth=0 blks
> naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
> log      =Intern                 bsize=4096   blocks=57531, version=2
>          =                       sectsz=4096  sunit=1 blks, lazy-count=1
> realtime =keine                  extsz=4096   blocks=0, rtextents=0

> [root@acer kosta]# /usr/sbin/rear mkbackup                                                                                                                        
> ERROR: Failed to save XFS options of /dev/sda3                                                                                                                    
> Aborting due to an error, check /var/log/rear/rear-acer.log for details                                                                                           
> Beendet                                                                                                                                                           
> [root@acer kosta]#                                                                                                                                                
> [root@acer kosta]#                                                                                                                                                
> [root@acer kosta]# cat /var/log/rear/rear-acer.log                                                                                                                
> rear-acer.log               rear-acer.log.lockless      rear-acer.log.lockless.old  rear-acer.log.old                                                             
> [root@acer kosta]# cat /var/log/rear/rear-acer.log                                                                                                                
> 2017-12-02 18:54:13.717101819 Relax-and-Recover 2.2 / Git                                                                                                         
> 2017-12-02 18:54:13.718549812 Command line options: /usr/sbin/rear mkbackup                                                                                       
> 2017-12-02 18:54:13.719878563 Using log file: /var/log/rear/rear-acer.log                                                                                         
> 2017-12-02 18:54:13.736314387 Including conf/Linux-i386.conf                                                                                                      
> 2017-12-02 18:54:13.737755742 Including conf/GNU/Linux.conf                                                                                                       
> 2017-12-02 18:54:13.824013940 Including /etc/rear/local.conf                                                                                                      
> 2017-12-02 18:54:13.825954565 ======================                                                                                                              
> 2017-12-02 18:54:13.827123862 Running 'init' stage                                                                                                                
> 2017-12-02 18:54:13.828306975 ======================                                                                                                              
> 2017-12-02 18:54:13.836402579 Including init/default/010_set_drlm_env.sh                                                                                          
> 2017-12-02 18:54:13.840647414 Including init/default/030_update_recovery_system.sh                                                                                
> 2017-12-02 18:54:13.844863657 Including init/default/050_check_rear_recover_mode.sh                                                                               
> 2017-12-02 18:54:13.846392569 Finished running 'init' stage in 0 seconds                                                                                          
> 2017-12-02 18:54:13.856054579 Using build area '/tmp/rear.qwxeFw8pZRXpub6'                                                                                        
> 2017-12-02 18:54:13.859427480 Running mkbackup workflow                                                                                                           
> 2017-12-02 18:54:13.863359167 ======================                                                                                                              
> 2017-12-02 18:54:13.864633347 Running 'prep' stage                                                                                                                
> 2017-12-02 18:54:13.865940071 ======================                                                                                                              
> 2017-12-02 18:54:13.874920546 Including prep/default/005_remove_workflow_conf.sh                                                                                  
> 2017-12-02 18:54:13.880838861 Including prep/default/020_translate_url.sh                                                                                         
> 2017-12-02 18:54:13.885297762 Including prep/default/030_translate_tape.sh                                                                                        
> 2017-12-02 18:54:13.891882730 Including prep/default/040_check_backup_and_output_scheme.sh                                                                        
> 2017-12-02 18:54:13.901253128 Including prep/NETFS/default/040_inspect_configuration_files.sh                                                                     
> 2017-12-02 18:54:13.905447958 Including prep/NETFS/default/050_check_NETFS_requirements.sh                                                                        
> 2017-12-02 18:54:13.911233489 Skipping 'ping' test for host 'qnap' in BACKUP_URL 'nfs://qnap/Sams_2TB/backup/rear/backup/'                                        
> 2017-12-02 18:54:13.926181227 Including prep/default/050_check_keep_old_output_copy_var.sh                                                                        
> 2017-12-02 18:54:13.931746501 Including prep/NETFS/default/060_mount_NETFS_path.sh                                                                                
> 2017-12-02 18:54:13.941069077 Mounting with 'mount  -t nfs -o rw,noatime qnap:/Sams_2TB/backup/rear/backup/ /tmp/rear.qwxeFw8pZRXpub6/outputfs'                   
> 2017-12-02 18:54:14.078264861 Including prep/NETFS/default/070_set_backup_archive.sh                                                                              
> 2017-12-02 18:54:14.083549216 Using backup archive '/tmp/rear.qwxeFw8pZRXpub6/outputfs/acer/backup.tar.gz'                                                        
> 2017-12-02 18:54:14.089740367 Including prep/NETFS/default/090_check_encrypted_backup.sh                                                                          
> 2017-12-02 18:54:14.095738392 Including prep/NETFS/default/100_check_nfs_version.sh                                                                               
> 2017-12-02 18:54:14.121115953 Including prep/default/100_init_workflow_conf.sh                                                                                    
> 2017-12-02 18:54:14.127114039 Including prep/NETFS/default/150_save_rsync_version.sh                                                                              
> 2017-12-02 18:54:14.133342862 Including prep/GNU/Linux/200_include_getty.sh                                                                                       
> 2017-12-02 18:54:14.155369087 Including prep/GNU/Linux/200_include_serial_console.sh                                                                              
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: getty: not found                                                                                  
> 2017-12-02 18:54:14.167315956 Including prep/NETFS/GNU/Linux/200_selinux_in_use.sh                                                                                
> 2017-12-02 18:54:14.171715345 Including prep/NETFS/GNU/Linux/205_inspect_tar_capabilities.sh                                                                      
> 2017-12-02 18:54:14.186497681 Including prep/GNU/Linux/210_include_dhclient.sh                                                                                    
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: dhclient: not found                                                                               
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: dhcp6c: not found                                                                                 
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: dhclient6: not found                                                                              
> 2017-12-02 18:54:14.205228934 Including prep/GNU/Linux/220_include_lvm_tools.sh                                                                                   
> 2017-12-02 18:54:14.207813741 Device mapper found enabled. Including LVM tools.                                                                                   
> 2017-12-02 18:54:14.215509700 Including prep/GNU/Linux/230_include_md_tools.sh                                                                                    
> 2017-12-02 18:54:14.221280353 Including prep/GNU/Linux/240_include_multipath_tools.sh                                                                             
> 2017-12-02 18:54:14.225794824 Including prep/GNU/Linux/280_include_systemd.sh                                                                                     
> 2017-12-02 18:54:14.240214706 Including systemd (init replacement) tool-set to bootstrap Relax-and-Recover                                                        
> 2017-12-02 18:54:14.244992623 Including prep/GNU/Linux/280_include_virtualbox.sh                                                                                  
> 2017-12-02 18:54:14.254374856 Including prep/GNU/Linux/280_include_vmware_tools.sh                                                                                
> 2017-12-02 18:54:14.263822890 Including prep/GNU/Linux/290_include_drbd.sh                                                                                        
> 2017-12-02 18:54:14.273658861 Including prep/GNU/Linux/300_check_backup_and_output_url.sh                                                                         
> 2017-12-02 18:54:14.288063400 Including prep/ISO/default/300_check_iso_dir.sh                                                                                     
> 2017-12-02 18:54:14.292680063 Including prep/GNU/Linux/300_include_grub_tools.sh                                                                                  
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: grub-probe: not found                                                                             
> /usr/share/rear/lib/_input-output-functions.sh: line 208: type: grub2-probe: not found                                                                            
> 2017-12-02 18:54:14.304345299 Including prep/GNU/Linux/310_include_cap_utils.sh                                                                                   
> 2017-12-02 18:54:14.309137296 Including prep/ISO/default/320_check_cdrom_size.sh                                                                                  
> 2017-12-02 18:54:14.316150177 Including prep/default/320_include_uefi_env.sh                                                                                      
> 2017-12-02 18:54:14.323707729 Including prep/ISO/GNU/Linux/320_verify_mkisofs.sh                                                                                  
> 2017-12-02 18:54:14.325516432 Using '/usr/bin/mkisofs' to create ISO images                                                                                       
> 2017-12-02 18:54:14.330303727 Including prep/ISO/Linux-i386/330_find_isolinux.sh                                                                                  
> 2017-12-02 18:54:14.336700142 Including prep/default/330_include_uefi_tools.sh
> 2017-12-02 18:54:14.341639797 Including prep/ISO/GNU/Linux/340_add_isofs_module.sh
> 2017-12-02 18:54:14.349310009 Including prep/NETFS/default/400_automatic_exclude_recreate.sh
> 2017-12-02 18:54:14.358256226 Including prep/default/400_save_directories.sh
> /boot 755 root root
> /dev 755 root root
> /dev/shm 1777 root root
> /dev/pts 755 root root
> /dev/hugepages 755 root root
> /dev/mqueue 1777 root root
> 2017-12-02 18:54:14.409058309 FHS directory /etc/opt does not exist
> 2017-12-02 18:54:14.413027737 FHS directory /etc/sgml does not exist
> 2017-12-02 18:54:14.433426027 FHS directory /media does not exist
> /proc 555 root root
> /run 755 root root
> /run/user/1000 700 kosta users
> /sys 555 root root
> /tmp 1777 root root
> 2017-12-02 18:54:14.490563614 FHS directory /usr/X11R6 does not exist
> 2017-12-02 18:54:14.529061881 Including prep/default/950_check_missing_programs.sh
> 2017-12-02 18:54:14.537056435 Including prep/NETFS/default/980_umount_NETFS_dir.sh
> 2017-12-02 18:54:14.541419254 Unmounting '/tmp/rear.qwxeFw8pZRXpub6/outputfs'
> 2017-12-02 18:54:14.657291289 Finished running 'prep' stage in 1 seconds
> 2017-12-02 18:54:14.658697830 ======================
> 2017-12-02 18:54:14.659945417 Running 'layout/save' stage
> 2017-12-02 18:54:14.661175759 ======================
> 2017-12-02 18:54:14.670599111 Including layout/save/GNU/Linux/100_create_layout_file.sh
> 2017-12-02 18:54:14.672204698 Creating disk layout
> 2017-12-02 18:54:14.674125611 Preparing layout directory.
> 2017-12-02 18:54:14.682794388 Removing old layout file.
> 2017-12-02 18:54:14.687842274 Including layout/save/GNU/Linux/150_save_diskbyid_mappings.sh
> 2017-12-02 18:54:14.756762493 Saved diskbyid_mappings
> 2017-12-02 18:54:14.761778396 Including layout/save/GNU/Linux/200_partition_layout.sh
> 2017-12-02 18:54:14.773386876 Saving disk partitions.
> 2017-12-02 18:54:15.222789484 Including layout/save/GNU/Linux/210_raid_layout.sh
> 2017-12-02 18:54:15.228864654 Including layout/save/GNU/Linux/220_lvm_layout.sh
> 2017-12-02 18:54:15.231179821 Saving LVM layout.
> 2017-12-02 18:54:15.284114617 Including layout/save/GNU/Linux/230_filesystem_layout.sh
> 2017-12-02 18:54:15.286089216 Begin saving filesystem layout
> 2017-12-02 18:54:15.290198259 Saving filesystem layout (using the findmnt command).
> xfs_info: /dev/sda3 is not a mounted XFS filesystem
> 2017-12-02 18:54:16.036079701 ERROR: Failed to save XFS options of /dev/sda3
> ==== Stack trace ====
> Trace 0: /usr/sbin/rear:543 main
> Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:11 WORKFLOW_mkbackup
> Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
> Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
> Trace 4: /usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh:150 source
> Trace 5: /usr/share/rear/lib/_input-output-functions.sh:251 StopIfError
> Message: Failed to save XFS options of /dev/sda3
> == End stack trace ==
> 2017-12-02 18:54:16.048595158 Running exit tasks.
> 2017-12-02 18:54:16.053254172 Finished in 3 seconds
> 2017-12-02 18:54:16.056412829 Removing build area /tmp/rear.qwxeFw8pZRXpub6
> 2017-12-02 18:54:16.070405704 End of program reached
</pre>

* Work-around, if any:

**Comment by gozora** [comment]
> Rear Scripts tries to execute xfs_info with FS name /dev/sda3 instead of Mountpoint /

Executing `xfs_info` on device is perfectly fine.

This is much rather to be a problem:
```
xfs_info: /dev/sda3 is not a mounted XFS filesystem
```

Can you post your _/proc/mounts_ here + attach log file from  `rear -d -D mkrescue` ?

V.

**Comment by Kosta-G** [comment]
xfs_info   /dev/sda3     gives this error output... "is not a mounted XFS filesystem"
executing with  xfs_info /   works.


[root@acer kosta]# cat /proc/mounts
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=4021744k,nr_inodes=1005436,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
/dev/sda3 / xfs rw,relatime,attr2,inode64,noquota 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
/dev/sda1 /boot ext3 rw,relatime,commit=600,stripe=4,data=ordered 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
/etc/autofs/auto.misc /misc autofs rw,relatime,fd=6,pgrp=12276,timeout=300,minproto=5,maxproto=5,indirect 0 0
-hosts /net autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,indirect 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=805836k,mode=700,uid=1000,gid=100 0 0
-hosts /net/qnap/4TB autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Bay3_2TB autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Download autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Julia_Doc autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Multimedia autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Music autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Public autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Recordings autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Sams_2TB autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Web autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
-hosts /net/qnap/Zeitschriften autofs rw,relatime,fd=12,pgrp=12276,timeout=120,minproto=5,maxproto=5,offset 0 0
qnap:/Bay3_2TB /net/qnap/Bay3_2TB nfs rw,nosuid,nodev,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.10,mountvers=3,mountport=30000,mountproto=udp,local_lock=none,addr=192.168.1.10 0 0

rear -d -D mkrescue aborts with same issue...

[root@acer kosta]# rear -d -D mkrescue
Relax-and-Recover 2.2 / Git
Using log file: /var/log/rear/rear-acer.log
Using backup archive '/tmp/rear.csigjpxz8MO0OID/outputfs/acer/backup.tar.gz'
Creating disk layout
ERROR: Failed to save XFS options of /dev/sda3
Aborting due to an error, check /var/log/rear/rear-acer.log for details
You should also rm -Rf /tmp/rear.csigjpxz8MO0OID
Beendet

**Comment by Kosta-G** [comment]
[rear-acer.log](https://github.com/rear/rear/files/1524042/rear-acer.log)

**Comment by gozora** [comment]
strange, maybe some Arch specialty ...
I'm going to check that.

V.

**Comment by gozora** [comment]
Can you try to update your _/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh_ as follows, and rerun `rear mkbackup` ?

```
diff --git a/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh b/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
index 915d64d4..4544d785 100644
--- a/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
+++ b/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
@@ -146,7 +146,7 @@ read_filesystems_command="$read_filesystems_command | sort -t ' ' -k 1,1 -u"
                 uuid=$(xfs_admin -u $device | cut -d'=' -f 2 | tr -d " ")
                 label=$(xfs_admin -l $device | cut -d'"' -f 2)
                 echo -n " uuid=$uuid label=$label "
-                xfs_info $device > $LAYOUT_XFS_OPT_DIR/$(basename ${device}.xfs)
+                xfs_info $mountpoint > $LAYOUT_XFS_OPT_DIR/$(basename ${device}.xfs)
                 StopIfError "Failed to save XFS options of $device"
                 ;;
```

Can you tell me what version of _xfsprogs_ are you using (`xfs_info -V`) ?

V.

**Comment by Kosta-G** [comment]
[kosta@acer ~]$ xfs_info -V
xfs_info Version 4.14.0

**Comment by Kosta-G** [comment]
changed  above file,

now skipping that issue, aborting with other error... (not an xfs issue)...

[root@acer kosta]# /usr/sbin/rear mkbackup
ERROR: Cannot autodetect what is used as bootloader, see default.conf about 'BOOTLOADER'
Aborting due to an error, check /var/log/rear/rear-acer.log for details
Beendet

2017-12-02 19:47:25.365525130 Including layout/save/default/445_guess_bootloader.sh
4+0 records in
4+0 records out
2048 bytes (2.0 kB, 2.0 KiB) copied, 5.4239e-05 s, 37.8 MB/s
2017-12-02 19:47:25.630106004 No known bootloader matches the first bytes on /dev/sda
2017-12-02 19:47:25.631943253 Begin of strings in the first bytes on /dev/sda
RPf1
Missing operating system.
f`f1
|fRfP
Ht[y9Y[
Multiple active partitions.
|XFSBu  f
Operating system load error.
/`8:
2017-12-02 19:47:25.634634597 End of strings in the first bytes on /dev/sda
2017-12-02 19:47:25.636755477 ERROR: Cannot autodetect what is used as bootloader, see default.conf about 'BOOTLOADER'
==== Stack trace ====
Trace 0: /usr/sbin/rear:543 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:11 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 4: /usr/share/rear/layout/save/default/445_guess_bootloader.sh:62 source
Message: Cannot autodetect what is used as bootloader, see default.conf about 'BOOTLOADER'
== End stack trace ==

**Comment by gozora** [comment]
My comment in https://github.com/rear/rear/issues/1618#issuecomment-348709609
> Executing xfs_info on device is perfectly fine.

Don't need to be necessary a truth.
excerpt from `man xfs_info`
```
xfs_info [ -t mtab ] mount-point
```

Looks like XFS (again) changes some defaults. This one particular seems to be related to XFS-v4.12.0
where:
excerpt:
```
xfs_growfs: ensure target path is an active xfs mountpoint
    
    xfs_growfs manpage clearly states that the target path must be
    an active xfs mountpoint.
    
    Current behavior allows xfs_growfs to proceed if the target path
    resides anywhere on a mounted xfs filesystem. This could lead to
    unexpected results. Unless the target path is an active xfs
    mountpoint, reject it. Create a new fs table lookup function which
    matches only active xfs mount points, not any file residing within
    those mountpoints.
```

@Kosta-G we need to keep separate issues separated, so open new issue for you new problem please.

I'm preparing new PR for this actual problem.

V.

**Comment by jsmeix** [comment]
@Kosta-G 
regarding your second issue in your
https://github.com/rear/rear/issues/1618#issuecomment-348711866
<pre>
ERROR: Cannot autodetect what is used as bootloader,
see default.conf about 'BOOTLOADER'
</pre>

I assume you did read default.conf about 'BOOTLOADER'
and setting BOOTLOADER as you need it helped.

**Comment by gozora** [comment]
With https://github.com/rear/rear/pull/1619 merged this issue is fixed.

@Kosta-G, thanks for reporting this bug!
If you still experience trouble with boot loader please open separate issue for that.

V.
