### ISSUE TITLE
430_prepare_timesync.sh:  systemd-based systems should not update /etc/inittab

### ISSUE THREAD

**Issue by N3WWN** [rear/rear#1622]
* rear version (/usr/sbin/rear -V): 2.3 and higher
* OS version (cat /etc/rear/os.conf or lsb_release -a): n/a
* Brief description of the issue:
  * Remove manipulations of `/etc/inittab` for systemd-based systems

This is a carry-over of additional work from https://github.com/rear/rear/issues/1598 and https://github.com/rear/rear/pull/1608

**Comment by jsmeix** [comment]
@N3WWN 
removing all manipulations of /etc/inittab for systemd-based systems
would cause regressions in particular for sshd, see
https://github.com/rear/rear/pull/1612
therein in particular
https://github.com/rear/rear/pull/1612#discussion_r154109785

**Comment by N3WWN** [comment]
@jsmeix 
Thanks for pointing that out!  

For now, I'm going to rename the issue to reflect that this was intended for the time sync portion of the code so that the regression problems do not crop up.

**Comment by gdha** [comment]
@N3WWN any chance to get this further?

**Comment by N3WWN** [comment]
Yes, this is also being tested as part of the changes to 430_prepare_timesync.sh that will include chronyd support.  Hopefully submitting the PR early next week.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1739 merged,
this issue should be fixed.
