### ISSUE TITLE
Add chrony support to 430_prepare_timesync.sh

### ISSUE THREAD

**Issue by N3WWN** [rear/rear#1623]
* rear version (/usr/sbin/rear -V): 2.3 and higher
* OS version (cat /etc/rear/os.conf or lsb_release -a): n/a
* Brief description of the issue:
  * script `rescue/default/430_prepare_timesync.sh` needs an update for **chronyd**

This is a carry-over of additional work from https://github.com/rear/rear/issues/1598

**Comment by gdha** [comment]
@N3WWN Are you still working on this?

**Comment by N3WWN** [comment]
Yes, I'm finishing it up and am hoping to get a PR submitted for this early next week.  

I just got time to revisit it about a week ago and, as of right now, a colleague is testing it for me.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1739 merged,
this issue should be fixed.
