### ISSUE TITLE
remove os.conf creation on rear.spec file

### ISSUE THREAD

**Issue by gdha** [rear/rear#1639]
* rear version (/usr/sbin/rear -V): 2.3+
* OS version (cat /etc/rear/os.conf or lsb_release -a): rhel and sles arch
* Brief description of the issue: clean up the `rear.spec` file around the creation of `os.conf` file
This is a continuation of issue #731

**Comment by jsmeix** [comment]
Via https://github.com/rear/rear/pull/1713
/etc/rear/os.conf gets autocreated in the original sytem (if not already exists).

I wonder why /etc/rear/os.conf is autocreated in the original sytem?

Why not only autocreate a $ROOTFS_DIR/etc/rear/os.conf in the recovery system
e.g. in the same way as $ROOTFS_DIR/etc/rear-release gets autocreated by
build/default/970_add_rear_release.sh ?

In general I do not like it when any "rear WORKFOLW" automatically
changes the original system without an explicit user request.
I think in general the original system should be sacrosanct - except there is
really a very good reason to automatically change the original system.

**Comment by gdha** [comment]
@jsmeix Cannot follow your reasoning here - it was like this for a decade. From my point of view this issue may be closed. If you want to change the behaviour then please create a new separate issue.

**Comment by jsmeix** [comment]
O.k. for me.
