### ISSUE TITLE
SLES11SP4 Btrfs OS Recover Fail

### ISSUE THREAD

**Issue by kodiss** [rear/rear#1654]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-recover 2.2 / 2017-07-20
* OS version (cat /etc/rear/os.conf or lsb_release -a): SLES11 SP4  (3.0.101-77)
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.34.41.94/osbackup
BACKUP_PROG_ARCHIVE="osbackup_$(hostname)"
NETFS_KEEP_OLD_BACKUP_COPY=yes
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
EXCLUDE_VG=( vgHANA )
BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" '/hana/*' '/hanabackup/*' )
BACKUP_PROG_INCLUDE=( '/var/tmp/*' '/srv/*' '/var/lib/pgsql/*' '/var/spool/*' '/var/run/*' '/var/lib/libvirt/images/*' '/var/opt/*' '/tmp/*' '/var/lib/named/*' '/var/log/*' '/var/lib/mariadb/*' '/home/*' '/var/lib/mailman/*' '/opt/*' '/usr/local/*' '/boot/grub/*' )

* Are you using legacy BIOS or UEFI boot? legacy Bios
* Brief description of the issue: 
   After recover OS, The OS isn't normal.
   when we use the command "rpm -qa | wc -l | , The result is '0'
  I attach the recover log file.
[recover.zip](https://github.com/rear/rear/files/1577976/recover.zip)

* Work-around, if any:

**Comment by jsmeix** [comment]
@kodiss 
where did you run the "rpm -qa" command?
In the recreated system i.e. after 'rear recover' finished
and after you rebooted or after 'rear recover' finished but
before the reboot i.e. still in the ReaR recovery system?

**Comment by kodiss** [comment]
@jsmeix 
Oh, Sorry. Our system's root fs is btrfs. And it have subvolume.
I  omit the var in BACKUP_PROG_INCLUDE.
After add it, I success to recover.

Thank you and sorry.

**Comment by jsmeix** [comment]
@kodiss 
many thanks for your feedback what the actual
reason was on your particular system and
for your confirmation that ReaR per se works.
It helps (at least me) a lot to have an explicit feedback
when there is no (possibly obscure) issue in ReaR.
