### ISSUE TITLE
CentOS 6 Build ReaR 2.3 Dissapeared

### ISSUE THREAD

**Issue by dcz01** [rear/rear#1655]
#### CentOS 6 Build ReaR 2.3 Dissapeared

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): ReaR 2.3
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL6/CentOS 6
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: ReaR 2.3 Build for CentOS 6 is not available.
* Work-around, if any: None

http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/CentOS_CentOS-6/x86_64/
Build for ReaR 2.3 not there.

**Comment by gdha** [comment]
Are you sure? I can see it at http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/CentOS_CentOS-6/x86_64/rear-2.3-1.el6.x86_64.rpm.mirrorlist

**Comment by dcz01** [comment]
@gdha Sorry it was an proxy caching problem. Now it is visable.

**Comment by jsmeix** [comment]
@dcz01 only FYI
why I added the lables "external tool" and "not ReaR":
Issues with the openSUSE build service (OBS)
are not issues "inside ReaR" => "not ReaR"
and OBS is an "external tool" (for ReaR).
