### ISSUE TITLE
sourceforge tarball much bigger than OBS tarball (4M versus 500K)

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1656]
Our source tarball rear-2.3.tar.gz at sourceforge
https://sourceforge.net/projects/rear/files/rear/
is about 4.8 MB.

In contrast our source tarball rear-2.3.tar.gz in OBS
https://build.opensuse.org/package/show/Archiving:Backup:Rear/rear-2.3
is about 500 KB.

Unpacking both and comparing them with 'diff -r' shows:
<pre>
#  diff -r -U0 rear-2.3.sourceforge rear-2.3.OBS

Only in rear-2.3.sourceforge/doc: Makefile.changelog
Only in rear-2.3.sourceforge: rear-1.17.2-1.fc23.x86_64.rpm
Only in rear-2.3.sourceforge: rear-1.17.2.tar.gz
Only in rear-2.3.sourceforge: rear-1.18-1.fc23.x86_64.rpm
Only in rear-2.3.sourceforge: rear-1.18.tar.gz
Only in rear-2.3.sourceforge: rear-1.19-1.fc23.x86_64.rpm
Only in rear-2.3.sourceforge: rear-1.19-1.git201610111647.fc23.x86_64.rpm
Only in rear-2.3.sourceforge: rear-1.19-1.git201611300645.fc25.x86_64.rpm
Only in rear-2.3.sourceforge: rear-1.19-git201610111647.tar.gz
Only in rear-2.3.sourceforge: rear-1.19-git201611300645.tar.gz
Only in rear-2.3.sourceforge: rear-1.19.tar.gz
Only in rear-2.3.sourceforge: rear-2.00-1.fc25.x86_64.rpm
Only in rear-2.3.sourceforge: rear-2.00.tar.gz
Only in rear-2.3.sourceforge: rear.cron
Only in rear-2.3.sourceforge/usr/share/rear/skel/default: lib
Only in rear-2.3.sourceforge: var
</pre>

Somehow additional RPMs and tarballs are in
our rear-2.3.tar.gz at sourceforge.

Ideally our source tarballs should be exactly the same
at sourceforge and in OBS.

**Comment by gdha** [comment]
Indeed strange - `make dist OFFICIAL=1` works better. Uploaded a new tar-ball

**Comment by jsmeix** [comment]
Now
https://sourceforge.net/projects/rear/files/rear/
shows
<pre>
Looking for the latest version?
Download rear-release-notes.txt (49.0 kB) 
</pre>
where "Download rear-release-notes.txt (49.0 kB)" is a link to
https://sourceforge.net/projects/rear/files/latest/download?source=files
and after clicking on "Download rear-release-notes.txt (49.0 kB)"
one really gets only the rear-release-notes.txt file.

**Comment by gdha** [comment]
That is now fixed as well - thanks for pointing this out - it was automatically selected when I deleted the bad tar-ball.

**Comment by jsmeix** [comment]
I can confirm it is o.k. now.

FYI:
The tarballs at sourceforge and in OBS are not exactly the same
but when unpacking them there are no differences.
Something makes the two tarballs still somehow different.
Ideally all our tarballs at any place are exactly the same.
