### ISSUE TITLE
how to avoid Relax-and-Recover created the rescue  ISO file automatically 

### ISSUE THREAD

**Issue by binyaoo** [rear/rear#1660]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / 2017-07-20
* OS version (cat /etc/rear/os.conf or lsb_release -a):OS_VENDOR=SUSE_LINUX  OS_VERSION=11
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
BACKUP=NETFS
BACKUP_PROG_EXCLUDE=( '/tmp/*'  '/dev/shm/*' "$VAR_DIR/output/*" )
BACKUP_URL=file:///oracle/
* Are you using legacy BIOS or UEFI boot?    vmware virtual machine
* Brief description of the issue:      
Relax-and-Recover had created a ISO file and other file automatically in my backup directory at 01:30 everyday
* Work-around, if any:

dear all,
I installed "rear-2.2-5.x86_64.rpm" on suse 11 sp4,and I just want to use "rear mkbackuponly" command to backup system files.
But I found that Relax-and-Recover had created a ISO file and other file automatically in my backup directory at 01:30 everyday ,just like this:

suse159:/oracle/suse159 # ll
total 1245364
-rw------- 1 root root        202 Dec 21 01:30 README
-rw------- 1 root root        271 Dec 21 01:30 VERSION
-rw-r--r-- 1 root root   12654812 Dec 21 16:34 backup.log
-rw-r--r-- 1 root root 1186067109 Dec 21 16:34 backup.tar.gz
-rw------- 1 root root   75190272 Dec 21 01:30 rear-suse159.iso
-rw------- 1 root root      60578 Dec 21 01:30 rear-suse159.log

And my local.conf file like this:
BACKUP=NETFS
BACKUP_PROG_EXCLUDE=( '/tmp/*'  '/dev/shm/*' "$VAR_DIR/output/*" )
BACKUP_URL=file:///oracle/

So how can I avoid it to create rescue CD file automatically ?

thank you.!

**Comment by jsmeix** [comment]
See
https://github.com/rear/rear/issues/1658#issuecomment-353362511
