### ISSUE TITLE
FYI: smenu - a shell GUI selection tool

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1661]
Right now I was informed about
https://github.com/p-gen/smenu
<pre>
This simple tool reads words from the standard input,
presents them in a cool interactive window
after the current line on the terminal
and writes the selected word, if any,
on the standard output.
</pre>
and
http://www.linux-magazine.com/Online/Features/smenu/%28offset%29/0

Probably not directly usable for ReaR right now
(unless smenu became usually installed on Linux systems)
but in general it looks interesting so that I like
to have you informend hereby.

**Comment by gdha** [comment]
@jsmeix looks to be a cool tool, but I not really usable within ReaR as not (yet) part of the core OS repositories
