### ISSUE TITLE
'cd somedir' without returning back in BORG/default/400_restore_backup.sh

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1678]
Current restore/BORG/default/400_restore_backup.sh does
<pre>
cd $TARGET_FS_ROOT
</pre>
but never returns from there to the usual working directory
where "rear recover" runs in.
Even if that somehow works it looks dangerous when
all subsequent scripts run with $TARGET_FS_ROOT
as the current working directory.
I suggest to use
<pre>
pushd $TARGET_FS_ROOT
...
popd
</pre>
cf. usr/share/rear/build/default/501_check_ssh_keys.sh
and usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

**Comment by gozora** [comment]
@jsmeix thanks for pointing this out!
This could introduce some nasty surprises in the future indeed!
I'll correct it in upcoming days.

V.

**Comment by gozora** [comment]
With https://github.com/rear/rear/pull/1698 merged, this issue can be closed!
