### ISSUE TITLE
initramfs creation failed

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#1684]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

Relax-and-Recover 2.00 / Git

Red Hat Enterprise Linux Server release 7.4 (Maipo)
```
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
#
# Linux - ReaR  - Location = mid
#
# xrearm1p.aetna.com = 
# xrearw1p.aetna.com = 
#
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=sshfs://root@xxx.xxx.xxx.xxx/dbar/
BACKUP_URL=sshfs://root@xxx.xxx.xxx.xxx/dbar/
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/var/cache/yum' 'websoft' 'sklm' '/aetnasmcca/sklmqbackup' '/media' '/var/tmp' '/var/crash')
KEEP_OLD_OUTPUT_COPY=1
```
BIOS

During a V2P migration we see this message below.
[rear-xsklmm1q-new.log](https://github.com/rear/rear/files/1611430/rear-xsklmm1q-new.log)

Running mkinitrd...
WARNING !!!
initramfs creation for Kernel version '3.10.0-327.el7.x86_64' failed,
please check '/var/log/rear/rear-xsklmm1q-new.log' to see the error messages in detail
and decide yourself, whether the system will boot or not.

**Comment by gozora** [comment]
@John-Leone https://github.com/rear/rear/issues/1455 maybe ?

V.

**Comment by John-Leone** [comment]
Thank you.
I will change local.conf and try again then let you know.

**Comment by gozora** [comment]
@John-Leone 

You need to upgrade to **ReaR 2.3**, that is first version where _DIRECTORY_ENTRIES_TO_RECOVER_ was implemented.

V.

**Comment by John-Leone** [comment]
@gozora 
After doing some testing it seems like i encountered a similar problem below.   
https://access.redhat.com/solutions/2359851
I'm going to open a case with RH and let you know how it goes

**Comment by John-Leone** [comment]
@gozora 
This problem only happens during a virtual to physical server migrations for RHEL 7 servers.
Our workaround is to select the rescue shell and rebuild the initial ramdisk for the impacted kernel.
Please close this case.
Thanks,
John
