### ISSUE TITLE
Cannot restore backup when BACKUP_INTEGRITY_CHECK=1

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1685]
* rear version (/usr/sbin/rear -V):

```
Relax-and-Recover 2.00 / Git
```
but also
```
Relax-and-Recover 2.3 / Git
```

* OS version (cat /etc/rear/os.conf or lsb_release -a):

```
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7
```

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

```
BACKUP_INTEGRITY_CHECK=1
```

* Brief description of the issue:

When using BACKUP_INTEGRITY_CHECK=1, recovery fails with the following error, trying to compute the md5sum of the backup:

```
Checking integrity of backup.tar.gz
backup.tar.gz: FAILED open or read
ERROR: Integrity check failed. Restore aborted because BACKUP_INTEGRITY_CHECK is enabled.
Aborting due to an error, check /var/log/rear/rear-vm-rear74.log for details
Terminated
```

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1686 merged
this issue is fixed.
