### ISSUE TITLE
centos 7 under onapp kvm: rescue hangs on unpaking initramfs

### ISSUE THREAD

**Issue by maximvolgin** [rear/rear#1691]
Hello,

Faced strange problem under centos 7 vm on cloud based on onapp kvm. It just hangs after boot:

![rescue_hangs](https://user-images.githubusercontent.com/25030663/34825988-7990dcf6-f6dd-11e7-9ccc-e569d1d2eed9.png)

No any problems on same environment with centos 6 and the same image booting no problems under VirtualBox.

May it be lack of RAM? Is there any way to debug it? 

Any help appreciated.
Max

**Comment by maximvolgin** [comment]
I've figured it's lack of RAM. Just added RAM  and it finally boots well :)

**Comment by jsmeix** [comment]
@maximvolgin 
thanks for the fast feedback what the actual reason was.
