### ISSUE TITLE
Rear with Borg - no umask variable.

### ISSUE THREAD

**Issue by pavl00** [rear/rear#1699]
Relax-and-Recover 2.3 / 2017-12-20
borg 1.1.4

When using Borg there is no option to set umask variable. 
Default it is 077, so there is a problem when few users try use one borg repository.

To resolve this issue:
add new variable: BORGBACKUP_UMASK
and set it correctly in borg_set_vars function.

**Comment by gozora** [comment]
Just a guess, but did you try to set _umask_ in your local.conf ?

V.

**Comment by pavl00** [comment]
Yes. I tried to set BORGBACKUP_UMASK="0007" and a few more combinations (including system environment variables) but I see that rear uses only a few BORGBACKUP_XXX variables to compose borg  command line options.
When borg is run without --umask option it uses default 077 and moreover it is passing it to borge serve (if run through ssh). And it doesn't matter if borg backup repository was created with different umask

**Comment by gozora** [comment]
OK, I see your point now.
I'll write a patch for this.

V.

**Comment by pavl00** [comment]
Yes it works with borg create.
But as I can see now  --umask must be used in all repo related borg commands, here in rear: create,prune, init(probably).

**Comment by gozora** [comment]
Hmm, I've forgotten about `borg prune ...`, thanks for reminding me!
I'll add it later today.

V.

**Comment by gozora** [comment]
@pavl00 I've added _BORGBACKUP_UMASK_ for `borg prune ...`.

I'll wait ~24 hours and do the merge, if no other issues arise.

V.

**Comment by pavl00** [comment]
ok, it works properly now. Thanks!

**Comment by gozora** [comment]
With #1700 merged, this issue can be closed.
