### ISSUE TITLE
Bug in file : /usr/share/rear/output/default/10_mount_output_path.sh

### ISSUE THREAD

**Issue by torig** [rear/rear#170]
Rear version 1.14

At line 8 missing $ before variable name OUTPUT_MOUNTCMD : 

OUTPUT_URL="var://OUTPUT_MOUNTCMD"

**Comment by pcahyna** [comment]
Why is that a bug? The variable reference gets expanded indirectly using`${!var}`.

**Comment by jsmeix** [comment]
See also
https://github.com/rear/rear/commit/20359a987662cc0c3fcfa52d62d1feac7cd55850#commitcomment-51375233
