### ISSUE TITLE
Replace 'read -t $WAIT_SECS' with UserInput function calls

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1705]
Current (ReaR 2.3) code contains several
<pre>
read -t $WAIT_SECS ...
</pre>
calls that should be replaced with UserInput function calls.

**Comment by gdha** [comment]
this can wait - pushing to 2.5 release

**Comment by jsmeix** [comment]
This issue can wait => postponing to "ReaR v2.6" milestone.
