### ISSUE TITLE
BinCopyTo: command not found

### ISSUE THREAD

**Issue by shellster** [rear/rear#1723]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): `Relax-and-Recover 2.2-git.2688.3ad23a02.master.changed / 2017-12-19`

* OS version (cat /etc/rear/os.conf or lsb_release -a): `Debian GNU/Linux 9.3 (stretch)`

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=cifs://<redacted ip>/<redacted folder>
BACKUP_OPTIONS="cred=/etc/rear/.cifs"
```

* Are you using legacy BIOS or UEFI boot? `Legacy`

* Brief description of the issue:
`Every time I run "rear mkbackup" it fails.  When I look at the log this is the error:`

```
/usr/share/rear/build/GNU/Linux/39_copy_binaries_libraries.sh: line 35: BinCopyTo: command not found
2018-02-01 13:31:53.595901730 ERROR: Could not copy binaries
==== Stack trace ====
Trace 0: /usr/sbin/rear:543 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:15 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 4: /usr/share/rear/build/GNU/Linux/39_copy_binaries_libraries.sh:36 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:251 StopIfError
Message: Could not copy binaries
== End stack trace ==
2018-02-01 13:31:53.620024402 Running exit tasks.
2018-02-01 13:31:53.628693199 Finished in 38 seconds
2018-02-01 13:31:53.634492385 Removing build area /tmp/rear.bYjK4ddPCxlVb9R
2018-02-01 13:31:54.013124197 End of program reached
```

* Work-around, if any:
`I searched for "BinCopyTo" but I can't find any reference to it anywhere except in the file mentioned in the error message.  I've pulled the latest version of rear from  the Debian repo.  I'm fairly linux savvy, so I'm happy to provide additional info or try things, if helpful.`

**Comment by gozora** [comment]
Can you run `rear -d -D mkbackup` and attach here your log file from /var/log/rear/ directory?

V.

**Comment by shellster** [comment]
I've attached the log, as requested.  I've redacted the machine name and various IP addresses, but it is otherwise the complete log.

Thanks for responding.

[rear-redacted.log](https://github.com/rear/rear/files/1691207/rear-redacted.log)

**Comment by gozora** [comment]
Hi @shellster,
There is something wrong with your installation of ReaR.
In the attached log it reads `Relax-and-Recover 2.2-git.2688.3ad23a02.master.changed` which is OK.
What is wrong however, are script prefix numbers which change in ReaR >= 2.0 from 2 to 3 digits.
E.g.
You have currently two versions of _*copy_binaries_libraries.sh_:
```
39_copy_binaries_libraries.sh
and
390_copy_binaries_libraries.sh
```
Looks like you've just extracted tar ball with ReaR 2.2 over ReaR < 2.0.
To fix this you should completely remove directory _/usr/share/rear_ directory and extract tar ball (with ReaR 2.2) again.
After this, your strange error should disappear.

V.

**Comment by jsmeix** [comment]
FWIW:
The special BinCopyTo() function in the global lib/linux-functions.sh was replaced
by the specific copy_binaries() in build/GNU/Linux/390_copy_binaries_libraries.sh via
https://github.com/rear/rear/commit/54f2c451acee47fbefb9a3ac87222866562dc7fc

Of course a mix-up of old and new ReaR scripts fails in arbitrary ways.

@gozora 
many thanks for the analysis what the root cause of this issue is.

**Comment by jsmeix** [comment]
@shellster 

FYI:

How you could test the current ReaR GitHub master code
without get things messed up with an already installed ReaR
(e.g. as software package from a Linux distribution):

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

In general regarding getting ReaR software packages see
http://relax-and-recover.org/download/

In general regarding ReaR version upgrades see the section
"Version upgrades with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

In general regarding debugging issues in ReaR see the section
"Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by shellster** [comment]
Thank you guys for your help.  Deleting all the copies and checking out the latest github version fixed that error.  It's still failing on a completely new error, but at least it closes this issue.
