### ISSUE TITLE
UUID <UUID> already in use on “/dev/<devicename>”

### ISSUE THREAD

**Issue by procurve86** [rear/rear#1735]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
Relax-and-Recover 2.2 / 2017-07-20

* OS version (cat /etc/rear/os.conf or lsb_release -a):
OS_VENDOR=RedHatEnterpriseServer OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
<pre>
# Create Relax-and-Recover rescue media as ISO image
OUTPUT=ISO
BACKUP=NETFS
NETFS_KEEP_OLD_BACKUP_COPY=no
NETFS_URL=nfs://10.1.30.20/u02/rear_backups
</pre>

* Are you using legacy BIOS or UEFI boot? 
UEFI

* Brief description of the issue:
When trying to rear recover on same machine with pv intact I got the following error for every disk device:
<pre>
UUID "UUID" already in use on “/dev/sda”
</pre>

* Work-around, if any:
<pre>
dd if=/dev/zero of=/dev/sda bs=409600 count=300
</pre>
then restart recovery

Is this the expected behavior?
Is there a way to force pv recreation?
Would it be possible to add kind of a force switch to rear recover or a dialog?

Thanks and best regards
Daniel

**Comment by jsmeix** [comment]
I assume "rear recover on same machine" means
that you run "rear recover" with an already used disk
in this case even with the exact same disk of your original system.

In general when you run "rear recover" with an already used disk
various weird issues can appear depending on what (remaining)
data there is on the already used disk.

For details and some examples see the issue
`Add an early "cleanupdisk" script`
https://github.com/rear/rear/issues/799
and follow the links therein.

Currently there is no such "cleanupdisk" script in ReaR.
In general it is therefore recommended to run "rear recover"
with a disk that was already fully cleaned up in advance
to avoid such issues.

**Comment by jsmeix** [comment]
@procurve86 
I think you can automate your workaround
<pre>
dd if=/dev/zero of=/dev/sda bs=409600 count=300
</pre>
via a PRE_RECOVERY_SCRIPT
see usr/share/rear/conf/default.conf

**Comment by procurve86** [comment]
Hi jsmeix

Thank you for your support! 
I'll do it with proposal "PRE_RECOVERY_SCRIPT"

Have a nice weekend.

Best regards
Daniel
