### ISSUE TITLE
pstree command not found

### ISSUE THREAD

**Issue by gdha** [rear/rear#1755]
* rear version (/usr/sbin/rear -V): rear-2.3 >
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL 7.4
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): n/a
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: `pstree` command not found
````
grep "command not found" var/log/rear/rear-awsablirl1016.log
./usr/share/rear/lib/_input-output-functions.sh: line 109: pstree: command not found
````
which is called from `function DoExitTasks`:
````
Log "$( pstree -Aplau $MASTER_PID )"
````
-> not that critical in this case. `pstree` is part of package **psmisc**, but it would be overkill to add this to the required packages IMHO.

* Work-around, if any: n/a

**Comment by jsmeix** [comment]
Argh!
I would have sworn I had checked that but in reality I could not have checked it
because also in my ReaR recovery system there is no "pstree"
(I only have "pstree" in my normal original SLES system)
so that this code cannot work during "rear recover".

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1756 merged this issue is fixed.
