### ISSUE TITLE
IBM power8  hmc console disconnects at root prompt for rear rescue

### ISSUE THREAD

**Issue by pspatola101** [rear/rear#1764]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
rear -V
Relax-and-Recover 2.3 / 2017-12-20
* OS version (cat /etc/rear/os.conf or lsb_release -a):
 cat /etc/rear/os.conf
cat: /etc/rear/os.conf: No such file or directory
 lsb_release -i -s
-bash: lsb_release: command not found

[root@sssxfs03 rear]# uname -a
Linux sssxfs03 3.10.0-514.21.1.el7.ppc64le #1 SMP Sat Apr 22 02:38:06 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://172.19.5.99/stuff/unix/iowa"
SSH_ROOT_PASSWORD="reardemo"
BOOT_FROM_SAN=y
AUTOEXCLUDE_MULTIPATH=n
REAR_INITRD_COMPRESSION=lzma
ONLY_INCLUDE_VG=( rhel_sssxfs03 )
BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" '/usr/lpp/mmfs/4.2.3.1' '/usr/lpp/mmfs/4.2.3.2' )

* Are you using legacy BIOS or UEFI boot?BIOS
* Brief description of the issue: The hmc console vterm disconnects when I get to the root prompt for recovery.
sssxfs03 login: root
**-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell**

At this point I cant type anything in. I tried setting the TERM but that didnt work. I did notice during the recovery the message.
[    0.000103] console [hvc0] enabled, bootconsole disabled
[    0.000103] console [hvc0] enabled, bootconsole disabled
The hvc is for a XEN and not for IBM Power. Is there a way to change this?
This is the full recovery:
OF stdout device is: /vdevice/vty@30000000
Preparing to boot Linux version 3.10.0-514.21.1.el7.ppc64le (mockbuild@ppc-047.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Sat Apr 22 02:38:06 EDT 2017
Detected machine type: 0000000000000101
Max number of cores passed to firmware: 256 (NR_CPUS = 2048)
Calling ibm,client-architecture-support... done
command line: BOOT_IMAGE=/kernel root=/dev/ram0 ip=10.97.31.245::10.97.28.1:255.255.252.0:sssxfs04:eth0:none
memory layout at init:
  memory_limit : 0000000000000000 (16 MB aligned)
  alloc_bottom : 000000000e4b0000
  alloc_top    : 0000000010000000
  alloc_top_hi : 0000000010000000
  rmo_top      : 0000000010000000
  ram_top      : 0000000010000000
instantiating rtas at 0x000000000eca0000... done
prom_hold_cpus: skipped
copying OF device tree...
Building dt strings...
Building dt structure...
Device tree strings 0x000000000e4c0000 -> 0x000000000e4c170c
Device tree struct  0x000000000e4d0000 -> 0x000000000e500000
Calling quiesce...
returning from prom_init
[    0.000000] Using pSeries machine description
[    0.000000] Page sizes from device-tree:
[    0.000000] base_shift=12: shift=12, sllp=0x0000, avpnm=0x00000000, tlbiel=1, penc=0
[    0.000000] base_shift=12: shift=16, sllp=0x0000, avpnm=0x00000000, tlbiel=1, penc=7
[    0.000000] base_shift=12: shift=24, sllp=0x0000, avpnm=0x00000000, tlbiel=1, penc=56
[    0.000000] base_shift=16: shift=16, sllp=0x0110, avpnm=0x00000000, tlbiel=1, penc=1
[    0.000000] base_shift=16: shift=24, sllp=0x0110, avpnm=0x00000000, tlbiel=1, penc=8
[    0.000000] base_shift=24: shift=24, sllp=0x0100, avpnm=0x00000001, tlbiel=0, penc=0
[    0.000000] base_shift=34: shift=34, sllp=0x0120, avpnm=0x000007ff, tlbiel=0, penc=3
[    0.000000] Using 1TB segments
[    0.000000] Found initrd at 0xc00000000be00000:0xc00000000e4ac692
[    0.000000] bootconsole [udbg0] enabled
[    0.000000] Partition configured for 64 cpus.
[    0.000000] CPU maps initialized for 8 threads per core
[    0.000000] Starting Linux PPC64 #1 SMP Sat Apr 22 02:38:06 EDT 2017
[    0.000000] -----------------------------------------------------
[    0.000000] ppc64_pft_size                = 0x1b
[    0.000000] physicalMemorySize            = 0x100000000
[    0.000000] htab_hash_mask                = 0xfffff
[    0.000000] -----------------------------------------------------
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.0-514.21.1.el7.ppc64le (mockbuild@ppc-047.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Sat Apr 22 02:38:06 EDT 2017
[    0.000000] [boot]0012 Setup Arch
[    0.000000] PPC64 nvram contains 15360 bytes
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x00000000-0xffffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   2: [mem 0x00000000-0xffffffff]
[    0.000000] Could not find start_pfn for node 0
[    0.000000] [boot]0015 Setup Done
[    0.000000] PERCPU: Embedded 3 pages/cpu @c000000001600000 s124952 r0 d71656 u262144
[    0.000000] Built 2 zonelists in Node order, mobility grouping on.  Total pages: 65480
[    0.000000] Policy zone: DMA
[    0.000000] Kernel command line: BOOT_IMAGE=/kernel root=/dev/ram0 ip=10.97.31.245::10.97.28.1:255.255.252.0:sssxfs04:eth0:none
[    0.000000] PID hash table entries: 4096 (order: -1, 32768 bytes)
[    0.000000] Sorting __ex_table...
[    0.000000] freeing bootmem node 2
[    0.000000] Memory: 4011904k/4194304k available (17152k kernel code, 0k reserved, 1344k data, 3657k bss, 4288k init)
[    0.000000] SLUB: HWalign=128, Order=0-3, MinObjects=0, CPUs=64, Nodes=256
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  RCU restricting CPUs from NR_CPUS=2048 to nr_cpu_ids=64.
[    0.000000] NR_IRQS:512 nr_irqs:512 16
[    0.000001] clocksource: timebase mult[1f40000] shift[24] registered
[    0.000090] Console: colour dummy device 80x25
[    0.000103] console [hvc0] enabled, bootconsole disabled
[    0.000103] console [hvc0] enabled, bootconsole disabled
[    0.000825] allocated 1048576 bytes of page_cgroup
[    0.000831] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000868] Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
[    0.000874] pid_max: default: 65536 minimum: 512
[    0.000921] Security Framework initialized
[    0.000933] SELinux:  Initializing.
[    0.001014] Dentry cache hash table entries: 524288 (order: 6, 4194304 bytes)
[    0.001668] Inode-cache hash table entries: 262144 (order: 5, 2097152 bytes)
[    0.001984] Mount-cache hash table entries: 4096
[    0.002719] Initializing cgroup subsys memory
[    0.002770] Initializing cgroup subsys devices
[    0.002772] Initializing cgroup subsys freezer
[    0.002775] Initializing cgroup subsys net_cls
[    0.002777] Initializing cgroup subsys blkio
[    0.002779] Initializing cgroup subsys perf_event
[    0.002782] Initializing cgroup subsys hugetlb
[    0.002784] Initializing cgroup subsys pids
[    0.002786] Initializing cgroup subsys net_prio
[    0.002909] EEH: pSeries platform initialized
[    0.002920] POWER8 performance monitor hardware support registered
[    0.010572] Brought up 32 CPUs
[    0.013752] devtmpfs: initialized
[    0.020921] EEH: devices created
[    0.021688] atomic64 test passed
[    0.022147] NET: Registered protocol family 16
[    0.022222] EEH: No capable adapters found
[    0.022238] IBM eBus Device Driver
[    0.022405] pstore: Registered nvram as persistent store backend
[    0.024301] PCI: Probing PCI hardware
[    0.024394] pseries-rng: Registering arch random hook.
[    0.050898] vgaarb: loaded
[    0.050946] SCSI subsystem initialized
[    0.050973] usbcore: registered new interface driver usbfs
[    0.050981] usbcore: registered new interface driver hub
[    0.051076] usbcore: registered new device driver usb
[    0.051353] NetLabel: Initializing
[    0.051356] NetLabel:  domain hash size = 128
[    0.051358] NetLabel:  protocols = UNLABELED CIPSOv4
[    0.051369] NetLabel:  unlabeled traffic allowed by default
[    0.051478] Switched to clocksource timebase
[    0.056564] NET: Registered protocol family 2
[    0.056780] TCP established hash table entries: 32768 (order: 2, 262144 bytes)
[    0.056851] TCP bind hash table entries: 32768 (order: 3, 524288 bytes)
[    0.056904] TCP: Hash tables configured (established 32768 bind 32768)
[    0.056913] TCP: reno registered
[    0.056923] UDP hash table entries: 2048 (order: 0, 65536 bytes)
[    0.056934] UDP-Lite hash table entries: 2048 (order: 0, 65536 bytes)
[    0.057047] NET: Registered protocol family 1
[    0.057082] Unpacking initramfs...
[    8.382331] Freeing initrd memory: 39552K (c00000000be00000 - c00000000e4a0000)
[    8.382995] IOMMU table initialized, virtual merging enabled
[    8.431976] hv-24x7: read 1330 catalog entries, created 337 event attrs (0 failures), 169 descs
[    8.432507] futex hash table entries: 16384 (order: 5, 2097152 bytes)
[    8.432665] Initialise system trusted keyring
[    8.432685] audit: initializing netlink socket (disabled)
[    8.432701] type=2000 audit(1522423719.430:1): initialized
[    8.454278] HugeTLB registered 16 MB page size, pre-allocated 0 pages
[    8.454284] HugeTLB registered 16 GB page size, pre-allocated 0 pages
[    8.455236] zpool: loaded
[    8.455239] zbud: loaded
[    8.455465] VFS: Disk quotas dquot_6.5.2
[    8.455513] Dquot-cache hash table entries: 8192 (order 0, 65536 bytes)
[    8.455683] msgmni has been set to 8040
[    8.455734] Key type big_key registered
[    8.456427] NET: Registered protocol family 38
[    8.456434] Key type asymmetric registered
[    8.456437] Asymmetric key parser 'x509' registered
[    8.456460] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    8.456588] io scheduler noop registered
[    8.456593] io scheduler deadline registered (default)
[    8.456619] io scheduler cfq registered
[    8.456668] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    8.456916] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    8.457171] Linux agpgart interface v0.103
[    8.457189] crash memory driver: version 1.1
[    8.457289] rdac: device handler registered
[    8.457351] hp_sw: device handler registered
[    8.457356] emc: device handler registered
[    8.457358] alua: device handler registered
[    8.457382] libphy: Fixed MDIO Bus: probed
[    8.457409] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    8.457417] ehci-pci: EHCI PCI platform driver
[    8.457424] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    8.457431] ohci-pci: OHCI PCI platform driver
[    8.457438] uhci_hcd: USB Universal Host Controller Interface driver
[    8.457465] usbcore: registered new interface driver usbserial
[    8.457470] usbcore: registered new interface driver usbserial_generic
[    8.457476] usbserial: USB Serial support registered for generic
[    8.457513] mousedev: PS/2 mouse device common for all mice
[    8.457657] rtc-generic rtc-generic: rtc core: registered rtc-generic as rtc0
[    8.457672] cpuidle: using governor menu
[    8.481483] nx_compress_pseries ibm,compression-v1: nx842_OF_upd: device disabled
[    8.521507] hidraw: raw HID events driver (C) Jiri Kosina
[    8.521575] usbcore: registered new interface driver usbhid
[    8.521577] usbhid: USB HID core driver
[    8.521589] drop_monitor: Initializing network drop monitor service
[    8.521648] TCP: cubic registered
[    8.521652] Initializing XFRM netlink socket
[    8.521736] NET: Registered protocol family 10
[    8.522004] NET: Registered protocol family 17
[    8.522123] Loading compiled-in X.509 certificates
[    8.522496] Loaded X.509 cert 'Red Hat Enterprise Linux Driver Update Program (key 3): bf57f3e87362bc7229d9f465321773dfd1f77a80'
[    8.522858] Loaded X.509 cert 'Red Hat Enterprise Linux kpatch signing key: 4d38fd864ebe18c5f0b72e3852e2014c3a676fc8'
[    8.523225] Loaded X.509 cert 'Red Hat Enterprise Linux kernel signing key: abee87f9ae3c21f216ca2d00b836473ad6a052a0'
[    8.523236] registered taskstats version 1
[    8.523735] rtc-generic rtc-generic: setting system clock to 2018-03-30 15:28:39 UTC (1522423719)
[    8.524043] Freeing unused kernel memory: 4288K (c000000000c90000 - c0000000010c0000)
[    8.527056] ip_tables: (C) 2000-2006 Netfilter Core Team
[    8.527069] systemd[1]: Inserted module 'ip_tables'
[    8.531260] systemd[1]: systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    8.531357] systemd[1]: Detected architecture ppc64-le.
[    8.531362] systemd[1]: Running with unpopulated /etc.

Welcome to Red Hat Enterprise Linux!

[    8.531520] systemd[1]: Set hostname to <sssxfs03>.
[    8.531544] systemd[1]: Initializing machine ID from random generator.
[    8.532084] systemd[1]: Failed to populate /etc with preset unit settings, ignoring: Invalid argument
[  OK  ] Reached target System Initialization.
[    8.536588] systemd[1]: Reached target System Initialization.
[    8.536596] systemd[1]: Starting System Initialization.
[  OK  ] Created slice -.slice.
[    8.536814] systemd[1]: Created slice -.slice.
[    8.536822] systemd[1]: Starting -.slice.
[  OK  ] Listening on udev Control Socket.
[    8.536991] systemd[1]: Listening on udev Control Socket.
[    8.536998] systemd[1]: Starting udev Control Socket.
[  OK  ] Listening on Journal Socket.
[    8.537135] systemd[1]: Listening on Journal Socket.
[    8.537142] systemd[1]: Starting Journal Socket.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[    8.537268] systemd[1]: Listening on D-Bus System Message Bus Socket.
[    8.537276] systemd[1]: Starting D-Bus System Message Bus Socket.
[  OK  ] Listening on udev Kernel Socket.
[    8.537430] systemd[1]: Listening on udev Kernel Socket.
[    8.537437] systemd[1]: Starting udev Kernel Socket.
[  OK  ] Listening on Delayed Shutdown Socket.
[    8.537554] systemd[1]: Listening on Delayed Shutdown Socket.
[    8.537561] systemd[1]: Starting Delayed Shutdown Socket.
[  OK  ] Listening on Syslog Socket.
[    8.537681] systemd[1]: Listening on Syslog Socket.
[    8.537689] systemd[1]: Starting Syslog Socket.
[  OK  ] Created slice system.slice.
[    8.537849] systemd[1]: Created slice system.slice.
[    8.537856] systemd[1]: Starting system.slice.
[  OK  ] Created slice system-serial\x2dgetty.slice.
[    8.538026] systemd[1]: Created slice system-serial\x2dgetty.slice.
[    8.538033] systemd[1]: Starting system-serial\x2dgetty.slice.
[    8.538459] systemd[1]: Starting udev Kernel Device Manager...
         Starting udev Kernel Device Manager...
[    8.538869] systemd[1]: Starting Relax-and-Recover boot script...
         Starting Relax-and-Recover boot script...
[  OK  ] Started Relax-and-Recover sshd service.
[    8.539447] systemd[1]: Started Relax-and-Recover sshd service.
[    8.539574] systemd[1]: Starting Relax-and-Recover sshd service...
         Starting Relax-and-Recover sshd service...
[    8.540056] systemd[1]: Starting udev Coldplug all Devices...
         Starting udev Coldplug all Devices...
[  OK  ] Created slice system-getty.slice.
[    8.540452] systemd[1]: Created slice system-getty.slice.
[    8.540464] systemd[1]: Starting system-getty.slice.
[  OK  ] Listening on Logging Socket.
[    8.540604] systemd[1]: Listening on Logging Socket.
[    8.540611] systemd[1]: Starting Logging Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Started Journal Service.
         Starting Journal Service...
[  OK  ] Started udev Kernel Device Manager.
[  OK  ] Reached target Basic System.
         Starting Initialize Rescue System...
[  OK  ] Started Relax-and-Recover boot script.
[  OK  ] Found device /dev/ttyS0.
[  OK  ] Started udev Coldplug all Devices.
[  OK  ] Found device /dev/hvc0.
[  OK  ] Started Relax-and-Recover run-syslog script.
         Starting Relax-and-Recover run-syslog script...

Configuring Relax-and-Recover rescue system

Running 00-functions.sh...
Running 01-run-ldconfig.sh...
Running 10-console-setup.sh...
Loading /etc/dumpkeys.out
Running 20-check-boot-options.sh...
IP address will be overruled by kernel option ip=10.97.31.245::10.97.28.1:255.255.252.0:sssxfs04:eth0:none
Running 40-start-udev-or-load-modules.sh...
/etc/scripts/system-setup.d/00-functions.sh: line 16: udevsettle: command not found
Waiting for udev ... /etc/scripts/system-setup.d/00-functions.sh: line 16: udevsettle: command not found
done.
Running 41-load-special-modules.sh...
Running 42-engage-scsi.sh...
Running 45-serial-console.sh...
Running 55-migrate-network-devices.sh...
No network interface mapping is specified in /etc/rear/mappings/mac
The original network interface eth0 d2:d5:09:ee:88:02 is not available
1) eth0 26:2f:0a:88:f2:02 ibmveth
2) Skip replacing eth0 d2:d5:09:ee:88:02
Choose replacement for eth0 d2:d5:09:ee:88:02 2
Skipping eth0 d2:d5:09:ee:88:02 (you may have to manually fix your network setup)
The original network interface eth1 d2:d5:09:ee:88:03 is not available
1) eth0 26:2f:0a:88:f2:02 ibmveth
2) Skip replacing eth1 d2:d5:09:ee:88:03
Choose replacement for eth1 d2:d5:09:ee:88:03 2
Skipping eth1 d2:d5:09:ee:88:03 (you may have to manually fix your network setup)
Running 58-start-dhclient.sh...
Running 60-network-devices.sh...
Cannot find device "eth1"
Cannot find device "eth1"
Cannot find device "eth1"
Cannot find device "eth1"
Running 62-routing.sh...
Running 63-teaming.sh...
Running 65-sysctl.sh...
Running 67-check-by-label-cdrom.sh...
Did not find a cdrom device. Recover might fail.
Running 99-makedev.sh...

Relax-and-Recover rescue system is ready

[  OK  ] Started Initialize Rescue System.
[  OK  ] Started Getty on tty3.
         Starting Getty on tty3...
[  OK  ] Started Getty on tty2.
         Starting Getty on tty2...
[  OK  ] Started Getty on hvc0.
         Starting Getty on hvc0...
[  OK  ] Started Getty on tty0.
         Starting Getty on tty0...
[  OK  ] Started Getty on tty1.
         Starting Getty on tty1...
[  OK  ] Started Getty on tty4.
         Starting Getty on tty4...
[  OK  ] Reached target Login Prompts.
[  OK  ] Reached target Multi-User.
[  OK  ] Started Serial Getty on ttyS0.
         Starting Serial Getty on ttyS0...
[  OK  ] Started Serial Getty on hvc0.

Relax-and-Recover 2.3 / 2017-12-20

Relax-and-Recover comes with ABSOLUTELY NO WARRANTY; for details see
the GNU General Public License at: http://www.gnu.org/licenses/gpl.html

Host sssxfs03 using Backup NETFS and Output ISO
Build date: Thu, 29 Mar 2018 14:41:57 -0400

Red Hat Enterprise Linux
Kernel 3.10.0-514.21.1.el7.ppc64le on an ppc64le

SSH fingerprint: 2048 65:1e:5b:a5:c7:8b:3a:29:e0:5c:87:9f:3b:7d:45:fc  root@sssxfs03 (RSA)

sssxfs03 login:

Relax-and-Recover 2.3 / 2017-12-20

Relax-and-Recover comes with ABSOLUTELY NO WARRANTY; for details see
the GNU General Public License at: http://www.gnu.org/licenses/gpl.html

Host sssxfs03 using Backup NETFS and Output ISO
Build date: Thu, 29 Mar 2018 14:41:57 -0400

Red Hat Enterprise Linux
Kernel 3.10.0-514.21.1.el7.ppc64le on an ppc64le

SSH fingerprint: 2048 65:1e:5b:a5:c7:8b:3a:29:e0:5c:87:9f:3b:7d:45:fc  root@sssxfs03 (RSA)

sssxfs03 login: root
-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell

Welcome to Relax-and-Recover. Run "rear recover" to restore your system !

* Work-around, if any:

**Comment by schabrolles** [comment]
Hi @pspatola101,

/dev/hvc0 is not only used by XEN. It is also the default console for POWER when using HMC virtual console (in PowerVM).

How do you use your system:
 - PowerNV (BareMetal, no virtualization, with VGA console or IPMI console)
 - PowerVM (Native Power Firmware Virtualisation, with HMC virtual console)
 - KVM on Power (KVM virtualization, virsh console, VNC console)
 - RHV/oVIrt (KVM, virtual console via VNC / Web interface)
 - Nutanix (Hyperconverged based on KVM, virtual console via Prism web interface)

**Comment by pspatola101** [comment]
I'm using the PowerVM.

**Comment by pspatola101** [comment]
Somewhere I read that I need the mingetty package on the linux lpar for the restore to work properly?

**Comment by schabrolles** [comment]
@pspatola101, If you are on PowerVM, then you should stay with `hvc0` as default console.

Is you still have errors with your console, you should also give a try to the current master branch (some patches regarding dbus could help to detect the console during boot on rescue media https://github.com/rear/rear/pull/1743)
```
git clone http://github.com/rear/rear
cd rear
make install
```

@jsmeix , What do you think about the following message:

```
cat /etc/rear/os.conf
cat: /etc/rear/os.conf: No such file or directory
lsb_release -i -s
-bash: lsb_release: command not found
```

**Comment by pspatola101** [comment]
I downloaded the latest rear and created an rpm package with it:
[root@sssxfs03 rear]# rear -V
Relax-and-Recover 2.3-git.2932.d6865ed.master.changed / 2018-03-23
I also installed the lsb components:
[root@sssxfs03 rear]# rpm -qa |grep lsb-core
redhat-lsb-core-4.1-27.el7.ppc64le

I ran the rear rescue again and recovered the system on another lpar and it worked! Many thanks!

**Comment by jsmeix** [comment]
@schabrolles 
many thanks for your help with this POWER related issue!

Regarding os.conf see https://github.com/rear/rear/issues/1639

Regarding "lsb_release: command not found":
As far as I know `lsb_release` is only required by RPM packaging.
This means when one installs the ReaR files not as RPM packages
one can have the ReaR files without `lsb_release`.
But I think then the SetOSVendorAndVersion() function in
usr/share/rear/lib/config-functions.sh
may error out depending on whether or not 
OS_VENDOR and OS_VERSION are already specified
and depending on whether or not the SetOSVendorAndVersion() function 
can determine OS_VENDOR and OS_VERSION also without `lsb_release`.
