### ISSUE TITLE
Recovering big endien

### ISSUE THREAD

**Issue by spacf** [rear/rear#1768]
Hello!
I am trying to create a working iso bootable that allow me to perform a complete system recover without any issues. Currently I am not able to do it.
My lpar is using a SAN lun to boot. After I run 'rear mkbackup' I do a 'dd' of the iso created by rear to the LUN. After I select it to boot from inside SMS menu. 
note.: I am using LVM.
[rear-restore.txt](https://github.com/rear/rear/files/1875019/rear-restore.txt)

Attached is the output of my config and also the steps and messages during boot process.

Can someone give me some hints on what to change/include to allow to make rear recover to avoid the error ...:
2018-04-04 10:38:58 ERROR: Backup archive '/rearbackup/ch13x777/backup.tar.gz' not found !

**Comment by spacf** [comment]
note .: /rearbackup is mounted on a lv created on a different LUN from boot LUN. 
[root@ch13x777 ~]# pvs
  /var/run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  PV                   VG          Fmt  Attr PSize   PFree
  /dev/mapper/mpathap3 vg_ch13x777 lvm2 a--u  49.50g      0
  /dev/mapper/mpathc   datavg      lvm2 a--u 400.00g 390.00g

**Comment by jsmeix** [comment]
See
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by gozora** [comment]
You are doing backup to local directory (`BACKUP_URL="file:///rearbackup"`).
In order to restore from such configuration, you need to have your backup archive (_backup.tar.gz_) available in `/rearbackup/ch13x777` directory prior running `rear recover`.

V.

**Comment by jsmeix** [comment]
Very informative!

@gozora 
many thanks for your time that you digged into that issue!
