### ISSUE TITLE
Restore fails due to invalid parted mkpart command

### ISSUE THREAD

**Issue by ritzmann** [rear/rear#1770]
* ReaR version ("/usr/sbin/rear -V"):
  Relax-and-Recover 2.3 / 2017-12-20

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
  Debian GNU/Linux 8.10 (jessie)

* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):
  OUTPUT=USB
  USB_DEVICE=/dev/disk/by-label/REAR-000
  USB_DEVICE_FILESYSTEM=ext4
  BACKUP=REQUESTRESTORE
  TIMESYNC=NTP
  CLONE_ALL_USERS_GROUPS="yes"

* System architecture (x86 compatible or POWER and/or what kind of virtual machine):
  amd64 (backup)
  amd64 (restore vbox 4.3.36)

* Are you using BIOS or UEFI or another way to boot?
  vbox BIOS

* Brief description of the issue:
I am testing restoration and created a simple VirtualBox machine with one hard drive (the backed up machine has multiple hard drives with various LVM volumes and partitions). The restore fails with a parted mkpart command that is called with the wrong parameter ('BIOS boot partition' instead of a valid partition type).

Here is a screenshot from the VM with the end of the rear.log:
![parted](https://user-images.githubusercontent.com/379272/38459007-0b637ea0-3aad-11e8-8705-df3f302129bb.png)

Steps to reproduce:
1. Create USB rescue image with rear mkrescue.
2. Create VirtualBox machine with hard disk and second disk that maps to USB stick.
3. Boot VBox image with USB stick and select rescue image in Grub menu.
4. Confirm a few questions to map partition layout to single disk.
5. From command line, invoke rear restore.

**Comment by ritzmann** [comment]
Renamed to disklayout.txt so that I could attach it instead of pasting.
[disklayout.txt](https://github.com/rear/rear/files/1886757/disklayout.txt)

**Comment by gozora** [comment]
You've been hit by https://github.com/rear/rear/issues/1563.
The problem of yours is fixed by 491548aef86340c50bc8e83441ab34a6658e29b4, which is unfortunately not included in ReaR 2.3.
In general downloading latest ReaR upstream code will fix your problem.

V.
