### ISSUE TITLE
Exclude subset of multipath disks

### ISSUE THREAD

**Issue by pspatola101** [rear/rear#1777]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.3-git.2932.d6865ed.master.changed / 2018-03-23
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
LSB Version:    :core-4.1-noarch:core-4.1-ppc64le
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo
* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):
[root@ssstfs03 rear]# vi local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://172.19.5.99/stuff/unix/iowa"
SSH_ROOT_PASSWORD="reardemo"
BOOT_FROM_SAN=y
AUTOEXCLUDE_MULTIPATH=n
REAR_INITRD_COMPRESSION=lzma
USE_STATIC_NETWORKING=y
ONLY_INCLUDE_VG=( "${ONLY_INCLUDE_VG[@]}" "rhel_ssstfs03" )
**EXCLUDE_COMPONENTS=( "${EXCLUDE_COMPONENTS[@]}" "multipath:/dev/mapper/mpathar" "multipath:/dev/mapper/mpathas" "multipath:/dev/mapper/mpathat")
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "multipath:/dev/mapper/mpathar" "multipath:/dev/mapper/mpathas" "multipath:/dev/mapper/mpathat")**
AUTOEXCLUDE_DISKS=y
#MIGRATION_MODE='true'
* System architecture (x86 compatible or POWER and/or what kind of virtual machine):
IBM Power 
* Are you using BIOS or UEFI or another way to boot?PPC64
* Brief description of the issue:
Trying to exclude certian multipath disks. I setuop the local.conf but those disks are not being excluded in the disklayout.conf
* Work-around, if any:

**Comment by jsmeix** [comment]
IBM Power architecture plus multipath means
it is best when @schabrolles has a look...

**Comment by schabrolles** [comment]
@pspatola101 

could you try without `multipath:` :  
```
EXCLUDE_COMPONENTS=( "${EXCLUDE_COMPONENTS[@]}" "/dev/mapper/mpathar" "/dev/mapper/mpathas" "/dev/mapper/mpathat")
```

**Comment by schabrolles** [comment]
@pspatola101,

Any news from your side? Did you find the time to test without `multipath:`

**Comment by pspatola101** [comment]
I apologize for the long delay. I had a family health emergency that required me to take time off from work.
I made the update to the local.conf as you suggested and it worked. I checked the disktodo.conf file and they are marked as done.
[root@ssstfs03 layout]# cat disktodo.conf |grep mpathar
done /dev/mapper/mpathar multipath
done /dev/mapper/mpathar1 part

I checked the disklayout.conf file and they are commented out.
[root@ssstfs03 layout]# cat disklayout.conf |grep mpathar
#multipath /dev/mapper/mpathar 10737418240 /dev/sdba,/dev/sddx
#part /dev/mapper/mpathar 10737369088 24576 GPFS none /dev/mapper/mpathar1

I really appreciate the help with this. I was hoping for an easier solution as I could have numerous gpfs disks on here and more would be added.

**Comment by pspatola101** [comment]
I tried one more thing. I saw someone had written a bash script to do the exclusion. I edited the file like so.
EXCLUDE_COMPONENTS=("${EXCLUDE_COMPONENTS[@]}" "$(/usr/lpp/mmfs/bin/mmlsnsd -m |grep mapper |awk '{print $3}' |sort -u)")

When I run the mkrescue -v it looks as if it will work...
[root@ssstfs03 rear]# rear -v mkrescue
Relax-and-Recover 2.3-git.2932.d6865ed.master.changed / 2018-03-23
Using log file: /var/log/rear/rear-ssstfs03.log
Using backup archive '/tmp/rear.xHcfc6vx9PVw8Ky/outputfs/ssstfs03/backup.tar.gz'
Creating disk layout
Excluding Volume Group datavg
Excluding Volume Group vgswap
Excluding component /dev/mapper/mpathaa
/dev/mapper/mpathab
/dev/mapper/mpathag
/dev/mapper/mpathai
/dev/mapper/mpathaj
/dev/mapper/mpathal
/dev/mapper/mpatham
/dev/mapper/mpathan
/dev/mapper/mpathao
/dev/mapper/mpathap
/dev/mapper/mpathaq
/dev/mapper/mpathar
/dev/mapper/mpathas
/dev/mapper/mpathat
/dev/mapper/mpathau
/dev/mapper/mpathav
/dev/mapper/mpathaw
/dev/mapper/mpathax
/dev/mapper/mpathay
/dev/mapper/mpathaz
/dev/mapper/mpathb
/dev/mapper/mpathba
/dev/mapper/mpathbb
/dev/mapper/mpathbc
/dev/mapper/mpathbf
/dev/mapper/mpathbg
/dev/mapper/mpathbh
/dev/mapper/mpathbi
/dev/mapper/mpathbj
/dev/mapper/mpathbk
/dev/mapper/mpathbl
/dev/mapper/mpathbm
/dev/mapper/mpathbn
/dev/mapper/mpathbo
/dev/mapper/mpathbp
/dev/mapper/mpathbq
/dev/mapper/mpathbr
/dev/mapper/mpathbs
/dev/mapper/mpathbt
/dev/mapper/mpathbu
/dev/mapper/mpathbv
/dev/mapper/mpathbw
/dev/mapper/mpathc
/dev/mapper/mpathd
/dev/mapper/mpathe
/dev/mapper/mpathf
/dev/mapper/mpathg
/dev/mapper/mpathh
/dev/mapper/mpathi
/dev/mapper/mpathj
/dev/mapper/mpathk
/dev/mapper/mpathl
/dev/mapper/mpathm
/dev/mapper/mpathn
/dev/mapper/mpatho
/dev/mapper/mpathp
/dev/mapper/mpathq
/dev/mapper/mpathr
/dev/mapper/mpaths
/dev/mapper/mpatht
/dev/mapper/mpathu
/dev/mapper/mpathv
/dev/mapper/mpathw
/dev/mapper/mpathx
/dev/mapper/mpathy
/dev/mapper/mpathz.

Unfortunately none of them are marked done in the disktodo.conf or commented out in the disklayout.conf
todo /dev/mapper/mpathbp multipath
todo /dev/mapper/mpathbp1 part
todo /dev/mapper/mpathak multipath
todo /dev/mapper/mpathr multipath
todo /dev/mapper/mpathr1 part
todo /dev/mapper/mpathbc multipath
todo /dev/mapper/mpathbc1 part
todo /dev/mapper/mpathe multipath
todo /dev/mapper/mpathe1 part
todo /dev/mapper/mpathaw multipath
todo /dev/mapper/mpathaw1 part
todo /dev/mapper/mpathbo multipath
todo /dev/mapper/mpathbo1 part
todo /dev/mapper/mpathaj multipath
todo /dev/mapper/mpathaj1 part
todo /dev/mapper/mpathq multipath
todo /dev/mapper/mpathq1 part
todo /dev/mapper/mpathd multipath
todo /dev/mapper/mpathd1 part
todo /dev/mapper/mpathbb multipath
todo /dev/mapper/mpathbb1 part
todo /dev/mapper/mpathav multipath
todo /dev/mapper/mpathav1 part
todo /dev/mapper/mpathbn multipath
todo /dev/mapper/mpathbn1 part
todo /dev/mapper/mpathai multipath
todo /dev/mapper/mpathai1 part
todo /dev/mapper/mpathp multipath
todo /dev/mapper/mpathp1 part
todo /dev/mapper/mpathba multipath
todo /dev/mapper/mpathba1 part
todo /dev/mapper/mpathc multipath
todo /dev/mapper/mpathc1 part
todo /dev/mapper/mpathau multipath
todo /dev/mapper/mpathau1 part
todo /dev/mapper/mpathbm multipath
todo /dev/mapper/mpathbm1 part
todo /dev/mapper/mpathah multipath
todo /dev/mapper/mpatho multipath
todo /dev/mapper/mpatho1 part
todo /dev/mapper/mpathb multipath
todo /dev/mapper/mpathb1 part
todo /dev/mapper/mpathat multipath
todo /dev/mapper/mpathat1 part
todo /dev/mapper/mpathbl multipath
todo /dev/mapper/mpathbl1 part
todo /dev/mapper/mpathag multipath
todo /dev/mapper/mpathag1 part
todo /dev/mapper/mpathn multipath
todo /dev/mapper/mpathn1 part
todo /dev/mapper/mpatha multipath
todo /dev/mapper/mpatha1 part
todo /dev/mapper/mpatha2 part
todo /dev/mapper/mpatha3 part
todo /dev/mapper/mpathas multipath
todo /dev/mapper/mpathas1 part
todo /dev/mapper/mpathz multipath
todo /dev/mapper/mpathz1 part
todo /dev/mapper/mpathbk multipath
todo /dev/mapper/mpathbk1 part
todo /dev/mapper/mpathaf multipath
todo /dev/mapper/mpathm multipath
todo /dev/mapper/mpathm1 part
todo /dev/mapper/mpathbw multipath
todo /dev/mapper/mpathbw1 part
todo /dev/mapper/mpathar multipath
todo /dev/mapper/mpathar1 part
todo /dev/mapper/mpathy multipath
todo /dev/mapper/mpathy1 part
todo /dev/mapper/mpathbj multipath
todo /dev/mapper/mpathbj1 part
todo /dev/mapper/mpathae multipath
todo /dev/mapper/mpathl multipath
todo /dev/mapper/mpathl1 part
todo /dev/mapper/mpathbv multipath
todo /dev/mapper/mpathbv1 part
todo /dev/mapper/mpathaq multipath
todo /dev/mapper/mpathaq1 part
todo /dev/mapper/mpathx multipath
todo /dev/mapper/mpathx1 part
todo /dev/mapper/mpathbi multipath
todo /dev/mapper/mpathbi1 part
todo /dev/mapper/mpathad multipath
todo /dev/mapper/mpathk multipath
todo /dev/mapper/mpathk1 part
todo /dev/mapper/mpathbu multipath
todo /dev/mapper/mpathbu1 part
todo /dev/mapper/mpathap multipath
todo /dev/mapper/mpathap1 part
todo /dev/mapper/mpathw multipath
todo /dev/mapper/mpathw1 part
todo /dev/mapper/mpathbh multipath
todo /dev/mapper/mpathbh1 part
todo /dev/mapper/mpathac multipath
todo /dev/mapper/mpathj multipath
todo /dev/mapper/mpathj1 part
todo /dev/mapper/mpathbt multipath
todo /dev/mapper/mpathbt1 part
todo /dev/mapper/mpathao multipath
todo /dev/mapper/mpathao1 part
todo /dev/mapper/mpathv multipath
todo /dev/mapper/mpathv1 part
todo /dev/mapper/mpathbg multipath
todo /dev/mapper/mpathbg1 part
todo /dev/mapper/mpathab multipath
todo /dev/mapper/mpathab1 part
todo /dev/mapper/mpathi multipath
todo /dev/mapper/mpathi1 part
todo /dev/mapper/mpathbs multipath
todo /dev/mapper/mpathbs1 part
todo /dev/mapper/mpathan multipath
todo /dev/mapper/mpathan1 part
todo /dev/mapper/mpathu multipath
todo /dev/mapper/mpathu1 part
todo /dev/mapper/mpathbf multipath
todo /dev/mapper/mpathbf1 part
todo /dev/mapper/mpathaa multipath
todo /dev/mapper/mpathaa1 part
todo /dev/mapper/mpathh multipath
todo /dev/mapper/mpathh1 part
todo /dev/mapper/mpathaz multipath
todo /dev/mapper/mpathaz1 part
todo /dev/mapper/mpathbr multipath
todo /dev/mapper/mpathbr1 part
todo /dev/mapper/mpatham multipath
todo /dev/mapper/mpatham1 part
todo /dev/mapper/mpatht multipath
todo /dev/mapper/mpatht1 part
todo /dev/mapper/mpathbe multipath
todo /dev/mapper/mpathg multipath
todo /dev/mapper/mpathg1 part
todo /dev/mapper/mpathay multipath
todo /dev/mapper/mpathay1 part
todo /dev/mapper/mpathbq multipath
todo /dev/mapper/mpathbq1 part
todo /dev/mapper/mpathal multipath
todo /dev/mapper/mpathal1 part
todo /dev/mapper/mpaths multipath
todo /dev/mapper/mpaths1 part
todo /dev/mapper/mpathbd multipath
todo /dev/mapper/mpathf multipath
todo /dev/mapper/mpathf1 part
todo /dev/mapper/mpathax multipath
todo /dev/mapper/mpathax1 part

**Comment by schabrolles** [comment]
I think we can close this one as it is now solved and continue the discussion about excluding GPFS in #1767
