### ISSUE TITLE
ReaR man page 'BACKUP SOFTWARE INTEGRATION' update needed?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1788]
* ReaR version: Current GitHub master

* Brief description of the issue:

I think the ReaR man page 'BACKUP SOFTWARE INTEGRATION' section
nedds an update/enhancement for BACKUP=TSM and BACKUP=BORG
because I think in both cases "rear mkbackup" is actually creating backups
in contrast to what is described in general in the man page.

Currently `man rear` and/or
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
reads (excepts):
<pre>
BACKUP SOFTWARE INTEGRATION
...
Please distinguish carefully between Relax-and-Recover support
for 3rd party backup software and Relax-and-Recover internal
backup methods. The latter also creates a backup of your data
while the former will only integrate Relax-and-Recover with the
backup software to restore the data with the help of the backup
software without actually creating backups. This means that
for all non-internal backup software you must take care of
creating backups yourself.
Especially the rear mkbackup command can be confusing
as it is only useful for the internal backup methods and has
no function at all with the other (external) backup methods.
...
The following BACKUP methods are external of Relax-and-Recover
meaning that you are responsible of backups being made:
...
BACKUP=TSM
...
BACKUP=BORG
</pre>

Regarding BACKUP=TSM:
I think since https://github.com/rear/rear/pull/1348 is merged
a TSM backup can be made during "rear mkbackup".

Regarding BACKUP=BORG:
In https://github.com/rear/rear/blob/master/doc/user-guide/04-scenarios.adoc
the section "ReaR with Borg back end" tells (excerpt):
<pre>
Executing rear mkbackup will create Relax-and-Recover rescue/recovery
system and start Borg backup process
</pre>

**Comment by gozora** [comment]
Hello @jsmeix,
I see your point here. But only reasonable correction of this text that comes to my mind is to introduce new term "mixed backup methods" ;-).

V.

**Comment by jsmeix** [comment]
I think - at last for now - some addedums that explain
the exceptional cases are sufficient, for example like
<pre>
BACKUP SOFTWARE INTEGRATION
...
Please distinguish carefully between Relax-and-Recover support
for 3rd party backup software and Relax-and-Recover internal
backup methods. The latter also creates a backup of your data
while the former will only integrate Relax-and-Recover with the
backup software to restore the data with the help of the backup
software without actually creating backups. This means that
for all non-internal backup software you must take care of
creating backups yourself (unless otherwise noted).
  [ added '(unless otherwise noted)' ]
Especially the rear mkbackup command can be confusing
as it is only useful for the internal backup methods and has
usually no function with the other (external) backup methods.
  [ added 'usually' ]
...
The following BACKUP methods are external of Relax-and-Recover
meaning that usually you are responsible of backups being made:
  [ added 'usually' ]
...
BACKUP=TSM
Use IBM Tivoli Storage Manager to restore the data.
The Relax-and-Recover result files (e.g. ISO image) are also saved into TSM.
There is a (currently experimental) first daft implementation
that a TSM backup is created by calling "dsmc incremental"
during "rear mkbackup".
  [ described the exceptional case ]
...
BACKUP=BORG
Use BorgBackup (short Borg) a deduplicating backup program
to backup and restore the data.
Executing "rear mkbackup" will create a Borg backup, see the section
"ReaR with Borg back end" in the ReaR user-guide "Scenarios" documentation.
  [ described the exceptional case ]
</pre>

**Comment by jsmeix** [comment]
I implemented
https://github.com/rear/rear/issues/1788#issuecomment-384992678
via https://github.com/rear/rear/pull/1791

@gozora @schabrolles 
if you do not object I will "just merge" it tomorrow.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1791 merged
this issue is fixed.
