### ISSUE TITLE
 2018-05-17 14:16:46.251048154 Including rescue/NSR/default/470_safe_filesystems.sh

### ISSUE THREAD

**Issue by nirmal21s** [rear/rear#1814]
OS Version :Red Hat Enterprise Linux Server release 7.5 (Maipo)
REAR rpm used : rear-2.3-1.el7.x86_64.rpm
Networker client : lgtoclnt-8.2.4.7-1.x86_64

local.conf : 
<pre>
NRSERVER=rn2barsv900-bar1
NSR_CLIENT_MODE=
OUTPUT=ISO
ISO_PREFIX="rear-nsr-$HOSTNAME"
BACKUP=NSR
OUTPUT_URL=file:///tmp
# Static IP (no DHCP!)
USE_DHCLIENT=
USE_STATIC_NETWORKING="y"
# NTP
TIMESYNC=NTP
</pre>

Error : 
<pre>
[VIP root@ts2otafe303: /usr/share/rear/rescue/NSR/default]$ rear -v mkrescue
Relax-and-Recover 2.3 / 2017-12-20
Using log file: /var/log/rear/rear-ts2otafe303.log
Creating disk layout
Using guessed bootloader 'GRUB'
No Networker ISO Backups found.
Creating root filesystem layout
Adding net.ifnames=1 to KERNEL_CMDLINE
Adding biosdevname=0 to KERNEL_CMDLINE
ERROR: The savefs command could not retrieve the "save sets" from this client
Aborting due to an error, check /var/log/rear/rear-ts2otafe303.log for details
Terminated
</pre>

**Comment by nirmal21s** [comment]
This time i installed the latest snapshot dump : 
VIP root@ts2otafe303: /etc/rear]$ rear dump
Relax-and-Recover 2.3-git.0.e4eb0e1.unknown / 2018-05-14
--------------------------------------------------------------------------------------------
This time also nsr_path was empty. 
mkrescue output attached
[mkrescue.txt](https://github.com/rear/rear/files/2014364/mkrescue.txt)
Site.conf : 
NRSERVER=
NSR_CLIENT_MODE=yes
OUTPUT=ISO
ISO_PREFIX="rear-nsr-$HOSTNAME"
BACKUP=NSR
OUTPUT_URL=file:///isorear/rear
export TMPDIR=/isorear/temprear
#
# Static IP (no DHCP!)
USE_STATIC_NETWORKING="y"
# NTP
TIMESYNC=NTP

**Comment by nirmal21s** [comment]
Hello Holger,

Any parameter needs to be changed on Backup server ,with respect to NSR_CLIENT_MODE ? 
Still the "savefs -p -s <NSRSERVER" command is not executing in 470_safe_filesystems.sh.
But when i run this command on client its showing the output.

**Comment by hpannenb** [comment]
@nirmal21s: ReaR behaves as per design here: In the NSR_CLIENT_MODE the NSR_PATH is not gathered and not required. The data recovery for the to be recovered server has to be initiated on the networker server side at a later stage of the recovery process. Once the rescue image has been booted ReaR will prepare the to be recovered server during the "rear recover" process and a prompt is shown to trigger the data recovery at a later stage (see [400_restore_with_nsr.sh](https://github.com/rear/rear/blob/17d8cf2778d4d22db12f2d0751c8fb5d82e95308/usr/share/rear/restore/NSR/default/400_restore_with_nsr.sh)).

**Comment by nirmal21s** [comment]
Thanks Holger!
I will do the testing and confirm you the status.

Again thanks for your help.
