### ISSUE TITLE
mount: mount(2) failed: /mnt/local: No such file or directory

### ISSUE THREAD

**Issue by mreubold** [rear/rear#1823]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 1.17.2 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
openSUSE 42.3 (ppc64le)

* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):
<pre>
BACKUP=NETFS
OUTPUT=ISO
BACKUP_URL=nfs://wdaix01/home/export
BACKUP_OPTIONS=nfsvers=3,nolock
NETFS_KEEP_OLD_BACKUP_COPY=
USE_DHCLIENT=
MODULES_LOAD=( )
BACKUP_PROG_INCLUDE=(/boot/grub2/powerpc-ieee1275/* /opt/* /srv/* /tmp/* /usr/local/* /var/cache/* /var/lib/libvirt/images/* /var/lib/machines/* /var/lib/mailman/* /var/lib/mariadb/* /var/lib/mysql/* /var/lib/named/* /var/lib/pgsql/* /var/log/* /var/opt/* /var/spool/* /var/tmp/*)
POST_RECOVERY_SCRIPT=(if\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ get-config\ |\ grep\ -q\ "^QGROUP.*[0-9]/[0-9]"\ ;\ then\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ set-config\ QGROUP=\ ;\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ setup-quota\ &&\ echo\ snapper\ setup-quota\ done\ ||\ echo\ snapper\ setup-quota\ failed\ ;\ else\ echo\ snapper\ setup-quota\ not\ used\ ;\ fi)
REQUIRED_PROGS=(snapper chattr lsattr ${REQUIRED_PROGS[@]})
COPY_AS_IS=(/usr/lib/snapper/installation-helper /etc/snapper/config-templates/default ${COPY_AS_IS[@]})
</pre>

* System architecture (x86 compatible or POWER and/or what kind of virtual machine):
POWER8 IBM, Lpar with vscsi disks from shared storage pool 

* Are you using BIOS or UEFI or another way to boot?
POWERVM

* Brief description of the issue:
Backup up in creating iso file for boot and backup tar.gz. Booting from recovery iso file ok but during restore process we get : 
<pre>
Starting Initialize Rescue System...
/etc/rear/local.conf: line 18: syntax error near unexpected token `|'
/etc/rear/local.conf: line 18: `POST_RECOVERY_SCRIPT=(if\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ get-config\ |\ grep\ -q\ "^QGROUP.*[0-9]/[0-9]"\ ;\ then\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ set-config\ QGROUP=\ ;\ snapper\ --no-dbus\ -r\ $TARGET_FS_ROOT\ setup-quota\ &&\ echo\ snapper\ setup-quota\ done\ ||\ echo\ snapper\ setup-quota\ failed\ ;\ else\ echo\ snapper\ setup-quota\ not\ used\ ;\ fi)'
* * * Configuring Rescue System * * *
Running 00-functions.sh...
Running 10-console-setup.sh...
...
process goes on and then :  
...
Start system layout restoration.
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
+++ create_component /dev/sdb disk
+++ local device=/dev/sdb
+++ local type=disk
+++ local touchfile=disk--dev-sdb
+++ '[' -e /tmp/rear.zoHwSXo1GvzDN4Q/tmp/touch/disk--dev-sdb ']'
+++ return 0
+++ Log 'Stop mdadm'
...
and 
...
+++ new_uuid=832aa16a-6f02-4d12-ae03-c9e2c2f97a00
+++ '[' 204c42b9-561b-4d48-bbde-bea673cbcd26 '!=' 832aa16a-6f02-4d12-ae03-c9e2c2f97a00 ']'
pping
grep: /var/lib/rear/layout/fs_uuid_mapping: No such file or directory
+++ echo '204c42b9-561b-4d48-bbde-bea673cbcd26 832aa16a-6f02-4d12-ae03-c9e2c2f97a00 /dev/sdb3'
+++ LogPrint 'Mounting filesystem /'
+++ Log 'Mounting filesystem /'
+++ test 1 -gt 0
++++ Stamp
++++ date '+%Y-%m-%d %H:%M:%S '
+++ echo '2018-06-01 17:23:59 Mounting filesystem /'
2018-06-01 17:23:59 Mounting filesystem /
+++ Print 'Mounting filesystem /'
+++ test 1
+++ echo -e 'Mounting filesystem /'
+++ mkdir -p /mnt/local/
+++ mount -t btrfs -o rw,relatime,space_cache,subvolid=260,subvol=/@/.snapshots/1/snapshot /dev/sdb3 /mnt/local/
mount: mount(2) failed: /mnt/local: No such file or directory
2018-06-01 17:24:02 An error occurred during layout recreation.
</pre>

* Work-around, if any:
none

On the source system (the one backuop was taken) the lvm socket is active 
<pre>
lvm2-lvmetad.socket                                   loaded active listening LVM2 metadata daemon socket
</pre>

**Comment by schabrolles** [comment]
@mreubold,
rear 1.17 is pretty old and known to have a lot of issues with Power. Since, a lot of improvement were brought to better support ppc64le arch and powerVM LPAR. I really recommend you to evaluate to latest code available (git master branch) or get the nightly built packages for opensuse here: http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/openSUSE_Factory_PowerPC/

**Comment by jsmeix** [comment]
@mreubold 
first and foremost you should fix your syntax error in your /etc/rear/local.conf
(use the examples in usr/share/rear/conf/examples/ as templates).

Basically all files in ReaR are scripts so that also what
is used as config files are actually scripts like
/usr/share/rear/conf/default.conf and /etc/rear/local.conf
which are also sourced (and executed) as scripts.

**Comment by mreubold** [comment]
@jsmeix : I've used yast2 rear to create the local.conf file and I guess this was taken from the templates. BTW as schabrolles suggested I'm going to test a newer version. Currently having problems with multipath on ibm-vscsi devices. The disk is one on SSP pools served from dual vios configuration hence /dev/sda + /dev/sdb are the same disk.

**Comment by jsmeix** [comment]
@mreubold 
frankly: personally I would recommend to not use `yast2 rear`.
I never use it. I perfer straightforward things (like `vi`) whenever possible.
You would need to contact YaST people in case of issues with `yast2 rear`.

For multipath issues @schabrolles is the expert.

In general I would recommend to have a closer look at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
I reported the `yast2 rear` issue as
https://bugzilla.opensuse.org/show_bug.cgi?id=1096218

**Comment by jsmeix** [comment]
Accoding to "no news is good news" I assume
the ReaR issue here (not the the issue in `yast2 rear`)
is fixed when using current ReaR upstream GitHub master code.
