### ISSUE TITLE
'Kernel panic' during recovery

### ISSUE THREAD

**Issue by malvinas2** [rear/rear#1825]
Hello, 

I created several backups using USB-sticks with Rear, e.g. "May_2018", "January_2018" or "October_2017". 
While I tried to recover my system as described in [Recovery failed - 'disk layout recreation script failed' #1824](https://github.com/rear/rear/issues/1824), luckily the latest backup -May- worked. But the other two just resulted in a kernel panic error. I saved a screenshot of the error message at [https://imgur.com/2v0ior0](https://imgur.com/2v0ior0). 
Are the usb-sticks corrupted or what's wrong here? 

EDIT: It is possible to mount both partitions of the two usb-sticks, but a check of the file systems shows inconsistencies: 

```
root@ubuntu:~# fsck.vfat -n /dev/sde1
fsck.fat 3.0.28 (2015-05-16)
/dev/sde1: 9 files, 44032/51145 clusters

root@ubuntu:~# e2fsck -f /dev/sde2
e2fsck 1.42.13 (17-May-2015)
Durchgang 1: Inodes, Blöcke und Größen werden geprüft
Inode 8 hat unzulässige(n) Block/Blöcke.  Bereinigen<j>? nein
Unzulässiger indirekte Blöcke (41947392) in Inode 8.  IGNORIERT.
Fehler beim Iterieren über die Blöcke in Inode 8: Es wurde ein ungültiger indirekter Block gefunden

REAR-000: ********** WARNUNG: Noch Fehler im Dateisystem  **********

e2fsck: abgebrochen

REAR-000: ********** WARNUNG: Noch Fehler im Dateisystem  **********

root@ubuntu:~#
```

```
root@ubuntu:~# hdparm -C /dev/sde

/dev/sde:
SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0a 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 drive state is:  standby
```

**Comment by gdha** [comment]
@malvinas2 My advise is to do a boot test of each USB stick after you created a rescue image on it. This way you will avoid lots of issues afterwards.
It is not the first time that certain types of USB sticks are untrust-worthy.

**Comment by malvinas2** [comment]
Good advice ;-)
In my case it wouldn't have been that bad, because besides the USB sticks I additonally saved the corresponding iso-files to an external harddisc. I am, however, somewhat surprised that even new USB-sticks which never had been used before for other purposes, show this negative behaviour.....
