### ISSUE TITLE
Wrong dependencies in ubuntu 18.04 (iproute)

### ISSUE THREAD

**Issue by didacog** [rear/rear#1826]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Current ReaR GitHub master
* Brief description of the issue:
The dependencies for rear in debian based OSes in
https://github.com/rear/rear/blob/master/packaging/debian/control#L12
include `iproute` but that is not present in new ubuntu 18.04, see
https://github.com/brainupdaters/drlm/issues/79#issuecomment-387434378
* Work-around, if any:
Maybe put iproute in suggests or recommends instead of Depends?

**Comment by gdha** [comment]
@didacog Has it been replaced by something else?

**Comment by didacog** [comment]
It seems that they moved to iproute2:
https://packages.ubuntu.com/bionic/iproute2

**Comment by jsmeix** [comment]
I am puzzled by
https://github.com/rear/rear/issues/1826#issue-331084300
that reads `ReaR version ("/usr/sbin/rear -V"): 2.4`

Was ReaR version 2.4 already released?

**Comment by didacog** [comment]
@jsmeix 

No, but is the actual master that will be rear 2.4. Sorry for the wrong description :P

**Comment by gdha** [comment]
With PR in place the **blocker** label may be removed again.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1827 merged
this issue should be fixed.
