### ISSUE TITLE
Which rpm to be used for RHEL5.8 with i686 arch

### ISSUE THREAD

**Issue by nirmal21s** [rear/rear#1834]
I need to install REAR for Red Hat Enterprise Linux Server release 5.8 (Tikanga)
Arch is i686.
I could not find Rear rpm for this arch. 
Kindly guide me on which rpm will suit.

**Comment by gdha** [comment]
See at http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/RedHat_RHEL-5/i386/ for a stable version, or http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/RedHat_RHEL-5/i386/ for the unstable version

**Comment by jsmeix** [comment]
I assume with
https://github.com/rear/rear/issues/1837
also this issue got solved.
