### ISSUE TITLE
Strange `# vim: set et ts=4 sw=4:` comments at the end of some scrips

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1844]
In current ReaR master code some scripts have a last line
<pre>
# vim: set et ts=4 sw=4:
</pre>
which got added by @rmetrich via
https://github.com/rear/rear/commit/b184194f37dd22a7e55655ff388579297239e73c
and
https://github.com/rear/rear/commit/84f03a4a2828ad21a1ab770b5737db9dac41074c

I.e. in current ReaR master code there is
<pre>
 $ find usr/sbin/rear usr/share/rear/ | xargs grep 'vim:' 2>/dev/null

usr/share/rear/lib/layout-functions.sh:# vim: set et ts=4 sw=4:
usr/share/rear/prep/GNU/Linux/220_include_lvm_tools.sh:# vim: set et ts=4 sw=4:
usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh:# vim: set et ts=4 sw=4:
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh:# vim: set et ts=4 sw=4:
</pre>

I guess this is some special automatism by the `vi` editor.

@rmetrich 
could you explan the reason behind
and whether or not I should remove them
or if it makes sense to have those trailing comment lines.

**Comment by rmetrich** [comment]
@jsmeix these directives tell vim to automatically adjust when editing the file:
- et : expand tabs
- ts=4 : 4 spaces when expanding a <tab> found in the file
- sw=4 : 5 spaces when hitting <tab> on your keyboard

Since most of ReaR's code is indented using these settings, keeping that would be nice to avoid messing up the files.

**Comment by jsmeix** [comment]
@rmetrich 
thanks for your prompt reply!
Now I understand.

**Comment by jsmeix** [comment]
@gdha @gozora @schabrolles 
what do you think:

Schouldn't then such a trailing comment line
<pre>
# vim: set et ts=4 sw=4:
</pre>
be appended to every ReaR script?

**Comment by gozora** [comment]
Honestly I didn't know about this feature, but I'd personally prefer to keep editor settings out of source code mainly because other users might appear with different editors storing another set of "meta-data" which could lead to mess...

V.

**Comment by rmetrich** [comment]
As you wish, although such metadata is widely used among projects, e.g. mariadb, sos, ruby, rsyslog, gnutls, NetworkManager, ...

Even in rear, it is already used in packaging/arch/PKGBUILD.

**Comment by gozora** [comment]
Don't get me wrong Renaud, I'm not going to fight to keep this away from ReaR source code, if you guys think this is a useful idea, let's keep it, no problem with that from my site.
My editor for example, keeps meta-data information (e.g. information about collapsed sections etc.) in separate files (dot prefixed) directly in source tree and I just thought that it might be disturbing for other people to deal with them, so I've reconfigured this behavior ...

V.

**Comment by jsmeix** [comment]
I hope such comments cannot cause real trouble (because they are only comments)
and because they are useful in some cases it is o.k. for me to have them.
I think the only real trouble that such comments could cause are the usual
"what is the right editor" plus "what is the right indentation style" wars ;-)

**Comment by rmetrich** [comment]
I can answer to "what is the right editor" ;-)

**Comment by jsmeix** [comment]
My editor is the only right one that is used by real hard men ;-)

**Comment by gozora** [comment]
@jsmeix `ed` ?

**Comment by rmetrich** [comment]
likely, at his time there was only that ;-)

**Comment by rmetrich** [comment]
or even maybe his editor was a puncher, for punch cards ;-)

**Comment by jsmeix** [comment]
@rmetrich 
in ancient times real hard men used a puncher chisel and a big hammer...
http://www.wordinfo.info/words/images/graph-epigraph-Egyptian-Col.gif

**Comment by jsmeix** [comment]
I think this issue is sufficiently discussed so that I can close it
and the consensus it that it is o.k. to have those comments
but it is not required to have such comments in every file or script.
