### ISSUE TITLE
Fedora28 need ldlinux.c32 with PXE booting

### ISSUE THREAD

**Issue by gdha** [rear/rear#1861]
* ReaR version ("/usr/sbin/rear -V"): >= 2.4
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): fedora28
* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"): PXE booting
* System architecture (x86 compatible or POWER and/or what kind of virtual machine): x86_64
* Are you using BIOS or UEFI or another way to boot? BIOS
* Brief description of the issue: PXE booting halts due to the missing ldlinux.c32 executable (part of syslinux)

**Comment by jsmeix** [comment]
@gdha 
you set "waiting for info" - what info and from whom do you need?
I assume with https://github.com/rear/rear/pull/1862
this issue is "fixed/solved/done" - isn't it?

**Comment by gdha** [comment]
@jsmeix I'm waiting on myself ;-) to do a full cycle test.

**Comment by gdha** [comment]
Yes this is fixed
