### ISSUE TITLE
LPAR/PPC64 bootlist is incorrectly set when having multiple 'prep' partitions

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1886]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): latest

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): RHEL7

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): AIX/LPAR

* System architecture (x86 compatible or PPC64/PPC64LE or what excat ARM device): PPC64/PPC64LE

* Description of the issue (ideally so that others can reproduce it):

When having 2 or more `prep` partitions, the code setting up the `bootlist` fails.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1887 merged
this issue should be fixed.
