### ISSUE TITLE
Rear changing permission on bin files

### ISSUE THREAD

**Issue by silent-mobius** [rear/rear#1896]
Relax-and-Recover (ReaR) Issue Template
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

ReaR version ("/usr/sbin/rear -V"): 2.4 / 2018-06.21

OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
<pre>
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):
OUTPUT=ISO
OUTPUT_URL=cifs://192.168.0.5/System_backup/
BACKUP_URL=cifs://192.168.0.5/System_backup/
BACKUP=NETFS
BACKUP_OPTIONS="cred=/etc/rear/cifs"
OUTPUT_OPTIONS="cred=/etc/rear/cifs"
</pre>

Real hardware (PC or PowerNV BareMetal or ARM) and/or virtual machine (KVM guest or PoverVM LPAR):
PC

System architecture (x86 compatible or POWER PPC64/PPC64LE or what excat ARM device):
x86_64

Are you using BIOS or UEFI or another way to boot (Open Firmware or Petitboot)?
BIOS

Brief description of the issue:
After restoring the system, the bin commands, e.g. ping, ls, cp and so on,  are getting "permission denied" with regular user( e.g. user named silentmobius that is listed at /etc/passwd)
Work-around, if any:
I am changin the permissions with root and setting the id with setuid.

**Comment by jsmeix** [comment]
I am not a Red Hat / Fedora or CentOS user but
I think this issue is basically the same or at least similar as
https://github.com/rear/rear/issues/1175
therein see in particular
https://github.com/rear/rear/issues/1175#issuecomment-315004132
and
https://github.com/rear/rear/issues/1411

In genaral when you need to do some special adaptions after "rear recover"
you can automate that via POST_RECOVERY_SCRIPT,
see usr/share/rear/conf/default.conf

**Comment by gdha** [comment]
@silent-mobius could you list the exact permissions after the recovery? Never encountered this problem description before.

**Comment by silent-mobius** [comment]
After some research, we found that it's tar issue. When backup.tar.gz is created it's changing the permissions of bin files to 600.
