### ISSUE TITLE
Rear ISO size increased from 350MB to 550MB in 2 days.

### ISSUE THREAD

**Issue by nirmal21s** [rear/rear#1898]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):2.3

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):RHEL 7.5

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

<pre> 
NSRSERVER=
NSR_CLIENT_MODE=yes
OUTPUT=ISO
ISO_PREFIX="rear-nsr-$HOSTNAME"
BACKUP=NSR
OUTPUT_URL=file:///
export TMPDIR=/
##Static IP (no DHCP!)
USE_STATIC_NETWORKING=yes
##NTP
#TIMESYNC=NTP
</pre>

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):Physical

* System architecture (x86 compatible or PPC64/PPC64LE or what excat ARM device):x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):BIOS

* Description of the issue (ideally so that others can reproduce it):
Is there any way to find  he cause or change that made the  ISO size to grow.

**Comment by gdha** [comment]
See #734 - I think you also backup the previous ISO file. Why is the `NSRSERVER` variable empty? Check the rear log file it can tell you more (or compare it with previous logs)? And, use debug mode which keeps the temporary ISO directory to be inspected afterwards.

**Comment by jsmeix** [comment]
@nirmal21s 
mount your ISOs and compare what grow in them.

For example when I have the backup in the ISO I get on my system:
<pre>
# mount /var/lib/rear/output/rear-f144.iso /mnt
mount: /dev/loop0 is write-protected, mounting read-only

# ls -lRh /mnt
/mnt:
total 4.0K
drwx------ 1 root root 2.0K Aug  9 15:23 isolinux
drwxr-x--- 1 root root 2.0K Aug  9 15:23 mybackup

/mnt/isolinux:
total 97M
-r-------- 1 root root 2.0K Aug  9 15:23 boot.cat
-rw------- 1 root root  20K Aug  9 15:23 chain.c32
-rw------- 1 root root 275K Aug  9 15:23 hdt.c32
-rw------- 1 root root  90M Aug  9 15:23 initrd.cgz
-rw------- 1 root root  24K Aug  9 15:23 isolinux.bin
-rw------- 1 root root 2.1K Aug  9 15:23 isolinux.cfg
-rw-r--r-- 1 root root 5.7M Jul  8  2017 kernel
-rw------- 1 root root  54K Aug  9 15:23 menu.c32
-rw------- 1 root root  261 Aug  9 15:23 message
-rw------- 1 root root 988K Aug  9 15:23 pci.ids
-rw------- 1 root root  239 Aug  9 15:23 poweroff.com
-rw------- 1 root root  985 Aug  9 15:23 rear.help
-rw------- 1 root root  800 Aug  9 15:23 reboot.c32
-rw------- 1 root root 150K Aug  9 15:23 vesamenu.c32

/mnt/mybackup:
total 933M
-rw-r--r-- 1 root root 9.9M Aug  9 15:23 backup.log
-rw-r--r-- 1 root root 923M Aug  9 15:23 backup.tar.gz
</pre>

**Comment by gdha** [comment]
@nirmal21s any update from your side?

**Comment by gdha** [comment]
@nirmal21s you can also define `OUTPUT_URL=null` if you want

**Comment by jsmeix** [comment]
No news is good news.
