### ISSUE TITLE
Add support for excluding logicaldrive

### ISSUE THREAD

**Issue by pavoldomin** [rear/rear#19]
I want to exclude smart array logicaldrive recreation; placed this in config:

    # grep logical /etc/rear/site.conf
    EXCLUDE_RECREATE=( fs:/backup logicaldrive:/dev/cciss/c0d0 logicaldrive:cciss/c0d0 )

    # rear -D -v savelayout
    Relax and Recover 0.0.810 / 2012-03-16 18:37:24 +0100    
    Creating disk layout
    Excluding RAID md2. 
    Excluding Volume Group lvlocal
    Excluding Volume Group vgbackup
    Excluding component fs:/backup
    Excluding component logicaldrive:/dev/cciss/c0d0
    Excluding component logicaldrive:cciss/c0d0
    Finished in 20 seconds

However, it's still included in disklayout:

    # grep c0d0 /var/lib/rear/layout/disklayout.conf
    # disk /dev/cciss/c0d0 146778685440 msdos
    # part /dev/cciss/c0d0 213057536 16384 primary none /dev/cciss/c0d0p1
    # part /dev/cciss/c0d0 146565611520 213073920 primary none /dev/cciss/c0d0p2
    # lvmdev /dev/lvlocal /dev/cciss/c0d0p2 XelE5V-1QBS-QbUV-8APC-m3UY-Y55t-ElRQ7W 286260960
    logicaldrive /dev/cciss/c0d0 0|A|1 raid=1 drives=1I:1:1,1I:1:2, spares= sectors=32 stripesize=

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature
