### ISSUE TITLE
In recovery mode rear -h does not work

### ISSUE THREAD

**Issue by gdha** [rear/rear#1901]
* ReaR version ("/usr/sbin/rear -V"): master

* Description of the issue (ideally so that others can reproduce it): in recovery the command `rear -h` does not work:
````
RESCUE client:~ # rear -h
ERROR: The workflow help is not supported in the ReaR rescue/recovery system
Some latest log messages since the last called script 050_check_rear_recover_mode.sh:
  2018-08-22 09:27:04.161732852 Including init/default/050_check_rear_recover_mode.sh
Aborting due to an error, check /var/log/rear/rear-client.log.lockless for details
Terminated
````

* Work-around, if any: none

**Comment by jsmeix** [comment]
See the related https://github.com/rear/rear/issues/1939

@gdha 
do you perhaps know what the reason behind was
why in init/default/050_check_rear_recover_mode.sh
the help workflow is not allowed inside the recovery system?

My forensics via
`git log -p --follow usr/share/rear/init/default/050_check_rear_recover_mode.sh`
shows that this script originated by you via
https://github.com/rear/rear/commit/ad2283c402736253e4f76d36659f353695aeceea
probably as a result of
https://github.com/rear/rear/issues/719#issuecomment-159967555

Perhaps therein
`From within the rescue system you can only run rear recover`
was too restrictive?

**Comment by jsmeix** [comment]
The pull request https://github.com/rear/rear/pull/1940
intends to fix this issue.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1940 merged
this issue should be fixed.
