### ISSUE TITLE
chroot bash test failed

### ISSUE THREAD

**Issue by nieberad** [rear/rear#1904]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.00 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): Red Hat Enterprise Linux Server release 5.9 (Tikanga)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): 
````
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is. 
# Our packages will never ship with a site.conf.
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=null
BACKUP_URL="iso:///backup"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/rear_backup' '/tmp' '/hana')
ISO_DIR="/rear_backup"
````
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): HP GL360

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

First tried NFS, then local disk for temp storage

* Description of the issue (ideally so that others can reproduce it):
````
ERROR: 
====================
BUG in /usr/share/rear/build/default/980_verify_rootfs.sh:
'ROOTFS_DIR '/home/rear_backup/rear.EIhIZpeycV11717/rootfs' is broken, chroot bash test failed.'
````
* Work-around, if any:

**Comment by nieberad** [comment]
[root@m500356 ~]# chroot /rear_backup/rear.nTacClGBVf29196/rootfs/ bash -c true
chroot: cannot run command `bash': No such file or directory
[root@m500356 ~]# ls -ltr /rear_backup/rear.nTacClGBVf29196/rootfs/bin/bash
-rwxr-xr-x 1 root root 801816 Sep 25  2014 /rear_backup/rear.nTacClGBVf29196/rootfs/bin/bash

It exists, so I dunno, kinda baffling to me.

**Comment by nieberad** [comment]
[root@m500356 ~]# cat .bash_profile 
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
unset USERNAME

**Comment by gdha** [comment]
@nieberad guessing this is related to #1905, no?
Try first to create a rescue image in debug mode:
````
rear -vdD mkrescue
````
and check the log file first. The real error will pop up somewhere.

**Comment by gdha** [comment]
@nieberad Did you check the log file of rear to see what exactly went wrong?

**Comment by jsmeix** [comment]
No news is good news.
