### ISSUE TITLE
rescue/GNU/Linux/500_clone_keyboard_mappings.sh: find traverses recursively from "/"

### ISSUE THREAD

**Issue by Lukey3332** [rear/rear#1906]
* ReaR version ("/usr/sbin/rear -V"): 2.4 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): debian buster

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): amd64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): BIOS / GRUB2

* Description of the issue (ideally so that others can reproduce it):
When doing rear mkbackup, a "find" command will traverse trough all filesystems from the root, which is quite inefficient. (see line 42 in rescue/GNU/Linux/500_clone_keyboard_mappings.sh ) There doesn't seem to be "/usr/share/keymaps" or any other keymap Directory in Debian buster. 

* Work-around, if any:
Set KEYMAPS_DEFAULT_DIRECTORY and KEYMAPS_DIRECTORY to point to an Empty Directory.

**Comment by gdha** [comment]
@Lukey3332 line 42? Can you be a bit more specific please?

**Comment by Lukey3332** [comment]
I meant in rescue/GNU/Linux/500_clone_keyboard_mappings.sh

**Comment by gdha** [comment]
@Lukey3332 are the keymaps perhaps under `/usr/share/console/lists/` ?

**Comment by Lukey3332** [comment]
@gdha No, that doesn't exist either. But I did check with apt-file and `/usr/share/keymaps` Is provided by the `console-data` Package which isn't installed on my System. Still I think that rear shouldn't try to search for a Keymap on the whole system if the directories already don't exist.

**Comment by gdha** [comment]
@Lukey3332 I agree that it is a bit overkill, but as the code was written by @jsmeix I leave the decision with him (when he is back from holiday).

**Comment by jsmeix** [comment]
This is a bug that I will fix when time permits.

It was never meant to search the whole tree of filesystems.
I failed to imagine what happens when `$keymaps_default_directory` is empty.
"Fortunately" (not really - I provide config variables for all stuff intentionally ;-)
there are config variables that can be used to avoid that issue.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1935 merged
this issue should be fixed.
