### ISSUE TITLE
Manually define BACKUP_URL and OUTPUT_URL to default values.

### ISSUE THREAD

**Issue by pdanek** [rear/rear#1919]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
rear-2.00-7

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
RHEL 7.5

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
https://github.com/thbe/puppet-rear/blob/master/manifests/params.pp

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
VMware guest

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS / GRUB

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN

* Description of the issue (ideally so that others can reproduce it):

We have cloned the existing Puppet module puppet-rear and because of our company policy, we prefer not to modify the modules directly (so we don't have to constantly maintain them when getting new version from upstream), but instead redefine things in dedicated YAML files.

Unfortunately the puppet-rear module already defines both BACKUP_URL and OUTPUT_URL and we don't want those:
output_url = 'nfs://192.168.0.1/srv/rear'
backup_url = 'nfs://192.168.0.1/srv/rear'

What we need and what worked great for us with manual testing or ReaR without Puppet was:
OUTPUT=ISO
BACKUP=NBU
... and both backup_url and output_url should be undefined in local.conf

Now we don't want to touch the module itself but redefine these 2 values back to DEFAULT in our YAML file.
How to properly do this please?
We can't leave them empty because then values from the puppet module will be used, so we need to manually set BACKUP_URL and OUTPUT_URL to default values.

* Work-around, if any:
Modifying the Puppet module itself, but that's not what we want.

**Comment by gdha** [comment]
@pdanek `OUTPUT_URL=null` is a possibility. For `BACKUP_URL` we do not have a `null` setting as that makes no sense. However, if you use `BACKUP=NBU` it really doesn't matter what the content is of `BACKUP_URL` 
Why question - what do you do with the ISO image? Does it stay on the system itself?

PS: interesting puppet cookbook - I'm not using puppet myself, but I'm using Chef instead. It is on my list to create a Chef cookbook for rear as well someday.

**Comment by pdanek** [comment]
@gdha Blazing fast reply as always, so we can use following?
OUTPUT=ISO
OUTPUT_URL=null
BACKUP=NBU
BACKUP_URL='nfs://192.168.0.1/srv/rear'

And it will be exactly the same effect as having only this:
OUTPUT=ISO
BACKUP=NBU

Reply to why question: yes we keep the ISO locally on each server in /var/lib/rear/output/ where it gets replaced with every new mkrescue.
This ISO will:
- get automatically backed up by Netbackup
- we want to schedule UC4 job which will copy the ISO from each server

**Comment by gdha** [comment]
@pdanek yes that should do the trick. Just test it out ;-)

**Comment by gdha** [comment]
@pdanek any feedback from your end?

**Comment by pdanek** [comment]
Yes, that did the trick, thanks!
Apologies for forgotten feedback.
