### ISSUE TITLE
mkbackup and mkrescue failing with nvme disks

### ISSUE THREAD

**Issue by perlvan** [rear/rear#1928]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4 / 2018-06-21
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
````
NAME="Oracle Linux Server"
VERSION="6.9"
ID="ol"
VERSION_ID="6.9"
PRETTY_NAME="Oracle Linux Server 6.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:6:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6"
ORACLE_BUGZILLA_PRODUCT_VERSION=6.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=6.9
````
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

````
KERNEL_FILE="/boot/vmlinuz-4.1.12-94.7.8.el6uek.x86_64"
PROGS=( ${PROGS[@]} /usr/bin/dsmc /sbin/ifconfig /sbin/route /bin/netstat )
BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' )

# Files/dirs to copy as-is (with tar):
COPY_AS_IS=( ${COPY_AS_IS[@]} /etc/adsm /etc/ofed /etc/magic /usr/share/misc/magic /sbin/modprobe.ksplice-orig )

TIMESYNC=NTP
KEEP_BUILD_DIR=false

# Default Backup and Output Targets:
BACKUP=NETFS
OUTPUT=PXE

BACKUP_URL=nfs://xxxxxxxxxxxxxxxxxxxxx/xxxxxxxx/
NETFS_SKIP_WARNING=1
# NETFS_OPTIONS="nolock,noauto,mountvers=3,nfsvers=3,intr"
NETFS_OPTIONS="nolock,vers=3,rw"
NETFS_PREFIX="$( uname -n )"

# BACKUP_URL="${NETFS_URL}"
BACKUP_OPTIONS="${NETFS_OPTIONS}"
BACKUP_SELINUX_DISABLE=1

# OUTPUT_URL="${NETFS_URL}"
OUTPUT_URL="${BACKUP_URL}"
OUTPUT_OPTIONS="${NETFS_OPTIONS}"
OUTPUT_PREFIX="${NETFS_PREFIX}"
#GRUB_RESCUE=1
#GRUB_RESCUE_PASSWORD="xxxxxxxxxx"
# ISO Stuff:
if [[ "${OUTPUT}" = "ISO" ]]; then
        BACKUP_URL="iso:///backup"
        OUTPUT_URL="null"
        ISO_PREFIX="rear-$( hostname -s )"
        # ISO_DIR="/net/$( echo ${NETFS_URL} | sed -e 's|^nfs://||' )/${NETFS_PREFIX}"
        ISO_DIR="/net/$( echo ${BACKUP_URL} | sed -e 's|^nfs://||' )/${NETFS_PREFIX}"
        ISOIMG="/opt/oracle.cellos/iso/isolinux.bin"
        [[ -f $ISOIMG ]] && ISO_ISOLINUX_BIN="${ISOIMG}"
        ISO_MKISOFS_BIN="$( type -p mkisofs || type -p genisoimage )"
fi
# PXE related:
if [[ "${OUTPUT}" = "PXE" ]]; then
        PXE_CREATE_LINKS=MAC
        PXE_REMOVE_OLD_LINKS="true"
        OUTPUT_PREFIX_PXE=""
        BACKUP_PROG=tar
        BACKUP_TYPE=full
fi
# Files whose changes warrant a new rescue image
CHECK_CONFIG_FILES=( '/etc/drbd/' '/etc/drbd.conf' '/etc/lvm/lvm.conf' '/etc/multipath.conf' '/etc/rear/' '/etc/udev/udev.conf' '/sbin/modprobe.ksplice' )
````

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
BareMetal
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI; bootloader GRUB
* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
NVMe with software RAID (1-mirroring)
* Description of the issue (ideally so that others can reproduce it):

* Work-around, if any:

**Comment by perlvan** [comment]
/usr/share/rear/lib/_input-output-functions.sh: line 328: type: sedutil-cli: not found
2018-10-12 15:09:44.394728129 Including layout/save/GNU/Linux/200_partition_layout.sh
2018-10-12 15:09:44.409437248 Saving disk partitions.
2018-10-12 15:09:44.484278574 No partitions found on /dev/nvme0n1.
2018-10-12 15:09:44.555495100 No partitions found on /dev/nvme1n1.
2018-10-12 15:09:44.622445361 No partitions found on /dev/nvme2n1.
2018-10-12 15:09:44.683813445 No partitions found on /dev/nvme3n1.
2018-10-12 15:09:44.688994580 Including layout/save/GNU/Linux/210_raid_layout.sh
2018-10-12 15:09:44.691630235 Saving Software RAID configuration.
/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh: line 44: let: sparedevices=2-: syntax error: operand expected (error token is "-")
/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh: line 65: [: : integer expression expected
2018-10-12 15:09:44.840130795 No partitions found on /dev/md127.
/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh: line 44: let: sparedevices=2-: syntax error: operand expected (error token is "-")
/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh: line 65: [: : integer expression expected
2018-10-12 15:09:44.967452392 No partitions found on /dev/md126.
2018-10-12 15:09:45.579209995 Including layout/save/GNU/Linux/220_lvm_layout.sh
2018-10-12 15:09:45.581065921 Saving LVM layout.
2018-10-12 15:09:46.381867155 Including layout/save/GNU/Linux/230_filesystem_layout.sh
2018-10-12 15:09:46.384240201 Begin saving filesystem layout
2018-10-12 15:09:46.388066793 Saving filesystem layout (using the findmnt command).
2018-10-12 15:09:46.490597687 /dev/mapper/VGExaDb-TEST_admin is mounted below /var/lib/docker (mount point /data/oracle/TEST/admin is under docker control), skipping.

**Comment by gdha** [comment]
@perlvan Please give some more details about your RAID layout. Are you using Oracle ASM?
You could also run `rear -vD mkrescue` for having debugging, that way we can see better why it fails.

**Comment by perlvan** [comment]
Yes, we use Oracle ASM. For some reasons i can't attach the logs.. Pasting the snippets of the log..

Given below is the output for -vD mkrescue .. 
Relax-and-Recover 2.4 / 2018-06-21
Using log file: /var/log/rear/rear-xxxxxxxx.log
Using backup archive '/tmp/rear.GQIYy90Tu1SImro/outputfs/xxxxxxx/backup.tar.gz'
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Using guessed bootloader 'EFI' (found in first bytes on /dev/nvme0n1)
Creating root filesystem layout
Handling network interface 'bondeth0'
bondeth0 is a bond
bondeth0 has lower interface eth12
eth12 is a physical device
bondeth0 has lower interface eth8
eth8 is a physical device
Handled network interface 'bondeth0'
Skipping 'docker0': not bound to any physical interface.
Handling network interface 'eth0'
eth0 is a physical device
Handled network interface 'eth0'
Handling network interface 'ib0'
ib0 is a physical device
Handled network interface 'ib0'
Handling network interface 'ib1'
ib1 is a physical device
Handled network interface 'ib1'
Handling network interface 'ib2'
ib2 is a physical device
Handled network interface 'ib2'
Handling network interface 'ib3'
ib3 is a physical device
Handled network interface 'ib3'
Handling network interface 'ib4'
ib4 is a physical device
Handled network interface 'ib4'
Handling network interface 'ib5'
ib5 is a physical device
Handled network interface 'ib5'
Handling network interface 'ib6'
ib6 is a physical device
Handled network interface 'ib6'
Handling network interface 'ib7'
ib7 is a physical device
Handled network interface 'ib7'
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/redhat/grubx64.efi' as UEFI bootloader file
Copying logfile /var/log/rear/rear-xxxxxxxx.log into initramfs as '/tmp/rear-xxxxxxxx-parti                                                                                      al-2018-10-13T02:56:34+0200.log'
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Copying all files in /lib*/firmware/
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (94086224 bytes) in 13 seconds
ERROR: Could not create '/tmp/rear.GQIYy90Tu1SImro/outputfs/xxxxxxxx/.lockfile'
Aborting due to an error, check /var/log/rear/rear-xxxxxxxx.log for details
Exiting rear mkrescue (PID 232960) and its descendant processes
Running exit tasks
You should also rm -Rf /tmp/rear.GQIYy90Tu1SImro
Terminated

#cat  more /var/log/rear/rear-xxxxxx.log
<snip>

++ echo '2018-10-13 03:06:50.333983549 Saving disk partitions.'
2018-10-13 03:06:50.333983549 Saving disk partitions.
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_spec'
++ [[ asm!.asm_ctl_spec = hd* ]]
++ [[ asm!.asm_ctl_spec = sd* ]]
++ [[ asm!.asm_ctl_spec = cciss* ]]
++ [[ asm!.asm_ctl_spec = vd* ]]
++ [[ asm!.asm_ctl_spec = xvd* ]]
++ [[ asm!.asm_ctl_spec = dasd* ]]
++ [[ asm!.asm_ctl_spec = nvme* ]]
++ [[ asm!.asm_ctl_spec = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg0'
++ [[ asm!.asm_ctl_vbg0 = hd* ]]
++ [[ asm!.asm_ctl_vbg0 = sd* ]]
++ [[ asm!.asm_ctl_vbg0 = cciss* ]]
++ [[ asm!.asm_ctl_vbg0 = vd* ]]
++ [[ asm!.asm_ctl_vbg0 = xvd* ]]
++ [[ asm!.asm_ctl_vbg0 = dasd* ]]
++ [[ asm!.asm_ctl_vbg0 = nvme* ]]
++ [[ asm!.asm_ctl_vbg0 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg1'
++ [[ asm!.asm_ctl_vbg1 = hd* ]]
++ [[ asm!.asm_ctl_vbg1 = sd* ]]
++ [[ asm!.asm_ctl_vbg1 = cciss* ]]
++ [[ asm!.asm_ctl_vbg1 = vd* ]]
++ [[ asm!.asm_ctl_vbg1 = xvd* ]]
++ [[ asm!.asm_ctl_vbg1 = dasd* ]]
++ [[ asm!.asm_ctl_vbg1 = nvme* ]]
++ [[ asm!.asm_ctl_vbg1 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg2'
++ [[ asm!.asm_ctl_vbg2 = hd* ]]
++ [[ asm!.asm_ctl_vbg2 = sd* ]]
++ [[ asm!.asm_ctl_vbg2 = cciss* ]]
++ [[ asm!.asm_ctl_vbg2 = vd* ]]
++ [[ asm!.asm_ctl_vbg2 = xvd* ]]
++ [[ asm!.asm_ctl_vbg2 = dasd* ]]
++ [[ asm!.asm_ctl_vbg2 = nvme* ]]
++ [[ asm!.asm_ctl_vbg2 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg3'
++ [[ asm!.asm_ctl_vbg3 = hd* ]]
++ [[ asm!.asm_ctl_vbg3 = sd* ]]
++ [[ asm!.asm_ctl_vbg3 = cciss* ]]
++ [[ asm!.asm_ctl_vbg3 = vd* ]]
++ [[ asm!.asm_ctl_vbg3 = xvd* ]]
++ [[ asm!.asm_ctl_vbg3 = dasd* ]]
++ [[ asm!.asm_ctl_vbg3 = nvme* ]]
++ [[ asm!.asm_ctl_vbg3 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg4'
++ [[ asm!.asm_ctl_vbg4 = hd* ]]
++ [[ asm!.asm_ctl_vbg4 = sd* ]]
++ [[ asm!.asm_ctl_vbg4 = cciss* ]]
++ [[ asm!.asm_ctl_vbg4 = vd* ]]
++ [[ asm!.asm_ctl_vbg4 = xvd* ]]
++ [[ asm!.asm_ctl_vbg4 = dasd* ]]
++ [[ asm!.asm_ctl_vbg4 = nvme* ]]
++ [[ asm!.asm_ctl_vbg4 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg5'
++ [[ asm!.asm_ctl_vbg5 = hd* ]]
++ [[ asm!.asm_ctl_vbg5 = sd* ]]
++ [[ asm!.asm_ctl_vbg5 = cciss* ]]
++ [[ asm!.asm_ctl_vbg5 = vd* ]]
++ [[ asm!.asm_ctl_vbg5 = xvd* ]]
++ [[ asm!.asm_ctl_vbg5 = dasd* ]]
++ [[ asm!.asm_ctl_vbg5 = nvme* ]]
++ [[ asm!.asm_ctl_vbg5 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg6'
++ [[ asm!.asm_ctl_vbg6 = hd* ]]
++ [[ asm!.asm_ctl_vbg6 = sd* ]]
++ [[ asm!.asm_ctl_vbg6 = cciss* ]]
++ [[ asm!.asm_ctl_vbg6 = vd* ]]
++ [[ asm!.asm_ctl_vbg6 = xvd* ]]
++ [[ asm!.asm_ctl_vbg6 = dasd* ]]
++ [[ asm!.asm_ctl_vbg6 = nvme* ]]
++ [[ asm!.asm_ctl_vbg6 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg7'
++ [[ asm!.asm_ctl_vbg7 = hd* ]]
++ [[ asm!.asm_ctl_vbg7 = sd* ]]
++ [[ asm!.asm_ctl_vbg7 = cciss* ]]
++ [[ asm!.asm_ctl_vbg7 = vd* ]]
++ [[ asm!.asm_ctl_vbg7 = xvd* ]]
++ [[ asm!.asm_ctl_vbg7 = dasd* ]]
++ [[ asm!.asm_ctl_vbg7 = nvme* ]]
++ [[ asm!.asm_ctl_vbg7 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vbg8'
++ [[ asm!.asm_ctl_vbg8 = hd* ]]
++ [[ asm!.asm_ctl_vbg8 = sd* ]]
++ [[ asm!.asm_ctl_vbg8 = cciss* ]]
++ [[ asm!.asm_ctl_vbg8 = vd* ]]
++ [[ asm!.asm_ctl_vbg8 = xvd* ]]
++ [[ asm!.asm_ctl_vbg8 = dasd* ]]
++ [[ asm!.asm_ctl_vbg8 = nvme* ]]
++ [[ asm!.asm_ctl_vbg8 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vdbg'
++ [[ asm!.asm_ctl_vdbg = hd* ]]
++ [[ asm!.asm_ctl_vdbg = sd* ]]
++ [[ asm!.asm_ctl_vdbg = cciss* ]]
++ [[ asm!.asm_ctl_vdbg = vd* ]]
++ [[ asm!.asm_ctl_vdbg = xvd* ]]
++ [[ asm!.asm_ctl_vdbg = dasd* ]]
++ [[ asm!.asm_ctl_vdbg = nvme* ]]
++ [[ asm!.asm_ctl_vdbg = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vio0'
++ [[ asm!.asm_ctl_vio0 = hd* ]]
++ [[ asm!.asm_ctl_vio0 = sd* ]]
++ [[ asm!.asm_ctl_vio0 = cciss* ]]
++ [[ asm!.asm_ctl_vio0 = vd* ]]
++ [[ asm!.asm_ctl_vio0 = xvd* ]]
++ [[ asm!.asm_ctl_vio0 = dasd* ]]
++ [[ asm!.asm_ctl_vio0 = nvme* ]]
++ [[ asm!.asm_ctl_vio0 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vio1'
++ [[ asm!.asm_ctl_vio1 = hd* ]]
++ [[ asm!.asm_ctl_vio1 = sd* ]]
++ [[ asm!.asm_ctl_vio1 = cciss* ]]
++ [[ asm!.asm_ctl_vio1 = vd* ]]
++ [[ asm!.asm_ctl_vio1 = xvd* ]]
++ [[ asm!.asm_ctl_vio1 = dasd* ]]
++ [[ asm!.asm_ctl_vio1 = nvme* ]]
++ [[ asm!.asm_ctl_vio1 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vio10'
++ [[ asm!.asm_ctl_vio10 = hd* ]]
++ [[ asm!.asm_ctl_vio10 = sd* ]]
++ [[ asm!.asm_ctl_vio10 = cciss* ]]
++ [[ asm!.asm_ctl_vio10 = vd* ]]
++ [[ asm!.asm_ctl_vio10 = xvd* ]]
++ [[ asm!.asm_ctl_vio10 = dasd* ]]
++ [[ asm!.asm_ctl_vio10 = nvme* ]]
++ [[ asm!.asm_ctl_vio10 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vio11'
++ [[ asm!.asm_ctl_vio11 = hd* ]]
++ [[ asm!.asm_ctl_vio11 = sd* ]]
++ [[ asm!.asm_ctl_vio11 = cciss* ]]
++ [[ asm!.asm_ctl_vio11 = vd* ]]
++ [[ asm!.asm_ctl_vio11 = xvd* ]]
++ [[ asm!.asm_ctl_vio11 = dasd* ]]
++ [[ asm!.asm_ctl_vio11 = nvme* ]]
++ [[ asm!.asm_ctl_vio11 = mmcblk* ]]
++ for disk in '/sys/block/*'
++ blockd='asm!.asm_ctl_vio12'
++ [[ asm!.asm_ctl_vio12 = hd* ]]
++ [[ asm!.asm_ctl_vio12 = sd* ]]
++ [[ asm!.asm_ctl_vio12 = cciss* ]]
++ [[ asm!.asm_ctl_vio12 = vd* ]]
++ [[ asm!.asm_ctl_vio12 = xvd* ]]
++ [[ asm!.asm_ctl_vio12 = dasd* ]]
++ [[ asm!.asm_ctl_vio12 = nvme* ]]
++ [[ asm!.asm_ctl_vio12 = mmcblk* ]]
++ for disk in '/sys/block/*'
<snip>
:
:
+++ my_dm=
+++ name=nvme0n1
+++ echo /dev/nvme0n1
+++ return 1
++ devname=/dev/nvme0n1
+++ get_disk_size nvme0n1
+++ local disk_name=nvme0n1
++++ get_block_size nvme0n1
++++ '[' -r /sys/block/nvme0n1/queue/logical_block_size ']'
++++ echo 512
+++ local block_size=512
+++ retry_command test -r /sys/block/nvme0n1/size
+++ local retry=0
++++ eval test -r /sys/block/nvme0n1/size
+++++ test -r /sys/block/nvme0n1/size
+++ command_stdout=
+++ echo -n ''
+++ local nr_blocks=6251233968
+++ local disk_size=3200631791616
+++ echo 3200631791616
++ devsize=3200631791616
+++ parted -s /dev/nvme0n1 print
+++ grep -E 'Partition Table|Disk label'
+++ cut -d : -f 2
+++ tr -d ' '
++ disktype=gpt
++ echo '# Disk /dev/nvme0n1'
++ echo '# Format: disk <devname> <size(bytes)> <partition label type>'
++ echo 'disk /dev/nvme0n1 3200631791616 gpt'
++ echo '# Partitions on /dev/nvme0n1'
++ echo '# Format: part <device> <partition size(bytes)> <partition start(bytes)> <partition type|name> <flags> /dev/<partition>'
++ extract_partitions /dev/nvme0n1
++ declare device=/dev/nvme0n1
+++ get_sysfs_name /dev/nvme0n1
+++ local name=nvme0n1
+++ name=nvme0n1
+++ [[ -e /sys/block/nvme0n1 ]]
+++ echo nvme0n1
+++ return 0
++ declare sysfs_name=nvme0n1
++ sysfs_paths=(/sys/block/$sysfs_name/$sysfs_name*)
++ declare -a sysfs_paths
++ declare path sysfs_path
++ [[ 0 -eq 0 ]]
++ [[ /dev/nvme0n1 = *\/\m\a\p\p\e\r\/* ]]
++ :
++ declare partition_name partition_prefix start_block
++ declare partition_nr size start
++ sort -un /tmp/rear.qMlh2TzzmEkXuwE/tmp/partitions_unsorted
++ [[ ! -s /tmp/rear.qMlh2TzzmEkXuwE/tmp/partitions ]]
++ Debug 'No partitions found on /dev/nvme0n1.'
++ test 1
++ Log 'No partitions found on /dev/nvme0n1.'
+++ date '+%Y-%m-%d %H:%M:%S.%N '
++ local 'timestamp=2018-10-13 03:06:50.395104478 '
++ test 1 -gt 0
++ echo '2018-10-13 03:06:50.395104478 No partitions found on /dev/nvme0n1.'
2018-10-13 03:06:50.395104478 No partitions found on /dev/nvme0n1.
++ return
++ for disk in '/sys/block/*'
++ blockd=nvme1n1
++ [[ nvme1n1 = hd* ]]
++ [[ nvme1n1 = sd* ]]
++ [[ nvme1n1 = cciss* ]]
++ [[ nvme1n1 = vd* ]]
++ [[ nvme1n1 = xvd* ]]
++ [[ nvme1n1 = dasd* ]]
++ [[ nvme1n1 = nvme* ]]
++ is_multipath_path nvme1n1
++ '[' nvme1n1 ']'
++ type multipath
++ multipath -c /dev/nvme1n1
++ [[ nvme1n1 = *rpmb ]]
++ [[ nvme1n1 = *[0-9]boot[0-9] ]]
+++ get_device_name /sys/block/nvme1n1
+++ local name=/sys/block/nvme1n1
+++ name=nvme1n1
+++ contains_visible_char nvme1n1
++++ tr -d -c '[:graph:]'
+++ test nvme1n1
+++ local device dev_number mapper_number
:
<snip>
:
+++ [[ nvme3n1 =~ ^mapper/ ]]
++++ readlink /dev/nvme3n1
+++ my_dm=
+++ name=nvme3n1
+++ echo /dev/nvme3n1
+++ return 1
++ disk=/dev/nvme3n1
++ '[' -z ' devices=/dev/nvme1n1' ']'
++ devices=' devices=/dev/nvme1n1,/dev/nvme3n1'
++ metadata=' metadata=imsm'
++ level=' level=container'
++ ndevices=' raid-devices='
++ uuid=' uuid=cc2508c6:4d5fc61e:d2a74d19:b5fd0147'
++ '[' '' -gt 0 ']'
/usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh: line 65: [: : integer expression expected
++ sparedevices=
++ '[' -n '' ']'
++ layout=
++ '[' -n '' ']'
++ chunksize=
++ [[ -n imsm0 ]]
++ name=' name=imsm0'
++ echo 'raid /dev/md127 metadata=imsm level=container raid-devices= uuid=cc2508c6:4d5fc61e:d2a74d19:b5fd0147 name=imsm0 devices=/dev/nvme1n1,/dev/nvme3n1'
++ extract_partitions /dev/md127
++ declare device=/dev/md127
+++ get_sysfs_name /dev/md127
+++ local name=md127
+++ name=md127
+++ [[ -e /sys/block/md127 ]]
+++ echo md127
+++ return 0
++ declare sysfs_name=md127
++ sysfs_paths=(/sys/block/$sysfs_name/$sysfs_name*)
++ declare -a sysfs_paths
++ declare path sysfs_path
++ [[ 0 -eq 0 ]]
++ [[ /dev/md127 = *\/\m\a\p\p\e\r\/* ]]
++ :
++ declare partition_name partition_prefix start_block
++ declare partition_nr size start
++ sort -un /tmp/rear.qMlh2TzzmEkXuwE/tmp/partitions_unsorted
++ [[ ! -s /tmp/rear.qMlh2TzzmEkXuwE/tmp/partitions ]]
++ Debug 'No partitions found on /dev/md127.'
++ test 1
++ Log 'No partitions found on /dev/md127.'
+++ date '+%Y-%m-%d %H:%M:%S.%N '
++ local 'timestamp=2018-10-13 03:06:50.748121940 '
++ test 1 -gt 0
++ echo '2018-10-13 03:06:50.748121940 No partitions found on /dev/md127.'
2018-10-13 03:06:50.748121940 No partitions found on /dev/md127.

lsblk:
=====

NAME                                    MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1                                 259:0    0   2.9T  0 disk
├─md24                                    9:24   0   250G  0 raid1
│ ├─md24p1                              259:6    0   512M  0 md    /boot
│ ├─md24p2                              259:7    0   256M  0 md    /boot/efi
│ └─md24p3                              259:8    0 249.3G  0 md
│   ├─VGExaDb-LVDbSys1 (dm-0)           249:0    0    30G  0 lvm   /
│   ├─VGExaDb-LVDbSys2 (dm-1)           249:1    0    30G  0 lvm
│   ├─VGExaDb-LVDbSwap1 (dm-2)          249:2    0    24G  0 lvm   [SWAP]
│   ├─VGExaDb-LVDoNotRemoveOrUse (dm-3) 249:3    0     1G  0 lvm
│   ├─VGExaDb-LVDbOra1 (dm-4)           249:4    0   100G  0 lvm
│   ├─VGExaDb-dbtoolslv (dm-9)          249:9    0     2G  0 lvm   /opt/dbtools
│   ├─VGExaDb-oracle (dm-10)            249:10   0    10G  0 lvm   /data
│  
└─md25                                    9:25   0   2.7T  0 raid1
  └─md25p1                              259:5    0   2.7T  0 md
    ├─VGExaDb-oracle_product (dm-5)     249:5    0   100G  0 lvm   /data/oracle
    ├─VGExaDb-oragrid_product (dm-6)    249:6    0   150G  0 lvm   /data/oragrid
    ├─VGExaDb-oragrid_diag (dm-7)       249:7    0   100G  0 lvm   /data/oragrid/product/admin
    ├─VGExaDb-oragrid_admin (dm-8)      249:8    0   100G  0 lvm   /data/oragrid/ASM
   
nvme1n1                                 259:1    0   2.9T  0 disk
└─md34                                    9:34   0   2.9T  0 raid1
  └─md34p1                              259:4    0   2.9T  0 md
nvme2n1                                 259:3    0   2.9T  0 disk
├─md24                                    9:24   0   250G  0 raid1
│ ├─md24p1                              259:6    0   512M  0 md    /boot
│ ├─md24p2                              259:7    0   256M  0 md    /boot/efi
│ └─md24p3                              259:8    0 249.3G  0 md
│   ├─VGExaDb-LVDbSys1 (dm-0)           249:0    0    30G  0 lvm   /
│   ├─VGExaDb-LVDbSys2 (dm-1)           249:1    0    30G  0 lvm
│   ├─VGExaDb-LVDbSwap1 (dm-2)          249:2    0    24G  0 lvm   [SWAP]
│   ├─VGExaDb-LVDoNotRemoveOrUse (dm-3) 249:3    0     1G  0 lvm
│   ├─VGExaDb-LVDbOra1 (dm-4)           249:4    0   100G  0 lvm
│   ├─VGExaDb-dbtoolslv (dm-9)          249:9    0     2G  0 lvm   /opt/dbtools
│   ├─VGExaDb-oracle (dm-10)            249:10   0    10G  0 lvm   /data
│   └
└─md25                                    9:25   0   2.7T  0 raid1
  └─md25p1                              259:5    0   2.7T  0 md
    ├─VGExaDb-oracle_product (dm-5)     249:5    0   100G  0 lvm   /data/oracle
    ├─VGExaDb-oragrid_product (dm-6)    249:6    0   150G  0 lvm   /data/oragrid
    ├─VGExaDb-oragrid_diag (dm-7)       249:7    0   100G  0 lvm   /data/oragrid/product/admin
    ├─VGExaDb-oragrid_admin (dm-8)      249:8    0   100G  0 lvm   /data/oragrid/ASM
  
nvme3n1                                 259:2    0   2.9T  0 disk
└─md34                                    9:34   0   2.9T  0 raid1
  └─md34p1                              259:4    0   2.9T  0 md
#

**Comment by gdha** [comment]
@perlvan could you also paste the output of `/var/lib/rear/layout/disklayout.conf` please?

**Comment by gdha** [comment]
@perlvan Perhaps worth looking at https://github.com/rear/rear/issues/721 too?

**Comment by gdha** [comment]
@perlvan sorry we will close this issue without further input in the coming weeks

**Comment by perlvan** [comment]
Yes please. Thank you.
