### ISSUE TITLE
Extend PXE_TFTP_PATH and PXE_CONFIG_PATH to support url

### ISSUE THREAD

**Issue by pavoldomin** [rear/rear#193]
Enhancement request:
Would be great if PXE_TFTP_PATH and PXE_CONFIG_PATH support URL syntax, similar to OUTPUT_URL, such that PXE kernel, initrd, message, menu and links can be uploaded directly to remote server.

See also #192

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature

**Comment by gdha** [comment]
I am currently addressing this topic

**Comment by gdha** [comment]
@pavoldomin perhaps an interesting feature you would like to test?

**Comment by gdha** [comment]
It works for me, closing this one. If problems arise I'm pretty sure a new issue will be opened.
