### ISSUE TITLE
UUID not updating after restore

### ISSUE THREAD

**Issue by MogiePete** [rear/rear#1938]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version: Relax-and-Recover 2.4-git.3115.507837a.unknown / 2018-10-16
* OS version: CentOS Linux release 7.5.1804 (Core) 
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
BACKUP=TSM
* Hardware: BareMetal
* System architecture: x86
* Firmware: BIOS
* Storage: Local Disks

* Description of the issue: The UUID is not being updated properly after performing a restore.

* Work-around, if any: Manually editting /etc/fstab prior to system reboot

We have two servers that are identical in their configuration which we were using to test DR. One is running Relax-and-Recover 2.4 / 2018-06-21 which comes with CentOS 7.5 and the other is the version provided above.

When we perform the install on the 2.4-git.3115.507837a version the UUID is not being updated properly and system will not boot. To resolve the issue I had to manually update the UUID in /etc/fstab post restore.

[rear-osn02.log](https://github.com/rear/rear/files/2503007/rear-osn02.log)
[rear-2018-10-17T14%3A47%3A25-0400.log](https://github.com/rear/rear/files/2503008/rear-2018-10-17T14.3A47.3A25-0400.log)
![not_working_2 4_pr1934](https://user-images.githubusercontent.com/2382464/47313400-dd90b500-d60c-11e8-8c5a-6dbb18086c9d.png)
![working_2 4](https://user-images.githubusercontent.com/2382464/47313405-dff30f00-d60c-11e8-908b-513fb243d90f.png)

**Comment by jsmeix** [comment]
Cf. https://github.com/rear/rear/issues/1926#issuecomment-430533773

**Comment by jsmeix** [comment]
@MogiePete 
both your rear-osn02.log and rear-2018-10-17T14%3A47%3A25-0400.log
do not contain debugging information (i.e. via `rear -D recover`)
so that I cannot see how they actually differ.

Can you provide logs with full debugging information?

Additionally I need each of the two disklayout.conf files
of the two servers.

**Comment by jsmeix** [comment]
Without debugging information (i.e. a `rear -D recover` log file)
there is nothing I can do.
