### ISSUE TITLE
Typo in /usr/share/rear/wrapup/default/500_post_recovery_script.sh

### ISSUE THREAD

**Issue by adm-fkt-physik** [rear/rear#1944]
Relax-and-Recover 2.4 / 2018-06-21

Typo in LINE 2 of `/usr/share/rear/wrapup/default/500_post_recovery_script.sh`

Replace
`POST_REVOVERY_SCRIPT`
by
`POST_RECOVERY_SCRIPT`
in the Log-Line.

**Comment by jsmeix** [comment]
@adm-fkt-physik 
thanky you for the report.

I fixed it via
https://github.com/rear/rear/commit/088083aa8201221e2989e27830e6974317291de7
