### ISSUE TITLE
Does rear support Oracle Enterprise Linux(OEL) ?

### ISSUE THREAD

**Issue by samurdhi** [rear/rear#1955]
Please let me know, 
Does rear support Oracle Enterprise Linux(OEL) with unbreakable Linux kernel?

**Comment by schlomo** [comment]
Probably yes. Did you try it?

**Comment by gdha** [comment]
@samurdhi in short yes it works the same as with RHEL (or CentOS)

**Comment by samurdhi** [comment]
Thanks @gdha  @schlomo 

I did not test it with OEL yet but I'm going to test it very soon Because we are hoping to update OS of all Oracle Linux servers soon.
