### ISSUE TITLE
NBU (Netbackup) not working since ReaR 2.4

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1974]
* ReaR version ("/usr/sbin/rear -V"): **2.4**

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): **RHEL7**

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

~~~
BACKUP=NBU
~~~

* Description of the issue (ideally so that others can reproduce it):

The Netbackup tools are copied as is into the rescue ISO. They are located in `/usr/openv`.

It appears that the new `usr/share/rear/build/default/980_verify_rootfs.sh` detects libraries dependencies and complains because some binaries and libraries included when including all of `/usr/openv` do not satisfy the dependencies.
This leads to an error while creating the rescue ISO.

Also, before that, `/usr/share/rear/build/GNU/Linux/100_copy_as_is.sh` finds out libraries but skips them because they are copied in multiple places (I will log an issue later about that).

Quick question: Do we have someone with access to NetBackup?

**Comment by gdha** [comment]
@rmetrich #1907 is a similar issue like yours. One of my customers is using NBU for backup, but not together with ReaR (they use `BACKUP=NETFS`). Unfortunately my time is limited I can spend on ReaR when I work for them (for obvious reasons as ReaR is working smoothly on their site).

**Comment by rmetrich** [comment]
@gdha I'm working on that currently. Was asking because I don't have access to NetBackup at all, so it's less efficient.

**Comment by jsmeix** [comment]
@rmetrich 
see in particular my comment
https://github.com/rear/rear/issues/1907#issuecomment-422338473

Because neither you nor I have access to NetBackup
there is nothing we can do to properly fix issues with
third-party backup tools.

As band-aid workaround for such issues I implemented
`NON_FATAL_BINARIES_WITH_MISSING_LIBRARY`
see default.conf.

**Comment by rmetrich** [comment]
Well I'll try having something better anyway.

**Comment by rmetrich** [comment]
I provided a patch to a customer, if this is a success, I'll submit it here.

**Comment by rmetrich** [comment]
@jsmeix no no, these are not yet in RHEL's repo, it's just in dev phase :-)

**Comment by jsmeix** [comment]
@rmetrich 
ah!
Even better to keep ReaR upstream topmost up-to-date :-)
