### ISSUE TITLE
Recreating LVM not working with ReaR 2.4 on RHEL 7.6

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#2009]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Red Hat Enterprise Linux Server release 7.6 (Maipo)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
export TMPDIR="/mnt/rear/"
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=sshfs://root@xxx.xxx.xxx.xxx/dbar/
BACKUP_URL=sshfs://root@xxx.xxx.xxx.xxx/dbar/
KEEP_OLD_OUTPUT_COPY=1
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/var/cache/yum')
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Cisco C240

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS - GRUB

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
Local

* Description of the issue (ideally so that others can reproduce it):
Hello,
Upgrading to Red Hat 7.6 updated ReaR from rear-2.00-7.el7_5.x86_64 to  rear-2.4-2.el7.x86_64.  
Running a backup worked with no issues, OS recoveries failed: 

Here are the messages from the ReaR recovery console:
```
ERROR:
====================
BUG in /usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh line 226:
'Unsupported LV layout '16777216' found for LV 'tmp''
--------------------
Please report this issue at https://github.com/rear/rear/issues
```

* Workaround, if any:

Restored server using a backup from ->
[rear-xzeenderm1d.log](https://github.com/rear/rear/files/2700001/rear-xzeenderm1d.log)
 Relax-and-Recover 2.00 / Git

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by John-Leone** [comment]
[disklayout.conf-.txt](https://github.com/rear/rear/files/2703936/disklayout.conf-.txt)
[rear-xzeenderm1d.log](https://github.com/rear/rear/files/2703937/rear-xzeenderm1d.log)

@rmetrich 
Hello,
I have uploaded the files you requested.

**Comment by rmetrich** [comment]
Hi @John-Leone , since you are a Red Hat customer, we should work on this in the Red Hat ticket you opened recently.

**Comment by gdha** [comment]
@rmetrich @John-Leone any update you are willing to share?

**Comment by rmetrich** [comment]
@gdha Issue resolved. We believe rear was running while the package got updated, causing updated scripts to be packed into ISO with content (disklayout.conf) computed from older scripts.

**Comment by gdha** [comment]
Thank you for the prompt reply -we can close this issue then
