### ISSUE TITLE
How to backup the large than 4GB system with archive files.

### ISSUE THREAD

**Issue by crazy90cc** [rear/rear#2012]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 1.17.2 / Git
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=cifs://CIFSSERVER/SHARED_PATH
BACKUP=NETFS
BACKUP_URL=iso://CIFSSERVER/SHARED_PATH
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC X86 server.
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
X86
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Description of the issue (ideally so that others can reproduce it):
From ReaR log:
Scanning ./Backup
File ./Backup/backup.tar.gz is larger than 4GiB-1.
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.

I'd like to know how to specify the parameter -allow-limited-size in ReaR configuration.
* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by crazy90cc** [comment]
Sorry, I would like to backup all files into 1 single ISO. So if that possible to make that iso file large than 4GB?

**Comment by gdha** [comment]
@crazy90cc Please start using rear-2.0 on RHEL 6 as 1.17.2 is too old. Version 2.0 is also supported by RH. And, yes it should be possible to make a single ISO image bigger than 4GB.

**Comment by crazy90cc** [comment]
Hi dgha,

Finnally i have make the 1 single iso. But i realized that rear will make the iso into directory /var/lib/rear/output, and after that will copy to the OUTPUT_URL location. How to make that clean the directory /var/lib/rear/output itselt? Or just directly copy the iso file to OUTPUT_URL?

**Comment by gdha** [comment]
@crazy90cc See also issue #734 and try to make `OUTPUT_URL=null` and I never defined the `BACKUP_URL=iso://cifs/path` -> did it work? I always used a path on a local path on the system with enough disk space.

**Comment by gdha** [comment]
@crazy90cc is your question sufficient answered?

**Comment by gdha** [comment]
no reply means everything is cool I guess?
