### ISSUE TITLE
Unable to restore to SLES12 SP4 on Power using Rear

### ISSUE THREAD

**Issue by suseusr168** [rear/rear#2042]
Is SLES12 SP4 supported for Rear?

This is our only SLES12 SP4 LPAR so we don't have all the information to gather.

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4-git.0.6ec9075.unknown / 2018-12-05

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):SLES12 SP4

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): PowerVM LPAR

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): PPC64LE

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): GRUB

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SAN XIV

* Description of the issue (ideally so that others can reproduce it):
We are unable to restore using Rear on SLES12 SP4 on Power.

Is SLES12 SP4 supported for Rear?

This is our only SLES12 SP4 LPAR so we don't have all the information to gather.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[Rear Restore SLES 12 SP4.txt](https://github.com/rear/rear/files/2865735/Rear.Restore.SLES.12.SP4.txt)

**Comment by jsmeix** [comment]
@suseusr168 
see "Supported Operating Systems" at
http://relax-and-recover.org/documentation/release-notes-2-4
and "rear / rear116 / rear1172a / rear118a / rear23a" at
https://en.opensuse.org/SDB:Disaster_Recovery

Your https://github.com/rear/rear/files/2865735/Rear.Restore.SLES.12.SP4.txt
contains (excerpts):
```
Configuring Relax-and-Recover rescue system
...
Running 55-migrate-network-devices.sh...
Cannot migrate network interface setup because there is no usable MAC address on this system
Running 58-start-dhclient.sh...
Running 60-network-devices.sh...
Cannot find device "eth0"
...
Cannot find device "eth1"
Running 62-routing.sh...
Cannot find device "eth0"
Cannot find device "eth1"

...

Running workflow recover within the ReaR rescue/recovery system
A symlink '/dev/disk/by-label/RELAXRECOVER' is required that points to the device with the ReaR ISO image
Create symlink '/dev/disk/by-label/RELAXRECOVER' that points to the ReaR ISO image device
1) /dev/cdrom is where the ISO is attached to
2) /dev/sr0 is where the ISO is attached to
3) /dev/sr1 is where the ISO is attached to
4) Use Relax-and-Recover shell and return back to here
5) Continue 'rear recover'
6) Abort 'rear recover'
```

See in usr/share/rear/lib/global-functions.sh
the mount_url() function therein the (iso) case, e.g. online at
https://github.com/rear/rear/blob/master/usr/share/rear/lib/global-functions.sh#L376
that explains the reason behind and URLs to other issues like
https://github.com/rear/rear/issues/1891
that was from you and seems to be the same one as this issue here,
in particular there also networking issues were mentioned.

Perhaps without networking the mount_url() function cannot work
in your case but I don't know where the ISO is attached to in your case.

**Comment by jsmeix** [comment]
Only a blind shot in the dark
(@suseusr168 why did you not provide your ReaR configuration file?)
cf.
https://github.com/rear/rear/pull/1894#issuecomment-411766357
```
I need MODULES=( 'all_modules' ) because without it
I get on my SLES12 x86_64 KVM system
...
  mount: unknown filesystem type 'iso9660'
...
where mount: unknown filesystem type 'iso9660'
is exactly my example for https://github.com/rear/rear/issues/1202
see also https://github.com/rear/rear/issues/1891#issuecomment-410757405
```

Regarding `MODULES=( 'all_modules' )` see also
https://github.com/rear/rear/issues/2041

**Comment by suseusr168** [comment]
The reason why the /etc/rear/local.conf wasn't included was that we couldn't restore the ISO backup and the system cannot get booted up.

 In hindsight, we could have gotten the local.conf if  we access the Rescue shell.  We were in panic mode.

The question we have is:
Is Rear supported for SLES12 SP4 on Power?


We would need to do more testing on a system that was migrated from SLES12 SP3 to SLES12 SP4 to see if we can restore at SLES12 SP4 level .


Here is the background of the problem:
1. System built from base SLES12 SP4 DVD ISO
    Cannot restore using Rear and and and the workaround in #2019 didn't work.

 ##    rear> udevadm control --reload-rules
##    rear> udevadm trigger
##    rear> multipath -r
##     create: 200173800348802b2 undef IBM,2810XIV
##     size=112G features='1 queue_if_no_path' hwhandler='0' wp=undef
##     `-+- policy='service-time 0' prio=50 status=undef
##       |- 2:0:0:1 sda 8:0  undef ready running
##       |- 2:0:1:1 sdb 8:16 undef ready running
##       |- 3:0:0:1 sdc 8:32 undef ready running
##       `- 3:0:1:1 sdd 8:48 undef ready running
##   NOTE:  If no ouput from multipath -r re-run the 2 udevadm commands
##          Also, there might not always be 4 paths


2. Restore SLES12 SP3 Rear backup and migrated to SLES12 SP4  to get the system up since the Rear backup of SLES12 SP4 didn't work.  We need to test if this restore from a SLES12 SP4 migrated system  will work.

Here are the info gathered from the system that was migrated from SLES12 SP3 to SLES12 SP4:
The /etc/rear/local.conf was the same file we used on a base SLES12 SP4 system and a migrated SLES12 SP4 system:
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

    * ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4-git.0.e9f9d4b.unknown / 2018-12-20

    * OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):SLES12 SP4
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles_sap:12:sp4"


    * ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y
REAR_INITRD_COMPRESSION=lzma
OUTPUT=ISO
ISO_MAX_SIZE=4000
BACKUP=NETFS
BACKUP_URL=iso:///iso_fs/REAR_BACKUP
ISO_DIR=/iso_fs/REAR_ISO
TMPDIR=/iso_fs/REAR_TEMP
OUTPUT_URL=null
BOOT_FROM_SAN=y
EXCLUDE_MOUNTPOINTS=( /iso_fs /opt/IBM/ITM /cv /opt/splunkforwarder /opt/teamquest /var/opt/BESClient /usr/sap /hana/data /hana/log /hana/shared /usr/sap/basis /usr/sap/srm /PA_backup )
EXCLUDE_COMPONENTS=( /dev/mapper/20017380034880218 /dev/mapper/20017380034880219 /dev/mapper/2001738003488021a /dev/mapper/2001738003488021b /dev/mapper/2001738003488021c /dev/mapper/2001738003488021d /dev/mapper/2001738003488021e /dev/mapper/2001738003488021f /dev/mapper/20017380034880220 /dev/mapper/20017380034880221 /dev/mapper/20017380034880222 /dev/mapper/20017380034880223 /dev/mapper/200173800348802ac /dev/mapper/200173800348802ad /dev/mapper/200173800348802ae /dev/mapper/200173800348802af )


    * Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): PowerVM LPAR

    * System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): PPC64LE

    * Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): GRUB

    * Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SAN XIV

    * Description of the issue (ideally so that others can reproduce it):
      We are unable to restore using Rear on SLES12 SP4 on Power.

**Comment by suseusr168** [comment]
Updates made to ticket 2019. C.losing this ticket.

**Comment by jsmeix** [comment]
This issue here is continued in https://github.com/rear/rear/issues/2019
therein starting at
https://github.com/rear/rear/issues/2019#issuecomment-465122332
