### ISSUE TITLE
90-eno-fix.rules missing in RULE_FILES for LAN interface MAC address changes

### ISSUE THREAD

**Issue by gdha** [rear/rear#2046]
* ReaR version ("/usr/sbin/rear -V"): rear-2.00-6.el7.x86_64

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): RHEL 7.5

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): `BACKUP=NETFS`

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): VMware clients x86_64

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): BIOS

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local

* Description of the issue (ideally so that others can reproduce it):
the customer has the issue as described in https://www.redhat.com/en/blog/red-hat-enterprise-linux-73-achieving-persistent-and-consistent-network-interface-naming-vmware-environments, or in https://access.redhat.com/solutions/2592561

When a new VM is provisioned it has the **ens**-style LAN interface names instead of the older **eno**-type LAN names. The test was done on a clone VM so that the **ens**-style has active and the ReaR image could not active the LAN interfaces at boot time.

* Workaround, if any: 
manual edit the  `/etc/scripts/system-setup.d/60-network-devices.sh` (and `62-routing.sh`) scripts and modify the LAN interface names. 
Or, modify line:
````
RULE_FILES=( /etc/udev/rules.d/*persistent*{names,net}.rules /etc/udev/rules.d/*eno-fix.rules )
````
in ReaR script `/usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh` before doing the recovery exercise.

I will prepare a PR for the skel and finalize pieces in ReaR

**Comment by gdha** [comment]
@rmetrich Have you seen reports within RH from customers about this behaviour? With this little fix ReaR can deal with it - perhaps something to add to the RH rear RPM?

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2049 merged
this issue should be fixed.
