### ISSUE TITLE
Recovery enters Migration mode when multiple disks have same size

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#2050]
* ReaR version ("/usr/sbin/rear -V"): Latest 2.4

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): All

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): All

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): All

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): All

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

Multipath or standard disks

* Description of the issue (ideally so that others can reproduce it):

When 2 disks have same size, the `rear recover` command forces the user into migration mode and displays the following messages:

~~~
Ambiguous disk layout needs manual configuration (more than one disk with same size used in '/var/lib/rear/layout/disklayout.conf')
Switching to manual disk layout configuration
Using /dev/sda (same name and same size) for recreating /dev/sda
Using /dev/sdb (same name and same size) for recreating /dev/sdb
Current disk mapping table (source => target):
  /dev/sda => /dev/sda
  /dev/sdb => /dev/sdb

UserInput -I LAYOUT_MIGRATION_CONFIRM_MAPPINGS needed in /usr/share/rear/layout/prepare/default/300_map_disks.sh line 275
Confirm or edit the disk mapping
1) Confirm disk mapping and continue 'rear recover'
2) Confirm identical disk mapping and proceed without manual configuration
3) Edit disk mapping (/var/lib/rear/layout/disk_mappings)
4) Use Relax-and-Recover shell and return back to here
5) Abort 'rear recover'
(default '1' timeout 300 seconds)
~~~

When the disks are well-known (through their Disk ID for example), then migration mode should be avoided (we know the exact mapping since it was saved into `/var/lib/rear/recovery/diskbyid_mappings`)

This is linked to #1857 

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[rear-vm-rear76.log](https://github.com/rear/rear/files/2885330/rear-vm-rear76.log)

**Comment by jsmeix** [comment]
@rmetrich 
this is a known (and currently intended) minor annoyance
to be 100% on the safe side aggainst possibly reinstalling
on a wrong disk, cf. the description about MIGRATION_MODE
in default.conf.

I look forward to a pull request from you that reliably
autodetects when the disks are really well-known
so that we can avoid that current annoyance
without any risk to reinstall on a wrong disk.

**Comment by rmetrich** [comment]
Sure, will work on this, but not immediately since I'm having some PTOs

**Comment by jsmeix** [comment]
Thank you very much in advance!
Take your time (I set its milestone to "ReaR future").

**Comment by jsmeix** [comment]
@rmetrich 
see https://github.com/rear/rear/issues/1057#issuecomment-258832970

**Comment by jsmeix** [comment]
@rmetrich 
see also https://github.com/rear/rear/issues/1063
