### ISSUE TITLE
NETFS backup fails if NETFS_PREFIX contains spaces

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#2077]
* ReaR version ("/usr/sbin/rear -V"): **master**

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): ALL

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

~~~
BACKUP=NETFS
NETFS_PREFIX="$HOSTNAME-$(date)"
BACKUP_URL=...
~~~

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): N/A

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): N/A

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): N/A

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): N/A

* Description of the issue (ideally so that others can reproduce it):

If NETFS_PREFIX is specified and contains some spaces, the backup will fail:

~~~
ERROR: dd failed with return code 1 and below output:
  ---snip---
  dd: unrecognized operand 'Mar'
  ----------
~~~

This is due to broken variable expansion.

**Comment by jsmeix** [comment]
This issue is basically just another instance of
https://github.com/rear/rear/issues/1372
