### ISSUE TITLE
Rear restore under Debian 9 with systemV

### ISSUE THREAD

**Issue by ralzibl** [rear/rear#2138]
Hi!

I can't use Rear with systemV configuration :(

It's possible to use any script compatible with sistemV?

Thanks ;)

**Comment by jsmeix** [comment]
@ralzibl 
see
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md

You get that automatically when you use the [New issue] button on
https://github.com/rear/rear/issues

**Comment by ralzibl** [comment]
Sorry...

I have solved this problem using Devuan instead of Debian 9.
