### ISSUE TITLE
openSUSE 12.3 genisoimage -efi-boot option missing

### ISSUE THREAD

**Issue by gdha** [rear/rear#214]
Cannot create a bootable UEFI ISO image on openSUSE 12.3 (and previous versions I guess) due to the fact that the -efi-boot option is missing in genisoimage executable.
Logged a bugzilla request at openSUSE:

https://bugzilla.novell.com/show_bug.cgi?id=811636

**Comment by gdha** [comment]
Need to add it in the release notes that OpenSuse ISO UEFI booting is not (yet) supported.

**Comment by gdha** [comment]
moved the milestone to *rear future* as we hope that OpenSuSe fixes this finally in version ??

**Comment by gdha** [comment]
See also issue #583

**Comment by gdha** [comment]
@pavoldomin To come back to your test with a self-compiled mkisofs (EFI compliant) which did not work. This was not the fault of the mkisofs executable, but it was due to script /usr/share/rear/output/ISO/Linux-i386/25_populate_efibootimg.sh which relies on *grub2-efi* package and SLES is using *elilo*. Perhaps, being positive if mkisofs becomes EFI compliant on SuSe then we better split the populate script up in two (grub-efi and elilo).

**Comment by gdha** [comment]
@pavoldomin Just inspected the openSUSE-13.2-DVD-x86_64.iso EFI content - it seems SuSe is using `prefix=($root)/boot/x86_64/grub2-efi` to boot an ISO image. `elilo` is just used to boot the HD.
ok, then the `grub2-efi` package becomes mandatory on SuSe architecture as well. Good to know. Suddenly, it becomes clear and easier to fix. A patched `mkisofs` would be nice if SuSe could deliver this a standard package instead of `genisoimage` (or give us the option to install this). It seems to be available in Opensuse-Factory 13.2

**Comment by pavoldomin** [comment]
Indeed, so with the recent **ReaR** and *mkisofs* from J. Schilling we should be able to recover UEFI booting (and btrfs-based) SLES12 systems. We will definitely test this in some not so distant future. Our current approach is temporary  legacy bios boot of the recovery image, or - when possible - just disable UEFI completely

**Comment by kostgr** [comment]
I've tried to make UEFI ISO on openSuse 13.2 with the rear from the Archiving repository (http://download.opensuse.org/repositories/Archiving/openSUSE_13.2/ - reported version of rear is 1.17.1???) with the patch as stated by @pavoldomin on output/ISO/Linux-i386/82_create_iso_image.sh file. 

I could create an ISO, but it can't be booted from (grub rescue console appears and I couldn't do anything with it - unknown filesystem on (cd0) => insmod iso9660 doesn't work as the most of the grub2 commands).

**Comment by gdha** [comment]
@kostgr If you have a support contract with SLES - why don't you request a solution? It takes much too long and they do not listen to me...

**Comment by kostgr** [comment]
@gdha Unfortunately I have no support contact with SLES - only login for openSuse. And the issue seems to be related to the grub installation on the disk image. I'm not so experienced with grub to check, whether it is the grub installatoin or iso image issue.

**Comment by gdha** [comment]
@kostgr  @pavoldomin @omeier @dagwieers @schlomo A possible solution is given at http://www.it3.be/2015/10/27/uefi-iso-boot-with-ebiso/
