### ISSUE TITLE
Use "medium" (instead of "media") for a single data carrier or use "ReaR rescue/recovery system"

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#2140]
We use currently at many places in the documentation the word `media`
when we usually mean only a single piece of data carrier
e.g. one ISO image that is burned onto one DVD.

E.g. `rear help` shows (excerpts)
```
 mkbackup        create rescue media and backup system
 mkbackuponly    backup system without creating rescue media
 mkrescue        create rescue media only
```

I wonder if we should use the word `medium` consistently
when we usually mean only a single piece of data carrier like
```
 mkbackup        create rescue medium and backup system
 mkbackuponly    backup system without creating rescue medium
 mkrescue        create rescue medium only
```

According to what I read for the English word `medium` at
https://dict.leo.org/german-english/medium?side=left
```
medium  - pl.: mediums, media  [TECH.]
```
it means in German
```
das Medium pl.: die Medien/die Media
```

But for French (I do not speak French) what I see at
https://www.linguee.com/english-french/search?source=auto&query=media
there also the English `media` seems to mean more than one data carrier
but for the English `medium` the results at
https://www.linguee.com/english-french/search?source=auto&query=medium
seem to not show something that means "a single data carrier"
but I do not speak French so I do not really understand it.

I also wonder if the word `media` or `medium` is actually correct
because I think ReaR cannot create the actual data carrier but
instead ReaR creates some kind of image of an actual data carrier.
At least that is true for `OUTPUT=ISO` while for `OUTPUT=USB`
I think ReaR creates the actual data carrier (i.e. the ready-to-use
USB stick with the bootable ReaR recovery system on it).

Therefore I wonder if the term `rescue media` or `rescue medium`
should be used at all because the word `media` or `medium` is
actually misleading.

Perhaps a more generic term like `rescue system`
or a bit more specific term like `ReaR rescue system`
or what I personally prefer `ReaR recovery system`
should be used?

Reasoning why I prefer
`[ReaR] recovery system` over `[ReaR] rescue system`:

From my point of view the meaning of `rescue system` is
a static bootable generic minimal system that can be used
to do generic and basic things to "revive" an existing system.

But a normal `rescue system` is usually insufficient to fully recreate
a system from scratch on bare metal.

Perhaps by luck all nedeed tools are included in the `rescue system`
to recreate the storage layout and perhaps by even more luck a tool
is included to restore the backup provided by even more more luck
one can access the backup that might be located on whatever
server in whatever complicated (enterprise) network environment
(virtual LAN, teaming, WTF... ;-)

In contrast the most important value of ReaR is that its
`ReaR recovery system` is exactly there to fully recreate
a system from scratch on bare metal because intentionally the
`ReaR recovery system` is not just a static generic `rescue system`
but a specifically made bootable minimal system to fully recreate
a particular system in its particular network environment with
its particular backup/restore software from scratch on bare metal.

Simply put:
A `ReaR recovery system` is so much more than a usual `rescue system`
that it deserves a specific proper name
```
ReaR recovery system
```
where its name matches ReaR's ultimate purpose `rear recover`.

As a backward compatible compromise I use often initially `ReaR rescue/recovery system`
(and in subsequent text parts I use `ReaR recovery system` or only `recovery system`)
so users who are used to use `rescue system` for the `ReaR recovery system`
will not get confused that `ReaR recovery system` may mean something new and different
and new users get a hint that the `ReaR recovery system` is a special kind of `rescue system`.
It also explains why the command is `rear mkrescue` to make the `ReaR rescue/recovery system`
(if that command was named e.g. `rear mkrecovery` its name would conflict with `rear recover`).

**Comment by sknorr** [comment]
Johannes asked on the #susedoc RC channel, so:

* "media" can be either a regular plural or a singular mass noun. However, this appears to very much depend on what is meant by the word "media."

* In the SUSE doc team, we use the Merriam-Webster dictionary as our reference. The relevant parts of the definitions for medium and media are:

> _medium_ [...]
>  * 2 : a means of effecting or conveying something: such as
>    [...]
>    * b. (plural usually _media_)
>        * (1) : a channel or system of communication, information, or entertainment — compare _mass medium_
>          [...]
>        * (4) : something (such as a magnetic disk) on which information may be stored


> _media_  (Entry 1 of 4) [...]
> * 2 : a medium of cultivation, conveyance, or expression _Air is a media that conveys sound._
>   especially : [medium sense 2b]

While the back reference to _medium_-2b at the end of the definition for media makes the situation a bit mushier, I think the general and more accepted advice is to use "medium" (sing.), "media" (pl.) in this case.

(To be honest, I think the back reference in the definition for _media_ is a mistake and should actually go to _medium_-2a which has a very similar example sentence.)

**Comment by jsmeix** [comment]
@sknorr 
thank you so much for your explanatory and helpful contribution to ReaR!

Don't worry - I have the power to reopen issues and even to fix things in ReaR ;-)
