### ISSUE TITLE
should skel/Fedora/ 16 & 17 be removed?

### ISSUE THREAD

**Issue by mutable-dan** [rear/rear#2146]
Just started looking at the skel dir and figuring out what it does.

I noticed that under skel/Fedora it has a 16 & 17 dir
or OS_MASTER_VENDOR_VERSION
for rhel,cent,fedora & scientific OS_MASTER_VENDOR is set to Fedora.
the 16 and 17 probably refer to fedora 16 & 17 which are out of support

right now rhel and centos are at ver 8, at some point (in quite a while) they will reach 16 and having the 16, 17 dir may cause and issue.   

Should skel/fedora[16|17] be removed?

**Comment by gdha** [comment]
@mutable-dan I created these many years ago and will have a look at them to see whether we still need those somehow, will come back later on this topic

**Comment by jsmeix** [comment]
I think this issue is fixed with https://github.com/rear/rear/pull/2233 merged.
