### ISSUE TITLE
openSUSE Leap 15.0 - nothing provides genisoimage needed by rear-2.4-1.git.3250.bf91ae91.master.x86_64

### ISSUE THREAD

**Issue by roseswe** [rear/rear#2161]
sudo zypper in ./rear-2.4-1.git.3250.bf91ae91.master.x86_64.rpm
::
Problem: nothing provides genisoimage needed by rear-2.4-1.git.3250.bf91ae91.master.x86_64
 Solution 1: do not install rear-2.4-1.git.3250.bf91ae91.master.x86_64
 Solution 2: break rear-2.4-1.git.3250.bf91ae91.master.x86_64 by ignoring some of its dependencies

**Comment by jsmeix** [comment]
This does not look like an issue in ReaR itself.
ReaR just works for me on my openSUSE Leap 15.0 system.
For me `rpm -q --requires rear` does not show `genisoimage`.

**Comment by jsmeix** [comment]
FWIW: Rear 2.4 is outdated, meanwhile ReaR 2.5 was released.

**Comment by roseswe** [comment]
Sorry, this bug is in https://github.com/gozora/rear  fork, not in "upstream" rear, closing

**Comment by jsmeix** [comment]
@roseswe 
I don't think it can be called a `bug` whatever @gozora may like to have
in his own particular fork of ReaR for his own experimenmts with it.
But it is likely a (possibly even severe) security `bug` when you try to
"just install" software from arbitrary foreign repositories onto your system
(except it is a well isolated test system).
