### ISSUE TITLE
Bug report on rear in /usr/share/rear/build/default/980_verify_rootfs.sh line 29

### ISSUE THREAD

**Issue by bwswah** [rear/rear#2198]
v#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.4 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): RedHatEnterpriseServer Version 7

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):  SuperMicro PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SATA RAID 1

* Description of the issue (ideally so that others can reproduce it):
rear mkrescue failed with error in /usr/share/rear/build/default/980_verify_rootfs.sh line 29
[rear.log](https://github.com/rear/rear/files/3460200/rear.log)
[rear.log](https://github.com/rear/rear/files/3460204/rear.log)

* Workaround, if any: none

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

run using rear -d -D mkrescue

**Comment by jsmeix** [comment]
@bwswah 
the actual error in your rear.log is
```
++ chroot /tmp/rear.uSzyGb945H7DRfQ/rootfs /bin/ldd /bin/bash
/usr/bin/ldd: fork: Cannot allocate memory
```
so it seems you are out of memory.
But I cannot guess why.

**Comment by jsmeix** [comment]
No news is good news.
