### ISSUE TITLE
checklayout indicates layout change if USB external drive mounted

### ISSUE THREAD

**Issue by adatum** [rear/rear#2207]
* ReaR version ("/usr/sbin/rear -V"): 2.4

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): Fedora 30

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
`REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" /home/test/Downloads/borg-linux64 )`

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI

* Description of the issue (ideally so that others can reproduce it):

If `rear mkrescue` has been run, `rear checklayout ; echo $?` is non-zero indicating a layout change if a USB external drive is mounted which was not present at the prior run of `rear mkrescue`. 

After the USB drive is unmounted, `rear checklayout ; echo $?` is zero again. 

This is bad especially when `rear checklayout || rear mkrescue` is scheduled to run automatically (cron or systemd timer), or even if it's just run manually while a USB drive happens to be mounted. 

This creates concern and confusion when `rear recover` notes that the device corresponding to the USB drive, `/dev/sdb` in this case, does not have a suitable target.
![rear_usb_target](https://user-images.githubusercontent.com/9773655/62841025-0dc74400-bc71-11e9-87ac-a85d3ca32908.png)

**Comment by jsmeix** [comment]
It works as designed.

ReaR takes all mounted normal filesystems into account
so when there are changes in what is mounted, the disk layout has changed.

**Comment by adatum** [comment]
In that case, is it possible to specify to ReaR not to monitor certain directories, eg. common mount points? 

Actually, does it even have to be mounted or does anything in `fdisk -l` get considered by ReaR?

The use case must be common enough, yes? Does it make sense to create a new (incorrect) disk layout if a USB key/drive is plugged in? The result becomes unpredictable, especially if `rear mkrescue` is run on a schedule.
