### ISSUE TITLE
Relax-and-Recover ERROR: Cannot find required programs:  route

### ISSUE THREAD

**Issue by imagoillusion** [rear/rear#2208]
#### Relax-and-Recover (ReaR) Issue Template

Relax-and-Recover 2.5 / Git

OS_VENDOR=Arch

OUTPUT=ISO
OUTPUT_URL=file:///run/media/imago/702AA0914937AB39/backup/
BACKUP=NETFS
BACKUP_URL=iso:///backup/
export TMPDIR=/run/media/imago/702AA0914937AB39/rear/tmp
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/mnt/*')

Bios: Mbr,grub.

Storage: External hard disk

[rear.log](https://github.com/rear/rear/files/3491060/rear.log)

**Comment by jsmeix** [comment]
@imagoillusion 
ReaR requires the program 'route' so you need to get that installed.

**Comment by imagoillusion** [comment]
On arch linux there is not such program call route

**Comment by jsmeix** [comment]
I am not an Arch Linux user so I cannot tell you what you need to do
to get the program 'route' installed on your particular Linux distribution.
Likely on some Arch Linux help forum you could get that kind of help.
