### ISSUE TITLE
ReaR mkrescue fails: multiboot.mod not found

### ISSUE THREAD

**Issue by adatum** [rear/rear#2211]
* ReaR version ("/usr/sbin/rear -V"): 2.5 (rpm built from git)

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): Fedora 30

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI, GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local SSD

* Description of the issue (ideally so that others can reproduce it):

`rear mkrescue` fails, and the log contains:

> grub2-mkimage: error: cannot open '/usr/lib/grub/x86_64-efi/multiboot.mod': No such file or directory.

On my system:

```
$ locate multiboot
/usr/lib/grub/i386-pc/multiboot.mod
/usr/lib/grub/i386-pc/multiboot2.mod
/usr/share/qemu/multiboot.bin
```

In versions of ReaR prior to 2.5, `linuxefi` also causes the same error.

* Workaround, if any:

Edit `/usr/share/rear/lib/uefi-functions.sh` and remove `multiboot` from the list of grub modules. Prior to ReaR 2.5, also remove `linuxefi`.

Both the problem and workaround have been previously reported in https://github.com/rear/rear/issues/1996#issuecomment-446389799 and https://github.com/rear/rear/issues/2204#issuecomment-520251443.

**Comment by jsmeix** [comment]
@rmetrich @pcahyna 
could you have a look here?

I think your https://github.com/rear/rear/pull/2199
could be related but therein it is about /usr/lib/grub*/x86_64-efi
while here is is about /usr/lib/grub/i386-pc/

**Comment by rmetrich** [comment]
@jsmeix It is related to #2199 
The current code searches in /boot/grub*, hence finds /boot/grub2/i386-pc/multiboot.mod even though architecture is different (x86-64-efi is used here)

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2199 merged
I think this issue is also fixed.

**Comment by rmetrich** [comment]
@jsmeix indeed, fixed.
