### ISSUE TITLE
ERROR: Cannot find required programs:  route

### ISSUE THREAD

**Issue by imagoillusion** [rear/rear#2212]
#### Relax-and-Recover (ReaR) Issue Template
Relax-and-Recover 2.5 / Git

SB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

OUTPUT=ISO
OUTPUT_URL=file:///run/media/imago/702AA0914937AB39/backup/
BACKUP=NETFS
BACKUP_URL=iso:///backup/
export TMPDIR=/run/media/imago/702AA0914937AB39/rear/tmp
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/mnt/*')

Desktop PC Hp Pro 3400 MT
Bios:MBR

Relax-and-Recover 2.5 / Git
Running rear mkbackup (PID 22888)
Using log file: /var/log/rear/rear-imagoillusion.log
ERROR: Cannot find required programs:  route
Some latest log messages since the last called script 950_check_missing_programs.sh:
  2019-08-13 14:09:01.616877237 Including init/default/950_check_missing_programs.sh
  /usr/share/rear/lib/_input-output-functions.sh: line 457: type: route: not found
Aborting due to an error, check /var/log/rear/rear-imagoillusion.log
 for details
Exiting rear mkbackup (PID 22888) and its descendant processes ...
Running exit tasks
Terminated

[Rear.log](https://github.com/rear/rear/files/3496903/Rear.log)

I have iproute installed but any way this program wanth wor enymore on my machine...Please help.Thank you.

**Comment by gozora** [comment]
Did you try  `sudo pacman -S core/net-tools` ?

V.

**Comment by imagoillusion** [comment]
No i didn't but for sure i will try.. Thank you man😘

**Comment by imagoillusion** [comment]
I try core/net-tools and it help with first error but than another came out..No more Relax and recover. That program become total shit with to much issues.Thanks anaway for help.

**Comment by gozora** [comment]
Well, It ain’t all rainbows and unicorns ...
Thanks anaway for your opinion.

V.
