### ISSUE TITLE
$BACKUP_OPTIONS missing for mount_url in 800_copy_to_tftp.sh and 810_create_pxelinux_cfg.sh

### ISSUE THREAD

**Issue by lewus** [rear/rear#2216]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.5-git.0.ef3febb.unknown.changed / 2019-07-04

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
OS_VENDOR=SUSE_LINUX
OS_VERSION=12.2

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://X.X.X.X/ReaR

OUTPUT=PXE
OUTPUT_PREFIX_PXE=rear/$HOSTNAME
PXE_CONFIG_GRUB_STYLE=y
PXE_TFTP_IP=X.X.X.X
PXE_CONFIG_URL="nfs://$PXE_TFTP_IP/ReaR/tftpboot/boot/grub2/powerpc-ieee1275"
PXE_CREATE_LINKS=IP
PXE_REMOVE_OLD_LINKS=y
PXE_TFTP_URL="nfs://$PXE_TFTP_IP/ReaR/tftpboot"

NETFS_KEEP_OLD_BACKUP_COPY=yes
export TMPDIR=/backup/rear
BACKUP_PROG_EXCLUDE+=( "${TMPDIR}/rear.*" )
ONLY_INCLUDE_VG=( 'vg00' )
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y

REAR_INITRD_COMPRESSION=lzma
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PowerVM LPAR

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
PPC64LE

* Description of the issue (ideally so that others can reproduce it):
If the NFS server is running AIX, BACKUP_OPTIONS="nfsvers=3,nolock" has to be specified.
This also works fine when using OUTPUT=ISO and BACKUP=NETFS.
However in case of OUTPUT=PXE, mounting the NFS will fail with "mount.nfs: Remote I/O error" because in 800_copy_to_tftp.sh and 810_create_pxelinux_cfg.sh there is no $BACKUP_OPTIONS specified when "mount_url" is issued.
Another solution would be to create a new option like: PXE_TFTP_BACKUP_OPTIONS and pass it to where it is needed.
I am opening this issue as I am not sure if this is a bug or a feature or maybe I have overseen something...

* Workaround, if any:
Add $BACKUP_OPTIONS to the line with mount_url in 00_copy_to_tftp.sh and 810_create_pxelinux_cfg.sh

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
`ERROR: Mount command 'mount -v -t nfs -o rw,noatime X.X.X.X:/ReaR/tftpboot /backup/rear/rear.NegRbcqsAJDpd64/tftpbootfs' failed.
Some latest log messages since the last called script 800_copy_to_tftp.sh:
  2019-08-16 12:29:03.005983358 Including output/PXE/default/800_copy_to_tftp.sh
  mkdir: created directory '/backup/rear/rear.NegRbcqsAJDpd64/tftpbootfs'
  2019-08-16 12:29:03.015161255 Mounting with 'mount -v -t nfs -o rw,noatime X.X.X.X:/ReaR/tftpboot /backup/rear/rear.NegRbcqsAJDpd64/tftpbootfs'
  mount.nfs: mount(2): Remote I/O error
  mount.nfs: Remote I/O error
  mount.nfs: timeout set for Fri Aug 16 12:31:03 2019
  mount.nfs: trying text-based options 'vers=4,addr=X.X.X.X,clientaddr=Y.Y.Y.Y'`

**Comment by gdha** [comment]
@lewus Good point - that is indeed missing with PXE/NFS - why don't you create a PR for it?

**Comment by lewus** [comment]
@gdha Sure, I have created PR [https://github.com/rear/rear/pull/2219](url)

**Comment by gdha** [comment]
@lewus Your PR has been merged - could you confirm all is oK?

**Comment by lewus** [comment]
@gdha yes, all is OK.

**Comment by gdha** [comment]
@lewus Thank you for testing it out - by this we can close this issue
