### ISSUE TITLE
Requesting PROGS fails

### ISSUE THREAD

**Issue by guru4712** [rear/rear#2228]
[rear-sm01.log.txt](https://github.com/rear/rear/files/3579184/rear-sm01.log.txt)

2.5-1

Red Hat Enterprise Linux Server release 7.6 (Maipo)

OUTPUT=ISO
USE_DHCLIENT=NO
USE_STATIC_NETWORKING=YES
USE_RESOLV_CONF=( NO )
PROGS=( more )

Fujitsu Server

X64

BIOS Grub2

local RAID5

Tried to build rescue system WITH OPTIONALLY ADDED PROGRAM "more" : rear mkrescue

Build process complains 'ldd' would be missing and requests new issue.

NO Workaround: if you include  'ldd' as well into the inclusion list, build process completes, BUT rescue kernel runs immediately into panic.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by jsmeix** [comment]
@guru4712 
etc/rear/local.conf is sources as a bash script so you need bash syntax,
see usr/share/rear/conf/default.conf
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf
where also each user config variable is described (at least a bit).
