### ISSUE TITLE
Question about defining values for predefined variables

### ISSUE THREAD

**Issue by guru4712** [rear/rear#2230]
Regarding Version 2.5-1

From issue https://github.com/rear/rear/issues/2228#issue-489707602 I learnt that setting values for variable PROGS must be carried out as an *addtion* of the new values to the predefined variable.

But why?
In default.conf variable PROGS is set to an *empty* array so it seemed not to make any harm to *set* some values. But it did not work.
Does anybody else do things to that variable before it is sourced with my values?
And if so, how could I know to be careful and only *add* things, since there is no hint in default.conf .

As for AUTOXCLUDE_PATH it works to *set* the respective pathes.

**Comment by pcahyna** [comment]
It is not empty. See at least https://github.com/rear/rear/blob/b8b7e466ed85891eff67e6653fb2239f41655f82/usr/share/rear/conf/GNU/Linux.conf#L12

**Comment by guru4712** [comment]
Thank you!

**Comment by jsmeix** [comment]
@guru4712 
a side note FYI:
Run `rear -s mkrescue` (`-s` is simulation mode)
to see what scripts would get sourced in your case.
Cf. "Debugging issues with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by guru4712** [comment]
Very helpful hints; thank you!

**Comment by jsmeix** [comment]
@pcahyna 
so we know now at least one reason for using
```
ARRAY=( "${ARRAY[@]}" additional elements )
```
instead of the simpler and more fail safe
```
ARRAY+=( additional elements )
```
:-)

@guru4712 
FYI what we are talking about see
https://github.com/rear/rear/issues/2220#issuecomment-528347818
and subsequent comments.
