### ISSUE TITLE
Enhanced default for AUTOEXCLUDE_PATH

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#2239]
Currently we have in default.conf
```
# Automatically exclude filesystems mounted under directories given here
# The default is /media to exclude USB devices mounted there.
# This is different from EXCLUDE_MOUNTPOINTS, which accepts only mountpoints.
AUTOEXCLUDE_PATH=( /media )
```

The recent issues like
https://github.com/rear/rear/issues/2215#issuecomment-521815673
(excerpt)
```
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "fs:/run/media" )

The problem is that it seems to exclude only exact paths
(eg. fs:/run/media/[USER]/[DISK_LABEL]),
and not everything inside /run/media.
It also does not expand globs like fs:/run/media/*.
```
and
https://github.com/rear/rear/issues/2229#issuecomment-531075116
(excerpt)
```
Changing to
AUTOEXCLUDE_PATH=( /run/media /mnt )
avoids commenting out components I want,
and also automatically excludes any temporary USB devices.
```
indicate that a nowadays better default for AUTOEXCLUDE_PATH
could be something like
```
AUTOEXCLUDE_PATH=( /media /run/media /mnt )
```

**Comment by gdha** [comment]
@jsmeix 
> what do you think about a nowadays better default for
> AUTOEXCLUDE_PATH to be something like
> 
> ```
> AUTOEXCLUDE_PATH=( /media /run/media /mnt )
Sure why not.

**Comment by rmetrich** [comment]
I would even propose
~~~
AUTOEXCLUDE_PATH=( /media /run /mnt /tmp )
~~~

**Comment by jsmeix** [comment]
@rear/contributors 
please review and test https://github.com/rear/rear/pull/2244
because I fear the impact could be high for some users
(e.g. when someone has /tmp mounted and expects that to be included).

**Comment by jsmeix** [comment]
@rmetrich 
regarding `/tmp` in AUTOEXCLUDE_PATH
I wonder if recovery still works o.k. by default
when one has `/tmp` mounted as a separated normal
filesystem like a separated disk with only /dev/sdc1
that is ext2 mounted at /tmp

**Comment by jsmeix** [comment]
In https://github.com/rear/rear/pull/2261#issue-332030061
I tested that it still works with a separated filesystem on /tmp.

With https://github.com/rear/rear/pull/2261 merged
I hope this issue is sufficiently done.
