### ISSUE TITLE
New BACKUP=CDM method to support Rubrik Cloud Data Management (CDM)

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2248]
#### Relax-and-Recover (ReaR) Issue Template

* ReaR version ("/usr/sbin/rear -V"): 

latest

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): 

All Linux distros that are supported by Rubrik CDM.

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

All that are supported by Rubrik CDM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

All that are supported by Rubrik CDM

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

All that are supported by Rubrik CDM

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

All that are supported by Rubrik CDM

* Description of the issue (ideally so that others can reproduce it):

Add support for Rubrik CDM as an external backup software.

* Workaround, if any:

None, new feature request.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

None, new feature request.

**Comment by jsmeix** [comment]
@DamaniN
many thanks for your valuable contribution to ReaR.
It is much appreciated.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2249 merged
this issue is done.

When there are issues with the new BACKUP=CDM method
new separated GitHub issues should be opened.

**Comment by jsmeix** [comment]
I updated the Release Notes for Relax-and-Recover version 2.6
https://github.com/rear/rear.github.com/blob/master/documentation/release-notes-2-6.md
