### ISSUE TITLE
lvm.conf filter

### ISSUE THREAD

**Issue by wdpoorte** [rear/rear#225]
Hi,

In our environment, with local boot disks and SAN disks, we want to make sure the SAN disks are only accessed via their multipath device, not the direct paths.  To do this, we block all access to the single paths using a filter in the lvm.conf file.  So in our filter line, we typically see something like this:

    filter = [ "a|/dev/disk/by-id/scsi-3600508b1001cdac79483c5b08490cb4d.*|", "a|/dev/mapper/mpath.*|", "a|/dev/disk/by-id/scsi-pvol.*|", "r/.*/" ]

Now if we recover a system using this on other hardware, we need to modify this filter line manually, otherwise the system will not boot after recovery.

**Comment by gdha** [comment]
@wdpoorte were you able to test this already with patch 6e05ec6?
