### ISSUE TITLE
Link to SuSE documentation in Rubrik User Guide is bad

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2255]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

Rear 2.5 - Master as of 10/1/2019

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

All

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

All

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

All

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

All

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

All

* Description of the issue (ideally so that others can reproduce it):

This link to the SuSE ReaR documentation leads to a SuSE download page:

https://www.suse.com/documentation/sle-ha-12/book_sleha/data/cha_ha_rear.html

* Workaround, if any:

Use this link instead: 

https://en.opensuse.org/SDB:Disaster_Recovery

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

N/A

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2256 merged
this issue is fixed.

@DamaniN 
thank you for your careful checking even of such minor details
that could make a major difference in end-user experience!
