### ISSUE TITLE
CDM: Recovery from alternate Rubrik cluster fails to copy certificate

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2263]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
2.6 - dev

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
All

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
N/A

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
All

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
N/A

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
N/A

* Description of the issue (ideally so that others can reproduce it):

To recover from a replica Rubrik CDM cluster the user is prompted to enter an alternate IP address. If a correct IP address is entered an error is produced indicating that the certificate cannot be copied.

* Workaround, if any:

None

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

````
RESCUE dn-rear-centos-7-6:~ # rear recover
Relax-and-Recover 2.5 / Git
Running rear recover (PID 6380)
Using log file: /var/log/rear/rear-dn-rear-centos-7-6.log
Running workflow recover within the ReaR rescue/recovery system

Is the data being restored from the original CDM Cluster? (y/n)
(default 'y' timeout 300 seconds)
n
Enter one of the IP addresses for the replica CDM cluster:
192.168.1.2
ERROR: Could not copy replica CDM cluster certificate
Some latest log messages since the last called script 410_use_replica_cdm_cluster_cert.sh:
  rubrik-agent-5.0.2.p1-sparc/openssl.cnf
  rubrik-agent-5.0.2.p1-sparc/version
  rubrik-agent-5.0.2.p1-sparc/RBA-sunos5.10.sparc.pkg
  rubrik-agent-5.0.2.p1-sparc/install-rubrik
  find: unknown predicate `-v'
  '/etc/rubrik/keys/rubrik.crt' -> '/etc/rubrik/keys/rubrik.crt.orig'
  cp: missing destination file operand after '/etc/rubrik/keys'
  Try 'cp --help' for more information.
Aborting due to an error, check /var/log/rear/rear-dn-rear-centos-7-6.log for details
Exiting rear recover (PID 6380) and its descendant processes ...
Running exit tasks
Terminated
````

**Comment by DamaniN** [comment]
This issue was introduced by 83e8c36. Assign this issue to me to fix.

**Comment by jsmeix** [comment]
@DamaniN 
thank you for your careful regression testing for BACKUP=CDM.

Sigh!
If there was better consistency in Unix command line options...

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2267 merged
this issue is fixed.
