### ISSUE TITLE
Cannot recover from ISO in UEFI Mode

### ISSUE THREAD

**Issue by Schneckubuntu** [rear/rear#2268]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.5 / Git
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
/etc/rear/local.conf:
OUTPUT=ISO
OUTPUT_URL=null
BACKUP=NETFS
BACKUP_URL=iso:///mnt/backup
BACKUP_PROG_EXCLUDE=(${BACKUP_PROG_EXCLUDE[@]} '/mnt/backup/*'  '/tmp/*' )
AUTOEXCLUDE_PATH=( /media /mnt ) 
ISO_DIR="/mnt/backup"
ISO_PREFIX="backup-$HOSTNAME-$DATE"
USING_UEFI_BOOTLOADER=1

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Asrock J5005 - UEFI BIOS
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
amd64
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Description of the issue (ideally so that others can reproduce it):
I cannot recover my ISO-Backup on UEFI platform.
I transfered the ISO with rufus to an USB Stick; after the boot sequence i start with "rear recover" but an error accurs, look at the picture:
https://abload.de/img/20191026_201427sljbp.jpg
On my other system, a legacy bios board Asrock J4205 all is fine without UEFI Mode.
Can you helb me to figure out the correct .conf?
All i want is to create a functional ISO backup (all-include, Boot and Backup)
On my other system, a legacy bios board Asrock J4205 all is fine without UEFI Mode.

**Comment by gozora** [comment]
Hi, 

Why dont you do backup directly to usb? 

https://github.com/rear/rear/blob/master/doc/user-guide/04-scenarios.adoc#bootable-usb-device-with-backup-to-usb

V.

**Comment by Schneckubuntu** [comment]
Hi gozora,
i want to make a cronjob every 2 weeks and archive the ISOs by copying to a NAS.
OK, directly to USB worked after a test and reovering is successful.
But i want to know why it is working on a legacy system and with UEFI not.

**Comment by Schneckubuntu** [comment]
Found the solution by myself...
It´s necessary to convert the ISO to stick with "Universal USB Installer v1.9.8.9" (Windows).
There is the option to "try via DD" before choosing the ISO.
Then booting and recovering worked fine!
The other way is to convert directly under Linux with:
> dd if=backup.iso of=/dev/sdb bs=1MB

Maybe there are other users here who are facing the same problem, so thread can be closed or not...
Rear is the best backup software for Linux!!!

**Comment by jsmeix** [comment]
@Schneckubuntu 
thank you for your feedback how you got things working
for your use case.

I did not check the details here but I think
https://github.com/rear/rear/issues/2210
looks like the same issue.

A side note FYI regarding
using `OUTPUT=USB` but without also using `BACKUP_URL=usb://...`
(e.g. using `OUTPUT=USB` with `BACKUP_URL=nfs//...`) see
https://github.com/rear/rear/issues/2171
