### ISSUE TITLE
"rear recover" over unstable ssh connection

### ISSUE THREAD

**Issue by geksi** [rear/rear#2282]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.4

```
I'm using rear with TSM.

The problem is, "rear recover" doesn't run to the end - unexpected ssh disconnects
occur during the TSM recovery job and rear job goes broken.

The TSM restore takes most of the time > 60 minutes. 

Is it possible to run the TSM restore job in the background?

P.S.
no other access methods are avaible exept ssh
```

**Comment by gozora** [comment]
@geksi just from top of my head, you could try to include `screen` using `PROGS` configuration variable and start restore inside `screen` ...

V.

**Comment by gdha** [comment]
@geksi see also https://superuser.com/questions/699676/how-to-prevent-ssh-from-disconnecting-if-its-been-idle-for-a-while

**Comment by gdha** [comment]
@geksi Any further info required?
