### ISSUE TITLE
CloudLinux Server release 6.10 on raid wont load udev while booting on rear rescue image

### ISSUE THREAD

**Issue by franciscohosting** [rear/rear#2287]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.5 / 2019-05-10

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6.10

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

BACKUP=BAREOS
BAREOS_CLIENT=desembarco104119
BAREOS_FILESET=centos-fileset
BAREOS_RESTORE_JOB=desembarco104119-restore
OUTPUT_URL=file:///var/lib/rear/rescueBootableImages
SSH_ROOT_PASSWORD=****
OUTPUT=RAWDISK
RAWDISK_IMAGE_COMPRESSION_COMMAND=''
export TMPDIR="/var/lib/backupTmp"
MIGRATION_MODE='true'
AUTORESIZE_PARTITIONS='true'

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

Legacy Grub

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

SSD

* Description of the issue (ideally so that others can reproduce it):

Doing a rescue image of a raid computer, and loading it to another PC without raid, the rescue image says that UDEV cant load, later on it says that /mnt/local is not mounted (obviously)

* Workaround, if any:

None yet

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

`rear -D mkrescue`

[rear-desembarco104119.log](https://github.com/rear/rear/files/3888933/rear-desembarco104119.log)

read `40-start-udev-or-load-modules.sh`, and thought that maybe my systmed_version was too low, so I forced rear to run the manual method to deal with modules, but didn't work either.

In the original server I don't have sysmted installed:
```
[root@asd rear]# systemd-notify --version
-bash: systemd-notify: command not found
```
![WhatsApp Image 2019-11-25 at 19 26 03](https://user-images.githubusercontent.com/56039320/69583367-843a4880-0fb9-11ea-9f04-fdcbd2d9df0b.jpeg)

**Comment by jsmeix** [comment]
As an initial quick generic info (I didn't have a closer look here)
regarding
```
Doing a rescue image of a raid computer,
and loading it to another PC without raid
```

This may work in some cases but in general it won't work.

See the sections
"Fully compatible replacement hardware is needed" and
"How disaster recovery with ReaR basically works" in
https://en.opensuse.org/SDB:Disaster_Recovery
where the latter reads in particular
```
The ReaR recovery ISO image contains
the ReaR recovery installation system with the ReaR installer
that is specific for the system where it was made
```

When you intend to do "rear recover" on different hardware
you do a so called "migration".

In general migrating with ReaR could become a complicated task
depending on how much the replacement system is different
compared to the original system.

Regarding migrating a system with ReaR see for example
http://lists.relax-and-recover.org/pipermail/rear-users/2018-November/003626.html
and follow the links therein as appropriate in your particular case.
