### ISSUE TITLE
SGI uv100 with SLES 11 SP1 

### ISSUE THREAD

**Issue by umcastello** [rear/rear#229]
I tried to run the system rear (rear-1.14-3.noarch.rpm) in a computer SGI uv100 with SLES 11 SP1 and got the following error:

#rear -v mkbackup                                                                                                                                    

Relax-and-Recover 1.14 / Git
Using log file: /var/log/rear/rear-machine.log
Creating disk layout
ERROR: Unknown boot loader elilo found in '/etc/sysconfig/bootloader'
Aborting due to an error, check /var/log/rear/rear-machine.log for details
Terminated

Is there any way to fix this?

Best regards,
Ulisses

**Comment by gdha** [comment]
https://bugzilla.novell.com/show_bug.cgi?id=649046 explains that the `dosfslabel` command is now part of the `dosfstools`  package. Hum, dates back from 2010, and now in 2015 on SLES 11SP3 there is no trace of `dosfslabel` even the package is installed:
````
# rpm -ql dosfstools
/sbin/dosfsck
/sbin/fsck.msdos
/sbin/fsck.vfat
/sbin/mkdosfs
/sbin/mkfs.msdos
/sbin/mkfs.vfat
/usr/share/doc/packages/dosfstools
/usr/share/doc/packages/dosfstools/CHANGES
/usr/share/doc/packages/dosfstools/README.Atari
/usr/share/doc/packages/dosfstools/TODO
/usr/share/doc/packages/dosfstools/dosfsck
/usr/share/doc/packages/dosfstools/dosfsck/COPYING
/usr/share/doc/packages/dosfstools/dosfsck/README
/usr/share/doc/packages/dosfstools/mkdosfs
/usr/share/doc/packages/dosfstools/mkdosfs/COPYING
/usr/share/doc/packages/dosfstools/mkdosfs/README
/usr/share/man/man8/dosfsck.8.gz
/usr/share/man/man8/fsck.msdos.8.gz
/usr/share/man/man8/fsck.vfat.8.gz
/usr/share/man/man8/mkdosfs.8.gz
/usr/share/man/man8/mkfs.msdos.8.gz
/usr/share/man/man8/mkfs.vfat.8.gz

````

**Comment by gdha** [comment]
SLES 12 seems ok:
````
$ rpm -ql dosfstools
/sbin/dosfsck
/sbin/dosfslabel
````

**Comment by jsmeix** [comment]
Regarding https://github.com/rear/rear/issues/229#issuecomment-97048029 I can explain why dosfslabel is still missing even on SLE11-SP3:

https://bugzilla.opensuse.org/show_bug.cgi?id=649046 is about openSUSE 11.3 and SLE11 is basically based on openSUSE 11.1 (cf. the list of values for the suse_version RPM macro in https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto)

Therefore the issue exists also in SLE11.

Unfortunaltely the issue was not fixed in any SLE11 service pack so that dosfslabel is still missing even on SLE11-SP3.

**Comment by jsmeix** [comment]
I submittend an internal request to get dosfslabel icluded in SLE11.

As far as I understand it dosfslabel is only needed to recover vfat partitions and because for UEFI Boot Loader its EFI System partition (ESP) is a vfat partition, dosfslabel is also needed for UEFI.

Or are there more cases where rear needs dosfslabel?

**Comment by gdha** [comment]
@jsmeix No that is basically it - was yesterday busy with a bunch of SLES SAP HANA systems based on SLES11SP3 and using UEFI to boot from, so that is why dosfslabel was needed. However, as UEFI ISO creation is not possible (see issue #214) I disabled UEFI and to recover a one-time boot into legacy BIOS is required. Afterwards, UEFI booting needs to be configured manually...

**Comment by jsmeix** [comment]
@gdha 
many thanks for the information!

**Comment by schlomo** [comment]
Maybe in this case we will spend less total effort by removing the
dependency on dosfslabel? mkfs.vfat allows setting the label and blkid can
be used to retrieve the label, with probably a bunch of other tools.

**Comment by jsmeix** [comment]
I am faster!
;-)

I built our newest dosfstools from the Base:System development project of the openSUSE build service in my personal playground project home:jsmeix also for SLE11 (all SLE11 service packs and various openSUSE versions and SLE12) for direct RPM download from
http://download.opensuse.org/repositories/home:/jsmeix/

Please read
https://build.opensuse.org/project/show/home:jsmeix

For example how I installed it on my SLE11-SP3 64bit x86_64 system:
<pre>
# wget http://download.opensuse.org/repositories/home:/jsmeix/SLE_11_SP3/x86_64/dosfstools-3.0.27-93.1.x86_64.rpm
...
2015-04-29 17:32:45 (8.55 MB/s) - `dosfstools-3.0.27-93.1.x86_64.rpm' saved [91120/91120]

# rpm -Uhv dosfstools-3.0.27-93.1.x86_64.rpm
...
1:dosfstools  ######################## [100%]

# type -a dosfslabel
dosfslabel is /sbin/dosfslabel
dosfslabel is /usr/sbin/dosfslabel
</pre>

**Comment by RedBrick36** [comment]
my .02
When it errored out, I edited the script (All I did was comment out the
call for dosfslabel) told it to continue and it finished running the
script just fine....

On Wed, 2015-04-29 at 05:54 -0700, Schlomo Schapiro wrote:
> Maybe in this case we will spend   total effort by removing the
> dependency on dosfslabel? mkfs.vfat allows setting the label and blkid
> can
> be used to retrieve the label, with probably a bunch of other tools.
> 
> On 29 April 2015 at 11:54, Johannes Meixner <notifications@github.com>
> wrote:
> 
> > @gdha <https://github.com/gdha>
> > many thanks for the information!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rear/rear/issues/229#issuecomment-97374746>.
> >
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

-- 
Admin <admin@mrelectricsa.com>

**Comment by jsmeix** [comment]
dosfslabel (fatlabel) is not part of dosfstools 2.11.

dosfstools 2.11 is provided up to SLE11-SP3 which means using dosfslabel cannot work up to SLE11-SP3.

For the upcoming SLE11-SP4 we will provide a version upgrade to dosfstools-3.0.26 (the same as we provide in SLE12) which means using dosfslabel will work for SLE11-SP4 (and SLE12).

Regarding @RedBrick36 "comment out the call for dosfslabel":

I am not at all a sufficient expert in this area to imagine if leaving out the call for dosfslabel may cause whatever issues elsewhere in some/many/most? cases.

If it should work in almost all cases also without the call for dosfslabel, a generic solution could be to test if dosfslabel can be called and only use it if it exists.

**Comment by pavoldomin** [comment]
@gdha how have you addressed a missing dosfslabel, when doing UEFI-booting DR of SAP HANA SLES (cf. http://www.it3.be/2015/10/27/uefi-iso-boot-with-ebiso/)? Have you installed dosfstools from the repo referenced by @jsmeix above, or does the recovery work also without? I am concerned because of the line in my ```rear -v savelayout``` log:

    /usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh: line 130: dosfslabel: command not found

**Comment by pavoldomin** [comment]
If I actually tried also *mkrescue*, I would not ask stupid questions, as it fails immediately with the clear message:

    # rear mkrescue
    ERROR: Cannot find required programs: dosfslabel
    Aborting due to an error, check /var/log/rear/rear-hostname.log for details
    Terminated

So you must have had dosfstools extra upgraded on your SLES11 server for HANA recovery @gdha , right?

**Comment by pavoldomin** [comment]
I am willing to obsolete the requirement of dosfstools by blkid and mkfs.vfat, as outlined above by @schlomo , unless you guys have reasons not to. I would post a pull request.

**Comment by gdha** [comment]
@pavoldomin Here is an example of a `/etc/rear/local.conf`file:
````
# SAP HANA on UEFI capable systems need EFI and DOS tools.
# SLES 11 SP3 does not have dosfslabel executable in package dosfstools-2.11-121.30.1
# Download package with dosfslabel included from (SLES 11 SP4 and SLES 12 are fine):
#  wget http://download.opensuse.org/repositories/home:/jsmeix/SLE_11_SP3/x86_64/dosfstools-3.0.28-97.1.x86_64.rpm
# and update it :
# rpm -Uvh dosfstools-3.0.28-97.1.x86_64.rpm

# ebiso package is available at (SLES 11 SP3):
#  wget http://download.opensuse.org/repositories/home:/gdha/SLE_11_SP3/x86_64/ebiso-0.1.4-7.1.x86_64.rpm
# Install it: rpm -ivh ebiso-0.1.4-7.1.x86_64.rpm
# Furthermore ebiso needs rear higher then 1.17.2 (e.g. use a development release)
ISO_MKISOFS_BIN=/usr/bin/ebiso

# Define backup method and location
BACKUP=NETFS
BACKUP_URL=nfs://sgnt8133/var/archive

# make sure to exclude ALL SAP HANA related volume groups and mount points
EXCLUDE_VG=( vgHANA-data-HC2 vgHANA-data-HC3 vgHANA-log-HC2
  vgHANA-log-HC3 vgHANA-shared-HC2 vgHANA-shared-HC3 )
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/hana/*' )
````

If you would like to get rid of `dosfslabel`  be my guest by creating a patch using `blkid` and `mkfs.vfat -n label` scheme. I really don't mind. It would save you lots of work (not to update dosfstools on all SLES 11 systems). However, if you wish to do so - could you re-open this issue so it is easier to track (for us). Or, perhaps, create a new issue...

**Comment by pavoldomin** [comment]
Thanks @gdha. I will indeed open separate new issues (dosfslabel is just one of them) and submit patches for problems I am having with my current DR tests, related with the complex uefi-booting landscape. You can expect several pull requests coming from me next week ;)

**Comment by jsmeix** [comment]
@gdha 
I think your above example of a /etc/rear/local.conf
for SAP HANA on UEFI capable systems
would make perfect sense to be added into
the new usr/share/rear/conf/examples directory
(cf. https://github.com/rear/rear/pull/681).

**Comment by jsmeix** [comment]
@gdha 
right now I copied dosfstools and ebiso to the openSUSE Build Service
project Archiving:Backup:Rear to make them avaialbe at the same
place where rear is:
<pre>
$ osc copypac -e home:gdha ebiso Archiving:Backup:Rear ebiso

$ osc copypac -e Base:System dosfstools Archiving:Backup:Rear dosfstools
</pre>

I will check how they build there.

If they build sufficiently there, I will adapt the URLs in
your above example of a /etc/rear/local.conf
for SAP HANA on UEFI
and add it into the new
usr/share/rear/conf/examples directory

**Comment by jsmeix** [comment]
I know I hijacked this issue but I hope for this
small documentation add-on it is o.k.
...

**Comment by jsmeix** [comment]
Building dosfstools and ebiso in OBS Archiving:Backup:Rear
looks fine:
<pre>
$ osc results -v Archiving:Backup:Rear dosfstools | grep succeeded            
SLE_11_SP3           i586       succeeded(unpublished)
SLE_11_SP3           x86_64     succeeded(unpublished)
SLE_11_SP2           i586       succeeded(unpublished)
SLE_11_SP1           x86_64     succeeded(unpublished)
SLE_11_SP1           i586       succeeded(unpublished)
SLE_11               x86_64     succeeded(unpublished)
SLE_11               i586       succeeded(unpublished)

$ osc results -v Archiving:Backup:Rear ebiso | grep succeeded            
SLE_12               x86_64     succeeded(unpublished)
SLE_11_SP4           x86_64     succeeded(unpublished)
SLE_11_SP3           x86_64     succeeded(unpublished)
SLE_11_SP1           x86_64     succeeded(unpublished)
SLE_11               x86_64     succeeded(unpublished)
</pre>
They should be automatically published in a few hours
which makes the RPMs available under
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/

@gdha 
when https://github.com/rear/rear/pull/683 is o.k. for you,
I can merge it.

**Comment by jsmeix** [comment]
RPMs for dosfstools and ebiso from OBS Archiving:Backup:Rear
are now available from
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/

dosfstools is available for i586 and x86_64 for
SLE_11 SLE_11_SP1 SLE_11_SP2 SLE_11_SP3

ebiso is available for x86_64 for
SLE_11 SLE_11_SP1 SLE_11_SP2 SLE_11_SP3
SLE_11_SP4 SLE_12

If needed I can enable build for more distributions and architectures.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/683 merged
and RPMs for dosfstools and ebiso
available from OBS Archiving:Backup:Rear
I consider the issue to be fixed as good as
currently possible in rear.
