### ISSUE TITLE
ReaR at FOSDEM 2020 "Backup and Recovery" devroom (01. Feb. 2020)

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#2304]
#### Visit us at the "Backup and Recovery" devroom on Saturday 01. Feb. 2020!

@gdha and @jsmeix will present
`Relax-and-Recover with Demo on Real Hardware`
https://fosdem.org/2020/schedule/event/basicrear/

@gdha will present
`Relax-and-Recover Mass Deployment`
https://fosdem.org/2020/schedule/event/massrear/

The current Backup and Recovery devroom schedule:
https://fosdem.org/2020/schedule/track/backup_and_recovery/

About FOSDEM 2020
https://fosdem.org/2020/

**Comment by jsmeix** [comment]
@schlomo @gozora @rmetrich @schabrolles
@dagwieers @jhoekx 
@OliverO2 @pcahyna @tcerna
@petroniusniger @mutable-dan @DamaniN @hpannenb @fabz5 @petrpavlu 
and all others who are interested in ReaR:

Do you plan to attend FOSDEM 2020?
If yes, we could talk to each other in person there!

**Comment by fabz5** [comment]
Can't make it unfortunately, maybe next time. :-)

**Comment by mutable-dan** [comment]
can not make it :-/

**Comment by pcahyna** [comment]
I am not going to FOSDEM unfortunately. Is anybody among you going to DevConf in Brno?

**Comment by petroniusniger** [comment]
Disclaimer | Use of IBA e-communication<https://iba-worldwide.com/disclaimer>

The contents of this e-mail message and any attachments are intended solely for the recipient (s) named above. This communication is intended to be and to remain confidential and may be protected by intellectual property rights. Any use of the information contained herein (including but not limited to, total or partial reproduction, communication or distribution of any form) by persons other than the designated recipient(s) is prohibited. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free. Ion Beam Applications does not accept liability for any such errors. Thank you for your cooperation.

**Comment by jsmeix** [comment]
@pcahyna 
I am not going to DevConf in Brno.
On a quick first glance it seems there is nothing on
https://devconfcz2020a.sched.com/
that matches disaster recovery or backup or even ReaR.

**Comment by jsmeix** [comment]
@petroniusniger 
it seems your recent comment
https://github.com/rear/rear/issues/2304#issuecomment-571120609
does not contain real content (it is only an e-mail disclaimer footer).

**Comment by petroniusniger** [comment]
@jsmeix 
Sorry about the rotten format of the emails I send -- some brilliant idea of our IT Dept. :-/ I don't have any control over this, unfortunately. The original message body is converted into an attachment -- go figure.

In any case, here was my reply to your message:

> Yes, I'll do my best to attend (would be a shame not to, as I live close
> by ;-) ), and I would indeed welcome the opportunity to meet you and the
> rest of the team.

> Can you please tell me where and when I can expect to find you?

> Cheers. Bye.

> Ph. A.

**Comment by jsmeix** [comment]
@petroniusniger 
you can find us (in particular @gdha and me )
in the "Backup and Recovery" devroom on Saturday 01. Feb. 2020
which is `Room: UD2.119` according to the current
https://fosdem.org/2020/schedule/track/backup_and_recovery/
where the `UD2.119` link points to
https://fosdem.org/2020/schedule/room/ud2119/
where a `Building: U` link is that points to
https://fosdem.org/2020/schedule/buildings/#u

More general info about the location `ULB Campus du Solbosch`
is on UBL pages like
https://www.ulb.be/en/maps-access
and
https://www.ulb.be/en/maps-directions/solbosch
and
https://www.ulb.be/en/solbosch/campus-map
but currently I fail to find a map of the rooms inside the `U` building.

I remember from former FOSDEM visits that finding the right room
inside a building was sometimes a somewhat advanced task for me
(I guess Belgians may have extradordinary habits of room counting
or Germans have extradordinary expectations of room counting ;-)

**Comment by petroniusniger** [comment]
Many thanks for this information, Johannes. I'll meet you there.
I'm familiar with the Campus du Solbosch, having studied there too many years ago. I can confirm its buildings can be labyrinthine.

**Comment by jsmeix** [comment]
After FOSDEM 2020 is before FOSDEM 2021
so I look forward to seeing you at FOSDEM 2021!
