### ISSUE TITLE
ERROR: Could not find file 'mbr.bin'. Syslinux version 3.08 or newer is required, 4.x prefered!

### ISSUE THREAD

**Issue by celikozl** [rear/rear#2305]
#### Relax-and-Recover (ReaR) Issue Template

Can you help me with this please?

* ReaR version ("/usr/sbin/rear -V"):
```
[root@telco ~]# /usr/sbin/rear -V
-bash: /usr/sbin/rear: No such file or directory
```

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
[root@telco ~]# cat /etc/rear/local.conf
cat: /etc/rear/local.conf: No such file or directory
[root@telco ~]# cat /etc/rear/site.conf
cat: /etc/rear/site.conf: No such file or directory
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC DELL Poweredge R220

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI Centos7

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
[root@telco ~]# lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT
NAME        KNAME     PKNAME   TRAN   TYPE FSTYPE   SIZE MOUNTPOINT
/dev/sda    /dev/sda                  disk          1.8T 
|-/dev/sda1 /dev/sda1 /dev/sda        part vfat     850M /boot/efi
|-/dev/sda2 /dev/sda2 /dev/sda        part xfs      1.1T /home
|-/dev/sda3 /dev/sda3 /dev/sda        part swap     7.6G [SWAP]
`-/dev/sda4 /dev/sda4 /dev/sda        part xfs    736.5G /
/dev/sdb    /dev/sdb           usb    disk         14.3G 
`-/dev/sdb1 /dev/sdb1 /dev/sdb        part ext3    14.3G 
/dev/sr0    /dev/sr0           sata   rom          1024M 
```

* Description of the issue (ideally so that others can reproduce it):
```
git clone https://github.com/rear/rear.git
```
after cloning the logs are below:
```
cd rear/
[root@telco rear]# sudo usr/sbin/rear format /dev/sdb1
USB device /dev/sdb1 is not formatted with ext2/3/4 or btrfs filesystem
Type exactly 'Yes' to format /dev/sdb1 with ext3 filesystem
(default 'No' timeout 300 seconds)
Yes
[root@telco rear]# cat > etc/rear/local.conf <<EOF
> ### write the rescue initramfs to USB and update the USB bootloader
> OUTPUT=USB
> 
> ### create a backup using the internal NETFS method, using 'tar'
> BACKUP=NETFS
> 
> ### write both rescue image and backup to the device labeled REAR-000
> BACKUP_URL=usb:///dev/disk/by-label/REAR-000
> EOF
[root@telco rear]# sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 2.5 / Git
Running rear mkrescue (PID 638)
Using log file: /root/rear/var/log/rear/rear-telco.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
ERROR: Could not find file 'mbr.bin'. Syslinux version 3.08 or newer is required, 4.x prefered!
Some latest log messages since the last called script 340_find_mbr_bin.sh:
  2020-01-03 16:34:04.303711417 Including prep/USB/Linux-i386/340_find_mbr_bin.sh
Aborting due to an error, check /root/rear/var/log/rear/rear-telco.log for details
Exiting rear mkrescue (PID 638) and its descendant processes ...
Running exit tasks
Terminated
```

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
```
[root@telco ~]# rear -D mkrescue/mkbackup/recover
bash: rear: command not found...
```

**Comment by gozora** [comment]
Hi,

Do you have Syslinux installed?

V.

**Comment by celikozl** [comment]
> Hi,
> 
> Do you have Syslinux installed?
> 
> V.
Thank You. I've installed Syslinux and Extlinux. Now there is another issue. After first command I tried the second one. Can you help me on this?

# sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 2.5 / Git
Running rear mkrescue (PID 11775)
Using log file: /root/rear/var/log/rear/rear-telco.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Using autodetected kernel '/boot/vmlinuz-3.10.0-957.el7.x86_64' as kernel in the recovery system
Creating disk layout
Using guessed bootloader 'EFI' (found in first bytes on /dev/sda)
Verifying that the entries in /root/rear/var/lib/rear/layout/disklayout.conf are correct ...
Creating root filesystem layout
Skipping 'virbr0': not bound to any physical interface.
To log into the recovery system via ssh set up /root/.ssh/authorized_keys or specify SSH_ROOT_PASSWORD
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/centos/grubx64.efi' as UEFI bootloader file
Copying logfile /root/rear/var/log/rear/rear-telco.log into initramfs as '/tmp/rear-telco-partial-2020-01-06T13:44:54+0300.log'
Copying files and directories
Copying binaries and libraries
Copying all kernel modules in /lib/modules/3.10.0-957.el7.x86_64 (MODULES contains 'all_modules')
Copying all files in /lib*/firmware/
Broken symlink '/etc/grub2.cfg' in recovery system because 'readlink' cannot determine its link target
Symlink '/usr/lib/modules/3.10.0-957.el7.x86_64/build' -> '/usr/src/kernels/3.10.0-957.el7.x86_64' refers to a non-existing directory on the recovery system.
It will not be copied by default. You can include '/usr/src/kernels/3.10.0-957.el7.x86_64' via the 'COPY_AS_IS' configuration variable.
Symlink '/usr/lib/modules/3.10.0-957.el7.x86_64/source' -> '/usr/src/kernels/3.10.0-957.el7.x86_64' refers to a non-existing directory on the recovery system.
It will not be copied by default. You can include '/usr/src/kernels/3.10.0-957.el7.x86_64' via the 'COPY_AS_IS' configuration variable.
Testing that the recovery system in /tmp/rear.3Hdf4t22QVXxYTL/rootfs contains a usable system
There are binaries or libraries in the ReaR recovery system that need additional libraries
/usr/lib64/syslog-ng/loggen/libloggen_socket_plugin.so requires additional libraries
	libloggen_helper-3.23.so.0 => not found
	libloggen_plugin-3.23.so.0 => not found
/usr/lib64/syslog-ng/loggen/libloggen_ssl_plugin.so requires additional libraries
	libloggen_helper-3.23.so.0 => not found
	libloggen_plugin-3.23.so.0 => not found
ReaR recovery system in '/tmp/rear.3Hdf4t22QVXxYTL/rootfs' needs additional libraries, check /root/rear/var/log/rear/rear-telco.log for details
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (261433505 bytes) in 21 seconds
ERROR: /dev/disk/by-label/REAR-EFI is not block device. Use `rear format -- --efi <USB_device_file>' for correct format
Some latest log messages since the last called script 100_create_efiboot.sh:
  2020-01-06 13:45:37.648544927 Including output/USB/Linux-i386/100_create_efiboot.sh
  2020-01-06 13:45:37.649685618 Configuring device for EFI boot
Aborting due to an error, check /root/rear/var/log/rear/rear-telco.log for details
Exiting rear mkrescue (PID 11775) and its descendant processes ...
Running exit tasks
Terminated


[root@telco rear]#  sudo usr/sbin/rear format -- -- efi /dev/sdb1
ERROR: Argument efi is not accepted.
Some latest log messages since the last called script 950_check_missing_programs.sh:
  2020-01-06 13:55:22.864238003 Including init/default/950_check_missing_programs.sh
  2020-01-06 13:55:22.868465513 Finished running 'init' stage in 0 seconds
  2020-01-06 13:55:22.872364532 Using build area '/tmp/rear.rQ18iWyATrjse4I'
  2020-01-06 13:55:22.874876000 Running format workflow
  2020-01-06 13:55:22.875707150 Command line options of the format workflow: -- efi /dev/sdb1
Aborting due to an error, check /root/rear/var/log/rear/rear-telco.log for details
Terminated

**Comment by jsmeix** [comment]
@celikozl 
in general you may also have a look at things like
http://relax-and-recover.org/documentation/
and
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
and
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf
therein in particular the `[U]EFI` config variables
and also in general at
https://en.opensuse.org/SDB:Disaster_Recovery
therein in particular the sections
"Testing current ReaR upstream GitHub master code"
and
"First steps with Relax-and-Recover"

In particular regarding `OUTPUT=USB` on a UEFI system cf.
https://github.com/rear/rear/issues/2275#issuecomment-553802315

So I think on a UEFI system you need to prepare your USB disk with
```
rear -v format -- --efi /dev/sdX
```
instead of plain `rear format /dev/sdX` as described at
http://relax-and-recover.org/documentation/getting-started
which I think is meant for traditional BIOS systems
(but I am not a UEFI expert so I could be wrong).

**Comment by jsmeix** [comment]
I got the following email which belongs to this issue
so here a fullquote
```
Date: Mon, 06 Jan 2020 03:09:20 -0800
From: celikozl <notifications@github.com>
Reply-To: rear/rear <reply+AANUVQGE52XR2FLDLSRASRF4EBD6BEVBNHHCA7FGWU@reply.github.com>
To: rear/rear <rear@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [rear/rear] ERROR: Could not find file 'mbr.bin'. Syslinux version 3.08 or newer is required, 4.x prefered! (#2305)
Parts/Attachments:
   1 Shown    73 lines  Text (charset: UTF-8)
   2   OK     80 lines  Text (charset: UTF-8)
----------------------------------------

> Hi,
> 
> Do you have Syslinux installed?
> 
> V.
Thank You. I've installed Syslinux and Extlinux.
Now there is another issue.
After first command I tried the second one.
Can you help me on this?

# sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 2.5 / Git
Running rear mkrescue (PID 11775)
Using log file: /root/rear/var/log/rear/rear-telco.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Using autodetected kernel '/boot/vmlinuz-3.10.0-957.el7.x86_64' as kernel in the recovery system
Creating disk layout
Using guessed bootloader 'EFI' (found in first bytes on /dev/sda)
Verifying that the entries in /root/rear/var/lib/rear/layout/disklayout.conf are correct ...
Creating root filesystem layout
Skipping 'virbr0': not bound to any physical interface.
To log into the recovery system via ssh set up /root/.ssh/authorized_keys or specify SSH_ROOT_PASSWORD
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/centos/grubx64.efi' as UEFI bootloader file
Copying logfile /root/rear/var/log/rear/rear-telco.log into initramfs as '/tmp/rear-telco-partial-2020-01-06T13:44:54+0300.log'
Copying files and directories
Copying binaries and libraries
Copying all kernel modules in /lib/modules/3.10.0-957.el7.x86_64 (MODULES contains 'all_modules')
Copying all files in /lib*/firmware/
Broken symlink '/etc/grub2.cfg' in recovery system because 'readlink' cannot determine its link target
Symlink '/usr/lib/modules/3.10.0-957.el7.x86_64/build' -> '/usr/src/kernels/3.10.0-957.el7.x86_64' refers to a non-existing directory on the recovery system.
It will not be copied by default. You can include '/usr/src/kernels/3.10.0-957.el7.x86_64' via the 'COPY_AS_IS' configuration variable.
Symlink '/usr/lib/modules/3.10.0-957.el7.x86_64/source' -> '/usr/src/kernels/3.10.0-957.el7.x86_64' refers to a non-existing directory on the recovery system.
It will not be copied by default. You can include '/usr/src/kernels/3.10.0-957.el7.x86_64' via the 'COPY_AS_IS' configuration variable.
Testing that the recovery system in /tmp/rear.3Hdf4t22QVXxYTL/rootfs contains a usable system
There are binaries or libraries in the ReaR recovery system that need additional libraries
/usr/lib64/syslog-ng/loggen/libloggen_socket_plugin.so requires additional libraries
        libloggen_helper-3.23.so.0 => not found
        libloggen_plugin-3.23.so.0 => not found
/usr/lib64/syslog-ng/loggen/libloggen_ssl_plugin.so requires additional libraries
        libloggen_helper-3.23.so.0 => not found
        libloggen_plugin-3.23.so.0 => not found
ReaR recovery system in '/tmp/rear.3Hdf4t22QVXxYTL/rootfs' needs additional libraries, check /root/rear/var/log/rear/rear-telco.log for details
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (261433505 bytes) in 21 seconds
ERROR: /dev/disk/by-label/REAR-EFI is not block device. Use `rear format -- --efi <USB_device_file>' for correct format
Some latest log messages since the last called script 100_create_efiboot.sh:
  2020-01-06 13:45:37.648544927 Including output/USB/Linux-i386/100_create_efiboot.sh
  2020-01-06 13:45:37.649685618 Configuring device for EFI boot
Aborting due to an error, check /root/rear/var/log/rear/rear-telco.log for details
Exiting rear mkrescue (PID 11775) and its descendant processes ...
Running exit tasks
Terminated

[root@telco rear]#  sudo usr/sbin/rear format -- -- efi /dev/sdb1
ERROR: Argument efi is not accepted.
Some latest log messages since the last called script 950_check_missing_programs.sh:
  2020-01-06 13:55:22.864238003 Including init/default/950_check_missing_programs.sh
  2020-01-06 13:55:22.868465513 Finished running 'init' stage in 0 seconds
  2020-01-06 13:55:22.872364532 Using build area '/tmp/rear.rQ18iWyATrjse4I'
  2020-01-06 13:55:22.874876000 Running format workflow
  2020-01-06 13:55:22.875707150 Command line options of the format workflow: -- efi /dev/sdb1
Aborting due to an error, check /root/rear/var/log/rear/rear-telco.log for details
Terminated

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/rear/rear/issues/2305#issuecomment-571100028
```

But there is no
https://github.com/rear/rear/issues/2305#issuecomment-571100028
here.
Strange.

**Comment by jsmeix** [comment]
@celikozl 
you need to use exact commands.
It is not `rear format -- -- efi /dev/sdb1`
but `rear format -- --efi /dev/sdb`
i.e. `--efi` (one argument) instead of `-- efi` (two arguments `--` and `efi`)
and `/dev/sdb` (your whole USB disk will be wiped out and prepared for ReaR)
instedad of `/dev/sdb1` (which is only the first partition on `/dev/sdb`).
Your existing `/dev/sdb1` will be destroyed and recreated anew.

**Comment by jsmeix** [comment]
Because "no news is good news" I close it.
