### ISSUE TITLE
Not enough memory to load specified image

### ISSUE THREAD

**Issue by gramps269** [rear/rear#2314]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.5 / Git
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.7 (Maipo)
Release:        7.7
Codename:       Maipo

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
BACKUP=CDM
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64:/usr/lib64/eog:/lib64/eog:/usr/lib64/clang-private:/usr/lib64/samba:/usr/lib64/webkit2gtk-4.0:/usr/lib64/firefox:/usr/lib64/firefox/gtk2:/usr/lib64/bind9-export:/usr/lib64/mysql:/usr/lib64/libwbclient.so.0:/usr/lib64/python2.7/site-packages:/etc/alternatives:/var/lib/alternatives:/usr/lib64/samba/wbclient"

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Hardware
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk
* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda             8:0    0  1.4T  0 disk
├─sda1          8:1    0  500M  0 part /boot
└─sda2          8:2    0  1.3T  0 part
  ├─rhel-root 253:0    0   50G  0 lvm  /
  ├─rhel-swap 253:1    0   16G  0 lvm  [SWAP]
  ├─rhel-u04  253:2    0   81G  0 lvm  /u04
  ├─rhel-u03  253:3    0  120G  0 lvm  /u03
  ├─rhel-u02  253:4    0  500G  0 lvm  /u02
  ├─rhel-u01  253:5    0  165G  0 lvm  /u01
  └─rhel-home 253:6    0   50G  0 lvm  /home
sr0            11:0    1 1024M  0 rom

* Description of the issue (ideally so that others can reproduce it):
After creating an ISO from the server (Dell PowerEdge R830), I burned the ISO to a dvd and since I couldn't test to see if the image would boot and bring up the ReaR Menu, I attempted to boot the ISO on an older Dell OptiPlex 990.  The R830 has 32G ram and the Optiplex only has 16G ram.

When booting the ISO image, the boot would fail during "Loading initrd.cgz" with the error:
"Not enough memory to load specified image".  I tried another DVD ISO from another R830 in which I did successfully perform a BMR but I received the same message.

* Workaround, if any:
Before actually booting the image, edit the boot line and add (without the quotes) "mem=16000m" and the image was able to load.  I used 16000m since my Optiplex has 16G of ram.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by gramps269** [comment]
I am going to close this issue as I was also able to find a workaround.

**Comment by jsmeix** [comment]
@gramps269 
only a side note FYI regarding `export LD_LIBRARY_PATH` cf.
https://github.com/rear/rear/pull/2270#issuecomment-551832257

**Comment by jsmeix** [comment]
This issue is likely fixed via https://github.com/rear/rear/pull/2747
