### ISSUE TITLE
How to change nfs IP address in bootable iso

### ISSUE THREAD

**Issue by prasad9920** [rear/rear#2328]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
2.4
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Centos 7
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OTUPUT=ISO
BACKUP=NETFS
BACKUP_URL=file:///mnt/REAR

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):
I mounted the external HDD to my physical machine on /mnt and taken the backup under REAR directory backup done successfully. I burn ISO on cd and boot from iso and attached the external HDD to my new physical server but relax and recovery iso not detecting the external disk. So I shifted my backup.tar.gz to nfs but now I am unable to change BACKUP_URL path under bootable disk because iso in read-only mode. Please share the solution for the same.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jsmeix** [comment]
@prasad9920 
I do not understand your situation.
In particular I do not understand why you like to change the ISO.

When you booted the ReaR rescue/recovery system
(regardless how you booted it, form ISO, via PXE, whatever)
the ReaR recovery system runs in a ramdisk on the
computer where you had booted it.

In the running recovery system you can change whatever you like.
I.e. after you had logged in as 'root' but before you launch `rear recover`.
In particular you can change `/etc/rear/local.conf` in the recovery system
before you launch `rear recover`.

The limitation is what files and programs
you have included in the recovery system,
i.e. what functionality is possible within the
running recovery system, e.g. whether or not
you can access something on a remote host
via this or that network protocol.

What files and programs get included in the recovery system
is determined while "rear mkrescue/mkbackup" is run.
So it would be a dead end if you can change `/etc/rear/local.conf`
in the running recovery system to something where files and programs
would be needed that had not been included in the recovery system.

**Comment by jsmeix** [comment]
@prasad9920 
In the running recovery system you can also do whatever you like
before you launch `rear recover`, e.g. whatever actions and
commands you need to make an external disk accessible.

In particular with `BACKUP_URL=file:///mnt/REAR`
you would have to manually mount that needed thing
in the running recovery system at `/mnt/REAR`
before you launch `rear recover`.

**Comment by prasad9920** [comment]
Hi Johannes,

Thanks for help. Got confused with vi editor now able to change the file no issue. sorry for trouble. Once again thanks for help.

**Comment by jsmeix** [comment]
@prasad9920 
thank you for your feedback how you made it work.
It helps us to understand if ReaR works reasonably well
or if we may need to do some further improvements.

**Comment by prasad9920** [comment]
Hi Johannes,

One more query I am taking backup from HP DL360 Gen 9 server details as under

ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 1.17.2

OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Oracle Linux 6.6

ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://192.168.1.100/nfs_share/pcrf1
EXCLUDE_MOUNTPOINTS=( '/Logs' )

 when I started the backup it was showing good speed around 8-9 mbps but after 2GB data backup slowly speed was getting down around 300-400 kbps. how to troubleshoot further where is the issue?
I checked the connectivity between backup server and nfs it is good.

**Comment by prasad9920** [comment]
[root@localhost ~]# rear -d -v mkbackup
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-localhost.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-localhost.iso (98M)
Copying resulting files to nfs location
Encrypting disabled
Creating tar archive '/tmp/rear.le0CKvQC97urWyY/outputfs/localhost/backup.tar.gz'
Archived 2155 MiB [avg 592 KiB/sec]
Archived 2156 MiB [avg 556 KiB/sec]
Archived 2167 MiB [avg 381 KiB/sec]
Archived 2168 MiB [avg 370 KiB/sec]
Archived 2171 MiB [avg 337 KiB/sec]
Archived 2177 MiB [avg 297 KiB/sec]
Archived 2177 MiB [avg 296 KiB/sec]

**Comment by jsmeix** [comment]
@prasad9920 
as far as I can imagine ReaR has no direct infuence
on any kind of speed, regardless if it is local disk speed
or network speed or memory I/O speed and so on...

E.g. with `BACKUP_URL=nfs://...` ReaR mounts the NFS share
at a local mountpoint directory and then things therein are
accessed as in any other directory and speed depends on
how NFS behaves.

In particular regarding NFS there is
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L566
```
# BACKUP_OPTIONS variable contains the mount options, do not confuse with BACKUP_PROG_OPTIONS
BACKUP_OPTIONS=
```
so you can use `BACKUP_OPTIONS` to specify NFS mount options
that might help with NFS issues, fror an example see
```
# BACKUP_OPTIONS variable contains the NFS mount options and
# with 'mount -o nolock' no rpc.statd (plus rpcbind) are needed:
BACKUP_OPTIONS="nfsvers=3,nolock"
```
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE11-ext3-example.conf#L15

**Comment by prasad9920** [comment]
Thanks for help working fine now.

**Comment by jsmeix** [comment]
@prasad9920 
could you provide feedback how excatly you made it work
because I am interested what special settings
have helped in this or that particular cases, cf.
https://github.com/rear/rear/issues/2328#issuecomment-582384574

**Comment by prasad9920** [comment]
Sorry but issue yet not resolved so we changed our plan to create the vm using vmware converter P2V. may be I will reproduce same issue in local lab and test the same but thanks for help never ever got such response before on community support. Really appreciated. Thanks again for help.

**Comment by jsmeix** [comment]
@prasad9920 
a general side note regarding things like "P2V":

When your original system is running on bare metal and
you like to recreate that system on a VMware virtual machine
you do actually a migration from bare metal to VMware.

In general migrating with ReaR could become a complicated task
depending on how much the replacement system is different
compared to the original system.

Regarding migrating a system with ReaR see for example
http://lists.relax-and-recover.org/pipermail/rear-users/2018-November/003626.html
and follow the links therein.

See also the section about "Virtual machines" in
https://en.opensuse.org/SDB:Disaster_Recovery
