### ISSUE TITLE
Backup Archive not readable

### ISSUE THREAD

**Issue by dveleztx** [rear/rear#2329]
**ReaR version ("/usr/sbin/rear -V"):**

ReaR 2.3

**OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):**

Ubuntu 18.04.3 LTS (Bionic)

**ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):**

```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://ipaddr/volume/backup/"
```

**Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):**

oVirt Virtual Machine, although having issues with it freezing when booting from ISO, so for the moment being I'm using a Synology NAS to create the VM and do the rescue (then export it to see if that works for oVirt).

To elaborate, I get my ISO. I use the ISO on oVirt to boot to it, and when it starts booting up after selecting "Rescue <hostname>" it freezes after a few moments. No idea why. So, I have a Synology NAS can can spin up machines, I create a VM there, boot to the ISO, works fine. But, then I run `rear rescue`, and it tells me that the tar.gz is not readable. It's pointing to some `/tmp` path. I don't get it.

**System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):**

x86_64 architecture on both VM and Synology

**Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):**

UEFI

**Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):**

Virtual Disk, technically an SSD on both the oVirt Host and Synology

**Description of the issue (ideally so that others can reproduce it):**

I'm trying to make backups for my VMs on oVirt. As described above, I've had no luck with ISOs on oVirt. It comes up to the menu, select Rescue <hostname>, and it starts loading, and freezes up. Thought it was maybe my browser or ovirt viewer, even tried looking at it from another OS, no dice.

At this point, all I really care about is if these backups actually do work. So far, I can't prove that my backups are even working because I can't rescue them. My alternative solution was to spin up a VM on my Synology NAS, and do the rescue there, and then export that VM to an OVA and see if the oVirt can take that image. It's a pain, but there aren't a lot of good options for backup solutions for oVirt that I've found.

Anyway, I go through the menu on the Synology, I get to the prompt and run `rear rescue` and it stops a moment later saying the tar.gz file is not readable.

**Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):**

Here's the full error after running `rear recover`
```
Relax-and-Recover 2.3 / Git
Using log file: /var/log/rear/rear-hostname.log
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
RPC status rpc.statd available.
Using backup archive '/tmp/rear.FXto7PceFQdH2hF/outputfs/hostname/backup.tar.gz'
ERROR: Backup archive '/tmp/rear.FXto7PceFQdH2hF/outputfs/hostname/backup.tar.gz'
Aborting due to an error, check /var/log/rear/rear-hostname.log for details
Terminated
```

**Comment by gozora** [comment]
Hi, 
Your boot might be stuck because of missing kernel modules. You could try with ReaR 2.5, which creates rescue system with all available modules by default.

> Anyway, I go through the menu on the Synology, I get to the prompt and run rear rescue and it stops a moment later saying the tar.gz file is not readable.

Did you mean `rear mkrescue` ?

Either way, I'd appreciate if you could provide us with debug output from problematic sessions (`rear -D mkrescue/mkbackup/recover`)

V.

**Comment by dveleztx** [comment]
No, the `mkrescue` isn't the problem, it does that part just fine. It creates the ISO.

When I'm booting off the ISO, and I get to the menu, login as root and run `rear recover`, is when I'm getting issues.

I just tried with 2.5, same issue. Backup archive is not readable.

**Comment by jsmeix** [comment]
@dveleztx 
you posted an incomplete error message
```
ERROR: Backup archive '/tmp/rear.FXto7PceFQdH2hF/outputfs/hostname/backup.tar.gz'
```
which makes it needlessly hard for us to find out
where in the ReaR scripts it comes from,
I guess it is
https://github.com/rear/rear/blob/master/usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh#L65

I am a bit confused by your description about what kind of hardware
("hardware" could be also virtual hardware) and network environment
you use while you run "rear mkrescue" versus "rear recover".

First and foremost ReaR is meant to
recreate the system on "same hardware", cf.
"Fully compatible replacement hardware is needed" in
https://en.opensuse.org/SDB:Disaster_Recovery

So if you try to recreate on incompatible replacement "hardware"
(i.e. when you do a so called "migration" with ReaR) various issues
will get into your way depending on how exactly your particular
replacement "hardware" behaves incompatible.

Furthermore `rear mkrescue` won't create any backup, cf. `man rear`
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
so if you really did only `rear mkrescue` but never `rear mkbackup`
you would not yet have any backup.

Finally see
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
that reads (except)
```
Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
```
see also "Debugging issues with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
@dveleztx 
could you elaborate on the part about
```
ISOs on oVirt. It comes up to the menu, select Rescue ,
and it starts loading, and freezes up.
Thought it was maybe my browser or ovirt viewer
```
in particular how "your browser" is related there.
I am not a oVirt user and I will certainly not investigate
what that thingy is or how it behaves in detail.
According to
https://en.wikipedia.org/wiki/OVirt
it is from Red Hat so you may have to contact them
if there are issues with booting ISOs via oVirt "in between"
cf. https://tools.ietf.org/html/rfc1925
```
It is always possible to add another level of indirection.
```
See also "Recovery medium compatibility" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by dveleztx** [comment]
@jsmeix 
I'm a bit confused, `rear rescue` a non-existent command? It says to try `rear rescue` when I boot into the ISO and login as root. I've even followed a few tutorials where people do the same thing.

One of the few I saw is seen here: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-relax-and-recover_rear

So, the process is this:
1. I ssh into my VM, I run the `rear -v mkrescue` and this creates an ISO on my backup server.
2. I create another VM where I go to perform a rescue, and I use the ISO that is on my backup server to boot into it.
3. A menu comes up with some options, the first of which is `Rescue <hostname>`, I select that. It goes through a process of loading and then there's a login prompt
4. I login as root, and there is a message that says to run `rear rescue`, I run that, and that's where I get my errors.

I will try performing a `mkbackup`. I will give it a try here in a moment and see the results.

-------
To elaborate on the oVirt piece:

My VMs that I'm backing up are on oVirt, and I run my `mkrescue` on there. So, when I do a rescue, I create a new VM with the exact same settings and I start it by booting into the rescue ISO. For some reason, when I select `Rescue <hostname>`, it starts loading and then freezes.

My assumption is that it's the Viewer app, the application that allows you to "console" into your VM. But, I discovered that wasn't the case, I tried several and they all show the console to be frozen. I thought maybe it was a browser issue as well, that is also not the case.

That part I'll have to investigate.

I'll update soon, thanks!

**Comment by dveleztx** [comment]
I was able to rescue on my test. I did the rescue on my Synology NAS. Instead of doing `mkrescue`, I did `mkbackup` as you recommended. You are right, I feel like some of the tutorials I followed are a bit dated. My fault for not completely finish reading the docs. One of them I did see and I missed literally the last paragraph that would have saved me.

Thank you @jsmeix !

**Comment by jsmeix** [comment]
@dveleztx 
thank you for your feedback how you made it work.
It helps us to understand if ReaR works reasonably well
or if we may need to do some further improvements.

I cannot find a `rear rescue` command mentioned
in our ReaR upstream source files
neither in our current master sources
nor in what we released as ReaR version 2.3.

All I can find are things like
```
ReaR rescue/recovery system
ReaR rescue system
ReaR rescue image
ReaR rescue entry
REAR rescue mode
```
so as far as I can see our sources look good.

Also in the third-party documentation of Red Hat
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-relax-and-recover_rear
I cannot find a `rear rescue` command mentioned.
Also there they only talk about the rescue sysem or the rescue image
so as far as I can also this Red Hat documentation look good.

**Comment by dveleztx** [comment]
@jsmeix 

I just realized that I meant `rear recover`. I've been consistently mis-typing it, sorry about that!!

**Comment by jsmeix** [comment]
Thank you for your frank feedback!
Now I know I am no longer the only one on planet Earth
with such kind of sticky misapprehension :-)
