### ISSUE TITLE
rear dump fails and says "ERROR: EFI_STUB="" is incorrect option value pair."

### ISSUE THREAD

**Issue by kingpoop** [rear/rear#2330]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.2 / 2017-07-20
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/rear_2.2.orig.tar.gz

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:   trusty

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
None, fresh install with no entries in local.conf

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Dell PowerEdge 2950

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64 x86_64 x86_64 GNU/Linux

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):
Installed rear on the following linux server:
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

DOWNLOADED THE BITS FROM THE FOLLOWING LOCATION:
```
sudo wget http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/rear_2.2.orig.tar.gz
```

UNTAR:
```
sudo tar xzvf rear_2.2.orig.tar.gz
```

LASTLY BUILT AND INSTALLED IT:
```
sudo make install
== Validating scripts and configuration ==
find etc/ usr/share/rear/conf/ -name '*.conf' | xargs -n 1 bash -n
bash -n usr/sbin/rear
find . -name '*.sh' | xargs -n 1 bash -n
find usr/share/rear -name '*.sh' | grep -v -E '(lib|skel|conf)' | while read FILE ; do \
                num=$(echo ${FILE##*/} | cut -c1-3); \
                if [[ "$num" = "000" || "$num" = "999" ]] ; then \
                        echo "ERROR: script $FILE may not start with $num"; \
                        exit 1; \
                else \
                        if $( grep '[_[:alpha:]]' <<< $num >/dev/null 2>&1 ) ; then \
                                echo "ERROR: script $FILE must start with 3 digits"; \
                                exit 1; \
                        fi; \
                fi; \
        done
== Prepare manual ==
make -C doc man
make[1]: Entering directory `/home/rear/rear-2.2/doc'
make[1]: Nothing to be done for `man'.
make[1]: Leaving directory `/home/rear/rear-2.2/doc'
== Installing configuration ==
install -d -m0700 /etc/rear/
install -d -m0700 /etc/rear/cert/
[[ ! -e /etc/rear/local.conf ]] && \
                install -Dp -m0600 etc/rear/local.conf /etc/rear/local.conf
make: [install-config] Error 1 (ignored)
[[ ! -e /etc/rear/os.conf && -e etc/rear/os.conf ]] && \
                install -Dp -m0600 etc/rear/os.conf /etc/rear/os.conf
make: [install-config] Error 1 (ignored)
find /etc/rear/ -name '.gitignore' -exec rm -rf {} \; &>/dev/null
== Installing binary ==
install -Dp -m0755 usr/sbin/rear /usr/sbin/rear
sed -i -e 's,^CONFIG_DIR=.*,CONFIG_DIR="/etc/rear",' \
                -e 's,^SHARE_DIR=.*,SHARE_DIR="/usr/share/rear",' \
                -e 's,^VAR_DIR=.*,VAR_DIR="/var/lib/rear",' \
                /usr/sbin/rear
== Installing scripts ==
install -d -m0755 /usr/share/rear/
cp -a usr/share/rear/. /usr/share/rear/
find /usr/share/rear/ -name '.gitignore' -exec rm -rf {} \; &>/dev/null
== Installing working directory ==
install -d -m0755 /var/lib/rear/
install -d -m0755 /var/log/rear/
== Installing documentation ==
make -C doc install
make[1]: Entering directory `/home/rear/rear-2.2/doc'
install -Dp -m0644 rear.8 /usr/share/man/man8/rear.8
make[1]: Leaving directory `/home/rear/rear-2.2/doc'
sed -i -e 's,/etc,/etc,' \
                -e 's,/usr/sbin,/usr/sbin,' \
                -e 's,/usr/share,/usr/share,' \
                -e 's,/usr/share/doc/packages,/usr/share/doc,' \
                /usr/share/man/man8/rear.8
```

VERIFIED VERSION:
```
rear --version
Relax-and-Recover 2.2 / 2017-07-20
```

ISSUE IS THAT WHEN I EXECUTE A rear dump command i get the following error:
```
sudo rear dump
Relax-and-Recover 2.2 / 2017-07-20
Using log file: /var/log/rear/rear-gitlab.log.lockless
**ERROR: EFI_STUB="" is incorrect option value pair.**
Aborting due to an error, check /var/log/rear/rear-gitlab.log.lockless for details
```

AND THE LOG FILE DOESN'T SHOW MUCH AS YOU CAN SEE:
```
sudo cat /var/log/rear/rear-gitlab.log.lockless

2020-02-06 13:32:02.681536255 Relax-and-Recover 2.2 / 2017-07-20
2020-02-06 13:32:02.683035461 Command line options: /usr/sbin/rear dump
2020-02-06 13:32:02.684207239 Using log file: /var/log/rear/rear-gitlab.log.lockless
2020-02-06 13:32:02.685783554 Including /etc/rear/os.conf
2020-02-06 13:32:02.687440260 Including conf/Linux-i386.conf
2020-02-06 13:32:02.689014550 Including conf/GNU/Linux.conf
2020-02-06 13:32:02.698201718 Including conf/Ubuntu.conf
2020-02-06 13:32:02.700722677 Including /etc/rear/local.conf
2020-02-06 13:32:02.704175285 ======================
2020-02-06 13:32:02.705457415 Running 'init' stage
2020-02-06 13:32:02.706756517 ======================
2020-02-06 13:32:02.712420956 Including init/default/005_verify_os_conf.sh
2020-02-06 13:32:02.714087720 Including init/default/010_EFISTUB_check.sh
2020-02-06 13:32:02.716085961 ERROR: EFI_STUB="" is incorrect option value pair.
==== Stack trace ====
Trace 0: /usr/sbin/rear:496 main
Trace 1: /usr/share/rear/lib/framework-functions.sh:95 SourceStage
Trace 2: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 3: /usr/share/rear/init/default/010_EFISTUB_check.sh:6 source
Message: EFI_STUB="" is incorrect option value pair.
== End stack trace ==
2020-02-06 13:32:02.722219122 Running exit tasks.
```

IF ANYONE CAN SHED SOME LIGHT ON HELPING ME RESOLVE I WOULD GREATLY APPRECIATE YOUR HELP.
THANKS,

* Workaround, if any:
Have not found a workaround.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
None yet, fresh install.

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like

verbatim content

**Comment by gozora** [comment]
Hello @kingpoop 

I'm pretty sure that EFI_STUB configuration variable is not present in ReaR 2.2 (if fist appeared in ReaR 2.5) so I'm just guessing that something went wrong during your installation...

V.

**Comment by jsmeix** [comment]
I am not an Ubuntu user so I cannot tell how to
manually install things from source on Ubuntu.

Perhaps
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
could also help to get a clean ReaR installation.

**Comment by kingpoop** [comment]
Thank you for the comments.  I fixed the issue by 
1. Removing all rear references on the filesystem
2. performing a clean install from /home/rear/rear-2.2/sudo make install
3. reran rear dump
4. got the following error: ERROR: Cannot find required programs:  bc
5. installing bc with sudo apt-get install bc
6. reruning rear dump
7. everything worked as expected.

Cheers.

**Comment by jsmeix** [comment]
@kingpoop 
thank you for your feedback that you got things working for you.
