### ISSUE TITLE
SLES15 SP1 PPCLE LPAR - rear 2.3 - ISO will not boot / kernel panic

### ISSUE THREAD

**Issue by ds2k5** [rear/rear#2336]
ReaR version:

Relax-and-Recover 2.3 / 2017-12-20

OS version:

lxtest:/etc/rear # lsb_release -a
LSB Version:	n/a
Distributor ID:	SUSE
Description:	SUSE Linux Enterprise Server 15 SP1
Release:	15.1
Codename:	n/a

ReaR configuration files: see attach please

architecture: Power9 LPAR

PPC64LE

bootloader GRUB 

Storage = SAN 

Storage layout
```
lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT
NAME                                                    KNAME     PKNAME    TRAN TYPE  FSTYPE       SIZE MOUNTPOINT
/dev/sda                                                /dev/sda                 disk                16G 
|-/dev/sda1                                             /dev/sda1 /dev/sda       part                 8M 
|-/dev/sda2                                             /dev/sda2 /dev/sda       part  xfs         14.7G 
|-/dev/sda3                                             /dev/sda3 /dev/sda       part  swap         1.3G 
`-/dev/mapper/3600a09803831424c64244f695431426b         /dev/dm-0 /dev/sda       mpath               16G 
  |-/dev/mapper/3600a09803831424c64244f695431426b-part1 /dev/dm-2 /dev/dm-0      part                 8M 
  |-/dev/mapper/3600a09803831424c64244f695431426b-part2 /dev/dm-3 /dev/dm-0      part  xfs         14.7G /
  `-/dev/mapper/3600a09803831424c64244f695431426b-part3 /dev/dm-4 /dev/dm-0      part  swap         1.3G [SWAP]
/dev/sdb                                                /dev/sdb                 disk  LVM2_member   34G 
`-/dev/mapper/3600a09803831424c64244f695431426c         /dev/dm-1 /dev/sdb       mpath LVM2_member   34G 
  `-/dev/mapper/datavg-lvrear                           /dev/dm-5 /dev/dm-1      lvm   xfs           20G 
/dev/sdc                                                /dev/sdc                 disk                16G 
|-/dev/sdc1                                             /dev/sdc1 /dev/sdc       part                 8M 
|-/dev/sdc2                                             /dev/sdc2 /dev/sdc       part  xfs         14.7G 
|-/dev/sdc3                                             /dev/sdc3 /dev/sdc       part  swap         1.3G 
`-/dev/mapper/3600a09803831424c64244f695431426b         /dev/dm-0 /dev/sdc       mpath               16G 
  |-/dev/mapper/3600a09803831424c64244f695431426b-part1 /dev/dm-2 /dev/dm-0      part                 8M 
  |-/dev/mapper/3600a09803831424c64244f695431426b-part2 /dev/dm-3 /dev/dm-0      part  xfs         14.7G /
  `-/dev/mapper/3600a09803831424c64244f695431426b-part3 /dev/dm-4 /dev/dm-0      part  swap         1.3G [SWAP]
/dev/sdd                                                /dev/sdd                 disk  LVM2_member   34G 
`-/dev/mapper/3600a09803831424c64244f695431426c         /dev/dm-1 /dev/sdd       mpath LVM2_member   34G 
  `-/dev/mapper/datavg-lvrear                           /dev/dm-5 /dev/dm-1      lvm   xfs           20G 
/dev/sr0                                                /dev/sr0                 rom   iso9660      240M 

```

* Description of the issue (ideally so that others can reproduce it):

1. create ISO with: rear mkrescue
2. map ISO to LPAR
3. boot LPAR from ISO

Workaround:  NO

Attachments: yes

rear logs:
[rear-lxtest.log](https://github.com/rear/rear/files/4248358/rear-lxtest.log)
[output.txt](https://github.com/rear/rear/files/4248359/output.txt)

Config files:
[conf-files.zip](https://github.com/rear/rear/files/4248361/conf-files.zip)

See output at boottime:

[boot.txt](https://github.com/rear/rear/files/4248369/boot.txt)

Tryed with this config too: 

/etc/rear/local.conf

```
BACKUP=TSM
OUTPUT=ISO
OUTPUT_URL=file:///mnt/rear/iso
BACKUP_URL=file:///mnt/rear/images
PXE_CONFIG_PATH=/mnt/rear/pxe
PXE_CREATE_LINKS=IP
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y
MODULES="all"
FIRMWARE_FILES="yes"

```

------------

tryed the git Version 2.5 - but the same issue
[boot_git_2_5.txt](https://github.com/rear/rear/files/4248641/boot_git_2_5.txt)

[rear-lxtest_git_2_5.log](https://github.com/rear/rear/files/4248692/rear-lxtest_git_2_5.log)

[rear_2_5_dump.txt](https://github.com/rear/rear/files/4248773/rear_2_5_dump.txt)

**Comment by jsmeix** [comment]
@ds2k5 
because you have `PXE_...` config variables in your etc/rear/local.conf
I assume you like to boot the ReaR recovery system via PXE.

I have no personal experience with booting via PXE and
even less personal experience with booting via SAN on PPC64/PPC64le.
@schabrolles is our expert regarding PPC64/PPC64le
but usually he is very busy...

I found
https://github.com/rear/rear/pull/1339
which indicates that booting the ReaR recovery system
via PXE on PPC64/PPC64le is some special thing
that requires special setup in etc/rear/local.conf
something as in our example config
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/RHEL7-PPC64LE-Multipath-PXE-GRUB.conf

FYI:
If you use the SUSE btrfs structure on other machines
you need additionally special SUSE btrfs related things
in etc/rear/local.conf something as in our example config
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

**Comment by jsmeix** [comment]
@ds2k5 
FYI in general regarding
booting the ReaR ISO image on non PC compatible architectures
see the section "Non PC compatible architectures" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by abbbi** [comment]
hi,

according to your disk layout information you root partition resides on a multipath
SAN configuration,so  you need to at least enable BOOT_OVER_SAN option in REAR config file. This wont solve your boot problems but as soon you have figured that you will run into other troubles during disk layout recovery if you havent activated that option.

Second i can see some PXE options which i dont know if they are related, but according
to the kernel command line it seems the image tries to find its root fs mappend within initrd:

command line: BOOT_IMAGE=/kernel root=/dev/ram0 selinux=0

but fails to boot:


Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0

please check the size of the initrd that was created during backup within the ISO image.
On PowerPc there are some known issues if the initrd becomes too big, then it mostly helps to set the compresion mode to LZMA witihn REAR config file prior to mkrescue.

**Comment by jsmeix** [comment]
In particular an explicit `FIRMWARE_FILES="yes"`
makes the ReaR recovery system initrd rather big,
cf. the sections about `FIRMWARE_FILES`
and `REAR_INITRD_COMPRESSION` in default.conf
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf

The related issues at that time have been
https://github.com/rear/rear/issues/1142
and
https://github.com/rear/rear/issues/1216

I don't know how far that things apply to PPC64LE Power9 LPAR.

**Comment by jsmeix** [comment]
Because "no news is good news" I assume the root cause was found
why it is "Unable to mount root fs" in this particular case
so the issue can be closed.
