### ISSUE TITLE
OPALPBA: cannot change password on multiple self-encrypting drives at once

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2349]
* ReaR version: Relax-and-Recover 2.5 / Git
* System architecture: x86
* Description of the issue:

`rear opaladmin changePW` (when used without any extra argument or with multiple arguments) is meant to change the disk password on multiple self-encrypting drives in a single invocation. However, it stops after successfully changing the password on the first drive. The password of subsequent drives remains unchanged.

**Comment by jsmeix** [comment]
With
https://github.com/rear/rear/pull/2350
merged this issue is be fixed.
