### ISSUE TITLE
rear mkopalpba fails: ERROR: The BACKUP method 'OPALPBA' is not known to ReaR.

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2351]
* ReaR version: Relax-and-Recover 2.5 / Git
* System architecture: x86
* Description of the issue:

`rear mkopalpba` fails with
```
ERROR: The BACKUP method 'OPALPBA' is not known to ReaR.
Some latest log messages since the last called script 035_valid_backup_methods.sh:
  2020-03-30 23:05:23.788858362 Including prep/default/035_valid_backup_methods.sh
```

* Possibly related to: 8eb72c1d845d2b91fa76f18d47c74454ed5432ec

* Note: `usr/share/rear/lib/mkopalpba-workflow.sh` contains:
```
    # Change workflow components before SourceStage jumps into action:
    # This makes the 'mkopalpba' workflow work with the configuration for the 'mkrescue' workflow,
    # yet produce a different outcome (the PBA instead of the rescue image) with it own set of
    # component scripts.
    BACKUP=OPALPBA  # There is no backup inside the PBA, so abuse the BACKUP component to create the PBA
```

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2353 merged
this issue is fixed - together with the commit
https://github.com/rear/rear/commit/e98c8adcd75d043672bbed9564bedef377d9639e

**Comment by jsmeix** [comment]
With
https://github.com/rear/rear/commit/fea58ee2775376ac7d2c6dc3fdd176a9519357a3
and
https://github.com/rear/rear/commit/161be72fcd89f2af23f49f32c21d2b049aae803d
I consider this issue "100% fully fixed".

Now it's knocking-off time and I am hungry, cf.
https://github.com/rear/rear/pull/2353#issuecomment-606585731
