### ISSUE TITLE
Resizing /boot using REAR

### ISSUE THREAD

**Issue by IT-Guy-1973** [rear/rear#2357]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):

Hello REAR community,

We have VM's running Linux where we need to resize (increase the size) the /boot partition. 

/boot is in /dev/sda1
LVM disk is /dev/sda2

Our Plan: Create a new VM with a larger root disk and restore the REAR backup by editing the diskrestore.sh file.

Questions:

1. In the restore screen rear shell can we enable ssh login? It is very difficult to edit files in the VMWARE console. So if we can have a way to ssh using putty to this system it will be great.

2. Can we resize the disk layout and increase the /dev/sda1 using this method in the first place?

Thank you,
Regards,
Niranjan 

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by IT-Guy-1973** [comment]
Hello Support,

I was able to resize boot using REAR. Wow ... That is something I have never seen in the past. REAR is great. So I got the answer to my second question. 

Regards,
Niranjan

**Comment by gdha** [comment]
@IT-Guy-1973 Answer to the 1st question is defining `SSH_ROOT_PASSWORD=?????` in your `/etc/rear/local.conf` file. In the rescue image a **sshd** will be started this variable has been defined.

**Comment by IT-Guy-1973** [comment]
I will try this @gdha and thank you so much.

**Comment by IT-Guy-1973** [comment]
I was able to test this and it works! Thank you, @gdha
