### ISSUE TITLE
Booting systems using REAR backup

### ISSUE THREAD

**Issue by IT-Guy-1973** [rear/rear#2358]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):

Hello REAR community,

We are in the process of restoring REAR backups to new VM's. The way we do REAR backups now is by using an NFS server. Once we do the backup we have to copy the "vmname.ISO" to the ESXI datastore and point the VM to boot from the ISO. Is there a way we can avoid this part and maybe do a network boot of the new VM from the REAR backup? 

Why I ask this is copying the ISO from the NFS server to ESXi involves our Compute team and that is not fun.

Regards,
Niranjan

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by gdha** [comment]
@IT-Guy-1973  PXE is supported with ReaR. For VMs within ESXi servers you have to be careful that the VM is located in the same VLAN otherwise PXE broadcast won't arrive at the proper DHCP/PXE daemon.
An example you will find at https://gist.github.com/gdha/b37878f3dc327da9351878f7bf3a1d4f

**Comment by IT-Guy-1973** [comment]
Hello gdha ,

So from the link, you sent me I see the following I need to include in my site.conf file: I will check to adjust the settings with my settings and see how it goes. 

OUTPUT=PXE
OUTPUT_PREFIX_PXE=$HOSTNAME

BACKUP=NETFS
BACKUP_URL=nfs://192.168.33.15/export/nfs

PXE_TFTP_URL=nfs://10.0.2.2/root/.config/VirtualBox/TFTP
PXE_CONFIG_URL=nfs://10.0.2.2/root/.config/VirtualBox/TFTP/pxelinux.cfg
PXE_RECOVER_MODE="unattended"
PXE_CREATE_LINKS="IP"

USE_STATIC_NETWORKING=y
KERNEL_CMDLINE="$KERNEL_CMDLINE net.ifnames=0"

FIRMWARE_FILES=( 'no' )

SSH_ROOT_PASSWORD="vagrant"

TIMESYNC=NTPDATE
TIMESYNC_SOURCE=0.pool.ntp.org

Thank you.
Regards,
Niranjan
