### ISSUE TITLE
"rear mkrescue" fails to modify sshd_config in recovery system if it is a symbolic link

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2360]
* ReaR version: Relax-and-Recover 2.5 / Git
* System architecture: x86
* Description of the issue:

If `etc/ssh/sshd_config` is a symbolic link, `build/default/500_ssh_setup.sh` will fail to apply patches:

```
2020-04-14 15:07:30.912377983 Including build/default/500_ssh_setup.sh
sed: can't read /tmp/rear.4sZcgsBNHi0t1lc/rootfs/etc/ssh/sshd_config: No such file or directory
sed: can't read /tmp/rear.4sZcgsBNHi0t1lc/rootfs/etc/ssh/sshd_config: No such file or directory
sed: can't read /tmp/rear.4sZcgsBNHi0t1lc/rootfs/etc/ssh/sshd_config: No such file or directory
```

Symbolic links will eventually get resolved to target files in `build/default/985_fix_broken_links.sh` but that's too late.

* Suggestion (tested successfully): move `985_fix_broken_links.sh` to `490_fix_broken_links.sh`.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2361 merged
this issue is fixed.

@OliverO2 
thank you for your issue report and your fix!
