### ISSUE TITLE
Add auto-detection of DHCP client with systemd-networkd

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2375]
* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.5 / Git
* OS version: Ubuntu 18.04 Server and others
* Description of the issue:
    
    ReaR can auto-detect a DHCP client on the original system and configure the rescue system accordingly. Currently, the auto-detection relies on finding a running DHCP client process.
    
    Ubuntu 18.04 Server by default uses [systemd\-networkd(8)](http://manpages.ubuntu.com/manpages/bionic/en/man8/systemd-networkd.8.html), which has a built-in DHCP client. ReaR should detect if this is enabled (cf. [systemd\.network(5)](http://manpages.ubuntu.com/manpages/bionic/en/man5/systemd.network.5.html)) and configure the rescue system accordingly.
    
    Note that Ubuntu 18.04 Desktop by default still uses _NetworkManager_ which fires up _dhclient_. This was already correctly detected by ReaR before.
    
    Also note that Ubuntu 18.04 by default uses [netplan(5)](http://manpages.ubuntu.com/manpages/bionic/en/man5/netplan.5.html) to configure the networking setup. Netplan uses a YAML configuration to generate the respective configuration files for _systemd-networkd_ or _NetworkManager_. Yet, these generated configurations can be overridden:
    
    In case of _systemd-networkd_, if _netplan_ had generated a configuration file `/run/systemd/network/10-netplan-eno1.network`, it could be overridden by creating a configuration file `/etc/systemd/network/10-netplan-eno1.network`.

* Note: PR upcoming

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2376 merged
this issue is done.
