### ISSUE TITLE
mkisofs: Bad Option '-e' (error -1 BADFLAG) on SLES15 SP1

### ISSUE THREAD

**Issue by pewo** [rear/rear#2379]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.5-git.0.6c2f857.unknown / 2020-04-20

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): SLES 15 SP1
os.conf: OS_VENDOR=SUSE_LINUX  / OS_VERSION=12

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): X86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):  SSD

* Description of the issue (ideally so that others can reproduce it):

When running "rear -v mkrescue" the script exists with an error message:
ERROR: Could not create ISO image (with /usr/bin/mkisofs)
A snippet from the logfile:
....Starting '/usr/bin/mkisofs'
....Making ISO image
....Including ISO UEFI boot (as triggered by USING_UEFI_BOOTLOADER=1)
Bad Option '-e' (error -1 BADFLAG)
Usage......

* Workaround, if any: N/A :-(

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jsmeix** [comment]
See default.conf
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf
for ISO and UEFI related settings.
