### ISSUE TITLE
ReaR uses NFS4 with AIX mount

### ISSUE THREAD

**Issue by mahmoudrafat** [rear/rear#2398]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.3

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
SUSE Linux Enterprise Server 12 SP3

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
OUTPUT_URL=nfs://IP/share
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://IP/share
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default 
BACKUP_PROG_INCLUDE=( '/var/lib/mysql/*' '/var/tmp/*' '/var/spool/*' '/var/lib/mailman/*' '/boot/grub2/powerpc-ieee1275/*' '/var/opt/*' '/var/cache/*' '/var/lib/machines/*' '/srv/*' '/var/lib/mariadb/*' '/tmp/*' '/var/lib/pgsql/*' '/opt/*' '/var/lib/libvirt/images/*' '/usr/local/*' '/var/log/*' '/var/lib/named/*' '/home/*' )
POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
EXCLUDE_MOUNTPOINTS=( '/MEG-sysbackup/*' '/run/user/*' '/sapmnt' '/usr/sap' )
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
SUSE on IBM power

* Description of the issue (ideally so that others can reproduce it):

I share a directory from AIX machine to use it as backup for ReaR,
i can mount it using command
```
mount -o vers=3 ip:/share /mount_point
```
but when i using ReaR it seems that it use NFS Version=4
and produce error. like below.

The log file in /var/log/rear/xxx.log
```
mkdir: created directory '/tmp/rear.rjbDv6M41RuA6rS/outputfs'
2020-05-14 16:16:38.263945559 Mounting with 'mount -v -t nfs -o rw,noatime IP:/share /tmp/rear.rjbDv6M41RuA6rS/outputfs'
mount.nfs: mount(2): Remote I/O error
mount.nfs: Remote I/O error
```

Can anyone help me?
thanks..

**Comment by gozora** [comment]
Hi @mahmoudrafat,

NFS version 4 is now Linux default, so it is not ReaR making trouble.
Try to add `BACKUP_OPTIONS="nfsvers=3,nolock"` to your _local.conf_ (_site.conf_).

V.

**Comment by gozora** [comment]
Hmm, now reading more carefully I see that you've already did that.

Can you provide full _/var/log/rear/rear.log_, so we can see what is going on ?

V.

**Comment by jsmeix** [comment]
@mahmoudrafat 
more precisely we need the full debug log, i.e. what you get
with `rear -d -D mkrescue` or `rear -d -D mkbackup`, see also
"Debugging issues with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by mahmoudrafat** [comment]
[rear-mag-bw-dev.log](https://github.com/rear/rear/files/4630297/rear-mag-bw-dev.log)
Hi, Thanks for your response,
i attached the error part only because the log is too big more than 1000 page!!
when i mount the shared direcotory with "mount -o nfsver=3 IP/share" it is ok.
may i change the rear mount command to use that command instead of mount -v -t nfs -o rw,noatime" ?

**Comment by gozora** [comment]
Hi @mahmoudrafat,

> i attached the error part only because the log is too big more than 1000 page!!

You can attach files directly to this conversation by drag-n-drop, no need to copy + paste file content.

> may i change the rear mount command to use that command instead of mount -v -t nfs -o rw,noatime" ?

You can, this right is granted to you by GPL ;-) 

I'm just wondering why `BACKUP_OPTIONS` does not work for you, because content of `BACKUP_OPTIONS` is normally passed to `mount` command by ReaR, so I'd still like to see output from `rear -d -D mkrescue` as @jsmeix proposed in https://github.com/rear/rear/issues/2398#issuecomment-628702055.

V.

**Comment by mahmoudrafat** [comment]
[rear-mag-bw-dev.log](https://github.com/rear/rear/files/4634623/rear-mag-bw-dev.log)
Hi, sorry for late due to time zone,
I uploaded the log file for your review.

> You can, this right is granted to you by GPL ;-)

Can you please explain how to do that?

Thanks.

**Comment by gozora** [comment]
Hmm, I always thought that if `OUTPUT_OPTIONS` is not explicitly set, it somehow takes over content from `BACKUP_OPTIONS`, but this is only true if following condition https://github.com/rear/rear/blob/f6e9fbca381ffd7ba14cb3685c64ecad3f1b9585/usr/share/rear/prep/default/020_translate_url.sh#L47-L52
is matched.

@mahmoudrafat can you please add following line to your _local.conf_ and try to re-run `rear mkbackup`

```
OUTPUT_OPTIONS="nfsvers=3,nolock" 
```

V.

**Comment by mahmoudrafat** [comment]
@gozora 
I did what you say and it make ISO image but the size is only 92M for ISO and 166MB for tar file, that doesn't make sense  because the used space for the root is 22GB!

![rear2](https://user-images.githubusercontent.com/34544193/82104704-3dcbd800-9718-11ea-9370-20a2fc9b2a51.png)

![rear](https://user-images.githubusercontent.com/34544193/82104703-3c9aab00-9718-11ea-80c3-afc3013c2e53.png)

**Comment by schabrolles** [comment]
@mahmoudrafat 

I think you forget to add some specific option needed by Suse when BTRFS and subvolume are used. Try to use the following as `local.conf`

```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
OUPUT_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://192.168.122.1/nfs
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"
PROGRESS_MODE=plain
PROGRESS_WAIT_SECONDS=3
KEEP_BUILD_DIR="yes"
FIRMWARE_FILES=( no )
REAR_INITRD_COMPRESSION=lzma

#SLES BTRFS specific
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )

for subvol in $(findmnt -n -r -t btrfs | cut -d ' ' -f 1 | grep -v '^/$' | egrep -v 'snapshots|crash') ; do
        BACKUP_PROG_INCLUDE=( "${BACKUP_PROG_INCLUDE[@]}" "$subvol" )
done

POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
```

**Comment by mahmoudrafat** [comment]
@schabrolles 
I used the example from the docs and i don't think this is the problem because i made it on VM machine with the same configuration.
the problem with NFS share from AIX to SUSE.

**Comment by schabrolles** [comment]
@mahmoudrafat, compare to the one included into the doc I added `OUPUT_OPTIONS="nfsvers=3,nolock"` (proposed by @gozora) ... 

Although, did you apply the following command on the AIX machine ? `nfso nfs_use_reserved_ports=1`

**Comment by mahmoudrafat** [comment]
@schabrolles, I did what @gozora  Said and added `OUPUT_OPTIONS="nfsvers=3,nolock"`
But it make an 150MB ISO only, see the previous comment.

> Although, did you apply the following command on the AIX machine ?

I will check it.

**Comment by jsmeix** [comment]
Now I see why
```
OUTPUT_OPTIONS="nfsvers=3,nolock"
```
(it is `OUTPUT_OPTIONS` not `OUPUT_OPTIONS`)
is needed when one has
```
OUTPUT=ISO
OUTPUT_URL=nfs://IP/share
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://IP/share
```
i.e. when OUTPUT_URL is explicitly specified:

This is because prep/default/020_translate_url.sh contains
```
if [[ -z "$OUTPUT_OPTIONS" ]] ; then
    if [[ -z "$OUTPUT_URL" && -z "$OUTPUT_MOUNTCMD" ]] ; then
        ### There can be cases where it's intentionally empty.
        OUTPUT_OPTIONS=$BACKUP_OPTIONS
    fi
fi
```
https://github.com/rear/rear/blob/master/usr/share/rear/prep/default/020_translate_url.sh#L48
so OUTPUT_OPTIONS inherits from BACKUP_OPTIONS
only if OUTPUT_URL is not explicitly specified.

**Comment by jsmeix** [comment]
@mahmoudrafat 
to see what actually happens while the backup is made
inspect your `backup.log` file.
For debug information in the log file
you must run rear with debug logging enabled
like `rear -d -D mkrescue` or `rear -d -D mkbackup`

**Comment by mahmoudrafat** [comment]
Hi,
Ok i will try what you said and apply it after the holidays ends (we have one week off).
Many thanks.

**Comment by mahmoudrafat** [comment]
Hi Again,
Today i test the recover but it stuck at this point i don't know wheres the problem is because small size of backup or something else, i investigated the log file but didn't find anything wrong.
does anyone face the same problem?
@jsmeix  

![rear](https://user-images.githubusercontent.com/34544193/83755026-3a6ba280-a66d-11ea-80d8-34de8831e92c.png)

**Comment by jsmeix** [comment]
@mahmoudrafat 
at this point "rear recover" is about to recreate the disk storage layout
which happens before the backup of the files is restored
so this new issue in your recent
https://github.com/rear/rear/issues/2398#issuecomment-638808558
has nothing to do with what is in the backup.

To get an initial basic understanding about
your particular actual disk storage layout and
what "rear mkrescue/mkbackup" finds out about it
we need the output of
```
lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT
```
or if that is not possible on SLES12 the output of
```
lsblk -io NAME,KNAME,FSTYPE,SIZE,MOUNTPOINT
```
or if that is also not possible at least the output of plain
```
lsblk
```
and additionally we need your particular
```
var/lib/rear/layout/disklayout.conf
```
file.

Because you use ReaR 2.3 which is meanwhile rather old
(from our ReaR upstream developer's point of view) and
because we at ReaR upstream do not support old ReaR releases
I would seriously recommend to try out our current ReaR upstream
GitHub master code from within a separated directory as a test
to find out if things work better with our current ReaR upstream
master code compared to your installed ReaR version,
see the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
how to do that.
To run `git clone https://github.com/rear/rear.git` you need
the RPM package `git-core` that provides `/usr/bin/git`.

**Comment by mahmoudrafat** [comment]
Thanks For your help, i made the backup and restore it without any problem, here is the final config file for your attention.
if there is no question you can close it.
Thanks again for your great support.
"/etc/rear/local.conf" file
`OUTPUT=ISO
OUTPUT_URL=nfs://IP/Share
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://IP/Share
OUTPUT_OPTIONS="nfsvers=3,nolock"
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
BACKUP_PROG_INCLUDE=( '/var/lib/mysql/*' '/var/tmp/*' '/var/spool/*' '/var/lib/mailman/*' '/boot/grub2/powerpc-ieee1275/*' '/var/opt/*' '/var/cache/*' '/var/lib/machines/*' '/srv/*' '/var/lib/mariadb/*' '/tmp/*' '/var/lib/pgsql/*' '/opt/*' '/var/lib/libvirt/images/*' '/usr/local/*' '/var/log/*' '/var/lib/named/*' '/home/*' )
POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
EXCLUDE_MOUNTPOINTS=( '/POint/*' )
EXCLUDE_VG=( 'VG_NAME' )
AUTOEXCLUDE_MULTIPATH=n`

**Comment by jsmeix** [comment]
@mahmoudrafat 
thank you for your feedeback that you got things working for your case
and for your etc/rear/local.conf that shows how you made it working.
