### ISSUE TITLE
RAWDISK output fails to boot on Ubuntu >=18.04.4 using Grub 2 + UEFI without Secure Boot

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2419]
* ReaR version: Relax-and-Recover 2.6 / Git
* OS version: Ubuntu 18.04.4 LTS, Ubuntu 20.04 LTS
* System architecture: x86_64
* Firmware and bootloader: UEFI, Grub 2 without Secure Boot
* Description of the issue:

If Grub 2 is used to boot a UEFI rescue medium created on Ubuntu 18.04 or 20.04 with RAWDISK output, which was **not** configured for Secure Boot, the following messages appear:
```text
error: file `/EFI/BOOT/x86_64/linuxefi.mod´ not found.
error: you need to load the kernel first.
```

This appears to be a regression, possibly caused by a change in Ubuntu's Grub packaging: According to this [mailing list post](https://lists.gnu.org/archive/html/help-grub/2016-08/msg00014.html), `linuxefi.mod` is a distribution-specific module.

NOTES:

* UEFI secure boot (also done via Grub 2) is not affected.
* UEFI booting via syslinux (another RAWDISK output option) is also not affected.

PR upcoming.

**Comment by jsmeix** [comment]
@OliverO2  @gozora @pcahyna 
could you have a look if UEFI booting the recovery system
for other output methods in particular for `OUTPUT=ISO`
cf. https://github.com/rear/rear/pull/2293
could be also affected by such distribution-specific modules?

**Comment by OliverO2** [comment]
UEFI-booting from an ISO image created on Ubuntu 18.04.4 LTS with `OUTPUT=ISO` works.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2420 merged
this issue is fixed.

@OliverO2 
thank you for testing ReaR on Ubuntu 18.04 and 20.04,
for your issue reports, and especially for your prompt fixes!

**Comment by OliverO2** [comment]
@jsmeix As always, thanks for reviewing and coordinating!
