### ISSUE TITLE
How to interrupt the boot process using rescue image to manually set IP address when booting in UEFI mode?

### ISSUE THREAD

**Issue by bobbysch** [rear/rear#2430]
When using BIOS, I had the option to interrupt the boot process (by pressing Tab key) to enter
define a fixed IP address when you boot up from the rescue image.
But this option is not available in UEFI mode. In this mode, you can edit the grub menu with "e" key to interact with kernel parameters and there is no do what I need to.

The only work around is to chose "One Time Boot" and opt for BIOS, but because my HP hardware allows me to do that, not sure if other servers vendors offer that option.

**Comment by gozora** [comment]
Pressing "e" in Grub menu and add following works fine for me:
![Screenshot from 2020-06-17 20-42-48](https://user-images.githubusercontent.com/12116358/84937098-8c83dd80-b0db-11ea-8997-6ed4ab9c4a53.png)

Result:
![Screenshot from 2020-06-17 20-44-28](https://user-images.githubusercontent.com/12116358/84937113-91e12800-b0db-11ea-8164-b34c664968c4.png)

V.

**Comment by bobbysch** [comment]
Thanks for your reply, I was not aware it works the same way.

**Comment by jsmeix** [comment]
@bobbysch 
FYI a side note:

If you know the fixed IP address of the ReaR recovery system in advance
you could specify that in etc/rear/local.conf via something like
```
NETWORKING_PREPARATION_COMMANDS=( 'ip addr add 192.168.100.2/24 dev eth0' 'ip link set dev eth0 up' 'ip route add default via 192.168.100.1' 'return' )
```
see the NETWORKING_PREPARATION_COMMANDS description
in usr/share/rear/conf/default.conf
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L2763
