### ISSUE TITLE
rear-2.6 repo added to RHEL 8/ SLES15 repositories?

### ISSUE THREAD

**Issue by gdha** [rear/rear#2433]
* ReaR version ("/usr/sbin/rear -V"): 2.6 stable

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): RHEL 8 / SLES 15

* Description of the issue (ideally so that others can reproduce it):
Are there plans to add `rear-2.6` version into the repositories of RHEL8 and SLES15?
- question raised to @rmetrich  @pcahyna @yontalcar for RHEL?
- and question also raised to @jsmeix for SLES 15?

**Comment by jsmeix** [comment]
@gdha 
I assume you are asking about adding ReaR 2.6
to SUSE's official SLE 15 repositories which means
to officially provide and support ReaR 2.6 in SLE-HA-15
cf. the section "SUSE support for Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

Adding a package to SLE is a rather complicated task.
Currently it is not planned to add ReaR 2.6 to SLE-HA.
Things could change if SLE-HA customers need ReaR 2.6.

**Comment by gdha** [comment]
@rmetrich @pcahyna @yontalcar And what about RHEL?
