### ISSUE TITLE
Rubrik CDM module fails to restore from remote cluster on newer Rubrik releases

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2441]
* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
# more /etc/rear/local.conf

OUTPUT=ISO
BACKUP=CDM
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

VMware VM.

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86-64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

N/A

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

N/A

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

N/A

* Description of the issue (ideally so that others can reproduce it):

When running `rear recover` with the CDM module the user is asked if they are recovering from the same Rubrik cluster. If they enter `n` and then type in the IP address of the new CDM cluster the recovery fails. The failure message indicates that the tar file cannot be unzipped.

The source of this problem is that the name of the tar file that is being downloaded has changed in Rubrik CDM v5.1.

* Workaround, if any:

Edit `/usr/share/rear/verify/CDM/default/410_use_replica_cdm_cluster_cert.sh` and change:

`CDM_SUNOS_TAR=rubrik-agent-sunos5.10.sparc.tar.gz`

to

`CDM_SUNOS_TAR=rubrik-agent-solaris.sparc.tar.gz`

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

```
ERROR: Could not extract rubrik-agent-sunos5.10.sparc.tar.gz
gzip: stdin: not in gzip format
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
```

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2445 merged
this issue should be somewhat fixed, cf.
https://github.com/rear/rear/pull/2445#issuecomment-662413240

A better solution would be in default.conf a new array like
```
CMD_RBS_AGENT_FILES=( "rubrik-agent-solaris.sparc.tar.gz" "rubrik-agent-sunos5.10.sparc.tar.gz" )
```
and then in verify/CDM/default/410_use_replica_cdm_cluster_cert.sh code like
```
local cdm_rbs_agent_file
for cdm_rbs_agent_file in "${CDM_RBS_AGENT_FILES[@]}'' ; do
        curl $v -fskLOJ https://$CDM_CLUSTER_IP/connector/$cdm_rbs_agent_file && break
done
```
