### ISSUE TITLE
Adding host to Rubrik gives error: SSL handshake failed while connecting to <IP_Address>:12801. Reason: tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2442]
* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
$ cat /etc/rear/local.conf
OUTPUT=ISO
BACKUP=CDM
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

N/A

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

N/A

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

N/A

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

N/A

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

N/A

* Description of the issue (ideally so that others can reproduce it):

Run `rear recover` and select a new Rubrik Cluster. After getting to the `rear>` prompt try to register the host with Rubrik. 

* Workaround, if any:

None

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

```
SSL handshake failed while connecting to <IP_Address>:12801. Reason: tlsv1 alert unknown ca
```

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2445 merged
this issue should be fixed.
