### ISSUE TITLE
FOG Project as PXE Boot Tool and REAR Rescue ISO

### ISSUE THREAD

**Issue by matekubi** [rear/rear#2446]
I want to add REAR Rescue ISO to FOG Project.
I want PXE with ISO or PXE files created by REAR. 

Clients are able to connect to PXE server, download kernel, download initrd.cgz
and then start kernel: then I was facing the issue
```
Kernel panic - not syncing: VFS: Unable to mount root fs on unknow-block(0,0)
```

When I build REAR Backup Rescue I can select as output PXE and ISO build:

1) PXE Option:
Then I have:
kernel and initrd.cgz file + config file:
```
default hd
prompt 1
timeout 300

label hd
    localboot -1
    say ENTER - boot local hard disk
    say --------------------------------------------------------------------------------
    display /localhost.message
    say ----------------------------------------------------------
    say rear = disaster recover this system with Relax-and-Recover
label rear
    kernel /localhost.kernel
    append initrd=/localhost.initrd.cgz root=/dev/ram0 vga=normal rw  selinux=0 
```

2) ISO Option: 

Then I have this content in ISO:
```
EFI G:\EFI
boot G:\boot
isolinux G:\isolinux
BOOT G:\EFI\BOOT
fonts G:\EFI\BOOT\fonts
locale G:\EFI\BOOT\locale
BOOTX64.efi G:\EFI\BOOT\BOOTX64.efi
embedded_grub.cfg G:\EFI\BOOT\embedded_grub.cfg
grub.cfg G:\EFI\BOOT\grub.cfg
grubx64.efi G:\EFI\BOOT\grubx64.efi
grub G:\boot\grub
efiboot.img G:\boot\efiboot.img
grub.cfg G:\boot\grub\grub.cfg
boot.cat G:\isolinux\boot.cat
chain.c32 G:\isolinux\chain.c32
hdt.c32 G:\isolinux\hdt.c32
initrd.cgz G:\isolinux\initrd.cgz
isolinux.bin G:\isolinux\isolinux.bin
isolinux.cfg G:\isolinux\isolinux.cfg
kernel G:\isolinux\kernel
ldlinux.c32 G:\isolinux\ldlinux.c32
libcom32.c32 G:\isolinux\libcom32.c32
libgpl.c32 G:\isolinux\libgpl.c32
libmenu.c32 G:\isolinux\libmenu.c32
libutil.c32 G:\isolinux\libutil.c32
menu.c32 G:\isolinux\menu.c32
message G:\isolinux\message
pci.ids G:\isolinux\pci.ids
rear.help G:\isolinux\rear.help
reboot.c32 G:\isolinux\reboot.c32
vesamenu.c32 G:\isolinux\vesamenu.c32
```

**Comment by matekubi** [comment]
Anyone use REAR by PXE\TFTP solution and can help with this? I have no more idea what can be wrong.

**Comment by gdha** [comment]
@matekubi Is this related to UEFI PXE booting perhaps - see related issue #2359 ?

**Comment by jsmeix** [comment]
@matekubi 
I know nothing about "FOG Project" https://fogproject.org/
so I cannot help with issues that are specific to that
and I am not at all an expert in PXE related areas.

In general when you submit a new issue
e.g. via the "New issue" button at
https://github.com/rear/rear/issues
that leads to
https://github.com/rear/rear/issues/new
you get this shown
https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md

Regardless whether or not I know about certain specific things
I cannot do anything when the basic information is missing that is needed
to get some initial understanding about your system and your environment.

**Comment by matekubi** [comment]
Sorry about the lack of details. 

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Latest

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Centos 8.1

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):


* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Virutal on Hyper-V, Virtualbox,

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
66bit

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
Local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
N/A

* Description of the issue (ideally so that others can reproduce it):

At this moment I just need to run REAR by iPXE. It looks like that I have problems with boot commands for kernel.
I've used option PXE and its generated kernel + boot menu + initrd.cgz. 
I want add it and boot by iPXE with UEFI machine (virtual or physical). 

I've got the error after loading kernel and initrd.cgz:
Kernel panic - not syncing VFS: unable to mount root fs on unknown block(0,0).

==============
kernel tftp://${fog-ip}/kernel
initrd tftp://${fog-ip}/initrd.cgz
imgargs initrd=initrd.cgz root=/dev/ram0
boot || goto failed
goto start
======================

From this post: https://github.com/rear/rear/issues/2359 it looks like that REAR generated file for BIOS, not UEFI. 
How to get commands for UEFI? I'm using IPXE (right now from FOG system, but on clear IPXE issue is the same). 



* Workaround, if any:
n/A

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```

**Comment by matekubi** [comment]
Update:

kernel tftp://${fog-ip}/vmlinuz
initrd tftp://${fog-ip}/initrd.img
imgargs vmlinuz initrd=initrd.img
boot || goto failed
goto start

I've changed files KERNEL from REAR which was created by PXE option to VMLINUZ from CentOS ISO and the same for initrd.cgz to initrd.img from clear ISO with Centos and I was able to boot. 

Something is wrong with kernel or initrd.cgz created by REAR...
