### ISSUE TITLE
How to stop REAR from bringing up the IP interface during migration

### ISSUE THREAD

**Issue by IT-Guy-1973** [rear/rear#2447]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
```
# rear -V
Relax-and-Recover 2.4 / 2018-06-21
```

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
```

* Description of the issue (ideally so that others can reproduce it):

We are migrating systems in the same network while the source system is running. When we start the REAR restore of the source systems it comes up to the rear menus. When we type "ip a s" it shows the exact same IP of the source server. We at this point puts in a new IP and move forward. However, during the time the source IP is there nobody can log into the original source server as there are two identical IP's in the same network.

How can we make the system come up without any IP address?

I saw the below option -

/etc/rear/mappings/ip_addresses

But I am more comfortable with having no IP when the system comes up.

Regards,
Niranjan

**Comment by jsmeix** [comment]
See `man rear` that reads
```
RESCUE IMAGE KERNEL COMMAND LINE OPTIONS
...
ip= nm= netdev= gw=

If IP address plus optionally netmask (default 255.255.255.0),
network device (default eth0), and a default gateway
are specified only that single network device is set up.
Example:
ip=192.168.100.2 nm=255.255.255.0 netdev=eth0 gw=192.168.100.1

noip
Skip network devices setup by the rescue system start up scripts
(overrides ip= nm= netdev= gw=).
```
https://github.com/rear/rear/blob/master/doc/rear.8.adoc

Additionally
see `NETWORKING_PREPARATION_COMMANDS` in default.conf
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L2771

Alternatively
use `USE_DHCLIENT=yes` in your etc/rear/local.conf - see default.conf
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L2735
