### ISSUE TITLE
REAR with EFI USB - ESP too small (200 MiB)

### ISSUE THREAD

**Issue by matekubi** [rear/rear#2454]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Latest

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Centos 8.2

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=USB
BACKUP=NTFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
USING_UEFI_BOOTLOADER=1
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
X86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS and UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
N/A

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME                    KNAME     PKNAME    TRAN   TYPE FSTYPE        SIZE MOUNTPOINT
/dev/sda                /dev/sda            usb    disk             115.6G
`-/dev/sda1             /dev/sda1 /dev/sda         part vfat        115.6G /run/media/root/CENTOS-8-2-
/dev/sdb                /dev/sdb            usb    disk              57.8G
|-/dev/sdb1             /dev/sdb1 /dev/sdb         part vfat          200M /tmp/rear-efi.ys5r3
`-/dev/sdb2             /dev/sdb2 /dev/sdb         part ext3         57.6G
/dev/sdc                /dev/sdc            sata   disk             238.5G
|-/dev/sdc1             /dev/sdc1 /dev/sdc         part vfat          600M /boot/efi
|-/dev/sdc2             /dev/sdc2 /dev/sdc         part ext4            1G /boot
`-/dev/sdc3             /dev/sdc3 /dev/sdc         part LVM2_member 236.9G
  |-/dev/mapper/cl-root /dev/dm-0 /dev/sdc3        lvm  xfs            50G /
  |-/dev/mapper/cl-swap /dev/dm-1 /dev/sdc3        lvm  swap          7.9G [SWAP]
  `-/dev/mapper/cl-home /dev/dm-2 /dev/sdc3        lvm  xfs         179.1G /home
```

* Description of the issue (ideally so that others can reproduce it):
During backup creation I was requested to create USB with EFI.
I did this with some paramter.
Now, I create backup to this USB stick and what I can see
REAR mounts EFI partition which is 200M
and throw error during execution about lack of space.

**Comment by gozora** [comment]
Did you used `rear format` to setup your usb disk?

V.

**Comment by gozora** [comment]
You can increase size of efi partition by using USB_UEFI_PART_SIZE parameter.

V.

**Comment by matekubi** [comment]
Yes, I used rear format for disk preparation.

Ok. I can use this parameter to increase size.

I thought that my EFI partition is good and REAR has some bug that it saves backup or other files to EFI partition instead of second large partition. But if my system needs a larger EFI partition that it is OK to change the size to a custom one.

**Comment by jsmeix** [comment]
I do not understand how with "latest" ReaR version
where default.conf contains
```
USB_UEFI_PART_SIZE="400"
```
one gets only a 200 MiB EFI partition by "rear format"?

**Comment by jsmeix** [comment]
Via
https://github.com/rear/rear/commit/34e25eb11fb68689d44b8f2012249e88f471ab9a
I fixed the default value when prompting user for size of EFI system partition on USB disk
if no valid value is specified but with default.conf `USB_UEFI_PART_SIZE="400"`
this case does not happen by default so there is still my question in
https://github.com/rear/rear/issues/2454#issuecomment-654053769

**Comment by jsmeix** [comment]
I assume with sufficient big USB_UEFI_PART_SIZE setting
this issue can get solved so that I can close it hereby.

**Comment by matekubi** [comment]
Yes, after this change everything works fine. Thank you!!!

**Comment by jsmeix** [comment]
You are welcome!
Thanks for your explicit confirmation that it actually works for you this way.
