### ISSUE TITLE
Set "dd ... bs=1M" blocksize for faster NETFS recovery

### ISSUE THREAD

**Issue by dsamx** [rear/rear#2458]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4 / Git
This is actually the SLES15 SP1 package rear23a-2.3.a-9.6.1.x86_64

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
AUTOSHRINK_DISK_SIZE_LIMIT_PERCENTAGE=80

OUTPUT=ISO
KEEP_OLD_OUTPUT_COPY=y

BACKUP=NETFS
BACKUP_URL=cifs://....
BACKUP_OPTIONS="cred=/etc/rear/cifs"
BACKUP_INTEGRITY_CHECK=Y
NETFS_KEEP_OLD_BACKUP_COPY=y

PRE_BACKUP_SCRIPT=(
"rm -rf /data/supportconfig/*;"
"/sbin/supportconfig -Q -c -R /data/supportconfig;"
)
POST_BACKUP_SCRIPT=()
PRE_RECOVERY_SCRIPT=()
POST_RECOVERY_SCRIPT=()

BACKUP_PROG_EXCLUDE=(
"${BACKUP_PROG_EXCLUDE[@]}"
/lost+found/*
/mnt/*
/var/cache/*
/var/tmp/*
)

BACKUP_PROG_INCLUDE=(
/boot/grub2/i386-pc/*
/boot/grub2/x86_64-efi/*
/opt/*
/srv/*
/usr/local/*
/var/lib/libvirt/images/*
/var/lib/machines/*
/var/lib/mailman/*
/var/lib/mariadb/*
/var/lib/mysql/*
/var/lib/named/*
/var/lib/pgsql/*
/var/log/*
/var/opt/*
/var/spool/*
)

REQUIRED_PROGS=(
awk
base64
dialog
diff
dos2unix
lsblk
lsof
lspci
md5sum
mkfs.vfat
mkswap
mount
mount.cifs
mount.fuse
mount.nfs
mount.nfs4
parted
ping
ping6
pstree
renice
rsync
screen
sha256sum
tmux
swapon
touch
vim
vimdiff
traceroute
traceroute6
scp
ssh
watch
snapper
chattr
lsattr
clear
infocmp
reset
tabs
toe
tput
tset
"${REQUIRED_PROGS[@]}"
)

COPY_AS_IS=(
/usr/lib/snapper/installation-helper
/etc/snapper/config-templates/default
"${COPY_AS_IS[@]}"
)

MODULES=( 'all_modules' )
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
HPE ProLiant 380 Gen10

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
grub2

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk, hardware raid

* Description of the issue (ideally so that others can reproduce it):
This is the recovery related version of issue https://github.com/rear/rear/issues/2369 which dealt with backup speed.
The mentioned issue added a blocksize setting of 1M to the tar backup to improve backup speed on certain systems.
This seemed to suffice until we had the same issue during recovery now - applying the same idea of adding bs=1M to NETFS/default/400_restore_backup.sh helps to solve the performance issue during netfs/tar recovery.

* Workaround, if any:
We created a short patch that adds bs=1M to the dd command in NETFS/default/400_restore_backup.sh which worked pretty well for us.
[400_restore_backup.patch.txt](https://github.com/rear/rear/files/4947766/400_restore_backup.patch.txt)

**Comment by jsmeix** [comment]
Oh yes, a few days ago I had already seen by luck
the missing counterpart in NETFS/default/400_restore_backup.sh

I am sorry that I did not have the idea to also look at the restore part during
https://github.com/rear/rear/issues/2369

I will add the missing counterpart in NETFS/default/400_restore_backup.sh
right now...

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2459 merged
this issue should be fixed.

**Comment by jsmeix** [comment]
@dsamx 
thank you for helping us to make ReaR better!
