### ISSUE TITLE
REAR 2.6: UEFI Based systems fail to boot with "error: file `/isolinux/kernel' not found"

### ISSUE THREAD

**Issue by abbbi** [rear/rear#2463]
Hi,

i have setup some automatic tests that use the latest Rear Version shipped with our components
to create a backup and automatically boot the generated iso image to verify a recovery would work (in simple setups, using 
expect to answer all the questions):

I also have some multipath setups that use UEFI boot, after updating to REAR 2.6, the generated ISO images
fail to boot with:

```
error: file `/isolinux/kernel' not found.
Loading initial ramdisk ...
error: you need to load the kernel first.
Press any key to continue...
```

We use mostly default settings, these worked with REAR 2.5, not sure if im hitting a regression here or does
REAR 2.6 need more settings regarding UEFI? Distributions in this case are SLE12/SLE15.

Backup log regarding UEFI looks quite normal:

```
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
[..]
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/sles/grubx64.efi' as UEFI bootloader file
[..]
```

**Comment by abbbi** [comment]
Having a quick look at the generated iso image it seems grub.cfg is referencing to /isolinux/kernel as boot image:

```
/mnt/EFI/BOOT/grub.cfg:     linux /isolinux/kernel root=UUID=36cb193a-9a79-4187-917e-84c6895fe38d selinux=0 console=ttyS0,9600 console=tty0
```

but that file is not part of the generated iso image:

```
/mnt/
├── boot
│   ├── efiboot.img
│   └── grub
│       └── grub.cfg
├── BOOT.CAT
├── EFI
│   └── BOOT
│       ├── BOOTX64.efi
│       ├── fonts
│       │   └── unicode.pf2
│       ├── grub.cfg
│       └── locale
└── isolinux
    ├── chain.c32
    ├── hdt.c32
    ├── initrd.cgz
    ├── isolinux.bin
    ├── isolinux.cfg
    ├── kernel
    ├── menu.c32
    ├── message
    ├── pci.ids
    ├── poweroff.com
    ├── rear.help
    ├── reboot.c32
    └── vesamenu.c32
```

**Comment by gozora** [comment]
Can this be related to https://github.com/rear/rear/issues/2434 ?

V.

**Comment by abbbi** [comment]
> Can this be related to #2434 ?
> 
> V.

most likely, i missed that one!

**Comment by gozora** [comment]
Then try latest upstrem ReaR, sholud be fixed there ...

V.

**Comment by abbbi** [comment]
> Then try latest upstrem ReaR, sholud be fixed there ...

will try again with the mentioned patches.

**Comment by abbbi** [comment]
I can confirm that after applying commit 149fea9775316ba0f6cf550c1cfd67a980de757f  our tests are now working again! Thanks!
