### ISSUE TITLE
Keep only 5 last backup 

### ISSUE THREAD

**Issue by rearuser** [rear/rear#2467]
Hello,

Is there an option that could delete and old backup after a period
I put the variable NETFS_KEEP_OLD_BACKUP_COPY=y , but i need to keep only 5 instances, so the oldest one could be deleted and replaced by the new one

is there a way to do this  with rear please ?

Thank you in advance

**Comment by jsmeix** [comment]
Relax-and-Recover (ReaR) is neither a backup software
nor a backup management software
and it is not meant to be one. 

See the section
"Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by rearuser** [comment]
If i understand rear is a disaster recover, so what i want to keep not one iso, but many ones, and if there is a way that rear could delete the previous iso starting after a period

**Comment by gozora** [comment]
@rearuser 

[POST_BACKUP_SCRIPT](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L3148-L3149) might help you to implement your own backup retention policy ...

V.

**Comment by rearuser** [comment]
Thank you for your feedback
