### ISSUE TITLE
Dependancy failed for Login Service

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2480]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.6 / 2020-06-17

* OS version ("cat /etc/os-release"):
````
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
````

* ReaR configuration files ("cat /etc/rear/local.conf"):
````
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="$HOSTNAME"
OUTPUT_URL=rsync://xxxx@192.168.1.123::rsync_backup
BACKUP_URL=rsync://xxxx@192.168.1.123::rsync_backup
MESSAGE_PREFIX="$$: "
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=/etc/rear/rsync_pass)
BACKUP_PROG_EXCLUDE+=( "/home/vijay/iso/*" "/etc/rear/rsync_pass" )
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
export TMPDIR="/home/vijay/iso/"
````
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
virtual machine

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI and GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
````
NAME                KNAME     PKNAME    TRAN   TYPE FSTYPE       SIZE MOUNTPOINT
/dev/sda            /dev/sda            sata   disk               32G 
|-/dev/sda1         /dev/sda1 /dev/sda         part ext4           1G /boot
`-/dev/sda2         /dev/sda2 /dev/sda         part LVM2_member   31G 
  |-/dev/mapper/fedora_localhost--live-root
  |                 /dev/dm-0 /dev/sda2        lvm  ext4          29G /
  `-/dev/mapper/fedora_localhost--live-swap
                    /dev/dm-1 /dev/sda2        lvm  swap         2.1G [SWAP]
/dev/sr0            /dev/sr0            ata    rom              1024M
````

* Description of the issue (ideally so that others can reproduce it):

I have done backup properly. When i try to perform recover operation that too worked properly. But unable to login my machine post that. facing Login service failed issue and it hung that place only.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue" debug log files):
attached rear -D mkrescue

[rear-localhost.log](https://github.com/rear/rear/files/5078045/rear-localhost.log)

**Comment by gdha** [comment]
@cvijayvinoth  We see in  the `rear-locahost.log` file that the `/etc/rear/os.conf` has been read:
````
++ OS_VENDOR=Ubuntu
++ OS_VERSION=18.04
````
Perhaps remove that file and try again? That is clearly not Fedora.
