### ISSUE TITLE
No code has been generated to recreate pv:/dev/sda2 (lvmdev)

### ISSUE THREAD

**Issue by abbbi** [rear/rear#2482]
#### Relax-and-Recover (ReaR) Issue Template

* ReaR version ("/usr/sbin/rear -V"): 2.5

Hi, 

i have come across the same situation as discussed in issue #1952

It seems the Hardware System in this case has two raid controllers which in case define two raid levels.
For some reason, it appears that this configuration looks to REAR like a Multipath setup, even tho multipath -ll does
not show any output.

It results in a behavior, where the local disks are excluded from the disklayout.conf during backup:

> 2020-08-13 11:53:26.163129805 Saving disk partitions.
> 2020-08-13 11:53:26.168784050 Ignoring sda: it is a path of a multipath device
> 2020-08-13 11:53:26.173146596 Ignoring sdb: it is a path of a multipath device

thus, the recovery fails because needed disk entries in disklayout.conf are missing entirely.

The relevant code is in:

https://github.com/rear/rear/blob/master/usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh#L383

Unfortunatley that means, that not even a commented out version of the disk configuration is added
to disklayout.conf (which would make recovery easy) but also, AUTOEXCLUDE_MULTIPATH='n' does not
work in such configurations.

**Comment by abbbi** [comment]
The "multipath -l" command on the system does not output anything, so i think the following statement is the one that might result in the multipath check function to return true:

https://github.com/rear/rear/blob/master/usr/share/rear/lib/layout-functions.sh#L705

I will request debug logfile.

**Comment by jsmeix** [comment]
@abbbi 
you use ReaR 2.5
but https://github.com/rear/rear/issues/2298
was fixed via https://github.com/rear/rear/pull/2299
for ReaR 2.6
cf. https://github.com/rear/rear/blob/master/doc/rear-release-notes.txt
