### ISSUE TITLE
Rubrik CDM agent missing after ReaR recovery

### ISSUE THREAD

**Issue by DamaniN** [rear/rear#2483]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

v2.5 &  v2.6

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

All

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

N/A

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

All

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

All

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

N/A

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

N/A

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

N/A

* Description of the issue (ideally so that others can reproduce it):

CDM v5.0.3-P4 and v5.1.1 began excluding the RBS agent from backups. As a result when a system is restored by ReaR and CDM the RBS agent won't be re-installed. Re-protection of the system after restore isn't possible until RBS is reinstalled. If the system needs to be re-linked to its old backups certificates on the recovered system will have to be updated with the ones prior to the restore. 

* Workaround, if any:

After recovery but before rebooting copy /etc/rubrik to /mnt/local/rubrik. Also copy /usr/bin/rubrik to /mnt/local/usr/bin/rubrik. Both copies should also copy the file permissions. 

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

N/A

**Comment by gdha** [comment]
@DamaniN Are you able to prepare a PR for this?

**Comment by DamaniN** [comment]
@gdha, yes I'm working on a larger one that will incorporate a fix for this.

**Comment by drakkainenn** [comment]
Dear team,

any update?? 3 years and I have still this issue.
rear: 2.7
rubrik: 8.0.1

After recovery:
[root@server rear]# ls -la /etc/rubrik
ls: cannot access '/etc/rubrik': No such file or directory
