### ISSUE TITLE
Oracle related hugepage settings in sysctl config might mess up memory in recovery image

### ISSUE THREAD

**Issue by abbbi** [rear/rear#2484]
hi,

today i have come accross a  situation which i like to share.. 

Recovery ISO booted, but no memory was available within the boot image!
OOM reaper was randomly killing processes resulting in applications to fail

It appeared that the system in question had an oracle database installed, and
oracle or related packages seem to enable the hugepages setting in 
/etc/sysctl.conf:

  vm.nr_hugepages = [some big value]

This settings (at least on SLES12) totaly messes up the memory in the
recovery image (all memory but some left over MB is in use)
As soon as option is disabled within recovery image:

 sysctl -w vm.nr_hugepages=0

the memory becomes free and everything is working as excpected.
Maybe that should be documented or during recovery, it might not be the best idea
to use sysctl settings as applied to the original system?

**Comment by gdha** [comment]
@abbbi  That is indeed valuable information to take with us (in documentation) or during the recovery OS image building. Need to think about it.

**Comment by abbbi** [comment]
> @abbbi That is indeed valuable information to take with us (in documentation) or during the recovery OS image building. Need to think about it.

especially in enterprise environments. I think other big software players like SAP do also setup/create sysctl settings that might change memory behavior in a way that it causes trouble. Yet i fail to understand why the hugepages setting kicks in in such a way if the kernel boots via initrd .. Havent done much more testing here yet.
