### ISSUE TITLE
Use REAR to backup a system to a local file system 

### ISSUE THREAD

**Issue by IT-Guy-1973** [rear/rear#2486]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.6 / 2020-06-17

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

SUSE 12 SP4

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86 Azure Cloud

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):

Hello Support,

Is there a way I could re-create the root disk partitions using a rear backup on a VM running in Azure?

I am able to create a "raw" backup using REAR of the VM. I can also mount the root disk to another system.  Can I delete the "/boot" and "/" partitions in rescue mode and re-create them to my needs using the rear backup in some way?

Regards,
Niranjan

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by gdha** [comment]
@IT-Guy-1973 Did you use BLOCKCLONE and dd (https://github.com/rear/rear/blob/master/doc/user-guide/04-scenarios.adoc) technique to create the raw image? I cannot give a correct answer as the input is not fully clear to me.

**Comment by IT-Guy-1973** [comment]
Hello @gdha ,

Sorry for the late response and my vague question. Here is the problem I have:

Cloud providers like Azure and AWS do not support booting from an ISO. Therefore I cannot use the ".iso" file that is created when I do a REAR backup to recover  a VM is Azure or AWS. Is there another method in REAR where I could recover a VM using REAR in a cloud environment?

Thank you,
Regards,
Niranjan

**Comment by jsmeix** [comment]
@IT-Guy-1973 
see the section "RESCUE IMAGE CONFIGURATION" in "man rear" e.g. online at
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
what kind of `OUTPUT` medium ReaR can make.

I don't know wherefrom a VM in Azure or AWS can boot.
I use neither Azure nor AWS.
I use only KVM/QEMU VMs that can boot from ISO (via virtual CDROM).

Perhaps a VM in Azure or AWS can boot via PXE (i.e. `OUTPUT=PXE`)?

For a generic workaround how to boot the ReaR recovery system see the section
"Launching the ReaR recovery system via kexec" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by gdha** [comment]
@IT-Guy-1973 If you mount a snapshot disk to another VM you can do what you like with it - including restoring / and /boot from another rear backup. I do think a grub2 mkconfig will be necessary to get this snapshot disk bootable. It is worth a try I would say.

Feedback is most welcome!
