### ISSUE TITLE
RPC Portmapper "rpcbind" unavailable - Proxmox Recovery

### ISSUE THREAD

**Issue by aftermath8** [rear/rear#2487]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
2.4 Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
OUTPUT_URL="nfs://192.168.178.110/mnt/proxmox_share"
BACKUP=NETFS
BACKUP_URL="nfs://192.168.178.110/mnt/proxmox_share"
BACKUP_OPTIONS="nfsvers=4,nolock"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
KVM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
$ lsblk
NAME               MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                  8:0    0 465.8G  0 disk 
`-sda1               8:1    0 465.8G  0 part /mnt/pve/ExternF1
sdb                  8:16   0 238.5G  0 disk 
|-sdb1               8:17   0  1007K  0 part 
|-sdb2               8:18   0   512M  0 part 
`-sdb3               8:19   0   238G  0 part 
  |-pve-swap       253:0    0     8G  0 lvm  [SWAP]
  |-pve-root       253:1    0  59.3G  0 lvm  /
  |-pve-data_tmeta 253:2    0   1.6G  0 lvm  
  | `-pve-data     253:4    0 151.6G  0 lvm  
  `-pve-data_tdata 253:3    0 151.6G  0 lvm  
    `-pve-data     253:4    0 151.6G  0 lvm  
sdc                  8:32   1   3.8G  0 disk 
`-sdc1               8:33   1   3.8G  0 part 
sdd                  8:48   1  15.1G  0 disk 
sde                  8:64   0 465.8G  0 disk 
|-sde1               8:65   0 121.1G  0 part 
`-sde2               8:66   0 344.7G  0 part 
sr0                 11:0    1  1024M  0 rom  
```

Hello,

First of all, I would like to thank you for this excellent software that makes life easier for all sysadmins.

Actually I am implementing a Backup/Disaster Recovery strategy for a medical environment, with virtual servers hosted on Proxmox ([](https://pve.proxmox.com/wiki/Main_Page)) for my license thesis.
The project is still in the simulation phase but the idea is to make Backups and Disaster Recovery of virtual machines, but also of Proxmox itself (more precisely of the node in which the virtual machines are located) in order to be able to facilitate the Disaster Recovery process. It's indeed quite possible to do it by saving the configuration of `/etc` and `/var/lib/pve-cluster` with periodic cronjobs and then do some tinkering, but this is not very intuitive.

ReaR works perfectly fine with virtual machines but it's when I try to apply it to the Proxmox server that things get complicated. First, by running the simulation command, this is what I get:

[rear -s mkbackup.txt](https://github.com/aftermath8/Bachelorarbeit/files/5162818/rear.-s.mkbackup.txt)

* This is the first dysfunction I've noticed:
```
Exiting rear mkbackup (PID 16241) and its descendant processes
Running exit tasks
```
I call it a _dysfunction_ because I don't get any error message but also this is not how it should run (at least, it did not appear for virtual machines' simulation)  

So once I run `rear -v mkbackup`, ReaR does the job with obviously the same dysfunction message at the end:
[rear -v mkbackup.txt](https://github.com/aftermath8/Bachelorarbeit/files/5163194/rear.-v.mkbackup.txt)

* So I create a VM and try to restore my Proxmox on it. The second dysfunction is that when I access the recovery terminal, I notice that my virtual machine has the same IP address as my Proxmox server (this should not happen because Proxmox generates a new IP for every VM). So I ping to see which address is free on the router and I change it manually in `/etc/hosts`, then reboot, but it doesn't change anything.

* This is what I get after `rear -v recover`

![Screenshot](https://user-images.githubusercontent.com/61789098/92006625-42f37800-ed45-11ea-9d87-0f4ba492a423.png)

![Screenshot2](https://user-images.githubusercontent.com/61789098/92006631-4555d200-ed45-11ea-9a06-b84c1259d637.png)

Sorry for being maybe too "amateur", I'm learning the job :man_student: 

Thank you!

**Comment by gdha** [comment]
@aftermath8 See http://relax-and-recover.org/documentation/faq section IP Migration. You could also use DHCP via  defining the vairable **USE_DHCLIENT=yes** in the `/etc/rear/local.conf` file.

**Comment by aftermath8** [comment]
Hi @gdha 
Thank you for your answer! I used the variable `USE_CLIENT=yes` and the IP address is indeed not the same anymore, but there is still a problem with `rpcbind`, which means that the Recovery process cannot be executed:

![Screenshot22](https://user-images.githubusercontent.com/61789098/92244438-3432cf80-eec3-11ea-99da-92ec0012eba6.png)

**Comment by gdha** [comment]
@aftermath8 Check if issue #2341 could help you with your problem? It is for RHEL, but yeah you never know.

**Comment by aftermath8** [comment]
Both issues helped, no such error message anymore, thanks!

Summary of the solution:
* Added `USE_DHCLIENT=yes`
* Replaced `test "ok" = $attempt || Error "RPC portmapper '$portmapper_program' unavailable."` by `test "ok" = $attempt || LogPrint "RPC portmapper '$portmapper_program' unavailable."`
* Replaced `rpcinfo -p 2>/dev/null | grep -q 'portmapper' && { attempt="ok" ; break ; }` by `rpcinfo -p | tee -a $RUNTIME_LOGFILE | grep -q 'portmapper' && { attempt="ok" ; break ; }`
