### ISSUE TITLE
On RHEL 7.6 OUTPUT=PXE with UEFI needs 'linuxefi' and 'initrdefi' in function make_pxelinux_config_grub

### ISSUE THREAD

**Issue by laurio0** [rear/rear#2497]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / 2020-06-17

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=PXE
PXE_CONFIG_URL="nfs://100.39.80.35/export/TFTP"
PXE_TFTP_URL="nfs://100.39.80.35/export/TFTP"
PXE_CONFIG_GRUB_STYLE=y
PXE_TFTP_IP=100.39.80.35
USING_UEFI_BOOTLOADER=yes
BACKUP=NETFS
BACKUP_URL="nfs://100.39.80.35/export/backup"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
DELL PowerEdge R440 Server

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
X86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI and GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
Local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):
The function "make_pxelinux_config_grub" on "bootloader-functions.sh", generate this lines:
```
linux (tftp)//nodo2.kernel root=/dev/ram0 vga=normal rw selinux=0 console=ttyS0,9600 console=ttyS1,9600 console=tty0
echo 'Loading initial ramdisk ...'
initrd (tftp)//nodo2.initrd.cgz
```
And it doesn't boot.

* Workaround, if any:
The woraround is to change the above lines with:
```
linuxefi (tftp)//nodo2.kernel root=/dev/ram0 vga=normal rw selinux=0 console=ttyS0,9600 console=ttyS1,9600 console=tty0
echo 'Loading initial ramdisk ...'
initrdefi (tftp)//nodo2.initrd.cgz
```

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by jsmeix** [comment]
@laurio0 
I am neither a REHL nor a PXE user so I would like to see in full detail
what exactly goes on on your particular system during "rear mkrescue"
so please attach your `rear -D mkrescue` debug log file.

**Comment by jsmeix** [comment]
PXE_CONFIG_GRUB_STYLE was implemented via
https://github.com/rear/rear/pull/1339

As far as I see PXE_CONFIG_GRUB_STYLE usage
is not yet sufficiently documented in ReaR.
E.g. is noticed in usr/share/rear/lib/bootloader-functions.sh
```
function make_pxelinux_config_grub {
...
    # we use this function only when $PXE_CONFIG_URL is set and $PXE_CONFIG_GRUB_STYLE=y
    # TODO First Draft. Need to complete with all other options (see make_pxelinux_config).
```
but those restrictions are not mentioned in usr/share/rear/conf/default.conf
so some general enhancements and cleanup is needed in this area.

**Comment by laurio0** [comment]
The message at boot is:

`Loading Kernel . . .
error: can't find command 'linux'.
Loading initial ramdisk . . .
error: can't find command 'initrd'.
`

**Comment by jsmeix** [comment]
@laurio0 
I am neither a REHL nor a PXE user so I would like to see in full detail
what exactly goes on on your particular system during "rear mkrescue"
so please attach a recent `rear -D mkrescue` debug log file.
