### ISSUE TITLE
Post recover system is not booting (systemd ends in "emergency mode")

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2499]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.6 / 2020-06-17

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME=Fedora
VERSION="32 (Server Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="$HOSTNAME"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://diskimage@192.168.1.123::rsync_backup
BACKUP_URL=rsync://diskimage@192.168.1.123::rsync_backup
ISO_DIR="$(</etc/rear/path.txt)/imageBackup/iso/$HOSTNAME"
MESSAGE_PREFIX="$$: "
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=/etc/rear/rsync_pass)
BACKUP_PROG_EXCLUDE+=( "$(</etc/rear/path.txt)/imageBackup/iso/*" "/etc/rear/rsync_pass" )
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
virtual machine

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI and GRUB 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): 
ssd 

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME            MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda               8:0    0   20G  0 disk
├─sda1            8:1    0    1G  0 part  /boot
└─sda2            8:2    0   19G  0 part
  ├─fedora-root 253:0    0   15G  0 lvm   /
  └─fedora-swap 253:1    0    2G  0 lvm   [SWAP]
sdb               8:16   0   20G  0 disk
└─sdb1            8:17   0   20G  0 part
  └─md0           9:0    0   20G  0 raid1 /mnt/raid1
sdc               8:32   0   20G  0 disk
└─sdc1            8:33   0   20G  0 part
  └─md0           9:0    0   20G  0 raid1 /mnt/raid1
sr0              11:0    1 1024M  0 rom
```

* Description of the issue (ideally so that others can reproduce it):

Post recover, If I boot my machine I am getting message like " You are in Emergency mode. After logging in, type "jpurnalctl -xb". ( attached screenshot for your reference)
[rear-localhost.log](https://github.com/rear/rear/files/5340880/rear-localhost.log)
![VirtualBox_fedora-64-nn_07_10_2020_17_41_26](https://user-images.githubusercontent.com/426209/95335411-ff080b80-08cc-11eb-80da-e058361fc9d7.png)

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

Please find the attachment

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by gdha** [comment]
@cvijayvinoth Did you install rear-2.6 from the Fedora release or did you downloaded a version from the ReaR download pages?

**Comment by cvijayvinoth** [comment]
> from the Fedora release

Installed from fedora release

**Comment by gdha** [comment]
@cvijayvinoth OK thanks - did you enter the emergency mode to find out what went wrong?

**Comment by jsmeix** [comment]
FYI:
This issue is not the same as https://github.com/rear/rear/issues/2528
because in this issue here
https://github.com/rear/rear/files/5340880/rear-localhost.log
shows that the initrd of the recreated system was recreated
```
628: 2020-10-07 18:36:23.569763718 Including finalize/Fedora/i386/550_rebuild_initramfs.sh
```
