### ISSUE TITLE
Improve TCG Opal 2 Documentation

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2511]
- https://github.com/Drive-Trust-Alliance/sedutil/issues/301#issuecomment-723010843 suggests to better explain the OS installation.
- Additionally, some information from the [relevant article on Ask Ubuntu](https://askubuntu.com/a/1271171/1120528) might be included.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2512 merged this issue is fixed.
