### ISSUE TITLE
SLES11 with UEFI: Creating ISO image fails with "Cannot make bootable EFI image of GRUB2"

### ISSUE THREAD

**Issue by abbbi** [rear/rear#2513]
Hi,

it seems newer rear versions (from version 2.5 on) have problems creating an bootable ISO image on SLES11 with UEFI BIOS, even with ebiso installed and

`ISO_MKISOFS_BIN=/usr/bin/ebiso`

Option set in local.conf.
The last working version seems to be rear-2.4, with this version im able to successfully create an bootable ISO image.
From version 2.5 on up to master, creating the iso image fails with:

```
ERROR: Cannot make bootable EFI image of GRUB2 (neither grub-mkstandalone nor grub2-mkstandalone found)
Some latest log messages since the last called script 250_populate_efibootimg.sh:
  2020-11-11 03:38:26.521755943 Including output/ISO/Linux-i386/250_populate_efibootimg.sh
  2020-11-11 03:38:26.529112634 Copying kernel
```

**Comment by abbbi** [comment]
Logfile with debug output from current master:

[rear-linux-st0j.log](https://github.com/rear/rear/files/5522864/rear-linux-st0j.log)

**Comment by abbbi** [comment]
Not exacly having the background, but in older versions the function simply returned, now it is issuing an error:

```
-        Log "Did not find grub-mkimage (cannot build bootx86.efi)"
-        return
+        # This build_bootx86_efi function is only called in output/ISO/Linux-i386/250_populate_efibootimg.sh
+        # which runs only if UEFI is used so that we simply error out here if we cannot make a bootable EFI image of GRUB2
+        # (normally a function should not exit out but return to its caller with a non-zero return code):
+        Error "Cannot make bootable EFI image of GRUB2 (neither grub-mkstandalone nor grub2-mkstandalone found)"
+    fi
```

reverting this change i was able to create a bootable iso image for SLES11.

**Comment by jsmeix** [comment]
@abbbi 
why do you need newer ReaR versions on SLES11?
What is missing in ReaR 2.4 for disaster recovery on SLES11?
I would assume that anyone who runs SLES11 should meanwhile
since a longer time have set up his particular disaster recovery procedure
that works in his environment for his SLES11 systems.
Cf. the section "Version upgrades with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

In general see
https://github.com/rear/rear/blob/master/doc/rear-release-notes.txt
(excerpts):
```
ReaR-2.6 is supported on the following Linux based operating systems:
...
  SLES 12 and 15
  openSUSE Leap 15.x
...
ReaR-2.6 dropped official support for the following Linux based operating
systems:
....
  SLES < 12
  openSUSE Leap 42.x and before (i.e. openSUSE <= 13)
  openSUSE Tumbleweed
...
ReaR-2.6 may still work for SLES 11 and openSUSE Leap 42.x or even earlier
openSUSE versions but it is no longer sufficiently well tested there so
arbitrary regressions could appear.
...
If you require support for unsupported Linux operating systems you must
acquire a ReaR support contract.
```

**Comment by abbbi** [comment]
> @abbbi
> why do you need newer ReaR versions on SLES11?

im sorry i have completely missed the statement in the release notes as it seems :(
Well, we have some Customers which still have HANA on SLES11 and came across this issue while updating the REAR version. We will stick with the last known working version then.

**Comment by jsmeix** [comment]
Argh!
Customers who seem to blindly upgrade their working ReaR version.
Yeah let's use latest greatest!
Why?
Yeah 'cause latest is greatest ever yeah!
;-)

@abbbi 
thank you for the issue report (so I know where newer ReaR fails on SLES11)
and for your explanation of the reason behind!

**Comment by pcahyna** [comment]
FYI here is the discussion about dropping distribution support due to this change: https://github.com/rear/rear/pull/2199#issuecomment-561293641 . At that time I thought that distributions using GRUB legacy (not GRUB 2) would not be affected by the change, but apparently I was wrong.
