### ISSUE TITLE
timestamp file not working anymore

### ISSUE THREAD

**Issue by brossob** [rear/rear#2521]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.4

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): Oracle Linux 7.8

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
HOST_DIR=`hostname`
DATE_DIR=`date +%U-%Y`
OUTPUT=ISO
OUTPUT_URL=nfs://prodmon01/backups
BACKUP=NETFS
BACKUP_URL=nfs://prodmon01/backups
BACKUP_PROG=tar
BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" '/apps' '/backup' '/prodmon01_backups' )
BACKUP_TYPE=incremental
FULLBACKUPDAY="Sun"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): Bare Metal

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): X86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):
i use tar with incremental backups, and since we moved from rear 1.17 to 2.4
the timestamps file does not work anymore, 

```
````

**Comment by jsmeix** [comment]
The "timestamp.txt" file was removed via
https://github.com/rear/rear/commit/eca18f9459ea78d440061e005c35713918985ecd
when real incremental backup support was implemented, cf.
https://github.com/rear/rear/pull/1071 and
https://github.com/rear/rear/issues/1069

See the descriptions about incremental and/or differential backup
in usr/share/rear/conf/default.conf in particular the part at `BACKUP_TYPE`
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1147

The "timestamp.txt" file was an implementation detail
that was never meant to be officially used by users.
Of course users can use implementation details
but they may change or go away at any time.

Now the timestams are "encoded" in the different backup file names.
That is also described in default.conf at `BACKUP_TYPE`
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1159
