### ISSUE TITLE
REAR-EFI lable should be configurable (multiple backup discs scenario)

### ISSUE THREAD

**Issue by DEvil0000** [rear/rear#2547]
* ReaR version ("/usr/sbin/rear -V"): 2.6
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI

Scenario:
The scenario is using multiple backup disks with one system (connected at the same time) and using UEFI on them. One internal disk and one usb stick for example.

The issue:
rear relies on the hardcoded REAR-EFI lable for writing efi/boot content to the partition.

The solution:
When this label would be configurable and/or rear would use the uuid (or id since vfat has a short one) of the EFI for the format/mkrescue process this would work fine.

Clarifications after looking at PR 2538:
* I am using rear with borg (not rawdisk)
* my system is using UEFI (it's a must)
* my backup/rear medium must boot using UEFI (it's a must) - also note it is using a additional UEFI partition (rear usb 'mode')

The REAR-EFI label used when creating a rear usb media with UEFI is hardcoded and makes creation and usage of a second usb media (attached at the same moment) impossible.

**Comment by gdha** [comment]
@DEvil0000 Looking forward to a PR ;-)

**Comment by OliverO2** [comment]
Hmm, it's already there, actually: https://github.com/rear/rear/pull/2538

**Comment by DEvil0000** [comment]
@OliverO2 I don't see how the linked PR fixes or addresses this issue. Even if it addresses the issue it would only fix it for RAWDISK - right?
I see some similarity in how we want to use rear but I don't see the PR fixing the issue in general. I will clarify things in the description above.

**Comment by OliverO2** [comment]
@DEvil0000
`RAWDISK` is basically a universal version of the `USB` output method which supports the use case you have described. The main difference is that `USB` directly writes to *one* installation medium while `RAWDISK` creates an image file, which you'll transfer to any number of installation mediums in a separate step:

* `OUTPUT=USB`
    * requires preparing a medium via `rear format`,
    * requires attaching the medium during `rear mkrescue`,
    * uses the hardcoded `REAR-EFI` label on that medium,
    * supports UEFI boot or BIOS boot (but not both simultaneously),
    * does not support multiple-partition installation.
* `OUTPUT=RAWDISK`
    * does not require a previously prepared medium being present,
    * creates an image file which can then be copied to any medium (including a USB drive or an HDD partition),
    * supports UEFI boot (and BIOS boot and hybrid UEFI/BIOS boot),
    * supports multiple-partition installation, either
        * automatically via https://github.com/rear/rear/pull/2538, or
        * manually via copying the image file to the respective partition(s).

Whether you are using Borg or any other `BACKUP` method is not affected by your choice of `OUTPUT` method.

**Comment by DEvil0000** [comment]
I understand but my usecase is `OUTPUT=USB` and for that it is at the moment not possible to have two USB devices at the same time - like described. Maybe I can switch to using `OUTPUT=RAWDISK` in such a case but thats not the general solution to this ticket.

**Comment by OliverO2** [comment]
You describe the scenario as follows (emphasis added):
> The scenario is using multiple backup disks with one system (connected at the same time) and using UEFI on them. **One internal disk** and one usb stick for example.

That would be a combination of one USB (full disk) device and one non-USB (disk partition) device. Looks pretty much out of scope for `OUTPUT=USB`.
