### ISSUE TITLE
Feature: BACKUP=fsarchiver

### ISSUE THREAD

**Issue by DEvil0000** [rear/rear#2557]
I think rear is lacking some option between `raw`, `rsync` and all those advanced things. I loved to use `fsarchiver` which does something like a filesystem backup (including parmission and such) and compresses that full backup into a single file. That comes in quite handy when you want a full backup but not raw since you have a lot of unused space. Due to the compression and less lookup effort it is at least in some cases better then using `rsync`. For example on a Raspberry PI thats in my eyes the optimal method.

Issue #413 would also integrate perfectly with it as with most other methods. Its a good choice to get a in time consistent snapshot of the stored files without stopping services. Please consider implementing this as well.

**Comment by gdha** [comment]
@DEvil0000 Supposingly you are referring to https://www.fsarchiver.org/ - The pages are mentioning SystemRescue is a perfect match, sure enough, ReaR is also a valid candidate to add `fsarchiver`  binary to copy with the rescue image and you could use the BACKUP=EXTERNAL setting in the `/etc/rear/local.conf` file.

Furthermore, I understand your reasoning behind the scenes, but it would add an extra layer of complexity I think (my opninion may vary of course with yours or others).
The case you are refering to RaspberryPI - perhaps useful yes, but ReaR has not yet be ported to aarch64 (in its full extends) and not sure ReaR has a clear understanding how to handle the boot mechanism on aarch64. I do know there ws some effort in the past, but I don't think it was completed.
