### ISSUE TITLE
Failed to connect network for static IP ( cent OS 7 ) during recovery process

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2568]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.5 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="diskimage_${HOSTNAME}"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://diskimage@XXXXXX::rsync_backup
BACKUP_URL=rsync://diskimage@XXXXX::rsync_backup
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
USE_STATIC_NETWORKING=y
NETWORKING_PREPARATION_COMMANDS=( 'ip addr add 10.0.1.17/24 broadcast 10.0.1.255 dev enp0s3' 'ip link set dev enp0s3 up' 'ip route add default via 10.0.1.1' 'return' )

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): virtual machine

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  500G  0 disk
├─sda1   8:1    0    1G  0 part /boot
├─sda2   8:2    0  251G  0 part /home
├─sda3   8:3    0  240G  0 part /
├─sda4   8:4    0    1K  0 part
└─sda5   8:5    0    8G  0 part [SWAP]
sdb      8:16   0   32G  0 disk
├─sdb1   8:17   0 14.5G  0 part
└─sdb2   8:18   0 17.6G  0 part
sr0     11:0    1 1024M  0 rom

* Description of the issue (ideally so that others can reproduce it):
I am using network settings as NAS on my vm ( recovery machine). Already I have mentioned static IP . When I am trying to recover on my machine getting network unreachable error. 

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): rear -D mkrescue attached
* 
![VirtualBox_centos7-rs_12_02_2021_19_49_14](https://user-images.githubusercontent.com/426209/107779562-8a0d7c80-6d6b-11eb-8160-b539ddda67de.png)

[rear-vijay-centos-7.log](https://github.com/rear/rear/files/5972326/rear-vijay-centos-7.log)
![VirtualBox_centos7-rs_12_02_2021_19_47_48](https://user-images.githubusercontent.com/426209/107779339-369b2e80-6d6b-11eb-88a1-7340f3ec76fa.png)

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by gdha** [comment]
@cvijayvinoth `ip addr add 10.0.1.17/24 broadcast 10.0.1.255` => could you ping 10.0.1.1? Why not using DHCP?
It is normal that you cannot reach 192.168.1.123 as it is a private network and you did not make a route to this network from 10.0.1.0 network.

**Comment by cvijayvinoth** [comment]
Yes. As of now i am keeping here private IP. I will make it as public IP. The issue is in my server network DHCP is disabled. So unable to go with dhcp.  When I try to create a virtualbox for a normal os via NAT network  internet connectivity is working fine. When try to boot via iso, i cannot able to connect Public IP / internet (  on NAT network ). Could you please guide me on this?
