### ISSUE TITLE
REAR image does not boot in UEFI

### ISSUE THREAD

**Issue by pcmurphy101** [rear/rear#2569]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):   
 
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): 

NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

[rear-gardel-en1-02.log](https://github.com/rear/rear/files/5984259/rear-gardel-en1-02.log)
```
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=file:///home/backup
BACKUP_URL=file:///home/backup
BACKUP_PROG_EXCLUDE=("{$BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/log' '/var/tmp' '/var/crash' '/tmp')
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

HP DL380 G10  

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

UEFI, See RESULTS.txt for bootloader info script results.
[RESULTS.txt](https://github.com/rear/rear/files/5984271/RESULTS.txt)

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME                                         KNAME     PKNAME    TRAN   TYPE FSTYPE        SIZE MOUNTPOINT
/dev/sda                                     /dev/sda            sas    disk             279.4G 
|-/dev/sda1                                  /dev/sda1 /dev/sda         part vfat          628M /boot/efi
|-/dev/sda2                                  /dev/sda2 /dev/sda         part ext4            1G /boot
`-/dev/sda3                                  /dev/sda3 /dev/sda         part LVM2_member   269G 
  |-/dev/mapper/rhel_gardel--en1--02-root    /dev/dm-0 /dev/sda3        lvm  ext4           30G /
  |-/dev/mapper/rhel_gardel--en1--02-swap    /dev/dm-1 /dev/sda3        lvm  swap           64G [SWAP]
  |-/dev/mapper/rhel_gardel--en1--02-usr     /dev/dm-2 /dev/sda3        lvm  ext4           40G /usr
  |-/dev/mapper/rhel_gardel--en1--02-var     /dev/dm-3 /dev/sda3        lvm  ext4           40G /var
  |-/dev/mapper/rhel_gardel--en1--02-var_log /dev/dm-4 /dev/sda3        lvm  ext4           20G /var/log
  |-/dev/mapper/rhel_gardel--en1--02-var_tmp /dev/dm-5 /dev/sda3        lvm  ext4           15G /var/tmp
  |-/dev/mapper/rhel_gardel--en1--02-tmp     /dev/dm-6 /dev/sda3        lvm  ext4           30G /tmp
  `-/dev/mapper/rhel_gardel--en1--02-opt     /dev/dm-7 /dev/sda3        lvm  ext4           30G /opt
/dev/sdb                                     /dev/sdb            sas    disk               4.1T 
|-/dev/sdb1                                  /dev/sdb1 /dev/sdb         part ext4         29.3G /codes
|-/dev/sdb2                                  /dev/sdb2 /dev/sdb         part ext4        439.5G /home
`-/dev/sdb3                                  /dev/sdb3 /dev/sdb         part ext4          3.7T /gardel
```
* Description of the issue (ideally so that others can reproduce it):

I burned the ISO image to dvd, and installed it into an identical bare metal DL380 G10 server.  the system was booted but the DVD was not identified as bootable.   I believe the UEFI secure boot is blocking the boot somehow.  

* Workaround, if any:

This is what is listed in my /boot/efi/EFI/redhat folder:
```
 -rwx------. 1 root root     182 Sep 22 05:46 BOOTX64.CSV
drwx------. 2 root root    4096 Aug 31 05:50 fonts
-rwx------. 1 root root    6666 Feb 10 12:18 grub.cfg
-rwx------. 1 root root    1024 Feb 15 12:41 grubenv
-rwx------. 1 root root 1893320 Aug 31 05:50 grubx64.efi
-rwx------. 1 root root 1170232 Sep 22 05:46 mmx64.efi
-rwx------. 1 root root 1244488 Sep 22 05:46 shimx64.efi
-rwx------. 1 root root 1238544 Sep 22 05:46 shimx64-redhat.efi
```
I believe the grubx64.efi was selected as the bootloader by rear.   I will attempt to specify the shimx64.efi as an alternate and try that while I wait for any replies.  I will also try to change to RAWDISK and load that on a USB.   However the perfered method of recovery in this case is an ISO burned to a DVD (this is due to the isolated nature of the systems being build and that USB needs preparation which is not easy under the cyber controls in place.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

debug log attached

**Comment by gdha** [comment]
@pcmurphy101 Do you have a RedHat subscription for this system? If yes why not open a case with RH? RH can assist us in this issue.
