### ISSUE TITLE
mount: /tmp/rear.xxxxxxxxxx/outputfs: no filesystem type specified.

### ISSUE THREAD

**Issue by BigMarioss** [rear/rear#2570]
- ReaR version: Relax-and-Recover 2.6-git.0.0382834.unknown / 2021-02-09

- OS version: CentOS 8

- ReaR configuration files:
```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso://backup
GRUB_RESCUE=1
TMPDIR=/mnt2/tmp
OUTPUT_URL=nfs://192.168.1.110/backup
NETFS_KEEP_OLD_BACKUP_COPY=yes
CLONE_ALL_USERS_GROUPS=yes
MODULES=( 'all_modules' )
ISO_FILE_SIZE_LIMIT=0
```

- Hardware: the backupped machine is an HP server (CPU AMD Opteron(tm) X3216 APU) 

- System architecture: x86_64

- Firmware: firmware 5.12 and (I think) bootloader GRUB2

- Storage: one 500gb HD

- Storage layout:
```
NAME               MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                  8:0    0 465.8G  0 disk
├─sda1               8:1    0     1G  0 part /boot
└─sda2               8:2    0 464.8G  0 part
  ├─cl_zabbix-root 253:0    0    70G  0 lvm  /
  ├─cl_zabbix-swap 253:1    0   7.4G  0 lvm  [SWAP]
  └─cl_zabbix-home 253:2    0 387.4G  0 lvm  /home
```

- Description of the issue:

I made an ISO image (files+recovery inside it) of a server and now I'm trying to install the ISO inside to a notebook but when I run "rear -v -d recover" the recover fails and I get this error: mount: /tmp/rear.xxxxxxxxxx/outputfs: no filesystem type specified.
I tryied to install the ISO inside a virtualbox VM successfully, but the recover fails on real PC's... Why?

Attachments, as applicable:
![logs](https://user-images.githubusercontent.com/39734056/108396310-fe866680-7216-11eb-9091-1da4d627fdde.jpeg)

**Comment by gdha** [comment]
@BigMarioss  Did you verify if the ISO could be mounted via the device name, e.g. /dev/sr0 on the recovery system?

**Comment by BigMarioss** [comment]
Hi, I resolved the problem by updating Rear version. The iso works successfully now.

But I have another problem: the option "NETFS_KEEP_OLD_BACKUP_COPY=yes" does not work. There are only two backup folders, "hostaname" and "hostname.old", and when I run the backup task the folder "hostname.old" is overwritten by the folder called "hostname", so there aren't more than two backups... Why?

**Comment by jsmeix** [comment]
`NETFS_KEEP_OLD_BACKUP_COPY=yes` works as implemented and described
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L2339
```
# Keep an older copy of the backup (mv $NETFS_PREFIX $NETFS_PREFIX.old before we copy the new version)
# empty means only keep current backup:
NETFS_KEEP_OLD_BACKUP_COPY=
```
