### ISSUE TITLE
PowerPC repo in OBS not present for RHEL/CenOS 6,7 & 8

### ISSUE THREAD

**Issue by didacog** [rear/rear#2578]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Any

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): CentOS/RHEL 6,7 & 8

* Description of the issue (ideally so that others can reproduce it):

There are no PPC64/PPC64LE packages in Rear Repositories for CentOS/RHEL systems.

**Comment by didacog** [comment]
Hello, I'm testing DRLM and ReaR on Power and there are no rpms for RHEL/Centos systems, I've seen you solved the SLES repos, but there are still missing the RHEL/CentOS ones. ;)

**Comment by jsmeix** [comment]
I enabled what can be enabled and
where ReaR builds successfully
so I enabled
* ppc64le for CentOS_7
* ppc64le for CentOS_8
* ppc64 for RHEL_7
* ppc64 for RedHat_RHEL-6

**Comment by didacog** [comment]
Great! Thanks @jsmeix!!

**Comment by jsmeix** [comment]
You are welcome!
