### ISSUE TITLE
Rear recovery with borgbackup failed, no python3 in rescue image

### ISSUE THREAD

**Issue by zolalmasi** [rear/rear#2582]
* ReaR version ("/usr/sbin/rear -V"):
2.5

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Ubuntu 20.04.2 LTS

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=BORG

BORGBACKUP_HOST="192.168.12.110"
BORGBACKUP_USERNAME="ubuntulocal"
BORGBACKUP_REPO="/mnt/backup/ubuntulocal/repo"
BORGBACKUP_REMOTE_PATH="/usr/local/bin/borg"

BORGBACKUP_PRUNE_KEEP_WEEKLY=2

BORGBACKUP_COMPRESSION="lzma,6"     # Slowest backup, best compression

BORGBACKUP_ENC_TYPE="none"
export BORG_PASSPHRASE='1234'
#COPY_AS_IS_BORG=( "$ROOT_HOME_DIR/.config/borg/keys/" )

export BORG_RELOCATED_REPO_ACCESS_IS_OK="yes"
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK="yes"

BACKUP_PROG_EXCLUDE+=( '/root/backup/*' )
```
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Dell desktop pc

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local ssd

Stock ubuntu 20.04 with official installed borg and rear package.
Made backup with rear mkbackup, then tried to recover with usb pendrive.
Rear recover gived error message: `Failed to list Borg archive.`
In console borg gived error:
```
/usr/bin/python3: bad interpreter: No such file or directory
```

(tried with rear 2.6 but with similar result)

**Comment by gozora** [comment]
Hello @zolalmasi 

Maybe https://github.com/rear/rear/issues/1727 can help you ?

V.

**Comment by zolalmasi** [comment]
Yes I think my fault... at n.th reading documentation I found:
We strongly recommend to use Borg standalone binary (..) as it includes all necessities for Borg operations. If you decide to go for different type of Borg installation types, make sure you include all needed files for Borg runtime into ReaR rescue/recovery system. E.g. by using COPY_AS_IS_BORG=( '/usr/lib64/python3.4*' '/usr/bin/python3*' '/usr/bin/pyvenv*' '/usr/lib/python3.4*' '/usr/lib64/libpython3*' )

**Comment by jsmeix** [comment]
@zolalmasi 
to test whether or not things work inside the ReaR recovery system
without the need to boot the ReaR recovery system you could set
```
KEEP_BUILD_DIR="yes"
```
in your `etc/rear/local.conf` and after "rear mkrescue/mkbackup"
`chroot` into TMPDIR/rear.XXX/rootfs/
and run things inside the ReaR recovery system as a test, see
`KEEP_BUILD_DIR` in your usr/share/rear/conf/default.conf
also online for current ReaR GitHub master code at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L148

Of course such tests are no replacement for a real "rear recover" test,
cf. "No disaster recovery without testing and continuous validation" in
https://en.opensuse.org/SDB:Disaster_Recovery
but such tests help to find obvious issues in the ReaR recovery system more easily.
