### ISSUE TITLE
Unable to boot fedora 30 machine post recovery

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2583]
* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.5 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="yuvaraj2_${HOSTNAME}"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://yuvaraj2@192.168.1.123::rsync_backup
BACKUP_URL=rsync://yuvaraj2@192.168.1.123::rsync_backup
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=/var/www/html/imageBackup/user_profile/yuvaraj2/rsync_pass)
BACKUP_PROG_EXCLUDE+=( "$(</etc/rear/path.txt)/imageBackup/iso/*" "$(</etc/rear/path.txt)/imageBackup/user_profile/*" "$(</etc/rear/path.txt)/imageBackup/data/rsync_pass" )
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
export TMPDIR="/var/www/html/imageBackup/iso/"
PXE_RECOVER_MODE=automatic
ISO_FILES=("/var/www/html/imageBackup/rsync")
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
USE_DHCLIENT="Yes"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): BIOS and GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME                                        KNAME     PKNAME    TRAN   TYPE FSTYPE        SIZE MOUNTPOINT
/dev/sda                                    /dev/sda            sata   disk             465.8G
|-/dev/sda1                                 /dev/sda1 /dev/sda         part ext4            1G /boot
`-/dev/sda2                                 /dev/sda2 /dev/sda         part LVM2_member 464.8G
  |-/dev/mapper/fedora_localhost--live-root /dev/dm-0 /dev/sda2        lvm  ext4           70G /
  |-/dev/mapper/fedora_localhost--live-swap /dev/dm-1 /dev/sda2        lvm  swap          7.8G [SWAP]
  `-/dev/mapper/fedora_localhost--live-home /dev/dm-2 /dev/sda2        lvm  ext4          387G /home
```

* Description of the issue (ideally so that others can reproduce it):
post recovery unable to boot my Fedora 30 machine.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): attached rear -D recover log file

![VirtualBox_yuvi-fedora_05_03_2021_16_56_44](https://user-images.githubusercontent.com/426209/110110114-5f479e80-7dd4-11eb-9dfa-7c4afee339c5.png)
[vvLog.txt](https://github.com/rear/rear/files/6090191/vvLog.txt)

**Comment by gdha** [comment]
@cvijayvinoth The vvLog.txt does not contain additional information towards your ReaR issue - check it out.
