### ISSUE TITLE
Define specific volumes / partitions to backup?

### ISSUE THREAD

**Issue by davehouser1** [rear/rear#2586]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.4

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): RHEL7.9

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): Baremetal (UEFI)

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): X64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): Local RAID

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift): Layout is /dev/sda and /dev/sdb

* Description of the issue (ideally so that others can reproduce it):

How do I tell rear to only backup specific volumes / partitions? Our /dev/sda is 11TB most of which is not used. /dev/sdb is where the kernel and all user files are. Is there a way to specify to only back up /dev/sdb?

Maybe I am blind, but I tried reading these documents, no of which mention partitions or volumes:
https://access.redhat.com/solutions/2115051
and
https://github.com/rear/rear/blob/master/doc/rear.8.adoc

**EDIT:** I did look over the default.conf file. From what I understand REAR will backup everything, and its the user's responsibility to define exclusion of mount points. However its not clear to me which option to use for my purposes.
Which option should I use to exclude say "/dev/sda" from backups, but backup everything else?

**Comment by jsmeix** [comment]
In general including/excluding components like disks/partitions/filesystems
is different from what gets included/excluded regarding the backup.
There are some relationships but in general both are different things.

From my experience with other issues the backup include/exclude functionality
versus the components include/exclude functionality in ReaR is "hairy".

Currently - as far as I see - there is no simple clear and consistently working way
how the user could specify what disk layout components he wants to get recreated
and what mountpoints or directories he wants to get included in the backup.

See also
https://github.com/rear/rear/issues/2229
therein in particular
https://github.com/rear/rear/issues/2229#issuecomment-529953810
and
https://github.com/rear/rear/issues/2229#issuecomment-531474858
