### ISSUE TITLE
machine is not booting post restore UEFI model ( Ubuntu 20.04 ).

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2592]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.5 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="diskimage_${HOSTNAME}"
OUTPUT_URL=rsync://diskimage@192.168.1.123::rsync_backup
BACKUP_URL=rsync://diskimage@192.168.1.123::rsync_backup
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=/var/www/html/imageBackup/user_profile/diskimage/rsync_pass)
ISO_DIR="/var/www/html/imageBackup/iso/$HOSTNAME"
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
export TMPDIR="/var/www/html/imageBackup/iso/"
PXE_RECOVER_MODE=automatic
ISO_FILES=("/var/www/html/imageBackup/rsync")
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
virtual machine

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 465.8G  0 disk 
|-sda1   8:1    0   512M  0 part /boot/efi
`-sda2   8:2    0 465.3G  0 part /local
```

* Description of the issue (ideally so that others can reproduce it):
machine is not booting post restore UEFI model.
blank screen is coming.
and in recovery log getting warning like this.
```
efibootmgr --create --gpt --disk /dev/sda --part 1 --write-signature --label 'Ubuntu 20.04' --loader '\EFI\ubuntu\grubx64.efi'
efibootmgr: ** Warning ** : Boot0002 has same label Ubuntu 20.04
BootCurrent: 0005
Timeout: 1 seconds
BootOrder: 0001,0000,0002,0003,0004,0005
Boot0000* ubuntu
Boot0002* Ubuntu 20.04
Boot0003* ubuntu
Boot0004* UEFI OS
Boot0005* UEFI: SanDisk Cruzer Blade 1.27
Boot0001* Ubuntu 20.04
```

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[rear-harishu20u-H81M-WW.log](https://github.com/rear/rear/files/6204577/rear-harishu20u-H81M-WW.log)

**Comment by jsmeix** [comment]
@cvijayvinoth 
you wrote and your https://github.com/rear/rear/files/6204577/rear-harishu20u-H81M-WW.log
contains `Relax-and-Recover 2.5 / Git`

Could you try out what is described in the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
or is this case a real disaster recovery where you cannot
redo "rear mkbackup" with current ReaR master code
on your original system?

**Comment by gdha** [comment]
@cvijayvinoth Did a restore test on an UEFI Ubuntu 20.04 LTS VM server with rear 2.6 git clone dating 15 April 2021 and with the `local.conf` containing:
````
BACKUP=NETFS
BACKUP_URL=nfs://192.168.0.38/export/nfs
FIRMWARE_FILES=( 'no' )
SSH_ROOT_PASSWORD="vagrant"
USER_INPUT_TIMEOUT=3
````
Rear mkbackup/recover worked perfectly and the `efibootmgr` output after recovery looked like:
````
# efibootmgr 
BootCurrent: 0005
Timeout: 0 seconds
BootOrder: 0005,0001,0004,0000,0002,0003
Boot0000* UiApp
Boot0001* UEFI VBOX CD-ROM VB2-01700376 
Boot0002* UEFI VBOX HARDDISK VBa375b630-4cb11598 
Boot0003* EFI Internal Shell
Boot0004* ubuntu
Boot0005* Ubuntu 20.04
````
With other words we cannot reproduce the issue with our latest upstream rear master software. Please try with the latest snapshot or git clone

**Comment by cvijayvinoth** [comment]
@gdha : Sure Let me check and update

**Comment by jsmeix** [comment]
No news is good news.
