### ISSUE TITLE
Unable to create ISO image on Fedora-31 UEFI model ( used latest rear 2.6 version )

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2600]
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="harish_${HOSTNAME}"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://harish@192.168.1.3::rsync_backup
BACKUP_URL=rsync://harish@192.168.1.3::rsync_backup
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=XXXXXX)
BACKUP_PROG_EXCLUDE+=( "$(</etc/rear/path.txt)/imageBackup/iso/*" "$(</etc/rear/path.txt)/imageBackup/user_profile/*" "$(XXXXXX" )
ISO_DIR="/var/www/html/imageBackup/iso/$HOSTNAME"
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
export TMPDIR="/var/www/html/imageBackup/iso/"
PXE_RECOVER_MODE=automatic
ISO_FILES=("/var/www/html/imageBackup/rsync")
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI & GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda               8:0    0 465.8G  0 disk
├─sda1            8:1    0   600M  0 part /boot/efi
├─sda2            8:2    0     1G  0 part /boot
└─sda3            8:3    0 464.2G  0 part
  ├─fedora-root 253:0    0    15G  0 lvm  /
  └─fedora-swap 253:1    0   7.8G  0 lvm  [SWAP]
sdb               8:16   0 465.8G  0 disk
├─sdb1            8:17   0   512M  0 part
└─sdb2            8:18   0 465.3G  0 part
```

* Description of the issue (ideally so that others can reproduce it):
I am using latest rear 2.6 version.
When I am trying to generate the iso image via rear -v mkrescue command,
I am getting below mentioned error.
```
grub2-mkstandalone may fail to make a bootable EFI image of GRUB2 (no /usr/*/grub*/x86_64-efi/moddep.lst file)
94419: 2021-04-15 07:33:10.182176622 GRUB2 modules to load: fat part_gpt xfs
94419: 2021-04-15 07:33:10.224783041 **ERROR: Failed to make bootable EFI image of GRUB2 (error during grub2-mkstandalone** of /var/www/html/imageBackup/iso/rear.xywekZB3bmwQ21I/tmp/mnt/EFI/BOOT/BOOTX64.efi)
```

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): rear -D mkrescue

[rear-recheckfedora31.log](https://github.com/rear/rear/files/6317698/rear-recheckfedora31.log)

**Comment by gdha** [comment]
Is this related to #2585?

**Comment by cvijayvinoth** [comment]
@gdha  : No its not related to #2585. On that issue bootable iso image was created. But in this issue, unable to create iso image itself. It is throwing error like this **grub2-mkstandalone may fail to make a bootable EFI image of GRUB2 (no /usr//grub/x86_64-efi/moddep.lst file)** while running rear -v mkrescue

**Comment by gdha** [comment]
@cvijayvinoth  Can you confirm that **grub2-efi-x64-modules** package is available on this system?

**Comment by cvijayvinoth** [comment]
Sorry Its my mistake. I installed correct package grub2-efi-x64-modules. Thanks for your update.
