### ISSUE TITLE
Commit "Add SUPPORT section in README" is broken

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#2605]
@gdha 
your recent commit "Add SUPPORT section in README"
https://github.com/rear/rear/commit/2f3b62a3b418027bbf177fd57d33c557266cca19
is broken.

It seems by accident many (or even all) symlinks in ReaR got deleted
and the content became re-added as regular separated duplicated files.

**Comment by gdha** [comment]
@jsmeix commits have been reverted - please check from your side if it is ok

**Comment by jsmeix** [comment]
Right now I did a new `git clone https://github.com/rear/rear.git` into a separated directory
and compared that why my existing clone from before
https://github.com/rear/rear/commit/2f3b62a3b418027bbf177fd57d33c557266cca19
and both are same so this issue is solved.

@gdha 
thank you for your fix!
