### ISSUE TITLE
ERROR: BUG BUG BUG!  ROOTFS_DIR

### ISSUE THREAD

**Issue by exfarmer** [rear/rear#2624]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 
   Relax-and-Recover 1.17.2 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
   LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
   Distributor ID: RedHatEnterpriseServer
   Description:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
   Release:        6.10
   Codename:       Santiago

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
   OUTPUT=ISO
   OUTPUT_URL=nfs://usspdd6800/data/col1/stpaul_linux_bu_image
   BACKUP_OPTIONS="nfsvers=3,nolock"
   OUTPUT_OPTIONS="nfsvers=3,nolock"
   BACKUP=NETFS
   BACKUP_URL=nfs://usspdd6800/data/col1/stpaul_linux_bu_image
   BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/usr/openv' '/var/log' '/var/log/audit')
   ONLY_INCLUDE_VG=( 'VolGroup00' 'vgos' )
   NETFS_KEEP_OLD_BACKUP_COPY=y

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
   VMware Virtual Platform

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
   Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
   
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
      SAN 
* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
  NAME="sda" KNAME="sda" TYPE="disk" FSTYPE="" MOUNTPOINT="" SIZE="100G"
  NAME="sda1" KNAME="sda1" TYPE="part" FSTYPE="ext4" MOUNTPOINT="/boot" SIZE="512M"
  NAME="sda2" KNAME="sda2" TYPE="part" FSTYPE="LVM2_member" MOUNTPOINT="" SIZE="99.5G"
  NAME="vgos-rootvol" KNAME="dm-0" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/" SIZE="10.3G"
  NAME="vgos-lvswap" KNAME="dm-1" TYPE="lvm" FSTYPE="swap" MOUNTPOINT="[SWAP]" SIZE="20G"
  NAME="vgos-lvtmp" KNAME="dm-5" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/tmp" SIZE="10.3G"
  NAME="vgos-lvvar" KNAME="dm-6" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/var" SIZE="20G"
  NAME="vgos-lvopt" KNAME="dm-7" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/opt" SIZE="10.3G"
  NAME="vgos-lvopenv" KNAME="dm-8" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/usr/openv" SIZE="15G"
  NAME="vgos-cbp" KNAME="dm-9" TYPE="lvm" FSTYPE="ext4" MOUNTPOINT="/srv" SIZE="2G"
* Description of the issue (ideally so that others can reproduce it):
2021-06-03 12:28:17.266286475 Including build/default/98_verify_rootfs.sh
chroot: failed to run command `bash': Operation not permitted
2021-06-03 12:28:17.291786597 ERROR: BUG BUG BUG!  ROOTFS_DIR '/tmp/rear.YP4rXqG34zWXSYR/rootfs' is broken, chroot bash test failed.
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-ussp-mltbvic02.log

HINT: If you can reproduce the issue, try using the -d or -D option !
====================
=== Stack trace ===
Trace 0: /usr/sbin/rear:251 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:15 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:70 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:31 Source
Trace 4: /usr/share/rear/build/default/98_verify_rootfs.sh:17 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:144 BugError
Message: BUG BUG BUG!  ROOTFS_DIR '/tmp/rear.YP4rXqG34zWXSYR/rootfs' is broken, chroot bash test failed.
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-ussp-mltbvic02.log

HINT: If you can reproduce the issue, try using the -d or -D option !
====================
===================
2021-06-03 12:28:17.316156246 Running exit tasks.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by pcahyna** [comment]
>     * Relax-and-Recover 1.17.2 / Git

This is a very old version. Please open a customer case if you are using the package shipped with RHEL (or try the newest version - ReaR 2.6).

**Comment by exfarmer** [comment]
The issue is not a ReaR backup issue, rather a Carbon Black issue not allowing ReaR to run.
We are in the process of adding ReaR to the inclusion list
