### ISSUE TITLE
ERROR: dd failed with return code 1

### ISSUE THREAD

**Issue by exfarmer** [rear/rear#2631]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
``` 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.8 (Maipo)
Release:        7.8
Codename:       Maipo
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
OUTPUT_URL=nfs://ussvdd3300/data/col1/ussv_linux_bu_image
BACKUP_OPTIONS="nfsvers=3,nolock"
OUTPUT_OPTIONS="nfsvers=3,nolock"
BACKUP=NETFS
BACKUP_URL=nfs://ussvdd3300/data/col1/ussv_linux_bu_image
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/var/log' '/usr/openv')
ONLY_INCLUDE_VG=( 'VolGroup00' 'rhel' )
NETFS_KEEP_OLD_BACKUP_COPY=y
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Dell Inc. PowerEdge R640

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
3.10.0-1160.25.1.el7.x86_64

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME                         KNAME     PKNAME    TRAN TYPE FSTYPE        SIZE MOUNTPOINT
/dev/sda                     /dev/sda                 disk               278G
|-/dev/sda1                  /dev/sda1 /dev/sda       part vfat          200M /boot/efi
|-/dev/sda2                  /dev/sda2 /dev/sda       part xfs             1G /boot
`-/dev/sda3                  /dev/sda3 /dev/sda       part LVM2_member 276.8G
  |-/dev/mapper/rhel-root    /dev/dm-0 /dev/sda3      lvm  xfs            50G /
  |-/dev/mapper/rhel-swap    /dev/dm-1 /dev/sda3      lvm  swap           24G [SWAP]
  |-/dev/mapper/rhel-lvdata  /dev/dm-2 /dev/sda3      lvm  xfs           100G /ichome
  `-/dev/mapper/rhel-lvopenv /dev/dm-3 /dev/sda3      lvm  xfs            12G /usr/openv
```

* Description of the issue (ideally so that others can reproduce it):
```
Creating tar archive '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz'
Archived 4694 MiB [avg 5071 KiB/sec] OK
ERROR: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.

Aborting due to an error, check /var/log/rear/rear-ussv-rdhpapp02.log for details
Exiting rear mkbackup (PID 236532) and its descendant processes
Running exit tasks
```

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by pcahyna** [comment]
From a quick look it seems that something was wrong with the NFS mount (from `ussvdd3300`).

**Comment by exfarmer** [comment]
I agree, but the backup starts, the /tmp/rear.KCXi6xCey8b60rU is created:
Creating tar archive '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz'
Archived 4694 MiB [avg 5071 KiB/sec] OK
ERROR: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------

I ran this # rear -D -d mkbackup
Can I run it with more debug information?
I haven’t deleted the /tmp/rear.KCXi6xCey8b60rU file yet, and I can see the ISO and other files on the target NFS disk: //ussvdd3300/data/col1/ussv_linux_bu_image/ussv-rdhpapp02.

Any ideas why this would fail?

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by pcahyna** [comment]
> rear -D -d mkbackup

This is enough, is there anything more interesting in the log (`/var/log/rear/rear*.log) before the error message?

> Any ideas why this would fail?

No concrete idea, perhaps network problem, or lack of space on the NFS server? Please check the system logs both on the system that you are backing up and on the NFS server, especially for NFS and filesystem related messages.

**Comment by pcahyna** [comment]
also, you say that you se other files on the target. How big is the (unfinished) backup.tar.gz ?

**Comment by exfarmer** [comment]
Hi, there’s nothing in dmesg or var/log/messages related to NFS or the rear backup.
It looks like it finishes the backup, then fails.
See attached


Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by pcahyna** [comment]
And is there enough space on the server to write more data to backup.tar.gz? Is there anything else in /tmp/rear.KCXi6xCey8b60rU/tmp/backup.log ?

**Comment by exfarmer** [comment]
Hi,

block 29610321: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64.img
block 29674835: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img
block 29704307: /boot/config-3.10.0-1160.21.1.el7.x86_64
block 29704610: /boot/vmlinuz-3.10.0-1160.21.1.el7.x86_64
block 29717843: /boot/initramfs-3.10.0-1160.21.1.el7.x86_64kdump.img
dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
9615118+0 records in
9615117+0 records out
4922939904 bytes (4.9 GB) copied, 947.122 s, 5.2 MB/s

***@***.*** ~]# df -H /tmp
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   54G   18G   37G  32% /

***@***.*** ~]# df -H /gsh_rear/
Filesystem                                 Size  Used Avail Use% Mounted on
ussvdd3300:/data/col1/ussv_linux_bu_image   17T  2.7T   14T  17% /gsh_rear

Although 4.9G is large, it isn’t close to the limit.
Other file systems on the NFS share are twice that size.

***@***.*** ~]# du -h /gsh_rear/*|sort
3.7G    /gsh_rear/ussv-cad01
4.3G    /gsh_rear/ussv-rdhpapp01
4.8G    /gsh_rear/ussv-rdhpapp01.old
4.9G    /gsh_rear/ussv-rdhpapp02
4.9G    /gsh_rear/ussv-rdhpapp02.old
5.5G    /gsh_rear/ussv-cad02.old
6.0G    /gsh_rear/ussv-cad02
6.2G    /gsh_rear/ussv-tvup01
6.2G    /gsh_rear/ussv-tvup01.old
9.1G    /gsh_rear/ussv-rdhpapp00.old
9.4G    /gsh_rear/ussv-rdhpapp00


Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by pcahyna** [comment]
Is the error reproducible? Have you tried the backup multiple times?

**Comment by exfarmer** [comment]
Yes, the backup runs through Blade Logic, but I also ran it manually and each time, twice, it failed with the same error.

/var/log/rear/rear-ussv-rdhpapp02.log
==== Stack trace ====
Trace 0: /usr/sbin/rear:547 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:26 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 4: /usr/share/rear/backup/NETFS/default/500_make_backup.sh:252 source
++ echo 'Message: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '\''/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz'\'': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.
'
Message: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.

++ echo '== End stack trace =='
== End stack trace ==
++ kill -USR1 236532
+++ EXIT_FAIL_MESSAGE=0
+++ echo 'Aborting due to an error, check /var/log/rear/rear-ussv-rdhpapp02.log for details'

/var/log/rear/rear-ussv-rdhpapp02.log.old
==== Stack trace ====
Trace 0: /usr/sbin/rear:547 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:26 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 4: /usr/share/rear/backup/NETFS/default/500_make_backup.sh:252 source
Message: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.Qhi8DRaSmBo7kPc/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.

== End stack trace ==
2021-06-10 05:21:44.728908362 Exiting rear mkbackup (PID 199284) and its descendant processes
2021-06-10 05:21:45.803894935 rear,199284 /usr/sbin/rear -d -v mkbackup
  `-rear,232834 /usr/sbin/rear -d -v mkbackup
      `-pstree,232835 -Aplau 199284
/usr/share/rear/lib/_input-output-functions.sh: line 157: kill: (232838) - No such process
2021-06-10 05:21:45.890447727 Running exit tasks

I can run it again and see what is in the /tmp.rear.whatever/tmp/backup.log, without deleting the one that is there now.
Let me know
Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by pcahyna** [comment]
Does it abort at the same size of output file every time (4694 MiB)? Do I understand correctly that you are saving backups from multiple machines to the same NFS server and only one of them has the problem? If so, do you know what might make the problematic machine different?

**Comment by exfarmer** [comment]
Hi,

Just ran it again:

Archived 4680 MiB [avg 5056 KiB/sec] OK
ERROR: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.oqOJpPF14XJAVjF/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.

From /tmp/rear.oqOJpPF14XJAVjF/tmp/backup.log
block 29606323: /boot/symvers-3.10.0-1160.25.1.el7.x86_64.gz
block 29606953: /boot/vmlinuz-3.10.0-1160.25.1.el7.x86_64
block 29620186: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64.img
block 29684700: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img
dd: writing to '/tmp/rear.oqOJpPF14XJAVjF/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
9586305+0 records in
9586304+0 records out
4908187648 bytes (4.9 GB) copied, 948.811 s, 5.2 MB/s
++ pipes_rc=(${PIPESTATUS[@]})
++ let index=3-1

From the previous one, /tmp/rear.KCXi6xCey8b60rU/tmp/backup.log
block 29674835: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img
block 29704307: /boot/config-3.10.0-1160.21.1.el7.x86_64
block 29704610: /boot/vmlinuz-3.10.0-1160.21.1.el7.x86_64
block 29717843: /boot/initramfs-3.10.0-1160.21.1.el7.x86_64kdump.img
dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
9615118+0 records in
9615117+0 records out
4922939904 bytes (4.9 GB) copied, 947.122 s, 5.2 MB/s
++ pipes_rc=(${PIPESTATUS[@]})
++ let index=3-1

It’s close, but not exact
Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by exfarmer** [comment]
Hi,

The storage team increased the quota on the NFS share, that fixed the issue.
It would have been nice to see that there was a quota issue in the log file, but all’s good now.

Thank you

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***


From: Hess, Gary
Sent: Thursday, June 10, 2021 11:22 AM
To: 'rear/rear' ***@***.***>; rear/rear ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [rear/rear] ERROR: dd failed with return code 1 (#2631)

Hi,

Just ran it again:

Archived 4680 MiB [avg 5056 KiB/sec] OK
ERROR: dd failed with return code 1 and below output:
  ---snip---
  dd: writing to '/tmp/rear.oqOJpPF14XJAVjF/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
  ----------
This means that the archiving process ended prematurely, or did
not even start. As a result it is unlikely you can recover this
system properly. Relax-and-Recover is therefore aborting execution.

From /tmp/rear.oqOJpPF14XJAVjF/tmp/backup.log
block 29606323: /boot/symvers-3.10.0-1160.25.1.el7.x86_64.gz
block 29606953: /boot/vmlinuz-3.10.0-1160.25.1.el7.x86_64
block 29620186: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64.img
block 29684700: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img
dd: writing to '/tmp/rear.oqOJpPF14XJAVjF/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
9586305+0 records in
9586304+0 records out
4908187648 bytes (4.9 GB) copied, 948.811 s, 5.2 MB/s
++ pipes_rc=(${PIPESTATUS[@]})
++ let index=3-1

From the previous one, /tmp/rear.KCXi6xCey8b60rU/tmp/backup.log
block 29674835: /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img
block 29704307: /boot/config-3.10.0-1160.21.1.el7.x86_64
block 29704610: /boot/vmlinuz-3.10.0-1160.21.1.el7.x86_64
block 29717843: /boot/initramfs-3.10.0-1160.21.1.el7.x86_64kdump.img
dd: writing to '/tmp/rear.KCXi6xCey8b60rU/outputfs/ussv-rdhpapp02/backup.tar.gz': Input/output error
9615118+0 records in
9615117+0 records out
4922939904 bytes (4.9 GB) copied, 947.122 s, 5.2 MB/s
++ pipes_rc=(${PIPESTATUS[@]})
++ let index=3-1

It’s close, but not exact
Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by pcahyna** [comment]
> It would have been nice to see that there was a quota issue in the log file, but all’s good now.

Glad to hear that. ReaR itself can't report a quota issue, it merely runs tools like dd and reports the result. Why dd was not able to report the quota error is a valid question, it seems that it merely reports the error from the kernel. "Input/output error" is `EIO` (see the errno(3) man page). I would expect `EDQUOT` (Disk quota exceeded) instead. I suggest to ask your storage administrators whether they know how one can make NFS to report quota errors properly (maybe there is a way), or contact Red Hat support.

Anyway, this is not the right place for solving this problem, my NFS-fu is not strong enough for this.

**Comment by exfarmer** [comment]
Hi,

I meant that the dd statement would return different codes, not that I expected ReaR to do it.
I think we’re good, the error was from a Wednesday night server, the Thursday night servers had no issues.
The failed server also worked.

Close this case, if something comes up next Wednesday, I’ll email you

Thank you


Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

335 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***

**Comment by jsmeix** [comment]
@pcahyna 
thank you for your analysis that revealed the root cause in the user's environment!
