### ISSUE TITLE
No /usr/share/rear when booting rescue system

### ISSUE THREAD

**Issue by tigaente** [rear/rear#2642]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.0.7
Codename:       Ornara
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=RAWDISK
OUTPUT_URL="file:///var/lib/rear/output"
KERNEL_FILE="/boot/vmlinuz-5.12-x86_64"
COPY_AS_IS="/usr/lib/modules/extramodules-5.12-MANJARO"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Hardware PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86-64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
Firmware: UEFI
Bootload: GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME        KNAME     PKNAME   TRAN   TYPE FSTYPE   SIZE MOUNTPOINT
/dev/sda    /dev/sda           sata   disk        238,5G
|-/dev/sda1 /dev/sda1 /dev/sda        part vfat     550M /boot/efi
|-/dev/sda2 /dev/sda2 /dev/sda        part swap       4G [SWAP]
`-/dev/sda3 /dev/sda3 /dev/sda        part ext4   233,9G /
/dev/sdb    /dev/sdb           sata   disk        232,9G
`-/dev/sdb1 /dev/sdb1 /dev/sdb        part ext4   232,9G /home
```

* Description of the issue (ideally so that others can reproduce it):
I used the documentation from this URL https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc to create a rescue USB stick with PBA environment for OPAL 2 SEDs.
The commands
```
rear mkopalpba
rear mkrescue
```
work fine and do not show errors. Also dd-ing the raw image to a USB drive works, but when booting from the USB I see some errors about files not found. However, those fly by so fast I cannot really read them. After logging in, the command rear does not work. Instead, it gives an error that /usr/share/rear/default.conf cannot be found and some other source errors where files seem to be missing.
Upon checking, there simply is no /usr/share/rear-directory on the USB drive. It does exist on my main OS, though that I use to create the rescue image.
I'm currently using the pkgbuild from ARCH AUR, but I also tried cloning the git repo manually and used that version. But the outcome stays the same. When using the git version in the local dir, I sometimes see this error:
```
Broken symlink '/usr/share/rear' in recovery system because 'readlink' cannot determine its link target
```
Any help here is highly appreciated.
Andi

**Comment by jsmeix** [comment]
I am not a OPAL user and I do not have a TCG Opal 2-compliant self-encrypting disk
so I cannot reproduce issues related to self-encrypting disks.

What I tried on a QEMU/KVM x86_64 virtual test machine with SLES15-SP3
with latest ReaR upstream master code, see the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery

I did (my very first experiment with OPAL stuff):
```
# wget -O sedutil_LINUX.tar.gz https://github.com/Drive-Trust-Alliance/exec/blob/master/sedutil_LINUX.tgz?raw=true
...
2021-07-05 13:05:45 (4.95 MB/s) - ‘sedutil_LINUX.tar.gz’ saved [249464/249464]

# tar -xf sedutil_LINUX.tar.gz

# cp sedutil/Release_x86_64/GNU-Linux/sedutil-cli /usr/local/bin


# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf
...

# cat etc/rear/local.conf
FIRMWARE_FILES=( 'no' )
MODULES=( 'loaded_modules' )
PROGRESS_MODE="plain"
PROGRESS_WAIT_SECONDS="3"
USE_DHCLIENT="yes"
SSH_ROOT_PASSWORD="rear"
OUTPUT=RAWDISK
OUTPUT_URL="file:///var/lib/rear/output"


# usr/sbin/rear -D mkopalpba
Relax-and-Recover 2.6 / Git
Running rear mkopalpba (PID 3337 date 2021-07-05 12:59:47)
Command line options: usr/sbin/rear -D mkopalpba
Using log file: /root/rear.github.master/var/log/rear/rear-localhost.log
Using build area: /tmp/rear.JeqjpKW3aQQoNjD
Running workflow mkopalpba on the normal/original system
Re-configuring Relax-and-Recover to create a TCG Opal pre-boot authentication (PBA) image
TIP: Your system seems to include a Plymouth graphical boot animation. You can achieve a nicer user
     interface for the PBA by setting OPAL_PBA_{PROGS,COPY_AS_IS,LIBS} to include Plymouth components.
Using autodetected kernel '/boot/vmlinuz-5.3.18-57-default' as kernel in the recovery system
Creating recovery system root filesystem skeleton layout
Handling network interface 'eth0'
eth0 is a physical device
Handled network interface 'eth0'
Included current keyboard mapping (via 'dumpkeys -f')
Included default US keyboard mapping /usr/share/kbd/keymaps/legacy/i386/qwerty/defkeymap.map.gz
Included other keyboard mappings in /usr/share/kbd/keymaps
Copying files and directories
Copying binaries and libraries
A list of executables with their dependencies has been stored in /tmp/rear.JeqjpKW3aQQoNjD/tmp/executable-dependencies
Copying only currently loaded kernel modules (MODULES contains 'loaded_modules') and those in MODULES_LOAD
Omit copying files in /lib*/firmware/ (FIRMWARE_FILES='no')
Skip copying broken symlink '/etc/mtab' target '/proc/22963/mounts' on /proc/ /sys/ /dev/ or /run/
Skip copying broken symlink '/etc/resolv.conf' target '/run/netconfig/resolv.conf' on /proc/ /sys/ /dev/ or /run/
Testing that the recovery system in /tmp/rear.JeqjpKW3aQQoNjD/rootfs contains a usable system
Testing each binary with 'ldd' and look for 'not found' libraries within the recovery system
Testing that the existing programs in the PROGS array can be found as executable command within the recovery system
Testing that each program in the REQUIRED_PROGS array can be found as executable command within the recovery system
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (37717853 bytes) in 7 seconds
Using Grub 2 to create an EFI bootloader
Creating 51 MiB raw disk image "TCG-Opal-PBA-localhost.raw"
Using syslinux to install a Legacy BIOS bootloader
Copying resulting files to file location
Saving /root/rear.github.master/var/log/rear/rear-localhost.log as rear-localhost.log to file location
Copying result files '/tmp/rear.JeqjpKW3aQQoNjD/tmp/TCG-Opal-PBA-localhost.raw /tmp/rear.JeqjpKW3aQQoNjD/tmp/VERSION /tmp/rear.JeqjpKW3aQQoNjD/tmp/README /tmp/rear.JeqjpKW3aQQoNjD/tmp/rear-localhost.log' to /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost at file location
Exiting rear mkopalpba (PID 3337) and its descendant processes ...
Running exit tasks
To remove the build area use (with caution): rm -Rf --one-file-system /tmp/rear.JeqjpKW3aQQoNjD

# find /tmp/rear.JeqjpKW3aQQoNjD/rootfs/ | grep 'usr/share/rear' | wc -l
23

# find /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost -ls
     2173      0 drwxr-x---   1 root     root          114 Jul  5 13:00 /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost
     2175  52224 -rw-------   1 root     root     53477376 Jul  5 13:00 /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost/TCG-Opal-PBA-localhost.raw
     2176      4 -rw-------   1 root     root          279 Jul  5 13:00 /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost/VERSION
     2177      4 -rw-------   1 root     root          505 Jul  5 13:00 /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost/README
     2178   1844 -rw-------   1 root     root      1886762 Jul  5 13:00 /root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost/rear-localhost.log


# usr/sbin/rear -D mkrescue
Relax-and-Recover 2.6 / Git
Running rear mkrescue (PID 31087 date 2021-07-05 13:02:13)
Command line options: usr/sbin/rear -D mkrescue
Using log file: /root/rear.github.master/var/log/rear/rear-localhost.log
Using build area: /tmp/rear.20JBtUGj4EFKEv3
Running workflow mkrescue on the normal/original system
Using local PBA image file '/root/rear.github.master/var/lib/rear/TCG-Opal-PBA/localhost/TCG-Opal-PBA-localhost.raw'
Using autodetected kernel '/boot/vmlinuz-5.3.18-57-default' as kernel in the recovery system
Creating disk layout
Overwriting existing disk layout file /root/rear.github.master/var/lib/rear/layout/disklayout.conf
SLES12-SP1 (and later) btrfs subvolumes setup needed for /dev/mapper/system-root (default subvolume path contains '@/.snapshots/')
Added  /dev/mapper/system-root to BTRFS_SUBVOLUME_SLES_SETUP in /tmp/rear.20JBtUGj4EFKEv3/rootfs/etc/rear/rescue.conf
Disabling excluded components in /root/rear.github.master/var/lib/rear/layout/disklayout.conf
Using sysconfig bootloader 'grub2'
Verifying that the entries in /root/rear.github.master/var/lib/rear/layout/disklayout.conf are correct
Created disk layout (check the results in /root/rear.github.master/var/lib/rear/layout/disklayout.conf)
Creating recovery system root filesystem skeleton layout
Handling network interface 'eth0'
eth0 is a physical device
Handled network interface 'eth0'
Included current keyboard mapping (via 'dumpkeys -f')
Included default US keyboard mapping /usr/share/kbd/keymaps/legacy/i386/qwerty/defkeymap.map.gz
Included other keyboard mappings in /usr/share/kbd/keymaps
Copying logfile /root/rear.github.master/var/log/rear/rear-localhost.log into initramfs as '/tmp/rear-localhost-partial-2021-07-05T13:02:20+02:00.log'
Copying files and directories
Copying binaries and libraries
Copying only currently loaded kernel modules (MODULES contains 'loaded_modules') and those in MODULES_LOAD
Omit copying files in /lib*/firmware/ (FIRMWARE_FILES='no')
Skip copying broken symlink '/etc/mtab' target '/proc/11678/mounts' on /proc/ /sys/ /dev/ or /run/
Skip copying broken symlink '/etc/resolv.conf' target '/run/netconfig/resolv.conf' on /proc/ /sys/ /dev/ or /run/
Testing that the recovery system in /tmp/rear.20JBtUGj4EFKEv3/rootfs contains a usable system
Testing each binary with 'ldd' and look for 'not found' libraries within the recovery system
Testing that the existing programs in the PROGS array can be found as executable command within the recovery system
Testing that each program in the REQUIRED_PROGS array can be found as executable command within the recovery system
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (108225402 bytes) in 14 seconds
Using Grub 2 to create an EFI bootloader
Creating 122 MiB raw disk image "rear-localhost.raw"
Using syslinux to install a Legacy BIOS bootloader
Copying resulting files to file location
Saving /root/rear.github.master/var/log/rear/rear-localhost.log as rear-localhost.log to file location
Copying result files '/tmp/rear.20JBtUGj4EFKEv3/tmp/rear-localhost.raw.gz /tmp/rear.20JBtUGj4EFKEv3/tmp/VERSION /tmp/rear.20JBtUGj4EFKEv3/tmp/README /tmp/rear.20JBtUGj4EFKEv3/tmp/rear-localhost.log' to /var/lib/rear/output/localhost at file location
Exiting rear mkrescue (PID 31087) and its descendant processes ...
Running exit tasks
To remove the build area use (with caution): rm -Rf --one-file-system /tmp/rear.20JBtUGj4EFKEv3

# find /tmp/rear.20JBtUGj4EFKEv3/rootfs/ | grep 'usr/share/rear' | wc -l
1521

# find /var/lib/rear/output/localhost -ls
    14494      0 drwxr-x---   1 root     root          104 Jul  5 13:03 /var/lib/rear/output/localhost
    14496 114144 -rw-------   1 root     root     116879576 Jul  5 13:03 /var/lib/rear/output/localhost/rear-localhost.raw.gz
    14497      4 -rw-------   1 root     root           279 Jul  5 13:03 /var/lib/rear/output/localhost/VERSION
    14498      4 -rw-------   1 root     root           505 Jul  5 13:03 /var/lib/rear/output/localhost/README
    14499   1708 -rw-------   1 root     root       1745275 Jul  5 13:03 /var/lib/rear/output/localhost/rear-localhost.log
```

So "rear mkopalpba" made a TCG-Opal-PBA-localhost.raw
that seems to contain only 23 files of usr/share/rear
(only some usr/share/rear/lib/*functions.sh files)
while "rear mkrescue" made a rear-localhost.raw.gz
that contains all of usr/share/rear (1521 files of usr/share/rear in my case).

Because I am not a OPAL user and I do not have a self-encrypting disk
I cannot tell if the above made TCG-Opal-PBA-localhost.raw is right
i.e. I cannot verify if it works as described in the section
```
Administering Self-Encrypting Disks
  Creating a Pre-Boot Authentication (PBA) System
```
in
https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc

**Comment by tigaente** [comment]
Hi,
thanks a lot for your reply. My problem, however, is not with the SEDs. It is with the rescue system. Let me explain:

My plan is as follows:

1. Create a REAR rescue image with OPAL PBA support
2. Put the rescue image on a USB disk and boot from it. This way I can make sure I have a recovery system to disable drive encryption if anything breaks.
3. Enable drive encryption (or to be more precise: enable drive locking) to enforce the encryption
4. Install the PBA into the ShadowMBR on the Boot drive
5. Power-down, reboot and hope for the best :)

Right now, I fail at point 2. I can create the rescue image and boot from it. However, in the rescue system the 'rear' command does not work because it wants to source some files from /usr/share/rear which simply are not present in the rescue system.

For what it's worth though, here is what I did right now, to create the rescue image:

1. Clone github-repo to local disk: `git clone https://github.com/rear/rear`
2. Run rear command from local git repo to create the PBA: `usr/sbin/rear -D mkopalpba`
`Relax-and-Recover 2.6 / Git
Running rear mkopalpba (PID 144340 date 2021-07-05 15:46:37)
Command line options: usr/sbin/rear -D mkopalpba
Using log file: /root/rear/var/log/rear/rear-Andi-PC.log
Using build area: /tmp/rear.usWP6A4ijL9HUAZ
Running workflow mkopalpba on the normal/original system
Re-configuring Relax-and-Recover to create a TCG Opal pre-boot authentication (PBA) image
Found EFI system partition /dev/sda1 on /boot/efi type vfat
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Using specified KERNEL_FILE '/boot/vmlinuz-5.12-x86_64' as kernel in the recovery system
Creating recovery system root filesystem skeleton layout
Handling network interface 'enp3s0'
enp3s0 is a physical device
Handled network interface 'enp3s0'
Included current keyboard mapping (via 'dumpkeys -f')
Included default US keyboard mapping /usr/share/kbd/keymaps/i386/qwerty/defkeymap.map.gz
Included other keyboard mappings in /usr/share/kbd/keymaps
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/Manjaro/grubx64.efi' as UEFI bootloader file
Copying files and directories
Copying binaries and libraries
A list of executables with their dependencies has been stored in /tmp/rear.usWP6A4ijL9HUAZ/tmp/executable-dependencies
Copying only currently loaded kernel modules (MODULES contains 'loaded_modules') and those in MODULES_LOAD
Omit copying files in /lib*/firmware/ (FIRMWARE_FILES='no')
Skip copying broken symlink '/etc/mtab' target '/proc/158648/mounts' on /proc/ /sys/ /dev/ or /run/
Testing that the recovery system in /tmp/rear.usWP6A4ijL9HUAZ/rootfs contains a usable system
Testing each binary with 'ldd' and look for 'not found' libraries within the recovery system
Testing that the existing programs in the PROGS array can be found as executable command within the recovery system
Testing that each program in the REQUIRED_PROGS array can be found as executable command within the recovery system
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (47872007 bytes) in 5 seconds
Using Grub 2 to create an EFI bootloader
TIP: You can achieve a faster EFI boot by installing syslinux for EFI on this system
Creating 60 MiB raw disk image "TCG-Opal-PBA-Andi-PC.raw"
Copying resulting files to file location
Saving /root/rear/var/log/rear/rear-Andi-PC.log as rear-Andi-PC.log to file location
Copying result files '/tmp/rear.usWP6A4ijL9HUAZ/tmp/TCG-Opal-PBA-Andi-PC.raw /tmp/rear.usWP6A4ijL9HUAZ/tmp/VERSION /tmp/rear.usWP6A4ijL9HUAZ/tmp/README /tmp/rear.usWP6A4ijL9HUAZ/tmp/rear-Andi-PC.log' to /root/rear/var/lib/rear/TCG-Opal-PBA/Andi-PC at file location
Exiting rear mkopalpba (PID 144340) and its descendant processes ...
Running exit tasks
To remove the build area use (with caution): rm -Rf --one-file-system /tmp/rear.usWP6A4ijL9HUAZ`
3. Run rear command from local git repo to create the rescue image: `usr/sbin/rear -D mkrescue`
`Relax-and-Recover 2.6 / Git
Running rear mkrescue (PID 164282 date 2021-07-05 15:49:16)
Command line options: usr/sbin/rear -D mkrescue
Using log file: /root/rear/var/log/rear/rear-Andi-PC.log
Using build area: /tmp/rear.CE8YrMBCmLDpY7U
Running workflow mkrescue on the normal/original system
Found EFI system partition /dev/sda1 on /boot/efi type vfat
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Using local PBA image file '/root/rear/var/lib/rear/TCG-Opal-PBA/Andi-PC/TCG-Opal-PBA-Andi-PC.raw'
Using specified KERNEL_FILE '/boot/vmlinuz-5.12-x86_64' as kernel in the recovery system
Creating disk layout
Automatically excluding disk /dev/sdc (not used by any mounted filesystem)
Marking component '/dev/sdc' as done in /root/rear/var/lib/rear/layout/disktodo.conf
Dependant component /dev/sdc1 is a child of component /dev/sdc
Marking component '/dev/sdc1' as done in /root/rear/var/lib/rear/layout/disktodo.conf
Automatically excluding disk /dev/sdd (not used by any mounted filesystem)
Marking component '/dev/sdd' as done in /root/rear/var/lib/rear/layout/disktodo.conf
Dependant component /dev/sdd1 is a child of component /dev/sdd
Marking component '/dev/sdd1' as done in /root/rear/var/lib/rear/layout/disktodo.conf
Disabling excluded components in /root/rear/var/lib/rear/layout/disklayout.conf
Disabling component 'disk /dev/sdc' in /root/rear/var/lib/rear/layout/disklayout.conf
Disabling component 'part /dev/sdc' in /root/rear/var/lib/rear/layout/disklayout.conf
Disabling component 'disk /dev/sdd' in /root/rear/var/lib/rear/layout/disklayout.conf
Disabling component 'part /dev/sdd' in /root/rear/var/lib/rear/layout/disklayout.conf
Using guessed bootloader 'EFI' (found in first bytes on /dev/sda)
Verifying that the entries in /root/rear/var/lib/rear/layout/disklayout.conf are correct
Created disk layout (check the results in /root/rear/var/lib/rear/layout/disklayout.conf)
Creating recovery system root filesystem skeleton layout
Handling network interface 'enp3s0'
enp3s0 is a physical device
Handled network interface 'enp3s0'
Included current keyboard mapping (via 'dumpkeys -f')
Included default US keyboard mapping /usr/share/kbd/keymaps/i386/qwerty/defkeymap.map.gz
Included other keyboard mappings in /usr/share/kbd/keymaps
To log into the recovery system via ssh set up /root/.ssh/authorized_keys or specify SSH_ROOT_PASSWORD
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/Manjaro/grubx64.efi' as UEFI bootloader file
Copying logfile /root/rear/var/log/rear/rear-Andi-PC.log into initramfs as '/tmp/rear-Andi-PC-partial-2021-07-05T15:49:22+02:00.log'
Copying files and directories
Copying binaries and libraries
Copying all kernel modules in /lib/modules/5.12.9-1-MANJARO (MODULES contains 'all_modules')
Copying all files in /lib*/firmware/
**Symlink '/usr/share/rear' -> '/usr/share/rear' refers to a non-existing directory on the recovery system.
It will not be copied by default. You can include '/usr/share/rear' via the 'COPY_AS_IS' configuration variable.**
Skip copying broken symlink '/etc/mtab' target '/proc/175343/mounts' on /proc/ /sys/ /dev/ or /run/
Testing that the recovery system in /tmp/rear.CE8YrMBCmLDpY7U/rootfs contains a usable system
Testing each binary with 'ldd' and look for 'not found' libraries within the recovery system
Testing that the existing programs in the PROGS array can be found as executable command within the recovery system
Testing that each program in the REQUIRED_PROGS array can be found as executable command within the recovery system
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (609214371 bytes) in 42 seconds
Using Grub 2 to create an EFI bootloader
TIP: You can achieve a faster EFI boot by installing syslinux for EFI on this system
Creating 633 MiB raw disk image "rear-Andi-PC.raw"
Copying resulting files to file location
Saving /root/rear/var/log/rear/rear-Andi-PC.log as rear-Andi-PC.log to file location
Copying result files '/tmp/rear.CE8YrMBCmLDpY7U/tmp/rear-Andi-PC.raw.gz /tmp/rear.CE8YrMBCmLDpY7U/tmp/VERSION /tmp/rear.CE8YrMBCmLDpY7U/tmp/README /tmp/rear.CE8YrMBCmLDpY7U/tmp/rear-Andi-PC.log' to /var/lib/rear/output/Andi-PC at file location
Exiting rear mkrescue (PID 164282) and its descendant processes ...
Running exit tasks
To remove the build area use (with caution): rm -Rf --one-file-system /tmp/rear.CE8YrMBCmLDpY7U`

Again, as you can see it mentions some symlink error to a non-existant directory on the recovery system. I do not understand the reason, though. The files are there on the system that I use to create the rescue image. Why do they not get copied? And why is it trying to copy from /usr/share/rear and not usr/share/rear? ShouIdn't it take all the files from the loca github repo version?

Thanks,
Andi

**Comment by tigaente** [comment]
So.. using COPY_AS_IS solved it, but I do not really understand why and what the difference is.

**Comment by jsmeix** [comment]
I never had a symlink `/usr/share/rear -> /usr/share/rear`
so this seems to be the root cause in your particular case.

I have no idea why you have such a symlink.
Normally you should not have such a symlink.

E.g. in my `git clone https://github.com/rear/rear.git` directory
```
localhost:~/rear.github.master # find . -type l -ls | less
```
does not show such a symlink.

**Comment by jsmeix** [comment]
FYI
why symbolic links must be copied as symbolic links
see the comment in build/GNU/Linux/100_copy_as_is.sh
https://github.com/rear/rear/blob/master/usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
```
Symbolic links must be copied as symbolic links ('tar -h' must not be used here)
because 'tar -h' does not finish and blows up the recovery system to Gigabytes,
see https://github.com/rear/rear/pull/1636
```

**Comment by tigaente** [comment]
Hi,
so I double-checked like four times. I also do not have a symlink to /usr/share/rear nor is it one. That is the reason why I am so dumbfounded by that message.

But anyway.. I managed to get the OPAL thing working. Both disks are now locked. However, rear let me down with the OPAL enabling and locking procedure as well and I also do not use the rear-created PBA because that cannot unlock the disks for whatever reason. I use the one provided by chubbyant. You can find it on www.sedutil.com or https://github.com/ChubbyAnt/sedutil/releases if you are interested.
