### ISSUE TITLE
Serial config for kernel commandline

### ISSUE THREAD

**Issue by DEvil0000** [rear/rear#2663]
The following line breaks serial for me on some hardware/kernels/bios versions if ttyS0 is also used.
This should not get added in such a case.
https://github.com/rear/rear/blob/6a3d0b4d5e73c69a62ce0bd209b2b38ffb462569/usr/share/rear/rescue/GNU/Linux/400_use_serial_console.sh#L24

Also I still think it would be better to have an option for devices which should be used instead of using all tty devs found. This is true for every occurance of this search tty code.

**Comment by jsmeix** [comment]
Yes, that whole serial console code should be overhauled.

It is also rather old code that I tried to ignore as good as I could
(in particular because I do not have serial console hardware)
but it seems someone ;-) again forces me to finally clean up things :-)

**Comment by DEvil0000** [comment]
As an additional note on this issue:
From my understanding having `console=ttyS0,115200n8` and `console=tty0` in the kernel line should actually work and did work for all ubuntu versions up to and including ubuntu18. My understanding is that some systemd and tty auto setup related bug causes the system not to start since ubuntu20 systemd changes.

Giving the user more control over which tty devices get used is a good idea in any case sine some may be connected to other devices/hardware and it may also be a security concern running getty on all of them.
