### ISSUE TITLE
Please start the restore process on your backup host during recovery

### ISSUE THREAD

**Issue by 4thomasmueller** [rear/rear#2670]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6-git.4317.be8b6ed.master / 2021-04-21

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
"SUSE Linux Enterprise Server 12 SP5"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): 
OUTPUT=ISO
ISO_PREFIX="rear-nfs-$HOSTNAME"
OUTPUT_URL=nfs://192.168.16.210/share/iso
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://192.168.16.210/share/backup
#KEEP_OLD_OUTPUT_COPY=yes
AUTOEXCLUDE_MULTIPATH=y
EXCLUDE_MOUNTPOINTS=('/global')

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
VMware Workstation 16

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0   15G  0 disk 
└─sda1            8:1    0   15G  0 part 
  ├─system-swap 254:0    0  1,4G  0 lvm  [SWAP]
  └─system-root 254:1    0   10G  0 lvm  /
sdb               8:16   0    1G  0 disk 
sdc               8:32   0    2G  0 disk 
└─sdc1            8:33   0    2G  0 part /global
sdd               8:48   0    3G  0 disk 
└─sdd1            8:49   0    3G  0 part /srv/www/htdocs
sr0              11:0    1 1024M  0 rom  
sr1              11:1    1 1024M  0 rom

* Description of the issue (ideally so that others can reproduce it):
Backup:
on system do a rear -v mkbackup -C /etc/rear/nfs-local.conf
Rescuemedia and backuparchive will be created
Restore:
on system boot the created recovery iso file
login as root
do rear -v recover
Disklayout will be created, NIC mapping is alos done, the the message "Please start the restore process on your backup host" like if I set BACKUP=REQUESTRESTORE, but I set BACKUP=NETFS

![rear_1](https://user-images.githubusercontent.com/42620376/129712435-fef91dd2-39cc-4bb5-8cc5-be112be9cef0.png)
![rear_2](https://user-images.githubusercontent.com/42620376/129712438-068d30f2-c576-4742-8cc1-6735ed683074.png)
![rear_3](https://user-images.githubusercontent.com/42620376/129712441-2fb9f511-74c4-4411-907e-60f8f766658a.png)

**Comment by 4thomasmueller** [comment]
Update/Workaround: cp /etc/rear/nfs-local.conf /etc/rear/local.conf and run rear -v mkbackup without any other configfile.
But what effect has got the option -C <alternative_configfile> compared to default local.conf??

**Comment by gdha** [comment]
@4thomasmueller Did you try to add the option `-C ...` before the `mkbackup` command? See https://github.com/rear/rear/blob/master/doc/user-guide/11-multiple-backups.adoc

**Comment by 4thomasmueller** [comment]
yes, I did it. But I've misunderstood that the -C option is additional to local.conf. All stuff in local.conf and it works.
Thx for reply
