### ISSUE TITLE
Failed to make bootable EFI image of GRUB2

### ISSUE THREAD

**Issue by nmaheve** [rear/rear#2674]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):  Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME=RHEL
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
[root@testl07dc ~]# cat /etc/rear/local.conf
# This file etc/rear/local.conf is intended for the user's
# manual configuration of Relax-and-Recover (ReaR).
# For configuration through packages and other automated means
# we recommend a separated file named site.conf next to this file
# and leave local.conf as is (ReaR upstream will never ship a site.conf).
# The default OUTPUT=ISO creates the ReaR rescue medium as ISO image.
# You need to specify your particular backup and restore method for your data
# as the default BACKUP=REQUESTRESTORE does not really do that (see "man rear").
# Configuration variables are documented in /usr/share/rear/conf/default.conf
# and the examples in /usr/share/rear/conf/examples/ can be used as templates.
# ReaR reads the configuration files via the bash builtin command 'source'
# so bash syntax like VARIABLE="value" (no spaces at '=') is mandatory.
# Because 'source' executes the content as bash scripts you can run commands
# within your configuration files, in particular commands to set different
# configuration values depending on certain conditions as you need like
# CONDITION_COMMAND && VARIABLE="special_value" || VARIABLE="usual_value"
# but that means CONDITION_COMMAND gets always executed when 'rear' is run
# so ensure nothing can go wrong if you run commands in configuration files.
# Sets output to an be an ISO file
OUTPUT=ISO
# # Specifies CDM as the backup and recovery application
BACKUP=CDM

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64/bind9-export"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PHYSICAL SERVER 

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64 x86_64 x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI & GRUB2
/boot/efi/EFI/redhat/grubx64.efi' as UEFI bootloader file

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk - SATA

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
Storage layout:
```
[root@testl07dc ~]# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 279.4G 0 disk
├─sda1 8:1 0 1000M 0 part
├─sda2 8:2 0 2G 0 part
├─sda3 8:3 0 90G 0 part
│ ├─rhel-home 253:0 0 20G 0 lvm
│ ├─rhel-root 253:1 0 100G 0 lvm
│ ├─rhel-var 253:2 0 20G 0 lvm
│ ├─rhel-tmp 253:3 0 10G 0 lvm
│ ├─rhel-swap 253:4 0 10G 0 lvm
│ └─rhel-opt 253:5 0 20G 0 lvm
├─sda4 8:4 0 2G 0 part /boot/efi
├─sda5 8:5 0 2G 0 part /boot
└─sda6 8:6 0 30G 0 part /var

sdb 8:16 0 279.4G 0 disk
├─sdb1 8:17 0 90G 0 part
│ └─rhel-root 253:1 0 100G 0 lvm
└─sdb2 8:18 0 189.4G 0 part /
```
* Description of the issue (ideally so that others can reproduce it):  

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by nmaheve** [comment]
Classification: Confidential
Hello Support team

Do we have any update on this ..
We have installed the package on server , and after installation I have tried to run the rear -D mkrescue but still we are same error .

I have uploaded  the log file  as well on portal , requesting you to please help us here to resolve this issue


Thanks ,
Nikhil Maheve

From: Nikhil Kumar Maheve
Sent: Friday, August 27, 2021 7:41 PM
To: 'rear/rear' ***@***.***>; 'rear/rear' ***@***.***>
Cc: 'Mention' ***@***.***>; Suraj Rawat ***@***.***>
Subject: RE: [rear/rear] Failed to make bootable EFI image of GRUB2 (#2674)

Classification: Confidential
Hello  Team ,

We have installed the package on server ..

Here is the output..

***@***.*** ~]# rpm -qa | grep grub2-efi-x64-modules
grub2-efi-x64-modules-2.02-0.87.el7_9.6.noarch
***@***.*** ~]#



Thanks ,
Nikhil Maheve

From: Nikhil Kumar Maheve
Sent: Friday, August 27, 2021 7:02 PM
To: rear/rear ***@***.******@***.***>>; rear/rear ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; Suraj Rawat ***@***.******@***.***>>
Subject: RE: [rear/rear] Failed to make bootable EFI image of GRUB2 (#2674)

Classification: Confidential

Sure will install and let u know

Thanks ,
Nikhil Maheve

**Comment by gdha** [comment]
@nmaheve The Grub2 creation was successful, however, you have some missing libraries:
```
Testing each binary with 'ldd' and look for 'not found' libraries within the recovery system
/usr/lib64/eog/plugins/libfullscreen.so requires additional libraries
        libeog.so => not found
/usr/lib64/eog/plugins/libreload.so requires additional libraries
        libeog.so => not found
/usr/lib64/eog/plugins/libstatusbar-date.so requires additional libraries
        libeog.so => not found
/usr/lib64/samba/pdb/smbpasswd.so requires additional libraries
```
Try to change the following [entry](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1818) in the /etc/rear/.local.conf file:
```
COPY_AS_IS_CDM=( /etc/rubrik /usr/bin/rubrik /var/log/rubrik /etc/pki /usr/lib64/*)
```

**Comment by nmaheve** [comment]
[log.txt](https://github.com/rear/rear/files/7078116/log.txt)
 please have done the changes 
we have copied complete  COPY_AS_IS_CDM=( /etc/rubrik /usr/bin/rubrik /var/log/rubrik /etc/pki /usr/lib64/*)
 in .local.conf file 

please suggest

**Comment by nmaheve** [comment]
hello Support ,
 
please suggest  we are waiting for your response ..

**Comment by gdha** [comment]
@nmaheve Please check where on your live system these missing libraries, e.g. libeog.so, resides. E.g. try
`find /  -name "libeog.so*"` to find the path. If that path is different then `/usr/lib64` add it to the variable `COPY_AS_IS_CDM` (in assumption you are still using `BACKUP=CDM`)

**Comment by nmaheve** [comment]
here is the output  of local.conf file 

OUTPUT=ISO
# # Specifies CDM as the backup and recovery application
#BACKUP=CDM
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64/bind9-export"
COPY_AS_IS_CDM=( /etc/rubrik /usr/bin/rubrik /var/log/rubrik /etc/pki /usr/lib64/*


we have commented the backup=CDM 
after that we have run the  rear -D mkrescue and the output is attached here 
[log.txt](https://github.com/rear/rear/files/7092708/log.txt)

**Comment by gdha** [comment]
@nmaheve If you comment out `BACKUP=CDM` then the line `COPY_AS_IS_CDM` will not be used. And, did you forget to end  it with `)` ?
Within ReaR everything is a bash script, so you can test it with `bash -n /etc/rear/local.conf` (should not complain).

What is the content of  ` ls /etc/ld.so.conf.d/` ? I think within ReaR root fs the /etc/ld.so.conf file is missing a library path. For example, for Legato we had to add something like `/usr/share/rear/build/NSR/default/550_add_nsr_libs_to_ldsoconf.sh` to add some missing  library paths. Could be an equivalent issue.

**Comment by pcahyna** [comment]
Concerning the original issue.

> Can you confirm package grub2-efi-x64-modules is present on your system? See also issue #2600

There are several reports of the same issue, like #1193 and #2524 . As you can see from https://github.com/rear/rear/issues/1193#issuecomment-451450705, I proposed to add a warning that hints what package to install, but at the end a more generic message was chosen: https://github.com/rear/rear/issues/1193#issuecomment-452617591 that does not mention the specific package:

> If we detect something is missing, we will not tell the user what software package
> (e.g. a rpm or deb package or whatever else) he must install to get the missing piece
> because we cannot continuously track and maintain for all those various kind
> of different Linux distributions what particular software package provides
what program or file in what version of each Linux distribution.

**Comment by jsmeix** [comment]
@pcahyna 
to avoid misunderstandings:

My statement in
https://github.com/rear/rear/issues/1193#issuecomment-452617591
that we will not tell the user what software package is missing
was meant for the generic code in ReaR, cf. what @gdha wrote in
https://github.com/rear/rear/issues/1193#issuecomment-451450705
"if we decide to add this we should verify the OS version".

So we could have distribution specific code provided:

Distribution specific code is properly conditioned,
See the SetOSVendorAndVersion() function in lib/config-functions.sh
what variables are set how to which vaules to distinguish between
different distributions and distribution versions.
See layout/prepare/Linux-s390/205_s390_enable_disk.sh
for an example of distribution specific code inside a script.

AND

There is someone who continuously tracks and maintains
distribution specific code to keep it up to date in the future.


By the way as an additional side note
in general regarding the word `WARNING` in messages see
https://schlomo.schapiro.org/2015/04/warning-is-waste-of-my-time.html
and for background information see
https://github.com/rear/rear/issues/564#issuecomment-86188528
and the subsequent comments therein.

**Comment by pcahyna** [comment]
@jsmeix thanks for the clarification, this separation of distribution-specific code makes sense. I will resubmit the change in a way that respects the separation. 
Concerning WARNING, I think it can be justified if it explains an error that is expected to happen in the next step (so that in the output you see the error immediately preceded by the warning that explains its likely cause and action to take). Of course, the explanatory message could be printed only when the actual error occurs, but then it will be harder to maintain it separately in a distribution-specific code.

**Comment by bbabaria** [comment]
Thank you
I already tried that method to exclude those library and getting error "rubrik cluster couldn't connect to the agent while run restore using that ISO (size is decreased to 733MB to 300MB)

**Comment by pcahyna** [comment]
Hello @DamaniN, you wrote the Rubrik CDM support, could you please help here?

**Comment by DamaniN** [comment]
@bbabaria,

Please refer to https://github.com/rear/rear/issues/2685#issuecomment-935098986 to troubleshoot the issue you are seeing.

**Comment by DamaniN** [comment]
@nmaheve,

Please update your `LD_LIBRARY_PATH` in the `local.conf` file to include:

`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64/bind9-export:/usr/lib64/eog:/usr/lib64/python3.6/site-packages:/usr/lib64/samba:/usr/lib64/firefox:/usr/lib64/python3.6/site-packages/haw
key:/usr/lib64/mutter-4"`

**Comment by jsmeix** [comment]
In general FYI regarding LD_LIBRARY_PATH:

In general using LD_LIBRARY_PATH is known to cause troubles, cf.
https://github.com/rear/rear/issues/1907#issuecomment-434215448
which links to
https://www.hpc.dtu.dk/?page_id=1180
"LD_LIBRARY_PATH – or: How to get yourself into trouble!"
which further links to
http://xahlee.info/UnixResource_dir/_/ldpath.html
"Why LD_LIBRARY_PATH is bad"

In particular using `export LD_LIBRARY_PATH="..."`
is usually really bad, see
https://www.hpc.dtu.dk/?page_id=1180
that reads (excerpt)
```
Do NOT do:

$ export LD_LIBRARY_PATH=/path/to/lib1:/path/to/lib2:/path/to/lib3
$ ./myprog

since this will pollute the shell environment for all consecutive commands!

Never put LD_LIBRARY_PATH in your login profiles!
In that way you will expose all the applications you start
to this – probably problematic – path!
```

**Comment by bbabaria** [comment]
Hi Pcahyna,

Please find the attached log files.
Thank you,
[rear-njidlpuppet01.log](https://github.com/rear/rear/files/7295567/rear-njidlpuppet01.log)

**Comment by marcus9467** [comment]
@nmaheve can you post an update on how you were able to create the ISO on the original server? 

I spent some time with the team this afternoon after they were able to create an ISO from the RHEL 7.9 server. Attempting to recover presented some additional challenges though. 

Appended to the default /etc/rear/local.conf was:
`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64/bind9-export:/usr/lib64/eog:/usr/lib64/python3.6/site-packages:/usr/lib64/samba:/usr/lib64/firefox:/usr/lib64/python3.6/site-packages/hawkey:/usr/lib64/mutter-4"`

After the recovery attempt the logs showed the following:
![image (1)](https://user-images.githubusercontent.com/41637724/140553572-3f050bae-403f-44b8-8ca0-a27987230cf2.png)
![image (2)](https://user-images.githubusercontent.com/41637724/140553756-686293f3-b34b-4f0d-b077-557767822944.png)

**Comment by nmaheve** [comment]
Classification: Confidential
Hello Support ,

We  were facing issue while creating the  As per Redhat recommendation, we uninstall the rear packages  provided by Rubrik and install the required packages from Redhat repository.  Then , tried  to create backup using CDM backup option and  run command rear  -v mkresuce  to create ISO  on path /var/lib/rear/output. It ran successfully without any errors and  ISO  image has been created  as backup on the server.


Please refer the  attached case history



Thanks ,
Nikhil Maheve

**Comment by DamaniN** [comment]
@nmaheve, It looks like the issue you are having now, as shown by the screenshots posted by @marcus9467, is with reformatting the disks on the recovery system. This is a new issue and should be created as such in GitHub. That will allow others who work on that part of the code to respond. Since this is not a CDM related issue, the people on this issue thread may not be able to help. Please create a new issue on this repo with the screenshots and description that @marcus9467 posted so that others who deal with that part of the ReaR code can help.

**Comment by gdha** [comment]
@nmaheve  can this issue be closed for you?

**Comment by sk0al** [comment]
I am facing a similar error, however I am running oracle linux 8.7.  I do have grub2 utils installed.  I have updated my LD_LIBRARY_PATH as stated in the thread above but still have the same error.  How do you want me to proceed with a new issue or ?

**Comment by jsmeix** [comment]
See https://github.com/rear/rear/issues/2897
and https://github.com/rear/rear/issues/2783
