### ISSUE TITLE
Formatting USB drive for efi is broken

### ISSUE THREAD

**Issue by bearpebble** [rear/rear#2680]
#### Relax-and-Recover (ReaR) Issue Template

* ReaR version ("/usr/sbin/rear -V"):
`Relax-and-Recover 2.6 / Git (7c42e2bd3e600d059f24bd0b46526700c1d8bda0)`

* Description of the issue (ideally so that others can reproduce it):
Using `usr/sbin/rear format -v -- --efi /dev/sd...` does not create the layout required for EFI.<br>
The switch `--efi` is simply ignored, as it sets `FORMAT_EFI=y`, which is never used anywhere else in the code.
https://github.com/rear/rear/blob/7c42e2bd3e600d059f24bd0b46526700c1d8bda0/usr/share/rear/lib/format-workflow.sh#L32-L33

* Workaround, if any:
Put the line `EFI=$FORMAT_EFI` right before the following line, since `$EFI` is never set anywhere.
https://github.com/rear/rear/blob/7c42e2bd3e600d059f24bd0b46526700c1d8bda0/usr/share/rear/format/USB/default/300_format_usb_disk.sh#L59-L61

**Comment by gozora** [comment]
Shouldn't it be `usr/sbin/rear format -v -- --efi /dev/sd` (with tow dashes in fromt of `efi`) ?

V.

**Comment by bearpebble** [comment]
@gozora you are right, that was a typo in the issue. Sorry about that.
Unfortunately that is not the problem. I used the correct command and it only worked after I applied the workaround, i.e. edited the code

**Comment by jsmeix** [comment]
@bearpebble 
thank you for your issue report.
It is a bug caused by me.

**Comment by jsmeix** [comment]
Should now be fixed via
https://github.com/rear/rear/commit/d032145b15a9e9c7f8df63d4bfe1e977b41cafee

@bearpebble 
please test if our latest GitHub master code that contains
that above commit works for you, cf. the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by bearpebble** [comment]
The `usr/sbin/rear format -v -- --efi /dev/sd...` command works as expected using d032145.
Thanks for the quick fix @jsmeix

**Comment by jsmeix** [comment]
@bearpebble 
thank you for your prompt test and feedback!

**Comment by jsmeix** [comment]
I think less than one hour from initial user bug report
to final user confirmation that the fix actaully works
is probably our fastest case that we had here.
So - now it's time for my morning coffee and breakfast...
