### ISSUE TITLE
ERROR: Could not create ISO image

### ISSUE THREAD

**Issue by LightSlight** [rear/rear#2682]
I was configured the OUTPUT and BACKUP variables like follows:

OUTPUT=ISO
OUTPUT_URL=file:///path/backup/
BACKUP=NETFS
NACKUP_URL=iso:///backup/

as you can see, i‘m trying to include the backup file within the ISO  image. And then i run "rear  -v mkbackup",it didn't work , show me a problem as title say.Can anyone help me with this question? Thanks a lot.

**Comment by jsmeix** [comment]
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by LightSlight** [comment]
Fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

ReaR version ("/usr/sbin/rear -V"):
‘’‘
Relax-and-Recover 2.4 / Git
’‘’

OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
‘’‘
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
’‘’

ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
'''
OUTPUT=ISO
OUTPUT_URL=file:///mnt/part_sdb1/backup/
BACKUP=NETFS
BACKUP_URL=iso:///backup/
'''
Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
‘’‘
VMware workstation guest
’‘’

System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
'''
x86_64
'''
Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
'''
BIOS and GRUB
'''

Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
'''
local disk
'''
Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT"):
'''
NAME                                         KNAME     PKNAME     TRAN TYPE FSTYPE             SIZE     MOUNTPOINT
/dev/sda                                    /dev/sda                        spi     disk                            20G 
|-/dev/sda1                                /dev/sda1  /dev/sda               part   xfs                     500M  /boot
`-/dev/sda2                                /dev/sda2  /dev/sda               part   LVM2_member 19.5G 
  |-/dev/mapper/centos-root     /dev/dm-0 /dev/sda2             lvm    xfs                    15.5G  /
  `-/dev/mapper/centos-swap   /dev/dm-1 /dev/sda2             lvm    swap                 4G      [SWAP]
/dev/sdb                                    /dev/sdb                        spi    disk                            20G 
`-/dev/sdb1                                /dev/sdb1 /dev/sdb               part   ext3                  20G      /mnt/part_sdb1
/dev/sr0                                     /dev/sr0                         ata    rom   iso9660            4.4G     /run/media/root/CentOS 7 x86_64
'''

Description of the issue (ideally so that others can reproduce it):
'''
I run the 'rear -v mkbackup'  command, the error message like follow:
Making ISO image
ERROR: Could not create ISO image (with /usr/bin/xorrisofs)
'''

Workaround, if any:

Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
'''
The output log like this :

Making ISO image
GNU xorriso 1.4.8 : RockRidge filesystem manipulator, libburnia project.
Drive current: -outdev 'stdio:/var/lib/rear/output/rear-localhost.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 2388m free
Added to ISO image: directory '/'='/tmp/rear.PbpAwds8h081Qdo/tmp/isofs'
xorriso : UPDATE : 18 files added in 1 seconds
xorriso : UPDATE : 18 files added in 1 seconds
xorriso : FAILURE : Image size 2250465s exceeds free space on media 1222618s
libisofs: MISHAP : Image write cancelled
xorriso : NOTE : -return_with SORRY 32 triggered by problem severity FAILURE
2021-09-29 09:37:44.974080483 ERROR: Could not create ISO image (with /usr/bin/xorrisofs)

FAILURE shows image size exceeds free space , but actually i output the ISO into another disk that mounted on '/mnt/part_sdb1/' and there is  enough space.
'''

Did I express myself clearly enough? What the problem might be?

**Comment by pcahyna** [comment]
> FAILURE shows image size exceeds free space , but actually i output the ISO into another disk that mounted on '/mnt/part_sdb1/' and there is enough space.

ReaR builds the image in its space (see `/var/lib/rear/output/rear-localhost.iso` in the xorriso messages) and then copies it to `OUTPUT_URL`. Not sure if you can instruct it to write to `OUTPUT_URL` directly.

**Comment by pcahyna** [comment]
In other words, you may have enough space at your `OUTPUT_URL`, but not enough in `/var`.

**Comment by pcahyna** [comment]
I found how to instruct ReaR to write somewhere else: set `ISO_DIR` (by default it is `$VAR_DIR/output`) and set `OUTPUT_URL=null` (to avoid a second copy). See the description in `/usr/share/rear/conf/default.conf`.

**Comment by LightSlight** [comment]
It worked! I appreciate that.Thank you so much!

**Comment by LightSlight** [comment]
@pcahyna  It worked! I appreciate that.Thank you so much!

**Comment by jsmeix** [comment]
@pcahyna 
thank you for your analysis and for finding a solution.
