### ISSUE TITLE
OUTPUT=USB support for UEFI and BIOS dual boot (cf. OUTPUT=RAWDISK)

### ISSUE THREAD

**Issue by DEvil0000** [rear/rear#2698]
At the moment creating a boot media does only support legacy BIOS boot or UEFI boot but not both from within the same image. I think this is true in general but definitely for USB media.
It should be possible to create boot media supporting both modes in the same image.
The format command does have a --efi option and default/without --efi goes the legacy BIOS boot route.

Proposed changes:
* add a --bios switch which only does legacy bios installs.
* change format without --efi/--bios to create a hybrid stick
* make grub the default bootloader (since I know this one best and know how to do it with that)
* small partitoning changes may be needed
* bootloader auto detect in rescue/default/850_save_sysfs_uefi_vars.sh needs to get changed (must work if booted in legacy and no boot/efi, efivars and efibootmgr is availabe) e.g. UEFI_BOOTLOADER=/usr/lib/grub/x86_64-efi/monolithic/grubx64.efi

If you agree I will start the next days to prepare a PR.

**Comment by jsmeix** [comment]
@DEvil0000 
of cource I agree when you do a PR.
I appreciate it and I look forward to it.

In the end if we could come to one single generic bootloader setup
for the bootloader of the ReaR recovery system that is by default
`Hybrid UEFI and BIOS with GRUB2 as bootloader`
it could be a great step forward to get that part of ReaR simple and straightforward.

**Comment by pcahyna** [comment]
Is it really possible to create an image which supports both BIOS and UEFI? In particular, would a disk with an EFI partition table (I suppose it is needed for UEFI support?) be bootable by BIOS?

**Comment by jsmeix** [comment]
I guess one could have both a bios_grub partition and a ESP
and have their partitioning data both in MBR and in a GPT
so a disk with a ReaR recovery system could have a partitioning like
* free space for GPT (e.g. up to USB_PARTITION_ALIGN_BLOCK_SIZE)
* 8 MiB bios_grub partition
* 512 MiB ESP
* /boot partition with USB_BOOT_PART_SIZE
* ReaR data partition up to USB_DEVICE_FILESYSTEM_PERCENTAGE
* free space for secondary GPT at the end of the disk
so that four partitions could be both in MBR and in a GPT and
kernel, initrd, and GRUB2 could be hopefully installed (e.g. two times as neded)
so that it can boot both with BIOS firmware and UEFI firmware.
I would hope that BIOS firmware ignores GPT and ESP and
that UEFI firmware ignores MBR and bios_grub partition.

**Comment by OliverO2** [comment]
It's already there in ReaR. To quote from [rear/03-configuration.adoc](https://github.com/rear/rear/blob/master/doc/user-guide/03-configuration.adoc#rescue-media-output) (emphasis added):

> OUTPUT=RAWDISK
Create a bootable raw disk image on as rear-$(hostname).raw.gz. Supports UEFI boot if syslinux/EFI or Grub 2/EFI is installed. Supports Legacy BIOS boot if syslinux is installed. **Supports UEFI/Legacy BIOS dual boot** if syslinux and one of the supported EFI bootloaders are installed.

**Comment by OliverO2** [comment]
The creation of `RAWDISK` output was guided by a number of factors:

1. the defined goal of creating a PBA for TCG OPAL-2-compliant self-encrypting disks,
2. the quality, comprehensibility, and fitness for re-use of existing code, 
3. the volume of tests required to support all the options available,
4. the risk of inadvertently breaking existing functionality,
5. last not least: finite resources.

Not using the "lib" functions was a deliberate decision based on careful research.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2705 merged
"rear format" has now in addition to the --efi switch a --bios switch.
If none is given (i.e. by default) it will now do hybrid formatting
with a BIOS boot partition (on GPT) and an EFI system partition.
This is a precondition for this issue here.

**Comment by jsmeix** [comment]
I postponed this issue to ReaR 2.8
