### ISSUE TITLE
/var/tmp running out of space during iso creation

### ISSUE THREAD

**Issue by humis988** [rear/rear#2700]

**Comment by gdha** [comment]
@humis988  please fill in the template, otherwise, we need to close this issue.

**Comment by humis988** [comment]
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

ReaR version ("/usr/sbin/rear -V"):

```
Relax-and-Recover 2.6-git.4538.7c42e2b.master
```
OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
Oracle Linux Server release 7.9
```


ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

```
cat /etc/rear/site.conf
# local rear /etc/rear/site.conf file
# recommended not to change local.conf and to crate site.conf
# when using package management
# see /etc/rear/local.conf
# configured for Rubrik BMR
# iso written to /var/lib/rear/output/
# and also copied to OUTPUT_URL as specified below
OUTPUT=ISO
BACKUP=CDM
OUTPUT_URL=file:///root/restoreinfo
```


Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
ovm / kvm / hp physical hardware - current testing with kvm

System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86

Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

test vm is bios

Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

kvm host uses fc


Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT"):

** /var below was expanded to facilitate testing

``` 
lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT
NAME                             KNAME     PKNAME    TRAN TYPE FSTYPE       SIZE MOUNTPOINT
/dev/sr0                         /dev/sr0            ata  rom              1024M
/dev/sda                         /dev/sda                 disk              150G
|-/dev/sda2                      /dev/sda2 /dev/sda       part LVM2_member   96G
| |-/dev/mapper/ol-swap          /dev/dm-1 /dev/sda2      lvm  swap          16G [SWAP]
| |-/dev/mapper/ol-usr_openv     /dev/dm-8 /dev/sda2      lvm  xfs            5G /usr/openv
| |-/dev/mapper/ol-tmp           /dev/dm-6 /dev/sda2      lvm  xfs           16G /tmp
| |-/dev/mapper/ol-var_log       /dev/dm-4 /dev/sda2      lvm  xfs            5G /var/log
| |-/dev/mapper/ol-home          /dev/dm-2 /dev/sda2      lvm  xfs           16G /home
| |-/dev/mapper/ol-root          /dev/dm-0 /dev/sda2      lvm  xfs           16G /
| |-/dev/mapper/ol-opt           /dev/dm-7 /dev/sda2      lvm  xfs           16G /opt
| |-/dev/mapper/ol-var_log_audit /dev/dm-5 /dev/sda2      lvm  xfs            1G /var/log/audit
| `-/dev/mapper/ol-var           /dev/dm-3 /dev/sda2      lvm  xfs           50G /var
|-/dev/sda3                      /dev/sda3 /dev/sda       part LVM2_member   53G
| `-/dev/mapper/ol-var           /dev/dm-3 /dev/sda3      lvm  xfs           50G /var
`-/dev/sda1                      /dev/sda1 /dev/sda       part xfs            1G /boot
```

Description of the issue (ideally so that others can reproduce it):

/var running out of space during iso creation

Workaround, if any:

looking for options?

Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like

**Comment by humis988** [comment]
Looks good - quick  and a little dirty approximate results below.  This provides an answer to my question and will avoid having to expand /var for the time being.

Thank you!

OUTPUT_URL=file:///root/restoreinfo

export TMPDIR="${TMPDIR-/opt/reartmp}"

~ .9 on /var
~ 4 on /opt
iso ~ .9 GB

with ISO_DIR=:/root/restoreinfo

/var ~ 0
/opt ~ 3.3 Gb
iso ~ 1 GB

**Comment by jsmeix** [comment]
This issue is likely fixed via https://github.com/rear/rear/pull/2747
