### ISSUE TITLE
ReaR USB, error filesystem vfat will not be supported

### ISSUE THREAD

**Issue by Chownx** [rear/rear#2707]
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
BACKUP=NETFS
TIMESTAMP=$(date +%d-%m-%Y_%H:%M)
OUTPUT=USB
USE_RESOLV_CONF="no"
BACKUP_PROG=tar
BACKUP_URL="usb:///dev/sdc1"
USB_UEFI_PART_SIZE="512"
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
X86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS / GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SSD and HD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT"):
```
NAME        KNAME     PKNAME   TRAN   TYPE FSTYPE   SIZE MOUNTPOINT
/dev/sda    /dev/sda           sata   disk        698,6G 
`-/dev/sda1 /dev/sda1 /dev/sda        part btrfs  698,6G /mnt/btrfs_pool
/dev/sdb    /dev/sdb           sata   disk        238,5G 
|-/dev/sdb1 /dev/sdb1 /dev/sdb        part btrfs    953M /boot
|-/dev/sdb2 /dev/sdb2 /dev/sdb        part swap    14,9G [SWAP]
`-/dev/sdb3 /dev/sdb3 /dev/sdb        part btrfs  222,6G /home
```

* Description of the issue (ideally so that others can reproduce it):
I have to tried to make a ReaR USB with below details,
but always get the same error: 
```
ERROR: Filesystem 'vfat' will not be supported.
Saved /var/log/rear/rear-irix.log as rear/irix/20211108.2314/rear-irix.log
ERROR: Filesystem 'vfat' will not be supported.
Some latest log messages since the last called script 850_make_USB_bootable.sh:
  2021-11-08 23:15:53.913609798 Including output/USB/Linux-i386/850_make_USB_bootable.sh
Aborting due to an error, check /var/log/rear/rear-irix.log for details
Exiting rear mkbackup (PID 56515) and its descendant processes ...
Running exit tasks
```
I dont have any vfat filesystem on my laptop and i could not to find out
whta is the root cause, can you please help me ?

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by Chownx** [comment]
Hi jsmeix, 
Thanks a lot for your quick response. To be honest I did the format to USB stick, but I will do double check again. 

Thanks a lot.

**Comment by Chownx** [comment]
Hi jsmeix,

you were right, the problem was due to the USB partition. I have to remove the  current partition and do the rear format /dev/sdX again. 

Thanks a lot for your support.

**Comment by jsmeix** [comment]
@Chownx 
thank you for the prompt feedback what the root cause was.
It is important for us at ReaR upstream to get such explicit feedback
so we know whether or not there could be a hidden issue inside ReaR.

**Comment by jsmeix** [comment]
@Chownx 
wait - I think I found something - you have
```
BACKUP_URL="usb:///dev/sdc1"
USB_UEFI_PART_SIZE="512"
```
which indicates you did `rear format -- --efi /dev/sdc`
and then /dev/sdc1 will be the EFI system partition (ESP)
but I guess you don't wnat to store your backup in the ESP ;-)
so I think your BACKUP_URL points to the wrong partition.
You need the ReaR data partition as BACKUP_URL.
By default the filesystem on theReaR data partition
is labeled REAR-000 by the ‘format’ workflow so the usual
```
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
```
cf. http://relax-and-recover.org/documentation/getting-started
should "just work".
