### ISSUE TITLE
Support for http targets in PXE 

### ISSUE THREAD

**Issue by Flunkyball** [rear/rear#2733]
Due to performance reasons I want the kernel and initrd information to be pulled via http instead of tftp.
There is currently no option to tell rear that the kernel and initrd is a http target.
A typical produced config looks like this:

```
[...]
MENU title Relax-and-Recover v2.6
display CLIENT/CLIENT.message
say ----------------------------------------------------------
[...]
ENDTEXT
    kernel CLIENT/CLIENT.kernel
    append initrd=CLIENT/CLIENT.initrd.cgz root=/dev/ram0 vga=normal rw  selinux=0
say ----------------------------------------------------------
[...]
```
Manually adding the necessary http information works pretty fine:

```
kernel http://pxe-over-http-srv:7777/CLIENT/CLIENT.kernel
append initrd=http://pxe-over-http-srv:7777/CLIENT/CLIENT.initrd.cgz root=/dev/ram0 vga=normal rw  selinux=0
```

**Comment by Flunkyball** [comment]
I created an pull request for that including the code that works fine for me.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2738 merged
this issue should be done.

@Flunkyball 
thank you for your contribution to ReaR!
