### ISSUE TITLE
ReaR- Testing BMR on Linux physical server so we need to know server hardware requirement 

### ISSUE THREAD

**Issue by suraj952** [rear/rear#2737]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by suraj952** [comment]
Here is your query answered as much as we have:-

ReaR version ("/usr/sbin/rear -V"): **2.6.5 (latest available)**

OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): **RHEL 8.0**

ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): **HPE ProLiant DL380 Gen9**

System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): **x86_64**

Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): **UEFI GRUB2**

Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): **DM**

Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

Description of the issue (ideally so that others can reproduce it): We were trying to do testing on Physical server using 7.9rhel OS version but its failing to recover each and every time so we are going to try on RHEL 8.0 OS version hence we need to know if any specific hardware requirement should be placed prior testing the bare metal recovery.

Workaround, if any: NA as of now

Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by pcahyna** [comment]
Hello @suraj952, no specific hardware is required by ReaR, but some hardware (especially storage) setups can be unsupported. I know of two cases: IMSM RAID (#2702) and iSCSI storage. From a quick look at the HPE ProLiant DL380 Gen9 specs, I don't see anything that should be unsupported. Since you will apparently use this hardware to test recovery of some other systems, you should make the system as close as possible to your production system.

**Comment by jsmeix** [comment]
Regarding iSCSI see
https://github.com/rear/rear/issues/2429
`Implement iSCSI support (currently iSCSI needs special manual setup)`
where in particular
https://github.com/rear/rear/issues/2429#issuecomment-645626221
and
https://github.com/rear/rear/issues/2429#issuecomment-646216100
show an example of special manual setup that is needed for iSCSI.

**Comment by jsmeix** [comment]
@suraj952 
in general see in particular the section
"Fully compatible replacement hardware is needed" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
I assume this question was sufficiently answered.
