### ISSUE TITLE
Create only rear ISO with borg binary

### ISSUE THREAD

**Issue by mitch-geht-ab** [rear/rear#2769]
* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

```
root@debian:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

depends, see below

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

VM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86

* Description of the issue (ideally so that others can reproduce it):

Hi,
I have a script for backing up system files with borg, also including /boot partition etc.
Would be great to have a rear ISO to recover the system, including the borg binary, to recover my own backup via NFS mount.
Means, do my daily borg backup script jobs and from time to time a "rear mkrescue".
And in case of a DR, mount ISO, do the rear rescue (partition and bootloader restore), mount manually my NFS share, start manually my borg restore.

Tried to create an ISO-only with BACKUP=BORG but all the time, the rear+borg implementation scripts try to mount an USB stick (which fails) and stopped.

What worked, for an ISO-only without Borg binary:

```
cat /etc/rear/local.conf
OUTPUT=ISO
OUTPUT_URL=null
GRUB_RESCUE=n
```

What I tried and failed:

```
cat /etc/rear/local-borg.conf
OUTPUT=ISO
OUTPUT_URL=null
GRUB_RESCUE=n
BACKUP=BORG
```

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

```
root@debian:~# rear -v mkrescue
Relax-and-Recover 2.6 / Git
Running rear mkrescue (PID 19886)
Using log file: /var/log/rear/rear-debian.log
Running workflow mkrescue on the normal/original system
Couldn't list Borg repository '' on USB
Borg: /tmp/rear.ufpTrEFH8yOpIAc/borg_backup is not a valid repository. Check repo config.
ERROR: Failed to initialize Borg repository, borg rc 2!
Some latest log messages since the last called script 300_init_archive.sh:
  2022-03-10 12:48:38.297758104 Including prep/BORG/default/300_init_archive.sh
  2022-03-10 12:48:38.676694719 Couldn't list Borg repository '' on USB
  2022-03-10 12:48:38.684851097 Borg: /tmp/rear.ufpTrEFH8yOpIAc/borg_backup is not a valid repository. Check repo config.
Aborting due to an error, check /var/log/rear/rear-debian.log for details
Exiting rear mkrescue (PID 19886) and its descendant processes ...
Running exit tasks
Terminated
root@debian:~#
```

Have also attached you the  rear.log:
[rear-debian.log](https://github.com/rear/rear/files/8223106/rear-debian.log)

**Comment by jsmeix** [comment]
I am not a Borg backup user so cannot
actually help with Borg backup specific issues.

As fas as I see in
https://github.com/rear/rear/blob/master/doc/user-guide/04-scenarios.adoc
therein in the section "ReaR with Borg back end"
it looks as if several more config options are needed
to make things work with BACKUP=BORG.

In general regarding issues with third-party backup tools:
Usually we at ReaR upstream do not use third-party backup tools
so usually we cannot reproduce issues with third-party backup tools.
Nevertheless we try to help as good as we can from plain looking at the code.
You may also have a look at the related general section
"Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery
