### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by danboid** [rear/rear#2773]
I would like to see rear gain support for backing up and recovering ZFS disks including root on ZFS disks eg Proxmox VE and Ubuntu are two distros that let the user easily install to a ZFS root pool. I just grepped the rear source tree for `zpool` and `zfs` and got no results so I think its a safe assumption to make that it currently has no support for ZFS.

I would recommend using syncoid (part of sanoid) for replicating ZFS snapshots.

**Comment by jsmeix** [comment]
See https://github.com/rear/rear/issues/1932
and https://github.com/rear/rear/issues/2563

**Comment by danboid** [comment]
I don't know if enough people are interested in using rear with ZFS to justify adding those links as a response to a new "Does rear support ZFS?" question in [the FAQ?](http://relax-and-recover.org/documentation/faq)
