### ISSUE TITLE
Question: Adequate REAR Validation Measures ?

### ISSUE THREAD

**Issue by paulra1** [rear/rear#2782]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.6-git.0.0.master.changed / 2022-03-11

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): Ubuntu 20.04.3

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): local.conf
```
# Linux rear, Relax-and-Recover, local.conf configuration file. This version
# is for an Ubuntu 20.4 OS and version 2.6-git.0.0 of rear.
#
# These settings are for creating an image an an external USB hard disk that
# includes both a boot partition and ext4 file system partition and can be
# used for bare metal recovery.
#
# Setting USB indicates the external USB hard disk is a USB device.
#
OUTPUT=USB
#
# Using NETFS indicates the USB disk is an external device.
#
BACKUP=NETFS
#
# REAR-000 is the label of the ext4 partition on the USB disk.
#
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
#
# The maximum size of the EFI partition in megabytes.
# 
USB_UEFI_PART_SIZE=1024
# This indicates the data is stored with an ext4 file system.
#
USB_DEVICE_FILESYSTEM=ext4
#
# These make progress reporting easier to track.
#
PROGRESS_MODE=plain
PROGRESS_WAIT_SECONDS=3
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): N/A

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): AMD64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"): Approximate
```
NAME             KNAME          PKNAME       TRAN   TYPE FSTYPE   LABEL    SIZE MOUNTPOINT
/dev/loop0       /dev/loop0                         loop squashfs        938.5M /snap/android-studio/118
/dev/loop1       /dev/loop1                         loop squashfs         55.5M /snap/core18/2284
/dev/loop2       /dev/loop2                         loop squashfs            4K /snap/bare/5
/dev/loop3       /dev/loop3                         loop squashfs        938.5M /snap/android-studio/119
/dev/loop4       /dev/loop4                         loop squashfs         55.5M /snap/core18/2344
/dev/loop6       /dev/loop6                         loop squashfs         61.9M /snap/core20/1376
/dev/loop7       /dev/loop7                         loop squashfs        248.8M /snap/gnome-3-38-2004/99
/dev/loop8       /dev/loop8                         loop squashfs        247.9M /snap/gnome-3-38-2004/87
/dev/loop9       /dev/loop9                         loop squashfs         54.2M /snap/snap-store/558
/dev/loop10      /dev/loop10                        loop squashfs         43.6M /snap/snapd/15177
/dev/loop11      /dev/loop11                        loop squashfs         49.8M /snap/snap-store/467
/dev/loop12      /dev/loop12                        loop squashfs        164.8M /snap/gnome-3-28-1804/161
/dev/loop13      /dev/loop13                        loop squashfs         65.2M /snap/gtk-common-themes/1519
/dev/loop14      /dev/loop14                        loop squashfs         62.1M /snap/gtk-common-themes/1506
/dev/loop15      /dev/loop15                        loop squashfs          219M /snap/gnome-3-34-1804/77
/dev/loop16      /dev/loop16                        loop squashfs        391.3M /snap/gimp/383
/dev/loop17      /dev/loop17                        loop squashfs        255.6M /snap/gnome-3-34-1804/36
/dev/loop18      /dev/loop18                        loop squashfs         43.6M /snap/snapd/14978
/dev/loop19      /dev/loop19                        loop squashfs         61.9M /snap/core20/1405
/dev/nvme0n1     /dev/nvme0n1                nvme   disk                 931.5G 
|-/dev/nvme0n1p1 /dev/nvme0n1p1 /dev/nvme0n1 nvme   part vfat     EFI      512M /boot/efi
|-/dev/nvme0n1p2 /dev/nvme0n1p2 /dev/nvme0n1 nvme   part ext4     Ubuntu   927G /
`-/dev/nvme0n1p3 /dev/nvme0n1p3 /dev/nvme0n1 nvme   part swap                4G [SWAP]
```

* Description of the issue (ideally so that others can reproduce it):
Dear Staff:

I would like to prove that the bare-metal rear backup procedures I developed for the System76
machine, described below, are valid. However, I don't have a spare System76 machine. I think,
but don't know, if the procedures work on the Dell machine, described below, configured with
the same Linux OS version as the System76 machine, the same backup procedures will also
work for the System76 machine.

In your opinion, is performing rear validation on the Dell machine sufficient to prove the same
set of procedures used for the Dell machine will also work for the System76 machine?
(Assume they have machines have same release of the Ubuntu 20.04.3 LTS OS installed on them.)

The System76 machine is described by the following link.

	https://tech-docs.system76.com/models/gaze16/README.html

It has an 11th Gen Intel® Core™ i7-11800H @ 2.30GHz × 16 processor, 16GB RAM, and a 1TB SSD.

The Dell Latitude machine is described by the following links.

	https://i.dell.com/sites/content/shared-content/data-sheets/en/documents/latitude-e6420-spec-sheet.pdf
	https://ark.intel.com/content/www/us/en/ark/products/52229/intel-core-i52520m-processor-3m-cache-up-to-3-20-ghz.html

It has a i5-2520M @ 2.5Ghz processor, 8GB RAM and a 128GB SSD.

Both of the above machines have AMD64 architecture and satisfy the Ubuntu requirements described by
the following link.

	https://linuxconfig.org/ubuntu-20-04-system-requirements

The sequence of validation procedures is as follows.

* Install Linux Ubuntu 20.04.3 LTS on the machine.

* Use "rear mkbackup" on an external USB disk to create a rescue disk with both boot and data sectors.

* Erase the internal disk on the machine.

* Use the rear image on thee external USB disk to restore the machine.

Best Regards,

Paul R.
* 

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by gdha** [comment]
@paulra1 Hi - thanks for using ReaR, however, you cannot expect from us that we validate your hardware setup. The ultimate test has to be done by you. Don't be afraid to test it out as thousands of other end-users already did it before you.
If you encounter a bug with ReaR then submit an issue, but hope that won't be necessary.

**Comment by paulra1** [comment]
Hi gdah
I understand and don't expect validatation of my hardware setup and that is not the topiic of the case.
The case is in fact an opinion question. In particular, I would like to know if you and your colleagues
believe the strategy I described in adequate to verify that a rear backup will work. What prompted it
is that I am unable to perform a direct test because I don't have the right kind of spare machine.

Best Regards,
Paul R.

**Comment by paulra1** [comment]
Hi Johannes:

Thank you for your lucid explanation. I don't believe my question could be addressed better,
and think the the case should be closed.

You are right that the Dell machine is just being used as a playground and your comments make
it clear that the rear configuration behavior on the Dell machine has only limited applicatility
to how the configuration will behave on another machine--for instance the System76 machine.

While both machines are UEFI machines, their BIOS are significantly different.
In addition, as you pointed out, the differences in low level SSD layout merits
careful consideration.

Best Regards,

Paul R.

**Comment by jsmeix** [comment]
@paulra1 
thank you for your feedback!

Only as a side note FYI:
To avoid confusion I recommend to use the word BIOS
only if you mean the legacy firmware in PC architecture
and also when you use the firmware in legacy BIOS mode
but the word EFI or UEFI if you mean nowadays firmware
that you use in its native way (i.e. as [U]EFI bootloader)
and the word firmware as generic name for such kind of software
that is provided built-in by the manufactuer of the raw hardware.
