### ISSUE TITLE
Unable to restore with incremental backup - 'backup.tar.gz' not found

### ISSUE THREAD

**Issue by tpebcp** [rear/rear#2793]
Relax-and-Recover 2.6 / 2020-06-17

/etc/rear/site.conf
```
OUTPUT=ISO
OUTPUT_URL=nfs://vesta/log/
BACKUP=NETFS
BACKUP_URL=nfs://vesta/log/
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
FULLBACKUPDAY="Sun"
BACKUP_TYPE=incremental
NETFS_KEEP_OLD_BACKUP_COPY=y
```

Environment
KVM, x86/64, BIOS with local disk on target server.
OS = Red Hat Enterprise Linux release 8.4

* Description of the issue (ideally so that others can reproduce it):

I'm trying the feature 'incremental backup', backup seems to work,
but I cannot restore automatically because of 'backup.tar.gz missing'.
I found a workaround (rename the fullbackup tar ball to backup.tar.gz)
but not sure if this is the right approach.

My procedure is:
I used rear mkbackup -d -v to create first full backup.
I can restore the system with full backup, that's OK.
But after I changed the site.conf and use incremental,
I can see the rear knows my plan:
```
Latest full backup found (2022-04-15-1835-F.tar.gz) triggers incremental backup
Performing incremental backup for files newer than 2022-04-15 using backup archive '2022-04-15-1843-I.tar.gz'
```

But I got two folders from my NFS server 'vesta':
```
z84
z84.old
```
(z84 is my test server name, the backup target)

And both folders contain tar.gz file like
```
z84/2022-04-16-0812-I.tar.gz         // incremental backup, a few MBs
z84.old/2022-04-16-0745-F.tar.gz     // full backup. 2.6GB
```

No backup.tar.gz and that leads to a issue when I use boot ISO file to restore the system:
```
Using backup.tar.gz for backup restore
Will do driver migration (recreating initramfs/initrd)
ERROR: Backup archive 'backup.tar.gz' not found.
Some latest log messages since the last called script 550_check_backup_archive.sh:
  2022-04-16 08:52:43.776712293 Including verify/NETFS/default/550_check_backup_archive.sh
```

Indeed I don't have backup.tar.gz because rear deleted during my last backup??
```
[root@vesta z84] # cat rear-z84.log | grep tar.gz
(omitted)
removed '/tmp/rear.rIesEYcrrtple4r/outputfs/z84.old/backup.tar.gz'
```

Please advise what I am doing wrong?

Workaround:
If I copy z84.old/2022-04-16-0745-F.tar.gz(full backup)
to z84/backup.tar.gz on NFS server and rear can resume,
and restoration seems to work...

**Comment by jsmeix** [comment]
See usr/share/rear/conf/default.conf (excerpt)
```
# Incremental or differential backup and NETFS_KEEP_OLD_BACKUP_COPY contradict each other so that
# NETFS_KEEP_OLD_BACKUP_COPY must not be 'true' in case of incremental or differential backup
# because NETFS_KEEP_OLD_BACKUP_COPY would move an already existing backup directory away
# but for incremental or differential backup an already existing backup directory must stay there
# so that after the initial full backup the incremental or differential backups can be stored therein.
```
which is currently online at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1334

I recommend to read the whole section in usr/share/rear/conf/default.conf
about incremental or differential backup which starts currently online at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1329
