### ISSUE TITLE
Setting the bootloader

### ISSUE THREAD

**Issue by danboid** [rear/rear#2817]
I have a few machines where sda and the first few disks are GPT formatted then the OS disks are something like sdh and sdi etc and these use GRUB2  installed in a BIOS partition to boot. Because of this, rear incorrectly chooses to use EFI as the bootloader for backup and restore purposes which will cause the USB rear disk to fail to boot.

I cannot find any documentation on how to manually define the bootloader type to use so I had to read the source code. The user has to create a file `/etc/sysconfig/bootloader` containing:

```
LOADER_TYPE="grub2"
```

To force rear to use BIOS grub recovery.

I think this is a very important point to note and so I think this should be covered in the README / Quickstart guide but I wanted to discuss it here first because maybe we should expose this as a command line option or make it possible to specify this in the main rear config file because I think /etc/sysconfig/bootloader is specific to Suse Linux. The /etc/sysconfig dir doesn't exist at all by default under Ubuntu so its a bit messy having to create that dir/file for this one setting.

**Comment by danboid** [comment]
Looking into this a bit more, I think I should actually be using

```
LOADER_TYPE="GRUB"
```

Because that is the string I see if I check the output of a command like:

```
dd if=/dev/sdh bs=512 count=4 | strings > boottest
```

These machines are definitely using grub2 as their bootloader but they return GRUB so why is there also a `grub2` bootloader setting? Does it make any difference? Should I recreate my backups using `LOADER_TYPE="GRUB"`?

**Comment by pcahyna** [comment]
Hello, I am curious about what is happening with firmware detection. It seems that you are saying that ReaR detects it should use an EFI bootloader, because it sees that the first disks have an EFI partition label. Are you sure about that? IIRC ReaR detects EFI according to the content of `/sys/firmware`, but maybe I have misunderstood.

**Comment by danboid** [comment]
The script that checks for EFI vs BIOS is rear/layout/save/default/445_guess_bootloader.sh

It takes a dd sample of the first 4 blocks of all your disks (starting with hd* and sd*) then greps the strings output of those boot blocks for GRUB/GRUB2 etc UNLESS you have a  `/etc/sysconfig/bootloader` file present to override the auto detection.

**Comment by danboid** [comment]
> Can you please describe what issue are you having, or is this report purely a result of code analysis? Or, do you see anything in the ReaR log that makes you think the rescue image or backup is somehow wrong? If so, please include the relevant log snippet.

I've already explained the root cause of my doubt and the reason I opened this ticket. I have a few machines that are UEFI capable but I have set them up to use BIOS boot because their OS disks are using mdadm software RAID which works best with BIOS GRUB booting. However, when I run rear with its default config I detects the bootloader as being EFI instead of GRUB.

So what difference does EFI vs GRUB make to rear? It must make a difference somewhere or else why are their scripts to detect it? Or am I worrying about nothing because it doesn't matter and rear can successfully restore a EFI image to a BIOS machine (I doubt it)?

Should rear be able to successfully restore my software RAID10 config?

**Comment by jsmeix** [comment]
@danboid 
you must try out and verify for each one of your machines
that "rear recover" actually works for you.
See in particular the section
"Inappropriate expectations" in
https://en.opensuse.org/SDB:Disaster_Recovery
and therein in particular the sub section
"No disaster recovery without testing and continuous validation"

**Comment by jsmeix** [comment]
@danboid 
see
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
what info we ususally need to be able to understand
how things look like on your particular system.
You get this when you click on the [New issue] button on
https://github.com/rear/rear/issues

**Comment by pcahyna** [comment]
@danboid 
> I've already explained the root cause of my doubt and the reason I opened this ticket. 

You have said:
> rear incorrectly chooses to use EFI as the bootloader for backup and restore purposes

but you have not said how do you know what ReaR chooses. I suppose you found out reading a log or in the program output, so please add the part of log file or output that makes you think so (the log preferably created using the -D option).

**Comment by danboid** [comment]
Am I correct in assuming then that rear cannot restore a mdraid (RAID 10) config?

**Comment by pcahyna** [comment]
Your assumption is generally not correct, I have tested that config recently (not for the boot disk though).

**Comment by danboid** [comment]
> but you have not said how do you know what ReaR chooses. I suppose you found out reading a log or in the program output, so please add the part of log file or output that makes you think so (the log preferably created using the -D option).

I run

```
rear mkbackup
```

And that print something like

```
Using guessed bootloader EFI for 'rear recover' (found in first bytes on $disk_device with GPT BIOS boot partiion)
```

**Comment by pcahyna** [comment]
> And that prints something like
> 
> ```
> Using guessed bootloader EFI for 'rear recover' (found in first bytes on $disk_device with GPT BIOS boot partiion)
> ```

This message comes from `usr/share/rear/layout/save/default/445_guess_bootloader.sh`, which sets the bootloader to be reinstalled (case B), not the bootloader on the USB rescue disk.

**Comment by danboid** [comment]
> > And that prints something like
> > ```
> > Using guessed bootloader EFI for 'rear recover' (found in first bytes on $disk_device with GPT BIOS boot partiion)
> > ```
> 
> This message comes from `usr/share/rear/layout/save/default/445_guess_bootloader.sh`, which sets the bootloader to be reinstalled (case B), not the bootloader on the USB rescue disk.

Yes, thats what I thought it was and it rear doesn't detect it correctly so I expect it would fail to restore correctly too.

**Comment by pcahyna** [comment]
> For example, sda-sdg are a ZFS pool then disks sdh-sdk are mdraid array. Does rear remember which disks it should be restoring to or will it prompt me when I run the recover? 

If the disks have the same names and same sizes, it should remember them (I believe it still prompts you to confirm disk mapping). But it needs to be tested for your specific case.

> Will it then re-install GRUB on each one of the disks in the mdraid array after restoring?

It reinstalls GRUB on the MBR of disks that contain the /boot partition, not sure about the details though.

**Comment by danboid** [comment]
For mdrarid arrays, GRUB needs to installed on each disk within the array. I might have to do that bit myself if rear doesn't do it for me.

**Comment by pcahyna** [comment]
> Unfortunately the various bootloader and EFI related
> user config variables that are described in
> usr/share/rear/conf/default.conf
> do not clearly distinguish between the two cases
> so things get rather tricky if bootloader specific
> settings are needed for special cases.

I think that `BOOTLOADER` is meant for case B and `USING_UEFI_BOOTLOADER` is meant for case A. But `usr/share/rear/finalize/Linux-i386/660_install_grub2.sh` is using `USING_UEFI_BOOTLOADER`, despite being intended to handle case B. Even more confusingly, a comment in the script says "The solution is to specify the BOOTLOADER config variable", but the script does not use that variable.

**Comment by pcahyna** [comment]
> For mdraid arrays, GRUB needs to installed on each disk within the array. I might have to do that bit myself if rear doesn't do it for me.

ReaR has a dependency resolution for storage components, so it installs GRUB to every device that `/boot` resides on (including devices that are RAID components) - so this should work.

**Comment by danboid** [comment]
I suppose my config is a niche case where the first disk doesn't reflect your firmware but I think this will still be common enough a issue to make mention of it in the README.

**Comment by pcahyna** [comment]
that was my understanding as well: the script does depend on `BOOTLOADER` indirectly (via `NOBOOTLOADER`), because other scripts check `BOOTLOADER` and then set `NOBOOTLOADER`.
