### ISSUE TITLE
New users cannot subscribe to mailing list

### ISSUE THREAD

**Issue by schlomo** [rear/rear#2832]
A user reported that he couldn't subscribe, who from @rear/contributors can fix this? I can provide more details privately

**Comment by jsmeix** [comment]
According to
https://github.com/rear/rear/pull/2819#issuecomment-1166895246
it seems the the ReaR mailing lists that are shown at
http://relax-and-recover.org/development/
are hosted at the mail system at host service.3ti.be

@gdha 
can you help with mail issues on service.3ti.be
or do you know who could help?
