### ISSUE TITLE
E-mail notification

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [rear/rear#2835]
Hello,

Not an issue, rather a configuration question.

I have a question about e-mail notifications.

From what I can see, there is no e-mail notification within ReaR?  (If I am wrong about that, can someone point me in the right direction)

And looking at crontab there only seems to be the ability to configure a single recipient.

Ideally what I would like is the following:

1.	Two recipients
a.	One for success
b.	One for fail
i.	And in an ideal world the failure notification would attach logs to the e-mail (although this isn’t essential). The main thing is to be aware that an error has occurred

Is what I have described possible?

If not, what do others do regarding monitoring?

Thank you

Regards,
Vaughan

**Comment by didacog** [comment]
hello @ZENAdmin-Ops no, there is no error notification within ReaR. If you are interested in error reporting, you may take a look at https://github.com/brainupdaters/drlm project and see if it suits you with that and other features to manage GNU/Linux DR using ReaR.

Hope this helped,
Regards,
Didac

**Comment by jsmeix** [comment]
We do not have any 'cron' file in the ReaR upstream source files
so I don't know what that "crontab there" is in the above
https://github.com/rear/rear/issues/2835#issue-1292225915

In the past some Linux distributions had a 'cron' file in their
ReaR package (e.g. a RPM package or something like that), cf.
https://github.com/rear/rear/issues/1892#issuecomment-410973078
In this case you may ask at the Linux distribution wherefrom
you got ReaR about things related to "using ReaR with cron" and
how that is meant to be used by the particular Linux distribution.

In general ReaR does not include things to manage ReaR
or things to manage backups and so on, cf. the section
"Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
I assume this issue is sufficiently answered so I close it.
Further comments may be added regardless that it is closed
or it could be reopened if needed.
