### ISSUE TITLE
P2V Restore RHEL 8 - Remove ioctl on mpathc failed: device busy

### ISSUE THREAD

**Issue by jssanche** [rear/rear#2837]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / 2020-06-17 

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=8
# The following information was added automatically by the mkbackup workflow:
OS='GNU/Linux'
OS_VERSION='8'
OS_VENDOR_VERSION='RedHatEnterpriseServer/8'
OS_VENDOR_ARCH='RedHatEnterpriseServer/i386'
OS_MASTER_VENDOR=FEDORA
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
AUTOEXCLUDE_MULTIPATH=n
OUTPUT=ISO
OUTPUT_URL=nfs://99.99.99.99/data/backup
BACKUP=NETFS
BACKUP_URL=nfs://99.99.99.99/data/backup
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
VMware VM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
X86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

device-mapper: remove ioctl on mpathc1 failed: Device or resource busy. 

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jssanche** [comment]
Hello!
This is a P2V restore using ReaR, the original server is a RHEL8 X86 server, the destination server is a VMware Virtual Machine. This is the step by step procedure to recover the Physical Server in the destination virtual server...

1. Boot the VM with ReaR ISO backup file.
2. Assing IP ADDRESS and ROUTER information from the command line. 
3. Starting the MULTIPATH Daemon from command mode: #modprobe dm-multipath and # /bin/multipathd 
4. Reconfigure the /etc/multipath.conf file with the WWID of every available VMDISK
5. Reconfigure the multipath: # multipath reconfigure
6. Run ReaR with manual recover (selecting every destination VMDisk)
7. ReaR fails during the mapping process, the LOG message:  Remove ioctl on mpathc1 failed: device or resource busy. 
Please your help. 

Note: Physical server has multipath enable.

**Comment by jsmeix** [comment]
@pcahyna 
because this issue is about RHEL
could you have a look here
as far as time permits?
