### ISSUE TITLE
EXTERNAL_IGNORE_ERRORS not checked against RSYNC

### ISSUE THREAD

**Issue by fadamo** [rear/rear#2870]
As per /usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh, backup via rsyncd does not care about config:

````
```
# The following exit codes from EXTERNAL_* should not abort the backup or recovery
# This example is useful for rsync
EXTERNAL_IGNORE_ERRORS=( 23 24 )
```
````
as /usr/share/rear/backup/EXTERNAL/default/500_make_backup_with_external.sh instead does.
Using rsync vanished files are quite familiar.
Is it possible to include an exit code check in 500_make_rsync_backup.sh ?

**Comment by jsmeix** [comment]
Currently EXTERNAL_IGNORE_ERRORS is meant only for BACKUP=EXTERNAL
according to how it is described in default.conf
currently online starting at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L2834

So what is needed is an enhancemnet for the BACKUP=RSYNC method
with a new separated config variable in default.conf
e.g. something similar as BORGBACKUP_IGNORE_WARNING
cf. https://github.com/rear/rear/pull/2846

**Comment by fadamo** [comment]
OK, btw the comment "# This example is useful for rsync" is misleading imo.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2872
there should be now a better (i.e. less misleading)
description of the BACKUP=EXTERNAL config variables
in default.conf.

**Comment by fadamo** [comment]
> @fadamo how do you deal with "rsync vanished files " right now ?

I currently have an almost endless list of exclusions. I am studying how to "inject" an error check without modifying the original ReaR scripts, otherwise at the first "yum update" I lose the changes. However I think the correct solution is to do as in /usr/share/rear/backup/EXTERNAL/default/500_make_backup_with_external.sh.
