### ISSUE TITLE
Could not copy /tmp/rear.EuPg57S6kXbLPM9/tmp/initrd.cgz to /tmp/rear-efi.yegNr//EFI/BOOT/initrd.cgz

### ISSUE THREAD

**Issue by kazi-md-munam** [rear/rear#2881]
[rear-localhost.log](https://github.com/rear/rear/files/9799177/rear-localhost.log)
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
```
$ /usr/sbin/rear -V
Relax-and-Recover 2.4 / Git
```

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
$ nano /etc/rear/os.conf

OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
$ nano /etc/rear/local.conf

OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
```
$ uname -a

Linux localhost.localdomain 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
 Firmware = UEFI 
 bootloader = GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
 local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

**It's Work for :
                     ( CentOS 7 Legacy BIOS  Successfully )
                     ( CentOS 7 UEFI  Error )
                     ( Miracle Linux 8.4 UEFI - Some time showing error some time do Successfully )**

 Issued command  **"sudo rear -v mkbackup"** 
Rear terminated with an error;
```
Relax-and-Recover 2.4 / Git
Using log file: /var/log/rear/rear-localhost.log
Using backup archive '/tmp/rear.EuPg57S6kXbLPM9/outputfs/rear/localhost/20221017.0859/backup.tar.gz'
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)

Created initrd.cgz with gzip default compression (284329435 bytes) in 37 seconds
ERROR: Could not copy /tmp/rear.EuPg57S6kXbLPM9/tmp/initrd.cgz to /tmp/rear-efi.yegNr//EFI/BOOT/initrd.cgz
Aborting due to an error, check /var/log/rear/rear-localhost.log for details
Exiting rear mkbackup (PID 887) and its descendant processes
Running exit tasks
/home/munam/Documents/build-QT_to_SHELL-Desktop-Debug/uxbd.sh: line 111:   879 Terminated              sudo rear -v mkbackup
```

* Workaround, if any:
I do not find any solution.

My system work in 
![Screenshot from 2022-10-14 02-08-46](https://user-images.githubusercontent.com/109643631/196087219-4f22006f-108d-4c5c-8341-b34a5fec7054.png)
![uefi](https://user-images.githubusercontent.com/109643631/196087309-ae39c971-8b89-4021-8017-47e9f03281a6.png)

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**sudo rear -v mkbackup**

MY LOG FILE:
==== Stack trace ====
Trace 0: /sbin/rear:547 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:24 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:101 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:49 Source
Trace 4: /usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh:40 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:372 StopIfError
Message: Could not copy /tmp/rear.EuPg57S6kXbLPM9/tmp/initrd.cgz to /tmp/rear-efi.yegNr//EFI/BOOT/initrd.cgz
== End stack trace ==
2022-10-17 09:01:02.066890562 Exiting rear mkbackup (PID 887) and its descendant processes
2022-10-17 09:01:03.166598591 rear,887 /sbin/rear -v mkbackup
  `-rear,20397 /sbin/rear -v mkbackup
      `-pstree,20398 -Aplau 887
/usr/share/rear/lib/_input-output-functions.sh: line 157: kill: (20401) - No such process
2022-10-17 09:01:03.203148745 Running exit tasks
2022-10-17 09:01:03.205099890 Finished in 78 seconds
2022-10-17 09:01:03.206747282 Removing build area /tmp/rear.EuPg57S6kXbLPM9
rmdir: removing directory, '/tmp/rear.EuPg57S6kXbLPM9'
2022-10-17 09:01:03.558644220 End of program reached

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jsmeix** [comment]
@kazi-md-munam 
the last item
```
Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files)
``
is missing,
i.e. you need to attach a 
```
# rear -D mkbackup
```
debug log file /var/log/rear/rear-localhost.log
so we can (hopefully) see what the actual error behind is why it
```
Could not copy /tmp/rear.EuPg57S6kXbLPM9/tmp/initrd.cgz to /tmp/rear-efi.yegNr//EFI/BOOT/initrd.cgz
```

**Comment by kazi-md-munam** [comment]
[rear-localhost.log](https://github.com/rear/rear/files/9799206/rear-localhost.log)
It's My log file

**Comment by kazi-md-munam** [comment]
> 
I also try  **rear -D mkbackup** But it's show same Error
 

I used this command for format my USB **sudo rear format -- --efi  /dev/sdb**                [/dev/sdb is my USB location]

**Comment by jsmeix** [comment]
Your
https://github.com/rear/rear/files/9799206/rear-localhost.log
tells it all:
```
cp: error writing '/tmp/rear-efi.yegNr//EFI/BOOT/initrd.cgz': No space left on device
```

See `USB_UEFI_PART_SIZE` in your usr/share/rear/conf/default.conf

In ReaR 2.4 usr/share/rear/conf/default.conf
https://github.com/rear/rear/blob/rear-2.4/usr/share/rear/conf/default.conf#L685
this was by default
```
USB_UEFI_PART_SIZE="200"
```
which is too small for nowadays bigger ReaR recovery systems
(the initrd.cgz contains the whole ReaR recovery systems).

In curent ReaR 2.7 usr/share/rear/conf/default.conf
https://github.com/rear/rear/blob/rear-2.7/usr/share/rear/conf/default.conf#L1053
this is meanwhile by default
```
USB_UEFI_PART_SIZE="1024"
```
see https://github.com/rear/rear/pull/1205
for background information why it increased all the time.

So you should set an appropriate USB_UEFI_PART_SIZE
as you need it in your etc/rear/local.conf
and then re-do
```
# rear format -- --efi /dev/sdb
```
to get your USB disk partitioned with a bigger ESP
(this will overwrite all what there is non your USB disk)
and then re-do
```
rear mkbackup
```

**Comment by kazi-md-munam** [comment]
@jsmeix   Thank You So Much.

 I did solve this problem based on your Suggestion.
