### ISSUE TITLE
USB formatting is really slow

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [rear/rear#2885]
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
2.6

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Ubuntu 22.04

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
Hyper-V

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
USB

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

Same issue as described in issue
https://github.com/rear/rear/issues/2761

lusb - t
produces no output?

I would like to identify a way to improve the speed of the formatting.

Is there a quickformat option for instance?

With Windows you can select quickformat,
which does not scan the target disk for bad sectors
and is many times quicker than a "standard" format.

* Workaround, if any:
This is what I'm looking for.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by DEvil0000** [comment]
this depends on:
* the device and bus speed
* the partition size
* the filesystem used

for some filesystems there are parameters to speed this up but then it takes longer later when writing. so there is a tradeoff.
I am sure parameters can get tuned but this is normally not the step taking long. In my case about 20s for a 64GB usb stick.
