### ISSUE TITLE
No further output during rear automatic recovery

### ISSUE THREAD

**Issue by will-code-for-pizza** [rear/rear#2895]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.7

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): Ubuntu 22.04

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
SSH_ROOT_PASSWORD=xxx
### write the rescue initramfs to USB and update the USB bootloader
OUTPUT=ISO
### create a backup using the internal NETFS method, using 'tar'
BACKUP=NETFS
### write both rescue image and backup to the device labeled REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
USB_DEVICE_FILESYSTEM=ext4
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): KVM guest

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_amd64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): QCOW2

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"): 
```
NAME        KNAME     PKNAME   TRAN   TYPE FSTYPE LABEL      SIZE MOUNTPOINT
/dev/sr0    /dev/sr0           sata   rom  udf    REAR-ISO 616.5M 
/dev/vda    /dev/vda                  disk                    25G 
|-/dev/vda1 /dev/vda1 /dev/vda        part vfat              487M /mnt/local/boo
`-/dev/vda2 /dev/vda2 /dev/vda        part ext4             24.5G /mnt/local
/dev/vdb    /dev/vdb                  disk                    40G 
|-/dev/vdb1 /dev/vdb1 /dev/vdb        part                     8M 
|-/dev/vdb2 /dev/vdb2 /dev/vdb        part vfat   REAR-EFI     1G 
`-/dev/vdb3 /dev/vdb3 /dev/vdb        part ext3   REAR-000    39G
```

* Description of the issue (ideally so that others can reproduce it):
After automatic recovering the system via boot ISO, there is no notification.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by will-code-for-pizza** [comment]
![image](https://user-images.githubusercontent.com/19435718/205592001-61a65001-af09-4129-9c52-f13c4906bd9b.png)

**Comment by jsmeix** [comment]
@will-code-for-pizza 
according to your screenshot in
https://github.com/rear/rear/issues/2895#issuecomment-1336961870
this issue is same as
https://github.com/rear/rear/issues/2843
therein in particular
https://github.com/rear/rear/issues/2843#issuecomment-1250843183
and the subsequent comments in particular
https://github.com/rear/rear/issues/2843#issuecomment-1196588256
and
https://github.com/rear/rear/issues/2843#issuecomment-1196592017

**Comment by will-code-for-pizza** [comment]
@jsmeix 
Thanks for your fast reply.
The mentioned patch in https://github.com/rear/rear/issues/2843 is still not part of rear 2.7 ?

Cheers.

**Comment by jsmeix** [comment]
@will-code-for-pizza 
I assume you could make it work for your use case
with some setting(s) of those config variables
```
USE_SERIAL_CONSOLE
SERIAL_CONSOLE_DEVICES
SERIAL_CONSOLE_DEVICES_KERNEL
SERIAL_CONSOLE_DEVICE_SYSLINUX
SERIAL_CONSOLE_DEVICE_GRUB
```

Could you provide feedback what exact setting(s)
made it work for you?

It is important for us at ReaR upstream to get such feedback
so we know how far things in ReaR also work for other users.
