### ISSUE TITLE
BACKUP_PROG_COMPRESS_OPTIONS="" makes 'tar ... -C /mnt/local/' untar in $(pwd) i.e. in /root

### ISSUE THREAD

**Issue by scprsync** [rear/rear#2911]
setting
BACKUP_PROG_COMPRESS_OPTIONS=""
BACKUP_PROG_COMPRESS_SUFFIX=""

makes a nice tar file in the backup, but fails to restore the files. i think its still trying to do a tar xzf which fails because it's not gzipped.

what option can i set to make it untar on recovery ?
thank you

~chris

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jsmeix** [comment]
@scprsync 
how does it fail for you?

**Comment by scprsync** [comment]
When restoring a machine, the file download and install doesn’t restore any files.

It tried to do an nfs mount and untar the backup.tar file but it doesn’t extract any files

/mnt/local has directories, but no files… so of course the rest of the restoration fails

When allowing gzip it all works, creation, restoration…

When removing the gzip, it makes backup.tar , but then when restoring it doesn’t untar the files.  It actually shows them being downloaded, just doesn’t untar them


~chris

**Comment by scprsync** [comment]
I think given todays backup systems dedupe ability, having rear able to backup non compressed and restore non compressed is really important

I write the files to a truenas (ZFS file system using lz4 compression, so it gets compressed on the backend) where I’m hoping for a good dedupe number.

Another solution which isn’t quite as good.  I passed pigz on the front end to make the image.  This greatly speeded up the compression and therefore transfer, but again I couldn’t retore because im guessing the pigz command was saved in the initrd but the binary wasn’t there.  If instead of saving the pigz command and not finding it, it just used gzip to decompress, it would have worked reasonably well

REaR is a really nice product.  We did something similar by hand that’s why I like it so much.

~chris


From: Christopher Ward
Sent: Tuesday, January 17, 2023 7:54 AM
To: rear/rear ***@***.***>
Subject: RE: [rear/rear] removing gzip for dedupe and then doesnt restore files (Issue #2911)

When restoring a machine, the file download and install doesn’t restore any files.

It tried to do an nfs mount and untar the backup.tar file but it doesn’t extract any files

/mnt/local has directories, but no files… so of course the rest of the restoration fails

When allowing gzip it all works, creation, restoration…

When removing the gzip, it makes backup.tar , but then when restoring it doesn’t untar the files.  It actually shows them being downloaded, just doesn’t untar them


~chris

**Comment by jsmeix** [comment]
For me it seems to "just work":
```
RESCUE localhost:~ # rear -D recover
Relax-and-Recover 2.7 / Git
...
Disk layout created.
Running 'restore' stage ======================
Restoring from '/var/tmp/rear.H1FRjykwUNNKLmO/outputfs/localhost/backup.tar' (restore log in /var/lib/rear/restore/recover.backup.tar.725.restore.log) ...
Backup restore program 'tar' started in subshell (PID=4761)
Restored 519 MiB [avg. 106376 KiB/sec] 
Restored 1051 MiB [avg. 107675 KiB/sec] 
Restored 1512 MiB [avg. 103268 KiB/sec] 
...
```

**Comment by scprsync** [comment]
trying again right now, will post whatever log data i can right here

**Comment by scprsync** [comment]
[rear-adcphltappserver46.log](https://github.com/rear/rear/files/10437505/rear-adcphltappserver46.log)

**Comment by jsmeix** [comment]
@scprsync 
I had a first look at your
https://github.com/rear/rear/files/10437505/rear-adcphltappserver46.log
and it shows (excerpts):

```
+++ Print 'Creating filesystem of type ext4 with mount point / on /dev/mapper/rootvg-rootlv.'
+++ wipefs --all --force /dev/mapper/rootvg-rootlv
/dev/mapper/rootvg-rootlv: 2 bytes were erased at offset 0x00000438 (ext4): 53 ef
+++ mkfs -t ext4 -b 4096 -i 16255 -U 73e56cee-dc12-4209-ae25-c48aba05a423 -F /dev/mapper/rootvg-rootlv
...
+++ Print 'Mounting filesystem /'
+++ mkdir -p /mnt/local/
+++ mount -o rw,relatime,errors=remount-ro /dev/mapper/rootvg-rootlv /mnt/local/
+++ mount -o rw,relatime,errors=remount-ro,remount,user_xattr /dev/mapper/rootvg-rootlv /mnt/local/
```
so dev/mapper/rootvg-rootlv is mounted at /mnt/local/
while "rear recover" is running.
The 'Print' messages are meant from what it was on the original system
(i.e. what was stored in disklayout.conf by "rear mkrescue/mkbackup")
and what it will be finally on the recreated target system
(i.e. after the reboot when "rear recover" had finished).

```
2023-01-17 16:40:20.180005623 Restoring from '/tmp/rear.X9RyqxbJOSVg4Lo/outputfs/adcphltappserver46/backup.tar' (restore log in /var/lib/rear/restore/recover.backup.tar.815.restore.log) ...
2023-01-17 16:40:20.188737813 dd if=/tmp/rear.X9RyqxbJOSVg4Lo/outputfs/adcphltappserver46/backup.tar | tar --block-number --totals --verbose --anchored --xattrs --xattrs-include=security.capability --xattrs-include=security.selinux --acls  -C /mnt/local/ -x -f -
2023-01-17 16:40:20.189415958 Launched backup restore subshell (PID=1880)
2023-01-17 16:41:21.648781917 Backup restore 'tar' finished with zero exit code
2023-01-17 16:41:21.652773917 Restoring finished (verify backup restore log messages in /var/lib/rear/restore/recover.backup.tar.815.restore.log)
```
so `... | tar ... -C /mnt/local/ ...` should untar in /mnt/local/
(at least this is what "man tar" tells what should happen
as far as I understand what "man tar" tells).
Did you "verify backup restore log messages in /var/lib/rear/restore/recover.backup.tar.815.restore.log"?

**Comment by gdha** [comment]
@scprsync Could you paste the `/etc/rear/local.conf` please?

**Comment by jsmeix** [comment]
@scprsync 
thank you for your description that "its untaring in /".

When I tried to reproduce it
on a KVM/QEMU test VM with 2 GIB of mamory
I had issues like this one which is from right now today:
```
Restoring from '/var/tmp/rear.21UbIcsbfyqiwo3/outputfs/localhost/backup.tar' (restore log in /var/lib/rear/restore/recover.backup.tar.1497.restore.log) ...
Backup restore program 'tar' started in subshell (PID=5510)
Restored 241 MiB [avg. 49419 KiB/sec] 
Restored 519 MiB [avg. 53188 KiB/sec] 
Restored 754 MiB [avg. 51496 KiB/sec] 
Restored 975 MiB [avg. 49970 KiB/sec] 
Restored 1137 MiB [avg. 46598 KiB/sec] 
Restored 1404 MiB [avg. 47952 KiB/sec] 
Restored 1551 MiB [avg. 45406 KiB/sec] 
Killed
```

I noticed 'oom-killer' in the dmesg output like
```
... tar invoked oom-killer ...
...
... Out of memory: Killed process ... (rear) ...
```

But I failed to see the reason why it runs out of memory.

Now I see it:
It is because 'tar ... -C /mnt/local/' untars in $(pwd)
i.e. in '/root' in the ReaR recovery system
if 'tar' is called without '--gzip'
like this:
```
Welcome to Relax-and-Recover. Run "rear recover" to restore your system !

RESCUE localhost:~ # du -xhsc /
167M    /
167M    total

RESCUE localhost:~ # rear -D recover
...
Restoring from '/var/tmp/rear.21UbIcsbfyqiwo3/outputfs/localhost/backup.tar' (restore log in /var/lib/rear/restore/recover.backup.tar.1497.restore.log) ...
Backup restore program 'tar' started in subshell (PID=5510)
Restored 241 MiB [avg. 49419 KiB/sec] 
Restored 519 MiB [avg. 53188 KiB/sec] 
Restored 754 MiB [avg. 51496 KiB/sec] 
Restored 975 MiB [avg. 49970 KiB/sec] 
Restored 1137 MiB [avg. 46598 KiB/sec] 
Restored 1404 MiB [avg. 47952 KiB/sec] 
Restored 1551 MiB [avg. 45406 KiB/sec] 
Killed

RESCUE localhost:~ # ls -lhtr
total 0
drwxr-xr-x   3 root root 0 Jun 29  2021 srv
drwxr-xr-x   3 root root 0 Jun 29  2021 home
drwxr-xr-x   3 root root 0 Jun 29  2021 boot
drwxr-xr-x   3 root root 0 Aug  5  2021 opt
drwxr-xr-x   4 root root 0 Jan 17 12:21 rear.github.master
drwx------  14 root root 0 Jan 17 12:50 root
drwxrwxrwt   2 root root 0 Jan 17 12:50 tmp
drwx------  10 root root 0 Jan 18 11:35 var
drwx------ 101 root root 0 Jan 18 11:35 etc
drwxr-xr-x   4 root root 0 Jan 18 11:35 usr

RESCUE localhost:~ # du -xhsc /
1.8G    /
1.8G    total

RESCUE localhost:~ # du -xhsc /mnt/local
4.0K    /mnt/local
4.0K    total

RESCUE localhost:~ # pwd
/root
```

Because the ReaR recovery system runs in a ramdisk
and my VM has only 2GiB memory it gets out of memory.

**Comment by jsmeix** [comment]
I have no idea why in the ReaR recovery system
'tar ... -C /mnt/local/' untars in $(pwd) i.e. in '/root'
when 'tar' is called without '--gzip'
because on my homeoffice laptop it works:
```
~> mkdir /tmp/mydir1 /tmp/mydir2 /tmp/mydir3 /tmp/mydir4

~> cd /tmp/mydir1

/tmp/mydir1> echo Hello >hello.txt

/tmp/mydir1> tar -c -f hello.tar hello.txt

/tmp/mydir1> tar -c --gzip -f hello.tar.gz hello.txt

/tmp/mydir1> ls -l
total 20
-rw-r--r-- 1 johannes users 10240 Jan 18 12:02 hello.tar
-rw-r--r-- 1 johannes users   227 Jan 18 12:02 hello.tar.gz
-rw-r--r-- 1 johannes users     6 Jan 18 12:02 hello.txt

/tmp/mydir1> cat hello.tar.gz | tar -v --gzip -C /tmp/mydir2 -x -f -
hello.txt

/tmp/mydir1> ls -l /tmp/mydir2
total 4
-rw-r--r-- 1 johannes users 6 Jan 18 12:02 hello.txt

/tmp/mydir1> cat hello.tar | tar -v -C /tmp/mydir3 -x -f -
hello.txt

/tmp/mydir1> ls -l /tmp/mydir3
total 4
-rw-r--r-- 1 johannes users 6 Jan 18 12:02 hello.txt

/tmp/mydir1> cat hello.tar | tar --block-number --totals --verbose --anchored --xattrs --xattrs-include=security.capability --xattrs-include=security.selinux --acls  -C /tmp/mydir4 -x -f -
block 3: hello.txt
block 4: ** Block of NULs **
Total bytes read: 10240 (10KiB, 20MiB/s)

/tmp/mydir1> ls -l /tmp/mydir4
total 4
-rw-r--r-- 1 johannes users 6 Jan 18 12:02 hello.txt
```

**Comment by jsmeix** [comment]
In my above ReaR recovery system the
/var/lib/rear/restore/recover.backup.tar.1497.restore.log
shows nothing that tells me (I am not a 'tar' expert) that
'tar ... -C /mnt/local/' does not untar in /mnt/local/
or even why it seems tar ignores '-C /mnt/local/':
```
++ case "$BACKUP_PROG" in
++ '[' -s /var/tmp/rear.21UbIcsbfyqiwo3/tmp/restore-exclude-list.txt ']'
++ is_true false
++ case "$1" in
++ return 1
++ Log 'dd if=/var/tmp/rear.21UbIcsbfyqiwo3/outputfs/localhost/backup.tar bs=1M | tar --block-number --totals --verbose --anchored' --xattrs --xattrs-include=security.capability --xattrs-include=security.selinux '--acls  -C /mnt/local/ -x -f -'
++ test -w /var/log/rear/rear-localhost.log
++ echo '2023-01-18 11:34:58.792671397 dd if=/var/tmp/rear.21UbIcsbfyqiwo3/outputfs/localhost/backup.tar bs=1M | tar --block-number --totals --verbose --anchored --xattrs --xattrs-include=security.capability --xattrs-include=security.selinux --acls  -C /mnt/local/ -x -f -'
++ tar --block-number --totals --verbose --anchored --xattrs --xattrs-include=security.capability --xattrs-include=security.selinux --acls '' -C /mnt/local/ -x -f -
++ dd if=/var/tmp/rear.21UbIcsbfyqiwo3/outputfs/localhost/backup.tar bs=1M
block 3: boot/grub2/x86_64-efi/
block 6: boot/grub2/i386-pc/
tar: acl_set_file_at: Cannot set POSIX ACLs for file 'boot/grub2/x86_64-efi': Operation not supported
tar: acl_delete_def_file_at: Cannot drop default POSIX ACLs for file 'boot/grub2/x86_64-efi': Operation not supported
block 9: boot/grub2/i386-pc/load.cfg
...
block 3265634: usr/share/locale/vi/LC_TIME/coreutils.mo
block 3265637: usr/share/locale/wa/
block 3265640: usr/share/locale/wa/LC_MESSAGES/
block 3265643: usr/share/locale/wa/LC_MESSAGES/popt.mo
```
there it stops logging (because oom-killer killed it).

I had noticed those "POSIX ACLs" messages also yesterday
but I did not see the reason (because it untars in a ramdisk).

I use tar version 1.34 (on openSUSE Leap 15.4).

**Comment by jsmeix** [comment]
For me 'tar ... -C /mnt/local/' without --gzip
works manually in the ReaR recovery system.
I used the enforced MIGRATION_MODE
so that I can halt "rear recover"
before the backup is restored
at this user dialog
```
UserInput -I LAYOUT_MIGRATED_CONFIRMATION needed in /usr/share/rear/layout/recreate/default/200_run_layout_code.sh line 168
Confirm the recreated disk layout or go back one step
1) Confirm recreated disk layout and continue 'rear recover'
2) Go back one step to redo disk layout recreation
3) Use Relax-and-Recover shell and return back to here
4) Abort 'rear recover'
(default '1' timeout 300 seconds)
3
UserInput: Valid choice number result 'Use Relax-and-Recover shell and return back to here'

Welcome to Relax-and-Recover.

rear>
```

In the "Relax-and-Recover shell" I did the following test:
```
rear> pwd
/var/lib/rear

rear> ls -l
total 0
drwxr-xr-x 6 root root 0 Jan 18 13:33 layout
drwxr-xr-x 2 root root 0 Jan 17 10:39 output
drwxr-xr-x 2 root root 0 Jan 17 10:38 recovery
drwxr-xr-x 2 root root 0 Jan 17 10:39 sysreqs

rear> echo Hello >hello.txt

rear> tar -c -f hello.tar hello.txt

rear> tar -c --gzip -f hello.tar.gz hello.txt

rear> ls -l hello.*
-rw-r--r-- 1 root root 10240 Jan 18 13:43 hello.tar
-rw-r--r-- 1 root root   210 Jan 18 13:43 hello.tar.gz
-rw-r--r-- 1 root root     6 Jan 18 13:43 hello.txt

rear> cat hello.tar.gz | tar -v --gzip -C /mnt/local -x -f -
hello.txt

rear> ls -l /mnt/local/hello.*
-rw-r--r-- 1 root root 6 Jan 18 13:43 /mnt/local/hello.txt

rear> rm /mnt/local/hello.txt   

rear> cat hello.tar | tar -v -C /mnt/local -x -f -
hello.txt

rear> ls -l /mnt/local/hello.*
-rw-r--r-- 1 root root 6 Jan 18 13:43 /mnt/local/hello.txt

rear> rm /mnt/local/hello.txt

rear> cat hello.tar | tar --block-number --totals --verbose --anchored --xattrs --xattrs-include=security.capability --xattrs-include=security.sel
inux --acls  -C /mnt/local -x -f -
block 3: hello.txt
block 4: ** Block of NULs **
Total bytes read: 10240 (10KiB, 10MiB/s)

rear> ls -l /mnt/local/hello.*
-rw-r--r-- 1 root root 6 Jan 18 13:43 /mnt/local/hello.txt

rear> rm /mnt/local/hello.txt

rear> exit
Are you sure you want to exit the Relax-and-Recover shell ? y
exit
```

Leaving the "Relax-and-Recover shell"
makes "rear recover" continue with this:
```
...
Restoring from '/var/tmp/rear.x5KbBEeRTtGGXGS/outputfs/localhost/backup.tar' (restore log in /var/lib/rear/restore/recover.backup.tar.715.restore.log) ...
Backup restore program 'tar' started in subshell (PID=5291)
Restored 591 MiB [avg. 121069 KiB/sec] 
Restored 890 MiB [avg. 91230 KiB/sec] 
Restored 1199 MiB [avg. 81891 KiB/sec] 
Killed
```

Currently I have no idea what is going on here...

**Comment by jsmeix** [comment]
... I found something:

When I change in
/usr/share/rear/restore/NETFS/default/400_restore_backup.sh
the actual restore command line from
```
    (   case "$BACKUP_PROG" in
            (tar)
...
                if is_true "$BACKUP_PROG_CRYPT_ENABLED" ; then 
...
                else
...
                    dd if=$restore_input bs=1M | $BACKUP_PROG --block-number --totals --verbose "${BACKUP_PROG_OPTIONS[@]}" "${BACKUP_PROG_COMPRESS_OPTIONS[@]}" -C $TARGET_FS_ROOT/ -x -f -
                fi
```
to
```
                    dd if=$restore_input bs=1M | $BACKUP_PROG --block-number --totals --verbose "${BACKUP_PROG_OPTIONS[@]}" -C $TARGET_FS_ROOT -x -
f -
```
it works for me.

**Comment by jsmeix** [comment]
Argh!

It "just works" (without code modifications) with
```
BACKUP_PROG_COMPRESS_OPTIONS=()
BACKUP_PROG_COMPRESS_SUFFIX=""
```

**Comment by scprsync** [comment]
My version is slightly different (bs=1M isn’t in it), but I dropped the BACKUP_PROGRAM_OPTIONS and it now works

So


  1.  Thank you
  2.  Does this break anything for others? Can we get this change into the Debian 11 repository so that I don’t have to track it on 400 computers and can just install from repo?

And again, thank you.  It’s a nice product.  One that we used to do ourselves locally, but your is more robust and I like it.  Honestly, more people should know about it.


~chris

**Comment by scprsync** [comment]
Correction, I dropped the BACKUP_PROG_COMPRESS_OPTIONS and it works



From: Christopher Ward
Sent: Wednesday, January 18, 2023 8:24 AM
To: rear/rear ***@***.***>
Subject: RE: [rear/rear] "rear recover": 'tar ... -C /mnt/local/' untars in $(pwd) i.e. in /root if 'tar' is called without '--gzip' (Issue #2911)

My version is slightly different (bs=1M isn’t in it), but I dropped the BACKUP_PROGRAM_OPTIONS and it now works

So


  1.  Thank you
  2.  Does this break anything for others? Can we get this change into the Debian 11 repository so that I don’t have to track it on 400 computers and can just install from repo?

And again, thank you.  It’s a nice product.  One that we used to do ourselves locally, but your is more robust and I like it.  Honestly, more people should know about it.


~chris

**Comment by jsmeix** [comment]
@scprsync 
it seems you missed my last entry here
https://github.com/rear/rear/issues/2911#issuecomment-1387056556

It reads in particular
```
It "just works" (without code modifications) with

BACKUP_PROG_COMPRESS_OPTIONS=()
BACKUP_PROG_COMPRESS_SUFFIX=""
```

So use
```
BACKUP_PROG_COMPRESS_OPTIONS=()
```
to set it to an actually empty array
instead of
```
BACKUP_PROG_COMPRESS_OPTIONS=""
```
which sets the first array element to be an empty string
```
# arr=( one two )

# declare -p arr
declare -a arr=([0]="one" [1]="two")

# arr=""

# declare -p arr
declare -a arr=([0]="" [1]="two")

# arr=()

# declare -p arr
declare -a arr=()
```
and I assume then things will "just work" also for you
(without code modifications).

For more information and some details behind how tar behaves
in this particular case see my complete last entry
https://github.com/rear/rear/issues/2911#issuecomment-1387056556

**Comment by jsmeix** [comment]
A side note regarding the current (since ReaR 2.7)
```
dd if=$restore_input bs=1M | ...
```
versus the before (up to ReaR 2.6)
```
dd if=$restore_input | ...
```
in usr/share/rear/restore/NETFS/default/400_restore_backup.sh
see https://github.com/rear/rear/issues/2369
and https://github.com/rear/rear/issues/2458
where the former reads in particular (excerpts)
```
... the speed was 500KiB/s ... on a 100MBit line ...
...
After adding bs=1M to the dd command
the speed was now really fast in comparison:
it used the full capacity of the line (about 100MBit/s).
```

**Comment by scprsync** [comment]
I understand.

I added the bs=1M option.  Restoration went from ~85MB/s -> 220MB/s, significant improvement.

How large does /tmp need to be with a NETFS option?

Anyway, great tool, thank you a ton for your effort.


~chris

**Comment by jsmeix** [comment]
FYI:

Simple reproducers for the inexplicable behaviour
when 'tar' gets an additional empty argument
(I use GNU tar 1.34 on openSUSE Leap 15.4):
```
$ tar -v -x '' -C /targetdir -f archive.tar
```
and
```
$ tar -v '' -x -C /targetdir -f archive.tar
```
untar into the current working directory
while
```
$ tar -v -x -C /targetdir '' -f archive.tar
```
and
```
$ tar '' -v -x -C /targetdir -f archive.tar
```
untar into /targetdir

I guess this might be related to the "Old Option Style"
that is described in
https://www.gnu.org/software/tar/manual/tar.html#Old-Options

But I fail to see how the additional empty argument
interferes with the -C option and its value.
