### ISSUE TITLE
How to modify the disklayout.conf file to add AUTOINCREASE_ DISK_ SIZE_ THRESHOLD_ PERCENTAGE=50 I can't modify this file

### ISSUE THREAD

**Issue by sd2070953** [rear/rear#2913]
How to modify the disklayout.conf file to add AUTOINCREASE_ DISK_ SIZE_ THRESHOLD_ PERCENTAGE=50 I can't modify this file

**Comment by jsmeix** [comment]
@sd2070953 

all ReaR configuration variables are documented in
usr/share/rear/conf/default.conf
online for ReaR 2.7 at
https://github.com/rear/rear/blob/rear-2.7/usr/share/rear/conf/default.conf
and for ReaR 2.6 at
https://github.com/rear/rear/blob/rear-2.6/usr/share/rear/conf/default.conf

Both read (excerpt - long lines shown wrapped here):
```
Here we define and describe all configuration
variables and set them to a default.

Do not change them here. Set them in your
site.conf or local.conf file as needed.
```

So set in your etc/rear/local.conf file
```
AUTOINCREASE_DISK_SIZE_THRESHOLD_PERCENTAGE=50
```
