### ISSUE TITLE
HYPER-V: Rescue ISO media stuk/freeze at "Loading kernel ... / Loading initial ramdisk ..."

### ISSUE THREAD

**Issue by iamgupta24** [rear/rear#2920]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
``` 
~]# /usr/sbin/rear -V
Relax-and-Recover 2.6 / 2020-06-17
```

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
~]# cat /etc/redhat-release ; uname -r
Red Hat Enterprise Linux release 8.5 (Ootpa)
4.18.0-348.el8.x86_64
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
~]# cat /etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=nfs://IPADDRESS/backups
BACKUP_URL=nfs://IPADDRESS/backups
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/mnt')
NETFS_KEEP_OLD_BACKUP_COPY=
FULLBACKUPDAY="Wed"
BACKUP_PROG=tar
BACKUP_TYPE=incremental
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):  
HYPER-V

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): 
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):  
UEFI | GRUB 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
~]# lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT
NAME                                         KNAME     PKNAME    TRAN TYPE FSTYPE      LABEL          SIZE MOUNTPOINT
/dev/sda                                     /dev/sda                 disk                             10G
|-/dev/sda1                                  /dev/sda1 /dev/sda       part vfat                       256M /boot/efi
|-/dev/sda2                                  /dev/sda2 /dev/sda       part xfs                        512M /boot
`-/dev/sda3                                  /dev/sda3 /dev/sda       part LVM2_member                9.2G
  |-/dev/mapper/vgsrv_system1-pool00_tmeta   /dev/dm-0 /dev/sda3      lvm                               8M
  | `-/dev/mapper/vgsrv_system1-pool00-tpool /dev/dm-2 /dev/dm-0      lvm                             6.4G
  |   |-/dev/mapper/vgsrv_system1-root       /dev/dm-3 /dev/dm-2      lvm  xfs         root           6.4G /
  |   `-/dev/mapper/vgsrv_system1-pool00     /dev/dm-5 /dev/dm-2      lvm                             6.4G
  |-/dev/mapper/vgsrv_system1-pool00_tdata   /dev/dm-1 /dev/sda3      lvm                             6.4G
  | `-/dev/mapper/vgsrv_system1-pool00-tpool /dev/dm-2 /dev/dm-1      lvm                             6.4G
  |   |-/dev/mapper/vgsrv_system1-root       /dev/dm-3 /dev/dm-2      lvm  xfs         root           6.4G /
  |   `-/dev/mapper/vgsrv_system1-pool00     /dev/dm-5 /dev/dm-2      lvm                             6.4G
  `-/dev/mapper/vgsrv_system1-swap           /dev/dm-4 /dev/sda3      lvm  swap        swap             1G [SWAP]
/dev/sr0                                     /dev/sr0                 rom  iso9660     RELAXRECOVER 455.4M
~]#
```

* Description of the issue (ideally so that others can reproduce it): 
~~~~
ReaR Rescue media stuck after booting with "Relax-and-Recover (no Secure Boot)"
Loading Kernel ...
Loading Initial ramdisk ...
~~~~
![Relax-and-Recover Kernel](https://user-images.githubusercontent.com/24269816/218050953-5843952c-a33b-4ea5-9a10-7fcc265a6635.JPG)
![Relax-and-Recover (no Secure Boot)](https://user-images.githubusercontent.com/24269816/218050959-db94f21b-e786-47b7-b8c0-b710f81339a3.JPG)

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by jsmeix** [comment]
@iamgupta24 
I have zero experience with HYPER-V.
I only use KVM/QEMU virtual machines.

I assume the root cause is something in HYPER-V
why it cannot boot the ReaR recovery system
or in other words:
I assume something special is needed in ReaR
to make a ReaR recovery system that boots under HYPER-V.

Cf. the section "Virtual machines" in
https://en.opensuse.org/SDB:Disaster_Recovery
therein in particular the part about
"paravirtualized XEN guest"
as an example that certain virtualization software or
certain virtualization methods may need special things.

**Comment by schlomo** [comment]
See https://github.com/rear/rear/issues/2933#issuecomment-1434421579 for things to try out as well
