### ISSUE TITLE
rear recover can't find /bin/rear

### ISSUE THREAD

**Issue by Scooty-Puff-Jr** [rear/rear#2925]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version: 2.6

* OS version: RHEL 8.5

* ReaR configuration files: 
  OUTPUT=USB
  OUTPUT_URL="usb:///dev/disk/by-label/REAR-000"
  BACKUP=NETFS
  BACKUP_URL="usb:///dev/disk/by-label/REAR-000"
  BACKUP_SELINUX_DISABLE=1
  CLONE_ALL_USERS=y
  USE_SERIAL_CONSOLE=n
  SSH_ROOT_PASSWORD=
  USE_SERIAL_CONSOLE=n
  COPY_AS_IS="/usr/src/kernals/4.18.0-348.el8.x86_64"
  USB_UEFI_PART_SIZE="650"
  EOF

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware: GRUB

* Storage: SSD

* Description of the issue: So I was able create a mkBACKUP on a external lockable SSD that I had available. I am able to boot to the drive by plugging the device and the SSD into a docking station to keep the lockable ssd powered so it won't auto lock during the reboot process, however once booted to the drive and it enters ReaR the drive umounts and instantly locks after loading into rear. Once ReaR loads and asks for the login, I do that and attempt a rear recover, but says it can't find /bin/rear to find the default.conf file. I unlock the drive, do a lsblk to make sure that it shows that it is mounted on the system, but I get the same result.

Is it impossible to use a lockable drive as the USB device or am I missing something to make this work correctly? 
![20230213_100912](https://user-images.githubusercontent.com/124938481/218521634-7aa509b6-c216-46db-8ed0-2248dd87636f.jpg)

**Comment by schlomo** [comment]
Can you please use version 2.7? We can't support older version, sorry.

Also, how did you install ReaR? @jsmeix do we have RHEL 8 repos with current packages somewhere?

Is there a specific reason for copying a kernel *source* to the rescue system? What would you do with that during recovery?

IMHO the lockable USB storage device should not make a difference as long as it is unlocked. The rescue systems runs completely out of a RAM disk (created by the `initrd` so that at this moment nothing should be mounted in any case.

**Comment by Scooty-Puff-Jr** [comment]
I can try the newer version. Didn't realize I was using an older version.

yum install rear

I had to do the copy as is with that kernel because the mkbackup kept erroring out with that specific line as the cause, when I went looking for solutions that copy as is line was what I found and once I included it, I could at the very least create the backup.

That makes sense, but why would it reach out for the default.conf file during that phase? 

This was a second go round, I uninstalled rear and all of the packages with it. Reinstalled it and had the same error at the same point. 

I will attempt with the newer version and try again.

**Comment by schlomo** [comment]
BTW, you can configure SSH for the rescue system to make your life simpler.

**Comment by jsmeix** [comment]
The cause is
```
COPY_AS_IS="/usr/src/kernals/4.18.0-348.el8.x86_64"
```
in etc/rear/local.conf (or etc/rear/site.conf)
because this overwrites
```
COPY_AS_IS=( $SHARE_DIR $VAR_DIR )
```
in usr/share/rear/conf/default.conf that is sourced in usr/sbin/rear
before etc/rear/local.conf or etc/rear/site.conf get sourced
so nothing in usr/share/rear/ or var/lib/rear gets copied
into the ReaR rescue/recovery system.

Use
```
COPY_AS_IS+=( /usr/src/kernals/4.18.0-348.el8.x86_64 )
```
instead.
Note that COPY_AS_IS is an array,
see the initial comments in
usr/share/rear/conf/default.conf

See also the comments in our original
ReaR 2.6 upstream etc/rear/local.conf
https://github.com/rear/rear/blob/rear-2.6/etc/rear/local.conf

By the way:
Is it really '/usr/src/kernals/' and not '/usr/src/kernels/'?

**Comment by jsmeix** [comment]
In the openSUSE Build Servoce (OBS)
there is no RHEL 8 repository avialable for building on
https://build.opensuse.org/projects/Archiving:Backup:Rear/distributions/new
Login at OBS is needed to see that - without login at OBS one gets
"Sorry, you are not authorized to update this project."

**Comment by schlomo** [comment]
Nice catch @jsmeix! 

Maybe some day we can do a simple check for such common mistakes by validating that variables that should be an array are actually still an array, or at least the ones where we always expect more than one value in them, like this `COPY_AS_IS`.

**Comment by jsmeix** [comment]
Interestingly "rear mkrescue" does not error out with
```
COPY_AS_IS="/some/directory"
```
I tested it right now.
I would have expected that something fails with that.

I think I will enhance
usr/share/rear/build/default/990_verify_rootfs.sh
to verify that 'rear' can be run inside the recovery system
e.g. by calling
```
rear dump 1>/dev/null
```
or something similar.

When I call this inside the ReaR recovery system
with 'COPY_AS_IS="/some/directory"' I get
```
# chroot /tmp/rear.BaBizTjSCHecwck/rootfs/

bash-4.4# rear dump 1>/dev/null
/sbin/rear: line 312: /usr/share/rear/conf/default.conf: No such file or directory
/sbin/rear: line 377: /usr/share/rear/lib/_input-output-functions.sh: No such file or directory
/sbin/rear: line 384: : No such file or directory
/sbin/rear: line 390: : No such file or directory
/sbin/rear: line 407: LogPrint: command not found
/sbin/rear: line 408: LogPrint: command not found
/sbin/rear: line 409: Log: command not found
/sbin/rear: line 410: LogPrint: command not found
/sbin/rear: line 424: Debug: command not found
/sbin/rear: line 425: Debug: command not found
/sbin/rear: line 430: Debug: command not found
/sbin/rear: line 433: Source: command not found
/sbin/rear: line 435: SetOSVendorAndVersion: command not found
/sbin/rear: line 447: Source: command not found
/sbin/rear: line 447: Source: command not found
/sbin/rear: line 509: SourceStage: command not found
/sbin/rear: line 528: QuietAddExitTask: command not found
/sbin/rear: line 529: Log: command not found
/sbin/rear: line 537: has_binary: command not found
/sbin/rear: line 544: LogPrintError: command not found
/sbin/rear: line 576: LogToSyslog: command not found

bash-4.4# echo $?
1
```

**Comment by schlomo** [comment]
Should we keep this issue open till we actually add a sanity check?

I was thinking along the lines of parsing `default.conf` to find all variables that should be an array:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/101384/218696832-de042698-99ac-4b62-bd7e-902ecf5904be.png">

And then we can add a check like this to validate that all those variables are actually still arrays:
```
[[ "$(declare -p EXCLUDE_BACKUP)" =~ "declare -a" ]] && echo array
```

(and this code is not very robust, see https://stackoverflow.com/a/42877229 for the probably most "correct" implementation)

What do you think. Should I add that to ReaR?

**Comment by jsmeix** [comment]
I did
https://github.com/rear/rear/issues/2930
for the generic test to have things separated.

By the way:
```
COPY_AS_IS=( /some/directory )
```
would be syntactically correct but still result
the same useless recovery system.
