### ISSUE TITLE
Creating a bootable usb stick from a .iso file saved on a disk

### ISSUE THREAD

**Issue by Commandante-che** [rear/rear#2938]
Hi
I'm also trying to get rear up and running for the first time.
I hope someone can help me.
I’ve listed (I hope) all the details requested below.

I've got mkrescue working over a samba network(Version 4.15.13-Ubuntu)
with two Ubuntu 22.04 nodes.
I've now got a .iso file saved on the server.  

I want to copy the .iso file onto a bootable usb stick.
The reason for this is that I'm going to be running mkrescue as a cron job.
I don't want anyone to have to remember to stick the stick in the computer,
so I've saving the .iso to the server and then (trying to) copy the .iso
to a stick so I can boot from the stick and recover a crashed system.

Does anyone know how to do this? Is this a reasonable thing to want to do?
I've tried using Balena Etcher, but it tells me that the .iso file
is not bootable and indeed after I've copied it to the usb stick and
tried to boot from it, it was not recognised as bootable.
I've also tried to format the usb stick with 'rear format -- --efi
and then used dd to copy the .iso file to the usb stick,
but that doesn't work either.

Any ideas anyone?
I can't think what else to do.
Thanks in advance for any help.

```
root@mike-PC:/home/mike# rear --version
Relax-and-Recover 2.6 / Git

root@mike-PC:/home/mike# cat /etc/rear/os.conf
OS_VENDOR=Ubuntu
OS_VERSION=22.04

OUTPUT=ISO
OUTPUT_URL=cifs://192.168.1.101/mike-pc-bu-p
OUTPUT_OPTIONS="credentials=/etc/.creds.txt"

description: Desktop Computer
  Motherboard: Z77-DS3H
  vendor:  Gigabyte Technology Co., Ltd.
 
description: BIOS
 vendor: American Megatrends Inc.
 version: F11a NV1
 bios boot specification uefi

description: CPU
 product: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
 vendor: Intel Corp.
 
description: System Memory
 physical id: 7
 slot: System board or motherboard
 size: 16GiB
 description: DIMM DDR3 Synchronous 1333 MHz (0.8 ns)i7-3770K CPU @ 3.50GHz
  
NVMe disk
 description: NVMe device
 product: Sabrent
 logical name: /dev/nvme0n1
  size: 953GiB (1024GB)

 description: ATA Disk
 product: TOSHIBA HDWE150
 vendor: Toshiba
 logical name: /dev/sda
 size: 4657GiB (5TB)

root@mike-PC:/home/mike# lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT | grep -v loop
NAME             KNAME          PKNAME       TRAN   TYPE FSTYPE   LABEL   SIZE MOUNTPOINT
/dev/sda         /dev/sda                    ata    disk                  4.5T 
`-/dev/sda1      /dev/sda1      /dev/sda            part ntfs     5Tb     4.5T /media/5Tb
/dev/nvme0n1     /dev/nvme0n1                nvme   disk                953.9G 
|-/dev/nvme0n1p1 /dev/nvme0n1p1 /dev/nvme0n1 nvme   part vfat             512M /boot/efi
`-/dev/nvme0n1p2 /dev/nvme0n1p2 /dev/nvme0n1 nvme   part ext4           953.4G /
```

**Comment by jsmeix** [comment]
@Commandante-che 
perhaps https://github.com/rear/rear/issues/2210
could be of interest for you here?

Additionally there is the RAWDISK output method, cf.
https://github.com/rear/rear/pull/2555#issuecomment-767451545
but RAWDISK does not support to include the data backup, cf.
https://github.com/rear/rear/pull/2555#issuecomment-769034845
and
https://github.com/rear/rear/pull/2555#issuecomment-769144572

**Comment by schlomo** [comment]
@jsmeix great idea! ideally we could merge `ISO` and `RAWDISK` output methods so that the resulting file is universally usable as boot/recovery media.

I guess that this work would require sponsoring.

**Comment by jsmeix** [comment]
@schlomo 
I cannot provide actually helpful input here because
"make a bootable thingy" is not my area of expertise.

I know that we have too many different implementations
of "making a bootable thingy" where some are rather old
but I cannot clean up that pile of stuff on my own
so yes, this would need (massive) sponsoring.

For example see
https://github.com/rear/rear/issues/764
and
https://github.com/rear/rear/issues/1601

Both faded away because noone appeared to implement it.

**Comment by guru4712** [comment]
For testing purposes, I succeeded with RUFUS.
You could also give Win32 Disk Imager (https://win32diskimager.org/) a try (untested).

**Comment by schlomo** [comment]
@guru4712 can it be that RUFUS actually does ISO **image** booting similar to https://schlomo.schapiro.org/2013/11/magic-iso-image-booting-with-gnu-grub-2.html?

That would be another approach although personally I really prefer us to get a proper solution for hybrid ISO/disk boot. I suppose that with limiting support for UEFI boot only that would be much simpler as we don't need magic bootloaders for UEFI boot.

**Comment by guru4712** [comment]
@schlomo: My goal was only to test if there is a way to boot a rescue hardware if the usb-stick intended to boot from is unavailable. I alwas generate the .ISO, too, and leave it within the data backup. 
I simply took RUFUS in a version dating approx. end of 2022 and re-created a working boot stick 
(of course burning a cd and booting from it works as well)
Sorry, I do not remember which options were used, so I cannot really contribute to your question above.
