### ISSUE TITLE
Fix ReaR source download links in packaging / drop SourceForge?

### ISSUE THREAD

**Issue by schlomo** [rear/rear#2945]
We point to SourceForge in multiple places:
https://github.com/rear/rear/blob/72e92b8d442a62e463b18755ef0fbca2b0ca0ecc/packaging/rpm/rear.spec#L22
https://github.com/rear/rear/blob/72e92b8d442a62e463b18755ef0fbca2b0ca0ecc/packaging/gentoo/rear.ebuild#L9
https://github.com/rear/rear/blob/72e92b8d442a62e463b18755ef0fbca2b0ca0ecc/Makefile#L174

But we stopped uploading ReaR release files there: https://sourceforge.net/projects/rear/files/rear/

How about we start using GitHub Releases for actual production releases? We already have tags for every release, which are the basis for a GitHub release.

Or, as an alternative, we can simply point to the GitHub repo as the Source, that would IMHO still be better than pointing at the outdated SourceForge.

Actually, our website already points to GitHub releases even though we don't publish GitHub releases yet:
https://github.com/rear/rear.github.com/blob/abfffc502d43e0420f71fa40f76964686918b216/download/index.md?plain=1#L18

**Comment by jsmeix** [comment]
@schlomo 
from my personal point of view
(i.e. unless other @rear/contributors object)
feel free to cleanup and update those things
as you think what works best for us and our users.

**Comment by pcahyna** [comment]
@schlomo I saw the same thing in the RPM spec recently and I have a fix - II can send a PR unless you are working on it already.

**Comment by schlomo** [comment]
Please send a fix, thank you very much.

**Comment by pcahyna** [comment]
Hi @schlomo, sorry for the delay. PR #2949. I touched only the RPM spec as I am not familiar with Gentoo (if nobody else can test it, I can update it blindly).
The spec works already even without having releases on GitHub - it refers to the archive that corresponds to the tag (arguably the release tarball will be a bit different, but looking at the Makefile, the difference should be only in omitted dot files and the files listed in .gitignore, right?).
