### ISSUE TITLE
Automatic recover should be set as default or via user input in local.conf

### ISSUE THREAD

**Issue by pawelRusin** [rear/rear#2962]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4 / Git
* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
OUTPUT=ISO
OUTPUT_URL=nfs://...........
BACKUP=NETFS
BACKUP_URL=iso:///mnt/backup
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/root/OS' '/tmp' '/run/log/journal')
KERNEL_CMDLINE="unattended"
USER_INPUT_TIMEOUT=1
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):
* 
Hello, I would like to use rear in CI and it should be fully automated. 
OS - Red Hat - 8.4
OUTPUT = ISO
OUTPUT_URL=nfs
I have added some variables 
KERNEL_CMDLINE="unattended"
USER_INPUT_TIMEOUT=1
but it hasn't solved my problem. I still have to manually choose in rear but menu bwtween:
Reciver/ Aumatic recover/ Boot First Local Disk etc.

How can I configure it to choose Automatic recover or set Automatic recover as default option?

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by pcahyna** [comment]
We have been using ReaR in CI. These settings have worked well for us in the case of ISO output and BIOS booting:
```sh
ISO_DEFAULT=automatic
ISO_RECOVER_MODE=unattended
```

**Comment by pawelRusin** [comment]
Thank you very much.
