### ISSUE TITLE
Exclude SAN disk from the rear mkrescue process

### ISSUE THREAD

**Issue by ITGuyAtWork** [rear/rear#2977]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recovery 2.7 / Git

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6.9
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=CMD
ISO_DIR=/var/rearISO
AUTOEXCLUDE_PATH=(/dev/sdaa)  ** Try to exclude the /dev/sdaa disk 
AUTOEXCLUDE_MULTIPATH=y
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
HP DL 360 G10

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
Local disk, SAN (FC)

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
See the log attached

* Description of the issue (ideally so that others can reproduce it):
 
Hi.
Trying to create the ISO file with the "rear -v mkrescue" command.
The goal is just to create ISO file;
then we will create the bootable USB stick with this ISO.
The data backup and recover will be done with Rubrik instead of rear.
However, the process keep reporting the error below and mkrescue is not able to generate the ISO file:
```
No partition label type for 'disk /dev/sdaa' (may cause 'rear recover' failure)
Unsupported partition table '' (must be one of 'msdos' 'gpt' 'gpt_sync_mbr' 'dasd')**
```

The "disk /dev/sdaa" is one of the SAN storage
connected through FC on this physical server;
this physical server has multiple SAN storage connected through FC. 
 
Checked the "/var/lib/rear/layout/disklayout.conf" file,
and it shows rest of the SAN storage were excluded
(guess this is excluded by default with the AUTOEXCLUDE parameter),
except /dev/sdaa

How can we configure the mkrescue process to exclude /dev/sdaa
so it can generate the ISO file we need?
Thank you. 

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```
[layout.txt](https://github.com/rear/rear/files/11377230/layout.txt)
[rear-toro-vsaa-p001.log](https://github.com/rear/rear/files/11377231/rear-toro-vsaa-p001.log)
[disklayout.txt](https://github.com/rear/rear/files/11377295/disklayout.txt)

**Comment by abbbi** [comment]
AUTOEXCLUDE_PATH refers to path of them mointpoint for the device,  not the device itself. So adding /dev/sdaa to this option wont solve your issue. If the system uses multipath, output of multipath -ll probably helps and rear with debug option to get debug logging.
