### ISSUE TITLE
Rewrite network configuration abstraction

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#3]
As discussed in rear-users at: http://sourceforge.net/mailarchive/message.php?msg_id=28515321

it would be nice if the network configuration can be instructed at boot-time.

Options could be to:

 * skip network configuration
 * use DHCP
 * use the original configuration.

There's also the possibility:

 * to force network configurations on different hardware (addresses)
 * to detect if any of the given network configurations in fact work on a certain interface (e.g. do an arping to the gateway)
 * to expect the same hardware to be available

As much as possible should work out of the box...

**Comment by gdha** [comment]
will close this one and if required (on demand) a new issue can be openend
