### ISSUE TITLE
When using xorriso, if the ISO_DIR specification includes a schema, it will not work.

### ISSUE THREAD

**Issue by chattytak** [rear/rear#3008]
* ReaR version ("/usr/sbin/rear -V"):
```
Relax-and-Recover 2.6 / 2020-06-17
```

* If your ReaR version is not the current version, explain why you can't upgrade:
It's the latest version provided by RPM.

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=null
BACKUP_URL=iso:///backup
ISO_DIR=file:///mnt/smb
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
KVM guest

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
NAME        KNAME     PKNAME   TRAN TYPE FSTYPE LABEL SIZE MOUNTPOINT
/dev/vda    /dev/vda                disk               64G
|-/dev/vda1 /dev/vda1 /dev/vda      part vfat           1G /boot/efi
|-/dev/vda2 /dev/vda2 /dev/vda      part xfs            1G /boot
`-/dev/vda3 /dev/vda3 /dev/vda      part xfs           62G /
```

* Description of the issue (ideally so that others can reproduce it):
If I put a `file://` scheme specification in ISO_DIR, an error occurs and the ISO is not output.

* Workaround, if any:
Change as follows
`ISO_DIR=file:///mnt/smb` -> `ISO_DIR=/mnt/smb`

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by pcahyna** [comment]
Should it work? IMO `ISO_DIR` does not support anything else than paths (it is not a URL but a path), so adding a schema would be superfluous anyway.

**Comment by pcahyna** [comment]
Basically all variables are documented using comments in default.conf. It is not an ideal form of documentation of course, but it should be fairly complete.
