### ISSUE TITLE
Multiple Disk

### ISSUE THREAD

**Issue by rajatjpatel** [rear/rear#3016]
* ReaR version ("/usr/sbin/rear -V"):
```
[root@node2 ~]# rear -V
Relax-and-Recover 2.6 / 2020-06-17
```

* If your ReaR version is not the current version, explain why you can't upgrade:
With CentOS 8 above version available to install 

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
[root@node2 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
cat /etc/rear/local.conf
OUTPUT=ISO
OUTPUT_URL=nfs://192.168.122.1/back
BACKUP=NETFS
BACKUP_URL=nfs://192.168.122.1/back
#BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
#NETFS_KEEP_OLD_BACKUP_COPY=
#BACKUP_TYPE=incremental
#FULLBACKUPDAY="Day"
#0 22 * * 1-5 root /usr/sbin/rear mkbackup
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
BareMetal (HPE)

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
--

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
[root@node2 ~]# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0          11:0    1 1024M  0 rom  
vda         252:0    0   20G  0 disk 
├─vda1      252:1    0    1G  0 part /boot
└─vda2      252:2    0   19G  0 part 
  ├─cs-root 253:0    0   17G  0 lvm  /
  └─cs-swap 253:1    0    2G  0 lvm  [SWAP]
vdb         252:16   0   20G  0 disk 
└─vg-lv     253:2    0   20G  0 lvm  /rear
```

* Description of the issue (ideally so that others can reproduce it):

We have media server all live video files are getting save,
we have 3 physical disk in the server
/dev/sda  256GB for CentOS 8,
/dev/sdb 8TB for every day video files
/dev/sdc 8TB for copy end of day all video files from /dev/sdb to /dev/sdc.

We are using cronjob for copying data which run ever day midnight rsync.
Now we are adding new server same make and model with bigger disk layout
like /dev/sdb=16TB and /dev/sdc=16TB.

For this we are using rear to create ISO on our NFS share.
But we are not able to get in our back /dev/sdb and /dev/sdc.

Above all configuration we are test using vm's.
we are able to backup only /dev/sda.

It is possible to add /dev/sdc & /dev/sdb in the same backup
so while restoring we get as it is.
 
* Workaround, if any:
Did not found

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by jsmeix** [comment]
I would recommed the opposite:

Use ReaR to only backup the basic operating system
i.e. only for sda with CentOS 8.

Do the backup of huge data stuff separetedly.

I would even backup the "every day video files" on sdb
separatedly from the backup of the "every day video files" on sdc.

Reason:

When you recreate the system with "rear recover"
the whole backup gets restored.

During "rear recover" restoring the backup needs
most of the whole time.

When you recreate the system with "rear recover"
and only several GiB CentOS 8 files need to get restored
"rear recover" will finish rather soon and you have
your basic operating system back wherefrom you then
can restore your huge data stuff as needed,
in particular you would first only restore
the "every day video files" on sdb
and later - as time permits - also restore the
backup of the "every day video files" on sdc.

Assume restoring several GiB CentOS 8 files needs 5 minutes
then restoring several TiB data needs about 5000 minutes
which is more than 80 hours which is more than 3 days.

So if you had all in one backup "rear recover" would
need more than 6 days to finish - and if there is one
single fatal backup restore error all will be lost.

**Comment by rajatjpatel** [comment]
Thank you so much for you quick reply on my question, we understood it take backup only for OS Disk. In case if we need to add 2nd disk to this backup if it is possible how
