### ISSUE TITLE
Recovery system fails to start up on Fedora 39 (systemd errors)

### ISSUE THREAD

**Issue by GreasyMonkee** [rear/rear#3017]
* ReaR version ("/usr/sbin/rear -V"):
rear-2.6-9.fc38.x86_64

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product:
HPE DL380p

* System architecture:
x86_64

* Firmware:
BIOS, GRUB2

* Storage :
Local Disk

* Storage layout: Not able to get any log for the disk layout

* Description of the issue:

After re-creating the RAID 5 array (6 x 2TB WD Green HDD's),
same settings as used for the previous 12 months
(including the generation of the three ReaR backup copies),
the server fails to boot using either the backup or backup with Autorecover,
with Kernel 6.3.0.0.rc5 or 6.4.0-0.rc2.
In all cases I cannot get it to progress past getty@.service,
with it failing with the following message:
```
[$TIME] systemd [1]: /usr/lib/systemd/system/getty@.service:44: Failed to resolve instance name in DefaultInstance="%I": Invalid slot
```
I am not clear where the problem is coming from,
or where the DefaultInstance %I is referring to,
so I am seeking the assistance of some more knowledgable folks here
to try and find out the next steps in solving this.

It is clear that it is referring to line 44 of the file that is found at
https://github.com/rear/rear/blob/master/usr/share/rear/skel/default/usr/lib/systemd/system/getty%40.service

however I am not clear on where or what it is looking at for the "DefaultInstance" - the "Invalid slot" appears to indicate it is looking at some hardware-related location in the server, however I am not sure why that may have changed, as there has been no hardware changes for the past 12 months

* Workaround, if any:
None - I have not found a way to get the server to start. It is not able to start even with Recovery.Target or Emergency.Target added into the GRUB config line via the ReaR terminal acreen (TAB at the selection)

* Attachments, as applicable : Images captured from screen

![Boot_from_ReaR](https://github.com/rear/rear/assets/13631259/65c291de-c7c4-4aac-bb43-6a1fda620b91)

![Bootfail_ReaR](https://github.com/rear/rear/assets/13631259/9e01def4-1798-494b-8159-aa7168facc20)

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by pcahyna** [comment]
Does the problem appear when booting the ReaR rescue system, or after a recovery when booting the recovered system?

**Comment by pcahyna** [comment]
I suppose that "the server fails to boot using either the backup or backup with Autorecover" means booting the rescue image, but this is not entirely clear. In this case, you should not add emergency.target nor rescue.target to the kernel command line, because the rescue image does not support those targets AFAIK. I suspect that the getty messages are related to a terminal that can not be found, but getty.service is referred to only as [getty@tty0.service](https://github.com/rear/rear/blob/master/usr/share/rear/skel/default/usr/lib/systemd/system/getty.target.wants/getty%40tty0.service), and tty0 should exist always ...

**Comment by GreasyMonkee** [comment]
Correct - it is whilst trying to recover the server due to a "collection of things going wrong", with DNF5 upgrade, php8.2, etc - so my decision was "well, I have got three back-ups, so wipe the disk array and re-load", but lo and behold, not are working......

I have just tried all the saved images on another machine that has a functional load of Fedora 37 Server, and the same errors occur on that machine.

So given that the backups also fail on a second machine, in the same way, it does not appear to be a hardware or Array configuration issue on my main machine.

**Comment by pcahyna** [comment]
Have you ever booted the rescue image successfully on that server in the past? And what happens when you don't add the emergency.target part to the command line?

**Comment by pcahyna** [comment]
I suppose that you could ssh to the rescue system even if getty on its console does not start.

**Comment by pcahyna** [comment]
and indeed, it does not look related to the RAID array change.

**Comment by GreasyMonkee** [comment]
Have you ever booted the rescue image successfully on that server in the past?
Yes, I have restored from a ReaR backup multiple occasions on the same hardware, including after re-building the disk array, when additional disks were added in.

And what happens when you don't add the emergency.target part to the command line?
The last logs I can see are that sysinit.service fails, and it appears to be related to the fact the Getty@.service is failing, the machine locks up and will not respond to any keyboard commands (as expected, for a Getty problem)

**Comment by pcahyna** [comment]
The rescue image is the thing that you are booting, so I see you have been able to get that to the machine. After you boot, try ssh to the machine, it could respond even if the console is locked up (assuming that you have network configured of course).
> sysinit.service fails

do you have the error messages from sysinit.service? It should run even before getty is started.

**Comment by GreasyMonkee** [comment]
I attempted to SSH into from another device (laptop), there is no Network up after 5 minutes (PING: Host unreachable)

Below is the image from the final messages seen in the startup, where it just "stops".

![Final fail-point](https://github.com/rear/rear/assets/13631259/acad280b-a37d-4f08-8267-ebce40f88504)

**Comment by GreasyMonkee** [comment]
Any ideas from the team would be greatly appreciated.

**Comment by pcahyna** [comment]
I would try to pass some systemd debug options on the kernel command line to find out what's wrong. E.g. `systemd.log_level=debug systemd.log_target=console`. I have never used this though - I have never seen before a case where ReaRs sysinit.service fails and even getty.service does not work.
Note that `Failed to resolve instance name in DefaultInstance="%I": Invalid slot` does not appear anymore - I suspect it was related to your attempt with emergency.target.
By the way, do you have a way to attach a serial console to the system?

**Comment by GreasyMonkee** [comment]
I am running Fedora headless, through the serial console - I share office space with the server cabinet.......

Shall see what I can get on the console as a capture, but my SysAdmin skills are very poor (I sill consider my self as a "noob")

**Comment by GreasyMonkee** [comment]
Yes - sorry, my bad for not being clear...... I checked another Fedora server that is all at default, the serial terminal is tty1, so I am assuming that it should be the same as the one I am trying to ressurect, as I had not changed it from the default

**Comment by GreasyMonkee** [comment]
I have managed to get my terminal to scroll back through the logs..... finally.

Below it can be seen that the problem with DefaultInstance="%I" is still present when the target is not set to emergency.target or recovery.target.

This appears to be the problem, as it is causing /etc to not be populated, and it fails to start.

![Startup_Page0](https://github.com/rear/rear/assets/13631259/d519d36a-0dc6-4e0d-9b82-8c59ac4d46ed)

![Startup_Page1](https://github.com/rear/rear/assets/13631259/79204340-9175-4210-8f12-0f3030c95e13)

**Comment by pcahyna** [comment]
I checked notes from my experiments with the ReaR rescue image bootup... there were messages
```
systemd[1]: /usr/lib/systemd/system/getty@.service:46: Failed to resolve instance name in DefaultInstance="%I": Invalid slot 
systemd[1]: /usr/lib/systemd/system/getty@.service:46: Failed to resolve instance name in DefaultInstance="%I": Invalid slot 
systemd[1]: Failed to populate /etc with preset unit settings, ignoring: Invalid slot 
```
and the rescue system was working properly nevertheless. From this I conclude that the messages are harmless and not the source of your problem.

**Comment by pcahyna** [comment]
> serial terminal is tty1

tty1 is not a serial terminal, it is the first virtual console. So, are you using a serial terminal or not?

**Comment by GreasyMonkee** [comment]
My apologies - I am not a Sys Admin, so maybe I am using the wrong terminology.

I know that I have a plugged into the multi-ping D socket for a VGA terminal on the server box - it has always worked, and when I run the command "tty" on a different server, running Fedora 37, it replies "/dev/tty1". I assume that the system with the problems that I am experiencing is likewise, as it was set up and configured in the same manner.

Thanks for all of your input, and your notes/experiments, so I will consider that to not be the source of my problems.

I have tried to load the backup (all three from different dates) onto the secondary server, I get the same result, so I conclude it is not something related to hardware.

I will need to keep digging.

**Comment by pcahyna** [comment]
Have you tried the `systemd.log_level=debug systemd.log_target=console` parameters to get more details on what's wrong?

**Comment by GreasyMonkee** [comment]
Small steps forward.....

On another HP server, I ran ReaR, got quite a few errors about various files not found, etc, however that gave me another ReaR backup file that I could try on my main machine, and YES, it booted up :-)

Also I found the backup logs from the three backups that fail, so now I have a "recipe" for a backup that has worked, I will have to go through line-by-line to see where things are going wrong.

One thing of note was that in the backup that worked, there was no "CONSOLE=" entries in the bootloader execute line - I am baffled as to where they came from or why they appear in the other three backups.

I also manually set the VGA Mode setting "VGA=" to 795, that gave a much more readable set of text for the logs,

![No_CONSOLE_VGA795](https://github.com/rear/rear/assets/13631259/eb35d33a-36fb-428e-8439-cf95c8006fd9)

From here it looks like the first thing that fails is systemd-udevd.service.

Thanks you very much pcahyna, for nudging me along the path to a point where I am starting to see the "forest instead of trees" and with the working and non-working logs, hopefully I can make progress toward resolving this issue.

I will leave this open at present, so I can post updates or ask further questions on this specific topic.

Cheers.

**Comment by GreasyMonkee** [comment]
Is there any way of getting the machine to start (using fedora live USB or similar), to be able to access/read the journalctl or systemctl messages, whilst trying to boot off the ReaR recovery USB?

With all of the Console entries deleted, I have tried systemd.log_level=debug and also init=/bin/bash to try and see further messages than what I have added above, but I still get the same set of messages returned, without and further verbosity or way of accessing further information?

**Comment by GreasyMonkee** [comment]
@jsmeix - Seeking your support for this problem.

I have three ReaR back-ups, which appear to have all been successful, however after a complete hard-disk array re-creation (due to later problems with DNF and PHP, not related to this issue), none of the backups will restore to the same disk arrangement from which the back-ups were taken.

I have had no issue at all with restoring backups in the same manner over many years with ReaR, on the same machine, as well as previous servers, so it is confusing to me why it will now not restore.

I am not able to get any debug logs, however I do have the complete logs that were saved on the USB drive with the created backup (rear-servnet.log), the latest instance is attached for your reference.

[rear-servnet.log](https://github.com/rear/rear/files/11938341/rear-servnet.log)

If there is any further information required, or if I can assist your efforts in any way, please feel free to contact me at gathrees1960@gmail.com - your knowledge and expertise is always appreciated.

**Comment by pcahyna** [comment]
Hi @GreasyMonkee sorry for the late reply. If you have an image that boots on your server, you could restore your server by using /var/lib/rear/layout and the backup (backup.tar.gz if you are using NETFS) from your non-working image inside your working image. (/var/lib/rear/ayout encodes the storage layout of the system that you need to recreate and backup.tar.gz contains the backup of the files.)

**Comment by pcahyna** [comment]
> **UPDATE**: I found this Red Hat issue
> 
> https://access.redhat.com/solutions/6317011
> 
> which looks remarkably similar, however I do not know how I might be able to edit the .conf file that is refered to when it is within a backup - any suggestions on how this may be done would be greatly appreciated.

It should not be the case - ReaR uses this nsswitch.conf file: https://github.com/rear/rear/blob/master/usr/share/rear/skel/default/etc/nsswitch.conf

**Comment by jsmeix** [comment]
I am not a Red Hat or Fedora user so I cannot actually help
when issues are specific for Red Hat or Fedora.

This issue is not really clear to me
but as far as I see it seems it is about
that the ReaR recovery system fails to start up
on replacement hardware that is somewhat different
(in particular with a re-created RAID array)
compared to the original system where "rear mkbackup" was run.

What happens is that on the replacement hardware
the ReaR recovery system boot menu is shown and
GRUB loads the ReaR recovery system kernel and initrd
and the ReaR recovery system kernel starts but then
during systemd startup phase various things go wrong
with various inexplicable systemd error messages.

A very generic thing that I am wondering about is
whether or not that replacement hardware can
successfully start up any other installation system?

For example an original Fedora installation image
or an installation image of another Linux distribution?

@GreasyMonkee 
does it work - only as a test - to install Fedora
from scratch with an original Fedora installation image
on that replacement hardware?

If this works, you may (as some kind of "last resort")
install the exact right Fedora version that matches exactly
the one on your original system where "rear mkbackup" was run
from scratch with an original Fedora installation image
on that replacement hardware and afterwards "overwrite" that
by restoring the backup of the files that you made with ReaR.
Probably this may not result a perfectly clean system
but perhaps (or hopefully) it may result a usable system.

By the way:
In your 
https://github.com/rear/rear/files/11938341/rear-servnet.log
it seems you run "rear mkbackup"
but no "backup" stage is run because:
```
# grep ' Running ' rear-servnet.log

2023-06-04 18:45:09.578362732 Running rear mkbackup (PID 3483910)
2023-06-04 18:45:09.692531050 Running 'init' stage
2023-06-04 18:45:09.731380685 Running workflow mkbackup on the normal/original system
2023-06-04 18:45:09.758998908 Running mkbackup workflow
2023-06-04 18:45:09.766836060 Running 'prep' stage
2023-06-04 18:45:16.104897140 Running 'layout/save' stage
2023-06-04 18:45:22.648027996 Running 'rescue' stage
2023-06-04 18:45:26.676248229 Running 'build' stage
2023-06-04 18:46:20.800012709 Running 'pack' stage
2023-06-04 18:46:46.039429233 Running 'output' stage
```
Perhaps all is well - but at least it looks strange.
In contrast for example on my system I get:
```
# usr/sbin/rear mkbackup

# grep ' Running ' var/log/rear/rear-linux-h9wr.log
2023-07-04 15:27:34.072253131 Running rear mkbackup (PID 31280 date 2023-07-04 15:27:33)
2023-07-04 15:27:35.685224693 Running 'init' stage
2023-07-04 15:27:36.041051624 Running workflow mkbackup on the normal/original system
2023-07-04 15:27:36.068516253 Running mkbackup workflow
2023-07-04 15:27:36.077492471 Running 'prep' stage
2023-07-04 15:27:37.209541443 Running 'layout/save' stage
2023-07-04 15:27:40.338678498 Running 'rescue' stage
2023-07-04 15:27:42.114612502 Running 'build' stage
2023-07-04 15:28:09.402770255 Running 'pack' stage
2023-07-04 15:28:22.380478272 Running 'output' stage
2023-07-04 15:28:23.611574736 Running 'backup' stage
2023-07-04 15:28:33.904032065 Running exit tasks
```

**Comment by pcahyna** [comment]
> it seems you run "rear mkbackup"
> but no "backup" stage is run because:

I suspect the log ends here because it is at this point that it gets copied to the medium.

**Comment by pcahyna** [comment]
which is here:
https://github.com/rear/rear/blob/0ab7f19455c599335beedda7300ae5ea752fab71/usr/share/rear/output/USB/Linux-i386/830_copy_kernel_initrd.sh#L16

**Comment by GreasyMonkee** [comment]
An "off-topic" rant by someone else who is also experiencing, and troubleshooting the "452 - out of range" issue 
[](https://github.com/pbatard/rufus/issues/2233)

**Comment by jsmeix** [comment]
@pcahyna 
thank yo so much for the explanation
why that log file looks bad but is OK!

I will fix that piece of code (I know it but I no idea that
this piece of code has such bad effects when one does not
have it in mind when looking at a log file from a user)
to make it clear and obvious that this log file is an
unfinished stub.

**Comment by pcahyna** [comment]
@jsmeix does the file need to be an unfinished stub? Perhaps the copy could happen later, immediately before unmounting the medium?

**Comment by pcahyna** [comment]
> Perhaps the copy could happen later, immediately before unmounting the medium?

... which would not help much, because, IIUC, the "rescue" stage unmounts it and "backup" mounts it again. Sigh.

**Comment by pcahyna** [comment]
I believe that the log is being copied again later, here:
https://github.com/rear/rear/blob/0ab7f19455c599335beedda7300ae5ea752fab71/usr/share/rear/output/default/950_copy_result_files.sh#L46

**Comment by jsmeix** [comment]
Via
https://github.com/rear/rear/commit/81db19ff4f4f2e9a97b195834ae4a4226a1342c3
I fixed things for now with a minimal code change in
output/USB/Linux-i386/830_copy_kernel_initrd.sh
i.e. simply have the
```
LogPrint "Saving current (unfinished) $RUNTIME_LOGFILE as $USB_PREFIX/$logfile_basename"
```
before the current (unfinished) RUNTIME_LOGFILE gets copied
so the last message in the copied log file should
hopefully sufficiently indicate that it is
an unfinished copy of RUNTIME_LOGFILE.

**Comment by GreasyMonkee** [comment]
From the other thread I referenced from Pete Batard, there are some serious issues with Fedora (and Ubuntu) together with GRUB, so that may well be precipitating the issue.

If it is indeed an issue with GRUB, is there a way that the modified GRUB files can be "inserted" or such for an existing ReaR backup?

I know it is a long-shot, but I am prepared to give anything a try.......

**Comment by GreasyMonkee** [comment]
UPDATE 08-07-2023.

I created a completely new installation of Fedora Rawhide (FC39), and added a couple of applications, plus required ones for running ReaR.

I then created a ReaR backup using a new USB drive, formatted using "rear format". When I attempted to boot from the created backup, the exact same behaviour as documented above has occurred.

Fedora Rawhide is still using Relax and Recover version 2.6, not sure if there is an issue from the use of this slightly older release (latest is 2.7 from the ReaR documentation I have found)

The config file used was site.conf, with the following options set:

OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

Attached below is the debug log (using -D to capture all the messages).

[20230708-1723_servnet_rear_debug.log](https://github.com/rear/rear/files/11994807/20230708-1723_servnet_rear_debug.log)

I can provide the complete backup file, if required for de-bugging purposes.

I am submitting this is the hope that whatever is the issue may be identified and corrected - I no longer am hopeful of recovering the data from the original backups where the problem first occurred, but to save others the same pain of rebuilding a system from "scratch" when the backups do not work.

**Comment by jsmeix** [comment]
@GreasyMonkee 
thank you for reproducing it with a
completely new installation of Fedora Rawhide (FC39)!

I assume when you reproduced it in your "UPDATE 08-07-2023"
https://github.com/rear/rear/issues/3017#issuecomment-1627655311
you did not do some "disk array re-creation" on the
replacement hardware (or replacement virtual machine)
where you booted the ReaR recovery system?

I.e. I assume when you reproduced it in your "UPDATE 08-07-2023"
your replacement system was not somewhat different
compared to the original system where "rear mkbackup" was run?

When my assumption is true it means this issue changes
from a special one
"ReaR image(s) will not load after disk array re-creation"
to a generic one
"Recovery system fails to start up on FC39 (systemd errors)"

**Comment by GreasyMonkee** [comment]
> you did not do some "disk array re-creation" on the
> replacement hardware (or replacement virtual machine)
> where you booted the ReaR recovery system?
Correct, no changes, or anything between the taking of the logs and attempting to reboot with the ReaR backup.

> When my assumption is true it means this issue changes
> from a special one
> "ReaR image(s) will not load after disk array re-creation"
> to a generic one
> "Recovery system fails to start up on FC39 (systemd errors)"

Yes, feel free to change the name of the issue to accurately reflect the situation  (or do I need to do that?)

**Comment by pcahyna** [comment]
I am able to reproduce the issue myself now - not sure yet what the root cause is.

**Comment by pcahyna** [comment]
ok I know what's wrong. After mounting /sys in the recovery system, all systemd units fail with `status=219/CGROUP`. Quick and dirty fix is here: https://github.com/pcahyna/rear/pull/12/commits/29c6f3c57727c4c6bb8cbeb0d41baca56145c6b7

**Comment by GreasyMonkee** [comment]
> ok I know what's wrong. After mounting /sys in the recovery system, all systemd units fail with status=219/CGROUP. Quick and dirty fix is here: https://github.com/pcahyna/rear/commit/29c6f3c57727c4c6bb8cbeb0d41baca56145c6b7

Great :-)

I will test that change later tonight and let you know how it goes.

**Comment by GreasyMonkee** [comment]
To clarify, did you do the change on a functional system, make a new backup and then able to restore that file, or

 you modified the result contained within the backup.tar.gz file of a backup which failed to restore, and then able to successfully restore it?

I tried the latter, and it was not successful.

**Comment by pcahyna** [comment]
I made a completely new backup. To use your existing backup, you should not modify the cotnent of backup.tar.gz, but of initrd. Let me find out how to do this

**Comment by pcahyna** [comment]
So the recipe is: find initrd.cgz from your bootable medium and unpack it somewhere:
```sh
cd /var/tmp
mkdir rear-root
cd rear-root
zcat ~/initrd.cgz | cpio -i
```
change the file
```sh
vi etc/scripts/boot
```
and repack the initrd
```sh
find . ! -name "*~" | cpio -H newc --create --quiet | gzip > ~/initrd-new.cgz
```
replace `initrd.cgz` on your bootable medium by `initrd-new.cgz` and boot (keep a backup copy of the original bootable medium of course).

**Comment by GreasyMonkee** [comment]
Many thanks for the procedure to go through, will run it later tonight and let you know :-)

**Comment by GreasyMonkee** [comment]
> @GreasyMonkee did you succeed?

Yes, with some twists and turns......

By changing the initrd contents, the checksum fails.

for some reason I could not nail down, I was getting a situation where there was no bootloader being created on the recovered system.

To get around that issue, I then loaded another one of the three backups from the menu selection from ReaR following the itial boot.

I have confirmed that the modification of "commenting out" the line in the skeleton file, and generating a new backup, that restores correctly without any modification of the saved initrd file.

**Comment by pcahyna** [comment]
> By changing the initrd contents, the checksum fails.

Oops, I have not thought of that. Otherwise, are you satisfied with the outcome now?

**Comment by GreasyMonkee** [comment]
Yes.

Thank you very much for your assistance, with your help I have managed to:

- Recover files and databases that were critical
- found a resolution to address the issue which caused the problem

If I understood correctly, there has been a change  in the Fedora rawhide package, to ReaR 2.6-11.fc39 ?

I am OK for this topic to be closed.

**Comment by pcahyna** [comment]
> If I understood correctly, there has been a change in the Fedora rawhide package, to ReaR 2.6-11.fc39

There has been no meaningful change, what you are seeing is just a dummy Release number bump. The Fedora maintainer is unresponsive.

I will reopen the issue, just not as a support question, because it is still a bug.

**Comment by pcahyna** [comment]
Glad to hear that you managed to recover the system.

**Comment by GreasyMonkee** [comment]
> There has been no meaningful change, what you are seeing is just a dummy Release number bump. The Fedora maintainer is unresponsive.

I will reopen the issue, just not as a support question, because it is still a bug.

If you wish I will open a Bugzilla report for it, and reference this thread?

**Comment by schlomo** [comment]
@pcahyna could you finally understand why mounting `/sys` causes a problem? Can we just disable mounting it or does it get auto-mounted somewhere else?

**Comment by pcahyna** [comment]
@schlomo I don't know unfortunately, I haven't investigated this. Since it is affecting more and more users (probably it is a feature of some recent systemd version that is getting into distros), I think I will just change the code to something like `mountpoint /sys || mount /sys`.

**Comment by schlomo** [comment]
@pcahyna if a fix is that simple then let's do it. It won't harm anything AFAIK.

**Comment by pcahyna** [comment]
> @pcahyna if a fix is that simple then let's do it. It won't harm anything AFAIK.

@schlomo https://github.com/rear/rear/pull/3079

**Comment by jsmeix** [comment]
@pcahyna 
thank you for your simple and backward compatible fix
(cf. https://github.com/rear/rear/issues/3017#issuecomment-1808550849)
of this severe issue!
