### ISSUE TITLE
BACKUP=SESAM default excludes dysfunctional

### ISSUE THREAD

**Issue by abbbi** [rear/rear#3018]
hi,

it seems as the default excludes we read from sesam configuration file:

 https://github.com/rear/rear/blob/master/usr/share/rear/lib/sesam-functions.sh#L25

are disfunctional because the pathes from the configuration file contain an trailing /.
As such, tar wont match the pathes from the exclude file and they end up in the generated
ISO image.

A simple fix would be to remove the pathes via something like:

```
 FOO="/var/opt/sesam/var/log/lgc/"
 echo ${FOO%%+(/)}
```

Better alternative would probably be to add * add the end of pathes (lgc/*) so directory
itself is considered but no contents.

are there any rules for "bashisms" like these in the code or is there already a function
that could be used? I would prepare an PR to fix this issue, accordingly. Thanks.

**Comment by abbbi** [comment]
Proposed fix in my branch:

1) read only the toplevel directory from the configuration file, in case someone has changed the installation paths for the application these are the only values that change
2) default the rest of the directories to their location beneath the installation path, end with * so only contents are excluded not the directories itself.

**Comment by jsmeix** [comment]
Via
```
# find usr/sbin/rear usr/share/rear -type f | xargs grep 'trailing slash'
```
I found only one code place that mentiones 'trailing slash'
which is in
usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
```
# accounting for possible trailing slashes in TARGET_FS_ROOT
esp_mountpoint_inside="${esp_mountpoint#${TARGET_FS_ROOT%%*(/)}}"
```
which also works
but `%%*(/)` looks less clear than `%%+(/)`
because `%%*(/)` removes zero or more occurrences of trailing `/`
while `%%*(/)` removes one or more occurrences of trailing `/`
but why should zero trailing `/` be removed at all?

**Comment by abbbi** [comment]
see:

**Comment by jsmeix** [comment]
@abbbi 
I am wondering if code like
```
SESAM_WORK_DIR="${SESAM_VAR_DIR%%+(/)}/var/work/*"
```
is really needed because - as far as I know - directory paths
with duplicated slashes like
```
//path///to/some/dir////
```
do not matter in Linux so `${SESAM_VAR_DIR%%+(/)}`
could be unneeded and the simpler
```
SESAM_WORK_DIR="$SESAM_VAR_DIR/var/work/*"
```
could also work, for example like
```
# SESAM_VAR_DIR=//var///lib//rear///

# SESAM_WORK_DIR="$SESAM_VAR_DIR/layout/config/*"

# echo $SESAM_WORK_DIR
//var///lib//rear////layout/config/df.txt //var///lib//rear////layout/config/files.md5sum

ls $SESAM_WORK_DIR
//var///lib//rear////layout/config/df.txt  //var///lib//rear////layout/config/files.md5sum

# ls /var/lib/rear/layout/config
df.txt  files.md5sum
```
?

**Comment by abbbi** [comment]
i think the problem is, that tar is pretty picky about this in its exclude list, as you can see it wont
consider the second path with duplicate slashes in its exclude list:

```
~ $ tar -cz - --exclude=/tmp/testme/folder1/* /tmp/testme/| tar -ztvf -
tar: Removing leading `/' from member names
-rw-r--r-- root/root   1048576 2023-03-20 16:18 -
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/folder1/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/test/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/folder12/
~ $ tar -cz - --exclude=/tmp/testme//folder1/* /tmp/testme/| tar -ztvf -
tar: Removing leading `/' from member names
-rw-r--r-- root/root   1048576 2023-03-20 16:18 -
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/folder1/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/folder1/folder2/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/test/
drwxr-xr-x abi/abi           0 2023-06-26 14:04 tmp/testme/folder12/
```

**Comment by jsmeix** [comment]
@abbbi 
ah! - yes - I forgot that 'tar' is "in between" here.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/3019 merged
this issue is fixed.

@abbbi 
thank you for your issue report and for your fix!

Contributions for third-party backup tool support in ReaR
are much appreciated because we at ReaR upstream
usually do not have those third-party backup tools
so we totally depend on contributions from people
who use and know about third-party backup tools.

**Comment by abbbi** [comment]
@jsmeix 

hi,

i think we have to re-open as our internal CI has proven that now, where the exludes work and are in place
there is an issue with the sesam backup client service during ISO boot. Usually the service starts automatically
but now fails to start as the SESAM_WORK_DIR is excluded.

This wasnt a problem for older Sesam client versions but it now is. Fix is probably to remove the SESAM_WORK_DIR
from the exclude list altogether.

I have fixed this in our labs and will wait until our next build and CI cycle finishes so i can confirm and will create
another Pull Request to fix the issue introduced.

**Comment by jsmeix** [comment]
@abbbi 
thank you for testing it!

I reopened this issue so we can continue here
because its subject still matches.

**Comment by abbbi** [comment]
@jsmeix Followup PR ready

**Comment by jsmeix** [comment]
With also https://github.com/rear/rear/pull/3023 merged
this issue should be solved.

@abbbi 
thank you for your continuous contributions to ReaR
in particular here for BACKUP=SESAM!
