### ISSUE TITLE
Having issues creating ISO for boot testing on Ubuntu 18.04 with libraries not being found

### ISSUE THREAD

**Issue by gramps269** [rear/rear#3032]
* ReaR version:
Relax-and-Recover 2.6 / Git

* Using 2.6 currently due to I couldn't get 2.7 to work.

* OS version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
BACKUP=CDM
OUTPUT=ISO

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
EXXACT
Baremetal

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI
GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
1xNVME 2TB
1x16TB HDD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
NAME             KNAME          PKNAME       TRAN   TYPE FSTYPE LABEL  SIZE MOUNTPOINT
/dev/sda         /dev/sda                    sata   disk              14.6T
`-/dev/sda1      /dev/sda1      /dev/sda            part ext4         14.6T /data
/dev/nvme0n1     /dev/nvme0n1                nvme   disk               1.9T
|-/dev/nvme0n1p1 /dev/nvme0n1p1 /dev/nvme0n1 nvme   part ext4          476M /boot
|-/dev/nvme0n1p2 /dev/nvme0n1p2 /dev/nvme0n1 nvme   part vfat          477M /boot/efi
|-/dev/nvme0n1p3 /dev/nvme0n1p3 /dev/nvme0n1 nvme   part swap          9.3G [SWAP]
`-/dev/nvme0n1p4 /dev/nvme0n1p4 /dev/nvme0n1 nvme   part ext4          1.9T /
```

* Description of the issue (ideally so that others can reproduce it):
Unable to create an ISO file with command `/usr/sbin/rear mkrescue`

Partial output:
```
/bin/openssl requires additional libraries (fatal error)
        libssl.so.1.1 => not found
/bin/dbus-uuidgen requires additional libraries (fatal error)
/bin/dbus-uuidgen: /lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.13.18' not found (required by /bin/dbus-uuidgen)
/bin/clear requires additional libraries (fatal error)
        libtinfow.so.6 => not found
/bin/dbus-daemon requires additional libraries (fatal error)
/bin/dbus-daemon: /lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.13.18' not found (required by /bin/dbus-daemon)
        libexpat.so.1 => not found
/bin/dbus-send requires additional libraries (fatal error)
/bin/dbus-send: /lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.13.18' not found (required by /bin/dbus-send)
/bin/curl requires additional libraries (fatal error)
        libcurl.so.4 => not found
ReaR recovery system in '/tmp/rear.KbJOztogi7Yxxwj/rootfs' needs additional libraries, check /var/log/rear/rear-exxact01.log for details
Build area kept for investigation in /tmp/rear.KbJOztogi7Yxxwj, remove it when not needed
ERROR: ReaR recovery system in '/tmp/rear.KbJOztogi7Yxxwj/rootfs' not usable (required libraries are missing)
Some latest log messages since the last called script 990_verify_rootfs.sh:
  2023-07-27 13:12:36.334443301 /bin/curl requires additional libraries (fatal error)
  2023-07-27 13:12:36.347399758         linux-vdso.so.1 (0x00007ffe1fa80000)
        libcurl.so.4 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fddb3c1e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fddb382d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fddb3e3d000)
  2023-07-27 13:12:38.437583659 ReaR recovery system in '/tmp/rear.KbJOztogi7Yxxwj/rootfs' needs additional libraries, check /var/log/rear/rear-exxact01.log for details
  2023-07-27 13:12:38.439462899 Build area kept for investigation in /tmp/rear.KbJOztogi7Yxxwj, remove it when not needed
Aborting due to an error, check /var/log/rear/rear-exxact01.log for details
```

* Workaround, if any:
Unable to find a workaround as of yet.
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by gramps269** [comment]
I found another location for the libraries and added that to my LD_LIBRARY_PATH and I was able to create the ISO file.  I will now see if it will boot.

**Comment by gramps269** [comment]
Still doesn't boot as the kernel isn't getting created and placed in the ISO.  Any ideas?

**Comment by pcahyna** [comment]
Can you please attach a log file?

**Comment by gramps269** [comment]
I'm still unable to get the iso to boot, so I'm switching products.

**Comment by jsmeix** [comment]
Only as an addendum
because this issue is also about using LD_LIBRARY_PATH
see
https://github.com/rear/rear/pull/2270#issuecomment-551832257
cf.
https://github.com/rear/rear/issues/2314#issuecomment-575529364
