### ISSUE TITLE
Rear boots Linux system to recovery screen 

### ISSUE THREAD

**Issue by hspindel** [rear/rear#3033]
* ReaR version ("/usr/sbin/rear -V"):

v 2.7

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

Rocky Linux 9.2

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=cifs://192.1.1.12/rocky-dd
BACKUP_OPTIONS="cred=/etc/rear/creds,vers=2.1"
USE_RAMDISK=0
BACKUP_PROG_EXCLUDE=( "${BACKUP_PROG_EXCLUDE[@]}" '/home/timeshift' )

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

Dell T7910

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

BIOS. GRUB.

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

Local HDD.

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

RAID 5 (mdraid)

* Description of the issue (ideally so that others can reproduce it):

Every time I reboot my server, it goes to the Rear recovery boot screen.  It never used to do this.  In order for booting to proceed, I have to select "boot next device".  If I wanted the Rear recovery screen, I would boot from a USB drive.

This just started happening recently.  How do I make it go away and boot directly?

* Workaround, if any:

Select "boot next device."

**Comment by jsmeix** [comment]
The only reason I can imagine is that
in the BIOS of your Dell T7910
the device with the ReaR recovery system
is the first one that can be booted
so you would have to change the boot ordering
in the BIOS of your Dell T7910 to make the harddisk
the first boot device - or at least have the harddisk
before the device where the ReaR recovery system is.

My blind guess is that the first boot device
in the BIOS of your Dell T7910 is (perhaps by default)
a CDROM drive or a USB disk or something similar
i.e. a device where now the bootable ReaR recovery system is.

When before the CDROM drive or USB or similar
did not contain something that can be booted,
the BIOS skips it and proceeds with the next device
according to the boot ordering in the BIOS
until it reaches the harddisk
wherefrom it boots the normal system.

**Comment by hspindel** [comment]
Silly me.  Months ago I left a Rear boot CD in the CD drive and forgot about it.

Thanks for prompting me!
