### ISSUE TITLE
Failed to boot ReaR ISO on a new VM in VMware with vCenter

### ISSUE THREAD

**Issue by Yugandharg99** [rear/rear#3040]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.7 / Git

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
``` 
OUTPUT=ISO
BACKUP=CDM
ISO_DIR=$VAR_DIR/output
ISO_ISOLINUX_BIN=/usr/bin/mkisofs
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): 
VM Running on Hypervisor: VMware ESXi, 7.0.3
Model:VxFlex integrated rack R640 C

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
vmdk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

I am testing BMR for Linux in a virtual environment.
We are using Rubrik CDM for backup and recovery.
I was able to =generate ISO and backup the ISO using Rubrik and successfully downloaded it. 

Later tried booting the ISO as a NEW VM and tried to boot the same VM using ISO but it does not bot just stuck and gives me black screen.
Could someone advise ow to successfully boot the ISO in a vcenter env?

* Workaround, if any: 

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by roseswe** [comment]
Same issue here, also with Rubrik CDM. Maybe https://www.claudiokuenzler.com/blog/1298/unable-boot-virtual-cd-drive-iso-mount-vmware-virtual-machine gives some insights?
