### ISSUE TITLE
mount.nfs: portmap query failed: RPC: Remote system error - Address already in use

### ISSUE THREAD

**Issue by exfarmer** [rear/rear#3045]
* ReaR version ("/usr/sbin/rear -V"): 
Relax-and-Recover 2.4 / Git

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Red Hat Enterprise Linux Server release 7.9 (Maipo)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
[root@ussp-oaddvic02 ~]# cat /etc/rear/local.conf
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf
OUTPUT=ISO
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP=NETFS
BACKUP_URL=nfs://edlussp001.oneabbott.com/data/col1/stpaul_linux_bu_image
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/var/log' '/usr/openv' '/srv' '/tmp/*')
ONLY_INCLUDE_VG=( "vgos" )
SYSLINUX_MODULES_DIR="/usr/share/syslinux"
OUTPUT_PREFIX="$HOSTNAME.ReaRbkup.$( date +%Y%m%d%H%M%S 2>/dev/null )"
NETFS_PREFIX="$HOSTNAME.ReaRbkup.$( date +%Y%m%d%H%M%S 2>/dev/null )"
PROGRESS_WAIT_SECONDS="10"
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
VMware, Inc. VMware Virtual Platform

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN
* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
NAME                            KNAME     PKNAME    TRAN TYPE FSTYPE      LABEL      SIZE MOUNTPOINT
/dev/sda                        /dev/sda                 disk                        100G
|-/dev/sda1                     /dev/sda1 /dev/sda       part ext4                   512M /boot
`-/dev/sda2                     /dev/sda2 /dev/sda       part LVM2_member           99.5G
  |-/dev/mapper/vgos-rootvol    /dev/dm-0 /dev/sda2      lvm  ext4                  10.3G /
  |-/dev/mapper/vgos-lvswap     /dev/dm-1 /dev/sda2      lvm  swap                    16G [SWAP]
  |-/dev/mapper/vgos-lvtmp      /dev/dm-6 /dev/sda2      lvm  ext4                  15.3G /tmp
  |-/dev/mapper/vgos-lvvar      /dev/dm-7 /dev/sda2      lvm  ext4                    20G /var
  |-/dev/mapper/vgos-lvopt      /dev/dm-8 /dev/sda2      lvm  ext4                    20G /opt
  `-/dev/mapper/vgos-lvopenv    /dev/dm-9 /dev/sda2      lvm  ext4                    15G /usr/openv
/dev/sdb                        /dev/sdb                 disk LVM2_member            250G
|-/dev/mapper/vgora-lvu01       /dev/dm-2 /dev/sdb       lvm  ext4                    75G /u01
|-/dev/mapper/vgora-lvu02       /dev/dm-3 /dev/sdb       lvm  ext4                    75G /u02
`-/dev/mapper/vgora-lvu03       /dev/dm-4 /dev/sdb       lvm  ext4                    75G /u03
/dev/sdc                        /dev/sdc                 disk LVM2_member            100G
`-/dev/mapper/vgora-lvomshome   /dev/dm-5 /dev/sdc       lvm  ext4                   171G /oms_home
/dev/sdd                        /dev/sdd                 disk                        200G
`-/dev/sdd1                     /dev/sdd1 /dev/sdd       part LVM2_member            200G
  `-/dev/mapper/vgora-lvomshome /dev/dm-5 /dev/sdd1      lvm  ext4                   171G /oms_home
/dev/sde                        /dev/sde                 disk                        300G
`-/dev/sde1                     /dev/sde1 /dev/sde       part oracleasm   ORADATA01  300G
/dev/sdf                        /dev/sdf                 disk                        100G
`-/dev/sdf1                     /dev/sdf1 /dev/sdf       part oracleasm   ORAFRA01   100G
/dev/sdg                        /dev/sdg                 disk                        100G
`-/dev/sdg1                     /dev/sdg1 /dev/sdg       part oracleasm   ORAARC01   100G
/dev/sdh                        /dev/sdh                 disk                         70G
`-/dev/sdh1                     /dev/sdh1 /dev/sdh       part oracleasm   OCR_VOTE1   70G
/dev/sdi                        /dev/sdi                 disk                         70G
`-/dev/sdi1                     /dev/sdi1 /dev/sdi       part oracleasm   OCR_VOTE2   70G
/dev/sdj                        /dev/sdj                 disk                         70G
`-/dev/sdj1                     /dev/sdj1 /dev/sdj       part oracleasm   OCR_VOTE3   70G
/dev/sr0                        /dev/sr0            ata  rom                        1024M
```

* Description of the issue (ideally so that others can reproduce it):
``` 
++ echo '2023-09-04 14:49:31.658484143 Mounting with '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'''
2023-09-04 14:49:31.658484143 Mounting with 'mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'
++ eval mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs
+++ mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs
mount.nfs: portmap query failed: RPC: Remote system error - Address already in use
mount.nfs: Address already in use
mount.nfs: timeout set for Mon Sep  4 14:51:31 2023
mount.nfs: trying text-based options 'nfsvers=3,nolock,addr=10.1.52.124'
mount.nfs: prog 100003, trying vers=3, prot=6
++ StopIfError 'Mount command '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'' failed.'
++ ((  32 != 0  ))
++ Error 'Mount command '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'' failed.'
++ LogPrintError 'ERROR: Mount command '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'' failed.'
++ Log 'ERROR: Mount command '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'' failed.'
+++ date '+%Y-%m-%d %H:%M:%S.%N '
++ local 'timestamp=2023-09-04 14:49:31.685420243 '
++ test 1 -gt 0
++ echo '2023-09-04 14:49:31.685420243 ERROR: Mount command '\''mount -v -t nfs -o nfsvers=3,nolock edlussp001.oneabbott.com:/data/col1/stpaul_linux_bu_image /tmp/rear.lAZGT5aQYOGenQk/outputfs'\'' failed.'
```

* Workaround, if any:
None

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[rear-ussp-oaddvic02.log](https://github.com/rear/rear/files/12515046/rear-ussp-oaddvic02.log)

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by exfarmer** [comment]
Hi,

The mount point is set for timeo=600, that’s 60 seconds. This is also the default. The NFS command is also a hard mount, so changing the timeout value has no effect.
I need to investigate soft mounts and timeout values. For example:

What’s the disadvantage or what could go wrong if this is a NFS soft mount?

Do you have any guidance on this?

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>

**Comment by jsmeix** [comment]
I am not at all a sufficient NFS expert
to be able to actually help with NFS specific issues.

**Comment by exfarmer** [comment]
Hi,

Is there a rear policy on this?

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>

**Comment by gdha** [comment]
@exfarmer ReaR follows what you define with `BACKUP_OPTIONS` concerning NFS mount options, e.g. you can also use as options `nfsvers=4,nolock`

**Comment by exfarmer** [comment]
Let me ask another question.

I added this line to the local.conf file:
PROGRESS_WAIT_SECONDS="10"

But the log still shows the archive growing every 1-2 seconds.
I thought that change in the local.conf file would mean the updates come every 10 seconds or more.

Thank you
Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>

**Comment by jsmeix** [comment]
@exfarmer 
PROGRESS_WAIT_SECONDS only affects ProgressInfo messages on the terminal,
see
https://github.com/rear/rear/blob/rear-2.4/usr/share/rear/backup/NETFS/default/500_make_backup.sh
```
    (tar)
        while sleep $PROGRESS_WAIT_SECONDS ; kill -0 $BackupPID 2>/dev/null; do
...
            ProgressInfo "Archived $((size/1024/1024)) MiB [avg $((size/1024/(SECONDS-starttime))) KiB/sec] "
        done
```
and
https://github.com/rear/rear/blob/rear-2.4/usr/share/rear/lib/progresssubsystem.nosh
```
        function ProgressInfo () {
            echo -en "..." 1>&7
```

Messages in the log file are not affected by PROGRESS_WAIT_SECONDS.

**Comment by exfarmer** [comment]
Is there a way to reduce the "archived" messages?

Thank you

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gdha** [comment]
@exfarmer  not using '-v' (verbose) option might help

**Comment by jsmeix** [comment]
Regarding verbose messages in the log file:
The 'tar' option '--verbose' is hardcoded in
usr/share/rear/backup/NETFS/default/500_make_backup.sh
I guess those verbose 'tar' messages is what @exfarmer means.

**Comment by gdha** [comment]
> Regarding verbose messages in the log file: The 'tar' option '--verbose' is hardcoded in usr/share/rear/backup/NETFS/default/500_make_backup.sh I guess those verbose 'tar' messages is what @exfarmer means.

@jsmeix perhaps the '**verbose**' option of tar should follow what the rear _verbose_ option?

**Comment by jsmeix** [comment]
@gdha 
yes - perhaps - but I don't know if there is a reason
why the 'tar' option '--verbose' is hardcoded.

On the other hand I wonder why it actually matters
when there are verbose 'tar' messages in the log file.
I understand the need for configurable verbosity level
on the terminal - but why does the log file actually matter?

**Comment by exfarmer** [comment]
Hi,

The tar verbose messages fill the log message buffer when running the rear backup in BladeLogic.
I will change the level on a few servers and see what happens.
Thank you

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jsmeix** [comment]
@exfarmer 
thank you for describing the reason behind
why too much in the log file matters
in your particular case.

Normally we call commands in verbose mode
only when 'rear' is run in verbose or debug mode
(via '$v' and/or '$verbose'), see for ReaR 2.4
https://github.com/rear/rear/blob/rear-2.4/usr/sbin/rear#L247
versus for current ReaR
https://github.com/rear/rear/blob/master/usr/sbin/rear#L287
cf.
https://github.com/rear/rear/commit/892bd274d0340f25684bfcd4f3297f5be740110f
and
https://github.com/rear/rear/issues/2416#issuecomment-702142588

**Comment by exfarmer** [comment]
Hi,

Like so many of the comments in the links you sent. I feel the need for verbose messages, but not for tar.
On another note: do you know if rear supports NFS v4?

Thank you

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>

**Comment by gdha** [comment]
> Hi, Like so many of the comments in the links you sent. I feel the need for verbose messages, but not for tar. On another note: do you know if rear supports NFS v4? Thank you

Yes it does.

**Comment by jsmeix** [comment]
@exfarmer 
regarding NFS v4 see
https://github.com/rear/rear/issues/3050

**Comment by exfarmer** [comment]
Hi,

I changed the /usr/share/rear/backup/NETFS/default/50_make_backup.sh script to remove –verbose in the tar command:
Line 75: Log $BACKUP_PROG $TAR_OPTIONS --sparse --block-number --totals –verbose \
Line 82: Log $BACKUP_PROG $TAR_OPTIONS --sparse --block-number --totals –verbose \
These are the same without –verbose on the end, but that didn’t remove the verbose output in the logs.

I want verbose messages for all other commands, just not for tar.
We maybe running an older version of rear, Relax-and-Recover 1.17.2 / Git, so I figured the command was 50_make_backup.sh and not 500_make_backup.sh
The servers ( I tested on 2 servers ) are RHEL v6.

Thank you
Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>

**Comment by gdha** [comment]
> Hi, I changed the /usr/share/rear/backup/NETFS/default/50_make_backup.sh script to remove –verbose in the tar command: Line 75: Log $BACKUP_PROG $TAR_OPTIONS --sparse --block-number --totals –verbose \ Line 82: Log $BACKUP_PROG $TAR_OPTIONS --sparse --block-number --totals –verbose \ These are the same without –verbose on the end, but that didn’t remove the verbose output in the logs. I want verbose messages for all other commands, just not for tar. We maybe running an older version of rear, Relax-and-Recover 1.17.2 / Git, so I figured the command was 50_make_backup.sh and not 500_make_backup.sh The servers ( I tested on 2 servers ) are RHEL v6. Thank you Abbott [image001] Gary Hess Administrator, Sr - Unix Abbott

@exfarmer Rear version 1.17.2 is no longer supported by us (nor by RH I suppose). However, you can still use a more recent version from http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/RHEL_6/

**Comment by jsmeix** [comment]
Regarding
https://github.com/rear/rear/issues/3045#issuecomment-1748444466
and
https://github.com/rear/rear/issues/3045#issuecomment-1748600710

I will have a look (as time permits) if it works for me
when the hardcoded '--verbose' option of 'tar' is replaced
with the usual ReaR verbose option setting via 'VERBOSE'
i.e. via '$v' ('-v') and/or '$verbose' ('--verbose').

I guess the reason why the 'tar' option '--verbose' is hardcoded
is that tha 'tar --verbose' output should be in the log file
regardless if "rear mkbackup" or "rear -v mkbackup" was called.
If the hardcoded '--verbose' option of 'tar' is replaced
with the usual ReaR verbose option setting via 'VERBOSE'
this would be a regression for users who call "rear mkbackup"
because those users would no longer get the 'tar --verbose' output
in their log file.

Alternative methods could be
to make TAR_OPTIONS a user config varaiable
(currently that is only used in backup/NETFS/default/500_make_backup.sh
so TAR_OPTIONS is actually a local variable in that script)
OR
(probably better) move the 'tar' option '--verbose' from hardcoded
into BACKUP_PROG_OPTIONS in default.conf so nothing should change
for users who call "rear mkbackup" (without '-v') and users
who do not like 'tar --verbose' output can specify their
specific BACKUP_PROG_OPTIONS in their local.conf file.

**Comment by jsmeix** [comment]
Ah!

Those messages are from the so called "progress subsystem",
e.g. in usr/share/rear/backup/NETFS/default/500_make_backup.sh
```
ProgressStart "Preparing archive operation"
...
ProgressInfo "Archived $((size/1024/1024)) MiB [avg $((size/1024/(SECONDS-starttime))) KiB/sec] "
...
ProgressStop
```

Currently there is no way to configure
to not get those messages.

Currently we have
PROGRESS_MODE "ANSI" (default/fallback) or "plain"
but we do not have e.g. PROGRESS_MODE "none" or "quiet".

**Comment by exfarmer** [comment]
There’s the issue.

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.******@***.***>
