### ISSUE TITLE
SLES 15.5 no ppc64le rpm

### ISSUE THREAD

**Issue by viper1986** [rear/rear#3055]
Hello,

On http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.5/ . I do not see rpm for SUSE 15.5 ppc64le.

Is it possible to add such a package in version 2.6?

**Comment by jsmeix** [comment]
In OBS Archiving:Backup:Rear I enabled 'ppc64le' for '15.5'.
The new build results (rear-2.6 and rear-2.7 RPMs) are now here:
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.5/ppc64le/
