### ISSUE TITLE
OBS remove whole Archiving:Backup:Rear:Snapshot (all is old and outdated)

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#3056]
Currently
https://build.opensuse.org/project/show/Archiving:Backup:Rear:Snapshot
shows only old and outdated stuff:
```
Name                 | Changed
---------------------+-----------------
rear                 | 12 months ago
rear-github-master   | over 2 years ago
rear-manual-snapshot | over 1 year ago
```

At least I don't have time to continuously maintain it.

When there is noone who can continuously maintain it,
then I prefer to better remove old and outdated stuff
than to let it rot even longer.

In particular I do not want to ever get a user issue report
because someone uses this old and outdated stuff by mistake.

**Comment by jsmeix** [comment]
In our https://github.com/rear/rear.github.com sources
I did not find 'Archiving:Backup:Rear:Snapshot' mentioned:
```
# git clone https://github.com/rear/rear.github.com.gi
...

# cd rear.github.com

# find . -type f | xargs grep -i 'snapshot'
[only lists ./documentation/release-notes*.md files
 and ./download/index.md
 and the latter only mentiones 'Archiving:Backup:Rear']
```

Furthermore ./download/index.md reads
```
### Master branch snapshot
The latest development snapshot is available via the [GitHub download rear-master.zip](https://github.com/rear/rear/archive/master.zip) button.
```
which works well (at least for me)
because via
```
# wget https://github.com/rear/rear/archive/master.zip

# unzip master.zip
```
I get our current GitHub master code
in a `rear-master` sub-directory.

**Comment by jsmeix** [comment]
I changed the 'Archiving:Backup:Rear:Snapshot' description at
https://build.opensuse.org/project/show/Archiving:Backup:Rear:Snapshot
to
```
Relax-and-Recover snapshot packages (old and outdated)

Do not use packages from Archiving:Backup:Rear:Snapshot.
Instead use stable ReaR versions from Archiving:Backup:Rear
or see http://relax-and-recover.org/download/
how to get the latest development snapshot at GitHub
or the current GitHub master sources via "git clone".
The packages in Archiving:Backup:Rear:Snapshot are old and outdated.
Archiving:Backup:Rear:Snapshot is no longer actively maintained.
Unless someone volunteers to actively maintain it,
Archiving:Backup:Rear:Snapshot will be removed,
see https://github.com/rear/rear/issues/3056
```

**Comment by jsmeix** [comment]
I disabled building and publishing completely
for 'Archiving:Backup:Rear:Snapshot' at
https://build.opensuse.org/repositories/Archiving:Backup:Rear:Snapshot

**Comment by jsmeix** [comment]
Let's wait and see if the already built RPMs below
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/
will get automatically deleted...

**Comment by jsmeix** [comment]
Next week (unless there are objections)
I will remove the source packages at
https://build.opensuse.org/project/show/Archiving:Backup:Rear:Snapshot
see
https://github.com/rear/rear/issues/3056#issue-1951491795
which source packages there are.

**Comment by jsmeix** [comment]
@gdha @schlomo @pcahyna @rear/contributors 
unless you object I would like to remove tomorrow afternoon
the old and outdated source packages at
https://build.opensuse.org/project/show/Archiving:Backup:Rear:Snapshot

**Comment by schlomo** [comment]
@jsmeix I guess you are the only one left here who actually knows how to use OBS.

With the per-commit snapshot builds here on GitHub I don't see any need for OBS snapshot builds beyond what you might need for SUSE-internal purposes.

For releases I see more value, especially for release builds targeting distros that don't include ReaR themselves or via one of their extended repo ecosystem.

If and when we will be doing more regular releases I'm sure that we will be revisiting this question again, till then I'd suggest to follow the past of least effort.

**Comment by schlomo** [comment]
Oh, and big thanks @jsmeix  for all the cleaning up you keep doing, I notice and see it and appreciate it very much!!!

**Comment by jsmeix** [comment]
@schlomo 
thank you so much for your kind words!
It makes me happy that my cleanup efforts are recognized.

In particular because cleanup does not produce some-"thing",
in contrast cleanup makes some existing things disappear
so after cleanup it is invisible what had been done.

**Comment by jsmeix** [comment]
The OBS Project Archiving:Backup:Rear:Snapshot is gone now.

I made copies of its packages as
https://build.opensuse.org/package/show/home:jsmeix/Archiving-Backup-Rear-Snapshot-rear
https://build.opensuse.org/package/show/home:jsmeix/Archiving-Backup-Rear-Snapshot-rear-github-master
https://build.opensuse.org/package/show/home:jsmeix/Archiving-Backup-Rear-Snapshot-rear-manual-snapshot
to keep the package sources for some time
(perhaps something might be needed at a later time)
but nothing gets built or published there.

**Comment by jsmeix** [comment]
Personally I see no reason for Archiving:Backup:Rear:Snapshot

I never used RPMs from Archiving:Backup:Rear:Snapshot

For testing current development things I use "git clone".

For reproducing SUSE customer issues I use our
official SUSE Linux Enterprise (SLE) packages, cf.
"Relax-and-Recover (ReaR) RPM packages for disaster recovery" in
https://en.opensuse.org/SDB:Disaster_Recovery

For SUSE customers and openSUSE users who like to try out
our current ReaR upstream GitHub master code, I recommend
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
because "git clone" does not conflict with their
normally installed ReaR version via RPM package. 

For SUSE customers and openSUSE users who like
to upgrade to a later or to the latest ReaR release
(without official SUSE support), I recommend
RPMs from the OBS Project Archiving:Backup:Rear
