### ISSUE TITLE
Can rear handle multiple backups on just one USB stick?

### ISSUE THREAD

**Issue by R-Sommer** [rear/rear#3063]
It looks like the mailing list is no longer active. Hope it’s ok to ask a question here.

rear can create a bootable USB stick for recovering ONE system but I would like to have just one USB stick for recovering multiple systems. Unfortunately, I’m not able to figure out reading the documentation and hundreds of articles in the internet.

For me it would be perfect when each backup would automatically be added to USB sticks’ grub.

Can someone please shed some light e.g.: Is it necessary to install rear on each system or can/have this one USB stick (to) be used to create the backups?

**Comment by jsmeix** [comment]
Yes, the mailing list is no longer active.
It is perfectly right to ask questions here.

In general I recommend to
Keep Separated Issues Separated ("KSIS"),
cf. RFC 1925 item (5).

In this case use a separated USB device for each system
and even use a separated USB device for each new backup.

See
https://github.com/rear/rear/discussions/2948#discussioncomment-5139092
(excerpt)
```
As far as I see it is (at least in practice) impossible
to use one USB disk to recover two different systems.

I think there is only one ReaR recovery system possible
for one USB disk because it is the data that is stored
inside the ReaR recovery system which is specific for the
original system where "rear mkrescue/mkbackup" was run
in particular the disklayout.conf file where information
about partitions, filesystems and mountpoints is stored.
```

See also
https://github.com/rear/rear/issues/3048#issuecomment-1715415036
(excerpt)
```
in particular with flash memory based storage
like USB sticks or USB SSDs:

Never use one same medium for more than one backup.
Never use a medium with a recent backup that you may need
to store one more backup on it.
For each backup use a separated clean medium.
```

**Comment by R-Sommer** [comment]
What about storing several ISO files on a USB stick and configuring grub to allow selecting any of these for recovering?

I'm using a similar approach but with a product called Macrium Reflect. I can boot from my stick and backup to the free area on a second partition or recover any of those backups. This gives me the oppertunity to take the stick everytime with me and recover any of my systems even on a new hardware (in case of a desaster).

To mitigate the risk of losing everything I connect the stick with my NAS and sync new backups. And I clone the stick on a other stick and put it in an other safe place.

As one downside of this product I cannot exclude directories and that's why I'm interested in rear.

**Comment by jsmeix** [comment]
@R-Sommer 
the crucial point is
neither whether or not it can be implemented
nor how to implement it.
The crucial point is
who will actually initially implement it and
then further support and maintain the code
(for about at least one year or longer)
until it works sufficiently well and reliable.

**Comment by we-sell-bags** [comment]
maybe look here:
grub-n-iso_multiboot

seems to be a script that adds bootable .iso images to allow them to appear in the grub bootloader.
it also works with a usb stick as the main boot device.
the ISO are just file images stored in a normal directory
