### ISSUE TITLE
Storing and reading Self Encrypted Disk (SED) password from TPM

### ISSUE THREAD

**Issue by Strykar** [rear/rear#3074]
I have a Self Encrypted Disk (SED). I'd like to use `sedutil` to lock the disk, but I want the password to be sealed in the TPM module on board the system, instead of in ATA BIOS.

Essentially I want the Pre-Boot Authentication (PBA) image to pick up the password from the TPM automatically upon boot.

Is this even possible?

**Comment by schlomo** [comment]
If you manage to do this with your regular Linux system then ReaR should also be able to do it, can you please share the CLI commands to do so?

**Comment by jsmeix** [comment]
@Strykar 
I am not a PBA (OpalPBA) user
so I cannot actually help with PBA issues.

We at ReaR upstream got
https://github.com/rear/rear/pull/2956
that mentiones "TPM2-assisted encryption".

If this is what you mean, then you need
our current ReaR GitHub master code, cf.
"Testing current ReaR upstream GitHub master code" on
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by Strykar** [comment]
@jsmeix I didn't mean to be obtuse, this was really a _is this even possible_ type of question based off
- https://github.com/systemd/systemd/issues/16089
- https://gitlab.com/cryptsetup/cryptsetup/-/merge_requests/461

Mostly since sedutil appears to have little traction or interaction on Github 
- https://github.com/ChubbyAnt/sedutil/issues

**Comment by jsmeix** [comment]
@Strykar 
I never used 'sedutil'
so I really cannot answer such questions.
I only liked to point to something that I found
but I don't know if that matches what you are looking for.

**Comment by prolez** [comment]
Hello,

I have developed a patch for Storing and reading Self Encrypted Disk (SED) password from TPM. If you are interested in I can create the PR.

**Comment by schlomo** [comment]
Wow, that is indeed very interesting and simplifies the "same machine" scenario.

We are currently in the process of releasing ReaR 2.8, so I can't promise you now that we can include that PR. We'll have a look at it and let you know.

So please yes, do open a PR for that. Much appreciated!!!

**Comment by prolez** [comment]
It seems I can't push the new branch. Do I need some permissions?
