### ISSUE TITLE
 ERROR: Bacula client status unknown on director.

### ISSUE THREAD

**Issue by Githopp192** [rear/rear#3082]
* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.6 / 2020-06-17

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

Red Hat Enterprise Linux 8.9 (Ootpa)"

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

HPE ProLiant DL20 Gen10

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

When REAR will check if bacula is available it will run:

"/usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh"

This script will do a : 

grep -i address /etc/bacula/bconsole.conf | awk '{ print $3 }'

In my environment/case i've got an entry in "/etc/bacula/bconsole.conf"

![image](https://github.com/rear/rear/assets/32612067/b702b198-2470-4bca-96e1-3c92893f433e)

The obove mentioned script's output is:

grep -i address /etc/bacula/bconsole.conf | awk '{ print $3 }':

![image](https://github.com/rear/rear/assets/32612067/c26fb6fd-7f18-4cba-91ae-f647bcb952e1)

And that it is - the bacula check will fail - but indeed all is running (bacula) properly.

So the script command line should check in a more specifc way, like : 

 grep '^[[:space:]]*address[[:space:]]*=' /etc/bacula/bconsole.conf

* Workaround, if any:
remove the comment-"address"-entries in the /etc/bacula/bconsole.conf

... same is valid for command:

grep $(hostname -s) /etc/bacula/bacula-fd.conf | grep "\-fd" | awk '{print $3}' | sed -e "s/-fd//g"

It seems REAR will not handle config files properly, when some line are commented with similar content.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by jsmeix** [comment]
@gdha 
could you please have a look here (as time permits)?

@Githopp192 
could you show us your whole
/etc/bacula/bconsole.conf
and
/etc/bacula/bacula-fd.conf
files?

**Comment by Githopp192** [comment]
Thanks Johannes .. cannot input the whole backup config - to confidential.

But the context is easy to follow - as long as - in this example "client-fd" is there there more than one time (one uncommented);
the script will have two results (2x client) the script will return an error an REAR will exit

![image](https://github.com/rear/rear/assets/32612067/fc5ea173-f15b-428b-9a72-9f2579c35a07)


![image](https://github.com/rear/rear/assets/32612067/077fe142-c9a8-4cfa-8451-8309b87ede52)

same is true for your check for "bconsole.conf": 

![image](https://github.com/rear/rear/assets/32612067/81a6e8e0-3dc2-47f6-bde7-145f6e08885b)

![image](https://github.com/rear/rear/assets/32612067/efeca997-2358-46a0-ad02-67bc19952057)

Affected script: /usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh", line 15 & 32

![image](https://github.com/rear/rear/assets/32612067/dd9e604d-b8b0-415d-a4ff-486f1fe0e9cb)

**Comment by jsmeix** [comment]
@Githopp192 
thank you for your information.

I am not a user of Bacula
(or any other third-party backup tool)
so I need sufficient input to understand
how things look with Bacula.

**Comment by Githopp192** [comment]
Very welcome, Johannes .. yes can understand  & glad to support & thx for this great product.
I used it several timess for Disaster Recovery ... and i got everything back to work :-)

**Comment by jsmeix** [comment]
@Githopp192 
thanks for your explicit feedback that
ReaR works when it comes to the crunch.

We don't get many reports when it works
but mostly when something doesn't work
(which is expected).

**Comment by Githopp192** [comment]
@gdha 

i'm glad you mentioned that, because today - this got into my mind, too .... may be it sounds stupid enough, i should/i could .. but i'm not experienced with this .. but - yes this is not an excuse :-) - i will give it a try. Thx 4 your input. I do appreciate

**Comment by gdha** [comment]
@Githopp192  Could you verify if the updated script `usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh` fix your issues?
