### ISSUE TITLE
AWS VM HVM: ISO boots but RAWDISK won't boot (stuck at "Probing EDD" with syslinux 4.X)

### ISSUE THREAD

**Issue by ramzcode** [rear/rear#3090]
* ReaR version :
2.4 and 2.7

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version :
Amazon Linux 2 and 2023

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
RAWDISK_IMAGE_NAME="NEW-TESTRAWV2"
OUTPUT=RAWDISK
KEEP_BUILD_DIR="yes"
BACKUP=NETFS
USE_DHCLIENT=yes
BOOTLOADER='GRUB2'
OUTPUT_URL=nfs://172.31.3.205/backup/linux
BACKUP_URL=nfs://172.31.3.205/backup/linux
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
AWS VM HVM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS / GRUB

* Model:
NVMe Device (nvme)
```
Disk /dev/nvme0n1: 16.1GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:
Number  Start   End     Size    File system  Name                 Flags
128     1049kB  2097kB  1049kB               BIOS Boot Partition  bios_grub
 1      2097kB  16.1GB  16.1GB  xfs          Linux
```

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
NVMe

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
``` 
NAME               KNAME            PKNAME       TRAN   TYPE FSTYPE LABEL SIZE MOUNTPOINT
/dev/nvme0n1       /dev/nvme0n1                  nvme   disk               15G
|-/dev/nvme0n1p1   /dev/nvme0n1p1   /dev/nvme0n1 nvme   part xfs    /      15G /
`-/dev/nvme0n1p128 /dev/nvme0n1p128 /dev/nvme0n1 nvme   part                1M
```

* Description of the issue (ideally so that others can reproduce it):

A ISO output boots,
but when i use RAWDISK as an output it wont boot,
stuck at the syslinux boot EDD line

* Workaround, if any: Not Sure

**Comment by jsmeix** [comment]
@ramzcode 
what exactly do you mean
with "stuck at the syslinux boot EDD line" ?

If you don't see further (console) output after the line
```
Probing EDD (edd=off to disable)... ok
```
see
https://github.com/rear/rear/issues/2955#issuecomment-1465642166

Check your ReaR recovery system kernel command line arguments
and look for "console=..." settings.

E.g. for BIOS you can get the
ReaR recovery system kernel command line arguments
by selecting in the ReaR recovery system boot menue
the topmost enty of the form "Recover HOSTNAME" and then
pressing the [Tab] key which shows the kernel command line.

**Comment by ramzcode** [comment]
The problem was with the syslinux 4.X version, the bootloader did not progress further. But after installing the latest version it did work. Now the RAWDISK boots as expected, yet to test the recovery process further

**Comment by ramzcode** [comment]
@jsmeix  It looks like the ReaR missed the Bios partition to include in the partion layout but it has info inside the parted file. Due to this the target has not boot partition created and GRUB2 failed to install. 

Number  Start   End     Size    File system  Name                 Flags
128     1049kB  2097kB  1049kB               BIOS Boot Partition  bios_grub
 1      2097kB  16.1GB  16.1GB  xfs          Linux

Unfortunately it picked 1 partition and ignored 128 which is my BIOS boot. 

Any idea, is this expected or do am i missing anything ?

Please suggest

**Comment by jsmeix** [comment]
I never had a system with a partition number 128
and in particular I never tried ReaR with such a system
so I cannot comment how such a system behaves in practice.

**Comment by ramzcode** [comment]
AWS EC2 Amazon Linux 2 has this behaviour, it boots into the rescue environment now, but the problem is that particular partition of 128 is BIOS kind and it is not recorded by the system or by the ReaR. 

This makes the system not to boot and just enter into the grub prompt

**Comment by jsmeix** [comment]
https://github.com/rear/rear/issues/3093
is the right issue since
https://github.com/rear/rear/issues/3090#issuecomment-1825859747

**Comment by jsmeix** [comment]
The initial issue here seems to be solved via
https://github.com/rear/rear/issues/3090#issuecomment-1823269201

**Comment by schlomo** [comment]
@ramzcode thanks a lot for your testing on Amazon Linux! Could I kindly ask you for a summary of your findings that we can include with ReaR for other users? Or maybe you can PR a short guide into our https://github.com/rear/rear/tree/master/doc/user-guide?

It would be much appreciated!

**Comment by ramzcode** [comment]
@schlomo I just updated the Sylinux version to 6.04 on my source VM and then it started to work like a charm.
