### ISSUE TITLE
ReaR source based Installation and RPM based Installation has inconsistency 

### ISSUE THREAD

**Issue by ramzcode** [rear/rear#3106]
ReaR version 2.7.

RPM Source:https://download.opensuse.org/repositories/Archiving:/Backup:/Rear/RHEL_7/x86_64/

Build: From Github

Both types has different behavior's of execution and errors. 
Ex:
Build from  source code has an error 
ERROR: Syntax error: Variable FULLBACKUPDAY not assigned as Bash array in /etc/rear/local_i.conf:
FULLBACKUPDAY=`date +%a`

But the same works in a RPM based installation. 

Is this behavior expected ??

**Comment by jsmeix** [comment]
See default.conf how to specify FULLBACKUPDAY, cf.
init/default/001_verify_config_arrays.sh
https://github.com/rear/rear/blob/master/usr/share/rear/init/default/001_verify_config_arrays.sh

We neither have a /etc/rear/local_i.conf file
in our GitHub sources, cf.
https://github.com/rear/rear/tree/master/etc/rear
nor do we specify FULLBACKUPDAY in our
https://github.com/rear/rear/blob/master/etc/rear/local.conf

**Comment by ramzcode** [comment]
@jsmeix  The prob is we need to use FULLBACKUPDAY=(date +%a) for the built from source and just FULLBACKUPDAY=date +%a for the RPM deployment. Why is that ?

Does the default files has one and another don't have the array  another ?
And this the default behavior. Ignore the conf file, it is a custom file that we created along with local.conf.
