### ISSUE TITLE
BACKUP_PROG_INCLUDE

### ISSUE THREAD

**Issue by isaacintactile** [rear/rear#313]
When trying somethinmg like:

BACKUP_PROG_EXCLUDE=('/tmp/*' '/dev/shm/*' '/exclude/*'
BACKUP_PROG_INCLUDE=('/exclude/include/*')

The in $BACKUP_PROG_INCLUDE named Directories are not included.

**Comment by gdha** [comment]
@isaacintactile can we close this issue or do you want me to add the label *sponsorship*?
