### ISSUE TITLE
root_uuid device .. is no block device

### ISSUE THREAD

**Issue by abbbi** [rear/rear#3134]
hi,

Im facing a situation where creating the REAR mkrescue backup fails (version 2.7)
because the symlink for the device on / is is missing on the system:

```
+++ get_root_disk_UUID
+++ set -o pipefail
+++ mount
+++ grep ' on / '
+++ awk '{print $1}' 
+++ xargs blkid -s UUID -o value
++ local root_uuid=201aaa04-1247-49de-8c0c-3e1274ee9fxx
++ test -b /dev/disk/by-uuid/201aaa04-1247-49de-8c0c-3e1274ee9fxx
++ Error 'root_uuid device '\''/dev/disk/by-uuid/201aaa04-1247-49de-8c0c-3e1274ee9fxx'\'' is no block device'
```

clearly, this is an issue of the system itself, partprobe does not create the required symlinks.
Is this however mandatory in REAR, or is the symlink only used if /etc/fstab contains UUID entries?
Im searching for a workaround, if any.

Thanks

**Comment by jsmeix** [comment]
@abbbi 
I cannnot imagine how your storage layout looks like
so please provide the output of
```
# lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT
```
and what /dev/disk/by-uuid/201aaa04-1247-49de-8c0c-3e1274ee9fxx
actually is (i.e. its symlink target)

**Comment by abbbi** [comment]
hi,

as it stands, there was an missing udev rule on the system involved, which resulted in
the symlink missing.
