### ISSUE TITLE
delete prep/Linux-s390/305_include_s390_tools.sh

### ISSUE THREAD

**Issue by pcahyna** [rear/rear#3144]
the whole check in usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh should now be deleted, it is useless and potentially harmful (any failure during checking /boot will result in all s390 tools omitted from the recovery image, with disastrous results).
Actually this whole file can then be deleted and the PROG+= lines moved to usr/share/rear/conf/Linux-s390x.conf or whatever is appropriate for s390 (this file got deleted in cba3590b27bedb526e5b439cd8d4d01e1ec0169a without explanation).

_Originally posted by @pcahyna in https://github.com/rear/rear/issues/3136#issuecomment-1913671596_

**Comment by lzaoral** [comment]
@jsmeix Could you please reassign this issue to me?  Thank you!
