### ISSUE TITLE
Centos6 / RHEL 6 Recovery / selinux issue

### ISSUE THREAD

**Issue by sepsesam** [rear/rear#316]
hi,

currently testing backup / restore on Centos6 and RHEL 6 with latest rear release (1.15) It seems a recovered system wont boot if selinux still active. It complains about missing liblkid and fails to mount the root system.

As it stands the issue is caused by selinux after recovery as described here:

https://bugzilla.redhat.com/show_bug.cgi?id=451503

booting the recovered system with selinux=0 in grub works fine :)

**Comment by gdha** [comment]
@sepsesam is there any chance rear will ever contain a proper sepsesam integration? Perhaps for rear-1.18 (for rear-1.17 as we froze the feature list to get it all stable before we release it end of this month)

**Comment by abbbi** [comment]
currently there are not plans to change the integration

**Comment by gdha** [comment]
no need to keep this open for now
