### ISSUE TITLE
Multiple disks recovery & external disk backup/recovery

### ISSUE THREAD

**Issue by Spadille1337** [rear/rear#3161]
* ReaR version ("/usr/sbin/rear -V"):  
Relax-and-Recover 2.5 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0     4K  1 loop /snap/bare/5
loop1    7:1    0  63.9M  1 loop /snap/core20/2105
loop2    7:2    0  55.7M  1 loop /snap/core18/2812
loop3    7:3    0  55.7M  1 loop /snap/core18/2796
loop4    7:4    0  74.1M  1 loop /snap/core22/1033
loop5    7:5    0  63.9M  1 loop /snap/core20/2182
loop6    7:6    0   497M  1 loop /snap/gnome-42-2204/141
loop7    7:7    0 218.4M  1 loop /snap/gnome-3-34-1804/93
loop8    7:8    0 240.8M  1 loop /snap/gnome-3-34-1804/24
loop9    7:9    0  74.2M  1 loop /snap/core22/1122
loop10   7:10   0  62.1M  1 loop /snap/gtk-common-themes/1506
loop11   7:11   0  91.7M  1 loop /snap/gtk-common-themes/1535
loop12   7:12   0  40.9M  1 loop /snap/snapd/20290
loop13   7:13   0  12.3M  1 loop /snap/snap-store/959
loop14   7:14   0  49.8M  1 loop /snap/snap-store/433
loop15   7:15   0  40.4M  1 loop /snap/snapd/20671
loop16   7:16   0    64M  1 loop /snap/sublime-text/156
loop17   7:17   0    64M  1 loop /snap/sublime-text/137
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0   976M  0 part /boot
├─sda2   8:2    0     1K  0 part 
├─sda5   8:5    0   3.8G  0 part [SWAP]
├─sda6   8:6    0   9.5G  0 part /home
└─sda7   8:7    0  85.7G  0 part /
sdb      8:16   0    25G  0 disk 
├─sdb1   8:17   0 487.3M  0 part /home/ubuntu/Documents/mnt1
├─sdb2   8:18   0 488.3M  0 part /home/ubuntu/Documents/mnt2
└─sdb3   8:19   0    24G  0 part /home/ubuntu/Documents/mnt3
sr0     11:0    1 412.7M  0 rom  /media/ubuntu/RELAXRECOVER
```

* Issue 1 : I want to restore both the disks with same partition mapping sda and sdb using rear recovery.
* Issue 2 : I want to take backup of sbb only and restore sdb only with same partition mapping for sdb using rear.

Kindly help me with the above Issues.

**Comment by jsmeix** [comment]
@Spadille1337 
do you have separated fully compatible replacement hardware
(or a replacement VM if you currently use a VM) available
where you could risklessly try out step by step how far
"rear recover" works for your specific intended use case?

Cf.
https://en.opensuse.org/SDB:Disaster_Recovery
