### ISSUE TITLE
Backup of only /dev/sdb

### ISSUE THREAD

**Issue by Spadille1337** [rear/rear#3164]
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.5 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* lsblk
```
root@ubunu2004:~# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0     4K  1 loop /snap/bare/5
loop1    7:1    0    55M  1 loop /snap/core18/1705
loop2    7:2    0  55.7M  1 loop /snap/core18/2812
loop3    7:3    0  74.2M  1 loop /snap/core22/1122
loop4    7:4    0 240.8M  1 loop /snap/gnome-3-34-1804/24
loop5    7:5    0   497M  1 loop /snap/gnome-42-2204/141
loop6    7:6    0  62.1M  1 loop /snap/gtk-common-themes/1506
loop7    7:7    0 218.4M  1 loop /snap/gnome-3-34-1804/93
loop8    7:8    0  91.7M  1 loop /snap/gtk-common-themes/1535
loop9    7:9    0  49.8M  1 loop /snap/snap-store/433
loop10   7:10   0  12.3M  1 loop /snap/snap-store/959
loop11   7:11   0  40.4M  1 loop /snap/snapd/20671
loop12   7:12   0  63.9M  1 loop /snap/core20/2182
loop13   7:13   0    64M  1 loop /snap/sublime-text/156
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0   976M  0 part /boot
├─sda2   8:2    0     1K  0 part 
├─sda5   8:5    0   3.8G  0 part [SWAP]
├─sda6   8:6    0   9.5G  0 part /home
└─sda7   8:7    0  85.7G  0 part /
sdb      8:16   0  12.5G  0 disk 
├─sdb1   8:17   0   4.8G  0 part /mnt/mnt1
├─sdb2   8:18   0   2.4G  0 part /mnt/mnt2
└─sdb3   8:19   0   5.4G  0 part /mnt/mnt3
sr0     11:0    1  1024M  0 rom
```
* Issue
I am using virtual machine. As we can see, I mounted /dev/sdb1 over /mnt/mnt1, /dev/sdb2 over /mnt/mnt2 and /dev/sdb3 over /mnt/mnt3. 
If I include the following line in local.conf
`EXCLUDE_COMPONENTS=("${EXCLUDE_COMPONENTS[@]}" "/dev/sda7" "/dev/sda1" "/dev/sda6" "/dev/sda2" "/dev/sda5")` , this excludes the whole system data including /dev/sdb1, /dev/sdb2, /dev/sdb3. If I include "/dev/sda7" then this will take backup of /dev/sdb1, /dev/sdb2, /dev/sdb3 along with that data in "/" as "/dev/sda7 is mounted over "/". 
Kindly tell me how can I take backup of only "/dev/sdb" in this situation.

**Comment by jsmeix** [comment]
@Spadille1337 
I do not understand what you like to achieve
with ReaR and a "backup" of only /dev/sdb
when /dev/sda is your system disk
(where `/` `/boot` `/home` and `swap` is)
because ReaR is meant to recreate a system
so at least the system disk must be backed up
but ReaR is no backup software and is not meant to be one.

See
https://en.opensuse.org/SDB:Disaster_Recovery

Therein see in particular the section
"Relax-and-Recover versus backup and restore"
https://en.opensuse.org/SDB:Disaster_Recovery#Relax-and-Recover_versus_backup_and_restore
