### ISSUE TITLE
linux rehl 7.9 : pb with rear recover , failed to create LVM volume vg_system/home' with lvcreate

### ISSUE THREAD

**Issue by sathyane007** [rear/rear#3248]
i try to recover linux physical  system in DELL Environment 
i charged iso file without firmware specification on rear conf file (in order to have a small file size )
but i got this issue 👍 
failed to create LVM volume 'vg_system/home' with lvcreate -L 134217720b -n home vg_system
also failed to create LVM volume 'vg_system/home' with lvcreate l 100%FREE n home vg_system

can someone help me , please ?

**Comment by jsmeix** [comment]
https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md

**Comment by jsmeix** [comment]
https://github.com/rear/rear/issues/3186#issuecomment-2026899680
shows at least what Dell hardware it is

**Comment by sathyane007** [comment]
hello
Dell PowerEdge R750
Bios Version 1.9.2
Integrated Dell Remote Access Controller 9........................................................................... Version 6.10.30.00(Build 29)

**Comment by gdha** [comment]
@sathyane007 which ReaR version? Did the target disk have a different size?
