### ISSUE TITLE
ERROR: Mount command 'mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.fbhHW5ocbWdLhET/outputfs' failed

### ISSUE THREAD

**Issue by sirtow** [rear/rear#326]
Hi , i have 3.10.9 kernel running with udev 204. 
While running rear recover im getting the following error :
```

ERROR: Mount command 'mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.fbhHW5ocbWdLhET/outputfs' failed

```

i have 2 block devices detected :
```

ls -l /sys/block/ |grep -v "ram\|loop"
total 0
lrwxrwxrwx 1 root root 0 Nov  9 21:58 sda -> ../devices/pci0000:00/0000:00:0d.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx 1 root root 0 Nov  9 21:58 sr0 -> ../devices/pci0000:00/0000:00:01.1/ata4/host3/target3:0:0/3:0:0:0/block/sr0

```

so it seems kernel was able to detect my virtual disk and cdrom(virtualbox)

the disk/by-lable is empty : 

```

ls -l /dev/disk/by-label/
total 0

```

Any suggestions on how to solve and where is there is the problem?

Edit:
Actually no entries were created under /dev for block devices.
No /dev/sda or /dev/sr0 exists.

I manually created sr0 (mknod b 11 0) and added a link under /dev/disk/by-lable but i think its shouldn't be like that...

**Comment by gdha** [comment]
@jezzaaa sorry for the extremely late reply - did you try the latest unstable rear repo yet? As many fixes were added around udev. Would be nice to know if it is any better now?

**Comment by jezzaaa** [comment]
@gdha Sorry, I'm not able to test any more. The host is now in production.

**Comment by williat** [comment]
I have just started looking at "rear" and am testing with a centos 5 64-bit vm on vmware esxi. I just replaced the version from EPEL with rear-1.16.1-121.git201502062115.el5.noarch.rpm, ran rear -v mkbackup, copied the resulting ISO to esxi and attached it to a second (empty) vm. I booted from that ISO and ran rear -v recover. It failed. "ERROR: Mount command 'mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.blah/outputfs' failed". /dev/disk/by-label is empty. Also, in /var/log/rear/rear-<systemname>.log I see that the line following the mount attempt shows "mount: you must specify the filesystem type" but I don't know if that is relevant. My intent is to have the "data backup" included on the ISO so that recovery is just isolated to using the ISO. For some of my VM's / servers this is an appropriate approach. From /etc/rear/site.conf:

    OUTPUT=ISO
    OUTPUT_URL=nfs://a.b.c.d/some/path/backup
    BACKUP=NETFS
    BACKUP_URL=iso:///backup

This does appear to add my data to the ISO and then copies the ISO to the nfs server.

**Comment by gdha** [comment]
This issue is related to issue #363 as well

**Comment by hpannenb** [comment]
Hello. I am facing the same described behaviour from above when trying to recover a virtual machine (KVM) on Ubuntu 14.04.3. I am using the current Relax-and-Recover 1.17.2-git201509191126 / 2015-09-19. Maybe I can help in debugging the situation a bit further.

**Comment by gdha** [comment]
@hpannenb That would be appreciated as this issue is open much too long already!

**Comment by hpannenb** [comment]
I tested ReaR 1.17.2 with different Ubuntu versions (all with latest updates) and backup to ISO as follows:

- 12.04 => Recovery works fine.
- 14.04 => Fails as mentioned (no /dev/disk/by-label/RELAXRECOVER found)
- 15.04 => Recovery works fine.

That is my state. What can I do to debug the situation under 14.04 a bit better?

**Comment by gdha** [comment]
usr/share/rear/skel/default/etc/scripts/40-start-udev-or-load-modules.sh was recently modified for module loading (issue #766). Perhaps it could fix the issue with Ubuntu 14.04 as well?

**Comment by DaGSUMan** [comment]
Where should the symbolic link be placed?  I cannot get the iso to mount during recovery.

**Comment by hardrain47** [comment]
Just ran into this same problem on Redhat 5.11 on 1.17.2 RPM install. The issue comes because the ISO label isn't being read and aliased into the /dev/disk/by-name/ directory

I fix it by running

ln -s /dev/cdrom /dev/disk/by-label/RELAXRECOVER

Isn't there a simple way to fix this by putting an option in to specify the iso device label in the configuration file, or to specify it at recover time?

**Comment by gdha** [comment]
@hardrain47 Could you try the latest snapshot as several modifications were made around udev? - see http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/CentOS_CentOS-5/x86_64/

**Comment by DaGSUMan** [comment]
**My original local.conf**
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso://backup
ISO_MAX_SIZE=3500
OUTPUT_URL="nfs://server_name/mnt/array1/CMISLEMS/"
EOF

**Was getting this during recover **
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...

**The new local.conf**
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso:///dev/disk/by-label/REARRECOVER/
ISO_MAX_SIZE=3500MB
OUTPUT_URL="nfs://10.10.10.10/mnt/array1/server_name/"
EOF

**Backup**
[root@server_name ~]# rear -v mkbackup
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-server_name.log
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Encrypting disabled
Creating tar archive '/tmp/rear.MmfKBLuMwAsre2x/tmp/isofs/dev/disk/by-label/REARRECOVER/backup.tar.gz'
Archived 10573 MiB in 1430 seconds [avg 7571 KiB/sec]
Preparing 4 ISO images ...
Making additionnal ISO image : rear-server_name_01.iso
Wrote ISO image: /var/lib/rear/output/rear-server_name_01.iso (380K)
Making additionnal ISO image : rear-server_name_02.iso
Wrote ISO image: /var/lib/rear/output/rear-server_name_02.iso (380K)
Making additionnal ISO image : rear-server_name_03.iso
Wrote ISO image: /var/lib/rear/output/rear-server_name_03.iso (380K)
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-server_name.iso (11G)
Copying resulting files to nfs location

**Recover sitll gets**
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...
Please insert the media called REARRECOVER in your CD-ROM drive...
RELAXRECOVER detected in /dev/sr0 ...

Can anyone tell me what I am doing wrong on the backup or the recover?

**Comment by hardrain47** [comment]
Tried the snapshot. Same issue. There's no link for it in the /dev/disk/by-label directory.

ln -s /dev/cdrom /dev/disk/by-label/RELAXRECOVER
fixes the problem

rear-1.17.2-170.git201603021132.el5.x86_64.rpm      was the RPM I used.

**Comment by DaGSUMan** [comment]
@hardrain47 At what point are you making the symbolic link?

**Comment by hardrain47** [comment]
I made the symlink after booting to recovery and opening the shell.

in your case, you'll want to link to sr0 instead of /dev/cdrom. (I assume you knew that). We're having separate issues possibly because you're dealing with multiple dvds.

**Comment by hardrain47** [comment]
@GDHA did you make a code change on this? I saw one on udev.

**Comment by DaGSUMan** [comment]
@hardrain47 i am having no luck.  Can you send me a sample local.conf file to see the iso backup format.  FYI when my backup was less that 4GB and a single iso.  the restore worked just fine.  its only since it has grown over 4GB that it splits into two and the restore gives the RELAXRECOVER issue.

**Comment by gdha** [comment]
@hardrain47 added some extra sleep time...

**Comment by hardrain47** [comment]
What OS you on @DaGSUMan? I'll see if I can test multiple disks.

**Comment by DaGSUMan** [comment]
@hardrain47 I'm on Red Hat 6.7

**Comment by hardrain47** [comment]
here's my local.conf.  I'm going to drop my iso size to 1GB and test.

OUTPUT=ISO
OUTPUT_URL=null
ISO_MAX_SIZE=4500
BACKUP=NETFS
BACKUP_URL=iso://backup
ISO_DEFAULT=manual

**Comment by hardrain47** [comment]
Well, on 5u11, multiple DVDs appears to be working when I do 
ln -s /dev/cdrom /dev/disk/by-label/RELAXRECOVER
before running >rear recover

I also just use the default output location: /var/lib/rear/output
I'll test on 6.7

**Comment by DaGSUMan** [comment]
Please see the screen shots
[REARError.docx](https://github.com/rear/rear/files/159370/REARError.docx)

**Comment by hardrain47** [comment]
Something already exists in your /dev/disk/by-label directory.
What does > ls -al /dev/disk/by-label report?

**Comment by DaGSUMan** [comment]
RELAXRECOVER -> ../../sr0
.
![rearerror01](https://cloud.githubusercontent.com/assets/17571121/13540603/1f0d4d4a-e21d-11e5-8359-f22a41cee7bf.PNG)

**Comment by hardrain47** [comment]
what happens when you do ls -al /dev/sr0 ?

**Comment by DaGSUMan** [comment]
![rearerror02](https://cloud.githubusercontent.com/assets/17571121/13541003/5b3cfea8-e21f-11e5-9244-6d2639dcccf7.PNG)

**Comment by hpannenb** [comment]
@gdha I retested with Relax-and-Recover 1.17.2-git201603021132 / 2016-03-02 on Ubuntu 14.04.4 in a KVM. Still missing the /dev/disk/by-label/RELAXRECOVER.

**Comment by hardrain47** [comment]
@DaGSUMan Couldn't test over the weekend with 6.7, but I have some results for you.

I am on an extremely similar RHEL release 6.7.2.6-32-573.e16.x86_64 

I did a test setup with a 700MB max iso size which split my system into two isos and tried a restore. I had no problem restoring with multiple isos. Worked flawlessly. Do you think perhaps it could be your CD drive, or how you burned your isos? I am using a USB DVD drive with isos burnt to DVD-RW on windows.

Another thing I thought you might be able to do is do a ctrl-z when it's asking for that CD and try to mount the filesystem manually. That may be easier said than done.

Still stuck on 5u11, but I can work around that issue. Going to try it on RHEL 4

**Comment by DaGSUMan** [comment]
THank you @hardrain47 I'll try it again.  Although, fyi I am using VM to test the restoring and mounting the ISO.  It is creating three iso's  one that is 7GB and the other two are like 300K

**Comment by hardrain47** [comment]
Oh, this could totally a virtual device issue. How are you "loading" these?

**Comment by DaGSUMan** [comment]
I was trying to burn them to an DVD but it was too large. It's not breaking the DVD size equally. My is 7GB from the physical server. That is why I was trying to restore to VM.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1894 merged
this issue should be now fixed in a (hopefully) better way.

See
https://github.com/rear/rear/pull/1894#issuecomment-411766357
for some examples how it behaves now.
