### ISSUE TITLE
Rear Recovery is it supported on Linux Node OpenSVC ?

### ISSUE THREAD

**Issue by sathyane007** [rear/rear#3262]
Hello
I have to use rear iso file to recover a linux Node openSVC in Cisco Platform
Do you think that rear is supported on OpenSVC , please?
i notice that there is a local tag so that the recovery script don't work ; we have to lauch the command :
"vgchange --addtag local vg_system " 
did someone had this pb ?

**Comment by gdha** [comment]
@sathyane007 please use template and fill it in properly as now we have no clue on which OS you are using? We need more info - that is the purpose of using the Issue template. Could you do that please?
Thanks for using/trying ReaR on openSVC - whatever it is using beneath...

**Comment by gdha** [comment]
@sathyane007 When no additional information is added we will close this issue soon. Sorry, we not enough info to do further research.
