### ISSUE TITLE
I would like to step back from personal responsibility for ReaR

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#3272]
I would like to step back from personal responsibility for ReaR
as a ReaR project maintainer with ReaR project write permissions.
I can no longer bear personal responsibility for ReaR.
I would like to stay but only as external contributor.
I intend to further contribute as before (as time permits).

**Comment by gdha** [comment]
@jsmeix Sorry to read this, but I respect your opinion. Everyone is free to decide what kind of responsibility he/she wants to have with an Open Source project.
However, we will miss you as a main contributor these days and we are certainly grateful for the years you literally tool leadership within this project.
We hope you stay on board as a **main contributor**.
When @schlomo agrees I will change your state with ReaR project tomorrow?

**Comment by jsmeix** [comment]
Since
http://relax-and-recover.org/documentation/security-architecture
I feel much relaxed because now
we clearly described and explained publicly
to what extent we feel responsible for ReaR
of course additionally limited by the GPL's
"Disclaimer of Warranty" and "Limitation of Liability"
and to what extent the user is responsible.

**Comment by jsmeix** [comment]
@schlomo 
thank you so much for making
http://relax-and-recover.org/documentation/security-architecture
I do appreciate it very much!
