### ISSUE TITLE
ERROR: BUG BUG BUG!  Empty string passed to get_device_name

### ISSUE THREAD

**Issue by pavoldomin** [rear/rear#328]
Hello,

Another problem related to the custom definition of the lvm filter and preferred_names discovered.
The problem comes from the colon in md device name (because md array was built with --name option) like
```
#pvs
  /dev/disk/by-id/md-name-hostname:NA3scs                        vgNA3scs   lvm2 a--     5.00g    4.00g
```
leading to the
```
#rear -v -D  savelayout
Relax-and-Recover 1.15-git201310211300 / 2013-10-21
Using log file: /var/log/rear/rear-hostname.log
Creating disk layout
ERROR: BUG BUG BUG!  Empty string passed to get_device_name
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-hostname.log

HINT: If you can reproduce the issue, try using the -d or -D option !
====================
Aborting due to an error, check /var/log/rear/rear-hostname.log for details
```

Hopefully relevant (and slightly censored) part of the logfile is here: https://gist.github.com/pavoldomin/0242b6d92fc45294996d

Worth adding, that this grep than returns two entries on this particular server:
```
#grep '^md-name-hostname' /var/lib/rear/recovery/diskbyid_mappings
md-name-hostname:NA3ora
md-name-hostname:NA3scs md35
```

As expected, if we add ```/dev/md*``` to the ```filter``` as well as ```preferred_names``` definition in ```lvm.conf```, the problem ceases.

**Comment by gdha** [comment]
As after one year no-one showed interest in this missing feature we classified it as 'wont fix'
