### ISSUE TITLE
Remove cronjob of RPM package on RHEL

### ISSUE THREAD

**Issue by GitarPlayer** [rear/rear#3282]
* ReaR version ("/usr/sbin/rear -V"):
```bash
Relax-and-Recover 2.6 / 2020-06-17
```
* If your ReaR version is not the current version, explain why you can't upgrade:
This is the latest version available through my dnf package manager on RHEL8. 

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```bash
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
default
* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
KVM guest
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS, GRUB
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
DM
* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```bash
NAME                             KNAME      PKNAME    TRAN   TYPE FSTYPE      LABEL  SIZE MOUNTPOINT
/dev/sda                         /dev/sda                    disk                    100G 
|-/dev/sda1                      /dev/sda1  /dev/sda         part xfs         boot     1G /boot
`-/dev/sda2                      /dev/sda2  /dev/sda         part LVM2_member         99G 
  |-/dev/mapper/rootvg-root      /dev/dm-0  /dev/sda2        lvm  xfs                 23G /
  |-/dev/mapper/rootvg-swap      /dev/dm-1  /dev/sda2        lvm  swap                 4G [SWAP]
  |-/dev/mapper/rootvg-journal   /dev/dm-3  /dev/sda2        lvm  xfs                  4G /var/log/journal
  |-/dev/mapper/rootvg-audit     /dev/dm-4  /dev/sda2        lvm  xfs                  4G /var/log/audit
  |-/dev/mapper/rootvg-log       /dev/dm-5  /dev/sda2        lvm  xfs                  4G /var/log
  |-/dev/mapper/rootvg-crash     /dev/dm-6  /dev/sda2        lvm  xfs                  8G /var/crash
  |-/dev/mapper/rootvg-var       /dev/dm-7  /dev/sda2        lvm  xfs                  8G /var
  |-/dev/mapper/rootvg-opt       /dev/dm-8  /dev/sda2        lvm  xfs                 16G /opt
  |-/dev/mapper/rootvg-home      /dev/dm-9  /dev/sda2        lvm  xfs                  8G 
  `-/dev/mapper/rootvg-cortex    /dev/dm-10 /dev/sda2        lvm  xfs                 10G /opt/traps
/dev/sdb                         /dev/sdb                    disk LVM2_member         50G 
`-/dev/mapper/datavg-export_home /dev/dm-2  /dev/sdb         lvm  xfs                 50G /home
/dev/sr0                         /dev/sr0             sata   rom                    1024M 
```
* Description of the issue (ideally so that others can reproduce it):
If I install the rear package it also includes a cronjob in /etc/cron.d/rear. I don't think this should be part of the package because without any additional configuration this daily cronjob will fail daily. I was searching through the repo where this cronjob is included but I could not find it. I would have submitted a pull request otherwise. Apologies for not finding it.
* Workaround, if any:
Remove /etc/cron.d/rear manually or as part of the installtion process with ansible
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by lzaoral** [comment]
Hello, @GitarPlayer!  The package sources for CentOS Stream 8 / RHEL 8 are available here: https://gitlab.com/redhat/centos-stream/rpms/rear/-/blob/c8s/rear.spec?ref_type=heads

I suggest to report this problem on the official issue tracker instead: issues.redhat.com

**Comment by pcahyna** [comment]
> If I install the rear package it also includes a cronjob in /etc/cron.d/rear. I don't think this should be part of the package because without any additional configuration this daily cronjob will fail daily. I was searching through the repo where this cronjob is included but I could not find it. I would have submitted a pull request otherwise. Apologies for not finding it.

I also think that having this cron job was a bad idea, but I don't think it is a good idea to remove it at a so late stage in the RHEL 8 lifecycle. RHEL 9 does not have the cron job anymore (it is installed into a documentation directory as an example and you have to copy to /etc/cron.d and modify it). See the deprecation notice in the RHEL 8 release notes.

**Comment by gdha** [comment]
@GitarPlayer Are you good with the replies? Can we close this issue?
