### ISSUE TITLE
Can't Restore ReaR backup on RHEL9 (ISO image got corrupted)

### ISSUE THREAD

**Issue by msharif4** [rear/rear#3288]
Hi ReaR team,
I installed ReaR in a rhel9 server and configured it. I took a full backup last week, and now the server is not working after patching it. I am trying to restore the server from the ReaR backup. However, I am getting an error **"failed to load ldlinux.c32".** The backup was stored in an NFS share, and I am using the Iventoy tool to boot the system from the network. I have both the iso file and the zip file with full backup. Did misconfigure the /etc/local.conf file? Now, can I restore the backup when the system is only starting on rescue mode? I am stressed out and desperate; please help me out. Below is the configuration file content, and the second one is the backup directory files list.

```
OUTPUT_URL=nfs://192.168.1.118/mnt/backup/rhel
BACKUP=NETFS
BACKUP_URL=nfs://192.168.1.118/mnt/backup/rhel
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
#NETFS_KEEP_OLD_BACKUP_COPY=y
BACKUP_TYPE=incremental
FULLBACKUPDAY=( Sun )
```

```
[root@pxe iso]# ll rhel-server-02/
total 4135152
-rw-------. 1 root root 3592429931 Jul 19 18:24 2024-07-19-0000-F.tar.gz
-rw-------. 1 root root    9372601 Jul 19 18:24 backup.log
-rw-------. 1 root root        202 Jul 19 18:24 README
-rw-------. 1 root root  631203840 Jul 19 18:24 rear-rhel-server-02.iso
-rw-------. 1 root root     169446 Jul 19 18:24 rear-rhel-server-02.log
-rw-------. 1 root root          0 Jul 19 18:24 selinux.autorelabel
-rw-------. 1 root root        287 Jul 19 18:24 VERSION
```

I appreciate your help.
![Screenshot 2024-07-19 180258](https://github.com/user-attachments/assets/8a338902-3da1-4b0e-9773-1fbc59354205)

**Comment by abbbi** [comment]
more info required.
you may want to share the iso image youve created. Could it be that the system in question is an UEFI system and youre attempting to boot via regular BIOS and SYSLINUX while the iso image is an UEFI bootable?

**Comment by msharif4** [comment]
I included OUTPUT=PXE and ran the command rear -v mkbackup, and it ran successfully. However, it didn't include an iso file. Just curious that without an iso, how can we restore the backup through PXE? Updated /etc/rear/local.conf file contents and backup file's content. Is there anything else that needs to be done?

```
OUTPUT=PXE
OUTPUT_URL=nfs://192.168.1.118/mnt/datastore/backup1/rhel
BACKUP=NETFS
BACKUP_URL=nfs://192.168.1.118/mnt/datastore/backup1/rhel
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
#NETFS_KEEP_OLD_BACKUP_COPY=y
BACKUP_TYPE=incremental
FULLBACKUPDAY=( Sun )
```

```
root@backup:/mnt/backup/rhel-server-03# ll
-rw------- 1 root root 1675321694 Jul 20 11:00 2024-07-20-1053-F.tar.gz
-rw------- 1 root root    5005087 Jul 20 11:00 backup.log
-rw------- 1 root root        516 Jul 20 10:56 README
-rw------- 1 root root        489 Jul 20 10:56 rear-rhel-server-03
-rw------- 1 root root     155071 Jul 20 10:56 rear-rhel-server-03.log
-rw------- 1 root root          0 Jul 20 11:00 selinux.autorelabel
-r-------- 1 root root  615039052 Jul 20 10:56 rhel-server-03.initrd.cgz
-r-------- 1 root root   13609080 Jul 20 10:56 rhel-server-03.kernel
-r-------- 1 root root        282 Jul 20 10:56 rhel-server-03.message
-rw------- 1 root root        282 Jul 20 10:56 VERSION
```
Thanks,

**Comment by msharif4** [comment]
rear-bitwarden.iso
<https://drive.google.com/file/d/1_nrE8O91X4cGDqMCnL1U9TdV4nKHKpkE/view?usp=drive_web>
Hi Michael,
It didn't allow me to attach it as an attachment so it got uploaded to the
Google drive. It's a virtual machine that created Linux KVM. Please let me
know if anything else is needed. Thanks

**Comment by abbbi** [comment]
this looks like the same issue than here:

https://github.com/rear/rear/issues/2471

**Comment by abbbi** [comment]
> I included OUTPUT=PXE 

yes, in this situation an initrd an kernel image are stored with the backups: 


> -rw------- 1 root root          0 Jul 20 11:00 selinux.autorelabel
> -r-------- 1 root root  615039052 Jul 20 10:56 rhel-server-03.initrd.cgz
> -r-------- 1 root root   13609080 Jul 20 10:56 rhel-server-03.kernel

which can then be booted via PXE.

the main problem however is why the generated iso image does not boot (and it doesnt boot using qemu either), it looks to me like an issue with UEFI/BIOS  like mentioned in #2471

**Comment by abbbi** [comment]
> rear-bitwarden.iso 

i loop mounted the iso image on my system and it seems like all files within the generated iso image are somewhat
broken. The iso images contents dont look sane to me. So either there has been a problem during creation of the iso image or the storage where the iso image comes from is broken..

**Comment by msharif4** [comment]
Can you provide me with all the contents that need to be added to the local
.conf file? I added all the content to the ticket. I will be using another
server via NFS to store the backup files. I don’t want to have the same
issue in the future. If you can update the existing content with the
correct parameters, I can use it.
I appreciate your help.

**Comment by msharif4** [comment]
No, the log file doesn't exist; I had two cron jobs run an hour apart, the first one ran to take backup, and the second one deleted the log file. That log file is removed, and the server is not booting up; that's why I wanted to restore the backup. Thanks

**Comment by msharif4** [comment]
Hi, I found the backup.log file. I am attaching it if that helps. Thanks,
[
[backup.log](https://github.com/user-attachments/files/16326233/backup.log)
](url)

**Comment by msharif4** [comment]
When the mkbackup job ran, it created a full backup; I mean, with iso, there is also a tar file **2024-07-19-0000-F.tar.gz**, which contains all of the directories such as / var, etc., boot, use, etc. Is there a way to restore the server using the .tar.gz file? Thanks

**Comment by abbbi** [comment]
> When the mkbackup job ran, it created a full backup; I mean, with iso, there is also a tar file **2024-07-19-0000-F.tar.gz**, which contains all of the directories such as / var, etc. boot, usr, etc. Is there a way to restore the server using the .tar.gz file? Thanks

without a working iso image it will be complicated. You can only setup a system with similar layout and restore the contents from the backup manually as required by extracting the data from the file backup.

**Comment by msharif4** [comment]
Got it. I will reinstall the OS and see if copying files works. To avoid such an issue in the future, I would like to re-configure the local.conf file with correct parameters. I added the below content into the file and ran "rear -v mkbackup" command, it created a full backup but it didn't create a .iso file. Having output file value pxe doesn't create an iso file? I would like to have a backup that I can restore through network boot.
```
OUTPUT=PXE
OUTPUT_URL=nfs://192.168.1.118/mnt/backup/rhel
BACKUP=NETFS
BACKUP_URL=nfs://192.168.1.118/mnt/backup/rhel
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
#NETFS_KEEP_OLD_BACKUP_COPY=y
BACKUP_TYPE=incremental
FULLBACKUPDAY=( Sun )
```
Thanks,

**Comment by abbbi** [comment]
OUTPUT=PXE will create two files as explained before. The linux kernel image and the initrd. Both can be booted via PXE. Complete ISO images are usually not booted via PXE, the PXE boot solution you are using seems to extract required contents from the ISO Image to make them boot via PXE.

**Comment by jsmeix** [comment]
@abbbi 
thank you for your help, in particular for
your debugging what the root cause was, cf.
https://github.com/rear/rear/issues/3288#issuecomment-2241288862

**Comment by jsmeix** [comment]
I assume it is sufficiently answered because "no news is good news".
(If not, reopen it with continuative information.)
