### ISSUE TITLE
DRLM_MANAGED=yes may source third party code from a remote host

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#3294]
@didacog 

For background information see
https://github.com/rear/rear/issues/3260
and its generic "parent"-issue
https://github.com/rear/rear/issues/3259

For this specific issue here see
https://github.com/rear/rear/issues/3285
and therein in particular for DRLM see
https://github.com/rear/rear/issues/3285#issuecomment-2244575251

The function drlm_import_runtime_config
in lib/drlm-functions.sh
may source third party code via
```
source $DRLM_CFG
```
where the DRLM_CFG file content
could be even downloaded from a remote host.

@didacog @rear/contributors 
it should be verified before the ReaR 3.0 release
if third party code could be sourced here
or if all is reasonably safe.

**Comment by didacog** [comment]
Hello @jsmeix 

This sources the rear config provided from DRLM over the network from the DRLM client configs.

Is completely safe to keep that source.

**Comment by jsmeix** [comment]
Hello @didacog 

do I understand it correctly that what is sourced here
is basically same as a local etc/rear/local.conf file
(and other usual ReaR config files)
but with DRLM those configs are stored on a DRLM server
which is basically the whole idea behind DRLM
to have various ReaR configs of various clients
stored and managed centrally on a DRLM server.

**Comment by didacog** [comment]
@jsmeix, correct! you nailed it! ;)

**Comment by jsmeix** [comment]
@didacog 
thank you for your prompt replies!
It helped me a lot.

**Comment by jsmeix** [comment]
Via
https://github.com/rear/rear/commit/1bce22e721ae1901ad56b119229ea7c5450abe83
I added in lib/drlm-functions.sh a comment
that explains how DRLM sources ReaR config files
to make it clear that all is OK with doing
```
source $DRLM_CFG
```

**Comment by jsmeix** [comment]
I removed the "critical/security/legal" label from this issue
because it is no longer "critical/security/legal", cf.
https://github.com/rear/rear/issues/3294#issuecomment-2244903207

**Comment by pcahyna** [comment]
Sourcing files from network looks rather problematic in general. Improvements in this area were done in #1252 , but I have not looked into details.

**Comment by schlomo** [comment]
AFAIK this is how DRLM works by design, so maybe the question should be how we can ensure a minimum level of trust between ReaR and the network source?

**Comment by didacog** [comment]
we only source configurations coming from drlm api, that is secured by token an over https. and only configurations for the client itself (rear) are available to each client.

we deploy rear and the drlm public key for the certificate and the token at install time.

not sure if this answers the question.

**Comment by jsmeix** [comment]
I think what is first and foremost needed
is documentation that explains the current state
so users understand what the current state really is
and what its current features and limitations are.

E.g. DRLM may (currently) not be intended to be used
via public Internet but only within a sufficiently
secured internal/private network. Or is perhaps
https plus token and private/public key things
already well sufficient to do DRLM communication
also via public Internet?

@didacog 
is such documentation already available?

Sorry if my question is ignorant.
I really don't know details about DRLM.

**Comment by pcahyna** [comment]
@jsmeix I suggest that you look at the changes in #1252.

**Comment by jsmeix** [comment]
Not exactly the explanatory documentation I was looking for.
I was looking for some more generic documentation and
not so much for specific config variable settings.

There I read
```
# DRLM_REST_OPTS, DRLM_SERVER and DRLM_ID variables can be changed
# in /etc/rear/local.conf and also can be updated at runtime.
# e.g.
#   rear recover SERVER=1.1.1.1 REST_OPTS="-k" ID=client01
```
By the way: It looks as if there are typos in the example
`SERVER` vs. `DRLM_SERVER`
`REST_OPTS` vs. `DRLM_REST_OPTS`
`ID` vs. `DRLM_ID`
?

It seems to mean that "rear recover" managed by DRLM
may run under contol of another DRLM server
with different options.
I assume this is an intentional feature but I wonder
if this might provide a way that could be somehow misused
to recreate a system different than what was intended?
Probably all is OK because in general the one who can
boot a ReaR recovery system and run "rear recover"
has full control how that system will be recreated
including changing restored files as he likes
same as anyone else who can install a system
from scratch on physical or virtual hardware.
But with "remotely managed by DRLM" things might be a bit
different and could be perhaps somehow "remotely misused"?

**Comment by didacog** [comment]
@jsmeix, ```DRLM_``` are defined in ```drlm_import_runtime_config```. This was the proper way to pass variables and tag them wit **DRLM_** so are only loaded if  ```is_true DRLM_MANAGED```.

Is to provide the hability to restore the DR from another instance of DRLM in different locations... it cannot be misused as is only configured when ReaR is deployed from the DRLM server and all is setup properly. There is no need to setup those things by hand, or without DRLM.

All DRLM options are ment to be used only with DRLM.
