### ISSUE TITLE
Better DRLM integration

### ISSUE THREAD

**Issue by didacog** [rear/rear#3297]
Hi all,

We've been wondering how to provide better DRLM & ReaR integration lately. We have some stuff, new and old, that would be better to integrate directly to the rear repo.

That being said, for us, makes no sense to push code that we cannot maintain or review other changes that can affect us with the integration, so we offer ourselves (DRLM Team) to be added as maintainers of the rear project, if no objections.

Waiting on your feedback.
Kind regards,
Didac

 [README](https://github.com/rear/rear/blob/master/README.adoc#authors-and-maintainers) *We hope that ReaR continues to prove useful and to attract more developers who agree to be maintainers.*

**Comment by gdha** [comment]
@didacog Hi Didac - from my side you are welcome as a ReaR maintainer.
@jsmeix @schlomo Please add your opinion as well.

**Comment by jsmeix** [comment]
Also from my side I welcome @didacog as a ReaR maintainer.

**Comment by didacog** [comment]
Thanks @gdha @jsmeix ! will be a pleasure to be a maintainer in Relax-and-Recover project as a DRLM Team representative if no objections.

**Comment by schlomo** [comment]
Hello @didacog welcome to ReaR and I'd be happy for you to join. Who exactly will be joining? Just you?

**Comment by didacog** [comment]
Hello @schlomo, thanks! 
we offered all of us, but whatever you prefer will be ok. 

kind regards,
Didac

**Comment by schlomo** [comment]
As you prefer

**Comment by didacog** [comment]
ok! then if ok, we can be: 

Ruben Carbonell @krbu
Pau Roura @proura 
Didac Oliveira @didacog 

we are glad to be able to join to the project, that inspired us to start our own project 11 years ago.

Kind regards,
Didac

**Comment by gdha** [comment]
> ok! then if ok, we can be:
> 
> Ruben Carbonell @krbu Pau Roura @proura Didac Oliveira @didacog
> 
> we are glad to be able to join to the project, that inspired us to start our own project 11 years ago.
> 
> Kind regards, Didac

Invitations are underway.

**Comment by krbu** [comment]
Hi all, glad to be part of the project.

**Comment by proura** [comment]
Hi everyone,
 
Happy to be part of the project. 
If there is anything I can help you with, count on me. 
Thank you!

**Comment by jsmeix** [comment]
I consider this as done.
If not, reopen it with further information.
