### ISSUE TITLE
[SLES] add SECURE_BOOT_BOOTLOADER into SUSE_LINUX.conf

### ISSUE THREAD

**Issue by jirib** [rear/rear#3300]
Wouldn't be ncie to have in `SLES_LINUX.conf` an example for `SECURE_BOOT_BOOTLOADER`?

That is:

```
$ cat /usr/share/rear/conf/SUSE_LINUX.conf 
# some scripts need this
COPY_AS_IS+=( /etc/sysconfig/network/config /etc/sysconfig/network/scripts/functions )

# uncomment for Secure Boot
# SECURE_BOOT_BOOTLOADER="/usr/lib64/efi/shim-sles.efi"
```

`/usr/lib64/efi/shim-sles.efi` is in fact symlink to `../../share/efi/x86_64/shim-sles.efi`.

Some details at: https://github.com/SUSE/doc-sleha/pull/404#issuecomment-2263007490

**Comment by jsmeix** [comment]
The ReaR scripts in usr/share/rear
are not meant as user config files so
usr/share/rear/conf/SUSE_LINUX.conf
is not the right place for user config settings.

We have example user config files in
usr/share/rear/conf/examples/

What matches most from the file name is
usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
which is the only one with UEFI in the file name.

**Comment by jsmeix** [comment]
Probably setting SECURE_BOOT_BOOTLOADER is no longer
required with current ReaR upstream master code, see
https://github.com/rear/rear/pull/3306#discussion_r1735815475
so this issue is perhaps meanwhile obsolete.

**Comment by gdha** [comment]
@jirib Are you satisfied with above replies and updates in the example configs?

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/3306
plus the updated SUSE documentation for SLE HA15 SP6
https://github.com/rear/rear/issues/3084#issuecomment-2330953577
this issue should be sufficiently fixed.
