### ISSUE TITLE
[RFE] Distribute `rear-release-notes.txt` under a more permissive license

### ISSUE THREAD

**Issue by lzaoral** [rear/rear#3302]
Fedora is undergoing a major check of licenses of its packages.  @pcahyna has noticed that [doc/rear-release-notes.txt](https://github.com/rear/rear/blob/master/doc/rear-release-notes.txt) file is distributed under the `CC BY-ND 3.0` license which is not allowed for documentation in Fedora, RHEL, Debian and possibly other distros.

Please, relicense this file under a more permissive license.  

At the moment, we have created a custom release archive in Fedora and RHEL with this file omitted but it would be nice to switch back to the official upstream release archives.

**Comment by jsmeix** [comment]
What git shows as autors of rear-release-notes.txt
```
# git log -p --follow doc/rear-release-notes.txt | grep '^Author: ' | sort -u
Author: Dag Wieers <dag@wieers.com>
Author: Dag Wieërs <dag@wieers.com>
Author: Damani <damani@rubrik.com>
Author: Gratien D'haese <gratien.dhaese@gmail.com>
Author: Johannes Meixner <jsmeix@suse.com>
Author: Johannes Röhl <Johannes.Roehl@novastor.com>
Author: Peter Oliver <git@mavit.org.uk>
Author: Schlomo Schapiro <schlomo@schapiro.org>
Author: gdha <gratien.dhaese@gmail.com>
Author: rowens275 <rowens@fdrinnovation.com>
```

**Comment by jsmeix** [comment]
Because in general ReaR is under GPL v3 license
I suggest to also have rear-release-notes.txt under GPL v3.

Hereby I (as one of the by git listed authors) I agree and
permit to change the license of rear-release-notes.txt
from its current license to GPL v3.

**Comment by jsmeix** [comment]
@lzaoral 
did Fedora's major check of licenses perhaps find
also other files in ReaR that are not under GPL v3
but have a different license explicitly specified?
If yes, could you please report them as a separated issue.
Ideally I would prefer to have all ReaR files under GPL v3
as far as possible legally and with reasonable effort.

**Comment by pcahyna** [comment]
@jsmeix My check was not very thorough. I basically looked ad what Debian is doing - they had stopped shipping `doc/rear-release-notes.txt` already. I also looked at usr/sbin/rear and noted that ReaR is GPL v3 or later (not just GPL v3): https://github.com/rear/rear/blob/1d03f236e1ecb57af75acef34e3acb0891beafdd/usr/sbin/rear#L9 .

**Comment by gdha** [comment]
> Because in general ReaR is under GPL v3 license I suggest to also have rear-release-notes.txt under GPL v3.
> 
> Hereby I (as one of the by git listed authors) I agree and permit to change the license of rear-release-notes.txt from its current license to GPL v3.

@jsmeix I have no problems to convert the license to GPL v3.

**Comment by jsmeix** [comment]
I think we should do the license change for ReaR 3.0 if possible.

**Comment by gdha** [comment]
@jsmeix okay will do it soon.

**Comment by pcahyna** [comment]
My understanding is that you should get agreements from all authors, or delete their contributions (@lzaoral is that right)? `git log  --author=dag@wieers.com --author=damani@rubrik.com --author=Johannes.Roehl@novastor.com --author=git@mavit.org.uk --author=rowens@fdrinnovation.com master -- doc/rear-release-notes.txt` shows the last commit:

```
commit 8d01a37c8b79a879cea59cb369f7ca8728189b02
Author: Johannes Röhl <Johannes.Roehl@novastor.com>
Date:   Thu Nov 12 12:06:36 2020 +0100
```

@JohannesRoehlNovaStor , FYI

**Comment by jsmeix** [comment]
I am not at all a software lincenses expert.
I also think I vaguely remember that to change a license
one needs to get agreements from all authors
which is my reason behind why I posted
https://github.com/rear/rear/issues/3302#issuecomment-2304184020

I think in practice it could be an impossible task
(i.e. impossible with reasonable effort in reasonable time)
to get agreements from all authors.

A possible way out could be to keep the current
doc/rear-release-notes.txt renamed e.g. to
doc/rear-release-notes-until-2.7.txt
and for ReaR 3.0 start from scratch with a new
doc/rear-release-notes.txt
keeping the unversioned name for the current one
to not break links and references at arbitrary places
that point to doc/rear-release-notes.txt

This way we could (by-the-way and hooray!)
mecilessly clean up our release notes
from any old and possibly outdated stuff,
cf. https://github.com/rear/rear/issues/3264

**Comment by pcahyna** [comment]
> A possible way out could be to keep the current
doc/rear-release-notes.txt as is but renamed
e.g. to doc/rear-release-notes-until-2.7.txt

Keeping the current release notes in the repo does not solve the problem of one file having a different license (and above all a non-free one) than the rest of the repo, so it is not a way out at all.

**Comment by jsmeix** [comment]
@pcahyna @lzaoral 
I (perhaps falsely assumed) you could then
(relatively easily) drop the old and outdated
doc/rear-release-notes-until-2.7.txt
from your RPM (or perhaps replace it with your own
that contains only a reference to out upstream one)
and you could provide (at least) the current
doc/rear-release-notes.txt
in your RPM.

If this is insufficient for what you need,
please help with getting agreements from all authors.

**Comment by pcahyna** [comment]
@jsmeix The main issue for us (at least in my POW) is not the lack of release notes in the package, but the inability to use the upstream source tarball at all and the resulting need of producing a cleaned-up tarball as the package source. Note that it is not just about the RPM, it is also about the SRPM, because the SRPM needs to be provided as well (distributions provide all their sources), and a file with such a license can not be shipped at all. It is also very confusing for anyone using the sources (they see that ReaR is GPL and they thus may assume that all the sources are GPL and then accidentally violate the license terms).

**Comment by pcahyna** [comment]
> If this is insufficient for what you need,
please help with getting agreements from all authors.

sure, but we need a plan B here in case we don't get it. What about doing what you proposed and then moving doc/rear-release-notes-until-2.7.txt to another repo (perhaps to the web pages)?

**Comment by gdha** [comment]
> My understanding is that you should get agreements from all authors, or delete their contributions (@lzaoral is that right)? `git log --author=dag@wieers.com --author=damani@rubrik.com --author=Johannes.Roehl@novastor.com --author=git@mavit.org.uk --author=rowens@fdrinnovation.com master -- doc/rear-release-notes.txt` shows the last commit:
> 
> ```
> commit 8d01a37c8b79a879cea59cb369f7ca8728189b02
> Author: Johannes Röhl <Johannes.Roehl@novastor.com>
> Date:   Thu Nov 12 12:06:36 2020 +0100
> ```
> 
> @JohannesRoehlNovaStor , FYI

@pcahyna @jsmeix Why not reaching out to them to inform the license change and mention explicitly if no reply is given an approval is assumed.

**Comment by pcahyna** [comment]
> mention explicitly if no reply is given an approval is assumed

IANAL, does not sound very legal to me TBH

**Comment by jsmeix** [comment]
@pcahyna 
regarding your
https://github.com/rear/rear/issues/3302#issuecomment-2333910077

Ah!
I didn't have the SRPM in mind.

But wouldn't it help to remove that file
in the RPM spec file section '%prep'
because I think I vaguely remember somehow
that the SRMP gets built after the '%prep' section
i.e. using possibly modified original sources
which is why one should normally not modify
the modify the original sources directly
but apply patches instead and for the latter case
see my
```
... or perhaps replace it with your own
that contains only a reference to our upstream one
```

I think such issues can be reasonably well
handled by RPM packaging means.

**Comment by gdha** [comment]
@jsmeix @pcahyna Why not remove the release-notes and documentation from our ReaR master branch and move it to a ReaR documentation source repository? Sources and documentation do not have to share the same tree.

**Comment by pcahyna** [comment]
@jsmeix 

> @pcahyna regarding your [#3302 (comment)](https://github.com/rear/rear/issues/3302#issuecomment-2333910077)
> 
> Ah! I didn't have the SRPM in mind.
> 
> But wouldn't it help to remove that file in the RPM spec file section '%prep' because I think I vaguely remember somehow that the SRMP gets built after the '%prep' section i.e. using possibly modified original sources which is why one should normally not modify the original sources but apply patches instead but in this case modifying the original sources is perhaps a valid exception?

No, that's not how `%prep` works. The SRPM contains the original source tarball and patches and `%prep` unpacks the tarball and applies the patches during the build of binary RPMs. If the original source tarball can't be included in the SRPM, one must build a new "original" that can be included, every time one wants to update the package.

**Comment by pcahyna** [comment]
> @jsmeix @pcahyna Why not remove the release-notes and documentation from our ReaR master branch and move it to a ReaR documentation source repository? Sources and documentation do not have to share the same tree. We already have a https://github.com/rear/rear-user-guide available.

yes, or just move the old release notes there and keep the new file that @jsmeix proposed in the sources (my preference).

**Comment by jsmeix** [comment]
@pcahyna 
do you have a URL to documentation that confirm this?
Next week - if time permits - I will try to find out
more about how '%prep' actually works - I remember
there had been something with "SRPM does not contain
pristine original sources" but I don't remenber the
details...

**Comment by pcahyna** [comment]
> @pcahyna do you have a URL to documentation that confirm this? Next week - if time permits - I will try to find out more about how '%prep' actually works - I remember there had been something with "SRPM does not contain pristine original sources" but I don't remenber the details...

@jsmeix

- http://ftp.rpm.org/max-rpm/s1-intro-to-rpm-rpm-design-goals.html
see "**Make it start with the original source code**"
- https://rpm-software-management.github.io/rpm/manual/buildprocess.html
see the order, `%prep` comes after "Unpack srpm"
- https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/
"One of the design goals of rpm is to cleanly separate upstream source from vendor modifications. For the Fedora packager, this means that sources used to build a package should be the vanilla sources available from upstream. "

I am curious whether SUSE has different guidelines, but I doubt it, AFAIK this is the main principle of RPM in general.

I wish you a relaxed and recovering weekend as well!

**Comment by gdha** [comment]
@rear/contributors  Please have a look at https://github.com/rear/rear/issues/3264 too (I almost forgot about it)?

**Comment by gdha** [comment]
@jsmeix Interesting article https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project

**Comment by jsmeix** [comment]
I will try to get this done for the "ReaR 2.8" milestone
so that Linux distributors can "just distribute" ReaR
without any licensing troubles.

**Comment by jsmeix** [comment]
In a current git clone
those are the only commits to doc/rear-release-notes.txt
which are not from Gratien or Schlomo or from me:
```
localhost:~/rear.github.master # git log -p \
 --follow doc/rear-release-notes.txt \
 | egrep '^commit |^Author: |^Date: ' \
 | egrep -v 'gratien.dhaese@gmail.com|jsmeix@suse.com|schlomo@schapiro.org' \
 | grep -1 '@'

commit 8d01a37c8b79a879cea59cb369f7ca8728189b02
Author: Johannes Röhl <Johannes.Roehl@novastor.com>
Date:   Thu Nov 12 12:06:36 2020 +0100
--
commit 34281671ebd2afd5978ecc46e2358891e869e794
Author: Damani <damani@rubrik.com>
Date:   Thu Oct 10 18:18:19 2019 -0700
commit 0eaf35f76aaeb63d66febe6e0257c66e9ecbec75
Author: Damani <damani@rubrik.com>
Date:   Fri Oct 4 16:52:55 2019 -0700
--
commit 643492e950ca394997661d6e7a7518a68b20acb9
Author: rowens275 <rowens@fdrinnovation.com>
Date:   Wed Sep 30 13:34:50 2015 -0400
--
commit fcce50989e2231ef0049d3afd3a0664d4c4e1a1c
Author: Peter Oliver <git@mavit.org.uk>
Date:   Mon Oct 20 17:54:42 2014 +0100
--
commit bbf63806d189118d16d0d75be354c2e6722a90aa
Author: Dag Wieërs <dag@wieers.com>
Date:   Fri Jun 22 21:15:25 2012 +0200
commit c46f50a13ee9d5622d8fa98ac69226dd7f58d31c
Author: Dag Wieërs <dag@wieers.com>
Date:   Thu Jun 7 21:22:49 2012 +0200
--
commit 569fb0f5c6e276a7727c6ec9dcd9d568f7dec15b
Author: Dag Wieers <dag@wieers.com>
Date:   Mon Nov 21 18:24:55 2011 +0000
commit b91baf682fd9f4e1b72884f574a8a726a86300fd
Author: Dag Wieers <dag@wieers.com>
Date:   Thu Nov 17 17:59:00 2011 +0000
```

**Comment by jsmeix** [comment]
@gdha
are you perhaps still in contact with Dag Wieers?
If yes, could you ask Dag if he agrees
to a license change of rear-release-notes.txt
from its current license `CC BY-ND 3.0`
to `GPL v3 or later`?

I think ideally Dag may agree to this license change
directly here in this GitHub issue (provided he can).

**Comment by dagwieers** [comment]
@jsmeix All fine by me! GPL v3 is acceptable for all my modifications.

**Comment by jsmeix** [comment]
@dagwieers 
thank you for your prompt reply that
a license change of rear-release-notes.txt
from its current license CC BY-ND 3.0
to GPL v3 or later is OK for you!

**Comment by jsmeix** [comment]
@rowens275
I would like to ask you if you agree
to a license change of "rear-release-notes.txt"
from its current exceptional license "CC BY-ND 3.0"
to "GPL v3 or later"?

We use "GPL v3 or later" in general for ReaR, see
https://github.com/rear/rear/blob/master/COPYING
and
https://github.com/rear/rear/blob/master/usr/sbin/rear
which reads
```
Relax-and-Recover is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
```

For the reason of this license change see
https://github.com/rear/rear/issues/3302#issue-2480126058

Your only commit to "rear-release-notes.txt" is
https://github.com/rear/rear/commit/643492e950ca394997661d6e7a7518a68b20acb9
which contains this single change in "rear-release-notes.txt"
```
 @@ -88,7 +88,7 @@ recovery process until the system runs:
 * Back-up backends
   - IBM TSM, HP DataProtector, Symantec NetBackup,
-    Bacula, tar, rsync
+    FDR/Upstream, Bacula, tar, rsync
```

**Comment by jsmeix** [comment]
@mavit 
I would like to ask you if you agree
to a license change of "rear-release-notes.txt"
from its current exceptional license "CC BY-ND 3.0"
to "GPL v3 or later"?

We use "GPL v3 or later" in general for ReaR, see
https://github.com/rear/rear/blob/master/COPYING
and
https://github.com/rear/rear/blob/master/usr/sbin/rear
which reads
```
Relax-and-Recover is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
```
For the reason of this license change see
https://github.com/rear/rear/issues/3302#issue-2480126058

Your only commit to "rear-release-notes.txt" is
https://github.com/rear/rear/commit/fcce50989e2231ef0049d3afd3a0664d4c4e1a1c
which contains this two changes in "rear-release-notes.txt"
```
 @@ -113,6 +113,10 @@ functionality:
   can be forced via the variable *USE_DHCLIENT=yes* (define in _/etc/rear/local.conf_).
   It is also possible to force DHCP at boot time with kernel option `dhcp`

+* By default, if DHCP is used, static network configuration is ignored.
+  Override this with *USE_STATIC_NETWORKING=yes* in
+  _/etc/rear/local.conf_.
+
 * Save layout and compare layouts for easy automation of making
   Relax-and-Recover snapshots (checklayout option)

 @@ -145,6 +149,10 @@ Relax-and-Recover, unless otherwise noted.
 The references pointing to *fix #nr* or *issue #nr* refer to our [issues  tracker](https://github.com/rear/rear/issues)


+### Version 1.17.0
+
+* A new configuration option, `USE_STATIC_NETWORKING=y`, will cause statically configured network settings to be applied even when `USE_DHCLIENT` is in effect.
+
 ### Version 1.16.1 (June 2014)

 * The validate rule for `xarg bash -n` changed into `xarg -n bash -n` so that rear is working correctly with older bash version 3 as well. Especially required for SLES 10, SLES 11 and EPEL 5 (issue #410).

```

**Comment by jsmeix** [comment]
Regarding the two changes of @DamaniN 
in "rear-release-notes.txt":

As far as I see
the first change dated Oct 5, 2019
https://github.com/rear/rear/commit/0eaf35f76aaeb63d66febe6e0257c66e9ecbec75
```
 @@ -194,6 +194,17 @@ for you.

 The references pointing to fix #nr or issue #nr refer to our issues tracker.

+Version 2.5.rubrik (October 2019)
+
+Abstract
+
+Added support for Rubrik Cloud Data Management (CDM)
+
+New Features:
+
+  o Added support for Rubrik Cloud Data Management (CDM) as an integrated
+   backup application.
+
 Version 2.5 (May 2019)

 Abstract
```
was undone by the subsequent commit on Oct 11, 2019
https://github.com/rear/rear/commit/34281671ebd2afd5978ecc46e2358891e869e794
```
 @@ -194,17 +194,6 @@ for you.

 The references pointing to fix #nr or issue #nr refer to our issues tracker.

-Version 2.5.rubrik (October 2019)
-
-Abstract
-
-Added support for Rubrik Cloud Data Management (CDM)
-
-New Features:
-
- o Added support for Rubrik Cloud Data Management (CDM) as an integrated
-   backup application.
-
 Version 2.5 (May 2019)

 Abstract
```

I don't know if we must ask in this case @DamaniN 
to agree to a license change of "rear-release-notes.txt"
from its current exceptional license "CC BY-ND 3.0"
to "GPL v3 or later"?

Nevertheless to be on the safe side I ask:

@DamaniN 
do you agree to a license change of "rear-release-notes.txt"
from its current exceptional license "CC BY-ND 3.0"
to "GPL v3 or later"?

We use "GPL v3 or later" in general for ReaR, see
https://github.com/rear/rear/blob/master/COPYING
and
https://github.com/rear/rear/blob/master/usr/sbin/rear
which reads
```
Relax-and-Recover is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
```

For the reason of this license change see
https://github.com/rear/rear/issues/3302#issue-2480126058

**Comment by jsmeix** [comment]
@mavit 
thank you for your prompt reply that
a license change of "rear-release-notes.txt"
from its current license "CC BY-ND 3.0"
to "GPL v3 or later" is OK for you!

**Comment by jsmeix** [comment]
@JohannesRoehlNovaStor
could you please have a look at
https://github.com/rear/rear/issues/3302#issuecomment-2468149845

Thank you in advance!

**Comment by jsmeix** [comment]
@rowens275
could you please have a look at
https://github.com/rear/rear/issues/3302#issuecomment-2468171038

Thank you in advance!

**Comment by schlomo** [comment]
@jsmeix I'm totally happy with any change you plan to do around the release notes. I've been asking myself the same question. I was also wondering how much we can automate the process of creating release notes and of creating the release itself.

I'd be most happy if the manual effort required for a new release can be reduced so that we can easily create releases more often than in the past.

**Comment by gdha** [comment]
> @jsmeix I'm totally happy with any change you plan to do around the release notes. I've been asking myself the same question. I was also wondering how much we can automate the process of creating release notes and of creating the release itself.
> 
> I'd be most happy if the manual effort required for a new release can be reduced so that we can easily create releases more often than in the past.

@jsmeix  @schlomo 
See also issue #3264 which was about this topic of automating the creation of release notes. The PR #3318 was closed for another reason, but can be revived again.

**Comment by schlomo** [comment]
FYI, https://rfc.archlinux.page/0040-license-package-sources/ shows that Linux distros are closing the remaining gaps of unlicensed content. We are therefore just in time with this topic and could check also other files for missing license coverage, defaulting to GPL3+

**Comment by jsmeix** [comment]
Since I made a new release-notes-2-8.md from scratch
https://github.com/rear/rear.github.com/blob/master/documentation/release-notes-2-8.md
this issue here does no longer block a ReaR release
and with that new release-notes-2-8.md from scratch
this specific issue is solved.
Improvements of the current text in
https://github.com/rear/rear.github.com/blob/master/documentation/release-notes-2-8.md
and/or future improvements towards automation of making
the release-notes should be done as needed
via separated issues and pull requests.
