### ISSUE TITLE
Issue  when starting recovery system (NVIDIA related / console log flodding) . rear not useable

### ISSUE THREAD

**Issue by rmueck** [rear/rear#3304]
* ReaR version ("/usr/sbin/rear -V"): 
`Relax-and-Recover 2.6 / Git`

* If your ReaR version is not the current version, explain why you can't upgrade: 
Package in repo is at V 2.6

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=PXE
BACKUP=NETFS
FULLBACKUPDAY=( Mon  Fri )
BACKUP_TYPE=incremental
FULLBACKUP_OUTDATED_DAYS=14
OUTPUT_URL=nfs://nas.fritz.box/volume1/PXE/images
BACKUP_URL=nfs://nas.fritz.box/volume1/PXE/images
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
`PC`

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
`x86 compatible `

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
```
BIOS
GRUB
```

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
```
SSD

```

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
/dev/nvme0n1     /dev/nvme0n1                nvme   disk                     931,5G
|-/dev/nvme0n1p1 /dev/nvme0n1p1 /dev/nvme0n1 nvme   part xfs                 488,3G /

```

* Description of the issue (ideally so that others can reproduce it):

When booting via PXE environment for rear i get flodding console messages and rear is not useable even it is running.
The flodding message is (repeating forever):

```Running 99-makedev.sh...
MEKADEV nvmem
/run/udev or or .... Aborting MAKEDEV 
```
Flodding with message (looping forever):

`[   89.713053] NVRM: The NVIDIA probe routine was not called for 1 device(s).`

NB: I am trying to recover to original source system.

Any help is highly appreciated!

**Comment by abbbi** [comment]
have you tried blacklisting the module causing these warnings using the grub boot commandline, as in

`modprobe.blacklist=MODULE_NAME`

like

`module.blacklist=nouveau`

**Comment by rmueck** [comment]
@abbbi : Thank you for the hint! 
By using this stanza in `site.conf`  `KERNEL_CMDLINE="modprobe.blacklist=nouveau"` the flodding message is gone,
and the nvidia related modules are loaded (verified by ssh into rescue system) - BUT: the screen turns black and i was unable to wake it up at the end - strange! I will do some more investigations ASAP.

**Comment by jsmeix** [comment]
@rmueck 
regarding "the screen turns black":

Does this mean that booting works so far for you,
so you see the bootloader menu correctly on your screen
and you also see some initial kernel boot messages
but then "the screen turns black"?

This could be an issue with false kernel command line
settings for the 'console'.

Regarding no further messages on the console see
https://github.com/rear/rear/issues/2843
in particular see
https://github.com/rear/rear/issues/2843#issuecomment-1196588256
what usually helps when you do not have a serial console.

When you do not have a serial console
but there are 'console' kernel command line settings
(check the kernel command line in your bootloader menu)
it usually helps to remove all 'console' settings
from the kernel command line to get the kernel default
behaviour which usually works best.

**Comment by jsmeix** [comment]
@rmueck 
regarding kernel video mode setting issues:

Sometimes it helps to specify the kernel command
line option `nomodeset` to avoid kernel video mode
setting issues.

In particular when using the ReaR recovery system
the simple kernel framebuffer driver with some
traditional VGA resolution should be sufficient.

Cf. starting at
https://github.com/rear/rear/issues/3194#issuecomment-2047646496
and some subsequent comments.

**Comment by rmueck** [comment]
@jsmeix 
Thanks for all this great tips! Finally the working solution is a combination of `nomodeset` and `vga=7` (have not tried other resolutions yet - i am sure they will work as well)

I must say the rear community is great - thanks! Going to close the issue.

**Comment by jsmeix** [comment]
@rmueck 
thank you for your prompt reply and in particular
for your information what exactly made it work for you
because that may later also help others.

@abbbi 
special thanks to you for your help here
even at non-working times on Sunday afternoon!
