### ISSUE TITLE
Is there any example configuration for creating a bootable medium and backup on one device?

### ISSUE THREAD

**Issue by danielrosehill** [rear/rear#3335]
Hi everyone,

While I know there are advantages to decoupling the backup medium from the actual backup copy of the OS, I was wondering if there are any sample `local.conf` configurations for those of us who want to live on the wild side and create a dual-purpose USB that's both bootable and which contains, on it, the full system backup (ie the file backup)?

I'm struggling a bit with figuring out how to set up such a configuration in the documentation.

TIA

**Comment by jsmeix** [comment]
E.g. see the "QUICK START GUIDE"
in the "README" section on
https://github.com/rear/rear
or directly at
https://github.com/rear/rear/blob/master/README.adoc
or alternatively the
"Relax-and-Recover Quick Start" on
http://relax-and-recover.org/documentation/getting-started

They show a sample local.conf as follows
(here without comments):
for BIOS booting
```
OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
```
and for UEFI booting
```
OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
SECURE_BOOT_BOOTLOADER=(/boot/efi/EFI/*/shimx64.efi)
```

In any case you need to prepare your USB stick/disk
with "rear format" to be used only for ReaR.
"rear format" destroys all existing data
on your USB stick/disk.

**Comment by jsmeix** [comment]
In general you may also have a look at the section
"First steps with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery
