### ISSUE TITLE
"chattr: command not found" Running rear recover using rescue ISO on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by cbmiller2610** [rear/rear#3338]
* ReaR version ("/usr/sbin/rear -V"): Relax-andRecover 2.7 / 2022-07-13

* If your ReaR version is not the current version, explain why you can't upgrade: https://software.opensuse.org/package/rear official version is at 2.7, no other community packages provide a newer version so I would have to build my own.

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): openSUSE Tumbleweed 20241011

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): 
[failed-local.conf.txt](https://github.com/user-attachments/files/17603675/failed-local.conf.txt)

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): Linux x64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): NVMe with secondary SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):
My NVMe drive recently began to mount read only (btrfs) and show errors with btfrs check. After replacing the drive and using the rear rescue ISO to attempt to recover, I ran into an issue where the disk recreation script is failing because of `chattr: command not found`.  No, I did not test this configuration (it worked perfectly with Fedora, so I got lazy and didn't test the ISO). However I'm using the Tarfile backup method and a separate backup of my home directory using Deja Dup, so nothing too critical will be lost... just time.

1. I believe I've run into https://github.com/rear/rear/issues/2927. Does this mean that this issue is fixed in Rear 2.8? If so, I will see if I can request a version bump from the maintainers of the package for Tumbleweed.
2. Am I screwed when it comes to restoring with the current ISO? Or, is there a way to get the missing chattr/lsattr binaries into the rescue system and complete the rescue? 

* Workaround, if any: none I can find

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): 
[failed-rear-localhost.log](https://github.com/user-attachments/files/17603690/failed-rear-localhost.log)

**Comment by cbmiller2610** [comment]
Update: I have made a lot of progress, and the bulk of my install is safe. I thankfully have another computer also running the same version of Tumbleweed, and I managed to copy over libraries and files that I needed for REAR to work: 

Steps
1) mount recovery drive
2) copy custom /etc/rear/rescue.conf with password prompt (using encrypted backup)
3) copy lsattr and chattr to /usr/bin
4) copy all missing lib* found using ldd on another machine to /lib64
```
dd /usr/lib/snapper/installation-helper 
	linux-vdso.so.1 (0x00007fcbda7a0000)
	libsnapper.so.7 => /lib64/libsnapper.so.7 (0x00007fcbda677000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcbda400000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcbda3d2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcbda000000)
	libboost_thread.so.1.86.0 => /lib64/libboost_thread.so.1.86.0 (0x00007fcbda3b4000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007fcbda245000)
	libacl.so.1 => /lib64/libacl.so.1 (0x00007fcbda66c000)
	libz.so.1 => /lib64/glibc-hwcaps/x86-64-v3/libz.so.1.3.1 (0x00007fcbda22b000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007fcbd9fb3000)
	libbtrfsutil.so.1 => /lib64/libbtrfsutil.so.1 (0x00007fcbda65f000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fcbd9f84000)
	libbtrfs.so.0 => /lib64/libbtrfs.so.0 (0x00007fcbda224000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcbd9e99000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcbda7a2000)
	liblzma.so.5 => /lib64/glibc-hwcaps/x86-64-v3/liblzma.so.5.6.3 (0x00007fcbd9e5e000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fcbd9e22000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fcbd9d77000)
	libeconf.so.0 => /lib64/libeconf.so.0 (0x00007fcbda215000)
```
5) copy over /usr/lib/snapper/installation-helper, and /usr/share/snapper/config-templates/default

**Comment by cbmiller2610** [comment]
Closing as it looks redundant to https://github.com/rear/rear/issues/2927, apologies!

**Comment by jsmeix** [comment]
The next ReaR release will contain
the two fixes
https://github.com/rear/rear/commit/64e9228e9178e717534526ba8ccd9a51af0cb4a8
and
https://github.com/rear/rear/commit/bfb4edf8ee30ebecb75b4019f86bc8f0a3e81460
which are needed to fix
https://github.com/rear/rear/issues/2927

**Comment by jsmeix** [comment]
@cbmiller2610 
regarding your question
```
I will see if I can request a version bump
from the maintainers of the package for Tumbleweed.
```
Because there is no newer ReaR release than 2.7
there cannot be a newer package version
in Linux distributions under normal circumstances
(i.e. when Linux distributions do not distribute
current work-in-progress upstream development states).
But you can on your own use any upstream state as needed
because ReaR is only bash scripts (plus documentation)
so nothing needs to be compiled or otherwise made usable.
E.g. see the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
or use our GitHub snapshots builds from
https://github.com/rear/rear/releases/tag/snapshot
