### ISSUE TITLE
Properly support site.conf and don't hack local.conf

### ISSUE THREAD

**Issue by schlomo** [rear/rear#342]
While doing 08387b9ba6c7b374edb56e01bc99ff8d060af440 I realized (grep for local.conf) that there are places where we check local.conf for a configuration setting and there are other places where we write to local.conf. 

Example: If users use site.conf to configure the use of DHCP in the rescue system then it won't work.

I think that this is very dangerous. Why not use the rescue.conf which is read *after* the local.conf for that purpose? Also, instead of greping local.conf for configuration items we should be sourcing in the ReaR configuration and use the value if set.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
