### ISSUE TITLE
rear for opensuse 12.3 grub2 issue

### ISSUE THREAD

**Issue by huawiceo** [rear/rear#346]
when reboot after recovery done, the system will run into grub, but opensuse use grub2. So I need to do below action to fix grub2 issue.
grub>root (hd0,1)
grub>setup (hd0)
grub>kernel /boot/vmlinuz
grub>initrd /boot/initrd
grub>boot
进入系统
#grub2-mkconfig -o /boot/grub2/grub.cfg
#grub2-install /dev/sda
#reboot 
An then, the system is OK.
Could you please check this issue for opensuse grub2? Thx

**Comment by gdha** [comment]
added to the release notes so we can close this issue
