### ISSUE TITLE
REAR support for Linux on the Power Architecture

### ISSUE THREAD

**Issue by earleye2014** [rear/rear#365]
I work with numerous customers who have implemented Linux on Power and they would like a solution like REAR.  I have found that REAR can be executed on Power; however, currently it appears to not be possible to generate an ISO that is bootable on Power.  Are there any plans to support Linux on Power?  I could potentially help with this effort be providing information on the specific files that would need to be written to the ISO file to make it bootable on Power.

Thanks for your consideration

**Comment by gdha** [comment]
PPC support is already included in rear -1.17. We can close this general request for now.
