### ISSUE TITLE
Does REAR support DRBD on LVM?

### ISSUE THREAD

**Issue by dragon299** [rear/rear#368]
Hello,

I am currently try to find out, if REAR does support DRBD on LVM volume. I know that LVM on DRBD works perfectly but I never tried the other way around. 

Is there someone who already tried this?

Thank you.

**Comment by gdha** [comment]
@bbeaver the diskrestore.sh script is generated during the `rear recover` session. You should copy it over to another system at the moment rear stops working. The script is auto-generated. That is the reason you do not have it by default.
Furthermore, running a `rear -vD recover` will generate a full debug file which is interesting to see where it fails and why...

**Comment by dragon299** [comment]
A few days ago I was able to do a restore with DRBD on LVM using REAR 1.17.2 on RedHat 7.2 without any issues. Maybe the problem is already fixed or does not exist on all plattforms.

**Comment by gdha** [comment]
@dragon299 That is good news. You can always pre-view the diskrestore.sh script - see http://www.it3.be/2016/06/08/rear-diskrestore/

**Comment by jsmeix** [comment]
According to https://github.com/rear/rear/issues/368#issuecomment-245303193
I think we can clse it as "fixed" - at least for now - it can be
reopened if needed.
