### ISSUE TITLE
Root file system is 100% full after recovery

### ISSUE THREAD

**Issue by gbeckett** [rear/rear#377]
I'm using Rear 1.15 on a RHEL 5.8 server. It has internal disks for the /boot and vg00 LVM volume group and SAN storage from an EMC VNX array and we are using Multipath for the 6 SAN storage devices.
Using the following local.conf variables I have been able to successfully backup the server.
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://#.#.#.#/admin/rear/"
NETFS_KEEP_OLD_BACKUP_COPY=2

When I attempt to recover the server it complains with the following error for all the devices. 
****
No code has been generated to restore device pv:/dev/mpath/mpath3p1 (lvmdev).
Please add code to the /var/lib/rear/layout diskrestore.sh to manually install it or choose abort.
****

I found issue #228 and edited the disklayout.sh file and changed the mpath to mapper as directed for each of my multipath deivces. But when I run the recover command I get the same errors. 
Now I've tried this a number of times, both with editing disklayout.sh and changing those lines and "not" changing them, but I get the same result. 
That being, the server is recovered, I can boot it, the LVM volumes are created, my multipath devices are there, BUT the root volume group vg00 is 100% FULL.  I can increase the size of root with a lvresize and a fsadm resize and all works. It was initially 4GB and had to increase it to 5GB. 
Then next time I attempted the recover, root was again 100% FULL so I had to increase the size from 5GB to 6GB. I cannot find where the extra data is being stored. I thought it was the inodes, but a df -i / indicates that only 1% of the inodes are being used. I've scanned the root file system and have compared it against another server identically built (but has not been Rear recovered) but I cannot find the problem. 
Can anyone make some suggests with respect to the mpath errors and the root file system being 100% full?
Thank you very much.
Gary

**Comment by gdha** [comment]
@gbeckett I guess you give up with rear? SAN disks are normally not touched during recovery, but as I never saw any evidence from your side I cannot say much more about it.
I'll close this issue - if you have some new input you may re-open this request
