### ISSUE TITLE
Ability to perform manual Netbackup restore instead of automated?

### ISSUE THREAD

**Issue by andyeff** [rear/rear#378]
Hi there,

I'm running Rear with the ISO + NBU (Netbackup) restore method, and am wondering if there is a way to have the restore process allow the restore engineer to send a selective Netbackup restore operation to the server, rather than use the automatic system currently in place.

For example: I boot a server from ISO, and run 'rear recover'. I press Enter twice to confirm I am restoring to the same machine and that I want to use the latest backup set.

REAR will then (as I understand it) query backups from 5 days ago, and start restoring from them. HOWEVER, due to the way the backup tapes are handled, this is unfortunately a bit inflexible for me, as some backup tapes may not be available. What I would want to do instead is to stop the automatic netbackup from running, and pause the scripts so I can send a more specific restore operation to the server.

For example, commenting out / removing lines 66-71 from the relevant script:
https://github.com/rear/rear/blob/79f5c64a3e8e12beeb4b924c6e6ccfd9bae70720/usr/share/rear/restore/NBU/default/40_restore_with_nbu.sh#L66-L71

And having the rear recover operation pause while I restore manually, then resume its finishing operations after the recovery is complete (replace the commented-out lines with: read -p "Press Enter to continue" for example.

Is there a way to do something like this with certain parameters in local.conf ? Or would I best need to alter the existing scripts on the machine before running the initial 'rear mkrescue' and generating the ISO?

**Comment by gdha** [comment]
@andyeff @schlomo @rear/contributors  Maybe `RESTORE_NR_DAYS` seems a better name for the variable. OK?

**Comment by andyeff** [comment]
Sounds good!

**Comment by schlomo** [comment]
If this variable is specific to NBU it **must** start with NBU_ because only then will `rear dump` actually show it.

**Comment by gdha** [comment]
The whole discussion is not needed any more as commit https://github.com/rear/rear/commit/45717daf09ce05e53fcf27827299f7d8678adb98#diff-9df2ad19942f62489ef3385c320f4bfc removed the Get_Start_Date function.
