### ISSUE TITLE
REAR with BACKUP=NSR breaks YUM on RHELv6

### ISSUE THREAD

**Issue by pteegarden** [rear/rear#387]
"I have installed a standard system with RHEL6.

I installed "rear" (Relax and Recover) from the epel. No problem.
I installed the dependencies (genisoimage, syslinux, and mtools) No problem.

If I run "rear mkrescue" with the standard configuration (OUTPUT=ISO), all is well.
IF I run "rear mkrescue" with the additional configuration option (BACKUP=NSR), it breaks any further attempt to use YUM.

It does this, as far as I can tell, because it changes the standard library association from

/lib64/libexpat.so.1 -> libexpat.so.1.5.2

to

/lib64/libexpat.so.1 -> ./libexpat.so

I can get YUM working again by putting the original link back in place.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
