### ISSUE TITLE
Network interfaces not recognized in recent version

### ISSUE THREAD

**Issue by ypid** [rear/rear#405]
Hi

I noticed that current rear master checkout does not show any network interfaces (except of lo) in recover mode with a current Debian testing amd64 system.

I was able to track the commit down which introduced this behavior (using git bisect). It was first introduced in 4ff29ff439a3d9d5b46911f52e52bbe24346bd52.

My systemd version is:
systemd 204
+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ

**Comment by gdha** [comment]
added to the release notes so we can close this issue
