### ISSUE TITLE
No layout recreation code generated for btrfs fs on Debian testing

### ISSUE THREAD

**Issue by ypid** [rear/rear#408]
Hi

During migration with ReaR I noticed that there was not layout generation code for my root filesystem which is btrfs. Also, because of the disk dependency system of ReaR, /boot was also not created (which I could fix by commenting out my root fs from the disklayout.conf file).

I am not sure what the problem is. When I need to migrate (or restore) once again in the future I will further investigate this issue. For now I could fix it by writing the section for the root fs myself.

Also I noticed that ReaR was not able to handle a swap partition, which is encrypted (and created) with a random key on each start. ReaR would have to do nothing more than to create a partition (which is then setup by dm-crypt on startup). The creation (mkswap) is not needed. Maybe possible to add a test for this.

https://github.com/rear/rear/blob/master/usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh

	disk /dev/sda 120034123776 msdos
	part /dev/sda 499122176 1048576 primary boot /dev/sda1
	part /dev/sda 1999634432 500170752 primary none /dev/sda2
	part /dev/sda 117533835264 2499805184 primary none /dev/sda3
	fs /dev/dm-0 / btrfs uuid=3a5e7bfe-1f80-4843-93f4-48c8670b840c
		devid1size109.46GiBused109.46GiBpath/dev/disk/by-uuid/3a5e7bfe-1f80-4843-93f4-48c8670b840c label= options=rw,noatime,nodiratime,space_cache
	fs /dev/sda1 /boot ext4 uuid=308700cb-7c8f-4cec-9d21-dbc77ab3858d label= blocksize=1024 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=4093 default_mount_options=user_xattr,acl options=rw,nosuid,nodev,noexec,noatime,nodiratime,data=ordered
	swap /dev/mapper/sda2_crypt uuid=2fb8c04e-9338-4f31-96da-cd6c91968578 label=
	crypt /dev/mapper/sda3_crypt /dev/sda3 cipher=aes mode=xts-plain64 hash=sha1 uuid=2be2e1ec-c91f-464f-a296-28ff54c49a77

**Comment by gdha** [comment]
@ypid Were you able to test rear-1.17.0 already on Debian with btrfs? Does it work now or is it still an issue?

**Comment by ypid** [comment]
I might be able to test this in a few months as I don’t have rear setup currently.

**Comment by jsmeix** [comment]
No further feedback sinde more than one year and
meanwhile I implemented generic support for btrfs
so that it should basically work (at least it works
for the relatively comlicated SLES btrfs structure).

I think we can close it as "fixed".
If needed it can be reopened.
