### ISSUE TITLE
REAR & Networker - Function 'iconv_open' failed

### ISSUE THREAD

**Issue by bastiw88** [rear/rear#411]
Hi, 

I tested REAR (1.15 & 1.16) in combination with EMC² Networker (V 8.1) on Ubuntu 12.04 LTS (64Bit). 

"rear -v mkbackup" works fine. 

"rear recovery" failed (screenshot below):

Function 'iconv_open' failed for UTF-8 to ANSI conversion. The function may be unable to determine the current locale. Verify appropriate values in environment variables LC_MESSAGES, LC_ALL and LANG.

Please help me to fix this issue!

Thanks

**Comment by gdha** [comment]
@bastiw88 @rear/contributors @chnusti Were you able to test rear-1.17.0 with NW 8.1 already? Does it work better or is it still the same?

**Comment by bastiw88** [comment]
@gdha 
Sorry for the delay. 
I tryed to test it with the following Settings:

lgtoclnt                               8.1.2.3 
rear                                   1.17.1

Ubuntu 12.04.5 LTS
3.2.0-37-generic 

site.conf:
BACKUP=NSR
OUTPUT=ISO
OUTPUT_URL=nfs://XXX.FQDNl/data/col1/backup/rear/output
NSRSERVER=BAK.FQDN
RETENTION_TIME="5Weeks"
USE_CFG2HTML=y

Same error :-(

Any idea?

Thanks 
BR

**Comment by bastiw88** [comment]
additional information:



Relax-and-Recover 1.17.1 / Git
Using log file: /var/log/rear/rear-XXX.log.lockless
Dumping out configuration and system information
This is a 'Linux-x86_64' system, compatible with 'Linux-i386'.
System definition:
                                    ARCH = Linux-i386
                                      OS = GNU/Linux
                        OS_MASTER_VENDOR = Debian
                       OS_MASTER_VERSION = 12.04
                   OS_MASTER_VENDOR_ARCH = Debian/i386
                OS_MASTER_VENDOR_VERSION = Debian/12.04
           OS_MASTER_VENDOR_VERSION_ARCH = Debian/12.04/i386
                               OS_VENDOR = Ubuntu
                              OS_VERSION = 12.04
                          OS_VENDOR_ARCH = Ubuntu/i386
                       OS_VENDOR_VERSION = Ubuntu/12.04
                  OS_VENDOR_VERSION_ARCH = Ubuntu/12.04/i386
Configuration tree:
                         Linux-i386.conf : OK
                          GNU/Linux.conf : OK
                             Debian.conf : missing/empty
                        Debian/i386.conf : missing/empty
                       Debian/12.04.conf : missing/empty
                  Debian/12.04/i386.conf : missing/empty
                             Ubuntu.conf : OK
                        Ubuntu/i386.conf : missing/empty
                       Ubuntu/12.04.conf : missing/empty
                  Ubuntu/12.04/i386.conf : missing/empty
                               site.conf : OK
                              local.conf : OK
Backup with NSR
                            NSR_ROOT_DIR = /nsr
                  BACKUP_INTEGRITY_CHECK =
                         BACKUP_MOUNTCMD =
                          BACKUP_OPTIONS =
                    BACKUP_RSYNC_OPTIONS = --sparse --archive --hard-links --verbose --numeric-ids --stats
                  BACKUP_SELINUX_DISABLE = 1
                             BACKUP_TYPE =
                        BACKUP_UMOUNTCMD =
                              BACKUP_URL =
Output to ISO
                                 ISO_DIR = /var/lib/rear/output
                               ISO_FILES =
                              ISO_IMAGES =
                        ISO_ISOLINUX_BIN =
                            ISO_MAX_SIZE =
                         ISO_MKISOFS_BIN = /usr/bin/mkisofs
                              ISO_PREFIX = rear-XXX
                               ISO_VOLID = RELAXRECOVER
                           RESULT_MAILTO =

/usr/share/rear/lib/validated/Ubuntu/12.04/i386.txt
Your system is validated with the following details:
Version:     Relax-and-Recover 1.14 / Git
Validation:  Ubuntu/12.04/i386
Submitted:   Andreas Lemke <andreas.lemke@tu-bs.de>, TU Braunschweig/Sprachenzentrum, Germany
Date:        2013-07-17
Features:    PXE
Comment:     We added /usr/share/rear/output/PXE/default/82_copy_to_net.sh to transfer the PXE files to the PXE server.

**Comment by gdha** [comment]
@bastiw88 if you check the installation manual of NSR does it mention anything special? Like a package that must be present to make NSR work properly? I think we need to verify this first before doing something on the rear side...

**Comment by bastiw88** [comment]
@gdha Please find all depentencies in this deb package below: 

 new debian package, version 2.0.
 size 110152288 bytes: control archive= 3707 bytes.
     870 bytes,    17 lines      control
    5746 bytes,   235 lines   *  postinst             #!/bin/sh
    1879 bytes,    74 lines   *  postrm               #!/bin/sh
    1602 bytes,    65 lines   *  preinst              #!/bin/sh
     809 bytes,    30 lines   *  prerm                #!/bin/sh
 Package: lgtoclnt
 Version: 8.1.2.3
 Architecture: amd64
 Section: non-free/admin
 Priority: optional
 Depends: ksh | pdksh, libacl1, libc6, libexpat1, libgcc1, libpam0g, libstdc++5, libx11-6, libxext6, libxml2, libxp6, libxt6, zlib1g
 Recommends: libncurses5
 Maintainer: EMC support <support@emc.com>
 Description: NetWorker Client
  EMC NetWorker protects the critical business data of more than 10,000
  enterprise customers worldwide by simplifying, centralizing, and automating
  backup and recovery operations across Unix, Windows, Linux and NetWare platforms
  in DAS, NAS, and SAN storage environments. Built upon an open, highly scalable
  client-server architecture, NetWorker reduces management overhead by providing
  "lights out" protection of storage assets in the largest corporate data centers
  and the smallest satellite branch offices.
 Homepage: http://www.emc.com

Addidionally you need the package "rpcbind" in ubuntu (apt-get install rpcbind). But this is not specific for lgto 8.x. It's necessary in all version of lgto client.

BR

**Comment by bastiw88** [comment]
This configuration works in /etc/rear/site.conf:

COPY_AS_IS=( ${COPY_AS_IS[@]} /usr/lib/x86_64-linux-gnu )

BR

**Comment by schlomo** [comment]
That will enlarge the rescue image by all the libraries in that directory. Better would be to be more specific and take only what we need. Also, the library path will be different depending on the distro etc. That is why we have the LIBS variable for libraries. The content will be resolved and searched for, not simply copied as is.

**Comment by gdha** [comment]
@bastiw88 could you test out with `ldd` command which libs it actual needs?

**Comment by schlomo** [comment]
And if `ldd` does not show it, please try to use `strace` to find out which libraries are loaded dynamically.

**Comment by gdha** [comment]
@bastiw88 any comments or update to share? Otherwise we would like to close this issue

**Comment by gdha** [comment]
If you have additional information please feel free to re-open this issue
