### ISSUE TITLE
output / PXE / default / 82_copy_to_net.sh doesn't differentiate between rsync proto and rsync ssh

### ISSUE THREAD

**Issue by paianoa** [rear/rear#412]
I would expect that OUTPUT_URL obeys the same syntax of BACKUP_URL when using rsync but it doesn't: 

 rsync://[USER@]HOST[:PORT]/PATH # using ssh
 rsync://[USER@]HOST[:PORT]::/PATH # using rsync

**Comment by gdha** [comment]
Solution works fine for me as it is - without contracting time we will not change it - we close the request until further notice
