### ISSUE TITLE
Redundant ISO on local hard disk

### ISSUE THREAD

**Issue by ctwombly** [rear/rear#419]
Here's a sample of my configs:

local.conf
````
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=file:///test
BACKUP_URL=iso:///backup
ISO_MAX_SIZE=4400
````
default.conf:
````
/* all default values with the following exception */
ISO_DIR=/temp
````
The issue I'm reporting is that when you define OUTPUT_URL to a local directory - for example /test - rear creates an ISO file at /test but also creates a subdirectory called localhost.  Within /test/localhost is the same ISO file found at /test along with the logfile and text documents.  This behavior is correct based on the current rear settings but could cause issues if the ISOs are large and there is limited disk space.  

What I'm trying to achieve is create an ISO backup on the local disk and then manually export this later, but eliminate the redundant ISO created on the local disk.  It appears that ISO_DIR should be able to be defined as a blank value - and thus ignored by rear - so that the only local backup is created at the OUTPUT_URL defined location.  

I have also tried to define OUTPUT_URL as nfs and point it to an unknown/unreachable IP address, hoping that rear would create the local copy based on the ISO_DIR declaration and then simply ignore the external copy since it can't route to that IP address, but unfortunately this causes rear to fault and terminate.

**Comment by gdha** [comment]
added to the release notes so we can close this issu
