### ISSUE TITLE
Incremental backup options with rear

### ISSUE THREAD

**Issue by bbeaver** [rear/rear#421]
I'm testing with rear 1.16 and have not had any luck with incrementals. I'm using the following config: 

@cal-s with rear it is now possible to make incremental and full backups:
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://lnx01/vol/lnx01/linux_images_dr/rear
BACKUP_TYPE=incremental
FULLBACKUPDAY="Mon"

I've run "rear mkbackuponly" three times in a row, modifying a few files in between so I can check to see if only the incremental changes get picked up. What appears to happen instead, is rear creates what appears to be a full backup each time:

-rw-r--r--. 1 root root 2016177806 Jun 4 12:49 2014-06-04-1243-F.tar.gz
-rw-r--r--. 1 root root 2014242030 Jun 4 12:59 2014-06-04-1253-I.tar.gz
-rw-r--r--. 1 root root 2015048301 Jun 4 13:11 2014-06-04-1305-I.tar.gz

When I run the rear recover process, the first saved file is what gets restored, (2014-06-04-1243-F.tar.gz). Should I be prompted during the recovery process so that I can tell rear which bkup/incremental I want applied? Thanks for your help - great program, I've just got to figure incrementals out.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
