### ISSUE TITLE
NetWorker:  95_nsr_save_result_files.sh fails to identify the correct tape pool to use

### ISSUE THREAD

**Issue by IanSJones** [rear/rear#429]
With NetWorker 8.1.1.5 (at least) when you run the command to list the pool(s) that the client uses you get many lines returned (usually of the same pool but can be others in there).  This sets the variable POOLNAME incorrectly.
If more than one pool name is returned we don't actually know which one to use so I have decided to use the first one returned.

Before:  line 42:  POOLNAME="$( mminfo -s $NSRSERVER -a -q "client=$CLIENTNAME" -r "pool" )"
After:  line 42:  POOLNAME="$( mminfo -s $NSRSERVER -a -q "client=$CLIENTNAME" -r "pool" | head -1 )"

**Comment by gdha** [comment]
added to the release notes so we can close this issue
