### ISSUE TITLE
[Debian testing]: /boot not correctly modified to boot after recovery

### ISSUE THREAD

**Issue by ypid** [rear/rear#434]
Hi

I noticed that after a recovery from Debian testing the system was not booting because it did not find it‘s root filesystem (changing UUID, new btrfs filesystem). The problem can be easily fixed by booting with the Debian installation CD in recover mode and either substitute the old UUID with the new one or just run `update-grub2`. I tried both methods on else untouched recovered systems successfully …

So I would suggest that rear chroot‘s into the recovered system and tries to run `update-grub2`. What do you think?

**Comment by gdha** [comment]
@ypid btrfs code has been enhanced in the meantime, so if you find the time try out rear-1.17.1.

**Comment by ypid** [comment]
I am afraid that currently I don’t find the time. To be honest, I am not using rear currently.

**Comment by gdha** [comment]
@ypid no problem then I just close the issue.
