### ISSUE TITLE
iscsi support - howto example requested

### ISSUE THREAD

**Issue by bbeaver** [rear/rear#435]
Could someone post a real live example of performing a full restore from an iscsi device?  Please reference  "Add iscsi support #64".  The goal is to first perform a full boot iso and tar backup using rear to an iSCSI mounted filesystem on my linux server, and then be able to do a recovery/restore from this iSCSI device when needed.  Thank you

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature

**Comment by msabry2020** [comment]
I have done a working demo to restore a rear backup from iscsi device. @gdha can you advise how to publish it ?

**Comment by jsmeix** [comment]
@msabry2020 FYI:
According to https://github.com/rear/rear/issues/2429
`currently iSCSI needs special manual setup`
Therein see in particular
https://github.com/rear/rear/issues/2429#issuecomment-645626221
and the subsequent comments therein for a description
how @gozora did a recovery with iSCSI devices
with some additional manual setup.

**Comment by gdha** [comment]
@msabry2020 What do you have in mind? A sub-chapter in the user guide perhaps? Or, is your intention to prepare a Pull Request to add a new feature into ReaR? I re-open this issue for further comments...

**Comment by msabry2020** [comment]
@gdha I've just came through this while I was trying to do the same scenario "to restore rear backup on iscsi device". I just wanted to share my findings.
