### ISSUE TITLE
Shortname vs longname causes "show log" to fail

### ISSUE THREAD

**Issue by jezzaaa** [rear/rear#439]
Due to an error when trying to recover, I get a menu giving me several options, one of which is to view the log.  If I try, it gives me an error.  Turns out that it's trying to show me a logfile that has my server's FQDN instead of shortname.

I think the shortname is what's supposed to be used (conf/default.conf sets HOSTNAME to "$(hostname -s)").  But it seems skel/default/etc/scripts/system-setup has this line:

       (1) less /var/log/rear/rear-`uname -n`.log;;

I think it should be using $HOSTNAME instead of `uname -n`.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
