### ISSUE TITLE
rear rescue ISO image kernel panic

### ISSUE THREAD

**Issue by kamensa** [rear/rear#444]
Hi All,

I have installed REAR on RHEL 6.5 - 2.6.32-431.el6.x86_64, physical box and RHEL 5.10 - 2.6.18-371.el5 i686 - VM on VirtualBox. REAR versions which I have used are rear-1.16.1-1.el5 and rear-1.15-9.el6.noarch. The backup process completes without any issues. I'm using NFS share for backup and iso files but when I try to boot from rescue image I get kernel panic. The same result on physical box and VM. Could you tell me how to attached my local.conf, site.conf and rear log file here? Basically I have copied default.conf into /etc/site.conf and changed the following:

BACKUP=NETFS
OUTPUT=ISO
BACKUP_URL=nfs://camstore3a/vol/camreardr_nfs
OUTPUT_URL=nfs://camstore3a/vol/camreardr_nfs
EXCLUDE_MOUNTPOINTS=("Data dirs")

The /etc/rear/local.conf contains: OUTPUT=ISO

The /etc/rear/os.conf contains:
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6

Here are the kernel panic snapshots:

![physical_box](https://cloud.githubusercontent.com/assets/8297326/3733319/ad880bc0-1706-11e4-9508-a0843d8bf269.PNG)

![vm_box](https://cloud.githubusercontent.com/assets/8297326/3733322/b5da43d8-1706-11e4-94c8-7b60eb9c7e39.PNG)

**Comment by gdha** [comment]
@kamensa Sorry for the delay...
The `MODULES_LOAD=( ${MODULES_LOAD[@]} ext3 )` is the correct definition.
Did you try the latest rear-1.17.1?

**Comment by gdha** [comment]
death case I'm afraid
