### ISSUE TITLE
ReaR - Ubuntu 14.04 - /dev/sda main disk not detected 

### ISSUE THREAD

**Issue by niteenk** [rear/rear#446]
I tried ReaR on Ubuntu 14.04 using bootable usb disk. Backup went through without problem but while recovering I can see /dev/sda which is my main disk having Ubuntu installed on it is not detected. /dev/sda is missing when I checked with fdisk -l.

Is this known issue or ReaR is not supported on Ubuntu 14.04. What should I check to debug this issue? 

Any help really appreciated.

thanks,

**Comment by gdha** [comment]
@rmerch1 Any luck with rear recovery?

**Comment by rmerch1** [comment]
No, thank you for following up. is there a newer version that has the fix already I could test with? The workaround may work but I was not able to get it to work. Has anyone else verified it works?

**Comment by gdha** [comment]
added to the release notes so we can close this issue - if the problem re-occurs then re-open or create a new issue

**Comment by rmerch1** [comment]
Thanks, I appreciate it.

**Comment by rmerch1** [comment]
I just wanted to confirm that thankfully this issue and the keyboard not working in Ubuntu 14.04 both seem to be resolved with 1.17. Thank you.
