### ISSUE TITLE
Rebuild initrd/initramfs in finalize stage for Arch, Gentoo

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#45]
Currently after recovering to a new system, only for Debian and SuSE the initrd is being recreated in order to support hardware changes. We need to extend this to other distributions (Arch, Gentoo) based on the supported infrastructure.

* finalize/Gentoo/i386/17_rebuild_initramfs.sh
  - needs to be written, I have no idea what should be done here (since I don't have Gentoo)

**Comment by gdha** [comment]
seems a dead issue
