### ISSUE TITLE
Disk Layout Generation with HP SmartArray with mor than one Logical Drive

### ISSUE THREAD

**Issue by wzwei** [rear/rear#455]
I experienced a bug in the generation of the disk layout file. My tests run on a system with four
disks building two Raid-1 logical drives. As far as I understand the array configuration part in the
recovery step, there should be two "logicaldrive"-Lines in disklayout.conf. Apparently mine has
only one entry:

logicaldrive /dev/sdb 0|B|2 raid=1 drives=1I:1:1,1I:1:2,1I:1:3,1I:1:4, spares= sectors=32 stripesize=256

But it should be like that:

logicaldrive /dev/sda 0|A|1 raid=1 drives=1I:1:1,1I:1:2, spares= sectors=32 stripesize=256
logicaldrive /dev/sdb 0|B|2 raid=1 drives=1I:1:3,1I:1:4, spares= sectors=32 stripesize=256

I had a look at 27_hpraid.layout.sh. The faulty part seems to be the while-loop starting at line 54. 

Regards, 
Wolfgang

**Comment by gdha** [comment]
added to the release notes so we can close this issue
