### ISSUE TITLE
interface misconfigured after successful restore

### ISSUE THREAD

**Issue by kruntas** [rear/rear#460]
Hi,

I have rear installed on RHEL 6 and experiencing the following issue:

 in ip_addresses I have configured
eth0 192.168.80.100/18

restore finishes fine but in the ifcfg-eth0 it leaves me with:
IPADDR='192.168.80.100/18'
NETMASK=''

When I do a reboot it can't bring the eth0 interface up, because of misconfigured ifcfg-eth0 file.

Some insight would be appreciated.

Thanks

**Comment by gdha** [comment]
added to the release notes so we can close this issue
