### ISSUE TITLE
disk mapping issue after new disk replacement

### ISSUE THREAD

**Issue by zsarosi** [rear/rear#461]
Hi!

I use rear v1.14, but the cause of the problem (mapping script) is the same in v1.16.
Situation:  
disk /dev/sda 34359738368 msdos
disk /dev/sdb 34359738368 msdos

In case of emergency, if disk sda is replaced by a different one (size: 51539607552), the disk mapping script(/usr/share/rear/layout/prepare/default/30_map_disks.sh) generates the following mapping:
This is the disk mapping table:
    /dev/sda /dev/sdb
    /dev/sdb /dev/sdb

Which is clearly a bad idea. Expected would be the keep the mapping for sdb and map sda on the new bigger disk (maybe after asking) or at least quit with an error.

**Comment by gdha** [comment]
Outdated issue
