### ISSUE TITLE
Mounting of NFS share fails at the time of recovering Ubuntu_12.04_x64 VM to physical system

### ISSUE THREAD

**Issue by pramodbiradar89** [rear/rear#463]
Steps:
1.Took backup of VM through rear by using NFS share.
2.created boot-able USB using iso.
3.On physical machine started recovery through rear.
4.on rear shell got error "Message: Mount command 'mount -v -t nfs -o rw,noatime 10.31.199.183:/NFS_DATA /tmp/rear.BTQ14pIsHuKqdsy/outputfs' failed."

5. After making changes in  /usr/share/rear/lib/global-functions.sh it got worked.

**Comment by gdha** [comment]
See also http://pikachu.3ti.be/pipermail/rear-users/2016-February/003290.html for the dhclient issue
