### ISSUE TITLE
LVs with stripes not managed correctly

### ISSUE THREAD

**Issue by iaragones** [rear/rear#466]
I’m installing ReaR into a server using LVs with stripes, as the following exemple:

Server0:/var/lib/rear/layout # lvs -o +devices | grep LVSample1
  LVSample1           VGTemp   -wi-ao  60.00g                                       /dev/mapper/temp_1(0),/dev/mapper/temp_2(0),/dev/mapper/temp_3(0),/dev/mapper/temp_4(0)

I see the layout generated ignores this configuration:

Server0:/var/lib/rear/layout # grep LVSample1 disklayout.conf
lvmvol /dev/VGTemp LVSample1 960 125829120
fs /dev/mapper/VGTemp-LVSample1 /sample1 reiserfs uuid=1d1e43d4-968f-46b9-bb55-ad6b773ae93c label= options=rw,notail,acl,user_xattr
Server0:/var/lib/rear/layout #

Commented at the Mailing List, and it seems to be an missing feature. I'm trying to attach the output of 'rear -vdD savelayout', as D'haese Gratien has suggested.

**Comment by gdha** [comment]
After 3 years still no sponsorship - close for it now
