### ISSUE TITLE
Unable to restore OS - RHEL 5 64 bit

### ISSUE THREAD

**Issue by raju4244** [rear/rear#470]
Hi,

I have successfully backed up RHEL 5 OS vg over the network, when i boot from boot iso i am unable to restore. I got a error saying "mount command failed"

So i tried to mount the nfs manuually but that also didnot work, i got the following error in /var/log/messages.

RPC: failed to contact portmap (errno -5)
locked_up: makesock failed, error=-5
portmap: server localhost not responding, timed out

When i give netstat -ano

i could not find portmap running on the booted image.

**Comment by gdha** [comment]
@raju4244 did you need to start `portmap` manually to get the restore going?

**Comment by gdha** [comment]
is linked with issue #547

**Comment by raju4244** [comment]
Dear gdham

Yes, it worked. but haven't looked your reference. Thanks
