### ISSUE TITLE
Better UI when mapping disks.

### ISSUE THREAD

**Issue by jhoekx** [rear/rear#48]
Reported by Shabahang Elmian on the mailing list.

If disks of source and destination are not same, script switches to manual mode, and asks to  map disk. if there are lots of available disks (special files) , the choices will be a long list and only the last lines can be displayed on screen. Seems that it needs formatting on output(eg. less the output)

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature
