### ISSUE TITLE
Suggestion: Virtualbox driver (+Vagrant provisioning) integration

### ISSUE THREAD

**Issue by Reiner030** [rear/rear#486]
Open issues before patch is ready to migrate:
* ssh connection didn't find in "auto mode" the /root/.ssh/known_hosts and perhaps also the id_rsa file - is it running without "id root" ?
* start of init script /etc/init.d/vboxadd
* mkdir of /vagrant and perhaps additional shared folders if available
* test/check of auto-mounting /vagrant and additional shared folders
* if inclusion of user vagrant with homefolder /home/vagrant is not wanted i can remove it
* if vagrant provision is needed on recover instance we need add sudo functionality

Testing branch for it:
https://github.com/Reiner030/rear/tree/vagrant-integration

Vagrant file with provisioning script and additional files needed:
https://gist.github.com/Reiner030/4b602289320f3c2ed4e7

**Comment by gdha** [comment]
@Reiner030 Do you want to keep this issue open? Or can it be closed?

**Comment by jsmeix** [comment]
No feedback since almost one year
indicate that this issue has become outdated
so that I like to close it now.
If needed it could be reopened but preferably
a new issue based on a current rear version
should be submitted.
