### ISSUE TITLE
Grub2 Install Issue Upon Recovery of CentOS 7 System

### ISSUE THREAD

**Issue by zwilliams360** [rear/rear#492]
I was attempting to recover a CentOS 7 machine to the same machine with different (larger) hard drives.  My general setup is as follows:
* two drives each with 2 partitions:
  * 512 MB partition that held /boot a long time ago - now unused
  * 80 GB partition 
* the 80 GB partitions are pulled into a a RAID 1 software raid array (/dev/md127)
* the /dev/md127 array is defined as an LVM physical volume, and holds a volume group with my root, swap, and any snapshot logical volumes.

rear -V shows: `Relax-and-Recover 1.16.1 / Git`

/etc/rear/local.conf contains the following additions:
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
OUTPUT=USB
I also included the following line in the same file and commented it out in /usr/share/rear/conf/default.conf.  I realize I probably should have just appended the "/data01/" directory here, but I didn't and I don't think it's relevant to any issues I'm having.
BACKUP_PROG_EXCLUDE=( '/tmp/*' '/dev/shm/*' $VAR_DIR/output/\* '/data01/*')

Recovery seems mostly successful, except when I reach the part when it is time to install Grub2:

```
Installing GRUB2 boot loader

WARNING ! For this system
RedHatEnterpriseServer/7 on Linux-i386 (based on Fedora/7/i386)
there is no code to install a boot loader on the recovered system or the code
that we have failed to install the boot loader correctly.

Please contribute this code to the Relax-and-Recover project. To do so
please take a look at the scripts in /usr/share/rear/finalize,
for an example you can use the script for Fedora (and RHEL/CentOS/SL) in
/usr/share/rear/finalize/Linux-i386/20_install_grub.sh

--------------------  ATTENTION ATTENTION ATTENTION -------------------
|                                                                     |
|          IF YOU DO NOT INSTALL A BOOT LOADER MANUALLY,              |
|                                                                     |
|          THEN YOUR SYSTEM WILL N O T BE ABLE TO BOOT !              |
|                                                                     |
-----------------------------------------------------------------------

You can use 'chroot /mnt/local bash --login' to access the recovered system.
Please remember to mount /proc before trying to install a boot loader.
```

I'm curious to know if the cause of this is:
 * there is no code to install a boot loader on the recovered system
or
 * the code that we have failed to install the boot loader correctly

Are there known issues surrounding the ReaR Grub2 install on RedHat/CentOS 7 systems?  I've run into Grub2 installation problems multiple times now using completely different sets of machines.  I've been consistently using the same setup though with similar partitioning, software raid, and LVM.  I've had to manually install Grub2 and it's been a pretty painful procedure each time, so I would love to see if I can get this part automated.  I likely have more information I can provide such as the disklayout.sh, diskrecovery.sh, and logs, but I want to make sure I don't start pasting too much information yet that may not be relevant.

Zach Williams

**Comment by gdha** [comment]
added to the release notes so we can close this issue
