### ISSUE TITLE
SLES12: lsb_release missing in created iso image?

### ISSUE THREAD

**Issue by abbbi** [rear/rear#496]
hi,

trying to recover a SLES12 instance gives me the following while executing rear recover:

RESCUE linux-60x9:~ # rear recover
Relax-and-Recover 1.16.1-git201410271553 / 2014-10-27
Using log file: /var/log/rear/rear-linux-60x9.log
ERROR: The LSB package is not installed.
    Currently there is no support to detect the OS and VERSION without LSB support.
    Please either install the LSB package (that supplies the 'lsb_release' command)
    or improve Relax-and-Recover to handle this situation better.

it seems  the lsb_release package is not included in the generated iso image, it however
exists on the system which created the backup. Grepping the logfile which was created
in debug mode does not give me any hints about lsb_release.

Should lsb_release not be part of the iso image?

**Comment by gdha** [comment]
@abbbi Adding `lsb_release` to the rear ISO image would blow up the size of the ISO image and we do not want that. You already discovered the the `os.conf` was found under `/var/opt/sesam/var/lib/rear/etc/rear`?? and rear itself expects it under `/etc/rear`
Did you know that the `/etc/rear/rescue.conf` file defines the PATH where rear looks for its own internal paths, but it maybe a chicken and egg problem as the SESAM rear fork does not look beneath `/etc/rear`
What can we do about it? SEP Sesam is not very co-operative with us, so I would open a support call with them.
