### ISSUE TITLE
Failed to start udev Kernel Device Manager (rear 1.16.1-git201410241343 )

### ISSUE THREAD

**Issue by tomid** [rear/rear#499]
I try to make a backup of my Arch-Linux-System (Kernek 3.17.1-1) via ISO/NFS and recover it in a vSphere-VM (P2V). The backup runs well and there are no errors in log. When i try to recover the system in virtual machine, i get the error "Failed to start udev Kernel Device Manager" several times, when i boot the ISO Image with "Automatic recover".  Therefore i´ve no ethenet-device and an unreachable network, so REAR cannnot access the Backup-Archiv on NFS. Anyone any idea? I could try to backup on USB, but this is no the solution, i want. My /etc/rear/local.conf:
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://192.168.0.252/volume1/NAS"
OUTPUT_URL="nfs://192.168.0.252/volume1/NAS"
ISO_ISOLINUX_BIN="/usr/lib/syslinux/bios/isolinux.bin"
AUTOEXCLUDE_PATH=/mnt
AUTOEXCLUDE_DISKS=y

**Comment by gdha** [comment]
@tomid I remember a case (P2V situation) where an additional network was required (which was not present in rear image). It was required to add this kernel module in the `/etc/rear/local.conf` as:
````
MODULES=( ${MODULES[@]} my_network_module )
MODULES_LOAD=( ${MODULES_LOAD[@]} my_network_module )
````
when we ran `rear mkbackup`

**Comment by jsmeix** [comment]
No fedback since more than one year => closing it.
