### ISSUE TITLE
run-init: /sbin/init: No such file or directory Kernel panic - not syncing: Attempted to kill init!

### ISSUE THREAD

**Issue by nelteren** [rear/rear#509]
After restoring and rebooting, I get the error:
run-init: /sbin/init: No such file or directory 
Kernel panic - not syncing: Attempted to kill init!

And cannot proceed. 
On the original host /sbin/init is also missing and other debian hosts it is also missing. Booting is no problem then.
What went wrong?

I use I use Relax-and-Recover 1.16 / Git 
Linux s03.net-products.nl 2.6.32-5-amd64 #1 SMP Sat May 5 01:12:59 UTC 2012 x86_64 GNU/Linux

Local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://xxx.xxx.xxx.xxx/rear/s03.net-products.nl/odd

(I have a destination for odd and even days)

os.conf
OS_VENDOR='Debian'
OS_VERSION='4.3.5-4'

**Comment by gdha** [comment]
@nelteren have a look at http://ubuntuforums.org/showthread.php?t=2163328 - might be your problem

**Comment by jsmeix** [comment]
No feedback since more than one year => closing it.
If needed it can be reopened.

**Comment by jeankoffi543** [comment]
First thing to do is:
1- boot your linux distribution on USB or CD
2- live boot your system on the USB or CD key
3- in command line type:  mount /dev/sda1(or your dist partition) /mnt
4- chroot /mnt5- nano /etc/resolv.conf (in this file, put this line: nameserver 8.8.8.8)
6- apt-get install init

after reboot your system. It will work fine. Enjoy

**Comment by gdha** [comment]
@jeankoffi543 So init was not present? Why was it not restored?

**Comment by jeankoffi543** [comment]
@gdha  i don't know why. But i know that init depends of insserv, update can remove insserv. 
There is many problem to this error. Reinstall init would solve this.

**Comment by jsmeix** [comment]
Since ReaR v 2.1 the new default.conf setting
REBUILD_INITRAMFS="yes" 
rebuilds the initramfs/initrd in any case during "rear recover" 
in the recreated system to be on the safe side.
I guess that avoids issues as this one.

**Comment by karnasoneji** [comment]
apt-get install init

Solved the problem.
