### ISSUE TITLE
Excluding files and/or directories from BACKUP=NETFS tar backup

### ISSUE THREAD

**Issue by bbeaver** [rear/rear#510]
What's the trick for excluding files from being picked up by the NETFS tar backup process?  I've tried multiple variations using the EXCLUDE_BACKUP and COPY_AS_IS_EXCLUDE variables within my local.conf.  For example, what would I add to my local.conf if I wanted to exclude the /apps/data01 directory from the tar backup?

Thanks

**Comment by gdha** [comment]
@bbeaver was the above an answer on your question? If yes, could we close this issue?

**Comment by bbeaver** [comment]
Yes - thanks
