### ISSUE TITLE
Using Bareos+rear

### ISSUE THREAD

**Issue by pgporada** [rear/rear#511]
I'm not sure if this is the correct place to write this, but I am having difficulty in configuring the bconsole.conf portion for use with rear.

Do I configure my clients /etc/bareos/bconsole.conf with the same Director and password that the Bareos server uses? If so, I am getting the following message
```
24-Nov 17:02 planetx-dir JobId 0: Fatal error: bsock.c:131 Unable to connect to Client: hale-bopp-fd on 192.168.1.10:9102. ERR=Connection refused
```

How do others configure this?

**Comment by gdha** [comment]
@sebastianlederer Kind reminder for making a pull request with your fix - thanks.

**Comment by sebastianlederer** [comment]
Finally got around testing the fix, found a new bug and fixed that too. Tests are ok now.

**Comment by gdha** [comment]
@sebastianlederer thank you for the fix.
