### ISSUE TITLE
lvcreate hangs because it expects yes prompt to be entered during restore if existing filesystem signature detected.

### ISSUE THREAD

**Issue by bobbysch** [rear/rear#513]
If can eventually fail when doing lvcreate because it could detect an existing filesystem (xfs for ex.) signature :
WARNING: xfs signature detected on /dev/vg0/foobar. Wipe it? [y/n] 
 and wait indefintely for prompting an yes answer.

To fix that, in REAR menu, chose to edit diskrestore.sh and add « yes | lvm lvcreate ... » instead of lvm lvcreate...

Please fix that permanently in your code.

Thanks.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
