### ISSUE TITLE
 Always need to start manually rpcbind and rpc.statd  before able to use rear to restore under RHEL

### ISSUE THREAD

**Issue by bobbysch** [rear/rear#514]
Please could you fix that so NFS can be used to restore automatically without having to start manually rpcbind and rpc.statd processes (like on the live system running RHEL).

**Comment by gdha** [comment]
@bobbysch _This issue made me wonder how to tell rear to recover from a non original source use for backup_ just change the BACKUP_URL variable before doing the recover.
Can this issue be closed?

**Comment by bobbysch** [comment]
Yes you can close it!
Thanks for this wonderful product!

On Tuesday, February 9, 2016, gdha <notifications@github.com> wrote:

> @bobbysch <https://github.com/bobbysch> *This issue made me wonder how to
> tell rear to recover from a non original source use for backup* just
> change the BACKUP_URL variable before doing the recover.
> Can this issue be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rear/rear/issues/514#issuecomment-181870061>.
>


-- 
Antoine Nguyen
