### ISSUE TITLE
How to restore using an alternative location storing the same backup files?

### ISSUE THREAD

**Issue by bobbysch** [rear/rear#516]
For ex, in case disaster strikes, the original location that stores the backup is is not available anymore, how to tell rear to recover from a non original source use for backup (suppose that all the backup files are replicated/copied over).
In my case I used NFS to backup, but since I have issue with NFS4 support by rear, how can tell rear to use the new place and not the original one  after transfering the backup files to a different place?

This is definitively very useful and flexible if rear can do it.

**Comment by gdha** [comment]
@bobbysch was your question answered, or do you need more info?
