### ISSUE TITLE
ReaR never gets to the backup step on systems with large numbers of disks

### ISSUE THREAD

**Issue by bjverzal** [rear/rear#517]
In our GPFS Analytical environment, the ReaR goes through the setup steps but never starts the actual backup because it takes so long to query all of the disk on the system

(root@myserver) /root # wc -l /proc/partitions 
2458 /proc/partitions

**Comment by gdha** [comment]
no the check was not there on purpose as we like to have our multipath config in our layout and what later it will be commented anyway. It is always nice to see what was originally configured on your system (handy in DR mode to see what was on the production system).
However, in rare cases there are just too many devices. I would not modify this script.
Just gonna close this issue.
