### ISSUE TITLE
pre-copy usb host drivers

### ISSUE THREAD

**Issue by tbsky** [rear/rear#519]
hi:
   I found rear will pre copy many kernel drivers, like network and storage drivers. it will help rear recovery on different hardware. maybe we should copy the usb host driver (kernel/drivers/usb/host) too. 

  when I make backup on a machine with only usb2 and restore to another machine with usb3, I found I can not use the keyboard, because the keyboard need xhci_hcd usb3 host driver.  and to my surprise I found on many usb3 machines even the usb2 port is driven by xhci_hcd, not by ehci_hcd. so although the keyboard is plug into usb2 port, it is still useless. and nowadays we don't have ps/2 port on these new machines.  so now I include "xhci_hcd" to my local.conf, but I think maybe rear should make it as default pre-copy modules.

   I don't know if  "23_storage_and_network_modules.sh" is a good place to put usb host driver. or there is some better place to pre copy the usb host dirver, especially the "xhci_hcd" driver.

**Comment by ProBackup-nl** [comment]
@schlomo In case the source is running on an xhci driver only (no ehci module loaded). Then, at least on Arch Linux, only `xhci-pci(.ko.gz)` is copied to the ReaR recovery medium. Next to copying `(uhci|ehci|xhci|ohci)-hcd` modules, could it be wise to also force copy their counterpart `(uhci|ehci|xhci|ohci)hci-pci` modules too?

---
Mkrescue target:
```
/rootfs/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/xhci-pci.ko.gz
/rootfs/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ohci-hcd.ko.gz
/rootfs/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/xhci-hcd.ko.gz
/rootfs/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ehci-hcd.ko.gz
/rootfs/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/uhci-hcd.ko.gz
```
---
Source:
```
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ehci-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ehci-pci.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/hwa-hc.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/isp116x-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/isp1362-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/max3421-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ohci-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/ohci-pci.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/oxu210hp-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/r8a66597-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/sl811-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/sl811_cs.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/u132-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/uhci-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/whci
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/xhci-hcd.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/xhci-pci.ko.gz
/usr/lib/modules/4.9.11-1-ARCH/kernel/drivers/usb/host/whci/whci-hcd.ko.gz
```

**Comment by jsmeix** [comment]
Only as a reference:
In general regarding what kernel modules get included
in the recovery system see also the related issue
https://github.com/rear/rear/issues/1202
