### ISSUE TITLE
Support for thin privisioned LVs

### ISSUE THREAD

**Issue by gha71** [rear/rear#521]
Hi

I am experimenting with RedHat EL 7 and thin provisioned LVs. I noticed that thin provisioned LVs are not supported yet. Is there a plan to add the support in a future release?

I managed to recover the system with some manual intervention:
- do a forced restore of the VG (required to restore thin LVs)
- create a temporary LV for thin Metadata
- restore thin LV metadata in temporary volume 
- swap thin LV Metadata with restored Metadata in temporary LV
- activate VG

**Comment by gdha** [comment]
No plans so far; no further requests received; can only be done when serious spondored (paid)
