### ISSUE TITLE
F22 System Wide Change: Set sshd(8) PermitRootLogin=no

### ISSUE THREAD

**Issue by gdha** [rear/rear#524]
The default of `PermitRootLogin=yes` will change into `PermitRootLogin=no` in Fedora 22:
https://fedoraproject.org/wiki/Changes/SSHD_PermitRootLogin_no

This might have an impact on our rear recovery image with ssh to root

**Comment by schlomo** [comment]
We already enable root login in our code:
```
$ grep -ri permitroot .
./usr/share/rear/build/GNU/Linux/16_adjust_sshd_config.sh:        sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/g' $ROOTFS_DIR/etc/ssh/sshd_config
```

It might indeed be better to only enable root login with key, though.
