### ISSUE TITLE
ppc64: PREP partition creation needed

### ISSUE THREAD

**Issue by jayfurmanek** [rear/rear#526]
Hi,
I was testing REAR on a ppc64 box. It backs up ok, but when restoring, the PREP partition doesn't get created. This partition is used as storage for the bootloader on ppc, so it's necessary.
It looks to be a pretty easy fix, though. Parted supports creating a PREP partition, and the backup part notes the partition type. We just need to check for the "prep" flag in the flaglist in:
      usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh
It's around line 160 or so. Pretty low risk change, too.
I have a system I can test on.

**Comment by gdha** [comment]
@jayfurmanek will you prepare a pull request for this?

**Comment by jayfurmanek** [comment]
I can, yes.

**Comment by jayfurmanek** [comment]
Pull request created. I'll likely be creating a few more for ppc64 as I ran into a few other issues. This particular issue is fixed with the change in the pull request.
