### ISSUE TITLE
Issue with Rear Restore/Restore with TSM .

### ISSUE THREAD

**Issue by bibssun** [rear/rear#528]
Able to take an OS backup with rear/TSM . When trying to recover there are two issues we have discovered .

1) If we do an Automatic restore , it  restores OS + NON-OS related OS .

2) If we select Manual Restore , we are able to restore OS image and OS based file systems only , but it it does not create directories/mountpoints for other NON-OS based filesystems.

**Comment by gdha** [comment]
To be able to give some support on this issue I need script debug log sessions (option -D) with *manual recover*. E.g. `rear -v -D recover`

To debug the *auto recover* you probably need to edit the file `./usr/share/rear/skel/default/etc/scripts/system-setup` and add `-D` after the line `rear recover -v` (on the production system and remake the ISO image to have this active).

**Comment by kvanopdorp** [comment]
I have a somewhat simple fix for both of these issues that I will commit and submit a pull request for.

**Comment by kvanopdorp** [comment]
As you can see, I created a pull request with my modification. There might be a better way to determine included and excluded filesystems from the rescue image but that is what seemed most logical to me. I tested it on RHEL6 and TSM version 6. I don't think there would be any OS specific catches but that is what I had available to test.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
