### ISSUE TITLE
Error restoring boot from SAN system

### ISSUE THREAD

**Issue by captaw3some** [rear/rear#529]
We are testing a rear restore on systems utilizing a multipath/ boot from SAN configuration. Currently we are getting the error "No code has been generated to restore device pv:/dev/mapper/mpatha2 (lvmdev). 

I have read through issue #228 but trying the troubleshooting items listed did not help. Looking at disklayout.conf I see that /dev/mapper/mpatha2 listed. I have uploaded debug logs to gist.

https://gist.github.com/04bf300a760b451e1816

**Comment by gdha** [comment]
I could not find the `diskrestore.sh` script. Would have been useful to see that one as well.

**Comment by captaw3some** [comment]
![screen shot 2015-01-20 at 11 11 53 am](https://cloud.githubusercontent.com/assets/8322655/5821919/38361e20-a095-11e4-85ef-a7a1a027a024.png)
Here is the diskrestore.sh (screenshot).

**Comment by gdha** [comment]
@captaw3some what you could do to get you further is to manual edit the `disklayout.conf` file and un-comment the following lines (for mpatha):
````
disk /dev/sda 21626880000 msdos
#disk /dev/sdb 21626880000 msdos
#disk /dev/sdc 5898240 unknown
disk /dev/sdd 21626880000 msdos
#disk /dev/sde 21626880000 msdos
#disk /dev/sdf 5898240 unknown
disk /dev/sdg 21626880000 msdos
#disk /dev/sdh 21626880000 msdos
#disk /dev/sdi 5898240 unknown
disk /dev/sdj 21626880000 msdos
#disk /dev/sdk 21626880000 msdos
#disk /dev/sdl 5898240 unknown
#disk /dev/sdm 0
multipath /dev/mapper/mpatha /dev/sda,/dev/sdd,/dev/sdg,/dev/sdj
````
Not sure that will be sufficient - you might consider to add the variable `BOOT_OVER_SAN=y` to the `local.conf` file (see script `./prep/GNU/Linux/24_include_multipath_tools.sh`).
Furthermore, making a bootable SAN disk is not yet automated within rear (so hoping you could help here).

**Comment by multipathmaster** [comment]
gdha, read my document that I have just posted in this issues section, it covers how to do this with multipath/boot from san, while taking advantage of LVM2 (i.e. vg/lvols etc...).  I just did another test where I scrapped /boot, /etc, /var and /tmp   and I was able to recover using REAR via my document.

**Comment by gdha** [comment]
See issue #572 - we can close this one
