### ISSUE TITLE
rear git201501071534 "rear recover" on Fedora 21: hangs at rpc.statd

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#532]
I am testing rear git201501071534 version on Fedora 21:

I boot the rear recovery system which works but see
https://github.com/rear/rear/issues/531

In the the recovery system I run

rear -d -D recover

which hangs with the last message

Using log file: /var/log/rear/rear-f42.log

<pre>
RESCUE f42:~ # tail /var/log/rear/rear-f42.log 
++ ((  0 != 0  ))
++ max_portmap_checks=5
++ rpcinfo -p localhost
++ has_binary rpc.statd
++ for bin in '$@'
++ type rpc.statd
++ return 0
++ grep -q status
++ rpcinfo -p localhost
++ rpc.statd
RESCUE f42:~ #
</pre>

Somehow rpc.statd does not work.

I aborted "rear -d -D recover" (simply [Ctrl]+[C]).

The following dirty hack seems to "fix" it for me:

ln -sf /bin/true /bin/rpc.statd

Afterwards I re-started "rear -d -D recover"
which successfully recovers the system.

**Comment by jsmeix** [comment]
<pre>
RESCUE f42:~ # grep -v '^#' /etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.20.30.40/nfs/rearBackups
NETFS_KEEP_OLD_BACKUP_COPY=yes
BACKUP_PROG_INCLUDE=( '/home/*' )
SSH_ROOT_PASSWORD="XXXX"
USE_DHCLIENT="yes"
RESCUE f42:~ #
</pre>

**Comment by gdha** [comment]
@jsmeix In my test environment I have no problems with `rpc.statd` daemon:
![image](https://cloud.githubusercontent.com/assets/888633/5975751/3c6612f0-a885-11e4-9846-162809bef20a.png)

In `top` output it is not showing (`systemd` and `systemd-journal` are consuming a lot - issue #531).
Perhaps, the NFS-server is type NFSv4? Could be related to a certain version? Just guessing.

**Comment by gdha** [comment]
@jsmeix can this one being closed or do you still have some comments to share?

**Comment by jsmeix** [comment]
@gdha 
I cannot remember whether or not I verified that it works for me with the released rear 1.17.0 on Fedora 21.
I think when it works for you, you can close it.
Furthermore I assume if it would not work there would have been same reports from other Fedora 21 users.
