### ISSUE TITLE
Add various INCLUDE_* options to limit Relax-and-Recover's scope

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#54]
Much like we currently allow the following configuration directives:

```bash
# Exclude components from being backed up, recreation information is active
EXCLUDE_BACKUP=()

# Exclude components during component recreation
# will be added to EXCLUDE_BACKUP (it is not backed up)
# recreation information gathered, but commented out
EXCLUDE_RECREATE=()
 
# Exclude components during the backup restore phase
# Only used to exclude files from the restore.
EXCLUDE_RESTORE=()
```

We would like to have ```INCLUDE_BACKUP```, ```INCLUDE_RECREATE``` and ```INCLUDE_RESTORE```. This enables users to specify a limited number of components to backup, recreate or restore.

The ```INCLUDE_*``` and ```EXCLUDE_*``` options could be mutual exclusive, or could be ordered somehow (up to the developer to see what is possible and how it is implemented).

**Comment by gdha** [comment]
have no time to work on this request...
