### ISSUE TITLE
Make component-prefix mandatory in layout code

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#55]
Currently the ```EXCLUDE_*``` variables only require a component-prefix in those cases where it is ambiguous. By requiring all components to be prefixed, we remove the inconsistency from the syntax.So instead of ```/dev/vg_data```, it would become ```vg:vg_data```

Example:

```bash
EXCLUDE_BACKUP=( "fs:/data" )
EXCLUDE_RECREATE=( "vg:vg_san" )
EXCLUDE_RESTORE=( "fs:/tmp" )
```

PS This affects #54

**Comment by gdha** [comment]
@dagwieers @jhoekx Do you still see the need of this request, or can we close it?

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature
