### ISSUE TITLE
Re: General rear backup/recovery questions

### ISSUE THREAD

**Issue by msoupramanien** [rear/rear#553]
Hi,

Couple of questions:

1) If we have to restore image of server "host1" onto server "host2", assuming that both are Virtual Machines. Have you seen any issues.
2) If we have to restore the ISO image of a physical server on a Virtual Machine or vice-versa, is it possible.

Regards,

**Comment by schlomo** [comment]
1) Yes
2) Yes

Please note that there is no "image" to restore. ReaR can create a tar or rsync backup for you and restore that if you don't want to use or don't have anything else.

**Comment by msoupramanien** [comment]
Thank you. Will test it out.

Regards,
