### ISSUE TITLE
Implement support for recovery when what is mounted at '/' is a btrfs snapshot subvolume

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#556]
Currently my code that supports btrfs in rear explicitly excludes support for btrfs snapshot subvolumes. The main reason for this is described in the "btrfs" secion at https://en.opensuse.org/SDB:Disaster_Recovery

Currently SUSE Linux Enterprise 12 is installed by default in a way so that what is mounted at '/' is a "normal" btrfs subvolume (the "/@" subvolume).

For the upcoming first service pack for SUSE Linux Enterprise 12 (i.e. SLE12-SP1) it is currently planned to install it by default in a way so that what is mounted at '/' is a btrfs snapshot subvolume (something like "/.snapshots/1/snapshot").

Therefore I need to enhance my code that supports btrfs for recovery when what is mounted at '/' is a btrfs snapshot subvolume.

This does not mean that I will implement support for any kind of btrfs snapshot subvolumes.

It only means I will enhance my current code so that recovery of all mounted btrfs subvolumes works regardless if there is a normal subvolume mounted or if there is a snapshot subvolume mounted.

In other words: It will be still unsupported to restore all data in all existing btrfs snapshot subvolumes. Only mounted btrfs snapshot subvolumes will become supported.

Background information:

The reason behind the change to install it by default in a way so that what is mounted at '/' is a btrfs snapshot subvolume is the following:

The snapshot subvolumes in "/.snapshots" are controlled by snapper (a tool for filesystem snapshot management, see http://snapper.io). 

This change ensures that always what is mounted at '/' is controlled by snapper (i.e. both after booting from a snapshot and also from the very beginning after the initial installation).

This way there is no longer a special difference after the system was booted from a snapshot compared to when the system was booted as it was setup during the initial installation.

In the end this change will ensure that the system works the same even after it was booted from a snapshot.

**Comment by gdha** [comment]
@jsmeix I assume this is a placeholder - I've put the milestone to 1.18 if that is Ok for you

**Comment by jsmeix** [comment]
Yes, it is meant for a future rear release after 1.17 and I will implement it.

**Comment by gdha** [comment]
@jsmeix are you OK with it I grant you the rights inside our master tree?

**Comment by jsmeix** [comment]
I do very much apreciate your offer but currently I am not a good-enough Git/GitHub user to be sure that I may not accidentally mess up your things.

At least for now - I prefer to learn how to make proper GitHub pull requests and after I got a somewhat experienced Git/GitHub user I might even become rights for your master tree.

In particular for this feature I will have to work separated from rear master with whatever changing beta versions of SLE12-SP1 and do some trial and error work until I learned how to deal correctly with it and then I can actually implement it for rear master - just as I did for the generic btrfs support ( you should be really happy that rear master never got my dirty-hack stuff that only works on SLE12-GA ;-).

For me it is topmost important not to cause regressions in rear master like https://github.com/rear/rear/issues/555 that is a really unfortunate side-effect of my change from "mount" to "findmnt".

**Comment by schlomo** [comment]
@jsmeix I agree with @gdha and salute your modesty. I'll be happy to give your pull requests and issues a high priority and assist in any way which you need.

**Comment by jsmeix** [comment]
Likely not yet for rear 1,18 (to be released about June 2015) but for rear 1.19 (to be released about Dec. 2015).

**Comment by jsmeix** [comment]
FYI some very first information:

I did some reverse-engineering how our installer does the default btrfs setup for SLE12-SP1.

Up to now I found out (by inspecting SLE12-SP1 beta3 installation on a KVM virtual machine) that snapper is now needed (specifically /usr/lib/snapper/installation-helper) in the installation system (inst-sys for our installer and the rear recovery system for rear).

Currently I cannot estimate how long it may take to integrate snapper into the rear recovery system.

Furthermore rear needs support for "chattr" (currently there is none in rear):

Because for SLE12-SP1 some btrfs subvolume directories (/var/lib/pgsql /var/lib/libvirt/images /var/lib/mariadb) have the "no copy on write (C)" file attribute set (via "chattr +C /path/to/directory") chattr support is needed in rear.

**Comment by jsmeix** [comment]
FYI:

For me the first basic step works (on a KVM/qemu virtual machine) that is:

Recovery of a SLES12-SP1 system with default btrfs structure (but currently without chattr support).

I made my current SLE12-SP1 specific implementation public available in the openSUSE Build Service development project "Archiving" package "rear" at

https://build.opensuse.org/package/show/Archiving/rear

**Comment by gdha** [comment]
@jsmeix any plans to integrate the patch *SLE12-SP1-btrfs.patch* (https://build.opensuse.org/package/view_file/Archiving/rear/SLE12-SP1-btrfs.patch?expand=1) into the upstream track?

**Comment by jsmeix** [comment]
@gdha
yes, but see "Reasoning and background information" in
https://github.com/rear/rear/issues/666#issue-110397975

**Comment by jsmeix** [comment]
I enhanced my SLE12-SP1-btrfs.patch so that now
on my test system it works for me to recreate
the SLE12-SP1 default btrfs structure
plus
for mounted btrfs subvolumes that have the 'no copy on write'
attribute set those btrfs subvolumes are recreated with that
attribute set (by using 'chattr' on the btrfs subvolume directory).

From my current point of view the issue is hereby fixed
specifically for SUSE.

@gdha 
please have a look at my SLE12-SP1-btrfs.patch in OBS project "Archiving" package "rear" at https://build.opensuse.org/package/show/Archiving/rear

I tried to implememt is so that it should be backward compatible
(i.e. I think my new stuff should not cause a regression)
but to be really safe this would require testing.

@gdha 
if you think it would be o.k. to have my current SUSE-specific
implementation in rear upstream I can of course make a
GitHub pull request.

**Comment by gdha** [comment]
@jsmeix looks ok to me - just prepare a pull request.
Furthermore, concerning the example config files - perhaps we can add these under `conf/examples/` ? What do you think?

**Comment by jsmeix** [comment]
O.k. - for next week - I like to do a few more tests.

Have a nice weekend!

**Comment by jsmeix** [comment]
The issue should be fixed with my above commit https://github.com/rear/rear/commit/307b98c1281c58619d59cb9e6f41863b9278122b

@gdha 
is my above commit o.k. for you?

**Comment by jsmeix** [comment]
I used it many times on my SLES12-SP1 test system
and for me it "just works" so that from my point of view
I can close this issue.

**Comment by jsmeix** [comment]
It seems that changing btrfs default setup never ends,
see https://github.com/rear/rear/issues/944
regarding what they changed from SLE12 SP1 to SP2.

**Comment by vishualways** [comment]
Hi, We are facing similar issue while recovering SLES 12 SP1 (Rear 1.19) with default btrfs for systemvg. We can backup and create image fine however during recovering it gives errors. Could you please help us in overcoming this issue and it has became a kind of show-stopper atm. Is there a workaround/patch/update to get it working on SLES12 SP1? I have contacted SLES support and they said they only support REAR on SLES for SAP version and not the normal SLES.
I am not well-verse with github so please excuse my non-awareness regarding posts. Your help/advice would be much appreciated.
Thanks and regards,
Vish

[rear-ulvwasaw01.txt](https://github.com/rear/rear/files/624689/rear-ulvwasaw01.txt)

We also tried solution given in one of the thread - https://github.com/rear/rear/issues/1036 - we used snapper to get around it however it still failed as in attached rear-sles12-test.log

**Comment by gozora** [comment]
Hi,

> as in attached rear-sles12-test.log

Attached where?

> we used snapper to get around it 

did you run `rear mkrescue` and booted from newly created ReaR rescue system?

What is size of your _/dev/mapper/system-lvroot_ ?

**Comment by jsmeix** [comment]
@gozora 
don't waste your time with that.

@vishualways 
cf. https://github.com/rear/rear/issues/1095
