### ISSUE TITLE
Confirming ReaR backup completed successfully  - check return codes or syslog output

### ISSUE THREAD

**Issue by bbeaver** [rear/rear#563]
Is there a simple way to confirm a "rear -v mkbackup" ran to completion without errors, when scripted to run automatically using cron?  For example, if the "rear -v mkbackup" command is placed within a shell wrapper, is it sufficient to check the return value, (echo $?), immediately after the script finishes?  We'll be running nightly with cron, and I would like to script such that I receive an email only if there are problems, or, a syslog event is triggered in the event of a problem.  Thanks

**Comment by schlomo** [comment]
Simply run `read mkbackup`. It will remain silent unless there is something to say. The return code should indicate success or failure.

**Comment by bbeaver** [comment]
Run "read mkbackup"?  Do you mean, "rear mkbackup", without the "-v" verbose option?  And when "rear mkbackup" completes, check the return value, (echo $?), for success status?  Assume return of zero is success and non-zero means there were problems, correct?  Thanks

**Comment by jsmeix** [comment]
@bbeaver 

What exactly do you mean with
"confirm a 'rear -v mkbackup' ran to completion without errors"?

E.g. to confirm that the backup of the files is complete without errors one would have to restore it to another place and the inspect if the restored stuff is complete without errors.

E.g. to confirm that the generated rear recovery system is complete without errors one would have to boot and run it on another machine and let it do its job there which means one would have to do a real "rear recover" and after that verify that the rercovered system is complete without errors.

Or do you only mean that no program/script that was run by 'rear -v mkbackup' resulted a non-zero exit code?

**Comment by gdha** [comment]
Since rear-1.16.x rear writes a return code message via syslogd to `var/log/messages`, e.g.
`Mar 10 10:22:20 <my_hostname> rear[20947]: DONE: rc=0`

**Comment by bbeaver** [comment]
Perfect - that's what I was looking for.  Will syslog also be written with any problems?  What local.conf variables need to be setup to support writing syslog events?  Thanks

**Comment by schlomo** [comment]
ATM the only thing that is logged to syslog are errors and a warning /
success result codes.

I think that it would be not difficult to add support for logging
everything to syslog instead of our own log file.

**Comment by bbeaver** [comment]
Leaving details in the ReaR log file is fine.  The objective here is to be notified if there are any issues with a regularly scheduled nightly run of "rear -v mkbackup".  Sysadmins will need to receive an email, or a syslog event if there are problems, and once this is received they can look at the ReaR log file details as to what failed.  Thinking something like this below:

rear -v mkbackup
rc=$?
if [ -z "${rc}" ]
then
send an email, or logger to syslog
fi

**Comment by gdha** [comment]
if you grep the syslog with the keyword *rear* you would find all issues if any or it went fine *DONE: rc=0*

**Comment by gdha** [comment]
This issue is related to the discussion held in #564

**Comment by gdha** [comment]
@bbeaver Doe you need some more info or are you good? Otherwise, close the issue.
thanks.
