### ISSUE TITLE
No code has been generated to retore device pv:/dev/mapper/sda2 (lvmdev) SLES 10

### ISSUE THREAD

**Issue by microchipmatt** [rear/rear#567]
When I try to restore a SLES10 SP3 OES2SP2 Linux install from the the rear rescue iso, I get the error:
No code has been generated to retore device pv:/dev/mapper/sda2 (lvmdev)
Here is the output of disklayout.conf:

http://pastebin.com/A9jCjFiT

**Comment by microchipmatt** [comment]
Here is the output of disklayout.conf:
#disk /dev/hdc 4294965248
#disk /dev/sda 128849018880 msdos
#part /dev/sda 73995264 32256 primary boot /dev/sda1
#part /dev/sda 16096872960 74027520 primary lvm /dev/sda2
#part /dev/sda 112678110720 16170900480 primary none /dev/sda3
lvmdev /dev/system /dev/mapper/sda2 U2Mr44-ftw1-O4P1-dt4i-nbKW-MSOu-vc2vX1 31439205
lvmgrp /dev/system 4096 3837 15716352
lvmvol /dev/system root 2560 20971520
lvmvol /dev/system swap 512 4194304
# Filesystems (only ext2,ext3,ext4,vfat,xfs,reiserfs,btrfs are supported).
# Format: fs <device> <mountpoint> <fstype> [uuid=<uuid>] [label=<label>] [<attributes>]
fs /dev/evms/lvm2/system/root / reiserfs uuid=9f58d7b1-61e8-4410-aa94-125bdf915601 label= options=rw,acl,user_xattr
fs /dev/evms/sda1 /boot ext2 uuid=3d460bae-61a1-4440-abf1-401682e5d6b0 label= blocksize=1024 reserved_blocks=5% max_mounts=33 check_interval=180d bytes_per_inode=4094 options=rw,acl,user_xattr
swap /dev/evms/lvm2/system/swap uuid= label=

**Comment by gdha** [comment]
@microchipmatt  I noticed that you are using evms (`fs /dev/evms/lvm2/system/root / reiserfs`) which to my knowledge is *not* supported by rear. Personally, I never worked wit evms so I'm not much of help in this particular case.

**Comment by microchipmatt** [comment]
That was my fear...was that it wasn't supported....I am struggling to find a decent way to protect my olde oes2 servers running on SUSE 10 with EVMS/LVM containers...it was the illd management system for linux and NSS before NLVM.

**Comment by schlomo** [comment]
OES2? Long time no see...

I basically can imagine the following options:
* [Convert EVMS to LVM](http://evms.sourceforge.net/user_guide/#evmstocomp)
* Contribute code to ReaR to support EVMS (IMHO not worth the effort as EVMS is a dead project)
* Use a different backup method for your system, for example based on Imaging.
* If this is a VM, backup the VM on the hypervisor level.
* ...

HTH,
Schlomo

**Comment by gdha** [comment]
Need to add to the documentation that EVMS is not supported.
