### ISSUE TITLE
ISO_FILES are no longer considered in /etc/rear/local.conf

### ISSUE THREAD

**Issue by domibarton** [rear/rear#569]
Hi

There were some commits a while ago https://github.com/rear/rear/commit/41efc97eb7141c30455df45a871b98cd08e09fa7 to add UEFI integreation support to mkbackup / mkrescue. You've changed several scripts which make use of the `ISO_FILES` variable, basically by replacing the extension of the `ISO_FILES` variable to multiple `cp` commands.

Finally the creation of the ISO image was replaced by using the current directory (which contains all the copied files) instead of the `ISO_FILES` variable:

```bash
    -R -J -volid "$ISO_VOLID" $EFIBOOT -v -iso-level 3 .  >&8
    ##-R -J -volid "$ISO_VOLID" $EFIBOOT  "${ISO_FILES[@]}"  >&8
```
The problem is, that users will still have some ISO_FILES defined in `/etc/rear/local.conf` (for example inclexcl files for the dsmc client) and `rear dump` will still report them.

I think we need to add / copy the files & directories from ISO_FILES to the tmp directory for the ISO creation as well. Do you agree?

Cheers
Domi

**Comment by gdha** [comment]
@domibarton Thank - are you only missing files you added to the array ISO_FILES manually in local.conf?

**Comment by domibarton** [comment]
@gdha yeah exactly!
