### ISSUE TITLE
Fix indentation in all scripts

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#57]
We decided ages ago to have indentation use 4 spaces. Currently the indentation is a mix of various personal styles.

During the reorganization we could do a re-indentation as well. By doing this together we avoid introducing errors or merge-conflicts with other changes. We probably also want to change other Bash constructs as we discussed (using [[ ]] and (( )), use of LogIfError/BugIfError, etc.)

**Comment by gdha** [comment]
We know and are trying to deal with it - gonna close this issue
