### ISSUE TITLE
An error occured during layout recreation

### ISSUE THREAD

**Issue by chelikani** [rear/rear#576]
Hi ,

I am trying to recover Rhel 6.2 on System x3850 X5 / x3950 X5 . But i am getting the error "An error occured during layout recreation" . I did checked the logs it is not complaining about any insufficient space  . Infact i am testing same server back up and recovery .

![screenshot](https://cloud.githubusercontent.com/assets/12000884/7212262/38e8516c-e532-11e4-85c8-3c337992fdb7.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/12000884/7212263/38e85f7c-e532-11e4-864e-22855a36db2e.png)
![screenshot](https://cloud.githubusercontent.com/assets/12000884/7212269/4757ccfa-e532-11e4-934f-5dd8a54456ee.png)

**Comment by gdha** [comment]
Could you copy/paste the `/var/lib/rear/layout/disklayout.conf` and I suspect that rear (for some unknown reason so far) cannot handle one of the options of the `/mnt/local/boot/efi` mount options...
You could try to mount it manually after the error just to be sure that the file system creation was successful?

**Comment by chelikani** [comment]
![image](https://cloud.githubusercontent.com/assets/12000884/7233030/d395e79e-e74c-11e4-82bd-5422cd187354.png)

![image](https://cloud.githubusercontent.com/assets/12000884/7233049/f9f2a814-e74c-11e4-91e5-6ff401a8568c.png)

![image](https://cloud.githubusercontent.com/assets/12000884/7233067/0fc6dd0e-e74d-11e4-9e73-e3a65e112f9f.png)

**Comment by gdha** [comment]
@chelikani Are you able to mount the `/mnt/local/boot/efi` by hand in recovery mode? We have to be sure that the `mkfs.vfat` was successful. Try it without any special options like `mount  /dev/sda1  /mnt/local/boot/efi`

**Comment by chelikani** [comment]
it mounted only with this command , mount /dev/sda1 /mnt/local/boot/efi

**Comment by gdha** [comment]
added in the release notes for 1.17.1

**Comment by pcahyna** [comment]
As mentioned in #2777 , `cp437` is not a valid value for `codepage=`, `437` is.
```
# mount -o codepage=cp437 /dev/vdb /mnt
mount: wrong fs type, bad option, bad superblock on /dev/vdb,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so
# dmesg | tail
FAT: Unrecognized mount option "codepage=cp437" or missing value
# mount -t vfat -o codepage=437 /dev/vdb /mnt
```
The problem was, Linux reported `codepage=cp437` among mount options, that's why it got into ReaR's disklayout.conf and was used on mount. Linux does not accept it then despite reporting it.

```
# cat /proc/mounts
(...)
/dev/vdb /mnt vfat rw,relatime,fmask=0022,dmask=0022,codepage=cp437,iocharset=ascii,shortname=mixed,errors=remount-ro 0 0
```

This was on RHEL 6, the problem is fixed in RHEL 7 and later:

```
# cat /proc/mounts
(...)
/dev/vdb /mnt/fat vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro 0 0
```
