### ISSUE TITLE
IRC Chat

### ISSUE THREAD

**Issue by RedBrick36** [rear/rear#577]
Please forgive me.
I am so sorry for leaving this message here, but I couldn't find any other resources....

Is there an IRC channel where users and developers of Relax-and-Recover go to assist each other?

My situation is that I am on Fedora 21 Workstation and I can run both the format and mkrescue without errors on both an external Toshiba 1TB USB 3.0 drive and a PNY 8GB thumbdrive. But for some reason neither of them will boot. It's probably related to my laptop (a Gigabyte P35) but I would like to talk to others about it... Maybe someone has a similar situation...

Again, I apologize for putting this question  here.
I really hope that there is a IRC channel somewhere...

Roger Baran
San Antonio, TX

**Comment by gdha** [comment]
There exists an IRC channel #rear however I don't find the time anymore to follow it actively. Need to work to earn some money;
