### ISSUE TITLE
ERROR: BUG BUG BUG!  Filesystem for device '/dev/sdc1' could not be found

### ISSUE THREAD

**Issue by fdelelis** [rear/rear#579]
Hi,

I am using rear to backup phisical machines and when use usb destination (layout image) and nfs to share the backup data, the process abort:
````
[root@srv-ln-ono ~]# rear -v mkbackup
Relax-and-Recover 1.17.0 / Git
Using log file: /var/log/rear/rear-srv-ln-ono.log
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
ERROR: BUG BUG BUG!  Filesystem for device '/dev/sdc1' could not be found
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-srv-ln-ono.log

HINT: If you can reproduce the issue, try using the -d or -D option !
====================
Aborting due to an error, check /var/log/rear/rear-srv-ln-ono.log for details
Terminated
````

In the log:
````
====================
=== Stack trace ===
Trace 0: /usr/sbin/rear:251 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:24 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:70 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:31 Source
Trace 4: /usr/share/rear/output/USB/Linux-i386/85_make_USB_bootable.sh:40 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:144 BugError
Message: BUG BUG BUG!  Filesystem for device '/dev/sdc1' could not be found
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-srv-ln-ono.log

HINT: If you can reproduce the issue, try using the -d or -D option !
````

How can solve the problem?

Thanks

**Comment by gdha** [comment]
Did you format the USB disk? See http://relax-and-recover.org/documentation/

**Comment by fdelelis** [comment]
Hi,
I format de usb disk with rear format. Do you have any idea?

Thanks

**Comment by gdha** [comment]
How did you format the USB disk? With which file system?

**Comment by fdelelis** [comment]
Hi,

I format the usb with the comand rear, #rear format /dev/sdc. When the
comand ask the format type I select ext3.

Thanks

2015-04-27 9:51 GMT+02:00 gdha <notifications@github.com>:

**Comment by gdha** [comment]
How did you define the USB device in the `/etc/rear/local.conf` file? In the documentation we mentioned the following:
`BACKUP_URL=usb:///dev/disk/by-label/REAR-000`
And, when you boot from the rescue image did the linux kernel recognized the USB device? Use the `dmesg` command to find out..

**Comment by fdelelis** [comment]
Hi,

I used the same parameter. I can't boot from the rescue image because I
ca't make the backup:

rear -v mkbackup.

Thanks

2015-04-27 11:09 GMT+02:00 gdha <notifications@github.com>:

**Comment by gdha** [comment]
What is the content of `/etc/rear/local.conf` or `/etc/rear/site.conf` ?

**Comment by fdelelis** [comment]
Hi,

The content of /etc/rear/local.conf is:

*OUTPUT=USB*

*USB_DEVICE="/dev/disk/by-label/REAR-000"*

*BACKUP=NETFS*

*BACKUP_URL= “nfs://192.168.62.204/nfs/rear/
<http://192.168.62.204/nfs/rear/>”*


*Thanks.*

2015-04-27 16:07 GMT+02:00 gdha <notifications@github.com>:

**Comment by gdha** [comment]
@fdelelis Could you try to replace `USB_DEVICE="/dev/disk/by-label/REAR-000`
with `OUTPUT_URL=usb:///dev/disk/by-label/REAR-000` ?

**Comment by gdha** [comment]
@fdelelis any feedback?

**Comment by fdelelis** [comment]
Sorry,

Thank you by the atention. I couldn't probe this configuration. Could
reopen the case in the future?

Thanks.

2015-05-31 16:51 GMT+02:00 gdha <notifications@github.com>:

**Comment by thepulze** [comment]
Could confirm problem reported by fdelelis.
I am using Relax-and-Recover 1.17.2 to backup a CentOS 7.1.1503 machine.

Using OUTPUT_URL instead of USB_DEVICE works.

Here my site.conf:

OUTPUT=USB
OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
#USB_DEVICE=/dev/disk/by-label/REAR-000
BACKUP=NETFS
BACKUP_URL=file:///mnt/backup
BACKUP_PROG=rsync

**Comment by gdha** [comment]
@thepulze @fdelelis I just tested it out myself and it works fine for me:
````
# ls /mnt/backup/rear/centos7-kvm/20151030.1011/
initrd.cgz  kernel  rear.log  syslinux.cfg


# ls /mnt/backup/centos7-kvm/
backup  backup.log  README  rear.log  selinux.autorelabel  VERSION

# cat /etc/rear/site.conf
OUTPUT=USB
OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
#USB_DEVICE=/dev/disk/by-label/REAR-000
BACKUP=NETFS
BACKUP_URL=file:///mnt/backup
BACKUP_PROG=rsync
````

**Comment by thepulze** [comment]
Yes, this config works for me too. But it does not work if you use USB_DEVICE  ___instead___ of OUTPUT_URL, meaning that the following config produces the error:

OUTPUT=USB
#OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
USB_DEVICE=/dev/disk/by-label/REAR-000
BACKUP=NETFS
BACKUP_URL=file:///mnt/backup
BACKUP_PROG=rsync

**Comment by gdha** [comment]
Thank you for mentioning this - need to check it myself.

**Comment by gdha** [comment]
@fdelelis @thepulze You were right - it was a bug - has been fixed - thanks it took a while to understand the issue...
