### ISSUE TITLE
Question on Relax-and-Recover...

### ISSUE THREAD

**Issue by itskk** [rear/rear#582]
I would like to use Relax-and-Recover to restore onto a new Linux server. The hardware configuration is different to the first server. I don't have the new Linux server yet but would like to invest in one. Before I do this, I would like to know if the bare-metal recovery is independent of hardware.

**Comment by gdha** [comment]
You need to know the new HW a bit. Be aware migration from x32 to x64 might give issues, or even from x86 to ppc or arm = no go.
Drivers that might be different  need to be added manually to the array MODULES.
For the rest it should be possible, perhaps some tweaks are still required after re-imaging.

**Comment by gdha** [comment]
@itskk Any feedback to share?
