### ISSUE TITLE
elilo Support on SLES11

### ISSUE THREAD

**Issue by ssievers** [rear/rear#583]
On SLES11 with elilo bootloader and EFI a mkrescue stops with the following error:
````
2015-04-29 16:13:08 Including output/default/94_grub_rescue.sh
2015-04-29 16:13:08 $grub_conf is set to:
/boot/efi/efi/SuSE/grub.conf <=== this is my debug output
2015-04-29 16:13:08 ERROR: GRUB configuration cannot be modified.
=== Stack trace ===
Trace 0: /var/lib/rear/usr/sbin/rear:249 main
Trace 1: /var/lib/rear/usr/share/rear/lib/mkrescue-workflow.sh:41
WORKFLOW_mkrescue
Trace 2: /var/lib/rear/usr/share/rear/lib/framework-functions.sh:79
SourceStage
Trace 3: /var/lib/rear/usr/share/rear/lib/framework-functions.sh:40 Source
Trace 4:
/var/lib/rear/usr/share/rear/output/default/94_grub_rescue.sh:54
source
Trace 5:
/var/lib/rear/usr/share/rear/lib/_input-output-functions.sh:131
StopIfError
Message: GRUB configuration cannot be modified.
````

Rear correctly sets $UEFI_BOOTLOADER to `/boot/efi/efi/SuSE/elilo.efi`
but later rear dies on the error grub.conf doesnt exit. 
There is no script to handle elilo yet.

**Comment by gdha** [comment]
Where lives your elilo config file?

**Comment by ssievers** [comment]
sles11:/boot/efi/efi/SuSE # ls -la
total 11636
drwxrwxr-x 2 root root    4096 Dec 13  2013 .
drwxrwxr-x 3 root root    4096 Dec 13  2013 ..
-rwxrwxr-x 1 root root    1215 Dec 13  2013 elilo.conf
-rwxrwxr-x 1 root root  247267 Aug 22  2013 elilo.efi
-rwxrwxr-x 1 root root      76 Dec 13  2013 elilo.list
-rwxrwxr-x 1 root root 7703233 Dec 13  2013 initrd-3.0.101-0.8-default
-rwxrwxr-x 1 root root 3942720 Nov  7  2013 vmlinuz-3.0.101-0.8-default

**Comment by gdha** [comment]
@ssievers If you could check with the updated lib/uefi-functions.sh script whether your problems goes away with it?

**Comment by ssievers** [comment]
Hi,

I am sorry, but noting changed here after editing the lib/uefi-functions.sh

Regards,

Soeren

**Comment by gdha** [comment]
@ssievers ok, it might be fixed in `output/default/94_grub_rescue.sh`. Would be nice if you could test it out. Keep in mind that after the recovery `elilo` still needs to be run - a pull request would be wonderful!

**Comment by gdha** [comment]
I'll move the milestone as elilo support is in rear-1.17.1, however, it was not yet fully tested

**Comment by gdha** [comment]
We were able to successfully restore with elilo on an UEFI system (using ebiso to create a bootable uefi iso image)
