### ISSUE TITLE
Rear Recover on UEFI system

### ISSUE THREAD

**Issue by pomusa** [rear/rear#585]
Hello,

I was able to run a ReaR mkbackup and recompiled the mkisofs for UEFI. I am running this on a brand new HP DL360 G9 server and running SLES 11 SP3. 

My local.conf

OUTPUT=ISO
BACKUP=NETFS
NETFS_URL=cifs://server/nfs/
NETFS_OPTIONS="cred=/etc/rear/.cifs"
EXCLUDE_VG=('/dev/vgoracle' '/dev/vgsap00' '/dev/vgsap01' )
UEFI_BOOTLOADER=/boot/efi/efi/SuSE/elilo.efi
ISO_ISOLINUX_BIN="/usr/share/syslinux/isolinux.bin"

TEST 1 - Standard UEFI boot
 i tried booting up the cdrom which i burned from the iso image and it just error out and stating that it couldn't find the config in the /EFI/BOOT. i looked there is a BOOTX64.conf in the iso image and it contained "default=0
timeout 5
splashimage=/EFI/BOOT/splash.xpm.gz
title Relax and Recover (no Secure Boot)
    kernel /isolinux/kernel
    initrd /isolinux/initrd.cgz"

however, i don't see splash.xpm.gz in the path /EFI/BOOT.

TEST 2 - OLD BIOS MODE
The HP Bios allows me to boot up in the OLD BIOS mode, i was able to boot the CD and i was able to get the ReaR Recover menu. i was able to go through the process on restoring the OS from backup. However, i tried rebooting after running rear recover, i just got a message that there is no operating installed.

If you can guide me the right direction, it would be much appreciated.

Thanks 

Boon

**Comment by gdha** [comment]
Is related with #583 - currently UEFI booting with SLES11/OpenSuse is a bit of a pain.
1. EFI ISO booting is not supported by mkisofs executable delivered with standard OS
2. elilo is not yet supported (working on it)

**Comment by pomusa** [comment]
I tried Parted Magic and it allows me to boot up in UEFI mode and i am hoping that it would be some help on booting up in the elilo mode.

![partedmagic](https://cloud.githubusercontent.com/assets/12265936/7600686/48e75254-f8c2-11e4-9e6b-5b34dfbe514c.png)

**Comment by gdha** [comment]
@pomusa please give 78a6f9f  a try.. that will detect the correct bootloader. Feedback is welcome.

**Comment by pomusa** [comment]
Instead of using mkisofs, Would it be possible to make a usb flash drive UEFI bootable?

**Comment by gdha** [comment]
@pomusa Have a look at http://www.it3.be/2015/10/27/uefi-iso-boot-with-ebiso/ to make a bootable ISO image on UEFI systems. It does work as I already used it for SLES11 SP3/SAP HANA systems.

**Comment by gdha** [comment]
@pomusa can this issue be closed?
