### ISSUE TITLE
Recovery process. Error. telinit: Did not receive a reply

### ISSUE THREAD

**Issue by sohmstyle** [rear/rear#590]
OS - CentOS 6.6 x86_x64
Hardware - ESXi 5.1 on HP Proliant DL160 G6
REAR 1.17

10.11.0.150 --- Bareos Server (testbackup-bareos)
10.11.0.151 --- Bareos Client (testbackup-client-01)(There is bareos-fd)

This ip addresses are static and this hosts have only one network interface - eth0.

[root@testbackup-client-01 ~]# uname -r
2.6.32-504.16.2.el6.x86_64

Going to 10.11.0.151 (Bareos Client) and backup it:

yum -y install nfs-utils genisoimage syslinux rear
mkdir /etc/rear/mappings
echo "eth0 10.11.0.151/24" > /etc/rear/mappings/ip_addresses
echo "default 10.11.0.1 eth0" > /etc/rear/mappings/route
vi /etc/rear/local.conf
############################
There is config. Link - 
http://pastebin.com/b3Hn1awQ
############################

Comparing to the default rear local.conf file I edit only lines:
BACKUP=BAREOS
OUTPUT=ISO
BAREOS_CLIENT=testbackup-client-01-fd
OUTPUT_URL=nfs://10.11.0.150/backup
USE_STATIC_NETWORKING=y

vi /etc/bareos/bconsole.conf

Director {
  Name = testbackup-bareos-dir
  DIRport = 9101
  address = 10.11.0.150
  Password = "1FlpWEdFUIgbewhedsGGHJgbedsf""
}

This is ok. bconsole work.

Then begin backup process:

[root@testbackup-client-01 ~]# rear -v -d -D mkrescue
Relax-and-Recover 1.17.0 / Git
Using log file: /var/log/rear/rear-testbackup-client-01.log
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-testbackup-client-01.iso (27M)
Copying resulting files to nfs location

[root@testbackup-client-01 ~]# rear -v dump
http://pastebin.com/xmEPSjQC

/usr/share/rear/lib/validated/RedHatEnterpriseServer/6/i386.txt
Your system is validated with the following details:
Relax and Recover Version 1.13.0 / $Date$
Validation:     RedHatEnterpriseServer/6/i386
Submitted:      tdec0909@yahoo.com, Marcel Keil <marcelk@tim.de>
Date:           2013-05-21, 2014-03-18
Features:       LVM, VMware guest, ISO, NETFS, NSR
Comment:

Size of rear-testbackup-client-01.iso is 34191360 bytes

Log file:
/var/log/rear/rear-testbackup-client-01.log --- 

https://drive.google.com/open?id=0B7jcjwezrniKTmo1b2s2NDl1VUU&authuser=0

When I boot from rear-testbackup-client-01.iso and choose Recovery testbackup-client-01 then I've got a error:
![screen error](https://cloud.githubusercontent.com/assets/12595731/7797447/e3b1e416-02f4-11e5-9a44-7a992ecb7e32.png)

telinit: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
init: rcS post-stop process (47) terminated with status 1

I don't know how to fix it.

Thanks

**Comment by gdha** [comment]
@sohmstyle According a RH Knowledge Article:
**
Check for the existence of `/etc/passwd`
Check for the existence of `/etc/nsswitch.conf` and check the content
If `/etc/passwd` does not exists, replace it from backup as described in the resolution above
**
It sounds not very applicable, but you never know...
Could you also reduce the `/etc/rear/local/conf` file to the bare minimum?
````
BACKUP=BAREOS
OUTPUT=ISO
BAREOS_CLIENT=testbackup-client-01-fd
OUTPUT_URL=nfs://10.11.0.150/backup
USE_STATIC_NETWORKING=y
````
And try again?

**Comment by sohmstyle** [comment]
>Could you also reduce the /etc/rear/local.conf file to the bare minimum?
I don't know how, but it helped!

Thanks! You can close issue.

And then I encountered a problem with "Error The LSB package is not installed."
There is same problems https://github.com/rear/rear/issues/496, https://github.com/rear/rear/issues/468, https://github.com/rear/rear/issues/326
I tried the solution of those posts, but they did not help.
I hope it will be possible to solve the problem with LSB package.
