### ISSUE TITLE
format-workflow.sh does not honor the option arguments 

### ISSUE THREAD

**Issue by gdha** [rear/rear#593]
In the `format-workflow.sh` script:
````
    # Parse options
    OPTS="$(getopt -n "$PROGRAM format" -o "fhy" -l "force,help,yes" -- "$@")"
````
These options are not honored as the `rear` main script interprets the options first and these are *unknown*. So, this piece of code was not well tested at creation time.

**Comment by gdha** [comment]
Not a bug, but lack of documentation of how to use it:
Use `rear -v format -- --help /dev/<usb-device>`

Came across this when I was looking into making the USB disk EFI bootable

**Comment by schlomo** [comment]
Maybe we can simplify the usage?

rear format dev=/dev/sdb
rear format /dev/sdb
... ?

**Comment by jsmeix** [comment]
For completeness:
Issue https://github.com/rear/rear/issues/603 is the one about
"making the USB disk EFI bootable" that is mentioned above.
