### ISSUE TITLE
failed to restore backup iso for Xen VM

### ISSUE THREAD

**Issue by kelwoo** [rear/rear#595]
Hi All,

I could seccessfully created ISO backup of VM in XEN and send to NFS repos. but when I try to restore the VM.

I encountered some problem and failed to restore VM eventaully,

1. When I tried to create a new VM (for restoration), If I select VM type as "CentOS / RHEL", I cannot startup the newly created ISO that for restoration

2. When I tried to create a new VM and select "other" type, I could restore the VM but failed to boot the recovered VM

The ISO backup and recover works perfectly under VMware

it said that there is problem in disk xvdsk/dsk convertion. I could not find any troubleshoot info from google or here. Is it only encountered by me? Anyone can help?

**Comment by schlomo** [comment]
When choosing "CentOS/RHEL" as the VM type you probably configured a paravirtualized VM (PVM) which to the best of my knowledge cannot boot an ISO.

Do you have a screenshot? The recovery log?

**Comment by abbbi** [comment]
Hi,

yes, if you create a VM with the template for the operating systems in use, they are allways Paravirtualized. I dont know wether if it is possible to boot a ISO image which already includes
a XEN PV kernel. We have asked the citrix guys about this but not yet got any answer:

http://discussions.citrix.com/topic/365604-how-to-boot-a-paravirtualized-kernel-off-an-cdrom-image/

I think it *might* work if you convert the ISO Image to a Virtual Disk, and then set the PV-Kernel
and PV-Bootloader options accordingly. Other than that i think the only solution is to boot the
kernel from the network.

One existing workaround is to install a regular kernel within the virtual machine besides the xen
kernel and start rear mkrescue with the -r option, passing the kernel verison which is not a xen
PV kernel.

Then you can at least boot the iso image with the "other install media" option which is a HVM
virtual machine. After recovery the Virtual machine has to be converted to PV again.

**Comment by jsmeix** [comment]
No further comments since more than two years
indicate that this issue has become outdated
so that I like to close it now.

If needed it could be reopened but preferably
file a new issue based on a current rear version.

In general regarding XEN and paravirtualization
you may have a look at the section about
"Virtual machines" in
https://en.opensuse.org/SDB:Disaster_Recovery
