### ISSUE TITLE
debian jessie: generated iso image is missing systemd files, fails to bringup udevd/networking

### ISSUE THREAD

**Issue by abbbi** [rear/rear#599]
hi,

it seems that on debian jessie some systemd realted files have been moved from /usr/lib/systemd to /lib/systemd, as such the files are not included (or some rear related startup files refer to /usr/lib/systemd)

you will note this as it fails to bringup the udevd service and the network during bootup of the 
recovery cdrom.

As a whacky workaround i have copied the files from /lib/systemd to /usr/lib/systemd on my testsystem 
to confirm that it correctly boots up if the files are included, and it does.

Bootup with those missing systemd files will look like:

[    5.840191] systemd[1]: Failed to load configuration for local-fs.target: No such file or directory
[    5.846160] systemd[1]: Failed to load configuration for plymouth-quit-wait.service: No such file or directory
[    5.846170] systemd[1]: Failed to load configuration for systemd-user-sessions.service: No such file or directory
[    5.846824] systemd[1]: Failed to load configuration for network.target: No such file or directory
[    5.916522] systemd[51]: Failed at step EXEC spawning /usr/lib/systemd/systemd-journald: No such file or directory
[    5.924280] systemd[48]: Failed at step EXEC spawning /usr/lib/systemd/systemd-udevd: No such file or directory
[    5.928407] systemd[58]: Failed at step EXEC spawning /usr/lib/systemd/systemd-journald: No such file or directory
[    5.950314] systemd[66]: Failed at step EXEC spawning /usr/lib/systemd/systemd-journald: No such file or directory
[    5.955368] systemd[65]: Failed at step EXEC spawning /usr/lib/systemd/systemd-udevd: No such file or directory
[    5.984561] systemd[74]: Failed at step EXEC spawning /usr/lib/systemd/systemd-udevd: No such file or directory
[    5.988237] systemd[76]: Failed at step EXEC spawning /usr/lib/systemd/systemd-journald: No such file or directory
[    5.999016] systemd[78]: Failed at step EXEC spawning /usr/lib/systemd/systemd-udevd: No such file or directory
[    6.001153] systemd[79]: Failed at step EXEC spawning /usr/lib/systemd/systemd-journald: No such file or directory
[    6.022310] systemd[82]: Failed at step EXEC spawning /usr/lib/systemd/systemd-udevd: No such file or directory
[    9.008749] systemd[1]: Failed to load configuration for local-fs.target: No such file or directory
[    9.010524] systemd[1]: Failed to load configuration for plymouth-quit-wait.service: No such file or directory
[    9.010533] systemd[1]: Failed to load configuration for systemd-user-sessions.service: No such file or directory
[    9.011022] systemd[1]: Failed to load configuration for network.target: No such file or directory

**Comment by gdha** [comment]
made a symbolic link from `buidl/SUSE_LINUX/61_link_systemd_lib.sh` to `build/Debian/61_link_systemd_lib.sh` which should fix it mormally.

**Comment by gdha** [comment]
On  my test systemd failed to start udev Kernel Device Manager - still needs investigation. As a result the ethernet interface is not recognized....

**Comment by abbbi** [comment]
See my pull request. I think the SUSE Workaround will not work on debian as it only symlinks the systemd/system directory but on debian the scripts are referenced one directory above.
