### ISSUE TITLE
debian jessie: prep/default/50_guess_bootloader.sh fails silently if strings is not installed

### ISSUE THREAD

**Issue by abbbi** [rear/rear#600]
hi,
on my newly installed debian jessie system binutils is not within the standard installation for a ssh server only. As such strings is missing from the system. If so, you will not the following error message during mkrescue:

2015-06-12 12:16:10 Including prep/default/50_guess_bootloader.sh
/var/opt/sesam/var/lib/rear/usr/share/rear/prep/default/50_guess_bootloader.sh: line 15: strings: command not found

its the section where it tries to write the bootloader information. May not be critical but i think
it would be better to really fail out with a proper error message if the script is missing an
executable?

**Comment by gdha** [comment]
@abbbi should bail out from the start now...
