### ISSUE TITLE
rear restore from one physical server to another

### ISSUE THREAD

**Issue by msoupramanien** [rear/rear#606]
Hi,

I took a rear backup of a physical server running RHEL5.4. I have to recover it on a different physical server with different hostname and IP. Could you please let me know how to do it.

Thanks and Regards,

**Comment by schlomo** [comment]
Did you try to recover the replacement server? It should "just work" :-)

After the recovery, before rebooting, you will have to go to /mnt/local and adjust the hostname and IP address in the configuration files.

**Comment by msoupramanien** [comment]
Hi Schlomo,

Thanks for your comments. I will update the hostname and IP in the configuration files as mentioned before rebooting.

Regards,
