### ISSUE TITLE
VM to physical server Rear Restore Failing

### ISSUE THREAD

**Issue by abhishekmittal02** [rear/rear#615]
Hi Guys,

I am trying to create a clone of a VM by taking rear and extracting the ISO to install a Physical HP G9 Blade.
Booting is not getting started with the ISO.

Thanks
Abhishek Mittal

**Comment by schlomo** [comment]
Hi Mittal,

this is a supported use case, the requirements are that the Linux kernel
and OS of your VM would work on the hardware. If that is *not* the case
(e.g. kernel too old, kernel is virtualization kernel that only works on
VMs ...) then ReaR cannot do anything.

If it is not that then please provide screenshots and/or logs from your
failed boot attempt.

Regards,
Schlomo

**Comment by gdha** [comment]
The problem IMO is Gen9 uses UEFI to boot and the ISO image created on your VM was **not** UEFI aware, therefore, the ISO cannot boot on the physical Gen9. Try to boot in legacy mode, but still that won't help as you should create a partition for the EFI and the rest for the OS. Above all, it should be a GPT partitioned disk, etc. As you see it is very difficult without the UEFI tools on the rear rescue image ISO. There is a lot of manual work to do.
Try cloning from an UEFI VM to Gen9

**Comment by rbeldin** [comment]
Gen9's have the capability of either being in UEFI or legacy BIOS mode.
Try setting legacy bios mode and try your restore.

I still think the chances of this working are slim.  Your VM may not
have the right drivers to talk to the devices that are native on the
real hw.  For example, if you were using virtual box para-virtualized
drivers for network and storage, you probably wouldn't have hpsa and
whatever nic drivers the gen9 needs for native access.

V2P and P2V are much more than just save and restore.  There is 'magic'
that goes on behind the scenes to make that process work.

-- 
Rick Beldin

**Comment by gdha** [comment]
@abhishekmittal02 did answer your question? Or, do you have any other concern?

**Comment by gdha** [comment]
no reply - so close it
