### ISSUE TITLE
Rear recovering failing on OracleLinux 6

### ISSUE THREAD

**Issue by rscott101** [rear/rear#618]
I'm testing Rear on OracleLinux 6 (a fully compatible respin of RHEL6), using Bareos as the backup device.

Restore image built successfully and was used to boot, partition, and restore the machine.

However, it failed installing grub - it appeared to be trying to install into /boot/grub ,not /mnt/local/boot/grub. The error was:-

Installing GRUB boot loader
ERROR: Could not find directory /boot/grub 

Any suggestions/ideas for a solution to this please?

**Comment by rscott101** [comment]
Been checking further, and it appears nothing in /boot/grub had been restored? I've checked the backups and the files are present in there.

**Comment by schlomo** [comment]
If Bareos did not restore all the files into /mnt/local then it won't work.
Maybe there is a bug in the Bareos restore part?

**Comment by rscott101** [comment]
Apologies for this... It was entirely user error..
