### ISSUE TITLE
Rear hangs upon restore for RHEL 7 for failure to mount /run

### ISSUE THREAD

**Issue by bibssun** [rear/rear#619]
For RHEL 7 Server - rear  restore appears to complete , but once the Server is rebooted -  The Server hangs with the message "Failed to mount /run . No such file or directory."

**Comment by bibssun** [comment]
The version of rear used is rear ver 1.17.

**Comment by bibssun** [comment]
Also the method of recovery used is Rear Recovery with TSM .

**Comment by gdha** [comment]
@bibssun could you check within TSM if /run was back-up'ed? Also, when you are still in recovery mode you could inspect the file systems under /mnt/local whether all required mount points are present.
You could verify the `/var/lib/rear/layout/disklayout.conf` file to see if /run was a separate mount point?

**Comment by gdha** [comment]
On my centos7 system I have the following tmpfs file systems:
````
tmpfs                          12229932       92  12229840   1% /dev/shm
tmpfs                          12229932     9276  12220656   1% /run
tmpfs                          12229932        0  12229932   0% /sys/fs/cgroup
````
These are temporary file systems and are not tracked in the disklayout.conf file.

The problem with TSM is that variable `MOUNTPOINTS_TO_RESTORE` gets defined in script `verify/TSM/default/40_verify_tsm.sh` and afterwards as the variable is not empty in script `restore/default/90_create_missing_directories.sh` it will skip the creation of some critical mount points which are *not* backup'ed by TSM such as `proc sys tmp dev/pts dev/shm`.
Furthermore, I noticed that **sys** is missing in this list too.
Therefore, this is a bug, that needs to be fixed

**Comment by gdha** [comment]
I think we need to do this in a more generic way and also restore the moint points with correct ownership and permissions. Therefore, we should make a *new* script in the prep work-flow and save the output for later and use it in the restore work-flow as input.

**Comment by gdha** [comment]
A good starting point for the script could be:
`$ ls -ld $(mount | grep -vE '(cgroup|fuse|nfs|/sys/)' | awk '{print $3}')` to get the list of mount points where we need to save the permissions and ownership

**Comment by gdha** [comment]
read some interesting comments from Schlomo in http://pikachu.3ti.be/pipermail/rear-users/2015-August/003138.html

**Comment by gdha** [comment]
@bibssun feel free to test out the new script committed.
