### ISSUE TITLE
ERROR: Cannot find required programs: loadkeys kbd_mode dumpkeys

### ISSUE THREAD

**Issue by firsttris** [rear/rear#620]
root@tvserv:/home# dpkg -i rear_1.17.0_all.deb
(Lese Datenbank ... 85599 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Ersetzen von rear 1.17.0 (durch rear_1.17.0_all.deb) ...
Ersatz für rear wird entpackt ...
rear (1.17.0) wird eingerichtet ...
Trigger für man-db werden verarbeitet ...
root@tvserv:/home# apt-get install -f
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
root@tvserv:/home# rear
ERROR: Cannot find required programs: loadkeys kbd_mode dumpkeys
Aborting due to an error, check /var/log/rear/rear-tvserv.log for details
Beendet

Debain 7 (openmediavault)

what am I doing wrong?

Regards
firsttris

**Comment by gdha** [comment]
@firsttris the message `ERROR: Cannot find required programs: loadkeys kbd_mode dumpkeys` means these are required programs which must be present before rear can run successfully. Please install these with debian tools

**Comment by firsttris** [comment]
can you tell me which package i need to install? where do i find these debian tools?

**Comment by firsttris** [comment]
apt-get install kbd

did the trick
