### ISSUE TITLE
restore a single file?

### ISSUE THREAD

**Issue by firsttris** [rear/rear#621]
hello, 
is it possible to restore a single file from an iso by extracting or mounting?

regards
firsttris

**Comment by gdha** [comment]
Does the ISO contains the archive as well or only the boot image? It depends of course. Do you use an external backup program?

**Comment by firsttris** [comment]
ISO contains only the backup/archive no boot image. No external Backup program

**Comment by gdha** [comment]
@firsttris could you show the `/etc/rear/local.conf` file as I have no clue where you boot from?

**Comment by firsttris** [comment]
sorry i explain in more detail:

OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=file:///media/4abdc695-ec9c-4fcf-ad8e-442c63dbc626/backup/img/
BACKUP_URL=file:///media/4abdc695-ec9c-4fcf-ad8e-442c63dbc626/backup/img/

if i run 

rear mkbackuponly    
(backup system without creating rescue media)

i get: 
backup.tar.gz

doc says:
OUTPUT=ISO
Create a bootable ISO9660 image on disk as rear-$(hostname).iso

why do i get a .tar.gz?

from my understanding i have now created a image which contains my system drive. 
usually if you get a iso file you can easily mount it if you do something like:
mount ISOFILE MOUNT-POINT -o loop
Is it now possible to mount or to unzip this --> backup.tar.gz "iso" while my system is running? 
Is there a easy/quick way to access a file in this iso/container/image?

in partclone, clonezilla this was possible..

is my understand about the iso wrong?

the reason:

i currently have 2 backups for my system drive..disaster recovery with rear and full rsync of my system drive (in case a file is lost or destroyed).

regards & thx for your help

**Comment by gdha** [comment]
what kind of device is `BACKUP_URL=file:///media/4abdc695-ec9c-4fcf-ad8e-442c63dbc626/backup/img/`?
* mkbackonly will not create an ISO image to boot from
* mkrescue only creates an ISO image and no tar archive
* mkbackup does both

**Comment by gdha** [comment]
@firsttris was your question answered? Or, do you need more feedback from us?

**Comment by firsttris** [comment]
yes!

thanks for your reply!

regards
firsttris
