### ISSUE TITLE
Backup to USB Flash Drive and Archive to External USB drive

### ISSUE THREAD

**Issue by pomusa** [rear/rear#622]
is there a way to split the backup for USB where i would like the ReaR bootable image to store on a flash stick and the archive image on another external USB drive. The reason is that 8GB USB flash drive cannot hold both boot image and archive image on the same stick.

thanks

Boon

**Comment by pomusa** [comment]
i noticed that UEFI booting from an USB is not supported. Is there a workaround to make it UEFI booting?

**Comment by gdha** [comment]
* OUTPUT=USB (do not forget to format the usb device) - not sure you can split it; however, I never tried it so perhaps it does work if you define another BACKUP_URL=usb:///dev/<device>
* UEFI and usb: see issue #603 - started with the preps, but it is not finished (vacation and lack of time)

**Comment by pomusa** [comment]
hello.. what is the difference between...
USB_DEVICE="/dev/sdb1"  and BACKUP_URL=usb:///dev/sdb1?

**Comment by pomusa** [comment]
tried with 2 entries of BACKUP_URL

BACKUP_URL=usb:///dev/sdc1
BACKUP_URL=usb:///dev/sdd1

it would just use /dev/sdd1 as default and not use sdc1

**Comment by gdha** [comment]
when you define OUTPUT=USB then you need to define USB_DEVICE also. This will set OUTPUT_URL and BACKUP_URL to the same location of the USB_DEVICE setting. As I said before this piece of code was written by @dagwieers and @jhoekx  so I think they could answer this much better then myself.

**Comment by gdha** [comment]
@pomusa what you need to do is:
* rear format /dev/sdc
* use /dev/sdd as a mounted linux file system (ext3 for example) - e.g. /mnt/usbdisk
* define in `/etc/rear/local.conf`:
````
  OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
  BACKUP_URL=file:///mnt/usbdisk
````
* rear -v mkbackup
  this should produce a bootable USB disk on device /dev/sdc and the tar archive on /dev/sdd.
* in recover mode you need first mount /dev/sdd on /mnt/usbdisk before starting `rear -v recover`

**Comment by jsmeix** [comment]
Closing because it is "fixed".
