### ISSUE TITLE
Missing binaries for hpssacli in recovery image

### ISSUE THREAD

**Issue by hpannenb** [rear/rear#630]
Hi, everyone.

I am rather new to ReaR and try to set it up under RHEL 6.4 on a HP server. Additionally I installed the hpssacli 2.20-11.0 of HP and discovered its binaries/the installation directory is not included in the rescue image.

Debugging the Relax-and-Recover Version 1.17.1-git201507281845 / 2015-07-28 shows what happens within the https://github.com/rear/rear/blob/master/usr/share/rear/layout/save/GNU/Linux/27_hpraid_layout.sh script,

Extract of the log executing `rear -dDv mkrescue`:
```
[...]
++++ get_path hpssacli
++++ type -p hpssacli
+++ grep ON_DIR= /usr/sbin/hpssacli
++ eval HPSSACLI_BIN_INSTALLATION_DIR=/opt/hp/hpssacli/bld/
+++ HPSSACLI_BIN_INSTALLATION_DIR=/opt/hp/hpssacli/bld/
++ COPY_AS_IS=("${COPY_AS_IS[@]}" "$HPACUCLI_BIN_INSTALLATION_DIR")
+++ get_version hpssacli version
+++ TERM=dumb
[...]
```

Looking at a previous hpacucli installation shows the variable
`HPPACUCLI_BIN_INSTALLATION_DIR=/opt/compaq/hpacucli/bld/`
whereas the "new" hpssacli tool includes the variable
`HPSSACLI_BIN_INSTALLATION_DIR=/opt/hp/hpssacli/bld/`

P.S.: A current workaround for me is to include a line
`COPY_AS_IS=( ${COPY_AS_IS[@]} /opt/hp/hpssacli/ )`
in the `site.conf`.

Questions? Welcome.

Regards,
Holger.

**Comment by gdha** [comment]
@hpannenb Before you modified the site.conf file (COPY_AS_IS) what did you exactly miss? The executable or the directory? Or both? I've check on a older version (HP Array Configuration Utility CLI 9.30.15.0) and all seemed fine?
Would like to know for sure what was missing...

**Comment by hpannenb** [comment]
Hello, Gratien. With the `hpssacli` tool installed everything under `/opt/hp/hpssacli/bld/` is missing.

**Comment by gdha** [comment]
@hpannenb just fixed the 27_hpraid_layout.sh script

**Comment by hpannenb** [comment]
@gdha I retested it and it works. I/You can close the issue. Many thanks.
