### ISSUE TITLE
Support for DL380G8 shipped with P830i array controllers

### ISSUE THREAD

**Issue by kushns** [rear/rear#632]
Hi All,

We have few DL380G8 server shipped with P830i array controllers cards, looks P830i array controllers are not yet supported by REAR.

Just want to confirm if fix/patch/update for the 800 series controller is imminent.

Regards

Kush

**Comment by gdha** [comment]
@kushns did you run into troubles with rear? If yes, could you share what went wrong?

**Comment by kushns** [comment]
830i card  isn't recognized by the the ReaR software.

**Comment by kushns** [comment]
Using rear for P2P migration from ProLiant DL580 G7 to DL380G8. So took rear image from DL580 G7 server and trying to restore it to DL380G8.

Rear is not recognizing 830i card on DL380G8.

**Comment by schlomo** [comment]
Which OS is installed on your DL580G7? Did you install any HP drivers?

If you install exactly the same on the DL380G8, does it recognize your 830i card? If yes, then we talk about a ReaR bug. If not, then your source OS is the "problem". The fix would be to install the required drivers there and then do the P2P migration.

**Comment by kushns** [comment]
Red Hat Enterprise Linux Server release 5.5 is OS for DL580G7.  HP PSP tool is already installed on server.

looks its not recognising 830i card on DL380G8.

**Comment by schlomo** [comment]
If HP does not support 830i for RHEL 5.5 then ReaR cannot do anything about it. If yes, then ReaR should pick up the drivers. If ReaR does not pick up the drivers then please provide more details here (e.g. debug mode log file).

**Comment by kushns** [comment]
Thanks for update....

I will check if RHEL5.5 support 830i card and get back to you...

**Comment by kushns** [comment]
Looks I need to check if kmod-cciss package is install on server or not. 

https://rhn.redhat.com/errata/RHEA-2013-1130.html

I have raised case with redhat as well......so I will do some testing tomorrow and share the findings...

Thanks.....

Kush

**Comment by kushns** [comment]
Hi,

I apologies for delay update.....

There is a cciss driver available which can be used to resolve the issue but minimum requirement for cciss driver is RHEL 5.7 so unfortunately will not work on RHEL5.5.

It worked for RHEL 5.9 after installing cciss drivers.

We are working with Vender to get the P830i card replaced with P420i cards.

According to RHEL DL580 G8 is certified for RHEL5.9 onwards only . 

Thanks for help......

Thanks

Kush

**Comment by schlomo** [comment]
Thanks for the info. If you need futher assistance please re-open this issue.
