### ISSUE TITLE
Unable to boot VM after a P2V

### ISSUE THREAD

**Issue by ravis1** [rear/rear#635]
Hi 
I have a P2V to be done of RHEL5.6 32 bit to Vmware .We have used REAR to do P2V and restore works but after restore when we try to boot of disk it just shows a blank screen on the VM console .

Alternately if we try to boot back of the rear recovery iso and select first boot device as hd0 it can boot of to the restored image on the VM .

Can you if possible guide us what we are missing or how to get it booted of just the disk without the use of recovery iso attach

Thanks 

Kush

**Comment by gdha** [comment]
Hum, this means that grub setup went fine. Can you repeat the error without first booting from the ISO image?

**Comment by ravis1** [comment]
I tried booting of the hard drive and it wont even reach the grub stage i get a blank screen and thats baffling me why .

**Comment by schlomo** [comment]
​Can you post the configuration of the VM? E.g. the VMX file (you can stip
all private data).​

**Comment by ravis1** [comment]
I am waiting from my vmware team to come online before i can get that data .But for now when i boot of iso and look at partition table 

Of Physical server

Disk /dev/cciss/c0d0: 146.7 GB, 146778685440 bytes
255 heads, 32 sectors/track, 35132 cylinders
Units = cylinders of 8160 * 512 = 4177920 bytes

           Device Boot      Start         End      Blocks   Id  System
/dev/cciss/c0d0p1   *           1         251     1024064   83  Linux
/dev/cciss/c0d0p2             252         765     2097120   82  Linux swap / Solaris
/dev/cciss/c0d0p3             766        2238     6009840   83  Linux
/dev/cciss/c0d0p4            2239       35132   134207520    5  Extended
/dev/cciss/c0d0p5            2239        2981     3031424   83  Linux
/dev/cciss/c0d0p6            2982        3474     2011424   83  Linux
/dev/cciss/c0d0p7            3475        3967     2011424   82  Linux swap / Solaris
/dev/cciss/c0d0p8            3968        4460     2011424   83  Linux
/dev/cciss/c0d0p9            4461        4953     2011424   83  Linux
/dev/cciss/c0d0p10           4954       35132   123130304   83  Linux

For The VM attaching image 
![partiotion screenshot](https://cloud.githubusercontent.com/assets/13679129/9250034/a84a1f60-41e7-11e5-8682-f0bd6ce8213f.png)

if you look at partition 4 it shows a windows label and also the partition table dosent match .Can that be an issue 

Thanks

**Comment by schlomo** [comment]
Partition 4 is an extended partition (
https://en.wikipedia.org/wiki/Extended_boot_record), looks normal to me.

**Comment by ravis1** [comment]
I was able to fix it by booting of iso and then boot of first disk and doing a grub install .Post that when i reboot of harddisk OS loads .

Thanks 

ravi

**Comment by gdha** [comment]
@ravis1 do you still no support for this?

**Comment by ravis1** [comment]
Hi 
No issue resolved thanks for your help 

Thanks

**Comment by ravis1** [comment]
Issuer resolved
