### ISSUE TITLE
Add iscsi support

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#64]
As reported on the mailinglist, iscsi can be supported already by using:

```bash
COPY_AS_IS=( "${COPY_AS_IS[@]}" /var/lib/iscsi /etc/iscsi )
PROGS=( "${PROGS[@]}" iscsiadm iscsid )
LIBS=( "${LIBS[@]}" libaio* )
```

You will also have to edit */etc/iscsi/iscsid.conf* to change the path to iscsid once you boot the rescue system.

But we would like to include iscsi automatically when used.

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature
