### ISSUE TITLE
rsync restore: --anchored invalid rsync option

### ISSUE THREAD

**Issue by lrirwin** [rear/rear#642]
I encountered an issue when trying to restore due to the entry of BACKUP_PROG_OPTIONS="--anchored" in conf/default.conf.
rsync does not have an option "--anchored", so the restore fails, grub-install fails, etc.
The backup works... so it must not be picked up during "rear mkbackup" - only during the restore operation. 
Setting BACKUP_PROG_OPTIONS="" in /usr/share/rear/conf/default.conf
fixes the problem and a complete backup and restore works.
I'm not sure how to parameterize the option...
It appears to have been a fix, but not for the configuration below:

Environment:
Dell Inc. PowerEdge T320 BIOS 2.4.2 01/29/2015
PERC w/HW RAID 5 - SAS drives using LVM2
Internal SATA RD1000 Backup - Auto-mount disabled using dconf editor
Ubuntu 14.04.3 LTS
Linux ccasvr 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24
21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Standard install of rear using Gdebi package installer (with
modification mentioned above) and the following /etc/rear/site.conf:
OUTPUT=USB
BACKUP=NETFS
BACKUP_PROG=rsync
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

**Comment by gdha** [comment]
By default we see (with dump)
````
BACKUP_RSYNC_OPTIONS = --sparse --archive --hard-links --verbose --numeric-ids --stats
BACKUP_PROG = rsync
BACKUP_PROG_OPTIONS = --anchored
````
The `BACKUP_PROG_OPTIONS` option should not be used with rsync - it is meant for tar. We will remove this option in the restore script.
Be aware that `BACKUP_RSYNC_OPTIONS` is an array to remove e.g. the verbose define in the `site.conf`:
````
BACKUP_RSYNC_OPTIONS=(--sparse --archive --hard-links --numeric-ids --stats)
````
Well, we will change this in the `default.conf`  so that the `-v` option with rear itself is honored with rsync and it is not forced by default - make more sense to me

**Comment by gdha** [comment]
commit 02af81d57dd5f5650afcb7c0ec314592ef17e10d and 0168c2adcff7b1f0490f901c88b9d53f1d3af46a to fix the rsync backup/restore issue
please test it out when convenient.

**Comment by gdha** [comment]
@lrirwin If you want you can test it out as I think it should be fixed in the meantime
