### ISSUE TITLE
rear backup that makes one ISO?

### ISSUE THREAD

**Issue by multipathmaster** [rear/rear#646]
Hello, MultipathMaster here,

We have a certain set of systems within our environment that have a horrible network connection (a t-1), which is only 1.5 megabit a second, and so we were wondering if there was a way to actually have rear (when mkbackup or mkrescue is issued) make one ISO for an entire system?

I understand that this would mean that the ISO would be 10 gigs or largers.

I really wanted to be able to do something like this BACKUP=ISO as well as the OUTPUT=ISO, so that it will just be one big ISO.

An easy way would be --> dd if=/dev/device | gzip > /path/to/location/backup.gz

then to include that at the %post section of the image build have it do this -->

cp /path/to/location/backup.gz $INSTALL_ROOT/

and this backup.gz will then be included within the ISO image itself.

Once this is accomplished, the way to restore would simply be -->
zcat/cat backup.gz | dd of=/dev/device

However that being said, I would like an answer as to whether or not rear has this option pre-built into him natively (i.e. make a giant ISO of the system, similar to how Mondo works).

Just a question.  Thanks -- MultipathMaster

**Comment by gdha** [comment]
@multipathmaster see the man page on how to create an ISO with archive included. Feedback is of course more then welcome. It should make multiple ISO images.

**Comment by multipathmaster** [comment]
GDHA, 

Again you have been more than helpful...

BACKUP=NETFS
OUTPUT_URL=file:///opt/hd/sa/mondo
BACKUP_URL=iso://backup
OUTPUT=ISO
ISO_DIR=/opt/hd/sa/mondo
ISO_PREFIX="rear-$HOSTNAME.dc9098-$(date "+%y%m%d.%H%M%S")"


Here is what I have to begin building the ISO files and the tar.gz archive, however quick question, how can I tell rear to use a different tmp directory than /tmp.   Running out of space, but in /opt/hd/sa/mondo we have more than enough space to write the ISO and the tarball as well as using this space for the tmp (rear working dir), how do I point rear to this dir to take advantage of the extra space?

**Comment by gdha** [comment]
@multipathmaster the `conf/default.conf` says:
````
# the TMPDIR influences the mktemp command to define an alternative basedir instead of /tmp
# useful in case he /tmp is not large enough to contain ISO images and/or backup archives
# be careful the directory MUST exist otherwise you will get an error by mktemp
TMPDIR=""
export TMPDIR    # the export is required so that mktemp can pickup the variable
````

Rule of dumb, always check the default.conf file first ;-)

**Comment by multipathmaster** [comment]
GDHA, you are the man!  We are working now!  We will test, but you can close this support case out, this gets us across the finish line for sure for this particular project.  Thanks again for your time.
