### ISSUE TITLE
Error during recovering (layout recreation) - dosfslabel /dev/sdb1 NO NAME

### ISSUE THREAD

**Issue by kostgr** [rear/rear#647]
I've got error during layout recreation with the following message:
![unabletorecover_becauseoffslabel_no_name](https://cloud.githubusercontent.com/assets/6648353/9518170/f4413412-4cb4-11e5-9892-57bfb9797160.png)

It looks like missing quoting of the partition name.
openSuse 13.2 UEFI backup image, rear 1.7.1, 

Recovering started by loading in the BIOS mode (booting in UEFI mode failed - see also #214).

Related part of disklayout.conf:
> fs /dev/sdb1 /boot/efi vfat uuid=6EA3-66F6 label=NO\\bNAME\\b\\b\\b\\b options=rw,relatime,fmask=0002,dmask=0002,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro

**Comment by gdha** [comment]
@kostgr I have patched script `layout/prepare/GNU/Linux/13_include_filesystem_code.sh` 
If you give it a try?

**Comment by kostgr** [comment]
The issue is fixed now. Thanks for a quick response.
