### ISSUE TITLE
Wrote ISO image: Saving result files with NSR

### ISSUE THREAD

**Issue by yunsr** [rear/rear#654]
HI, i have updated Relax-and-Recover to 1.17.2 vers. OS SlES 11sp3. 
When i make rear -v mkrescue and  rear saving ".iso" file to NSR, backup job freezes on networker side and wait for writeable tape in NSR pool which i didn't specify in /etc/rear/local.conf.
local.conf:
OUTPUT=ISO
ONLY_INCLUDE_VG=( "system" )
BACKUP=NSR
NSR_DEFAULT_POOL_NAME=TSTSYSBOOT00

So it must be saved to TSTSYSBOOT00 but rear saved to another. Why rear did incorrect choose? How i can definitely set pool name for ".iso" save and pool which will use for recovery data?

thnks

**Comment by tomglx** [comment]
Please see issue: NSR POOLNAME variable #640
I've made a patch that supports exactly that. Last Posting

**Comment by yunsr** [comment]
thnx tomgix! your patch solved this problem. Option 'NSR_POOL_NAME' works now!

**Comment by gdha** [comment]
I've applied the patch @tomglx suggested. I assume we can close this issue, tight?

**Comment by tomglx** [comment]
OK with me, but yunsr has last say.

**Comment by yunsr** [comment]
ok with me too, this issue can be closed
