### ISSUE TITLE
Cannot see correct MAC addresses on HP CN1100E CNA card

### ISSUE THREAD

**Issue by wiggett** [rear/rear#656]
Hi Everyone,

Does anyone know if the hardware HP StorageWorks CN1100E Dual Port Converged Network Adapter
is supported in Rear. After booting rear ISO I get the error 

SIOCGIFFLAGS: No such device
SIOCGIFMTU: No such device
SIOCGIFFLAGS: No such device
SIOCGIFMTU: No such device

Then when I ifconfig -a to start building the network to rear -v recover I see incorrect MAC addresses (from the source server) and not the local server I'm restoring the image on

**Comment by schlomo** [comment]
The ReaR rescue image should support all the hardware that the original system supports.

So, does your original system support your network card? Or are you trying to move to new hardware? In that case you will have to install the neccessary driver on the original system and recreate the ReaR rescue image.

**Comment by wiggett** [comment]
Hi schlomo - Thanks for your reply - I managed to get the system up using the rear iso and completed a rear -v recover. The issue I'm having now , after I reboot , is that it see's all the old MAC addesses on the ethernet cards from the source server . When I change to the new MAC addresses , the OS complains and the interfaces go down , it seems it's still getting network configurations from the old/source server during reboot . Have you seen something like this before ?

**Comment by schlomo** [comment]
You will need to provide much more detail for me to say anything. In general, ReaR patches the udev rules for the network cards and the network configuration files with the new MAC address. If there is more than one NIC in your system then ReaR should also ask you which new MAC to use for which old one. Did this happen?

**Comment by wiggett** [comment]
No - but I think the issue is what you mentioned in the first reply - we are moving to new hardware so the source/original server probably doesn't have the  drivers for the newer emulex cards

**Comment by schlomo** [comment]
@wiggett I close this issue now since we cannot help you to install the driver in your source server :-)

If you need more help with this case, just reopen it agains.
