### ISSUE TITLE
rear-1.17.2.tar.gz are different on sourceforge versus OBS

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#658]
When downloading rear-1.17.2.tar.gz from "the Sourceforge Downloads page" at http://relax-and-recover.org/download/ I get
<pre>
310548 bytes rear-1.17.2.tar.gz
</pre>

In contrast in OBS Archiving:Backup:Rear rear-1.17.2 there is
<pre>
310392 bytes rear-1.17.2.tar.gz
</pre>

Which one is the right one?

A diff between both shows that those files differ:
<pre>
doc/rear.8
packaging/rpm/rear.spec
</pre>

**Comment by gdha** [comment]
The OBS one was the latest stable uploaded and therefore the correct one. I've uploaded the OBS tar ball to Sourceforge.
