### ISSUE TITLE
ReaR doesn't automatically add itself to the Grub bootloader

### ISSUE THREAD

**Issue by Nemiroff84** [rear/rear#671]
Sorry if my English is bad. My native is Russian.
I have clean installation of Ubuntu 14.04.03 at VMWare Workstation 12.0. ReaR doesn't automatically add itself to the Grub bootloader.
I tried diffrent variants of /etc/rear/local.conf:
1. No additional configuration
2. GRUB_RESCUE=
3. GRUB_RESCUE=y
4. GRUB_RESCUE=yes

After each changing of file I tried to reboot several time. No result.
Is this a bug or I'm doing somithing wrong?

**Comment by gdha** [comment]
@Nemiroff84 `GRUB_RESCUE=y` should do the trick. Did you check the rear log file for errors? You do not need to reboot to see if it worked. Just check `/boot/grub/grub.cfg` and look for a rear entry

**Comment by Nemiroff84** [comment]
I'm new to Linux and beacause of this I think that it may be my mistake. And I'll show what i do step by step.
Installation:
wget http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/all/rear_1.17.2_all.deb
sudo dpkg -i rear*.deb
sudo apt-get -f install

Added string GRUB_RESCUE=y to /etc/rear/local.conf . Saved and closed filed. After I checked it whith cat command that my changes was saved.

Then I checked /boot/grub/grub.cfg and there is no rear word.
directory /var/log/rear is empty.

Can you recommend to me something?

**Comment by gdha** [comment]
Did you run `/usr/sbin/rear -v mkrescue`?

**Comment by Nemiroff84** [comment]
Only after your recomendation and recieved error:
ERROR: ERROR: no binary found for grub-mkpasswd-pbkdf2 or grub2-mkpasswd-pbkdf2
Aborting due to an error, check /var/log/rear/rear-dc1.log for details

and error at log:

2015-10-20 17:09:12 Wrote ISO image: /var/lib/rear/output/rear-dc1.iso (98M)
2015-10-20 17:09:13 Including output/ISO/Linux-i386/85_check_for_errors.sh
2015-10-20 17:09:13 Including output/default/94_grub2_rescue.sh
2015-10-20 17:09:13 ERROR: ERROR: no binary found for grub-mkpasswd-pbkdf2 or grub2-mkpasswd-pbkdf2
=== Stack trace ===
Trace 0: /usr/sbin/rear:251 main
Trace 1: /usr/share/rear/lib/mkrescue-workflow.sh:35 WORKFLOW_mkrescue
Trace 2: /usr/share/rear/lib/framework-functions.sh:70 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:31 Source
Trace 4: /usr/share/rear/output/default/94_grub2_rescue.sh:20 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:132 StopIfError
Message: ERROR: no binary found for grub-mkpasswd-pbkdf2 or grub2-mkpasswd-pbkdf2
===================
2015-10-20 17:09:13 Running exit tasks.
rmdir: removing directory, '/tmp/rear.aeHh3e65em2VAgX/outputfs'
rmdir: failed to remove '/tmp/rear.aeHh3e65em2VAgX/outputfs': Directory not empty
2015-10-20 17:09:13 Finished in 95 seconds
2015-10-20 17:09:13 Removing build area /tmp/rear.aeHh3e65em2VAgX
rmdir: removing directory, '/tmp/rear.aeHh3e65em2VAgX'
2015-10-20 17:09:13 End of program reached

**Comment by gdha** [comment]
@Nemiroff84 Verify is the following package is available:
````
# dpkg -S /usr/bin/grub-mkpasswd-pbkdf2
grub-common: /usr/bin/grub-mkpasswd-pbkdf2
````

**Comment by Nemiroff84** [comment]
I received the same output as you show.

**Comment by gdha** [comment]
@Nemiroff84 Well, seems you hit a bug on Ubuntu - I corrected the code and now it behaves better. See commit above for the changes if you want it do correct the script 94_grub2_rescue.sh manually.

**Comment by Nemiroff84** [comment]
https://github.com/rear/rear/issues/671#issuecomment-149620996
