### ISSUE TITLE
Unable to determine raw USB device

### ISSUE THREAD

**Issue by Supersempfft** [rear/rear#674]
Hello,

I tried to create a backup with rear on a usb device and got:

```
Relax-and-Recover 1.15 / Git
Using log file: /var/log/rear/rear-host7.log
ERROR: BUG BUG BUG!  Unable to determine raw USB device for /dev/dm-18

=== Stack trace ===
Trace 0: /usr/sbin/rear:249 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:15 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:79 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:40 Source
Trace 4: /usr/share/rear/prep/USB/Linux-i386/35_check_usb_disk.sh:28 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:143 BugError
Message: BUG BUG BUG!  Unable to determine raw USB device for /dev/dm-18
````
device mapper ...

Should I blacklist the USB Stick? Or is the a better solution?

What can it be?
Andy

**Comment by schlomo** [comment]
Please give us your configuration (what you changed), the full log and the output of `rear dump`. You can also use gist.github.com to upload files.

**Comment by schlomo** [comment]
Please give us

* your configuration
* the log
* the output of `rear dump`

Maybe create a https://gist.github.com for those files, easier that pasting all that into the ticket.

**Comment by Supersempfft** [comment]
... config is just like this:
OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

and nothing more in the log. Solution is: multipath blacklist for the USB Stiick.

**Comment by schlomo** [comment]
Do you mean blacklisting usb-storage in your MPIO configuration? Yes, that seems like a good idea.

Please reopen if you have more to add to this. Thanks a lot for providing the solution.
