### ISSUE TITLE
Fedora 22: Mkrescue USB drives don't boot 

### ISSUE THREAD

**Issue by tharrisone** [rear/rear#676]
I've tried with regular usb drives and ssd external drives and after I do mkrescue and mkbackup and even checklayout it doesn't boot. There is a flash where I see the syslinux info but it never boots. I have legacy boot enabled.

**Comment by gdha** [comment]
I've just tried fedora 23 and USB mkbackup - the recovery system boots fine from the USB device.
Did you format the USB device before using it? `rear format /dev/<usb-dev>`
My `/etc/rear/site.conf` looks like:
````
BACKUP=NETFS
OUTPUT=USB
BACKUP_URL="usb:///dev/disk/by-label/REAR-000"
````
If the above doesn't help, please explain in detail what you did and show me the config.

**Comment by tharrisone** [comment]
It seems that instead of using fdisk or parted using rear format 
everything worked out and it booted up just fine. I must of missed that 
in the man pages.

Thanks!
