### ISSUE TITLE
NFS mount error 

### ISSUE THREAD

**Issue by akumacxd** [rear/rear#684]
OS: SUSE 11 SP3
rear: relax-and-recover 1.16 /git
nfs :
 cat /etc/exports
/exports *(rw,no_root_squash)

I'm try to recover my system with command "rear recover" ,  then give me this message
EEERO:Mount commadn 'mount -v -t nfs -o rw,noatime 172.200.50.6:/backup /tmp/rear.J8DycUB/outputfs' failed.
 I can manually mount with this command
" mount -t nfs -o rw,noattime,nolock 172.200.50.6:/backup /mnt"
but i can not recover system
How to solve this problem? is it bug?

**Comment by akumacxd** [comment]
![1](https://cloud.githubusercontent.com/assets/15681932/10988348/816a8e9e-8476-11e5-857e-73e42a2f9b89.png)

**Comment by akumacxd** [comment]
my rear configuation 
vim /etc/rear/local.conf
  ISO_DIR=/backup/iso
  BACKUP=NETFS
  BACKUP_PROG=tar
  BACKUP_TYPE=full
  BACKUP_URL="nfs://172.200.50.6/backup"

**Comment by akumacxd** [comment]
nfs configuration
![2](https://cloud.githubusercontent.com/assets/15681932/10988521/fe13209a-8477-11e5-824d-4316341ceb9d.png)

**Comment by akumacxd** [comment]
I have another question about "mount LVM"
In recover environment I can not mount LVM, always mention is not a valid block device
![3](https://cloud.githubusercontent.com/assets/15681932/10988968/80c74792-847c-11e5-80e7-34ef09b5463c.png)

**Comment by akumacxd** [comment]
rear log

![4](https://cloud.githubusercontent.com/assets/15681932/10989030/2f212b6e-847d-11e5-927e-d4010a4f5c45.png)

**Comment by gdha** [comment]
@akumacxd Add the following `BACKUP_OPTIONS="nfsvers=3,nolock"` to you `/etc/rear/local.conf` file.
Before mounting a volume group (vg00) you should activate it: `vgchange -a y vg00`

**Comment by akumacxd** [comment]
Thank you very much for the answer. I appreciate that.
