### ISSUE TITLE
Define default use case for ReaR

### ISSUE THREAD

**Issue by schlomo** [rear/rear#698]
In relation to #696 we should decide which out-of-the-box use case to support via package dependencies.

**Comment by gdha** [comment]
From my point of view: ISO is the default OUTPUT and therefore, the only default mechanism. All others are optional and are defined by the users, where `prep` scripts should trigger a warning if something crucial for that path is missing.

**Comment by gdha** [comment]
@schlomo what do you want to do with this issue? No-one else replied...

**Comment by schlomo** [comment]
Let's go with the ISO beeing default. Probably NETFS is also most widely used, we could consider it beeing the default BACKUP method instead of REQUEST_RESTORE.

IMHO there is no immediate need for action.
