### ISSUE TITLE
ReaR UEFI image fails booting if shim.efi bootloader is used

### ISSUE THREAD

**Issue by pavoldomin** [rear/rear#702]
The rear image for the system that defines ```shim.efi``` (secure boot) as an UEFI bootloader application fails to boot. The reason is, ```shim.efi``` needs also the follow-up loader. 

A name of the followup loader seems to be hardcoded to be ```grub.efi```; it seems to be a compile-time option for ```shim.efi```. I.e. it can depend on vendor. If I get it right, a follow-up loader can be also ```elilo.efi``` (renamed to ```grub.efi```)

A suggested patch that includes the support for ```shim.efi``` bootloader : #701. It simply copies also the ```grub.efi``` and ```elilo.efi``` (and its corresponding config files) into the boot image EFI partition. 
It is tested on SLES11 SP3 system only, where (at least for me) it works completely transparently:
   1. boot rear uefi iso (ebiso tested only, but should work also with xorisso or mkisofs).
   2. rear recover.
   3. boot recovered system.

**Comment by gdha** [comment]
@pavoldomin Thank you for the pull request - it seems correct to me.
@gozora Vlado - if you could test the latest updates as well that would make me confident nothing is broken.

**Comment by gozora** [comment]
@gdha Certainly, will do ...

**Comment by gozora** [comment]
I've made several tests on SLES, Centos and Ubuntu. 
All looks good.

**Comment by gdha** [comment]
@pavoldomin I'll add the label 'fixed'

**Comment by pavoldomin** [comment]
Thanks Vlado @gozora, thanks @gdha. I am close the issue. We'll do another series of tests on our uefi san booting server next week (hopefully), this time with recent ReaR rpm from OBS, including these patches. If any problem occurs, i'd reopen the issue.
