### ISSUE TITLE
Copy "rear recover" log file and related data into recovered system

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#706]
At the end of "rear recover"
the log file /var/log/rear/
and other recovery related data
like /var/lib/rear/layout/disklayout.conf
and its matching /var/lib/rear/layout/diskrestore.sh
exist only in the rear recovery system.

When the rear recovery system is shut down
the "rear recover" related data is lost.

I like to implement that "rear recover" by default copies
the recovery related log and data into the recovered system
so that this data is later available for example for a detailled
analsysis of the recovery.

To keep the recovery related log and data strictly separated from
the other rear logs and data I like to use a separated directory
var/log/rear/recover for this.

In short:
I like to implemet that at the end of "rear recover"
basically the following is done:
<pre>
mkdir -p /mnt/local/var/log/rear/recover
cp -p /var/log/rear/rear*.log /mnt/local/var/log/rear/recover
mkdir /mnt/local/var/log/rear/recover/layout
cp -pr /var/lib/rear/layout/*  /mnt/local/var/log/rear/recover/layout
</pre>

I did a "rear --debugscripts xv recover" and the above
commands manually and /mnt/local/var/log/rear/recover
needs 1.1 MB disk space and with plain "rear recover"
/mnt/local/var/log/rear/recover needs needs 80 kB for me.

I do not think this "wastes disk space" and therefore
I think it can (and should) be done by default.

If there is so little free disk space that about 2 MB
for 'rear recover' with 'set -xv' and about 100 kB
for plain 'rear recover' makes a noticeable difference,
then that only points out the real problem
("too little free disk space").

**Comment by gdha** [comment]
@jsmeix I have no objection against it.
Perhaps we could in the meantime also tackle issue #21 ?

**Comment by jsmeix** [comment]
I will implement this one together with https://github.com/rear/rear/issues/21

**Comment by schlomo** [comment]
Why not copy it to `/root` in the recovered system - similar to how Red Hat's Kickstart leaves there the kickstart file and log?

**Comment by schlomo** [comment]
In any case, I would make sure that only root can read those files.

**Comment by jsmeix** [comment]
I already implemented that only root can access files
in /var/log/rear/recover

But I wonder why everybody can read the other files
in /var/log/rear and /var/lib/rear ?

In other words:
I wonder why it seems what "rear mkbackup" results is o.k. to be read by any user while what "rear recover" results is not?

**Comment by gdha** [comment]
@jsmeix @schlomo Personally, I don't think a log file is a security threat if it is readable. We only have to make sure there are no passwords or any other sensitive data visible. And, I believe we already have done that in the past (#560)

**Comment by jsmeix** [comment]
I implemented this particular issue with https://github.com/rear/rear/pull/709 but this does not yet implement https://github.com/rear/rear/issues/21

**Comment by jsmeix** [comment]
This particular issue is fixed with https://github.com/rear/rear/pull/709
