### ISSUE TITLE
Have '/mnt/local' in a global variable.

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#708]
Currently '/mnt/local' is hardcoded at many places in the code.

I think it would be better to have a global variable like
<pre>
RECOVERY_SYSTEM_ROOT="/mnt/local"
</pre>
in usr/share/rear/conf/default.conf

Cf. https://github.com/rear/rear/issues/678

**Comment by gdha** [comment]
@jsmeix +1

**Comment by jsmeix** [comment]
I will implement it carefully step by step.

I cannot simply replace all '/mnt/local' by '$RECOVERY_SYSTEM_ROOT' in an automated way (e.g. via "sed") because I need to carefully check that each $RECOVERY_SYSTEM_ROOT is correctly replaced by its value.

E.g.
<pre>
echo 'command with /mnt/local in it' >> "$LAYOUT_CODE"
</pre>
currently works as intended while
<pre>
echo 'command with $RECOVERY_SYSTEM_ROOT in it' >> "$LAYOUT_CODE"
</pre>
does no longer work.

**Comment by jsmeix** [comment]
FYI:
It appears only with leading '/' but with and without trailing '/':
<pre>
github/rear $ find * | xargs grep 'mnt/local' | wc -l
245

$ find * | xargs grep '/mnt/local' | wc -l
245

$ find * | xargs grep '/mnt/local/' | wc -l
128
</pre>

245 places isn't too hard to change manually...

**Comment by jsmeix** [comment]
I think the variable name RECOVERY_FS_ROOT is better
than RECOVERY_SYSTEM_ROOT because it means
the root of the filesystem tree of the to-be-recovered-system
and not the root filesystem of the recovery system.

**Comment by jsmeix** [comment]
Of course https://github.com/rear/rear/pull/710 is not yet
the final solution - but it should be a first working step
(at least "rear mkbackup" and "rear recover" still works for me).

**Comment by jsmeix** [comment]
Via https://github.com/rear/rear/pull/740 I would like to rename RECOVERY_FS_ROOT into TARGET_FS_ROOT.

I felt always unhappy with the name RECOVERY_FS_ROOT
but somehow I had no better idea how to call what it actually is.

During https://github.com/rear/rear/issues/732 I noticed that
the name RECOVERY_FS_ROOT is really misleading.

I would very much appreciate it if the rear upstream authors
would agree to rename it into TARGET_FS_ROOT.

In particular because when the next rear version is released
such a rename would be much more annoying.

**Comment by gdha** [comment]
@jsmeix I think this can be closed, no?

**Comment by jsmeix** [comment]
What we have is TARGET_FS_ROOT as global readonly variable
that is set to "/mnt/local" (in usr/sbin/rear).
That part is done.

But:
What we do not have is the currently 221 lines fixed in 60 scripts
that still contain hardcoded "/mnt/local..." strings, see my above
https://github.com/rear/rear/issues/708#issuecomment-158906275

But there is no bug with the current situation
of course provided nobody changes the
TARGET_FS_ROOT value in usr/sbin/rear ;-)

Accordingly I changed the milestone from Rear v1.18
to the uspecified "Rear future".

**Comment by jsmeix** [comment]
In https://github.com/rear/rear/pull/775 I replaced all hardcoded /mnt/local with $TARGET_FS_ROOT

When this pull request is accepted there is no longer any hardcoded /mnt/local in the scripts (except when it is set in usr/sbin/rear and in a few comments) and this issue here can be finally closed.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/775 this issue should be fixed (provided I did not cause any regressions).
