### ISSUE TITLE
Have rear-$(hostname)-$WORKFLOW-<date>.log in any case

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#712]
Currently subsequent runs of "rear &lt;workflow&gt;"
keep exactly one old log file in a hardcoded way
in usr/sbin/rear
<pre>
# Keep old log file:
if test -r "$LOGFILE" ; then
    mv -f "$LOGFILE" "$LOGFILE".old 2>&8
fi
</pre>

Because of https://github.com/rear/rear/pull/709#issuecomment-159346698 I like to discuss here
whether or not this should be changed to use rear-$(hostname)-$WORKFLOW-<date>.log in any case

The advantage is that unlimited old log files are kept.

The disadvantage is that unlimited old log files are kept
which could fill up the harddisk.

Perhaps the solution is to make the behaviour configurable
via usr/share/rear/conf/default.conf and voila! it is already there
<pre>
LOGFILE="$LOG_DIR/rear-$HOSTNAME.log"
</pre>

The admin can change this to
<pre>
LOGFILE="$LOG_DIR/rear-$HOSTNAME-$WORKFLOW-$( date -Iseconds ).log"
</pre>

Therefore from my point of view there is nothing to change here
and I set this issue initially to "fixed" and  "waiting for feedback".

FYI:
With unique LOGFILE names like
<pre>
LOGFILE="$LOG_DIR/rear-$( date -Iseconds ).log"
</pre>
one does not get *.old copies because for each "rear" run
the new LOGFILE name does not already exist.

**Comment by pavoldomin** [comment]
I support @jsmeix point, we should not modify the existing defaults: admins may have implemented  some post-processing with the rear log file (parse it/copy it somewhere/...) and changing the default name would break that.

**Comment by gdha** [comment]
Currently we have `./usr/share/rear/conf/default.conf:LOGFILE="$LOG_DIR/rear-$HOSTNAME.log"
` as a default. If there is a consensus to keep it as it is now then that is fine for me.
Others may have a different opinion, but then I would like to read it here...

**Comment by jsmeix** [comment]
Because there is general agreement not to change
the default log file name, I close this issue.
