### ISSUE TITLE
[ Misunderstood ] backup from rescue stick not possible by design / prevent incompatible workflows in rescue mode

### ISSUE THREAD

**Issue by megabert** [rear/rear#719]
# Short
When I run through the quickstart, I create the rescue disk and boot a server i want to backup. In rescue mode, when I try to backup a system, I get the error:

Could not find "isolinux.bin". Maybe you have to set ISO_ISOLINUX_BIN....

# Long 
1. I installed rear at debian 8 (At first 1.17.2 from git, then the deb package with same version, after that rear 1.16.1 as deb package, all the same outcome)
2. I formatted an usb stick with `rear -v format /dev/sdb`
3. I set up my local.conf(see below)
4. I create my rescue stick `rear -v mkrescue `
5. I booted rear ( using another hardware than the machine, where I created the stick )
6. I pressed ` ctrl + c ` when dhclient was waiting (I have no dhcp-server here)
7. I configured my network card manually with ifconfig and tested NFS-Connectivity
8. I executed `rear  -v mkbackuponly` (and mkbackup too)
9. This error was shown: `"Could not find 'isolinux.bin'. Maybe you have to set ISO_ISOLINUX_BIN [$ISO_ISOLINUX_BIN] or install the syslinux package ?"` And other errors, after I commented out this check (mbr.bin, ... all of the stuff in /usr/share/rear/prep/USB/Linux-i386). After I disabled all the checks in the mentioned directory, no backup data files were created at all, when I looked at my NFS Share

>
> local.conf
>
> OUTPUT=USB
> BACKUP=NETFS
> \# USB_DEVICE=/dev/disk/by-label/REAR-000  <---- this does not work (Fixed in 1.18)
> OUTPUT_URL=usb:///dev/disk/by-label/REAR-000 
> BACKUP_URL=nfs://storageserver.of.mine/temp/rear
> EOF

**Comment by gdha** [comment]
@megabert did you install extlinux - that is what you need to boot from an USB device?

**Comment by schlomo** [comment]
You should run `rear mkbackup` instead of `rear mkrescue`. From within the rescue system you can only run `rear recover`.

And yes, It can be that ATM you need to install the package that provides isolinux.bin. We will fix this in the next release, IIRC.

**Comment by megabert** [comment]
> did you install extlinux
Yes.

> You should run rear mkbackup instead of rear mkrescue. From within the rescue system you can > only run rear recover.

Ok. Seems I haven't got the full picture.

Thanks.

**Comment by schlomo** [comment]
If that is the case, maybe rename the issue to rear "prevent incompatible workflows in rescue mode"

**Comment by HazCod** [comment]
A bit of hijack perhaps, but can `rear recover` be executed automatically?

**Comment by schlomo** [comment]
Yes, hijack. See #686 for details:

```
ISO_DEFAULT=manual
```

And a pull request to the man page / web site is most welcome :-)

**Comment by gdha** [comment]
@schlomo `ISO_DEFAULT` is already described in the man page.
