### ISSUE TITLE
Incorrect rear bash history entry

### ISSUE THREAD

**Issue by jk04au** [rear/rear#722]
My environment:
<pre>
Testing date: 2015-12-01
Operating system: Debian 8.2 (jessie)
Package: rear_1.17.2_all.deb
</pre>

During a USB recovery phase, rear was unable to mount USB device. Decided to drop to shell when offered a menu for my next action. Found root .bash_history file already populated with a few entries presumably as a troubleshooting aide for administrators. 
<pre>: : : : : WHAT ELSE WOULD YOU HAVE EXPECTED HERE?
vi /var/lib/rear/layout/diskrestore.sh   # View/modify disk restore script
vi /var/lib/rear/layout/disklayout.conf  # View/modify disk layout configuration
less /var/log/rear/rear-myhost.log   # View log file
loadkeys -d     # Load default keyboard layout (US)
rear recover    # Recover your system
</pre>

Issue: Could not view diskrestore.sh because the script was missing
<pre>
vi /var/lib/rear/layout/diskrestore.sh   # View/modify disk restore script
</pre>

**Comment by gdha** [comment]
@jk04au these are simply some examples so that the history is not empty to start with. When you haven't started a recovery operation then the `distrestore.sh` script does not yet exists.
It is as it is...
