### ISSUE TITLE
Downgrade dependency in .DEB

### ISSUE THREAD

**Issue by itsbo** [rear/rear#723]
Could you downgrade the dependency on portmap also to a recommend? If nfs-client is already a Recommend then having a hard dependency on portmap is unnecessary and only leads to a rpc daemon running unnecessarily. Having to disable the portmapper manually is cumbersome.

**Comment by gdha** [comment]
@itsbo It makes sense. I'll make the necessary changes.

**Comment by itsbo** [comment]
Thank you.
