### ISSUE TITLE
Using HP DL360g9 SD-Card as rear recovery media in UEFI environment - HowTo?

### ISSUE THREAD

**Issue by swusowski** [rear/rear#736]
Hello,
I want to use the internal SD-Card of the HP DL360g9 for rear recovery media in UEFI boot (with booting from SD-Card) environment.
Is it basically possible boot the DL360g9 from SD-Card in UEFI?

If OUTPUT=ISO we can use this for UEFI boot via iLO virtual Media. I try to write the ISO-file to the SD-Card but it can't boot. (Didn't try in Legacy Mode)

If OUTPUT=USB we can only boot in Legacy Mode. 
Is it possible to recover a UEFI system with rear if it booted in Legacy Mode?

THX :-)

**Comment by gdha** [comment]
Perhaps see http://relax-and-recover.org/documentation/faq How to create a bootable USB disk from an ISO image
However, rear itself is not capable (yet) to make an UEFI bootable SD/USB disk.

**Comment by gdha** [comment]
See also issue #603
