### ISSUE TITLE
NETFS Tar Incremental restore fails with message « Backup archive '' not found » if BACKUP_PROG_COMPRESS is not gzip

### ISSUE THREAD

**Issue by DamienGombaultRecia** [rear/rear#743]
Hi.

I have set in local.conf :
BACKUP_PROG_COMPRESS_OPTIONS="--bzip2"
BACKUP_PROG_COMPRESS_SUFFIX=".bz2"
Incremental archives are now bziped and suffixed with .bz2.

In file /usr/share/rear/prep/NETFS/default/07_set_backup_archive.sh, line 14 :
for i in $(ls ${BUILD_DIR}/outputfs/${NETFS_PREFIX}/*.tar.gz); do restorearchive=$i;done
setting restorearchive variable is hardcoded with .tar.gz.

Restore fails because it does not find my .tar.bz2 files.
I think .tar.gz should be replaced with ${BACKUP_PROG_SUFFIX}${BACKUP_PROG_COMPRESS_SUFFIX}

Thank you.

**Comment by gdha** [comment]
@DamienGombaultRecia Thank you for reporting this. I'll check it myself when I have a bit of spare time (not this week anymore)

**Comment by gdha** [comment]
@DamienGombaultRecia could you verify the fix is correct?

**Comment by DamienGombaultRecia** [comment]
Hi. The patch looks good.
I'm on holidays, I will test it in January.
Happy christmas :)

**Comment by gdha** [comment]
@DamienGombaultRecia A kind reminder to run a quick test - thx

**Comment by DamienGombaultRecia** [comment]
Hi.
I'll try to test it tomorrow.

**Comment by DamienGombaultRecia** [comment]
Hi.
The fix is not complete and does not work.
I did not notice before but the verify/NETFS/default/07_set_backup_archive.sh file should be modified the same way, then it works.

**Comment by gdha** [comment]
@DamienGombaultRecia Thank you for catching this! I just fixed it as well. Please verify and give me feedback.

**Comment by DamienGombaultRecia** [comment]
The patch now works :)
Thank you.
