### ISSUE TITLE
Merry Christmas and a happy New Year!

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#744]
I wish all Relax-and-Recover users, contributors and authors
a Merry Christmas and a happy New Year!

**Comment by gdha** [comment]
@jsmeix Thank you and I can assure you that rear still has a bright future.
Today I already used a rear rescue image twice to safe a production SPA HANA cluster (after kernel rebuild) [SLES for SAP 11 SP3]

**Comment by jsmeix** [comment]
I also think that rear has a bright future.
As far as I can imagine the number of rear users
will increase very much in the near future.
