### ISSUE TITLE
33_find_isolinux.sh also called for OUTPUT=USB

### ISSUE THREAD

**Issue by schlomo** [rear/rear#745]
usr/share/rear/prep/USB/Linux-i386/33_find_isolinux.sh is a symlink to ISO

Why do we need this?

**Comment by gdha** [comment]
@schlomo `33_find_isolinux.sh` sets the `ISO_ISOLINUX_BIN` variable (this was there from the beginning). However, since the packages were split up some modules were moved to their own sub-directory, and therefore, the script `35_find_syslinux_modules.sh` was introduced to fix this. So, script `33_find_isolinux.sh` is purely there for legacy purposes.

**Comment by schlomo** [comment]
I am not sure I understand what you mean by "legacy purposes".

Can we remove this script to allow USB mode usage without installing isolinux (I know, we install it by default)?

**Comment by gdha** [comment]
@schlomo It seems we only need:
````
# Define the syslinux directory for later usage
SYSLINUX_DIR=$(dirname $ISO_ISOLINUX_BIN)
````
Perhaps, it would be better to create a new script called `30_find_syslinux.sh` and remove the link to `33_find_isolinux.sh` (would make more sense I guess). Your thoughts?

**Comment by gdha** [comment]
@schlomo Just verified it with `OUTPUT=ISO` and `BACKUP_URL=usb:///...` then the `SYSLINUX_DIR` is used in fact (and needed). With `OUTPUT=USB` the `SYSLINUX_DIR` is not used.
I would leave the link so that we don't break the ISO rescue image flow in combination with USB as backup destination.

**Comment by schlomo** [comment]
@gdha Not sure I follow your thoughts. With OUTPUT=ISO IMHO prep/USB should not be called at all. So removing something from prep/USB should not have any impact for OUTPUT=ISO but only for OUTPUT=USB.

Or do we have some auto magic stuff in place that would call prep/USB if BACKUP_URL=usb://*?

**Comment by gdha** [comment]
@schlomo I removed the link and it found no negative drawback in OUTPUT=USB nor OUTPUT=ISO. Therefore, we can remove the link. If we get complaints in the future then we should remember this issue somehow.

**Comment by schlomo** [comment]
Thanks a lot!
