### ISSUE TITLE
Backup to USB needs BACKUP_URL

### ISSUE THREAD

**Issue by schlomo** [rear/rear#746]
In the example in http://relax-and-recover.org/usage/, it seems like
```
BACKUP_URL=$OUTPUT_URL
```
is missing. 

Or is this actually a bug and it should work without?

I'll be happy to fix it, just wanted to be sure I fix the right thing :-)

**Comment by gdha** [comment]
@schlomo you are right - it should say `BACKUP_URL=` instead of `OUTPUT_URL=`. It would have been correct if the example would show `rear mkrescue` instead of `rear mkbackup`. If `BACKUP_URL` is defined (and no explicit `OUTPUT_URL` has been defined) then `OUTPUT_URL=BACKUP_URL`

**Comment by gdha** [comment]
To git@github.com:rear/rear.github.com.git
   f964e26..c577cae  master -> master
We can close this one.
