### ISSUE TITLE
ipv6 has been disabled in server, but ISO boots server with ipv6 assigned to eth0 and lo

### ISSUE THREAD

**Issue by blaxxton** [rear/rear#748]
ipv6 is disabled on server but when we boot the server from ISO and 
choose Recover, there is ipv6 assigned to either eth0 and lo.

This cause problem recovering from EMC Legato Networker with ipv6 name is not accessible.
EMC legato Networker check if there is ipv6 assigned to interface, and if there is , will look to find
the server name based on ipv6 address defined in /etc/hosts and fails.

We had to delete the ipv6 address on both  eth0 and loopback to be able to communicate with EMC Networker server and recover.

There is an option of adding ipv6 to /etc/hosts, but even with that , autorecover from Legato would not work if ipv6 is enabled in rescue mode while the original server has ipv6 disabled.

There should be an option to disable ipv6.

Thanks

**Comment by gdha** [comment]
@blaxxton please run rear and capture the following output (of scripts). Perhaps use GitHub Gist to store the output.
````
ip a
rear -vd mkrescue
cd /tmp/rear.<6AlinkJEojgKw9h>/rootfs    (replace <6AlinkJEojgKw9h> with the unique string)
cat etc/rear/rescue.conf
cat etc/scripts/system-setup.d/60-network-devices.sh
cat etc/scripts/system-setup.d/62-routing.sh
cat etc/scripts/system-setup.d/63-teaming.sh
````

**Comment by gdha** [comment]
@blaxxton perhaps also list the `ifcfg-<dev>` configuration script (location sometimes /etc/sysconfig/network-scripts)

**Comment by schlomo** [comment]
@blaxxton how did you disable ipv6 on your server?

**Comment by blaxxton** [comment]
MyHostName###ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:b1:06:77 brd ff:ff:ff:ff:ff:ff
    inet 192.168.112.167/24 brd 192.168.112.255 scope global eth0
MyHostName###

MyHostName###rear -vd mkrescue      
Relax-and-Recover 1.17.2-git201509031543 / 2015-09-03
Using log file: /var/log/rear/rear-MyHostName.log
Creating disk layout
Creating root filesystem layout
EMC Networker will recover these filesystems: / /boot /fs_db /fs_data /fs_bkup 
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-MyHostName.iso (105M)
Saving result files with NSR (EMC NetWorker)
If the NSR_RETENTION_TIME="1 day" is too low please add NSR_RETENTION_TIME variable in /etc/rear/local.conf
 pool           retent  name
============================
dailyclone 12/23/15 /var/lib/rear/output/rear-MyHostName.iso
dailyclone 12/24/15 /var/lib/rear/output/rear-MyHostName.iso
dailyclone 12/25/15 /var/lib/rear/output/rear-MyHostName.iso
You should also rm -Rf /tmp/rear.XR09RJW2vDY1y3X
MyHostName###


MyHostName###cd /tmp/rear.XR09RJW2vDY1y3X/rootfs
MyHostName###pwd
/tmp/rear.XR09RJW2vDY1y3X/rootfs
MyHostName###cat etc/rear/rescue.conf
# initialize our /etc/rear/rescue.conf file sourced by the rear command in recover mode
# also the configuration is sourced by system-setup script during booting our recovery image

SHARE_DIR="/usr/share/rear"
CONFIG_DIR="/etc/rear"
VAR_DIR="/var/lib/rear"
LOG_DIR="/var/log/rear"

# TMPDIR variable may be defined in local.conf file as prefix dir for mktemp command
# e.g. by defining TMPDIR=/var we would get our BUILD_DIR=/var/tmp/rear.XXXXXXXXXXXX
# However, in rescue we want our BUILD_DIR=/tmp/rear.XXXXXXX as we are not sure that
# the user defined TMPDIR would exist in our rescue image
# by 'unset TMPDIR' we achieve above goal (as rescue.conf is read after local.conf)!
unset TMPDIR
MyHostName###
MyHostName###cat etc/scripts/system-setup.d/60-network-devices.sh
# if USE_DHCLIENT=y then use DHCP instead and skip 60-network-devices.sh
[[ ! -z "$USE_DHCLIENT" && -z "$USE_STATIC_NETWORKING" ]] && return
# if IPADDR=1.2.3.4 has been defined at boot time via ip=1.2.3.4 then configure 
if [[ "$IPADDR" ]] && [[ "$NETMASK" ]] ; then
    device=${NETDEV:-eth0}
    ip link set dev "$device" up
    ip addr add "$IPADDR"/"$NETMASK" dev "$device"
    if [[ "$GATEWAY" ]] ; then
        ip route add default via "$GATEWAY"
    fi
    return
fi
ip addr add 192.168.112.167/24 dev eth0
ip link set dev eth0 up
ip link set dev eth0 mtu 1500
MyHostName###cat etc/scripts/system-setup.d/62-routing.sh
# if USE_DHCLIENT=y then skip 62-routing.sh as we are using DHCP instead
[[ ! -z "$USE_DHCLIENT" && -z "$USE_STATIC_NETWORKING" ]] && return
# if GATEWAY is defined as boot option gw=1.2.3.4 then use that one
[[ ! -z "$GATEWAY" ]] && return
if [[ -e /proc/cmdline ]] ; then
    if grep -q 'noip' /proc/cmdline ; then
        return
    fi
fi
ip route add default via 192.168.112.1 dev eth0 table main
MyHostName###cat etc/scripts/system-setup.d/63-teaming.sh
cat: etc/scripts/system-setup.d/63-teaming.sh: No such file or directory
MyHostName###ls etc/scripts/system-setup.d/
00-functions.sh           40-start-udev-or-load-modules.sh  45-serial-console.sh           60-network-devices.sh  99-makedev.sh
10-console-setup.sh       41-load-special-modules.sh        55-migrate-network-devices.sh  62-routing.sh
20-check-boot-options.sh  42-engage-scsi.sh                 58-start-dhclient.sh           90-networker.sh*
MyHostName###

**Comment by blaxxton** [comment]
I deleted the ipv6 address with ifconfig command after booting to rescue by choosing recover.

**Comment by blaxxton** [comment]
MyHostName###ls -la /etc/sysconfig/network-scripts/ifcfg-*
-rw-r--r-- 1 root root 268 Dec 23 16:08 /etc/sysconfig/network-scripts/ifcfg-eth0
-rw-r--r-- 1 root root 254 Oct 10  2013 /etc/sysconfig/network-scripts/ifcfg-lo
MyHostName###

**Comment by blaxxton** [comment]
I deleted the ipv6 address with ifconfig command after booting to rescue by choosing recover.

**Comment by blaxxton** [comment]
ipv6 disabled on server by adding:
MyHostName###tail -n 3 /etc/sysctl.conf 
# IPv6 support in the kernel, set to 0 by default
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
MyHostName###

MyHostName###head -n 2 /etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=no
MyHostName###

MyHostName###tail -n 1 /etc/sysconfig/network-scripts/ifcfg-eth0    
IPV6INIT=no
MyHostName###

**Comment by gdha** [comment]
Did you define `USE_DHCLIENT` somewhere in `local.conf` or `site.conf`? As I see no active IPv6 on your current system (which what you said), but when looking at the scripts produced by rear I see also **no** IPv6 definitions. It can only be introduced by dhcpd6 I guess?
You can always force static IP addresses with the variable `USE_STATIC_NETWORKING=1` if that would be required.

**Comment by blaxxton** [comment]
Already tired USE_STATIC_NETWORKING=1 in /etc/rear/local.conf
and the result was the same, ipv6 is being set on eth0.

MyHostName###tail -n 2 /etc/rear/local.conf
BACKUP=NSR
USE_STATIC_NETWORKING=1
MyHostName###

/etc/rear/local.conf does not have any USE_DHCLIENT.

I can't find where ipv6 is being set in any of the scripts.
The only place ipv6 address is being set is when we set dhcp ipv6 but 
dhcp is not installed on server

MyHostName###rpm -aq | grep -i dhcp                    
dhcp-common-4.1.1-38.P1.el6.x86_64
MyHostName###

.

**Comment by blaxxton** [comment]
Correct me if I am wrong.

In line 64 of 21_include_dhclient.sh:
64 [ ! -z "$DHCLIENT6_BIN" ] && USE_DHCLIENT=y

This means if DHCLIENT6_BIN is not empty set USE_DHCLIENT to y which seems to be correct
but on my server, below lines always return y:

MyHostName###export DHCLIENT6_BIN=""; echo $DHCLIENT6_BIN; [[ ! -z "$DHCLIENT6_BIN" ]] && USE_DHCLIENT=y; echo $USE_DHCLIENT

y
MyHostName###export DHCLIENT6_BIN="1"; echo $DHCLIENT6_BIN; [[ ! -z "$DHCLIENT6_BIN" ]] && USE_DHCLIENT=y; echo $USE_DHCLIENT
1
y
MyHostName###

I am using bash.

**Comment by blaxxton** [comment]
I even tried passing the ip and nm to kernel at boot time, but still ipv6 is being setup on both eth0 and loopback.

**Comment by blaxxton** [comment]
MyHostName###export DHCLIENT6_BIN= ; DHCLIENT6_BIN=${DHCLIENT6_BIN##*/}; echo $DHCLIENT6_BIN;  [ ! -z "$DHCLIENT6_BIN" ] && USE_DHCLIENT=y; echo $USE_DHCLIENT                       

y
MyHostName###export DHCLIENT6_BIN="/usr/bin/dhcclient.sh"; DHCLIENT6_BIN=${DHCLIENT6_BIN##*/}; echo $DHCLIENT6_BIN;  [ ! -z "$DHCLIENT6_BIN" ] && USE_DHCLIENT=y; echo $USE_DHCLIENT
dhcclient.sh
y
MyHostName###

**Comment by blaxxton** [comment]
I agree, I don't see any command that set ipv6 in rootfs, but I think show how USE_DHCLIENT is being set and dhcpd6 is being called. is it possible it is defined in kernel config file ?

**Comment by gdha** [comment]
@blaxxton to be 100% sure you could add `set -x` to the script `./skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh` and rebuild the rescue image and boot from it. Then you should see what it does... According to me the variable `USE_DHCLIENT` should **not** be set and this script should be skipped for that reason.
Otherwise, you could see what is running with `ps ax` on your rescue system. Or, the `/var/log/messages` could give a hint of what happened. It is a bit of mystery...

**Comment by blaxxton** [comment]
I don't think running set -x option to debug would help because you were right, and there is no where in script that ipv6 being set using ip command.

adding EXCLUDE_MODULES=( ipv6 ) to /etc/rear/local.conf fixed my problem and not seeing any ipv6 address assigned to either loopback or eth0.

This is RedHat 6 and even after disabling ipv6 in /etc/modprobe.d/ipv6.conf, I can see ipv6 modules in modprobe -l output.

According to RedHat Document:
https://access.redhat.com/solutions/72733

The root cause of the issue is the dracut-network plug-in but we don't have such a plugin installed.
resolution at RedHat level is rebuilding the initramfs file. 
The ipv6.conf file will be pulled into the initramfs file, and applied at the initramfs stage.

I tried rebuilding the initramfs but still am able to see ipv6 modules also not a very good idea to disable ipv6 module at system level.

somehow , your script create a initramfs that has ipv6 enabled based on the server.

**Comment by gdha** [comment]
perhaps you could run once `rear -vd mkrescue` and check under /tmp/rear/.XXXX/rootfs/etc directory the file `modules`. Is the ipv6 listed in there?

**Comment by blaxxton** [comment]
Only one entry in that file:
cat modules
vmxnet3

but there is ipv6 module in /var/lib/rear/recovery/initrd_modules
grep ipv6 /var/lib/rear/recovery/initrd_modules
ipv6

ipv6 is being added to interfaces when kernel is being loaded.

**Comment by gdha** [comment]
Interesting feedback - the script `./usr/share/rear/rescue/GNU/Linux/26_collect_initrd_modules.sh` prepares the initrd_modules file.
Perhaps, it would be a good idea if IPv6 is disabled to exclude it from this list. However, most likely there will always be a case where one needs it, no?

**Comment by schlomo** [comment]
IMHO we should actively suppress IPv6 as long as we don't handle it properly (with a flag to suppress that mechanism). So far we had more reports of "IPv6 broke my environment" than of "Please handle IPv6 properly".

**Comment by gdha** [comment]
````
$ cat /proc/net/if_inet6 
00000000000000000000000000000001 01 80 10 80       lo
fe80000000000000626720fffe18861c 03 40 20 80     wlo1
2a02a03f1a397700626720fffe18861c 03 40 00 00     wlo1
````
Is a good starting point

**Comment by blaxxton** [comment]
I think it is a good idea to disable ipv6 since ipv4 is always availablein all environments, even those that has set up ipv6 on their networkbut ipv6 would cause problem for those that has not setup ipv6 in thier environments and add extra steps to disable ipv6 to be able to recover.
I don't think there is any environment totally on ipv6 and no ipv4.
If yes, then it is a good idea to have it in config file.
Thanks

**Comment by blaxxton** [comment]
One more note:
We don't want to disable ipv6 at kernel level or even we don't want to disable loading ipv6since there might be some interdepency between modules.
So we decided to disable ipv6 only in /etc/sysctl.conf and /etc/sysconfig/network.
I checked the script /usr/share/rear/rescue/GNU/Linux/26_collect_initrd_modules.sh and all it does copying the current initrd and initrmfs along with modules but these are still having ipv6 enabled.
It is best to recreate the initramfs while disabling ipv6 and then copy it over:dracut --omit-drivers ipv6 /tmp/initramfs-$(uname -r).img $(uname -r)
so if there is a directive in config file, initramfs will be recreated and then copies overand if there is no directive initramfs directly copies over with no change.

Thanks

**Comment by schlomo** [comment]
IMHO ReaR should faithfully copy what you did on your source system. If you
disabled IPv6 in sysctl.conf then we should just copy that.

A quick look reveals that sysctl is not handled by ReaR whatsoever. Maybe
we should just add a "copy all sysctl.conf stuff over and activate it on
boot" feature to solve your problem.

**Comment by gdha** [comment]
@blaxxton perhaps you give it a try with development version rear-1.17.2-git201601052030?

**Comment by blaxxton** [comment]
I am going to try it tomorrow, will let you know the result soon.

**Comment by blaxxton** [comment]
Can you please provide the link to download rear-1.17.2-git201601052030 ?
Thanks

**Comment by gdha** [comment]
See page http://relax-and-recover.org/download/ and select a snapshot version according your distro and go deeper into x86_64 directory.

**Comment by blaxxton** [comment]
My test server is RedHat 6, but there is no x86_64 on snapshot version.
downloaded from i686:

Index of /repositories/Archiving:/Backup:/Rear:/Snapshot/RedHat_RHEL-6/i686

|   |
|   |  |   |   |   |   |   |
| Index of /repositories/Archiving:/Backup:/Rear:/Snapsho...Index of /repositories/Archiving:/Backup:/Rear:/Snapshot/RedHat_RHEL-6/i686 Name Last modified Size  |
|  |
| View on download.opensuse.org | Preview by Yahoo |
|  |
|   |


rear-1.17.2-115.git201601052030.el6.i686.rpm


 Is this ok ?

**Comment by gdha** [comment]
@blaxxton yes that is ok

**Comment by blaxxton** [comment]
I just tried rear-1.17.2-118.git201601091610.el6.i686.rpm
and it fails right at the beginning :
2016-01-11 17:03:30.248917438 ERROR: The savefs command could not retrieve the "save sets" from this client=== Stack trace ===Trace 0: /usr/sbin/rear:410 mainTrace 1: /usr/share/rear/lib/mkrescue-workflow.sh:29 WORKFLOW_mkrescueTrace 2: /usr/share/rear/lib/framework-functions.sh:85 SourceStageTrace 3: /usr/share/rear/lib/framework-functions.sh:45 SourceTrace 4: /usr/share/rear/rescue/NSR/default/47_safe_filesystems.sh:3 sourceMessage: The savefs command could not retrieve the "save sets" from this client===================

or later error:2016-01-11 17:18:31.334417502 Saving result files with NSR (EMC NetWorker)2016-01-11 17:18:31.661689735 Saving files '/var/lib/rear/output/rear-clientname.iso' with save98519:save: Unable to setup direct save with server nsr_server: no matching IP interface data domain devices for save of client `clientname'; check storage nodes, devices or pools.90018:save: Cannot open a save session with NetWorker server 'nsr_server': no matching IP interface data domain devices for save of client `clientname'; check storage nodes, devices or pools2016-01-11 17:18:32.331632992 ERROR: Could not save result files with save=== Stack trace ===Trace 0: /usr/sbin/rear:410 mainTrace 1: /usr/share/rear/lib/mkrescue-workflow.sh:35 WORKFLOW_mkrescueTrace 2: /usr/share/rear/lib/framework-functions.sh:85 SourceStageTrace 3: /usr/share/rear/lib/framework-functions.sh:45 SourceTrace 4: /usr/share/rear/output/NSR/default/95_nsr_save_result_files.sh:55 sourceTrace 5: /usr/share/rear/lib/_input-output-functions.sh:150 StopIfErrorMessage: Could not save result files with save===================2016-01-11 17:18:32.335602303 Running exit tasks.
works fine with older version.
Thanks

**Comment by gdha** [comment]
@blaxxton could you check the `/var/lib/rear/recovery/` directory to find out if the necessary `nsr_*` files were properly created? The NSR scripts were not modified in the last month, so I don't get it.

**Comment by blaxxton** [comment]
Yes, files have been created:
ls -latr /tmp/rear.CztH5P9ZiI8iI4L/rootfs/var/lib/rear/recoverytotal 40drwxr-xr-x 5 root root 4096 Jan  9 20:22 ../-rw-r--r-- 1 root root  143 Jan 12 08:36 mountpoint_permissions-rw-r--r-- 1 root root  665 Jan 12 08:36 diskbyid_mappings-rw-r--r-- 1 root root    5 Jan 12 08:36 bootloader-rw-r--r-- 1 root root  112 Jan 12 08:36 mountpoint_device-rw-r--r-- 1 root root   91 Jan 12 08:36 storage_drivers-rw-r--r-- 1 root root   11 Jan 12 08:36 nsr_server-rw-r--r-- 1 root root 2997 Jan 12 08:36 initrd_modules-r--r--r-- 1 root root    0 Jan 12 08:36 if_inet6drwxr-xr-x 2 root root 4096 Jan 12 08:36 ./-rw-r--r-- 1 root root   24 Jan 12 08:36 nsr_paths
ls -la /var/lib/rear/recoverytotal 40drwxr-xr-x 2 root root 4096 Jan 12 08:36 ./drwxr-xr-x 5 root root 4096 Jan  9 20:22 ../-rw-r--r-- 1 root root    5 Jan 12 08:36 bootloader-rw-r--r-- 1 root root  665 Jan 12 08:36 diskbyid_mappings-r--r--r-- 1 root root    0 Jan 12 08:36 if_inet6-rw-r--r-- 1 root root 2997 Jan 12 08:36 initrd_modules-rw-r--r-- 1 root root  112 Jan 12 08:36 mountpoint_device-rw-r--r-- 1 root root  143 Jan 12 08:36 mountpoint_permissions-rw-r--r-- 1 root root   24 Jan 12 08:36 nsr_paths-rw-r--r-- 1 root root   11 Jan 12 08:36 nsr_server-rw-r--r-- 1 root root   91 Jan 12 08:36 storage_drivers

What I noticed, if_inet6 is with size of 0 either with older version or the current one.
and ipv6 is in initrd_modules on both old and new version.
On new version I have some additional pv-uuid in diskbyid_mappings  but not sure if it is related.
lvm-pv-uuid-53T30q-AsBm-ATpW-5Y2s-AF8r-Yrpt-3xiLdJ sda3lvm-pv-uuid-r2Fd4w-mb2q-9KFp-FAVR-l1dp-Mk29-SQsA6M sda2lvm-pv-uuid-yVs0X8-rrpT-1OdI-rJUC-haan-lSvM-yin7Y6 sdb

The actual error is complaining about:
no matching IP interface data domain devices for save of client Client_Name check storage nodes, devices or pools.

but old version can do the backup with no problem.
What change you made in new version to fix the ipv6 ?
Thanks

**Comment by gdha** [comment]
@blaxxton Did you still had an IPv6 address after you booted from the rescue image?
In rescue image you will find a new script `/etc/scripts/system-setup.d/65-sysctl.sh` that read the `/etc/sysctl*.conf` files.
Furthermore, did you check the content of `/var/lib/rear/recovery/nsr_server` and `/var/lib/rear/recovery/nsr_paths`?

**Comment by blaxxton** [comment]
Still ipv6 there.

I think becuase 65-sysctl.sh only including /etc/sysctl.d/*.conf and missing including /etc/sysctl.conf.

# run sysctl /etc/sysctl.conf and /etc/sysctl.d/*.conf files
for file in /etc/sysctl.d/*.conf ; do
    test -f "$file" && sysctl -e -p "$file" >/dev/null 2>&1
done
test -f /etc/sysctl.conf && sysctl -e -p /etc/sysctl.conf >/dev/null 2>&1


 
nsr_server and nsr_paths seems to be ok and contain the server name and file systems are being backed up.
Thanks




________________________________

**Comment by gdha** [comment]
@blaxxton did you re-run your tests with the latest modifications? In rescue mode you could run ` sysctl -a|grep ipv6` to verify the status of IPv6.
On the other hand, the link https://wiki.archlinux.org/index.php/IPv6#Disable_IPv6 contains some useful information of parameters that can be added to `KERNEL_CMDLINE` (in `/etc/rear/local.conf`)

**Comment by blaxxton** [comment]
Ok, thanks, the scripts is fixed and now it can read /etc/sysctl.conf, but still there is ipv6 address assigned after booting from ISO.

Booted from ISO and sysctl -a | grep -i ipv6 | grep disable shows that ipv6 is enabled.
65-sysctl.sh was not executable, so I did chmod 755 65-sysctl.sh and then ran ./65-sysctl.sh
now ipv6 is gone.

Some how 65-sysctl.sh script is not being executed at boot time.

Can you please check why this script is not being called or executed when we boot from ISO ?

Thanks

**Comment by blaxxton** [comment]
Can we disable backing up the ISO file in NSR ?We run rear mkrescue to create the ISO to boot from but at the end it backup the ISO file as well.
We already backing up the server every night, and finding the correct default backup pool is not always accurateso why not disabling the backup of ISO at the time of creation, and only save it locally in disksince we are going to back it up at night.
Can this be done ?
The other question is:Consider we run daily rear mkrescue , and server crashes today but we find out the best recover time is last week and not today, how at recover time and after booting from ISO  I can specify specific date to recover ?
Thanks

**Comment by gdha** [comment]
@blaxxton _Can we disable backing up the ISO file in NSR ?_
Would prefer to see this in another issue as otherwise it is getting a mess...

**Comment by gdha** [comment]
@blaxxton _Some how 65-sysctl.sh script is not being executed at boot time._
_Can you please check why this script is not being called or executed when we boot from ISO ?_
I am sorry I wouldn't know how I can see why it is not called in your environment? You are asking too much of me. For remote assistance see http://it3.be/rear-support/

**Comment by gdha** [comment]
@blaxxton I've tested the `65-sysctl.sh` script and it worked fine. Ipv6 was disabled.

**Comment by gdha** [comment]
If no-one objects I'll mark it as fixed

**Comment by blaxxton** [comment]
Hi
I wanted to thank you for all your help.
Thanks
