### ISSUE TITLE
Suppress or mask log message that shows the decrypting key on console during recover

### ISSUE THREAD

**Issue by pexus** [rear/rear#749]
When using rear recover with a decrypting key, I did notice that during the recovery process, I see the following on the console that displays the decrypting archive key. Can this be disabled or masked. Showing the decrypting key is not a best practice from security stand point.

"Decrypting archive with key: XXXXXX"

**Comment by pexus** [comment]
Version used was  :  Debian  8 -  1.17.2

**Comment by gdha** [comment]
Could you some me the `local.conf` file (mask the key of course)?

**Comment by pexus** [comment]
Sorry for the delay. I will work on posting the local.conf soon.

**Comment by pexus** [comment]
Here is the local.conf that I am using.
-----------------------------------------------------
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
### write the rescue initramfs to USB and update the USB bootloader
OUTPUT=USB

### create a backup using the internal NETFS method, using 'tar'
BACKUP=NETFS

### write both rescue image and backup to the device labeled REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
BACKUP_PROG_CRYPT_ENABLED=1
BACKUP_PROG_CRYPT_KEY="XXXXXXXXXXXXXXXXXX"
BACKUP_PROG_CRYPT_OPTIONS="/usr/bin/openssl aes-256-cbc -salt -k "
BACKUP_PROG_DECRYPT_OPTIONS="/usr/bin/openssl aes-256-cbc -d -k "
BACKUP_PROG_EXCLUDE=( '/tmp/*' '/mnt/*' '/var/tmp/ppsconfig/mnt/*' '/dev/shm/*' $VAR_DIR/output/\* )

**Comment by pexus** [comment]
Here is the local.conf I am using.
----

OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
BACKUP_PROG_CRYPT_ENABLED=1
BACKUP_PROG_CRYPT_KEY="XXXXXX"
BACKUP_PROG_CRYPT_OPTIONS="/usr/bin/openssl aes-256-cbc -salt -k "
BACKUP_PROG_DECRYPT_OPTIONS="/usr/bin/openssl aes-256-cbc -d -k "
BACKUP_PROG_EXCLUDE=( '/tmp/*' '/mnt/*' '/var/tmp/ppsconfig/mnt/*' '/dev/shm/*' $VAR_DIR/output/\* )
