### ISSUE TITLE
BACKUP_URL=cifs:// does not work because it uses noatime option

### ISSUE THREAD

**Issue by DamienGombaultRecia** [rear/rear#752]
Hi.

I try to use BACKUP_URL=cifs:// but it fails because noatime option does not exist for cifs protocol.
Tested with CentOS 7.2 (up to date).
````
ERROR: Mount command 'mount -v -o rw,noatime,guest //xxx/xxx/tmp /tmp/rear.Q89mvOdrDdmhh0F/outputfs' failed.
Aborting due to an error, check /var/log/rear/rear-localhost.log for details
````
In /var/log/message :
````
Jan  8 12:10:12 localhost kernel: CIFS: Unknown mount option "noatime"
Jan  8 12:10:12 localhost rear[20257]: ERROR: Mount command 'mount -v -o rw,noatime,guest //xxx/xxx/tmp /tmp/rear.Q89mvOdrDdmhh0F/outputfs' failed.
````
`noatime` is set in file :
lib/global-functions.sh:108:    local defaultoptions="rw,noatime"

noatime should not be used with CIFS protocol.

**Comment by gdha** [comment]
You should define (see man page of rear):
````
       BACKUP_URL=cifs://
           To backup to a Samba share (CIFS), use BACKUP_URL=cifs://cifs-server-name/share/path. To provide
           credentials for CIFS mounting use a /etc/rear/.cifs credentials file and define
           BACKUP_OPTIONS="cred=/etc/rear/.cifs" and pass along:

               username=_username_
               password=_secret password_
               domain=_domain_
````

You got that error, because of the *guest* if-section in `lib/global-functions.sh`. If you would leave the noatime away you would have an issue with permissions.

**Comment by DamienGombaultRecia** [comment]
If I manually mount my (anonymous) CIFS mountpoint with
`mount -v -o rw,noatime,guest //xxx/xxx/tmp /mnt`
It works

**Comment by gdha** [comment]
@DamienGombaultRecia And you want to mount as guest on purpose?

**Comment by DamienGombaultRecia** [comment]
Yes, I mount it on purpose.
I will test with a login/password protected CIFS mount points.
But I think to noatime option will cause the same problem.

**Comment by gdha** [comment]
@DamienGombaultRecia If you use `BACKUP_OPTIONS` then you won't be using `noatime` option unless you add it in there.
However, I agree with you about `noatime` option: it doesn't seem to be a valid option for cifs (anymore?).

**Comment by DamienGombaultRecia** [comment]
I have set BACKUP_OPTIONS="guest" and it works, thank you (I thought BACKUP_OPTIONS was appended to defaultoptions (not replaced)).
However I think the noatime should be be used as a default at least for CIFS.

**Comment by gdha** [comment]
@DamienGombaultRecia You said "However I think the noatime should be be used as a default at least for CIFS" - is this correct? I thought **not** would be better?

**Comment by DamienGombaultRecia** [comment]
I fixed my comment.
