### ISSUE TITLE
Business Case: Backup operation verification with rear

### ISSUE THREAD

**Issue by yin747** [rear/rear#756]
After system backup completed, is there any effective way (ie: checking $?, enabling some rear's option, checking log files) to verify the backup operation as successful or failure?

**Comment by gdha** [comment]
@yin747 there will always be a line added to the syslog or messages file. Of course, the rear.log is also an excellent place to look in. You can even mail the rear.log automatically it if you define RESULT_MAILTO and RESULT_MAILSUBJECT in `/etc/rear/local.conf`
