### ISSUE TITLE
diskrestore.sh has not been changed, restarting has no impact

### ISSUE THREAD

**Issue by noahshines** [rear/rear#759]
![rear_issue_1](https://cloud.githubusercontent.com/assets/15383832/12518808/bc8f8adc-c108-11e5-88fe-5ac3eca9738d.PNG)

I tried to rerun the diskrestore.sh file but to no avail. Running OEL 5.5, REAR 1.17.2.  

please help as the server wont boot up without the REAR image.

**Comment by gdha** [comment]
I think the first line says it all **diskrestore.sh has not been changed**. Select first option 4 to edit the script and thereafter you can re-run it again.

**Comment by noahshines** [comment]
I am sorry..but what exactly do I edit in diskrestore.sh? 
I mean what anomalies do i need to look for?

**Comment by gdha** [comment]
As a starter have a look at https://github.com/rear/rear/blob/master/doc/user-guide/06-layout-configuration.adoc

**Comment by noahshines** [comment]
Thank you!. You may close the case now. The document pretty much helped me.
