### ISSUE TITLE
REAR with TSM

### ISSUE THREAD

**Issue by mperry999** [rear/rear#760]
When doing a "rear -v mkbackup" with TSM fails to remove /tmp/rear.BkNgkF9eCJMxzl2 because "Directory not empty". When looking in the /tmp/rear.BkNgkF9eCJMxzl2 directory the following exist : /opt/tivoli/tsm/client/api/bin/libApiDS.so, /opt/tivoli/tsm/client/api/bin/libxerces-c1_6_0.so and /opt/tivoli/tsm/client/api/bin/libxmlutil-5.5.3.0.so.

Is there a fix for this in newer release.

**Comment by gdha** [comment]
@mperry999 could you paste the output of `ls -l` of this directory?

**Comment by mperry999** [comment]
# ls -l
total 6164
-r-xrwxr-x+ 1 root root 3480944 Feb 20  2012 libApiDS.so
-r-xrwxr-x+ 1 root root 2676675 Feb 20  2012 libxerces-c1_6_0.so
-r-xrwxr-x+ 1 root root  125897 Feb 20  2012 libxmlutil-5.5.3.0.so
