### ISSUE TITLE
REAR TSM Management Class / Naming Request / Scheduling ?

### ISSUE THREAD

**Issue by mperry999** [rear/rear#761]
How do you set TSM Management class to backup REAR ISO Files ?

Can you name TSM REAR ISO files with Date / Time in the name? ( Example: rear-server123-20160204-101600.iso )

The reason I ask this is because our default TSM management class is 3 copies over 2 months. 

Should we be running "rear -v mkbackup" everyday so we can recover a server the from the night before?

**Comment by gdha** [comment]
You could redefine the `ISO_PREFIX="rear-$HOSTNAME"` in the local.conf file if you like.
However, if you are using TSM there is no need to create an ISO image every day. Unless you would like to avoid automatic removals within TSM (retention days).

**Comment by mperry999** [comment]
If I run TSM REAR ISO backups less frequently, lets say weekly on a Sunday, but the server breaks after that TSM REAR ISO backup, lets say the following Wednesday, can I recover the night before's Tuesday server using the TSM REAR ISO from the previous Sunday? ( Can I recover based on dates even though the TSM REAR ISO may not have been created on a certain date ? )

Another concern I have is if disks are added or removed or if networking has changed on a server after the TSM REAR ISO weekly was created. Can I still use the TSM REAR ISO to recover the system?

**Comment by gdha** [comment]
@mperry999 rear ISO rescue image does *not* contain any backup. Restore is always done via TSM.
