### ISSUE TITLE
SLES 10 REAR ISO Recovery

### ISSUE THREAD

**Issue by mperry999** [rear/rear#768]
Noticed there is a rear 1.17.x for SLES 10 but there was a mention that SLES 10 was not longer supported. Which version should we be using for SLES 10 recoveries?

http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/SLE_10_SDK/noarch/

Does the REAR ISO rescue image support the ability to recover image when recovering on different hardware? ( Example : Created REAR ISO image on SUN hardware but then try to restore on HP Blade? - network drivers different - will REAR ISO have drivers for HP even if image was created with SUN hardware )

**Comment by jsmeix** [comment]
From SUSE there is no official support for rear on SLE10.
SUSE supports rear on SLE11-HAE and SLE12-HAE
(i.e. not on plain SLE but only via the HA extension).

Regarding support from Relax-and-Recover upstream see
http://relax-and-recover.org/support/

In general regarding rear and in particular regarding
"different hardware" see
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
In genertl the rear recovery system on the ISO is specific
for each particular system where it was created.

In general there is currently no such thing as a
generic "full featured" rear recovery system
(that should boot and run on basically any hardware).

Regarding the future about this you may have a look at
https://github.com/rear/rear/issues/732
and at the section "Using rear as generic installer in any installation system" in https://en.opensuse.org/SDB:Disaster_Recovery
