### ISSUE TITLE
agetty: cannot open os-release file

### ISSUE THREAD

**Issue by gdha** [rear/rear#778]
with a fedora 23 rescue image noticed the following line in the messages file:
`agetty: cannot open os-release file`

The /etc/os-release seems to be linked to ../usr/lib/os-release on Fedora 23 and therefore, the copy probably did not succeed.

**Comment by phracek** [comment]
Yeah, that's correct.

~~~
$ ls -la /etc/os-release 
lrwxrwxrwx. 1 root root 21 Oct 20 00:35 /etc/os-release -> ../usr/lib/os-release
$ 
~~~

**Comment by gdha** [comment]
Has been fixed with commit https://github.com/rear/rear/commit/22a7337edb41b9fb053f497f846ff2651a2b8845
