### ISSUE TITLE
NVMe/M.2 SSD // LUKS // diskrestore ... 

### ISSUE THREAD

**Issue by GIT-STATA** [rear/rear#787]
* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a): OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

  OUTPUT=USB
  OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
  BACKUP=NETFS
  BACKUP_TYPE=full
  BACKUP_PROG=rsync
  BACKUP_URL=usb:///dev/disk/by-label/REAR-000
  AUTOEXCLUDE_DISKS=y

# Brief description of the issue

1.
2016-02-27 18:48:19 Comparing disks.
2016-02-27 18:48:19 Disk configuration is identical, proceeding with restore.
2016-02-27 18:48:19 No code has been generated to restore device pv:/dev/mapper/luks-40c4eca5-5b90-48aa-b46b-141cb2574452 (lvmdev).
    Please add code to /var/lib/rear/layout/diskrestore.sh to manually install it or choose abort.
**BUT** 
The disk configuration is absolutely not identical – SSD was formatted with fat32 – No partitions left on the NVMe. I can continue the process. In the end It will say 
'2016-02-27 18:48:25 Disk layout created.'... BUT the disklayout hasn't changed anyway! 

**The diskrestore/disklayout 'resetting' does not function at all on the NVMe hard drive. **

2.
I even tried to replace the NVMe Drive with a Samsung SSD 850 Pro and tried to restore the system on that SSD. 'The disklayout was not restored'. 

3.
The diskrestore.sh is empty – beside the fact the disklayout.conf look great. **Why is that?**
It would be great to get this issue resolved! 

**Thanks  to everybody!!!**

P.S. 
I attached disklayout.conf and rear-localhost.log 

[disklayout.txt](https://github.com/rear/rear/files/151450/disklayout.txt)
[rear-localhost-layout.txt](https://github.com/rear/rear/files/151451/rear-localhost-layout.txt)

**Comment by gdha** [comment]
Device `/dev/nvme0n1` is strange and is not recognized by rear it seems as there is no disk definition found in `disklayout.conf`. Perhaps, it would be nice to see the debug out of `rear -vd savelayout` which produces the `disklayout.conf` file.

**Comment by GIT-STATA** [comment]
Hi, 

**thanks for responding that nice and quick!** 
I attached the rear -vd savelayout OUTPUT. 

Again, thanks a lot!!! 

P.S. 

- rear
  -vd savelayout
  [savelayout.txt](https://github.com/rear/rear/files/152736/savelayout.txt)

**Comment by gdha** [comment]
@GIT-STATA sorry, my mistake I meant `rear -vD savelayout` (captital D to capture debugging)

**Comment by GIT-STATA** [comment]
No problem at all! 
Thanks a lot! 

*rear -vD savelayout*
-
[savelayout-vD.txt](https://github.com/rear/rear/files/152771/savelayout-vD.txt)

**Comment by gdha** [comment]
Ok I understand the issue now - according https://communities.intel.com/community/itpeernetwork/blog/2014/10/10/finding-your-new-intel-ssd-for-pcie-think-nvme-not-scsi it is not a scsi device and currently rear does not recognize it.
Script `20_partition_layout.sh` must be extended with this type disk.

**Comment by GIT-STATA** [comment]
Hi gdha,

thank you very much for your response. I guess, it must be this part of the script, which needed to be 'revised' 


>  Script 20_partition_layout.sh must be extended with this type disk.<

    for path in "${sysfs_paths[@]}" ; do
        ### path can be: /sys/block/sda/sda1 --> /dev/sda1
        ###              /sys/block/dm-4 --> /dev/mapper/mpathbp1

But still I have no clue what exactly to revise. 
Any Code would be so great! I would test it, of course... 


P.S. 
Maybe that is needed?

ls -la /sys/block/
[block.txt](https://github.com/rear/rear/files/161099/block.txt)

ls -la /sys/block/nvme0n1/
[nvme.txt](https://github.com/rear/rear/files/161103/nvme.txt)

Thanks again!

**Comment by gdha** [comment]
@GIT-STATA Just pushed a new version of 20_partition_layout.sh - pls give it a try

**Comment by GIT-STATA** [comment]
Hi, 

unfortunately it does not work.... 

**Partition is numbered '\'''\''. More than 128 partitions is not supported.'
Message: Partition  is numbered ''. More than 128 partitions is not supported.**

Here is rear -vD ... 
[rear-localhost-vD.txt](https://github.com/rear/rear/files/161304/rear-localhost-vD.txt)

Many thanks!

**Comment by gdha** [comment]
@GIT-STATA could you post `/var/lib/rear/layout/disklayout.conf`? I think we are on the right track, but noet completely finished yet.

**Comment by GIT-STATA** [comment]
Hi, 

sure! 

Here we go (disklayout.conf with NVMe SSD)
[disklayout-nvme.txt](https://github.com/rear/rear/files/161327/disklayout-nvme.txt)

Thanks!

**Comment by gdha** [comment]
In the disklayout.conf I noticed the start of the partition is missing:
````
# Format: part <device> <partition size(bytes)> <partition start(bytes)> <partition type|name> <flags> /dev/<partition>
part /dev/nvme0n1 524288000 primary boot  /dev/nvme0n1p1
part /dev/nvme0n1 255534825472 primary none  /dev/nvme0n1p2
`````
Could you run a debug session of savelayout once more?

**Comment by GIT-STATA** [comment]
Hi, 

of course... 
**Here we go... rear -vD savelayout**
[savelayout-vD.txt](https://github.com/rear/rear/files/161353/savelayout-vD.txt)

**Comment by gdha** [comment]
@GIT-STATA What does `cat /sys/block/nvme0n1/nvme0n1p1/start` return?

**Comment by GIT-STATA** [comment]
Hi, 

> cat /sys/block/nvme0n1/nvme0n1p1/start  

returns 
**2048**

**Comment by GIT-STATA** [comment]
Hi gdha, 

any new ideas o that issue? 
Thanks a lot!

**Comment by gdha** [comment]
Script `/usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh` calls:
````
+++ local nr_blocks=1024000
+++ local disk_size=524288000
+++ echo 524288000
++ size=524288000
+++ get_partition_start nvme0n1/nvme0n1p1
/usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh: line 64: get_partition_start: command not found
++ start=
++ echo '1 524288000 '
````
At this moment I have no clue why it doesn't find the function `get_partition_start` as it is defined  in `layout-functions.sh:get_partition_start()`
Next week we might have a smarter idea?

**Comment by GIT-STATA** [comment]
Hi, 

yes, lets see next week! 
**BUT**
get_partition_start() **is not called in** /usr/share/rear/lib/**layout-functions.sh**
I can't find it there! 

Thanks!

**Comment by gdha** [comment]
@GIT-STATA Could you remove rear and re-install it once to double check this? It must be there (in layout-functions.sh)

**Comment by GIT-STATA** [comment]
The **official stable releases from EPEL does not work**! 
After I used the **Relax-and-Recover sources from Github** and build the rpm package, I can now confirm that ReaR is working great! I have tested different scenarios and everything worked as it should! NVMe is now supported (from my point of view!)

**THANKS A LOT !!!gdha!!!**

**Comment by gdha** [comment]
I know it is time to make a new release!
