### ISSUE TITLE
On CentOs 7.2, backup seems successful but nothing is copied to NFS share

### ISSUE THREAD

**Issue by bobbysch** [rear/rear#789]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a): 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://10.2.209.220/HOU_Linuxbackups/linuxbackups"
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '*.trc' '*.trm' '/var/lib/libvirt/images/*' )
COPY_AS_IS_EXCLUDE=( ${COPY_AS_IS_EXCLUDE[@]} '*.trc' '*.trm' '/var/lib/libvirt/images/*' )
EXCLUDE_MOUNTPOINTS=( ${EXCLUDE_MOUNTPOINTS[@]} /exports )
AUTOEXCLUDE_PATH=( ${AUTOEXCLUDE_PATH[@]} /mnt* /var/lib/kvm/images )
BACKUP_PROG=tar
BACKUP_OPTIONS="nfsvers=3,nolock"

* Brief description of the issue:
rear -v mkbackup went successfully but nothing is copied to NFS share.

[rear-houdocker01.zip](https://github.com/rear/rear/files/153455/rear-houdocker01.zip)
 
* Work-around, if any:
When trying to use -S option with rear, I could see the size of the archive getting bigger and bigger, but in the end nothing remained!
Note that I tried with and without BACKUP_OPTIONS="nfsvers=3,nolock", same result.

**Comment by gdha** [comment]
In the log file I saw:
`2016-03-01 14:14:09 Command line options: /sbin/rear -v mkrescue` ??

**Comment by bobbysch** [comment]
i was tired! Sorry and thanks much.
