### ISSUE TITLE
99_sysreqs.sh: fix or implement remaining issues

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#798]
This issue is intended as follow-up of https://github.com/rear/rear/issues/795

In particular the root partition size is missing, cf.
https://github.com/rear/rear/issues/795#issuecomment-195425857

**Comment by jsmeix** [comment]
@gdha 
see my initail "FIXME" in 99_sysreqs.sh
<pre>
# FIXME: Provide a leading comment what this script is about.
</pre>

Can you provide me some explanatory information what
the purpose of this script is.

I see at its end that it outputs text to
$VAR_DIR/sysreqs/Minimal_System_Requirements.txt
but I have no idea what it is good for.

Is it just mean as textual information or is the content of
$VAR_DIR/sysreqs/Minimal_System_Requirements.txt
used by other scripts?

I cannot find the hardcoded file name "Minimal_System_Requirements"
nor can I find e.g. "TOTMEM" is any other script so that I wonder
what the purpose of 99_sysreqs.sh is.

**Comment by gdha** [comment]
@jsmeix Updated the script to make more sense on all Linux distro's. If you could review the end result? The `/var/lib/rear/sysreqs/Minimal_System_Requirements.txt` file is **not** used by rear in *recover* mode. The purpose is to have an idea in a remote DRP center what are the minimal physical requirements of a system to  foresee to perform a successful  recovery from the rear image provided.

**Comment by jsmeix** [comment]
@gdha 
many thanks for your nice clenaup of 99_sysreqs.sh.

Its resulting var/lib/rear/sysreqs/Minimal_System_Requirements.txt
looks good on my system.

With your clenaup of 99_sysreqs.sh this issue here
is sufficiently fixed from my point of view.
