### ISSUE TITLE
REAR 1.17 and NSR with RHEL 6.7

### ISSUE THREAD

**Issue by pmkri15** [rear/rear#803]
rear-1.17.2-1.el6.x86_64 (Relax-and-Recover 1.17.2 / Git)
lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-       4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release:        6.7
Codename:       Santiago

local.conf
OUTPUT=ISO
BACKUP=NSR
GRUB_RESCUE=y

Backing up RHEL VMGuest using EMC NSR (lgtoclnt-8.2.1-1.x86_64)
Successful can backup and restore over NFS but unfortunately that will not be possible for production systems)
So I am backing up with EMC Networker and using rear to get a DR image
Create ISO image
boot off ISO image
perform rear recover
reboot
boot fails with the following:
init:tty(/dev/tty6) main process (1068) terminated with status 127
init:tty(/dev/tty6) main process ended, respawning
.....until I get
init:tty (/dev/tty6) respawning too fast, stopped  
and it doesn't boot
Open to suggestions - thanks

**Comment by gozora** [comment]
Hi,
Looks like /dev/tty6 is missing or corrupted.
My best shot would be to boot system from RH rescue disk (or ReaR iso), mount / (root) and comment out tty6 edit **/etc/inittab.**
Something like:

```
1:2345:respawn:/sbin/mingetty --noclear tty1
2:2345:respawn:/sbin/mingetty tty2
3:2345:respawn:/sbin/mingetty tty3
4:2345:respawn:/sbin/mingetty tty4
5:2345:respawn:/sbin/mingetty tty5
#6:2345:respawn:/sbin/mingetty tty6
```

and tty boot again ...

**Comment by gdha** [comment]
Did selinux relabeling kick in? Might be that what is causing this...

**Comment by pmkri15** [comment]
Booted using the ISO mounted the root partition 
cd /etc/sysconfig
editted selinux and changed SELINUX from enforcing to permissive 
umounted root partition
reboot was successful
So as a test I set SELINUX back to enforcing and rebooted - same errors so I reset to permissive
Thanks for quick responses
