### ISSUE TITLE
Use 'ebiso' automatically as needed

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#805]
On openSUSE and SLE rear >= 1.18 plus 'ebiso' must be used
to make the rear recovery system ISO image bootable on UEFI.

With rear 1.18 one must explicitly specify in /etc/rear/local.conf
that 'ebiso' is used to make the ISO image - otherwise it fails (cf. https://github.com/rear/rear/issues/804 and https://github.com/rear/rear/issues/801).

This issue here is an enhancement request to automate it in a future
rear version to use ebiso `if is_true $USING_UEFI_BOOTLOADER` (cf. https://github.com/rear/rear/issues/801).

**Comment by gdha** [comment]
@jsmeix Does the latest SLES (or OpenSuSE) fixed the `genisoimage` rpm to boot from on UEFI, or is `ebiso` still a requirement?

**Comment by jsmeix** [comment]
As far as I know ebiso is still a requirement.

Furthermore I would prefer ebiso over genisoimage
because ebiso is known to work in practice and
I even know the one who makes ebiso personally
and I know he makes it "just work" (in contrast to
the genisoimage uncertainity at SUSE/openSUSE).

@gozora 
again many thanks for your relatively simple,
straightforward, and "just working" ebiso!

**Comment by gdha** [comment]
@jsmeix is the above statement still true? ebiso of @gozora was/is a blessing for SLES for sure, but it seems incredible that SLES does not fixes this in their base OS.

**Comment by jsmeix** [comment]
No idea if something meanwhile changed
and no time for investigation
cf. https://github.com/rear/rear/issues/799#issuecomment-531247109
so I just close it as can'tfix to get it out of sight.
