### ISSUE TITLE
ISO image not booting on IBM Power 8 / SLES 11.4

### ISSUE THREAD

**Issue by arielrolfo** [rear/rear#817]
- rear version (/usr/sbin/rear -V): Relax-and-Recover 1.18 / Git
- OS version (cat /etc/rear/os.conf or lsb_release  -a):
  LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64:desktop-4.0-noarch:desktop-4.0-ppc32:desktop-4.0-ppc64:graphics-2.0-noarch:graphics-2.0-ppc32:graphics-2.0-ppc64:graphics-3.2-noarch:graphics-3.2-ppc32:graphics-3.2-ppc64:graphics-4.0-noarch:graphics-4.0-ppc32:graphics-4.0-ppc64
  Distributor ID: SUSE LINUX
  Description:    SUSE Linux Enterprise Server 11 (ppc64)
  Release:        11
  Codename:       n/a
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
  OUTPUT=ISO
  BACKUP=NETFS
  BACKUP_URL=nfs://nimp8/export/images
  BACKUP_OPTIONS="nfsvers=3,nolock"
  NETFS_KEEP_OLD_BACKUP_COPY=yes
  BACKUP_PROG_INCLUDE=( '/' )
  BACKUP_PROG_EXCLUDE=( '/tmp/' '/dev/shm/' '/var/lib/rear/output/' '/media/' '/hana/' )
  BOOT_FROM_SAN=y
  AUTOEXCLUDE_MULTIPATH=n
- Brief description of the issue:
  I have done a backup via "rear -v mkbackup" and it went successfully but later on when I tried to boot from the .iso generated (55MB) I've got "no operating system installed" message.  The .iso file is fine apparently, I was able to mount it and there are two files in there:
  -rw-r--r-- 1 root system 35967339 Apr 09 05:00 initrd.cgz
  -rw-r--r-- 1 root system 20806910 Jun 24 2015 kernel

**Comment by arielrolfo** [comment]
One lead... from rear.log file I've got:
...
...
+ source /usr/share/rear/conf/Linux-ppc64.conf
....


that file has:
...
...
COPY_AS_IS=(
"${COPY_AS_IS[@]}"
/usr/lib/yaboot/yaboot
/usr/lib/yaboot/ofboot
/usr/lib/yaboot/yaboot.debug
/usr/lib/yaboot/addnote
)
...
...

But there is no "/usr/lib/yaboot/yaboot" file, instead I see this: "/lib/lilo/pmac/yaboot"

**Comment by arielrolfo** [comment]
well.... momentarily solved by editing "/usr/share/rear/output/ISO/Linux-ppc64/30_create_yaboot.sh" and skip returning if /etc/yaboot.conf doesn't exist, because if it returns it will never hit the last line of that file which injects "etc=etc ppc=ppc" in the iso image creation.

**Comment by jsmeix** [comment]
Can you provide a diff what exactly you changed
in what files so that it is easier and more clear
what you did to make it work for your particular case.

I have basically zero personal knowledge about the PPC architecture
but when I know what exactly you changed in what files
to make it work for your particular case, I could perhaps
derive a generally working solution on my own
or I could show your changes to my colleagues at SUSE
who know about the PPC architecture.

**Comment by arielrolfo** [comment]
hello, see below but it's only a temporary workaround to get over this:

```
# diff 20_install_yaboot.sh 20_install_yaboot-changed.sh
3c3
<   return
---
>   echo return

```
it basically allows the script to continue even when there is no /etc/yaboot.conf file in my system, at the end of this script it places the "ppc" and the "etc" in the iso image, otherwise it was not readable by my P8 system.

I'm not sure what was the rationale behind that "if" at the beginning.

**Comment by jsmeix** [comment]
@k0da 
could you have a look what goes on here.

Many thanks in advance!

**Comment by k0da** [comment]
@jsmeix on SLES yaboot is located at /lib/lilo/chrp/yaboot.chrp

**Comment by jsmeix** [comment]
@k0da 
regarding "on SLES yaboot is located at /lib/lilo/chrp/yaboot.chrp":

In https://github.com/rear/rear/issues/817#issuecomment-207794210 @arielrolfo reported "I see this: /lib/lilo/pmac/yaboot"

The lilo RPM package of SLE-11-SP4 contains both
/lib/lilo/chrp/yaboot.chrp and /lib/lilo/pmac/yaboot
with same size and also "strings" results the same
for both but "diff -s" tells they are different.

I don't know anything about yaboot and the above confuses me.

But it seems rear 1.18 is not yet working well
on PPC architecture on SLE11
at least not when yaboot is used.

**Comment by k0da** [comment]
@jsmeix the one @arielrolfo mentioned is for power mac. On IBM Power systems we need to use chrp one

**Comment by jsmeix** [comment]
@arielrolfo 
in general when files are missing in the rear recovery system
you can specify them in /etc/rear/local.conf via the
COPY_AS_IS and REQUIRED_PROGS array variables
as described in  /usr/share/rear/conf/default.conf
for example like
<pre>
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" additional_program1 additional_program2 )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /path/to/file1 /path/to/file2 )
</pre>
for some real examples have a look at
/usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf

**Comment by arielrolfo** [comment]
@k0da I'm using a Power System E870
@jsmeix I know that already, no issues with that, this is not related to it.

**Comment by arielrolfo** [comment]
@k0da see this pls https://www.debian.org/ports/powerpc/inst/yaboot-howto/ch1.en.html it says _"...Yaboot is a bootloader for PowerPC computers (NewWorld PowerMacs and IBM CHRP)..."_

**Comment by k0da** [comment]
@arielrolfo yes, the sources are the same but binaries are different. Please use chrp one

**Comment by arielrolfo** [comment]
@k0da great, how do I pick that one ?

**Comment by k0da** [comment]
It should come with lilo package
# rpm -ql lilo | grep yaboot.chrp
/lib/lilo/chrp/yaboot.chrp

**Comment by gdha** [comment]
Is there still something need to be done within rear for this issue?

**Comment by arielrolfo** [comment]
Hello, i'm on vacations right now til sep-25.  I'll get back to you then.
Cheers

**Comment by schabrolles** [comment]
@gdha, Please have a look at #1061. 
`/etc/yaboot.conf` is not created when SLES11 is installed with LVM system layout.
This prevent ReaR to recreate bootloader for the DVD and the system restrored.

**Comment by jsmeix** [comment]
@arielrolfo 
if you like to test if current ReaR GitHub master code
(that contains https://github.com/rear/rear/pull/1061)
now works o.k. for you:

How to test the currently newest rear GitHub master code:

Basically "git clone" it into a directory and
then run rear from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# cd rear

# vi etc/rear/local.conf

# usr/sbin/rear -d -D mkbackup
</pre>

**Comment by jsmeix** [comment]
I assume it works because "no news is good news".
