### ISSUE TITLE
Warning message "the system won't boot" at the end of restore is not correct

### ISSUE THREAD

**Issue by arielrolfo** [rear/rear#820]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:
- rear version (/usr/sbin/rear -V): 

Relax-and-Recover 1.18 / Git
- OS version (cat /etc/rear/os.conf or lsb_release  -a):

LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64:desktop-4.0-noarch:desktop-4.0-ppc32:desktop-4.0-ppc64:graphics-2.0-noarch:graphics-2.0-ppc32:graphics-2.0-ppc64:graphics-3.2-noarch:graphics-3.2-ppc32:graphics-3.2-ppc64:graphics-4.0-noarch:graphics-4.0-ppc32:graphics-4.0-ppc64
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (ppc64)
Release:        11
Codename:       n/a
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://nimp8/export/images
BACKUP_OPTIONS="nfsvers=3,nolock"
NETFS_KEEP_OLD_BACKUP_COPY=yes
BACKUP_PROG_INCLUDE=( '/' )
EXCLUDE_VG=('backupvg' 'datavg' 'hanalogvg' 'sharedvg')
BACKUP_PROG_EXCLUDE=( '/tmp/' '/dev/shm/' '/var/lib/rear/output/' '/media/' '/hana/' )
BOOT_FROM_SAN=y
AUTOEXCLUDE_MULTIPATH=n
- Brief description of the issue.
  After recovering my system I've got the message in the attached file but even though I was able to reboot it, I saw that the warning msg is showed if /etc/yaboot.conf file is not present but that is not a valid criteria to assume that there is no bootloader.
  ![no-bootloader-warning](https://cloud.githubusercontent.com/assets/12053180/14460580/a0e4f9f4-0094-11e6-83f3-84b5d0b04e0d.png)
- Work-around, if any

**Comment by gdha** [comment]
@jsmeix Could you take this issue with you as you already have a similar case (issue #817)

**Comment by jsmeix** [comment]
I cannot do much here myself because I have basically
zero personal knowledge about the PPC architecture
(cf. https://github.com/rear/rear/issues/817#issuecomment-208204721)
which means I cannot fix the yaboot related code myself
but I will take this issue at least as a "caretaker".

**Comment by gdha** [comment]
Due to time pressure (for new release) and lack of interest of the community we push this feature forward.

**Comment by schabrolles** [comment]
I had the same problem with a SLES11sp4 installed with LVM layout for the system.
If it is the case here (/boot included in / in a LVM volumegroup), I propose a patch here: #1061

**Comment by gdha** [comment]
@schabrolles Do you think this issue can be closed?

**Comment by schabrolles** [comment]
@gdha, Yes, It can be closed.
