### ISSUE TITLE
No code has been generated to restore device /dev/md0 (raid)

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#822]
Version
Relax-and-Recover 1.17.2 / Git

OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6
This is an IBM Power7 server

-local.conf.
OUTPUT=ISO
OUTPUT_URL=nfs://167.69.63.74/dbar
BACKUP=NETFS
BACKUP_URL=nfs://167.69.63.74/dbar
SSH_ROOT_PASSWORD="redhat"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/waslogs' '/wasdumps')
NETFS_KEEP_OLD_BACKUP_COPY=

Trying to recover a RHEL6 OS on IBM PPC64 P7 hardware using rear.
The OS is configured with software raid /dev/md0 and a second /dev/md1
Getting the following error:
+ source /usr/share/rear/layout/prepare/default/60_show_unprocessed.sh
++ read -u 3 status name type junk
+++ grep '^todo' /var/lib/rear/layout/disktodo.conf
++ LogPrint 'No code has been generated to restore device /dev/md0 (raid).
    Please add code to /var/lib/rear/layout/diskrestore.sh to manually install it or choose abort.'
++ Log 'No code has been generated to restore device /dev/md0 (raid).

**Comment by gdha** [comment]
@John-Leone could give some more background on the disk devices and what does `/var/lib/rear/layout/disklayout.conf` contain?

**Comment by John-Leone** [comment]
Thanks in advance for your help.

Hardware: IBM Power 7
We use two disks the configure software raid 1 to create a /dev/md0 array.
This particular server has two different md devices configured, one for the OS and the second for user data.


RESCUE xlabrhel6:/var/lib/rear/layout # cat disklayout.conf
raid /dev/md0 metadata=1.1 level=raid1 raid-devices=2 uuid=91c89a9a:bbe051ad:63f43b3a:05a9b51f devices=/dev/sda3,/dev/sdc3
raid /dev/md1 metadata=1.2 level=raid1 raid-devices=2 uuid=e9c456a4:04d64135:2212dbc1:9317bf2a devices=/dev/sdb3,/dev/sdd3
lvmdev /dev/uservg /dev/md1 Ow8ov2-GovF-siAx-nhya-2QCW-eG6T-cUd0Lm 1171630080
lvmdev /dev/rootvg /dev/md0 oqYbCq-yc19-3xj0-JnHI-tjFe-HNxd-Ci4on7 1171889912
lvmgrp /dev/uservg 4096 143021 585814016
lvmgrp /dev/rootvg 4096 143052 585940992
lvmvol /dev/uservg u02 12800 104857600
lvmvol /dev/rootvg root 2048 16777216
lvmvol /dev/rootvg swap 2048 16777216
lvmvol /dev/rootvg var 1024 8388608
lvmvol /dev/rootvg opt 2048 16777216
lvmvol /dev/rootvg home 2048 16777216
lvmvol /dev/rootvg midrange 1024 8388608
lvmvol /dev/rootvg tmp 2048 16777216
lvmvol /dev/rootvg origroot 2816 23068672
lvmvol /dev/rootvg origvar 1792 14680064
lvmvol /dev/rootvg u01 10240 83886080
# Filesystems (only ext2,ext3,ext4,vfat,xfs,reiserfs,btrfs are supported).
# Format: fs <device> <mountpoint> <fstype> [uuid=<uuid>] [label=<label>] [<attributes>]
fs /dev/mapper/rootvg-home /home ext4 uuid=1d9c5266-0d88-497d-8322-970c01ab1682 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-midrange /midrange ext4 uuid=07b9c4b5-85eb-4117-8d29-a9feb3e196c0 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-opt /opt ext4 uuid=f23bc089-15f9-48cc-bfdc-383e5a2efa43 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-root / ext4 uuid=40a2053f-4127-41df-8367-fb01059642af label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-tmp /tmp ext4 uuid=2436138d-5505-49af-8de5-7c3a77a315ea label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-u01 /u01 ext4 uuid=e98c2d72-1fd5-475d-abc8-7431f62496b2 label= blocksize=4096 reserved_blocks=5% max_mounts=26 check_interval=180d bytes_per_inode=16384 options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/rootvg-var /var ext4 uuid=2e5a95b1-d311-4243-9505-ff0011e6cf91 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16384 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/mapper/uservg-u02 /u02 ext4 uuid=a544bd8f-f249-4666-ada6-4d9296f5835d label= blocksize=4096 reserved_blocks=1% max_mounts=33 check_interval=180d bytes_per_inode=16384 options=rw,relatime,barrier=1,data=ordered
fs /dev/sda2 /boot ext4 uuid=f4309db7-6be3-48b0-831d-9d825817401d label= blocksize=1024 reserved_blocks=0% max_mounts=-1 check_interval=0d bytes_per_inode=4081 default_mount_options=user_xattr,acl options=rw,relatime,barrier=1,data=ordered
fs /dev/sdc2 /boot2 ext4 uuid=11695a5f-d4b5-4241-82a5-c8c44fa86e4f label= blocksize=1024 reserved_blocks=1% max_mounts=38 check_interval=180d bytes_per_inode=4081 options=rw,relatime,barrier=1,data=ordered
# Swap partitions or swap files
# Format: swap <filename> uuid=<uuid> label=<label>
swap /dev/mapper/rootvg-swap uuid=63c3595c-5e7e-41c6-bc8f-787a70f07f81 label=

**Comment by gdha** [comment]
@John-Leone rear-1.17.2 has no knowledge around **dasd** devices. It was introduced in rear-1.18, but not yet announced as it was not yet production proof. You could try rear-1.18 and see if it work better for you. And, if it not yet fully correct help us to get it right.

**Comment by John-Leone** [comment]
Hello,
Thank you.  We can try rear-1.18.
Does 1.18 work with software raid?
Thanks,
John

**Comment by gdha** [comment]
@John-Leone sure it does. Keep us updated of the results.

**Comment by John-Leone** [comment]
@gdha Thank you again.  rear-1.18 worked!
I have one more quick question.  If you use rear to migrate a server does the restore target need to be on the same subnet for the recovery to work? Or can the network files be updated during the recovery.

**Comment by gdha** [comment]
@John-Leone you can change the IP address manually, use dhcp (USE_DHCLIENT=1), or use IP address migration technique (see our FAQ page)

**Comment by John-Leone** [comment]
Thanks for your help on this issue!

**Comment by jsmeix** [comment]
Damn!
I made a typo in the git commit message for https://github.com/rear/rear/pull/903
where I falsely wrote https://github.com/rear/rear/issues/822
instead of the right issue https://github.com/rear/rear/issues/882
