### ISSUE TITLE
Error: file '/rear-kernel' not found:

### ISSUE THREAD

**Issue by tharrisone** [rear/rear#827]
* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.18 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
Description:	Fedora release 23 (Twenty Three)

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://10.10.10.114/volume1/SYNDRV/MASTER/BKUPS/REAR/"
GRUB_RESCUE=y
GRUB_RESCUE_PASSWORD="grub.pbkdf2.sha512.10000.A2AF95B6F680A14D2524C81D58376298C2D2D423138A2D760B174FA4714A1A165D84FA9ADE3..."
GRUB_SUPERUSER="root"

* Brief description of the issue
On login I am given this error
error: file '/rear-kernel' not found 
error: you need to load the kernel first.

**Comment by tharrisone** [comment]
On Arch Linux I found the exact same error.

**Comment by gdha** [comment]
@tharrisone you see this error while booting the ISO or via the rear ram-image?
