### ISSUE TITLE
Requires: syslinux

### ISSUE THREAD

**Issue by wmaeg** [rear/rear#830]
I got this error when try to install rear -1.18-3.el6.i686.rpm on oracle Linux 6.7 
How can i install  syslinux ? to solve this !
Pleas advise 

[root@oralnx6test RearRedHat_RHEL-6]# yum install rear-1.18-3.el6.i686.rpm
Loaded plugins: refresh-packagekit, security, ulninfo
Setting up Install Process
Examining rear-1.18-3.el6.i686.rpm: rear-1.18-3.el6.i686
Marking rear-1.18-3.el6.i686.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package rear.i686 0:1.18-3.el6 will be installed
--> Processing Dependency: syslinux for package: rear-1.18-3.el6.i686
--> Finished Dependency Resolution
Error: Package: rear-1.18-3.el6.i686 (/rear-1.18-3.el6.i686)
           Requires: syslinux
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by gdha** [comment]
`yum install rear syslinux` will do the trick, or you can first install syslinux also.
