### ISSUE TITLE
Migrating with rear

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#835]
[root@xjlappm1d init.d]# rear -V
Relax-and-Recover 1.17.1 / Git

[root@xjlappm1d init.d]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

We're trying to use rear as a migration tool. The network files on the recovery image need to be modified to work on the new subnet.  Is there a command line tool or process that lets you change the network files to support the new network?

I was searching the documentation but could not find anything.

Thanks,
John

**Comment by gdha** [comment]
See http://relax-and-recover.org/documentation/faq IP migration section.

**Comment by John-Leone** [comment]
Thank you that works!
Does rear work with bonded networks?

**Comment by gdha** [comment]
@John-Leone yes it understands it to recreate these on a new system, however, when booted from the rescue image there is no guarantee  it works (it might just be one interface).
