### ISSUE TITLE
Implement rear recovery system update support (my next SUSE hackweek project)

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#841]
I like to implement a "rear update" workflow
that is initially intended for the following use-case:

In the rear recovery system one can run "rear update"
which can download and install a tar.gz archive
that gets installed into the running rear recovery system.

This way a rear recovery system can be updated
if needed during run-time without the need to
create a new recovery system ISO image
on the original system via "rear mkrescue".

The basic idea behind is to implement the same
kind of functionality as the so called "dud" provides
for SUSE installation systems, cf. "DUD" and "dud" at
https://en.opensuse.org/SDB:Linuxrc

In particular my use-case will be to update the
rear configuration files in a running rear recovery system.

This way I can use one same fixed rear recovery system
for various sufficiently similar systems (i.e. systems
where the same rear recovery system works but
the only differences are in the rear configuration files).

This should in particular mitigate the problem that
UEFI bootable ISO images are much bigger than
traditional BIOS bootable ISO images, cf.
https://github.com/rear/rear/issues/810#issuecomment-205783287
<pre>
An UEFI bootable ISO image is much bigger (almost 450MiB)
than a traditional BIOS bootable ISO image which is less than
120 MiB for me.
</pre>

Assume one has 100 servers with identical hardware of type A
and 200 servers with identical hardware of type B, then
(I hope) it is possible to have only one bootable ISO image
for all type A servers and one for all type B servers.

For recovery of a type A server one boots the type A
ISO image on type A replacement hardware and
runs in the rear recovery system first and foremost
something like
<pre>
rear update server_ID
</pre>
which downloads a tar.gz archive that matches server_ID
(e.g. from a fixed predefined HTTP or NFS server
that is stored in the currently used local.conf file)
or explicitly something like
<pre>
rear update http://my_internal_server/server_ID.tar.gz
</pre>
that contains the rear configuration files that belong
to server_ID.

Afterwards one runs as usual
<pre>
rear recover
</pre>
to recover exactly that server_ID machine.

**Comment by jsmeix** [comment]
First things first
(or "avoid RFC 1925 item 5"):

For the SUSE Hackweek 14 I will implement only to
download rear configuration files in the recovery system.

See
https://hackweek.suse.com/14/projects/1508

Reason:

A generic recovery system update is complicated
because to be generoc it must also work to update
the currently running scripts (i.e. via  "rear update"
it must also work to update in particular the currently
running /usr/sbin/rear and also all scripts of the
currently running "odtate" workflow).

Becaue I have currently no use-case to update anything
in the recovery system I like to keep it simple and do
first things first and implememt only my current use-case.

When I have some specific "download and install" functionality
working in the "recover" workflow, I can later step by step
enhance it as actually needed towards more and more
generic recovery system update functionality.

Outlook:

I think generic recovery system update functionality
is useful:

Example:

Assume one has 100 servers with identical hardware of type A
and matching bootable ISO image for them.

Assume the replacement hardware for type A servers
is step by step changed from identical type A hardware
to new type C hardware that is similar but a bit different
so that the existing type A bootable ISO images do no
longer work.

It would be nice if one could still have one single
recovery system ISO image that works for both
the old type A replacement hardware and also
for the new type C replacement hardware.

Then generic recovery system update functionality
could help to update the running recovery system
during "rear recover" so that it also works even
on the new type C replacement hardware.

**Comment by didacog** [comment]
@jsmeix 
Regarding updating rear config files at recovery time, with DRLM running the recover workflow:

<pre>
# rear recover SERVER=X.X.X.X REST_OPTS=-k ID=drlm_cli_name
</pre>

http://drlm-docs.readthedocs.io/en/latest/Restore.html

It downloads rear configuration from DRLM server and start recovery with the latest configuration from DRLM. 

Just needed to use a properly configured DRLM server to do this ;)

**Comment by jsmeix** [comment]
@didacog 
many thanks for your hint!

Thanks to free software I will shamelessly and selfishly
try to re-use your code for my own purposes ;-)

**Comment by didacog** [comment]
@jsmeix 

You can take a look at: https://github.com/rear/rear/pull/522/commits

This was the code regarding DRLM integration in rear: issue #522

Hope this helps! ;)

**Comment by jsmeix** [comment]
Just an untested idea
how to get the recovery more automated:

In https://hackweek.suse.com/14/projects/1508 I wrote
<pre>
rear recover HOSTNAME
</pre>
i.e. an explicitly specifyied HOSTNAME is needed.

But that contradicts the basic idea of rear
that it should be possible to do the recovery
by a (relatively) unexperienced person
so that the experienced admin can relax
after he had set it up.

Therefore I think about a variable in local.conf like
<pre>
RECOVERY_CONFIG_URL="http://my_internal_server/$MAC_ADDRESS.tar.gz"
</pre>
or
<pre>
RECOVERY_CONFIG_URL="http://my_internal_server/$HOSTNAME.tar.gz"
</pre>
that evaluates in the recovery system to the mac address
or the hostname of the host where "rear recover" runs.

This way (I hope) it is possible that the admin could provide
appropriate rear configs on the HTML server in andvance
so that plain "rear recover" works as intended - provided also
things like DHCP setup of the recovery system networking
were appropriately prepared in andvance (this cannot work
with random mac addresses or hostnames in the recovery
system).

Next week I will see what I can get easily.

**Comment by jsmeix** [comment]
As far as I noticed in https://github.com/rear/rear/issues/943
it seems my very first implementation works sufficiently
well - at least for now - so that I close  this issue as "fixed".
For bugs or further enhancements please open new issues.
