### ISSUE TITLE
new BACKUP_URL=ftp://... in future version REAR

### ISSUE THREAD

**Issue by sergeymx** [rear/rear#845]
( sorry Bad my english )

new feature request
You could not be in future versions to add method ftpfs for BACKUP_URL ?
( http://curlftpfs.sourceforge.net/ its locate more distribute linux )

Thanks.

**Comment by jsmeix** [comment]
In http://curlftpfs.sourceforge.net/
their "quite simple" examples section
of the CurlFtpFS geeks is too simple 
because it does not mention how to do it
with authenticated ftp.

@sergeymx 
can you provide a full command line example how
to get a remote ftp URL with username and password
"mounted" at a local directory and how to "umount" it
after usage?
Preferably by using your ftp://mx@asu-test/rear/ from https://github.com/rear/rear/issues/842

Furthermore I would like to know if after such a "umount"
has returned then it means that all data is actually
successfully sent to the ftp server.

**Comment by sergeymx** [comment]
[root@centos6-build mx]# curlftpfs -o user=mx asu-test/rear /home/mx/ftp
Enter host password for user 'mx':
[root@centos6-build mx]# ls /home/mx/ftp
asu-test  rear-centos6-build-backup.iso  rear-centos6-build-rescue.iso
[root@centos6-build mx]# umount /home/mx/ftp
[root@centos6-build mx]# ls /home/mx/ftp
[root@centos6-build mx]# 
---
http://linux.die.net/man/1/curlftpfs

**Comment by sergeymx** [comment]
Steps:
1. use 1 terminal and mount curlftpfs
2. use 2 terminal and start : rear -v mkbackup
3. switch to terminal 1 and run command: umount /home/mx/ftp/
i see : 
[root@centos6-build mx]# umount /home/mx/ftp
umount: /home/mx/ftp: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))

**Comment by jsmeix** [comment]
Many thanks for the info.
As time permits I will try to implement something
as a very first starting point ...

**Comment by jsmeix** [comment]
https://github.com/rear/rear/pull/859 implements
first steps to support new ftpfs BACKUP_URL.

Note that the URI scheme is "ftpfs" to distinguish
that from the already existing URI scheme "ftp"
cf. https://github.com/rear/rear/issues/842#issuecomment-223248788

**Comment by jsmeix** [comment]
@sergeymx 
can you test https://github.com/rear/rear/pull/859
and report whether or not it also works for you?
Note the currently needed "modprobe fuse" as descibed
in https://github.com/rear/rear/pull/859#issue-158191489

**Comment by jsmeix** [comment]
@sergeymx 
can you test current rear master
and report whether or not it also works for you?

With current rear master "modprobe fuse" happens
automatically as needed, cf. https://github.com/rear/rear/pull/859#issuecomment-223540169

My next step would be trying to improve the speed when
the backup is stored via curlftpfs, cf. https://github.com/rear/rear/pull/859#issue-158191489

@sergeymx 
do you perhaps already know how to improve
the writing speed when using curlftpfs?
"man curlftpfs" lists many options where most of them
are meaningless for me (I am not at all a FTP expert).

**Comment by jsmeix** [comment]
No feedback => closing the issue.
