### ISSUE TITLE
Understanding REAR Checklayout

### ISSUE THREAD

**Issue by akshaysarraf2016** [rear/rear#846]
Hello, 

I installed REAR on a Server. When I try to run "rear -v mkbackup" It gives the output as 
```
`Relax-and-Recover 1.18 / Git
Using log file: /var/log/rear/rear-eul2e1.log
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
ERROR: BUG BUG BUG!  ROOTFS_DIR '/tmp/rear.RPoUCQycgh21105/rootfs' is broken, chroot bash test failed. 
=== Issue report ===
Please report this unexpected issue at: https://github.com/rear/rear/issues
Also include the relevant bits from /var/log/rear/rear-eul2e1.log

HINT: If you can reproduce the issue, try using the -d or -D option !
====================
Aborting due to an error, check /var/log/rear/rear-eul2e1.log for details
You should also rm -Rf /tmp/rear.RPoUCQycgh21105
Terminated
```

But, This is isn't my concern for now, I'll ask about this bug as my next question. My primary concern is, I dont have any earlier REAR Image of this server. But when I run "rear checklayout" it returns error code 0. Which means there is no change from the previous Image. But there was no image created since day 1. Why is it behaving so ?

**Comment by gdha** [comment]
@akshaysarraf2016 what did you see in the log file?
You can always run `rear savelayout` and check the files under `/var/lib/rear/layout`
I guess you will find a cron entry `/etc/cron.d/rear` which run checklayout

**Comment by jsmeix** [comment]
No response for more than 3 month => closing it.
If needed it can be reopenend.
