### ISSUE TITLE
How to manual recover?

### ISSUE THREAD

**Issue by kodiss** [rear/rear#847]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): 1.18
* OS version (cat /etc/rear/os.conf or lsb_release  -a): Redhat 6.4
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
  GRUB_RESCUE=1
  BACKUP=NETFS
  BACKUP_OPTIONS="nfsvers=3,nolock"
  BACKUP_URL="nfs:/XX.XX.XX.XX/osbackup"
  NETFS_KEEP_OLD_BACKUP_COPY=yes
  BACKUP_PROG_ARCHIVE="osbackup_$(hostname)"
  BACKUP_PROG_INCLUDE=('/' '/boot' '/tmp' '/usr' '/var')
BACKUP_PROG_EXCLUDE=('/dev/shm/*' '/var/crash/*' '/proc' '/sysadmin/nmondata/*')
 
* Brief description of the issue

After NFS Backup, when i want to restore and recover manually,
The step is below, please check and share the information.

1. use the another IP
2. use the specific file by command, is there specific command or option?
    ex) rear recover [Target file dest and name]
3. Any special manual recover guide doc?

Please Help and share.
Thank you and Best regards.

**Comment by gdha** [comment]
@kodiss
1.  to use another IP address then the original:
- see FAQ http://relax-and-recover.org/documentation/faq topic IP migration
- or, you can set it manually once booted via the rescue image
- or, you can force dhcp with `USE_DHCLIENT=1` in the local.conf file
- or, while booting the rescue image interrupt the kernel from booting and append the following commands to kernel: `ip=x.x.x.x. gw=x.x.x.y nm=255.255.255.x`
- or, while booting the rescue image interrupt the kernel from booting and append the following commands to kernel: `dhcp`

2. rear recover [file to restore] - rear purpose is to restore the complete base OS, not just one specific file.

3. recover manual: sorry - we know this is a gab, and we would love to write it, but as working on rear is mostly a unpaid job we cannot afford the time. However, nothing stops you of asking for it via http://www.it3.be/rear-support/index.html
We will be giving a workshop at http://osbconf.org/workshops/ - nothing stops you for coming

**Comment by jsmeix** [comment]
No further comments since more than 3 month
indicate it is sufficiently anwered => closing it.
