### ISSUE TITLE
some latest commit(s) make rear fail to launch the recovery system on SLE12

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#858]
Latest rear master on a SLE12-SP1
x86_64 kvm/qemu virtual machine with BIOS:

Some Git commit after the Git commit
bd3d2ac41c7ed04352abd28de16b9493aff40683
result that the rear recovery system hangs up
during its startup phase so that it never reaches
the shell prompt (where one would log in as root
and run "rear recover").

I.e. it boots but then during (I guess systemd's)
startup procedure it hangs up.

The Git commit
bd3d2ac41c7ed04352abd28de16b9493aff40683
is the last one which I have in my rear118a RPM package on
https://build.opensuse.org/package/show/home:jsmeix/rear118a
which works on my above mentioned SLE12-SP1 machine.

My problem is that I have no clue how I could debug
such kind of low-level issues when I even cannot log in
at the rear recovery system.

@gdha 
could you help me how to debug such issues?

**Comment by gdha** [comment]
@jsmeix Do you have an idea in which stage it hangs? What was the last line you saw on the screen?
From which media did you boot (iso or ramdisk)?
Most changes were on UEFI (not your area of testing), multipath (not used in your case I think?), BACKUP schemes checks, perhaps the `skel/default/etc/scripts/run-sshd` modifucation?
Otherwise, try a dirdiff between the last good base and the master?

**Comment by jsmeix** [comment]
I will provide a screenshot soon...

I boot my virtual kvm/qemu machine from
its virtual CD-ROM drive where I have
in the host system the rear-<hostnam>.iso
connected to the virtual CD-ROM drive.

In this case here (not too many commits)
I can (and will) do a bisecting until I found
the commit that makes it fail.

**Comment by jsmeix** [comment]
Screenshot:

![issue858](https://cloud.githubusercontent.com/assets/1788608/15777025/8c0a0c6a-298c-11e6-87f0-82c7b1a964f0.png)

**Comment by gdha** [comment]
@jsmeix perhaps check https://github.com/rear/rear/pull/844 commit.

**Comment by jsmeix** [comment]
After several futile attemts to find an older commit
where it works again I come to the conclusion
that something got somehow messed up
on my test system.

On a new from scratch installed SLES12-SP1 system
(same kind of kvm/qemu virtual machine)
everything "just works" with the current master.

Accordingly I close the issue as "false alarm".

@gdha 
many thanks for your time!

FYI:
If I remember correctly this is the second time
where rear failed on a test system after many tests.
I have the dim feeling it is relatively easily possible
to somehow mess up rear or even something in
the system when doing a lot to and fro with rear.
Of course I cannot reproduce reight now what
exactly got somehow messed up.
