### ISSUE TITLE
Having trouble with restoring a backup

### ISSUE THREAD

**Issue by nhenjes** [rear/rear#860]
- rear version: 1.17.2
- OS version: CentOS 6.3
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://10.10.25.20/mnt/Data/
ISO_MAX_SIZE=4096

#Exclude the Mounted Files
EXCLUDE_MOUNTPOINTS=("/mnt/release_files|/backups")

#Temporary file location
TMPDIR=("/files/rear")

#Include Multipath Files
AUTOEXCLUDE_MULTIPATH=n
```
- Brief description of the issue: When I run "rear recover" on a different machine to test backups (same hardware), I only get to the error "No filesystem mounted on /mnt/local" after rear runs the 25_verify_mount.sh script
- Work-around, if any: none
  The backup file size is 12GB and the mkbackup stage says it completed successfully.

**Comment by nhenjes** [comment]
I'm also seeing "Backup archive size is 0M (compressed)", but I see the backup files sitting on the NAS

**Comment by gdha** [comment]
@nhenjes the syntax of `EXCLUDE_MOUNTPOINTS=("/mnt/release_files|/backups")` is wrong. It should be `EXCLUDE_MOUNTPOINTS=("/mnt/release_files"  "/backups")`
Are there no other errors seen in the rear.log file?
Can you boot the iso image on the same HW successfully?
Perhaps, also check the files under `/var/lib/rear/layout` - are all file systems found and described properly? You may post it for verification.

**Comment by nhenjes** [comment]
Yeah, I wondered about that yesterday when I posted this. I changed it to have a space instead of pipe, but the individual points weren't quoted, only the whole thing.

I don't have the opportunity to try a reload on that exact system, but I did try it on an identical server (it was a warm spare for the others), and met the same issue.

I'll post the layout, but from what I can tell, the partitions are made correctly. I wiped the disk bare, and saw the partitions after running recover again.

**Comment by nhenjes** [comment]
disk /dev/sda 500107862016 msdos
part /dev/sda 235929600 1048576 primary boot,raid /dev/sda1
part /dev/sda 16106127360 236978176 primary raid /dev/sda2
part /dev/sda 16106127360 16343105536 primary raid /dev/sda3
part /dev/sda 1024 32449232896 extended none /dev/sda4
part /dev/sda 5368709120 32451330048 logical raid /dev/sda5
part /dev/sda 16106127360 37821087744 logical raid /dev/sda6
part /dev/sda 214748364800 53928263680 logical raid /dev/sda7
part /dev/sda 34359738368 268677677056 logical raid /dev/sda8
part /dev/sda 197069373440 303038464000 logical raid /dev/sda9
disk /dev/sdb 500107862016 msdos
part /dev/sdb 235929600 1048576 primary boot,raid /dev/sdb1
part /dev/sdb 16106127360 236978176 primary raid /dev/sdb2
part /dev/sdb 16106127360 16343105536 primary raid /dev/sdb3
part /dev/sdb 1024 32449232896 extended none /dev/sdb4
part /dev/sdb 5368709120 32451330048 logical raid /dev/sdb5
part /dev/sdb 16106127360 37821087744 logical raid /dev/sdb6
part /dev/sdb 214748364800 53928263680 logical raid /dev/sdb7
part /dev/sdb 34359738368 268677677056 logical raid /dev/sdb8
part /dev/sdb 197069373440 303038464000 logical raid /dev/sdb9
#disk /dev/sdd 0
raid /dev/md1 metadata=1.1 level=raid1 raid-devices=2 uuid=a3b0d04f:5726760a:b3c2254d:d6590f39 devices=/dev/sda2,/dev/sdb2
raid /dev/md6 metadata=1.1 level=raid1 raid-devices=2 uuid=38f5e366:ed8ca9af:0d26f8ad:fad3d1ac devices=/dev/sda8,/dev/sdb8
raid /dev/md0 metadata=1.0 level=raid1 raid-devices=2 uuid=42ccc462:1414bae1:0ed86b92:7f213848 devices=/dev/sda1,/dev/sdb1
raid /dev/md4 metadata=1.1 level=raid1 raid-devices=2 uuid=761b7984:ed2e8a81:6d61f2ce:875f63e4 devices=/dev/sda6,/dev/sdb6
raid /dev/md3 metadata=1.1 level=raid1 raid-devices=2 uuid=241f8c9d:855627fc:0edb9663:f7d159c6 devices=/dev/sda5,/dev/sdb5
raid /dev/md5 metadata=1.1 level=raid1 raid-devices=2 uuid=47e3b841:8bc18ff3:57736768:73827e28 devices=/dev/sda7,/dev/sdb7
raid /dev/md2 metadata=1.1 level=raid1 raid-devices=2 uuid=dd9bc485:5c855ee4:1fdb3e01:8b8e84dd devices=/dev/sda3,/dev/sdb3
raid /dev/md7 metadata=1.1 level=raid1 raid-devices=2 uuid=0d75234c:64e331a7:760c06a6:5480a8c8 devices=/dev/sda9,/dev/sdb9
# Filesystems (only ext2,ext3,ext4,vfat,xfs,reiserfs,btrfs are supported).
# Format: fs <device> <mountpoint> <fstype> [uuid=<uuid>] [label=<label>] [<attributes>]
fs /dev/md0 /boot ext4 uuid=034c8d59-6e71-4a40-bb96-b849188eb551 label= blocksize=1024 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=4083 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md1 / ext4 uuid=2f500e02-9a7c-4b0e-b636-7487b888f0d7 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16382 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md2 /home ext4 uuid=547d029e-0c23-43ce-98f1-15671422f1eb label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16382 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md3 /tmp ext4 uuid=9e88a19c-9c15-41c8-bbfc-752f94e038bc label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16380 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md4 /var ext4 uuid=6e1aac66-0df7-43a2-b17c-a4c033875425 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16382 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md5 /users ext4 uuid=17ecfc5b-bc81-4fb0-984b-f43b98823b32 label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16383 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
fs /dev/md7 /files ext4 uuid=ba700c57-ebf1-4f9c-937c-e45258c6673d label= blocksize=4096 reserved_blocks=4% max_mounts=-1 check_interval=0d bytes_per_inode=16375 default_mount_options=user_xattr,acl options=rw,noatime,barrier=1,data=ordered
swap /dev/md6 uuid=24b2d268-c2e3-4f19-bb46-36fe6c2fb688 label=

The server is running software RAID 1

**Comment by nhenjes** [comment]
[rear-server01.zip](https://github.com/rear/rear/files/297772/rear-server01.zip)

Here is the log file, I didn't see anything that stood out as an error in the backup process

**Comment by nhenjes** [comment]
Getting rid of the ISO_MAX_SIZE makes the restore show the correct archive size. I'm still getting errors about nothing mounted to /mnt/local. What is supposed to be mounted to /mnt/local?

**Comment by gdha** [comment]
The log file made during the recovery is of interest here as in recover mode rear will recreate the software raid and mount all file systems under /mnt/local. Something is probably failing...

**Comment by gdha** [comment]
@nhenjes waiting on the rear.log of during the rescue (with -dD option)
