### ISSUE TITLE
SLES12: /var/lib/empty is missing, SSHD does not start

### ISSUE THREAD

**Issue by abbbi** [rear/rear#864]
* rear version (/usr/sbin/rear -V): 1.18
* OS version (cat /etc/rear/os.conf or lsb_release  -a): SLES12 SP1

by default on SLES12 sshd daemon does not start during recovery because 

/var/lib/empty

is missing (/sbin/sshd will complain)
Simply creating the directory fixes this problem. Probably directory should be included during
mkrescue run.

**Comment by jsmeix** [comment]
It never happened for me.

On all my test systems (in particular on SLE12-SP1)
I have in /etc/rear/local.conf something like
<pre>
SSH_ROOT_PASSWORD="rear"
</pre>
and ssh access to the rear recovery system
always "just worked" for me.

@abbbi 

Do you have a non-default ssh configuration?

Does in /etc/rear/local.conf something like
<pre>
COPY_AS_IS=( "${COPY_AS_IS[@]}" /var/lib/empty )
</pre>
also fix it for you?

**Comment by abbbi** [comment]
we have set a custom password in local.conf:

SSH_ROOT_PASSWORD="recover"

besides that i used:

COPY_AS_IS=( "${COPY_AS_IS[@]}" /var/lib/empty )

to fix the problem!

**Comment by gdha** [comment]
@abbbi However, I still do **not** understand where `/var/lib/empty` comes from?

**Comment by gdha** [comment]
@abbbi I've checked our skel tree and `skel/default/var/lib/empty` does exist, therefore, it should always be present in a rescue environment. I just check a rescue image and `/var/lib/empty` directory was there. Are you really sure this directory was the issue?

**Comment by gdha** [comment]
@jsmeix If you could verify on a rescue environment (any SLES I guess) that directoru `/var/lib/empty` is there by default?

**Comment by gdha** [comment]
Verified it several times and /var/lib/empty is always present in the rescue image. No need to add it to the COPY_AS_IS array

**Comment by jsmeix** [comment]
Regarding  https://github.com/rear/rear/issues/864#issuecomment-231135110
see my https://github.com/rear/rear/issues/864#issuecomment-223944174
i.e. it never happened for me and on all my test systems I had
a /var/lib/empty/ directory in the recovery system e.g right now
on SLES12-SP2:
<pre>
RESCUE d245:~ # ls -ld /var/lib/empty/
drwxr-xr-x 2 root root 0 Aug 17 13:49 /var/lib/empty/
</pre>
