### ISSUE TITLE
Recover failed to restore user 

### ISSUE THREAD

**Issue by ryan-chow** [rear/rear#873]
* rear version: Relax-and-Recover 1.18 / Git
* OS version: OS_VENDOR=Fedora
                      OS_VERSION=23
* rear configuration files: OUTPUT=USB
                                        USB_DEVICE=/dev/disk/by-label/REAR-000
                                        BACKUP=NETFS
                                        BACKUP_URL=usb:///dev/disk/by-label/REAR-000
* Brief description of the issue
  The rear recover failed to restore the lone user of the system.  Root account was restored.
  The same rear configuration used to work on Fedora 23 LVM with rear 1.17.  I re-installed 
  Fedora23 recently and placed / and /home on Btrfs.  The rear recover did restore the system.
  I have the login screen with my lone user but could not login with the password.  I am able to login
  ROOT account and find the lone user.  I reset the password of it and the same problem persisted.
  The home directory was totally empty, which is also empty in the backup file.  I spotted no error in
  the backup log but found the errors in recover log:
  2016-06-09 18:48:21 Including restore/default/90_create_missing_directories.sh
  2016-06-09 18:48:21 Restore the Mountpoints (with permissions) from /var/lib/rear/recovery/mountpoint_permissions
  chown: invalid user: 'ryan:ryan'
  chown: invalid user: 'gdm:gdm'
* Work-around, I do not have any

**Comment by jsmeix** [comment]
"/home on Btrfs" means that for usual tools "/home" behaves
as if it was on a separated filesystem because btrfs subvolumes
behave as if there were separated filesystems.

Accordingly you must explicitly specify to backup the content
in "/home".

Cf. the btrfs example configs for SLE in
usr/share/rear/conf/examples/SLE12-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf

**Comment by jsmeix** [comment]
I assume with https://github.com/rear/rear/issues/873#issuecomment-225536867
the issue is sufficiently solved.
If not you can reopen it.
