### ISSUE TITLE
rear backup doesn't copy all libraries into chroot directory

### ISSUE THREAD

**Issue by pdanek** [rear/rear#879]
* rear version: rear-1.16-1.el6.noarch
* OS version: Oracle Linux Server release 6.6 (RHEL 6.6)
* rear configuration:
OUTPUT=ISO
BACKUP=TSM
* Brief description of the issue:
Rear backup doesn't copy all required libraries into chroot directory which causes chroot command to fail and entire backup to fail.
After backup fails, the missing libraries stay in /tmp instead of going go to /tmp/rear.JCUYFv0LeP7clzT/rootfs

Libraries in /tmp are shown in following text file:
[libraries-in-tmp.txt](https://github.com/rear/rear/files/315925/libraries-in-tmp.txt)

From backup log:
2016-06-15 10:20:04 Including build/default/98_verify_rootfs.sh
chroot: failed to run command `bash': No such file or directory
2016-06-15 10:20:04 ERROR: BUG BUG BUG!  ROOTFS_DIR '/tmp/rear.JCUYFv0LeP7clzT/rootfs' is broken, chroot bash test failed.

Chroot fails because bash is missing some libraries which are not copied to chroot (ldd /bin/bash).

Full debug log (rear -D) is also attached:
[rear-SERVERHOSTNAME.log.txt](https://github.com/rear/rear/files/315917/rear-SERVERHOSTNAME.log.txt)

* Work-around, if any: NONE

Thanks for help.

**Comment by gdha** [comment]
The problem is the following:
````
++ [[ -L /lib64/libgssglue.so.1 ]]
+++ readlink -f /lib64/libgssglue.so.1
++ target=
++ copy_lib
++ local lib=
++ ensure_dir
++ local dir=
````
It should return something like:
````
$ readlink -f /lib64/libgssglue.so.1
/usr/lib64/libgssglue.so.1
````
Does `readlink` exist on your os?

**Comment by pdanek** [comment]
You are right, /bin/readlink was zero size, although coreutils was installed.
I reinstalled coreutils and backup now runs successfully.

Thanks very much for blazing fast resolution!
