### ISSUE TITLE
Restore ReaR ISO to OVM Guest?

### ISSUE THREAD

**Issue by pdanek** [rear/rear#880]
* rear version: rear-1.16-1.el6.noarch
* OS version: Oracle Linux Server release 6.6 (RHEL 6.6)
* rear configuration:
OUTPUT=ISO
BACKUP=TSM
* Brief description of the issue:
We use ReaR backup across our VMware environment, but we are unable to boot ReaR ISO on our OVM Guests (PVM - paravirtualized).
We followed Oracle documentation to boot from ISO on OVM, mounted the ISO on our PXE server and then booted from PXE but nothing comes up on console / ISO is not bootable.

Obviously this could be more of an issue with OVM, but I would like to ask if any of you guys use Rear on OVM paravirtualized guests?

Thanks a million,
Peter

**Comment by gdha** [comment]
You should the ISO file available in your VMware storage pool somehow and then use the console and attach the ISO to your virtual DVD drive

**Comment by pdanek** [comment]
This is not VMware, but Oracle VM (OVM).
OVM doesn't support attaching the ISO from console, but instead we have to boot the ISO from PXE server, it's the only option with paravirtualized OVM guests (PVM).
We did that, same way as we boot installation ISOs from PXE and it doesn't boot.

**Comment by gozora** [comment]
You could try this::

1) Copy iso file to pxe server

2) Install syslinux if you don't already have it installed

3) Copy memdisk from /usr/lib/syslinux to your pxe folder

4) Edit pxelinux.cfg/default

And add this:
```
LABEL <your iso>
kernel memdisk
append iso initrd=<path to iso> raw

Example:
LABEL Win PE
kernel memdisk
append iso initrd=images/winpe/winpe.iso raw
```

[Source](http://ubuntuforums.org/showthread.php?t=1123054)

**Comment by pdanek** [comment]
Paravirtualized guests in OVM do not support traditional boot from PXE, but only boot from http server (basically not a PXE boot anymore, only only named as such in OVM).
There is just is single column called "Network Boot Path", used for booting from NFS/HTTP.

Normally for installing new servers from golden image, we would use something like this in Network Boot Path field:
`--kernel images/pxeboot/vmlinuz --ramdisk images/pxeboot/initrd.img --args="ksdevice=eth0 network bootproto=static ip=<IP_ADDRESS> netmask=<NETMASK> gateway=<GATEWAY>" http://webserver.example.com/examplerepo/OL6/disttree/ol66/`

/examplerepo/OL6/disttree/ol66/ is basically mounted installation CD and contains files which are used for initial boot:
images/pxeboot/vmlinuz
images/pxeboot/initrd.img

Rear ISO only contains isolinux directory and nothing else.
How can we craft our HTTP style boot path for Rear ISO please?

Thanks a million,
Peter

**Comment by gozora** [comment]
To be honest I've never booted from http, so this will be a blind shot...
From what you are describing you only need to extract **initrd.cgz** and **kernel** (I'm not sure now but kernel is called vmlinux in ISO?) from ISO created by `rear mkrescue/mkbackup` and put put them as parameters for `--kernel` and `--ramdisk`. Mentioned files should be located in isolinux directory.

**Comment by pdanek** [comment]
Directly putting the kernel and initrd as they are in ISO worked fine:
`--kernel isolinux/kernel --ramdisk isolinux/initrd.cgz`

We can now boot from HTTP.
Thanks very much for help!

**Comment by pushparajchand** [comment]
Hi pdanek,

Where you have added these parameter --kernel isolinux/kernel --ramdisk isolinux/initrd.cgz. in OVM Environment

We have option in PVM based VM's to enter the URL in Network Boot Path only like /examplerepo/OL6/disttree/ol66/
