### ISSUE TITLE
RFC: Document rear coding patterns?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#881]
This is a request for comments what you think about
making a document that contains preferred
bash coding patterns for Relax-and-Recover.

This RFC is triggered by my proposal in https://github.com/rear/rear/commit/4440a05ac782e30290e678b7b158d868f4758899#commitcomment-17878403
and that @gdha agreed that it is a "good idea" in https://github.com/rear/rear/commit/4440a05ac782e30290e678b7b158d868f4758899#commitcomment-17879810

Therefore I am wondering if I should step by step
collect bash coding patterns that we prefer to use
and document them to help all rear contributors
to get ready-to-use bash coding patterns.

Of course my request is primarily selfish ;-)
because first and foremost it is me who likes
to learn about preferred bash coding patterns
and therefore - provided you agree - I will make
such a document.

I would like to make it as a separated document in
the rear wiki that can be used together with the
existing Coding Style https://github.com/rear/rear/wiki/Coding-Style

**Comment by jsmeix** [comment]
FYI:

Triggered by https://github.com/rear/rear/issues/914#issuecomment-232755869
I initiated a "Developers Guide" document
https://github.com/rear/rear/wiki/Developers-Guide

But I think that coding patterns would not well match
the intent of the "Developers Guide" so that
coding patterns should be in a separated document.

**Comment by didacog** [comment]
@jsmeix I think this is a good idea.
