### ISSUE TITLE
Error while recovering SLES-11 SP3 --> cgroup_disable=memory

### ISSUE THREAD

**Issue by jottschi** [rear/rear#907]
Using Rear 1.18 / Git
OS-Version SLES 11 SP3 (+ OES11 on TOP)
Kernel-Version:  3.0.101-0.47.71-default
OS_VENDOR=SUSE_LINUX
OS_VERSION=11
ReaR Config: /etc/rear/local.conf

 OUTPUT=ISO
 BACKUP=NETFS
 BACKUP_URL=sshfs://sambasave@10.2.3.4/home/sambasave/Backup
#
MODULES_LOAD=( vmxnet vmxnet3 e1000e e1000 fuse hpsa )
USE_DHCLIENT=Yes
DHCLIENT_BIN=dhclient
###  END

**Issue**: 
The Kernel stops  booting while complainig about Memory C-Groups

**Work-Around:**
I added "**cgroup_disable=memory**" to the initrd kernel parameters as suggested by the error message
now it looks like this:
append initrd=initrd.cgz root=/dev/ram0 vga=normal rw selinux=0 cgroup_disable=memory console=tty0 auto_recover
Question: Is there a line in line for this in local.conf?

Thanks for reading!

**Comment by jsmeix** [comment]
I never used that particular configuration variable myself
but usr/share/rear/conf/default.conf
reads:
<pre>
# append special kernel parameters on rescue media
KERNEL_CMDLINE=""
</pre>

Please try in /etc/rear/local.conf
<pre>
KERNEL_CMDLINE="cgroup_disable=memory"
</pre>
and provide feedback if that makes it work for you.

**Comment by jsmeix** [comment]
FYI regarding
<pre>
BACKUP_URL=sshfs://...
...
MODULES_LOAD=( ... fuse ... )
</pre>

Currently the MODULES_LOAD functionality seems not to work,
see https://github.com/rear/rear/pull/905
and https://github.com/rear/rear/commit/0ec871676b7cdc52461574200c8a54867d0cfb37

**Comment by jsmeix** [comment]
No feedback.

With the fallback assumtion that "no news is good news"
I close it now.

**Comment by jottschi** [comment]
Yes. IT works.

Am 11.07.2016 13:33 schrieb "Johannes Meixner" <notifications@github.com>:

**Comment by jsmeix** [comment]
@jottschi 
many thanks for your confirmation feedback
that it actually works for you.
