### ISSUE TITLE
ERROR: Could not find 'mbr.bin'

### ISSUE THREAD

**Issue by turbovan** [rear/rear#908]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.18-git201607080200 / 2016-07-08
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
BACKUP=NETFS
OUTPUT=USB
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

* Brief description of the issue
Backup fails with following message:

$ sudo rear -v mkbackup
Relax-and-Recover 1.18-git201607080200 / 2016-07-08
Using log file: /var/log/rear/rear-localhost.log
ERROR: Could not find 'mbr.bin' in . Syslinux version 3.08 or newer is required, 4.x prefered !
Aborting due to an error, check /var/log/rear/rear-localhost.log for details

syslinux is installed:

$ syslinux --version
syslinux 6.03  Copyright 1994-2014 H. Peter Anvin et al

* Work-around, if any

First time rear user, haven't been able to figure out a workaround

**Comment by schlomo** [comment]
Can you please search your system for the `mbr.bin` file? Maybe we don't look in the right path.

**Comment by turbovan** [comment]
Hello schlomo, it is located at:
/usr/lib/syslinux/bios/mbr.bin

**Comment by schlomo** [comment]
Please check this change and let us know if it helps.

**Comment by turbovan** [comment]
All working now, thanks!
