### ISSUE TITLE
docs: rsync does not work 'only with ssh'

### ISSUE THREAD

**Issue by todoleza** [rear/rear#918]
from manpage:
       OUTPUT_URL=rsync://
           Write the image using rsync and the RSYNC protocol (SSH only).

The information provided above does not make sense since rsyncd is used on remote side, no ssh is involed altogether with this option. This also changes the path needed to be used from remote path to rsync module and path in it.

Relax-and-Recover 1.17.2 / Git
Red Hat Enterprise Linux Server release 7.2 (Maipo)
/etc/rear/local.conf:
OUTPUT=PXE
OUTPUT_URL="rsync://192.168.122.153/rear/"
BACKUP=RSYNC
BACKUP_URL="rsync://192.168.122.153/rear/"

**Comment by gdha** [comment]
@todoleza the rear man page is missing a section around **rsync**, we will enhance this a bit to be more precise. OTH - what is wrong in your opinion?

**Comment by jsmeix** [comment]
@todoleza 
regarding "BACKUP_URL="rsync://..."

See https://github.com/rear/rear/issues/899 and https://github.com/rear/rear/issues/919

In current rear master I have implemeted a test for
known valid BACKUP_URL schemes, see #842
so that one can no longer specify invaild
BACKUP_URL schemes.

**Comment by todoleza** [comment]
@gdha 
I think that '(SSH only)' should be omited altogether because it does not make sense. You need to either use rsyncd module for path specification or normal path for ssh transport. Examples here:
`"rsync://root@host::rear"`, `"rsync://root@host/srv/rear"` would be good to have there.

**Comment by gdha** [comment]
Man page and default.conf were already updated. Still need to check the user docs.

**Comment by jsmeix** [comment]
I close it because it is fixed.
