### ISSUE TITLE
Undocumented cifs support for OUTPUT_URL

### ISSUE THREAD

**Issue by tcerna** [rear/rear#923]
* rear version (/usr/sbin/rear -V):
1.17.2 / Git

* OS version (cat /etc/rear/os.conf or lsb_release -a):
RedHatEnterpriseServer 7

* description: OUTPUT_URL parameter for rescue image supports cifs protocol even though it's not explicitly documented in rear's man page. I managed to successfully backup an entire virtual machine via cifs (data + rescue image) with following settings and outcome:

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
```
# cat /etc/rear/local.conf 
OUTPUT=ISO
OUTPUT_URL=cifs://192.168.122.129/rear
OUTPUT_OPTIONS="cred=/etc/rear/.cifs"
BACKUP=NETFS
BACKUP_URL=cifs://192.168.122.129/rear
BACKUP_OPTIONS="cred=/etc/rear/.cifs"
```

* example:
```
Client:
[root@rearclient ~]# cat /etc/rear/.cifs 
username=root
password=root

Server:
[root@rearserver backups]# ll -h rearclient/
total 888M
-rw-------. 1 root root 4.3M Jul 14 13:21 backup.log
-rw-------. 1 root root 775M Jul 14 13:21 backup.tar.gz
-rw-------. 1 root root  202 Jul 14 13:18 README
-rw-------. 1 root root  32K Jul 14 13:18 rear.log
-rw-------. 1 root root 110M Jul 14 13:18 rear-rearclient.iso
-rw-------. 1 root root    0 Jul 14 13:21 selinux.autorelabel
-rw-------. 1 root root  282 Jul 14 13:18 VERSION
```

**Comment by jsmeix** [comment]
I think https://github.com/gdha/rear/commit/c025226be56ded92e2f03120106afbb22ff25fd3
fixes this particular issue => closing it.
