### ISSUE TITLE
No information in default rear output

### ISSUE THREAD

**Issue by tcerna** [rear/rear#929]
* rear version (/usr/sbin/rear -V):
rear-1.17.2

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
RHEL-7.2 Server

* Brief description of the issue
There are no information about run of backup creation if user started rear with command `rear mkbackup` and others options (mkrescue, etc.). User would appreciate to see that ISO was created and path to it. Maybe more information.

* Example:

   No information about rear run.
```
# rear mkbackup
#
```

   Information about rear run in verbose mode, user can see what was done and path to output rescue image and backup. This mode is more talkative.
```
# rear -v mkbackup
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-rearclient.log
Creating disk layout
Creating root filesystem layout
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-rearclient.iso (111M)
Modifying local GRUB configuration
Copying resulting files to nfs location
Encrypting disabled
Creating tar archive '/tmp/rear.M58WbZYxasPHrZs/outputfs/rearclient/backup.tar.gz'
Archived 161 MiB [avg 7871 KiB/sec]OK
Archived 161 MiB in 22 seconds [avg 7513 KiB/sec]
#
```

* Expected result:

   Output between run default and verbose mode.

   At least what was created and place where it is saved (and there can be more information than I specified):
```
# rear mkbackup
Wrote ISO image: /var/lib/rear/output/rear-rearclient.iso (111M)
Creating tar archive '/tmp/rear.M58WbZYxasPHrZs/outputfs/rearclient/backup.tar.gz'
```
   And information that backup and rescue image was saved to server $IP_ADDRESS.

**Comment by jsmeix** [comment]
This is intended since version 1.11.0.

doc/rear-release-notes.txt reads:
<pre>
Version 1.11.0 (May 2011)
...
The rear command is by default quiet, which means
if you want the same behavior as in previous versions
you need to add the verbose option (-v) with the rear
command
</pre>

**Comment by jsmeix** [comment]
See also https://github.com/rear/rear/issues/934#issuecomment-234180457
