### ISSUE TITLE
Missing information about RSYNC using in man page

### ISSUE THREAD

**Issue by tcerna** [rear/rear#930]
* rear version (/usr/sbin/rear -V):
rear-1.17.2

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
RHEL-7.2 Server

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
```
# cat /etc/rear/local.conf 
OUTPUT=ISO
OUTPUT_URL="rsync://$IP_ADDRESS/mnt/rear"
BACKUP=RSYNC
```

* Brief description of the issue:

  In manual page is written that BACKUP_URL is necessary to specified when using BACKUP=NETFS, not for BACKUP=RSYNC. Copy&paste from man page:
```
When using BACKUP=NETFS you should provide the backup target location through the BACKUP_URL variable. Possible BACKUP_URL settings are:
```

But when I run `rear -v mkbackup`, error message is appeared:
```
ERROR: Missing BACKUP_URL=rsync://[USER@]HOST[:PORT][::]/PATH !
Aborting due to an error, check /var/log/rear/rear-rearclient.log for details
Terminated
```

* Current result:
```
# rear -v mkbackup
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-rearclient.log
ERROR: Missing BACKUP_URL=rsync://[USER@]HOST[:PORT][::]/PATH !
Aborting due to an error, check /var/log/rear/rear-rearclient.log for details
Terminated
```

* Expected result:

   There should be information about this necessity in man page and documentation.

**Comment by gdha** [comment]
Man page and default.conf were already updated. Still need to check the user docs.

**Comment by jsmeix** [comment]
I close it because it is fixed.
