### ISSUE TITLE
Missing dependency at Debian 8

### ISSUE THREAD

**Issue by heinlein-support** [rear/rear#940]
At Debian 8 they removed some stuff from the syslinux package and createt "isolinux" and "extlinux". At Open SuSE Build service you should add those packages as dependency for ReaR under Debian 8.

**Comment by jsmeix** [comment]
I do neither use Debian nor do I know how to make
packages for Debian so that I cannot help here.

But it seems you use Debian and therefore I ask you
to contribute what is missing for your purpose.

**Comment by heinlein-support** [comment]
Give me maintainer access to the rear project at OBS and I'll fix it in 10 seconds.

**Comment by jsmeix** [comment]
@heinlein-support 
with great pleasure I added you right now
as maintainer to
https://build.opensuse.org/project/users/Archiving:Backup:Rear

I very much appreciate you contribution to Relax-and-Recover!

**Comment by jsmeix** [comment]
@heinlein-support 
I don't know for sure but I think that packaging errors
usually need to be fixed in the rear source files in the
packaging/ directory: https://github.com/rear/rear/tree/master/packaging

I.e. I think you might need to fix it via a GitHub pull request
and perhaps not by changing files in the openSUSE build
service?

**Comment by gdha** [comment]
@heinlein-support could you please be so kind to prepare a small pull request with the fix?

**Comment by gdha** [comment]
@heinlein-support I still have no clue what was changed - will close it - if needed you can re-open it again with some input I can understand - thanks

**Comment by frediz** [comment]
Well, upstream Debian, the packaging has a dependency on isolinux and it builds fine.
I don't know how Open SuSE Build service works but I think you should rely on Debian's packaging which I did and support.
Let me know if you can re-use that.

**Comment by jsmeix** [comment]
I assume this issue is fixed via
https://github.com/rear/rear/pull/1599
at least the "isolinux" part...
