### ISSUE TITLE
In recovery system "reboot" no longer works with newest systemd (e.g. SLE12 and FC24)

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#953]
Current rear GitHub master
with latest Git commit 01f35154b35de0d4829cfe2a5502d4f839c27d45
(i.e. with https://github.com/rear/rear/issues/944 fixed)
on SLES12-SP2-beta5.

In the recovery system after successful "rear recover"
"reboot" does not work:
<pre>
RESCUE g62:~ # rear -d -D recover
...
Finished recovering your system. You can explore it under '/mnt/local'.

RESCUE g62:~ # reboot
Failed to start reboot.target: Transaction contains conflicting jobs 'stop' and 'start' for reboot.service. Probably contradicting requirement dependencies configured.
Failed to talk to init daemon.
</pre>

Easy workaround:
<pre>
RESCUE g62:~ # umount -a
umount: /sys/fs/cgroup/systemd: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: /sys/fs/cgroup: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: /run: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: /dev: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
umount: /: not mounted

RESCUE g62:~ # reboot -f
Rebooting.
</pre>

I guess something related to systemd needs to be enhanced
in the rear recovery system to match newest fancy systemd stuff.

Because there is an easy workaround there is no time pressure
to get this done for Rear version 1.19 and therefore I set
the milestone to "Rear future".

**Comment by jsmeix** [comment]
Happens also on SLES12-SP2-RC1
=> probably happens on all SLE12-SP2

**Comment by GreasyMonkee** [comment]
Hi,

Identical problem in Fedora FC24, was OK in FC23 & 22.

Cheers,
GM.

**Comment by jsmeix** [comment]
@GreasyMonkee 
thanks for your posting because it shows that this issue is not
because of SUSE-specific fancy systemd changes but
likely a generic isssue with newer systemd versions.

@gdha 
I added you as assignee here mainly FYI.

**Comment by gdha** [comment]
@GreasyMonkee @jsmeix Just did a test with a fresh Fedora24 without any recover issues. Reboot went fine without any systemd error as well. Sorry - cannot reproduce your issue.

**Comment by jsmeix** [comment]
@gdha 
no need to be sorry when it works for you!

I guess that it sometimes works and sometimes fails
is because with systemd  booting and shutdown does
no longer happen in a basically hardcoded way
(as it was with SysVinit).
In particular systemd has no longer basically hardcoded
dependencies.

The following is a nice workaround for me
in the rear recovery system:
<pre>
RESCUE g136:~ # alias reboot='umount -a ; sleep 10 ; reboot -f'

RESCUE g136:~ # type -a reboot
reboot is aliased to `umount -a ; sleep 10 ; reboot -f'
reboot is /bin/reboot

RESCUE g136:~ # reboot
...
Rebooting.
</pre>

FYI:

On my SLES12-SP2-RC2 system:
<pre>
g136:~ # type -a reboot
reboot is /sbin/reboot

g136:~ # ls -l /sbin/reboot
lrwxrwxrwx 1 root root ... /sbin/reboot -> /usr/bin/systemctl

g136:~ # ls -l /usr/bin/systemctl
-rwxr-xr-x 1 root root 692208 ... /usr/bin/systemctl

# rpm -qf /usr/bin/systemctl
systemd-228-114.4.x86_64
</pre>

In the rear recovery system that was generated
on that SLES12-SP2-RC2 system by "rear mkbackup":
<pre>
RESCUE g136:~ # type -a reboot
reboot is /bin/reboot

RESCUE g136:~ # type -a systemctl
systemctl is /bin/systemctl

RESCUE g136:~ # ls -li /bin/systemctl
6638 -rwxr-xr-x 1 root root 692208 Aug 26 20:33 /bin/systemctl

RESCUE g136:~ # ls -li /bin/reboot   
6529 -rwxr-xr-x 1 root root 692208 Aug 26 20:33 /bin/reboot

RESCUE g136:~ # diff -s /bin/reboot /bin/systemctl
Files /bin/reboot and /bin/systemctl are identical
</pre>

By the way:
We could save 692208 bytes in the rear recovery system
by linking those indentical files.

**Comment by gdha** [comment]
@jsmeix perhaps we could replace the `/bin/reboot` with a script containing `systemctl --force reboot` when systemd is in place?

**Comment by jsmeix** [comment]
@gdha before doing such a hardcoded behavioural change
of how "reboot" normally works, I would wait some more time
until hopefully more information could be provided
why "reboot" sometimes fails with
<pre>
Failed to start reboot.target: Transaction contains conflicting
jobs 'stop' and 'start' for reboot.service. Probably contradicting
requirement dependencies configured.
Failed to talk to init daemon.
</pre>
so that we hopefully could solve the actual root cause.
I think in the meantime using the workaround
<pre>
# umount -a ; reboot -f
</pre>
is self-evident and easy to do.

**Comment by jsmeix** [comment]
Stupid me!
I noticed right now that both the SLES12-SP2
/usr/lib/systemd/system/systemd-reboot.service
and the rear
usr/share/rear/skel/default/usr/lib/systemd/system/reboot.service
contain
<pre>
ExecStart=...systemctl --force reboot
</pre>
i.e. the default behaviour is already an enforced reboot.

**Comment by jsmeix** [comment]
Plain "reboot" works for me on SLE12-SP2 when I remove
in /usr/lib/systemd/system/reboot.service
the whole "[Unit]" section so that it only is
<pre>
[Service]
Type=oneshot
ExecStart=/bin/systemctl --force reboot
</pre>

But I think there is a reason for the "[Unit]" section
<pre>
[Unit]
Description=Reboot
DefaultDependencies=no
Requires=shutdown.target umount.target final.target
After=shutdown.target umount.target final.target
</pre>
but I am not at all a sufficient systemd expert
to know the reasons behind.

But e.g. "shutdown" also does not work for me on SLE12-SP2:
<pre>
RESCUE g136:~ # shutdown
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory

RESCUE g136:~ # shutdown -r now
Failed to start reboot.target: Transaction contains conflicting
jobs 'stop' and 'start' for reboot.target. Probably contradicting
requirement dependencies configured.
Failed to talk to init daemon.

RESCUE g136:~ # shutdown -P now
Failed to start poweroff.target: Transaction contains conflicting
jobs 'stop' and 'start' for shutdown.target. Probably contradicting
requirement dependencies configured.
Failed to talk to init daemon.
</pre>

From my curent point of view I like most
<pre>
# umount -a ; reboot -f
</pre>

**Comment by jsmeix** [comment]
One of our (i.e. SUSE's) systemd maintainers told me
that the root cause is probably that dbus is not usable
in the rear recovery system and that with
"systemctl --force reboot/poweroff/halt" no dbus is used
so that it works this way.

**Comment by jsmeix** [comment]
I do not want to fiddle about dbus so that
I start to like the idea to replace in the rear recovery system
/bin/reboot /bin/halt /bin/poweroff /bin/shutdown
by scripts that basically do
<pre>
umount -a
systemctl --force reboot
</pre>
<pre>
umount -a
systemctl --force halt
</pre>
<pre>
umount -a
systemctl --force poweroff
</pre>
For /bin/shutdown there is no "systemctl --force shutdown"
so that probably a more elaborated script is need
that calls by default /bin/poweroff but when
'-r --reboot' is specified it calls /bin/reboot and when
'-H --halt' is specified it calls /bin/halt.

**Comment by jsmeix** [comment]
https://github.com/rear/rear/pull/1011is a first attempt
to make reboot halt poweroff and shutdown work simpler
and more fail-safe.

**Comment by jsmeix** [comment]
@GreasyMonkee 
could you test my new
63_simplify_systemd_reboot_halt_poweroff_shutdown.sh
script whether or not it also makes it work for you?

To add it to your currently installed rear, download it from
https://raw.githubusercontent.com/jsmeix/rear/simplify_systemd_reboot_halt_poweroff_shutdown_issue953/usr/share/rear/build/GNU/Linux/63_simplify_systemd_reboot_halt_poweroff_shutdown.sh

Then install it as
/usr/share/rear/build/GNU/Linux/63_simplify_systemd_reboot_halt_poweroff_shutdown.sh

Then run "rear mkbackup" or "rear mkrescue", boot the new
created rear recovery system and try out if in the rear recovery
system reboot halt poweroff shutdown also "just work" for you
(preferably after a "rear recover" when things are mounted).

**Comment by GreasyMonkee** [comment]
Hi, I am not able to test it as I am overseas for the next month, will be
late October at earliest before I have access to my server.

Sorry that I cannot assist at this time, but shall test on my return.

Cheers,
GM.

**Comment by jsmeix** [comment]
@GreasyMonkee 
many thanks for your prompt reply!
This way I know that I do not need to wait for your feedback.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1011 merged
this issue should be fixed.
