### ISSUE TITLE
SLES12 SP1 network device name not changed in recover mode

### ISSUE THREAD

**Issue by gozora** [rear/rear#958]
* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.18 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): SUSE Linux Enterprise Server 12 SP1
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): Not needed
* Brief description of the issue: udevadm trigger does not rename network devices
* Work-around, if any:
`udevadm trigger --action=add && systemctl daemon-reload`

Hi guys, I was poking around a bit around issue #951, and during very early stage I've run into interesting behavior. Once recovery media boot was near to finish, _55-migrate-network-devices.sh_  lunch asked me to remap old network device to new one. It looks like this action finished successfully but it doesn't. 

The thing is that after _/etc/udev/rules.d/70-persistent-net.rules_ was modified and **udevadm trigger** was called, my network device name was not changed. After a bit of playing around, following worked for me:
```
udevadm trigger --action=add
systemctl daemon-reload
```
I'm not sure now if this is related to SLES12 or systemd, so if you have some distro using systemd, could you check if by changing _/etc/udev/rules.d/70-persistent-net.rules_ and calling **udevadm trigger** works for you?

Thanks

V.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/959 merged
this issue should be fixed.

@gozora 
many thanks for your continuous improvements!

**Comment by gozora** [comment]
You are always welcome!
@jsmeix I love "The Enterprise Way" how you closed this issue :-D
Anyhow, I can confirm same behavior on Debian with systemd so this fix should indeed help.
