### ISSUE TITLE
ISO image generation requirment

### ISSUE THREAD

**Issue by yin747** [rear/rear#971]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.17.2 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
$ cat /etc/rear/site.conf
OUTPUT=ISO
OUTPUT_URL=file:///fsbackup/
BACKUP=NETFS
BACKUP_URL=iso:///fsbackup/
NETFS_KEEP_OLD_BACKUP_COPY=
TMPDIR="/fsbackup"
export TMPDIR
ISO_MAX_SIZE=3500

$ cat /etc/rear/local.conf
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}"
 '/dev' '/media' '/mnt' '/proc' '/sys' '/tmp' '/run' '/var/tmp' '/var/crash' '/fsbackup' '/linuxbackup' )
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}"
 "fs:/proc/sys/fs/binfmt_misc" "fs:/sl_test" "fs:/seed_7" "fs:/fsbackup" )
````
* Brief description of the issue
I would like to make ISO for backup/restore operations. When I use above settings, the error was returned, because of /var filesystem full. I found that the ISO file was generated under `/var/lib/rear/output`. That is expected behavior, even through I define `OUTPUT_URL=file:///fsbackup/`?
````
### command output ###
# $  ls -l /var/lib/rear/output/rear-cdctst1r_01.iso
-rw------- 1 root root 2138996736 Aug 18 11:30 /var/lib/rear/output/rear-cdctst1r_01.iso

### detail log ###
 72.91% done, estimate finish Thu Aug 18 11:30:32 2016
 73.26% done, estimate finish Thu Aug 18 11:30:33 2016
genisoimage: No space left on device. cannot fwrite 32768*1
2016-08-18 11:30:28 ERROR: Could not create ISO image rear-cdctst1r_01.iso (with /bin/mkisofs)
=== Stack trace ===
Trace 0: /usr/sbin/rear:251 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:22 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:70 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:31 Source
Trace 4: /usr/share/rear/output/ISO/Linux-i386/81_prepare_multiple_iso.sh:55 source
Trace 5: /usr/share/rear/lib/_input-output-functions.sh:132 StopIfError
Message: Could not create ISO image rear-cdctst1r_01.iso (with /bin/mkisofs)
===================
2016-08-18 11:30:28 Running exit tasks.
rmdir: removing directory, '/fsbackup/rear.E3ipV3u4BfHsVrw/outputfs'
2016-08-18 11:30:28 Finished in 430 seconds
2016-08-18 11:30:28 Removing build area /fsbackup/rear.E3ipV3u4BfHsVrw
rmdir: removing directory, '/fsbackup/rear.E3ipV3u4BfHsVrw'
2016-08-18 11:30:29 End of program reached
````

**Comment by feichashao** [comment]
I tried
~~~
OUTPUT_URL=null
ISO_DIR=/expect_output/output/
~~~
and then rear would not put iso in `/var/lib/rear/output`, instead rear put iso to `/expect_output/output/` directly.

**Comment by gdha** [comment]
See also issue #734 - however, still haven't found the time to implement this feature.
@feichashao Yes - the work-around you're using seems to do the job for the moment.

**Comment by gdha** [comment]
@feichashao as your work-around is sufficient for the moment and  issue #734 is still open for the same we can close this case.
