### ISSUE TITLE
cryptsetup fails on restore due to missing cracklib dictionaries

### ISSUE THREAD

**Issue by nikbarron** [rear/rear#972]
Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): CentOS 7 (reports as RedHatEnterpriseServer/7)
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=cifs://swss-nas3/REAR_Backups
BACKUP_OPTIONS="cred=/etc/rear/cifs"

* Brief description of the issue

There is an issue with restoring a system that uses LUKS encryption, which fails as shown in the attached screenshot with "An error occurred during layout recreation" immediately after the first password prompt to recreate the LUKS volume:

![rear-001](https://cloud.githubusercontent.com/assets/21100372/17769059/d88ed8c6-652e-11e6-823a-59942016fcb0.jpg)

Digging into this further I found that the issue is caused by the password quality check on cryptsetyp, which requires the cracklib dictionaries, which appear to be missing from the restore media:

![rear-002](https://cloud.githubusercontent.com/assets/21100372/17769060/d88fb69c-652e-11e6-8593-78a8c91752c8.jpg)

The system the ISO was generated from has the cracklib packages installed, so I guess the ISO creation process needs to be amended to include them?

* Work-around, if any

There's a simple workaround, edit the restore script and add the --force-password switch to the cryptsetup command(s), which skips the password quality check. The restore process then runs fine and restores as expected.

**Comment by jsmeix** [comment]
In general when something special is not automatically
included in the rescue/recovery system, you can
specify whatever you want to get it included
by using in /etc/rear/local.conf things like
<pre>
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" progam1 program2 )
COPY_AS_IS=( "${COPY_AS_IS[@]}" file1 file2 directory1 directory2 )
</pre>
for an example see
/usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
and in general for what you can configure
see /usr/share/rear/conf/default.conf

**Comment by gdha** [comment]
Issue #679 is about the same - see the solution provided - it will be included in 1.18
If this is sufficient for you then close this issue please?

**Comment by nikbarron** [comment]
Hi,

Sure, it was more of a heads-up, thought it should probably include the cryptlib by default as it includes LUKS support.

Happy to close, awesome work on REAR btw, off to donate now!

**Comment by gdha** [comment]
@nikbarron Thank you for your kind donation - it makes my day ;-)

**Comment by nikbarron** [comment]
You’re most welcome!

**Comment by jsmeix** [comment]
@nikbarron 
only FYI if you like to try out the currently
newest rear GitHub master code:

In general regarding how to test the currently
newest rear GitHub master code:
Basically "git clone" it into a directory and
then run rear from within that directory.
<pre>
# git clone https://github.com/rear/rear.git

# cd rear

# vi etc/rear/local.conf

# usr/sbin/rear -d -D mkbackup
</pre>

**Comment by nikbarron** [comment]
Thanks, will give that a try

Nik

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----
