### ISSUE TITLE
Bacula restore -> bconsole does not start -> No job control in this shell

### ISSUE THREAD

**Issue by e-it** [rear/rear#980]
Hello,

I tried to install the latest rear and created my first image using bacula as backupping-engine.

Now I started my created image and the procedure started fine.

But: If I come to the point where bconsole should be started - it is not started :-(

<img width="743" alt="napkin 24 08 16 10 31 01 pm" src="https://cloud.githubusercontent.com/assets/10261817/17946931/b61aecfa-6a4a-11e6-86d3-647b84114aea.png">

I'm getting the error "No job control in this shell" and if I open "bconsole", I always get "Connecting to director ... " and the shell is there again.

Any ideas?

**Comment by gdha** [comment]
@e-it Did you ping the bacula director server before the restore? It could be a network issue.

**Comment by jsmeix** [comment]
I know nothing at all about Bacula/bconsole but is seems
https://github.com/rear/rear/issues/996
is related.
