### ISSUE TITLE
Change network-settings on rescue-boot

### ISSUE THREAD

**Issue by e-it** [rear/rear#981]
* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): CentOS release 6.7 (Final)

Is it possible to change the network-settings on boot of the rescue-image? I would like to try the restore with bacula on a local VM but the network-configuration contains an IP that does not belong to my network so the network is unreachable.

**Comment by gdha** [comment]
@e-it sure - just like you do on a production system you can use `ip` or `ifconfig` to modify your network settings.

**Comment by e-it** [comment]
Okay, so I got it to work doing:

```
ifconfig eth0 192.168.10.123 netmask 255.255.255.0 up
ip route add 192.168.10.1 dev eth0
ip route add default via 192.168.10.1
```

But: Now I see that there is only one name server (127.0.0.1) - the director's host name can not be resolved this way. Is there any way to get a public name server into the config?

**Comment by jsmeix** [comment]
@e-it 
when you use the newest GitHub master code
there is support for NETWORKING_PREPARATION_COMMANDS
so taht you can define in etc/rear/local.conf whatever
commands you need for networking setup in the
recovery system, see
https://github.com/rear/rear/blob/dev/usr/share/rear/conf/default.conf
how NETWORKING_PREPARATION_COMMANDS
is meant to work and for some examples how it works see
https://github.com/rear/rear/pull/960#issuecomment-239448861

**Comment by gdha** [comment]
@e-it You can edit the `/etc/resolv.conf` file as well, or use @jsmeix suggestion.

**Comment by e-it** [comment]
Hm, but if I edit the resolv.conf I would have to restart the networking - and /etc/init.d does not contain a networking-init-script or am I wrong?

**Comment by didacog** [comment]
@e-it changes in /etc/resolv.conf should take effect immediately. No need to restart networking.

regards,

**Comment by gdha** [comment]
@e-it can this issue be closed?

**Comment by e-it** [comment]
Yes, thanks. The changes in `/etc/resolv.conf` do not take effect immediately, but it's possible to edit `/etc/hosts`
