### ISSUE TITLE
Rear local.conf Questions

### ISSUE THREAD

**Issue by John-Leone** [rear/rear#994]
Hello,
I was looking through the documentation but couldn’t find info on these questions..
For the local.conf file:
1.	Can the “BACKUP_URL=” if set to BACKUP=NETFS  use HTTP?
2.	For “BACKUP_PROG_EXCLUDE=” Is it possible to include only the filesytems to be backed up and exclude everything else?

Relax-and-Recover 1.17.2 / Git
Red Hat Enterprise Linux Server release 6.7 (Santiago)

Current local.conf
OUTPUT=ISO
OUTPUT_URL=nfs://xxx.xxx.xxx.xxx/dbar
BACKUP=NETFS
BACKUP_URL=nfs://xxx.xxx.xxx.xxx/dbar
SSH_ROOT_PASSWORD="xxxxxx"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash')
NETFS_KEEP_OLD_BACKUP_COPY=

Thanks,
John

**Comment by gdha** [comment]
@John-Leone The man page should explain most of it. If something is unclear after reading the man page then come back to this issue and tell us about it. If the docs are not clear please tell us what is confusing you?

**Comment by John-Leone** [comment]
Thank you.. 
Found what I was looking for in /usr/share/rear/conf/default.conf.
I will test BACKUP_PROG_INCLUDE=( ) & SSHFS and let you know if I have questions.

**Comment by jsmeix** [comment]
According to https://github.com/rear/rear/issues/994#issuecomment-247429237 "Found what I was looking for"
I close it - at least for now.

@John-Leone 
I think you can still post comments here even when it is closed
or you can re-open it if needed.
But when you have subsequent separated issues better submit
each of them as a new separated GitHub issue.
