### ISSUE TITLE
rear recover using bconsole

### ISSUE THREAD

**Issue by Naw4k** [rear/rear#996]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:
- rear version (/usr/sbin/rear -V):
  1.17.2
- OS version (cat /etc/rear/os.conf or lsb_release  -a):
  RHEL6 & 7
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
  OUTPUT=PXE
  BACKUP=BACULA
  CLONE_ALL_USERS_GROUPS=y
  OUT_URL=nfs://<our server>
  OUTPUT_PREFIX=`hostname`
- Brief description of the issue
  As you can see we use Rear in combination with bacula backup tool. We are facing the problem that rear needs the bacula console to work properly. But an installed bacula console on a client allows to restore files from any other host. This is a big security issue we are facing.
  Question: is there a way in rear to disable the bconsole check so that we can uninstall the console on each client (recovery should be done only on the server).
- Work-around, if any
  I played around with the rear bacula preq. shell scripts but it ended up not working doing a restore.
  Any suggestions?

**Comment by gdha** [comment]
What you probably want is a mechanism to push the backup to the client, right? Instead of the client doing the pull?

**Comment by Naw4k** [comment]
Correct. 
Our first idea was to manipulate the rear scripts and remove the bacula-console check. But it ended up that rear was not able to create the filesystem layout (during restore process)

**Comment by gdha** [comment]
As no request came for sponsoring we are closing this request and keep it on the radar to be re-opened if requested
